### ISSUE TITLE
[feature request] Add Zotero and Mendeley profiles to OSF social profile options

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#1002]
From @AndrewSallans in CenterForOpenScience/osf#957:

> Per user request on Twitter, add Zotero. Also, as it is similar, add Mendeley.
> 
> Also am interested in how much would be required to implement these connections with user-driven OAuth, and what value we might get in growing OSF via those connections (ie. push all of a user's public OSF projects to their Mendeley and Zotero profiles, allow for auto Twitter/Facebook/LinkedIn, tracking on Impactstory, etc.).

**Comment by lyndsysimon** [comment]
I'll be working with both Zotero and Mendeley as addons, so I'm self-assigning.

These will be my primary tasks over the next two months, with an expected go-live date in February.

**Comment by lbanner** [comment]
Thanks @lyndsysimon

**Comment by lyndsysimon** [comment]
Please remove me as assignee; I can't seem to do so.
