### ISSUE TITLE
[feature request] service health dashboard

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#1003]
From @AndrewSallans (moved from CenterForOpenScience/osf#578): 

> For improved communication of service availability and dependencies to end users, and ourselves, (ie. add-on connections), it would be good to add a service health dashboard. This would regularly ping services that the OSF draws upon and show whether they are up or down.

> Example: http://status.aws.amazon.com/

@lyndsysimon commented: 
> I really like Heroku's status dashboard as well. In particular, it shows a history of issues and responses.

**Comment by brianjgeiger** [comment]
From my duplicate issue: "An added flourish would be to have a status widget available everywhere (say, in the navbar) that would be color coded to indicate whether things are good, good but with minor issues, or bad, and they could click it to see the status page."

And maybe a "report a problem with X service" if we think it's working but someone else doesn't. This may just indicate individual users' internet problems sometimes, but it may also give us forewarning of a problem in other cases.
