### ISSUE TITLE
[UI] Formatting suggestions for user profiles 

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#1004]
From @jlcohoon (moved from CenterForOpenScience/osf#590): 
> For the updated public profiles, I would suggest the following formatting and content changes:

>1. Remove the user's name below the first HR, it is redundant considering it's directly above
>2. Remove the lower HR that is directly above the project list; add a 40px bottom margin instead.
>3. For the social tab, remove the top border for .table>tbody>tr>td that shows up above each social >media value
>4. When no content has been entered for a tab display "USER FIRST NAME has not provided any >information for this section." Add an italic font style and a 20px bottom margin to this. For the social tab, >this will mean getting rid of the well. For the employment and education tabs, this will mean not >displaying the empty tables.
>5. Reorganize the employment/education views so that the information appears in two unlabeled >columns. On the left, display the date range for the position. On the right, display the position title in >bold font, then the location then the department. See the image below for an example.
![screen shot 2014-05-29 at 4 31 26 pm](https://cloud.githubusercontent.com/assets/4965832/3123539/e8d5ffec-e773-11e3-8dee-b9cbfad7d7dd.png)

**Comment by caneruguz** [comment]
@samanehsan why is this issue deferred? These are good suggestions, especially the ones about the social, employment, education tabs. 

Also @jlcohoon has put two quite unrelated issues into this one, the second is no longer an issue I believe.

**Comment by lbanner** [comment]
I pulled the "defer" tag -- But this one needs consideration as to value of putting into OSF product backlog. I think -- new approach to items such as these. Ping @erinmayhood on this one. TY.

**Comment by samanehsan** [comment]
@caneruguz, this issue was deferred back when we decided to prioritize github issues that were bugs over ones that were enhancements to existing functionality. Now, it's priority might be different but that's up for discussion as @lbanner mentioned.

**Comment by samanehsan** [comment]
Also just to note, this one has been fixed on production:

>1. Remove the user's name below the first HR, it is redundant considering it's directly above

**Comment by caneruguz** [comment]
So I'm trying to remove as many issues as can be done and this one is not really a bug but it's related to redesign. Also some changes have been made in staging that address issues of header title continuty and navigation current item being higlighted. In other words I think we should close this from the issue tracker and move it to somewhere else as ideas to be developed into a proposal later for the profile page redesign. 

@erinmayhood @nanchen47 @samanehsan

**Comment by samanehsan** [comment]
Sounds good to me @caneruguz!

**Comment by lbanner** [comment]
Onboard --
