### ISSUE TITLE
[discussion] remove points and number of projects from user profile?

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#1007]
From @jlcohoon (moved over from CenterForOpenScience/osf#591): 

> I'd suggest removing the points and number of projects from users profiles. 
Activity points are not explained anywhere and don't affect anything.
The number of projects and number of public projects is informative, but I think that it highlights how many private projects a user has. We have been displaying that a private component exists when someone views a project that isn't theirs, but I think that highlighting the difference between the total number of projects and number of public projects in a person's profile is unnecessary.
All in all, I think the information doesn't provide anything for users and should be left out.

**Comment by erinmayhood** [comment]
User profile redesign proposal is moving forward and will not have this.
