### ISSUE TITLE
[addons framework][dev] Suggestion: don't lowercase config options

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#1011]
From @sloria in CenterForOpenScience/osf#269: 

>Turning figshare.MAX_FILE_SIZE into node_settings.config.max_file_size can be quite confusing for >anyone reading the addon code.

**Comment by sloria** [comment]
Closing this. On further consideration, I don't think my proposed alternative is necessarily better than the status quo.
