### ISSUE TITLE
[UI][enhancement] Detect Child Components as Deleting Project

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#1019]
From @caneruguz in CenterForOpenScience/osf#668:

> At the project Settings page when user wants to delete a project there is a description that notes the child components need to be deleted. During BITSS this came up as an issue where the user did not pay attention to the text and concluded that the project can't be deleted. If the user bypasses this note and goes straight to delete project button they have to enter the code before they find out this can't be done. 
> 
> To avoid this problem an enhancement to this setting could be to detect whether the project has child elements and if so,  disable delete project button and wrap the text into a warning box as well as giving the user a link to go to components directly. 
> 
> Also entering the code can be combined into the page without opening another modal window into the page itself. 

![screen shot 2014-06-23 at 12 03 27 pm](https://cloud.githubusercontent.com/assets/1314003/3360151/eff8e46c-faef-11e3-8c68-7e9aa95601b0.png)

**Comment by jlcohoon** [comment]
Just got user feedback related to this issue (that I agree with):
"I sometimes show my students how to create from a template, and I run a test. If I have to delete the project thereafter, I have to delete every single subcomponent. Gets a bit high on time investment after a while. It would be great to just be able to delete from the dashboard right away."

I'd suggest that in Caner's proposed updated dialogue box, that each component is listed there and the user clicks each one to confirm deletion. This way you don't have to visit many components to delete a project.

**Comment by sloria** [comment]
We no longer require the user to delete all components. Closing
