### ISSUE TITLE
[feature request]  View previous versions of wiki pages

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1020]
Moved from https://github.com/CenterForOpenScience/centerforopenscience.org/issues/105

From @mambocab : 

> On wiki pages on the OSF, I can view diffs between versions, but not old versions of pates. The wiki addon's routes.py would indicate that the same url, but with compare replaced with version, would serve the a particular version, but the request doesn't resolve.

**Comment by samanehsan** [comment]
Closing, since users can now view previous versions of wiki pages.
