### ISSUE TITLE
[Discussion] Why does the button to post a comment in the comment pane say "Save"?

### ISSUE THREAD

**Issue by huangginny** [CenterForOpenScience/osf.io#1032]
![screen shot 2014-09-30 at 9 31 42 am](https://cloud.githubusercontent.com/assets/8628591/4458796/29ffc1cc-48a6-11e4-9309-e9789e6c156d.png)

This is a minor thing. Unless I'm mistaken, the comment pane works like a "chatroom". However, the first time I try to use it, I am very confused about how it works. The "save" button gives me a feeling that I am saving a note or some important info, not sharing thoughts with others. I would suggest using "Comment" or "Post" instead.

**Comment by samanehsan** [comment]
The button now says "comment" instead of "save":   
![screen shot 2015-07-23 at 12 13 05 pm](https://cloud.githubusercontent.com/assets/6414394/8855659/5f01e7de-3134-11e5-81a0-65c02448257b.png)
