### ISSUE TITLE
[wiki] Renaming wiki "home" page moves its content to a new page

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1043]
### Steps
- Add some content to a wiki "home" page.
- While viewing the wiki "home" page, click "home" to pop up the editable input.  Change its name.
### Expected
- The "home" page name is not editable
### Actual
- A new page is created with the new name
- All the content from the home page is now on the new page.
- The "home" page content is empty

**Comment by petertwise** [comment]
I know this is marked as closed, but I'm still seeing this behavior in 2023. If I change the name of "Home" it just makes a new page with that name and then "Home" with the default content "Welcome to the [repo-name] wiki!" pops up again. Any tips for making a homepage that's got a title other than "Home"? Or are we just stuck with that permanently?
