### ISSUE TITLE
[github] [ui] Confusing button order in Github addon settings

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1045]
The "Create Repo" button is closer to the repo selection box than the "Submit" button that saves the selection. This opens potential for user error.

![osf___addons_example_settings](https://cloud.githubusercontent.com/assets/2379650/4506115/4914e438-4aff-11e4-8924-510fa7f3f412.png)

I propose switching the positions of the two buttons.

**Comment by nanchen47** [comment]
https://github.com/CenterForOpenScience/osf/pull/1189 never got merged in. The new full request for this fix is https://github.com/CenterForOpenScience/osf.io/pull/1305

**Comment by caneruguz** [comment]
@nanchen47 it looks like this fix got cut with other changes but this issue is still important to address. I recommend changing the priority and labeling Ready to get someone to claim this.

**Comment by chennan47** [comment]
This is included in @kushG 's https://github.com/CenterForOpenScience/osf.io/pull/1305. That pull request will need someone to get it updated to get merged in since it fixes a few problems with github addon. What about close this issue and open a new one about update that pr? @GaryKriebel @lbanner

**Comment by sloria** [comment]
I don't think we need to merge in that refactor just to make this minor change. I recommend someone just change the order and update that PR in the long run.

**Comment by erinmayhood** [comment]
fixed.
