### ISSUE TITLE
Pull request to fix OSF's rendering of jamovi files

### ISSUE THREAD

**Issue by jonathon-love** [CenterForOpenScience/osf.io#10505]
hi,

could someone take a look at this PR?

https://github.com/CenterForOpenScience/modular-file-renderer/pull/369

with thanks

jonathon

**Comment by felliott** [comment]
This has been released!

**Comment by cslzchen** [comment]
Closing this issue, fix has been released in https://github.com/CenterForOpenScience/modular-file-renderer/tree/24.0.0
