### ISSUE TITLE
[API] with /v2/users/ , User information can get from no authenticatd user.

### ISSUE THREAD

**Issue by ebijun** [CenterForOpenScience/osf.io#10629]
- https://github.com/CenterForOpenScience/osf.io/blob/develop/api/users/views.py#L149
<pre>
class UserList(JSONAPIBaseView, generics.ListAPIView, ListFilterMixin):
    """The documentation for this endpoint can be found [here](https://developer.osf.io/#operation/users_list).
    """
    permission_classes = (
        drf_permissions.IsAuthenticatedOrReadOnly,
</pre>
It seems "No Authenticated User" can get List all users with API.
- https://developer.osf.io/#operation/users_list

Is it true? or it should be "IsAuthenticated" only?

**Comment by Johnetordoff** [comment]
I’m not precisely sure what you’re asking. It’s an intentional decision to allow unauthenticated to access that view. This to allow people or organizations who don’t have an OSF account to easily access that information.

**Comment by ebijun** [comment]
I see. Thanx for your comment.

My Summary:
1. API: /v2/users/me : it used in "My Project" to list Projects.
- AnonymousUser can't get userlist.
- key=me |key=current_user.id can get userlist.

https://github.com/CenterForOpenScience/osf.io/blob/develop/api/users/views.py#L126-L137
<pre>
        if isinstance(current_user, AnonymousUser):
            if key == 'me':
                raise NotAuthenticated

        elif key == 'me' or key == current_user._id:
            return get_object_or_error(
OSFUser.objects.filter(id=current_user.id).annotate(default_region=F('addons_osfstorage_user_settings__default_region___id')).exclude(default_region=None),
                request=self.request,
                display_name='user',
            )

        obj = get_object_or_error(OSFUser, key, self.request, 'user')
</pre>

2. API: /v2/users/ users_list
https://developer.osf.io/#operation/users_list
- Anonymous User can get all user information(guid,Name,affriation).
- Authenticate user can get all user information(guid,Name,affriation).

https://github.com/CenterForOpenScience/osf.io/blob/develop/api/users/views.py#L145C1-L153C1
<pre>
class UserList(JSONAPIBaseView, generics.ListAPIView, ListFilterMixin):
    """The documentation for this endpoint can be found [here](https://developer.osf.io/#operation/users_list).
    """
    permission_classes = (
        drf_permissions.IsAuthenticatedOrReadOnly,
        base_permissions.RequiresScopedRequestOrReadOnly,
        base_permissions.TokenHasScope,
    )
</pre>

if I wan't to block all user information(guid,Name,affriation) from anonymous access,
<pre>
    permission_classes = (
        drf_permissions.IsAuthenticated,
        base_permissions.RequiresScopedRequest,
        base_permissions.TokenHasScope,
    )
</pre>
