### ISSUE TITLE
[wiki] Version Timestamp in history is 4 hrs ahead

### ISSUE THREAD

**Issue by kushG** [CenterForOpenScience/osf.io#1065]
<h3> Steps </h3>

1. Go to a wiki page of a project.
2. Make changes to that page & hit 'Save'
3. Click History to check the changes.
4. Timestamp of the new version created is 4 hrs ahead

![screen shot 2014-10-08 at 2 24 23 pm](https://cloud.githubusercontent.com/assets/8779995/4564710/b0f1320a-4f19-11e4-96e0-732e1e4194c8.png)

<h3> Expected </h3>

Timestamp should display the time when the changes were made.

<h3> Actual </h3>
Timestamp displayed is 4 hrs ahead.

**Comment by brianjgeiger** [comment]
This is no longer an issue, as wiki versions do not show metadata.
