### ISSUE TITLE
[production] [ui] [comments] Enter key does not submit abuse report

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1083]
Minor UI bug in the comment pane:

### Steps

- Click the Report Abuse icon on another user's comment
- Enter some text in the description field
- Press the Enter key.

### Expected

- The abuse report was submitted

### Actual

- The page refreshes

![osf___addons_testing_-__private_browsing_](https://cloud.githubusercontent.com/assets/2379650/4581985/bd7caaec-4fe4-11e4-9ae6-c0720e428a24.png)

**Comment by samanehsan** [comment]
@nanchen47, why was this issue closed? It's still a problem on staging & production.

**Comment by lbanner** [comment]
Yeah -- this is still pending w/ @huangginny 's fix -- I reopened -- TY

**Comment by samanehsan** [comment]
This is fixed on production now
