### ISSUE TITLE
[feature request] Limit numbers of "levels of replies" in the comment pane

### ISSUE THREAD

**Issue by huangginny** [CenterForOpenScience/osf.io#1085]
<h3>Steps</h3>
<ol>
<li>Hit the reply button to reply a comment in the comment pane.</li>
<li>Hit the reply button to reply to the comment you just commented</li>
<li>while you_do_not_feel_crazy_yet: Repeat step 2</li>
</ol>
<h3>Current result</h3>
At the end it gets frustrating...
![screen shot 2014-10-09 at 3 10 36 pm](https://cloud.githubusercontent.com/assets/8628591/4582479/f2add7aa-4fe8-11e4-8c8b-4daf363dbcb3.png)
![screen shot 2014-10-09 at 3 10 23 pm](https://cloud.githubusercontent.com/assets/8628591/4582481/f4d636e4-4fe8-11e4-8acc-3a555e0ae3a7.png)
<h3>Suggestion</h3>
Limit the "level" of reply to a certain number. Wordpress.com does 3.
This is from my word press blog... I can't reply to the "Test" comment
![screen shot 2014-10-09 at 3 16 40 pm](https://cloud.githubusercontent.com/assets/8628591/4582511/2073de5a-4fe9-11e4-8b7c-7477a562f10f.png)

**Comment by nanchen47** [comment]
@samanehsan is this problem going to be addressed in https://github.com/CenterForOpenScience/osf.io/pull/1762

**Comment by lbanner** [comment]
I believe it will -- @huangginny 's code handles this with the option to go to the full discussion page.

**Comment by erinmayhood** [comment]
@lbanner This issue will be addressed with the commenting release. I believe this can close.

**Comment by lbanner** [comment]
:+1:
