### ISSUE TITLE
Re-arranging widgets in Statistics: cannot immediately move a widget to the bottom

### ISSUE THREAD

**Issue by huangginny** [CenterForOpenScience/osf.io#1087]
Minor UI bug. This happens on both staging and production.
<h3>Steps</h3>
![screen shot 2014-10-09 at 4 06 05 pm](https://cloud.githubusercontent.com/assets/8628591/4583212/bc06ee2e-4fef-11e4-91cd-b86a743618bd.png)

Now, put "Visitors in Real Time" <strong>under</strong> "Keywords." You won't be able to reproduce this bug if you drag it elsewhere.

<h3>Expected</h3>

Dashes appear under "Keywords" as you are dragging the "Visitors in Real Time" towards that direction.
![screen shot 2014-10-09 at 4 06 05 pm](https://cloud.githubusercontent.com/assets/8628591/4583251/1bfd9e40-4ff0-11e4-8f82-363608c84021.png)

<h3>Actual</h3>
It does not immediately happen. You have to drag it to somewhere else (such as between "Visits overtime" and "Keywords"), see that a dashed rectangle appeared between them, and then drag down to see the dashes, and drop it.

**Comment by nanchen47** [comment]
You can only drag the widget to top but not bottom. Not sure if it is designed to be so or a bug @lyndsysimon thoughts?

**Comment by nanchen47** [comment]
Will be solved in the piwik enhancement. Thanks.
