### ISSUE TITLE
[staging & production] Anonymized links show GitHub username

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1090]
# Steps
1. Authorize GitHub for a project/component.
2. Select a repo and press Submit.
3. Create an Anonymous link to the project/component.
4. View project/component through anonymized link.

# Expected
All references to an individual should be anonymized.

# Actual
GitHub usernames are shown in the log. Confirmed with Saman that all GH logs begin with a user's GH username (followed by a slash and the repo name). Since GH usernames are commonly variants of a user's actual name, this is potentially a problem for anonymity. 
Anonymous link view:
![screen shot 2014-10-09 at 5 34 18 pm](https://cloud.githubusercontent.com/assets/5975444/4584585/1d993a82-4ffc-11e4-9a90-5fc1767f5d5e.png)

@chennan47, @sloria suggested I tag you here.

**Comment by GaryKriebel** [comment]
@nanchen47 is this still an issue?

**Comment by GaryKriebel** [comment]
Will defer this for now as there are complications in anonymizing all addons.  Language should be in the modal to alert the user that this may be an issue.

**Comment by nanchen47** [comment]
The language alert has already been added for the addons. Close for now.
