### ISSUE TITLE
[production][Add-on] Forking a project without GitHub authorization shows GitHub authentication warning

### ISSUE THREAD

**Issue by kushG** [CenterForOpenScience/osf.io#1093]
<h3> Steps </h3>

1. Go to Select Add-on in project Settings page & check GitHub.
2. Hit Submit. You should see Configure Add-Ons section below.
3. Under Configure Add-ons do not add any Git Hub account.
4. Fork this project.

<h3> Expected </h3>

![screen shot 2014-10-10 at 10 41 23 am](https://cloud.githubusercontent.com/assets/8779995/4594031/e6e15ac0-508b-11e4-92fb-dca2fff73029.png)

<h3> Actual </h3>
![screen shot 2014-10-10 at 10 47 18 am](https://cloud.githubusercontent.com/assets/8779995/4594078/663043ea-508c-11e4-9aa3-f9f52df51363.png)

<h3> Possible Cause </h3>

It might be only checking if GitHub is checked in Select Add-ons section.

**Comment by GaryKriebel** [comment]
@nanchen47 did you ever finish this fix?

**Comment by nanchen47** [comment]
Same issue as https://github.com/CenterForOpenScience/osf.io/issues/3521. But that issue includes all addons. Close this one. Continue discussion there.
