### ISSUE TITLE
Cannot reorder my employment/education

### ISSUE THREAD

**Issue by huangginny** [CenterForOpenScience/osf.io#1094]
This happens on both staging and production.

<h3>Steps</h3>
<ol>
<li>Login and click the "Settings" icon next to your name, on the top right corner (this error does not occur if you do it in your profile page)</li>
<li>Click on the Education/Employment</li>
<li>Enter MORE THAN ONE positions<br/>
Now it looks like this...... 
<img src="https://cloud.githubusercontent.com/assets/8628591/4594472/f4d6529e-508f-11e4-8eb2-ab1058f4ab35.png"></li>
<li><strong>Drag to reorder</strong></li></ol>

<h3>Expected</h3>
The position-block you wish to reorder follows your cursor. Probably a dashed box shows up at where you want it to locate. Something like when reordering the widgets in "Statistics."

<h3>Actual</h3>
<ul>
<li><strong>Dragging Position 2 above Position 1:</strong>
<img src="https://cloud.githubusercontent.com/assets/8628591/4594518/6054c76c-5090-11e4-887e-91af709bce5b.png">
<br/>
See that the scroll bar on the right becomes shorter and shorter. And when you scroll all the way down...
<br/>
<img src="https://cloud.githubusercontent.com/assets/8628591/4594553/c392d5bc-5090-11e4-866c-bdb99fda9056.png">
</li>
<br/>
<li><strong>Dragging Position 1 under Position 2:</strong>
<img src="https://cloud.githubusercontent.com/assets/8628591/4594587/03f1c442-5091-11e4-808f-1ac983b243e2.png">
<br/>
Scroll down...
<br/>
<img src="https://cloud.githubusercontent.com/assets/8628591/4594599/12414b4e-5091-11e4-9c0d-c1366bc25d40.png">
</li>
</ul>

Fortunately, it goes back to normal upon refresh (to the original position.)

**Comment by lbanner** [comment]
@nanchen47 -- the PR for this doesn't look to be closed yet -- Should this not remain open for now?

**Comment by nanchen47** [comment]
@lbanner You are right. This issue hasn't been fixed yet. Should stay open. My fault.

**Comment by nanchen47** [comment]
Actually it has the same drag and drop problem as the statistic panel which is you can only drag and drop from bottom to top but not to bottm

**Comment by samanehsan** [comment]
Closing since this issue no longer happens on production.
