### ISSUE TITLE
"Read + Write" permission shows up as "Write" in contributor's sharing page 

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#1101]
Steps
--------
1. Go to a project
2. Click on the "sharing" tab
3. Add a "Read + Write" contributor

![screen shot 2014-10-10 at 4 08 53 pm](https://cloud.githubusercontent.com/assets/6414394/4598522/05afe2fe-50ba-11e4-88b1-883f79974f1b.png)

Expected
-------------
The contributor sees "Read + Write" as their permission when they go to the sharing tab of the same project. 

Actual
---------
The contributor sees "Write" under permissions instead of "Read + Write."
![cailey_permissions](https://cloud.githubusercontent.com/assets/6414394/4598523/102727a6-50ba-11e4-9e89-11516a12d46a.png)

**Comment by Ghalko** [comment]
@lbanner, I can move Ginny's changes to the current repository and submit a pull request.

**Comment by lbanner** [comment]
OK good. Thanks.

**Comment by Ghalko** [comment]
This will be even simpler to fix with #2196 when it is merged. Should I wait for merge?

**Comment by lbanner** [comment]
I would say so -- @sloria -- any chance we can review/merge #2196? Thanks.
