### ISSUE TITLE
[wiki] Component's new wiki does not have editing toolbar

### ISSUE THREAD

**Issue by ericanbaranski** [CenterForOpenScience/osf.io#1103]
### To recreate: ###
1. go to project component's wiki
2. add new wiki

### Expected: ###
editing tool bar above wiki text box

### Actual: ###
editing tool bar is absent

![wiki issue](https://cloud.githubusercontent.com/assets/7913610/4608735/6c5e35e4-5288-11e4-8c1a-4f99c1f37c83.png)

### Notes:###
issue only on production and not staging
issue only with component's new wiki pages (not with project's new wiki pages or component 'home' wiki)
related to issue #1102

**Comment by lyndsysimon** [comment]
@kmjungersen - could you test this in IE, and let us know if it's still an issue?

**Comment by kmjungersen** [comment]
@lyndsysimon absolutely, I'll take a look

**Comment by kmjungersen** [comment]
I can't seem to reproduce this problem on Production using IE 11.  Am I correct this isn't an issue on staging?

**Comment by chennan47** [comment]
Since the wiki has been totally remade, this problem no longer exists.
![screen shot 2015-03-20 at 4 32 09 pm](https://cloud.githubusercontent.com/assets/4974056/6760420/b6c5f564-cf1e-11e4-8ee4-43b5c23daf2b.png)
