### ISSUE TITLE
File download button occluded on some rendered views

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/osf.io#1118]
Download buttons are partly blocked in the file version table for some (but not all) file types. PDFs and Word files are affected; tables aren't. See the blue buttons in the attachment below:
![screen shot 2014-10-15 at 5 10 48 pm](https://cloud.githubusercontent.com/assets/1633460/4653725/45ed04d8-54b0-11e4-8f60-d57cc963f52b.png)

**Comment by nanchen47** [comment]
@kushG any updates on this one?

**Comment by kushG** [comment]
@nanchen47 It seems to me that this issue can be closed. The bigger Download button(green) was resolved as per my comment above. And the blue occluded download button was taken care by https://github.com/CenterForOpenScience/osf/pull/1209. Although, as I can see this PR is not being merged, I believe this has been taken care as it is no longer an issue on production.

**Comment by lbanner** [comment]
Great @kushG -- @nanchen47 I will close this one. Thanks.
