### ISSUE TITLE
Proposal: Lazy-load nested nodes in HGrid views

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/osf.io#1122]
Currently, loading HGrid data for a node also loads all its child nodes, grandchild nodes, etc. For small projects, this is fine, but a consequence is that it takes about 5s to load the file tree for RPP (verify at https://osf.io/api/v1/project/ezcuj/files/grid/). We're also loading, unserializing, and reserializing a lot of data that most visitors to this page probably aren't going to look at. I propose that we only send the first level of files in this view, and make everything deeper lazy-loaded.

**Comment by samanehsan** [comment]
Closing since we are now using treebeard in production, which lazy-loads nested folders
