### ISSUE TITLE
[wiki] wiki logs don't update the wiki name

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1123]
<h4>Steps</h4>
<ul>
<li>Make a wiki page. Title it something and add content.</li>
<li>Change the wiki's title.</li>
<li>Make an edit to the wiki</li>
<li>Visit the overview to look at the logs</li>
</ul>

<h4>What should happen</h4>
<ul>
<li>The logs on the overview should, when referring to the wiki page (e.g. "Johanna Cohoon updated WIKINAME to version 2"), call the wiki in *all* logs by its updated title. This mimics the behavior of components that have had their titles changed</li>
<li>Clicking on the wiki title, from the logs, should bring you to the most updated version of the wiki</li>
</ul>

<h4>What does happen</h4>
<ul>
<li>The logs on the overview refer to the wiki by its original name for all logs that occur before the name was changed. References to the wiki after the name change show the updated name. This is incorrect. They should all refer to the wiki by the updated name.</li>
<img src="https://cloud.githubusercontent.com/assets/4965832/4665590/470ad0c4-554c-11e4-962f-3d723dd19b53.png">

<li>Clicking on the (old) wiki name in logs before the title was changed brings you to a wiki page with the old name. This wiki has no content. This is incorrect behavior—the only wiki page that users should ever be able to see with no content is the home page, because that one is included by default.</li>
<img src="https://cloud.githubusercontent.com/assets/4965832/4665608/61271a8a-554c-11e4-88d0-2a87b748d608.png">

<li>Clicking on the new wiki name in logs after the title was changed brings you to the correct page.</li>
<img src="https://cloud.githubusercontent.com/assets/4965832/4665611/64166b92-554c-11e4-8118-5bf42b44f387.png">

<li>The old wiki name (/page), does not appear in the project wiki pages list on the left sidebar. This is correct, but underlines the point that you should not be able to access this page.</li>
</ul>

**Comment by GaryKriebel** [comment]
With updates to wikis a few releases ago, this is no longer an issue.
