### ISSUE TITLE
[github] [dev] Rewrite github-node-cfg.js using Knockout

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1126]
The current Github project configuration widget uses a mix of jQuery and mako. The mako template receives it's context from `AddonGitHubNodeSettings#to_json`, which has been deprecated. 

After #1125 is complete, `github-node-cfg.js` can be rewritten to conform with the current KO-module style for rendering addon widgets.

**Comment by nanchen47** [comment]
addressed by https://github.com/CenterForOpenScience/osf.io/pull/1305
