### ISSUE TITLE
Emoji are allowed in titles but do not display in all browsers

### ISSUE THREAD

**Issue by csheldonhess** [CenterForOpenScience/osf.io#1127]
I named my project "This project has a wiki, 😃" and my wiki "This is A CoOoOoOol WiKi 💜"

I entered the information in Chrome, so the emoji came up as boxes, rather than what I picked. I expected they would be boxes in all of the other browsers. However, had I entered them in Safari or Firefox and seen them show up, I would have expected them to show up in Chrome and Opera, too.

I confirmed that this is the case on Staging and Production.

In Safari and Firefox (on Mac) they both show up fine:
![image](https://cloud.githubusercontent.com/assets/3027971/4669312/2679bb56-556d-11e4-8622-acf8c97434b9.png)

In Chrome and Opera (on Mac) they do not show up:
![image](https://cloud.githubusercontent.com/assets/3027971/4669370/b068a174-556d-11e4-922c-33fe53d5e823.png)

I confirmed that this is the case with emoji, but not with proper Unicode characters, which show up just fine, no matter which of the four browsers I used:
![image](https://cloud.githubusercontent.com/assets/3027971/4669490/98238dd0-556e-11e4-8891-437ea4cfe6f8.png)

After a quick Google search, it seems that Chrome does not natively support emoji. Perhaps we should not allow them in the OSF, to keep things consistent.

**Comment by nanchen47** [comment]
Will be considered in later enhancement. Thanks.
