### ISSUE TITLE
[project organizer] [ui] Confirmation buttons occluded by info box

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1128]
### Steps

- At the dashboard, click the "i" icon next to a folder to bring up its info box
- Click "Delete Folder". A modal should appear.

### Expected

- After clicking the "Delete Folder" button, the info box should disappear.

### Actual

- After clicking the "Delete Folder" button, the deletion confirmation modal appears behind the info box.

![osf___dashboard](https://cloud.githubusercontent.com/assets/2379650/4670319/0b35be0e-5576-11e4-944b-8faac481e13b.png)

**Comment by GaryKriebel** [comment]
@sloria @huangginny Has this PR been merged and released?

**Comment by huangginny** [comment]
@GaryKriebel I don't think so... And that PR is still in the old repository

**Comment by brianjgeiger** [comment]
This is no longer an issue with the redesign of the project organizer and integration of Treebeard.

**Comment by GaryKriebel** [comment]
Thanks @huangginny and @brianjgeiger
