### ISSUE TITLE
[osffiles] [dropbox][s3] Download and Delete buttons are oversized

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1138]
The download and delete buttons on file detail pages are very dominant due to their large size, bright color, and the added text, to the point where it can be distracting.

![osf___test_csv](https://cloud.githubusercontent.com/assets/2379650/4679968/cbcb06b6-5606-11e4-9bee-95bf050d7794.png)

I propose downsizing them:

![osf___test_csv](https://cloud.githubusercontent.com/assets/2379650/4680012/30b5be54-5607-11e4-9b5f-14106c317553.png)

I think the coloring and text are enough to make the buttons stand out, without being distracting.

**Comment by csheldonhess** [comment]
I think this issue can be closed.
