### ISSUE TITLE
[staging & production] [wiki] Add warning to save page after creating new wiki

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1142]
# Steps
1. Create a new wiki page (enter title)
2. Press OK
3. Navigate away from the page

# Expected
Since creating wiki pages with no content is now allowed, a warning modal should pop up to ask the user if they are sure they want to navigate away from the page before saving changes. 

# Actual
No warning modal pops up, and user is able to navigate away from the page. The new wiki page is then deleted since it was never saved. 

# Possible Solutions
Add a warning modal to ask if users would like to navigate away without saving changes.

**Comment by lbanner** [comment]
@brianjgeiger My sense is that this issue is now overcome with the recent Collaborative Wiki changes? -- or is this something we need still consider?

**Comment by brianjgeiger** [comment]
I believe this is covered by the last set of wiki changes. Would be worth having someone test, but I suspect that is the case.

**Comment by lbanner** [comment]
Thanks!

**Comment by lbanner** [comment]
Issue remains: No warning upon leaving and the "New" Wiki page is lost.

**Comment by mfraezz** [comment]
Issue still remains. I agree that "unsaved changes" dialogs are obnoxious. Given that this is only an issue with newly created wiki pages (old ones have a preserved draft thanks to ShareJS) and that blank wiki pages are allowed, would it make sense to save a blank page upon creation/naming of a new wiki page? No dialogs, and a draft is preserved if they navigate away after making unsaved edits.

**Comment by lbanner** [comment]
Thoughts on above ^^ @jlcohoon @brianjgeiger @caileyfitz ?

**Comment by jlcohoon** [comment]
I like the solution

**Comment by lbanner** [comment]
@caseyrollins You are tagged with this -- You still want it? or @mfraezz Can you implement your solution?

**Comment by mfraezz** [comment]
I've never worked on the wiki, but I doubt it would be a difficult fix.
