### ISSUE TITLE
[anonymous links] Distinguish between already checked and unchecked components 

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1143]
# Steps 
1. Go to sharing page on a project on which you have admin access
2. Press Create a link
3. Look at the options to associate components with the link

# Expected
Already selected components should appear disabled and components that can be selected should appear active.

# Actual
The current project is always already clicked, and components are listed below it. Since the text color is the same for the checked/selected components and active/unselected components, I always think that the unchecked components are also inactive. Does this make any sense? 
![screen shot 2014-10-17 at 11 49 58 am](https://cloud.githubusercontent.com/assets/5975444/4681774/0c0f973c-5616-11e4-8e90-f12adfe95fd4.png)
I think the text with the purple arrow should somehow be distinguished from the text with the blue arrows. Perhaps make it a lighter shade of gray? If the text were to change when selected (such as becoming gray), this may make it clearer which components can be clicked and which can't.

**Comment by haoyuchen1992** [comment]
I think this UI enhancement is necessary and also is not hard to do. Can I grab this one? Thanks :)

**Comment by haoyuchen1992** [comment]
The effect after changing: 
![screen shot 2015-06-29 at 11 02 18 am](https://cloud.githubusercontent.com/assets/5420789/8410847/bcb76a5a-1e4e-11e5-91d1-6b503e2531f9.png)

Similar unchecked box also exists in project setting page, make the similar change and it will get:
![screen shot 2015-06-29 at 10 59 58 am](https://cloud.githubusercontent.com/assets/5420789/8410995/76ae81b4-1e4f-11e5-8b8f-29fba0d682a2.png)

But after discussing with Caner, he pointed out that the grey checkbox has already shown the state of current component, which is checked but unselectable. From my point of view, grey color is to make the checked but unselectable state more obvious. It delivers the correct and useful information.  

Some additional discussions are needed.

**Comment by lbanner** [comment]
@haoyuchen1992 and @caileyfitz ... If I am understanding correct, does your example, "The effect after changing:" accomplish the needed task?

**Comment by haoyuchen1992** [comment]
@lbanner It does accomplish the needed task. But there is a discuss that the current implementation is already good. Changing the text color may not a good option.

**Comment by caneruguz** [comment]
Already selected components appearing disabled is against feedback rules for UI. One could bold the text but that could denote hierachy and also influence the visibility. 

@lbanner I already made my comments on this to Haoyu, unless someone specific can comment on it (in which case we need to tag them) we can move on and close this issue. 

@caileyfitz

**Comment by caileyfitz** [comment]
@caneruguz I don't think I completely understand... Doesn't the checkbox already appear disabled? Does *this* go against feedback rules for UI?

**Comment by caneruguz** [comment]
This is what can't be done " If the text were to change when selected (such as becoming gray), this may make it clearer which components can be clicked and which can't." 

Also the check box is already disabled, isn't it? 
disabled means you can't do an action on this right now. If that is the case we can use it, it doesn't mean "this is selected". I don't think there is any need to change here.

**Comment by lbanner** [comment]
@caileyfitz -- Good goal but I think this one we leave as is for now ... unless over time we receive confused feedback from users. Closing to clear the decks. TY!

**Comment by caileyfitz** [comment]
I stand my ground that this is still very confusing but see the need to focus energy into addressing more troublesome issues.
