### ISSUE TITLE
S3 logs are generated whether or not the upload succeeds

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/osf.io#1155]
As discussed in person with @sloria, this is an edge case that will occur very rarely, and may not have an elegant solution. The error will only come up when the user loses her connection during a PUT to S3, or if there are bugs in our S3 or Dropzone logic. As such, it's probably a low priority to address; I'm filing the issue so we have a record that the problem exists.

# Steps
* Request a signed upload URL through the S3 add-on, but don't upload the file
    * This can be simulated by returning an invalid signed URL from the `s3_upload` view function

# Expected
* The file is not uploaded, and no log is generated

# Actual
* The file is not uploaded, but an upload load is generated
* Clicking on the file link in the log leads to a 404

**Comment by caneruguz** [comment]
@jmcarp Is this still an issue?

**Comment by jmcarp** [comment]
No, this is fixed with the move to WaterButler. Thanks for pointing this out @caneruguz.
