### ISSUE TITLE
Guid `5zdrq` resolved to non-guid object

### ISSUE THREAD

**Issue by lyndsysimon** [CenterForOpenScience/osf.io#1156]
This was once a user apparently, but no longer exists. Perhaps this is the result of a user merge?

https://sentry.osf.io/osf/production/group/274/

**Comment by chennan47** [comment]
Talked with @lyndsysimon , this guid leads to a user which has never been created, has no nodes created and no contribution on any project. The url is hit by google bot, not sure where they get the reference. At this point I think we should just remove this guid.

**Comment by JeffSpies** [comment]
How do we know it's a user then?

**Comment by chennan47** [comment]
@JeffSpies Checked on the database, the guid showed it's a user.

**Comment by JeffSpies** [comment]
But you said the user had never been created?

**Comment by chennan47** [comment]
The user doesn't have any logs, nodes or even a user name. It's probably generated during some transition.

**Comment by JeffSpies** [comment]
OK, we need to deal with the problematic data, but the guid should not be
re-used.
