### ISSUE TITLE
ampersands (symbols?) render in HTML in contributor search and project linking modals

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1158]
<h4>Steps</h4>
1. Search for a user in the "add contributor" modal OR search for a project in the "add links" modal. Examples: try searching for Mallory Kidwell as a contributor or Wolf as a project to link. 

<h4>Outcome</h4>
1. When a contributor has an ampersand in an institution they list in their profile, the "add contributor" modal shows that ampersand in HTML. Not all symbols seem to render this way, however. Mallory used a % that shows up correctly.
![screen shot 2014-10-21 at 3 04 16 pm](https://cloud.githubusercontent.com/assets/4965832/4724915/11c41594-5955-11e4-826c-0662c8fa4663.png)

2. *Sometimes* when a project has an ampersand in the title, the "add links" modal shows it in HTML. 
This doesn't occur every time, however (compare "Replication of Zárate, Stoever, Mclin, & Arms-Chavez" to "Replication of Larsen & McKibban"). 
![screen shot 2014-10-21 at 2 47 50 pm](https://cloud.githubusercontent.com/assets/4965832/4724910/0642a816-5955-11e4-9e24-3736c450ab42.png)

<h4>Expected outcome</h4>
1. Symbols should never be shown in HTML.

**Comment by lbanner** [comment]
This is newly addressed in #1832  -- So I am closing this old issue.
