### ISSUE TITLE
[figshare] Figshare add-on root makes slow API call when loading HGrid

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/osf.io#1161]
I noticed that the HGrid on https://osf.io/hks4q/files/ loads pretty slowly (typically about 5s on my laptop). It turned out that much of that time was spent getting the title of the Figshare project from their API. This is a problem, because *all* HGrid content is waiting for the response from the Figshare API. In general, we should minimize (or ideally eliminate) any interactions with external APIs when building the HGrid root.

Proposed solution: Don't load the title of the Figshare project on the backend. Instead, make a separate API request from the client after loading the grid.

@lyndsysimon, @samanehsan: Not sure what priority you think this should be, but I did notice this on a public OSF demo page, and it's a little embarrassing.

**Comment by nanchen47** [comment]
With waterbulter, this should no longer be a problem.
