### ISSUE TITLE
[wiki] Error messages for duplicate wiki names should be consistent

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1164]
# Steps
1. Go to a wiki page on which you have write access.
2. Create a new wiki page with a name that already exists (for the easiest example, try to create a new page named 'home')
3. Press OK and take note of the error message.
4. Create a new wiki page and try to rename it to a name that already exists (can use 'home' here also). 
5. Take note of error message for wiki title renaming.

# Expected
Both error messages should be the same, since the same problem is encountered in two different ways.

# Actual
The error messages have both different wording and different formatting. 
When creating a new wiki page with a duplicate name:
![image](https://cloud.githubusercontent.com/assets/5975444/4737971/8d2bded4-59f9-11e4-83fe-4ca08dbe7c71.png)
When renaming a wiki page with a duplicate name:
![image](https://cloud.githubusercontent.com/assets/5975444/4737987/ab5c6b3a-59f9-11e4-857d-7796fc76313c.png)
The formatting may not be as big of an issue, but definitely the text should be consistent. Seeing a blue error message also strikes me as a little odd, since all other error messages (to my knowledge) are red.

**Comment by sloria** [comment]
Addressed by recent wiki redesign and 4a7c39e
