### ISSUE TITLE
Active folder is not selected in folder-picker

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1165]
<h4>Steps</h4>
1. Visit your project settings where you have a Dropbox folder selected as an add-on to your files.
2. Click on "Change" under the Dropbox configuration settings.

<h4>Expected Behavior</h4>
The active folder (the one you have selected already) should have its radio button filled in, to indicate that that is what is selected.

<h4>Actual Behavior</h4>
No folders have their radio button selected. The only thing showing which folder is selected is the "current folder" text above the file selection tree. 
![screen shot 2014-10-22 at 11 37 12 am](https://cloud.githubusercontent.com/assets/4965832/4739139/4a5cb962-5a02-11e4-86ac-5f13e103d81e.png)

**Comment by caneruguz** [comment]
@lbanner Treebeard now does this. I think this issue can be closed.
