### ISSUE TITLE
[dropbox] Changing folder name results in the appearance of lost files on OSF

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1166]
<h4>Steps</h4>
1. Connect a Dropbox folder to an OSF project
2. On your computer, or on dropbox.com, edit the name of the folder you connected
3. Refresh your OSF project

<h4>Expected Results</h4>
1. The name of the connected Dropbox folder would update on the OSF
2. All files in that folder would still be accessible

<h4>Actual Results</h4>
1. The OSF project does not update the name of the Dropbox folder
2. The connected Dropbox folder is now empty on the OSF
3. To resolve this, you have to visit the project settings and "change" which folder is selected. This will update the name and bring the files back.

This is a video that demonstrates the problem and the steps needed for a user to resolve it: http://youtu.be/KzKAQB_Q1DM

**Comment by nanchen47** [comment]
Will be considered in future enhancements. Thanks.
