### ISSUE TITLE
Clarify language on "visible"/bibliographic contributor toggle

### ISSUE THREAD

**Issue by csheldonhess** [CenterForOpenScience/osf.io#1167]
When adding a contributor, the current language asks if they should be visible or not. Internally, our treatment of this setting is not so much as a privacy toggle (for instance, expunging their actions or existence from logs), but rather as an indication of whether the contributor is "bibliographic" or "non-bibliographic," making it basically an attribution toggle. With the current wording, it would be easy for users to misunderstand and treat it as a privacy setting.

Here's the column under question:
![image](https://cloud.githubusercontent.com/assets/3027971/4739536/7bdfae06-5a05-11e4-81ba-e76a0e12253e.png)

And the tooltip that goes with it:
![image](https://cloud.githubusercontent.com/assets/3027971/4739544/89518096-5a05-11e4-97be-c8a9342baadb.png)

To clarify the intended function of this setting, we should label the column "Attributed?" or "Bibliographic?" (or something along those lines; let's discuss) and make the tooltip a little bit clearer.

**Comment by brianjgeiger** [comment]
@lbanner Looks like @himanshuo was kind enough to update this one. Should be very easy for @sloria to get in.

**Comment by lbanner** [comment]
TY @brianjgeiger  -- I think @sloria is on this one via #1223

**Comment by nanchen47** [comment]
This problem already got solved.
