### ISSUE TITLE
[s3] New IAM user created without user's knowledge

### ISSUE THREAD

**Issue by jakerose27** [CenterForOpenScience/osf.io#1190]
# Steps
1. Go to the settings page of a project for which you have write access.
2. Select the "Amazon Simple Storage Service" item and click submit.
3. Enter in AWS Secret Key and Access Key to link your S3 account.
4. Refresh page and confirm that your account as been linked.

# Expected
The user should expect that the OSF now has access to their S3 account using the credentials given. When deleting this key on the S3 site, OSF should no longer have access to their account.

# Actual
An IAM user is created on the user's S3 account without their knowledge:
![screen shot 2014-10-28 at 12 27 28 pm](https://cloud.githubusercontent.com/assets/4513007/4812263/63f29e8e-5ebf-11e4-9bb1-c6f0dd66ab5c.png)

Therefore, if a user wants to deauthorize the OSF from accessing their Amazon account and wants to complete this action from the S3 console, they have to delete an IAM user they did not know was created. Deleting the secret/access keys given to the OSF has no effect. The user should be warned about these actions on linking their account.

**Comment by lyndsysimon** [comment]
I propose we leave this as-is. The solution in place now considered this potential confusion, and we decided that having a discrete user for the OSF outweighed the negatives.

In light of that, I'm going to go ahead and close this. If anyone feels it has not been adequately addressed, by all means re-open it.
