### ISSUE TITLE
[production & staging] new project title warning font size too small

### ISSUE THREAD

**Issue by chennan47** [CenterForOpenScience/osf.io#1193]
Steps 
go to the dashboard page.
Click on the new project.(if you are on production)
expand the create a new project.(if you are on staging)
then click submit directly

Result
for production
![screen shot 2014-10-28 at 4 02 13 pm](https://cloud.githubusercontent.com/assets/4974056/4816193/640461a0-5edd-11e4-83c6-bd52107a4b71.png)

for staging
![screen shot 2014-10-28 at 4 03 49 pm](https://cloud.githubusercontent.com/assets/4974056/4816216/9371c0f4-5edd-11e4-84be-d334a3153755.png)

**Comment by lyndsysimon** [comment]
It's not great in terms of usability, but it's consistent with how we're doing things right now across the site.
