### ISSUE TITLE
Users should be able to delete their accounts

### ISSUE THREAD

**Issue by lyndsysimon** [CenterForOpenScience/osf.io#12]
Once a user account is created, there is no apparent way to delete the account. A "delete" and/or a "deactivate" option should be made available on a logged-in user's profile page.

**Comment by HarryRybacki** [comment]
@GaryKriebel @lbanner this is on the docker for this epic. We shouldn't forget to assign it accordingly once the issues are being worked on.

**Comment by lbanner** [comment]
Good point - yes

**Comment by lbanner** [comment]
Note @lyndsysimon PR: [WIP] [feature] Account deactivation #2165

**Comment by lyndsysimon** [comment]
Closed by #2602 - or at least, the interface is present. The functionality still requires admin approval, but that's an explicit decision because we don't want users to accidentally deactivate their accounts.
