### ISSUE TITLE
[production & staging] social page

### ISSUE THREAD

**Issue by chennan47** [CenterForOpenScience/osf.io#1201]
Steps
go to user settings page, click on edit on social tab
give some input then click return

Expected
I felt it should return should be default to be clicking submit button and save the change

Actual
![screen shot 2014-10-30 at 12 15 12 pm](https://cloud.githubusercontent.com/assets/4974056/4847059/f2d2c1ce-604f-11e4-9f47-8627d969eba6.png)
It seems the return button is defaulted to cancel button instead of submit

Also there is no validate for personal website url?
![screen shot 2014-10-30 at 12 16 46 pm](https://cloud.githubusercontent.com/assets/4974056/4847115/4e6bf60e-6050-11e4-883d-b77b7195fa36.png)

**Comment by nanchen47** [comment]
The interface has been changed and this is no longer an issue
