### ISSUE TITLE
When removing project contributors, notify user that removed contributors with access to components will retain that access

### ISSUE THREAD

**Issue by kmjungersen** [CenterForOpenScience/osf.io#1202]
Story: I have a contributor to a project with all (or some) of this project's components.  When I remove this user from the project, they retain permissions to components, which is not expected behavior for most users.    Possible solutions:

1. Fastest and Easiest: Simply display a warning to the user letting them know which components (if any) that the user(s) they are attempting to remove will retain access to.  

2. Moderate: We not only display the components which the user(s) still have access to, but provide a link that opens in a new tab to the sharing page for that component, allowing the admin to then remove anybody they need.

3. Best and most thorough solution: provide a checklist displaying the components that each contributor has access to (or some sort of similar interface).  This would enable the admin to quickly change permissions for all of the affected components.

One excellent point that @caneruguz brought up in a discussion about this is that the user should be able to exit this at any time in the process, in the case that it's intended behavior to remove the user's/users' access from the top level only.  Also if there are no components or no components which this user has access to, then of course there's no problem and none of these steps are necessary.

**Comment by samanehsan** [comment]
Marking this as "Hold" as per discussion in #3004

**Comment by lbanner** [comment]
:+1:
