### ISSUE TITLE
[production] routes with `<path:*>/action` fail when content matches action

### ISSUE THREAD

**Issue by icereval** [CenterForOpenScience/osf.io#1213]
Addons w/ `<path:*>/action`:
- [ ] dataverse
- [ ] dropbox
- [ ] github
- [ ] s3

Steps
--------
1) Load the dropbox addon in your project
2) Upload a file matching a route action, e.g. `download`
3) Click on the file to view it

![image](https://cloud.githubusercontent.com/assets/3111541/4876697/c160bc64-62ce-11e4-8dd8-39b1739fbfa9.png)

Expected
------------
File contents should be displayed to the user.

Actual
--------
Python throws an error because the file name `download` matches the route action `download`. We should be able to move the route action before the `<path:*>` to correct this behavior, e.g. `files/download/<path:*>/`.

![image](https://cloud.githubusercontent.com/assets/3111541/4876700/cfd64dae-62ce-11e4-8234-63f343e5608e.png)

**Comment by GaryKriebel** [comment]
This is no longer an issue.
![screen shot 2015-02-24 at 10 54 52 am](https://cloud.githubusercontent.com/assets/9437946/6352857/99ef3996-bc13-11e4-92f0-8eaaff793f26.png)
