### ISSUE TITLE
[enh] Enable caching for non-authenticated users

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/osf.io#1214]
@icereval and I put together some revisions to the Nginx configuration that would cache all responses for non-authenticated users (see https://github.com/CenterForOpenScience/private-configs/commit/304d24cd0f3aa80cdcd5020d02b8766847601d55). Some basic load testing showed that, unsurprisingly, performance for non-authenticated users is orders of magnitude better with caching enabled. Caching is currently enabled on the staging server for testing.

@JeffSpies, @sloria, @lyndsysimon: thoughts?

**Comment by lbanner** [comment]
@jmcarp -- Did this remain only on Staging? Or have we ether deployed this or overcome its issue?

**Comment by jmcarp** [comment]
@lbanner this went to production a while back. Should be ready to close.

**Comment by lbanner** [comment]
Thanks!
