### ISSUE TITLE
[ui] hgrid actions are not visible on touch displays (no mouseover)

### ISSUE THREAD

**Issue by icereval** [CenterForOpenScience/osf.io#1217]
Steps
--------
1) Use a touch screen device, e.g. Tablet/Phone
2) Load any OSF Project containing files
3) Navigate to the Files page

Expected
------------
HGrid Action items should be visible, allowing the user to select them. 

![image](https://cloud.githubusercontent.com/assets/3111541/4892014/cc909192-63ad-11e4-9665-fc0d13bbece5.png)

Actual
--------
Action items are not visible, the user can click in the general area and activate an action such as Delete however it is not intuitive.

![image](https://cloud.githubusercontent.com/assets/3111541/4892009/c45c3c56-63ad-11e4-83f7-04011775b4f6.png)

**Comment by GaryKriebel** [comment]
With the replacement of HGrid with TreeBeard, the actions are seen when the user selects a file.
![img_7683](https://cloud.githubusercontent.com/assets/9437946/6352792/35ad0706-bc13-11e4-8d07-14fd165610a4.PNG)
