### ISSUE TITLE
[enhancement][ui] allow deletion of multiple files at once

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1220]
Presently, only one file can be deleted from a component at a time. When multiple files need to be removed, this process can be laborious. 

I just decided to link a Dropbox folder to a component so that I could more easily revise my materials for a project. This meant that about 30 files that had been uploaded directly to the OSF were redundant (they were in the Dropbox folder as well). I wanted to delete those from the component, but the idea of deleting 30 files one at a time seemed terrible so instead I deleted the whole component and started fresh. This was much faster for me, but not ideal in terms of preserving a history of my project. 

To prevent other users from doing the same thing (deleting a whole component instead of deleting many files from it), I would suggest allowing users to select multiple files for deletion.

**Comment by kmjungersen** [comment]
Ping @JeffSpies, @lbanner and @GaryKriebel, I think this would be a great/simple feature to add to our roadmap soon.  This is pretty standard functionality for similar services.

**Comment by kmjungersen** [comment]
Also @caneruguz

**Comment by JeffSpies** [comment]
I like that idea.

**Comment by caneruguz** [comment]
Yes, I have been holding on to adding this. Treebeard has multiselect and hooks for onmultiselect. Project Organizer is already using something like this where you can select multiple items and remove from folders. I would have to talk to waterbutler guys but I think the implementation of this would be swift. 

@JeffSpies, let me know about a good time frame that fits with our goals and I'll fit it in to my list of to-do's.

**Comment by JeffSpies** [comment]
Will do. Let's see how the month starts--wiki is higher priority for your
skills and meeting our goals, I think.

We can chat more if need be.

**Comment by caneruguz** [comment]
@lbanner this is not in production so I think we can close the issue.
