### ISSUE TITLE
[production] can't complete upload of new file version on Chrome

### ISSUE THREAD

**Issue by AndrewSallans** [CenterForOpenScience/osf.io#1222]
User reported this issue/behavior:

(1) Tried uploading new file version to his project.
(2) Screen grays out and then goes to a page that has a link to "e-mail support". 
(3) Upload of new file version does not complete.

User was doing this on Chrome 39.0.2171.42 beta-m, and Windows 7 professional service pack 1

In further conversation with user, asked him to test same file, project, action, but to change the machine, OS, and/or browser.  He tested on the same machine and OS, but different browser and found that it worked.  It was successful when using Firefox.

**Comment by nanchen47** [comment]
checked with @AndrewSallans there is no update from the user and can't repo this problem. Close this for now
