### ISSUE TITLE
[production & staging] file page hgrid break

### ISSUE THREAD

**Issue by chennan47** [CenterForOpenScience/osf.io#1225]
Note: See [comment below](#issuecomment-62792214)

-----

Steps
create a project
enable an addon, just take github for example
![screen shot 2014-11-05 at 10 02 34 am](https://cloud.githubusercontent.com/assets/4974056/4919739/cb4285f2-64fc-11e4-8f20-bc3f7d57b029.png)

then upload a file to the osf file storage
![screen shot 2014-11-05 at 10 02 58 am](https://cloud.githubusercontent.com/assets/4974056/4919749/d94d5bea-64fc-11e4-8d03-4f45f95e3799.png)

then refresh the page
![screen shot 2014-11-05 at 10 03 25 am](https://cloud.githubusercontent.com/assets/4974056/4919762/e9662ae8-64fc-11e4-96bd-47b410429281.png)

and it will be more awful for empty github repo
addon enabled:
![screen shot 2014-11-05 at 10 04 21 am](https://cloud.githubusercontent.com/assets/4974056/4919777/0a8fe3bc-64fd-11e4-8e90-be74e4f63038.png)

file uploaded
![screen shot 2014-11-05 at 10 04 56 am](https://cloud.githubusercontent.com/assets/4974056/4919782/204db616-64fd-11e4-9df7-c1adc85ecd5d.png)

after refresh
![screen shot 2014-11-05 at 10 05 22 am](https://cloud.githubusercontent.com/assets/4974056/4919791/305e4aca-64fd-11e4-9a8c-ddb09ca92051.png)

**Comment by lyndsysimon** [comment]
I'm closing this issue, as it has drifted quite a bit from its original purpose. @brianjgeiger, if you still plan to make changes here feel free to open another issue and link to this one.
