### ISSUE TITLE
[search] Elastic search tests should not be using real indices

### ISSUE THREAD

**Issue by fabianvf** [CenterForOpenScience/osf.io#1228]
Ideally all the tests would be hitting a 'test' index, so that at the end of the tests you can just delete that index and not have to rebuild the search index from scratch. Because Node and User save methods will end up calling search, this will probably necessitate patching website/search.py:search so that its default index argument is 'test' instead of 'website' when you are running the tests.

**Comment by brandonPurvis** [comment]
If this is still needed I can do it.

**Comment by fabianvf** [comment]
That would be awesome

**Comment by samanehsan** [comment]
Closed by #3132
