### ISSUE TITLE
[ui][staging] Search results overlap with the queue when adding a pointer to a project

### ISSUE THREAD

**Issue by huangginny** [CenterForOpenScience/osf.io#1229]
This issue happens on staging, but NOT on production
Browser I'm using: Chrome

Steps
---------------------
1.Go to the project overview page
2. Click "add link"
3. Search for a really common term
4. Click add on one or more search results

Expected
----------------------
![screen shot 2014-11-05 at 2 01 33 pm](https://cloud.githubusercontent.com/assets/8628591/4923858/3a201a36-651e-11e4-9def-74740e6a69d0.png)
(Screen shot from production)

Actual
-----------------------
![screen shot 2014-11-05 at 1 55 46 pm](https://cloud.githubusercontent.com/assets/8628591/4923864/4222dcdc-651e-11e4-9104-feaad149e3d5.png)

**Comment by GaryKriebel** [comment]
This is no longer an issue.
