### ISSUE TITLE
[staging & production] [social links] Cannot delete education/employment positions once present

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1230]
# Steps
1. Go to the user profile page
2. Add two or more positions to either Education or Employment (or both - functionality in terms of this bug is the same)
3. Press Save
4. Click Edit on Education/Employment tab and attempt to delete all existing positions.

# Expected
A user should be able to delete all existing Education/Employment positions. 

# Actual 
A user can delete all positions, except for the position at the top of the list (labelled Position 1). There is no Remove button to remove the position completely. Clearing information from all fields also does not work, as the user encounters an error saying that the Institution field is required. This means that once a user has entered any Education/Employment information, there must always be at least one position listed.

**Comment by samanehsan** [comment]
Closing this issue in favor of #2384
