### ISSUE TITLE
[Onboard]File uploads dont work in IE 11

### ISSUE THREAD

**Issue by kushG** [CenterForOpenScience/osf.io#1232]
<h3> Steps </h3>
1.Go to the project dashboard page.
2. Drag a file from your system to the Upload File section(just below <code>Drop File(or click below)</code>)

<h3>Expected</h3>
File should have been uploaded to your project.

<h3> Actual</h3>
Opens up File Download wizard for the file you're actually trying to upload.
<strong> Note : </strong> Clicking on <code>Drop File(or click below)</code> wont show File upload wizard either leaving no option to upload files if you're using IE.
![gh issue](https://cloud.githubusercontent.com/assets/8779995/4938244/086ed4da-65ca-11e4-83a0-62ceee5dc68f.png)

**Comment by kmjungersen** [comment]
Just as a heads up, I'm still seeing this issue in IE, on both production and staging with no errors in the console.

**Comment by nanchen47** [comment]
same issue as https://github.com/CenterForOpenScience/osf.io/issues/1669
