### ISSUE TITLE
Previous name shows up in search results

### ISSUE THREAD

**Issue by huangginny** [CenterForOpenScience/osf.io#1237]
Steps
---------------------
1. Currently your user name is "name1"
2. Create a PUBLIC project, say "project1"
3. Change your name to "name2"
4. Search for "name1"
5. Search for "project1"

Expected
----------------------
You should see nothing when you search for "name1";
You should see that "name2" is listed under "project1" when searching for "project1"

Actual
----------------------
In both cases, project 1 shows up on search, with "name1" under contributors

@brianjgeiger is that a intended behavior or a bug?

**Comment by lyndsysimon** [comment]
I've updated @huangginny's PR to reflect changes to the codebase since this was submitted, and the PR is once again ready for review.

**Comment by lbanner** [comment]
Thanks .... @sloria -- this is a good one to prioritize for upcoming release.

**Comment by lyndsysimon** [comment]
@lbanner - We have two PRs and two issues for this. I've closed the other issue (#2565), and I recommend we go with my PR (#2956), as it makes only a single request to elasticsearch to update all projects for which a user is a contributor. I'll note that recommendation in the PR, as well.

**Comment by lbanner** [comment]
Yes -- @samanehsan had comments noting same on #2956 ... make it so : )

**Comment by samanehsan** [comment]
:+1:
