### ISSUE TITLE
[chrome][firefox][onboarding] Hit enter on "Go to project" does not take you to project

### ISSUE THREAD

**Issue by huangginny** [CenterForOpenScience/osf.io#1238]
I tested it on Safari. It does not happen.

Steps
--------------------
1. Go to your dashboard
2. On "Go To Project," select a project
3. Leave the component field empty
4. Hit enter

Expected
---------------------
You are taken to that project.
The reason why this is expected is because this is the behavior for "Create a project"

Actual
----------------------
Nothing happens. No error messages in console.
But if you put your cursor on the component field and press enter, you are taken to that project.

**Comment by brianjgeiger** [comment]
Would be good to test with IE as well.

**Comment by chennan47** [comment]
It works fine on IE.

**Comment by lbanner** [comment]
This still 'pending' as PR? -- or can we close? Thanks

**Comment by chennan47** [comment]
@lbanner it's still pending. Haven't been merged yet.

**Comment by huangginny** [comment]
This PR goes to osf not osf.io... do I need to do another PR?

**Comment by lbanner** [comment]
@sloria ^^

**Comment by chennan47** [comment]
@huangginny yeah you need to close this one and make a new one goes to osf.io

**Comment by huangginny** [comment]
@chennan47 @lbanner https://github.com/CenterForOpenScience/osf.io/pull/2150 Did another one!
