### ISSUE TITLE
Cancel button not working after you remove a position from Employment/Edcuation

### ISSUE THREAD

**Issue by kushG** [CenterForOpenScience/osf.io#1243]
<h3> Steps </h3>
1. Go to either Employment or Education tab on profile settings page.
2. Add a few positions.
3. Click 'Edit' to remove a position.

![screen shot 2014-11-10 at 10 51 44 am](https://cloud.githubusercontent.com/assets/8779995/4978677/c93c2972-68f1-11e4-9ad6-6c09d3bdc4fe.png)

 Hit 'Cancel' now

<h3> Expected </h3>
Either you should be navigated out of Edit or the changes made before hitting Cancel should be discarded.

<h3> Actual </h3>
Nothing happens ! Page stays as it is.

<strong>Note :</strong>This would be useful when a user accidentally removes a position while editing & wants to Undo the changes instantly,

**Comment by GaryKriebel** [comment]
Confirmed that this is no longer an issue.
