### ISSUE TITLE
[dev] Clean up code in project.js

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1244]
Unlike many of our newer JS modules, which are typically responsible for isolated UI components, `website/static/js/project.js` is a mix of helper functions for the project dashboard page as well as a number of jQuery event handlers that are applied globally.

I recommend the following:
- [x] Create a Knockout ViewModel to control the UI for the project duplicate modal
- [x] Use Knockout to bind event handlers for the citations and tags widgets.

Assigning to @mfraezz.

**Comment by erinmayhood** [comment]
@sloria can this be closed?

**Comment by sloria** [comment]
I lean towards keeping this open; the original issues described above are still present.
