### ISSUE TITLE
[ui][public profile] Public component names are often ambiguous

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1249]
<h4>Steps</h4>
1. Visit your public profile and look at your "Public Components"

<h4>Expected</h4>
1. Users should be able to distinguish one component from another.

<h4>Actual</h4>
1. Often, components from different projects have the same title (e.g. "Study Materials" or "Data"). They are listed in your public profile without providing the project title for context, so components with the same name are indistinguishable from each other. See below for an example:

![screen shot 2014-11-13 at 2 03 40 pm](https://cloud.githubusercontent.com/assets/4965832/5034679/f2354c7e-6b3e-11e4-87a3-c4d8e54f08b6.png)

I would suggest including the project title for each component in grey next to each component's title:
![screen shot 2014-11-13 at 2 08 05 pm](https://cloud.githubusercontent.com/assets/4965832/5034683/0b271f0a-6b3f-11e4-9267-689e8dc00e58.png)

**Comment by sloria** [comment]
@jlcohoon Is this still something you want? Does @huangginny's proposed UI meet your needs?

**Comment by jlcohoon** [comment]
It's definitely still something I'd like, and I think this solution is consistent with how we deal with this in search results. My comment now is, same as it is on the node refactor (https://osf.io/d72uk/wiki/Node%20Class%20Refactor/), that I'm inclined to click the first link, not the second one that might be truncated. That brings you to the project, not the component. 
Without thinking about it for too long, my best suggestion to avoid that issue is to give breadcrumbs not as part of the link:

![screen shot 2015-03-25 at 10 44 12 am](https://cloud.githubusercontent.com/assets/4965832/6827116/03438c06-d2dc-11e4-8332-989fdc290f64.png)

I also moved the contribution count to be on the same line as the progress bar (fewer lines of information in the box then). Since they're relative to one another in size, they could all be made to fit on one line like this.

**Comment by lbanner** [comment]
Unless disagreement on @jlcohoon 's suggestion .... (?) @huangginny Can you go ahead and make this change? Thanks.

**Comment by huangginny** [comment]
@lbanner will do

**Comment by huangginny** [comment]
@jlcohoon The breadcrumbs do not have links. Do you want me to add the links or not?
![screen shot 2015-03-25 at 3 27 43 pm](https://cloud.githubusercontent.com/assets/8628591/6833451/8bf06020-d303-11e4-9821-1ce8bb3faec6.png)

**Comment by jlcohoon** [comment]
No links, please!
