### ISSUE TITLE
[staging & production] github repo more specific warning message.

### ISSUE THREAD

**Issue by chennan47** [CenterForOpenScience/osf.io#1256]
Steps:
create a project with a component
link the project with a github repo
then go to the component and link it with the same repo
Then you got an error message

I believe there is a previous bug discussion making us forbid link the same addon repo to a project and its component, but we need a more clear error message

What happened
![screen shot 2014-11-17 at 9 41 06 am](https://cloud.githubusercontent.com/assets/4974056/5071337/e9f7f6d6-6e3d-11e4-9179-b53a1e6c6e0f.png)

**Comment by chennan47** [comment]
Confirmed that the behavior has been changed. So you can now actually link an addon to both parent and child project. The potential problem is that if you upload a file to that addon in the file page the change won't show up on the other file folder which linked to parent or child project untill you refresh it. It might confuse user.

**Comment by chennan47** [comment]
discussed with @brianjgeiger @sloria , the current front end can't support the synchronous update. This problem also occurs on the project organizer when you have a project in two folder on the same page that update one project won't update it in the other folder. In order to fix this problem, it needs a structure rework of the front end. As a result, put this to defer.

**Comment by lbanner** [comment]
Agreed @chennan47

**Comment by nanchen47** [comment]
The discussion leads a different problem which is issue https://github.com/CenterForOpenScience/osf.io/issues/280. Closing this one in favor of that one.
