### ISSUE TITLE
[production] PDF rendering fails silently in Safari for S3 and OSF Storage

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/osf.io#1257]
# Steps
* View the file detail page for a PDF stored in an S3 add-on in Safari (e.g. https://osf.io/neijc/)

# Expected
* The PDF is rendered

# Actual
* The PDF never renders, and no errors are thrown in the console.

This doesn't appear to be a cross-domain issue, since no errors are thrown. Other files that typically throw cross-domain errors, including images, work fine. This issue also affects PDF rendering in Safari in the new OSF Storage add-on. Thanks @GaryKriebel for originally reporting this.

**Comment by sloria** [comment]
This should be fixed on develop with the latest changes to MFR
