### ISSUE TITLE
Serialization for projects with many components is slow

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#1258]
## Steps
1. Go to a project page for a project with 200 components
2. Go to a project page for a project with 2000 components
## Expected

The page will load quickly, and maybe take a while to finish rendering all of the components.
## Actual

The first project takes a few seconds before the page starts to load. The second project takes a couple of minutes.
## Likely solution

Do not recursively serialize the project before rendering the Mako page. Just load the necessary data for the main project, then asynchronously load the components and pointers. If need be, paginate or otherwise limit the scope of data loading/rendering.

Related to #1160 and, tangentially, #1211.

**Comment by nanchen47** [comment]
@sloria any update on this one?
