### ISSUE TITLE
[Project Organizer] Shows dialog to delete multiple files from smart folder

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#1261]
Steps
--------
1. On project organizer, expand 'All my project' smart folder
2. Select at least two projects

Expected
------------
Items would be selected but that's all

Actual
---------
It brings up the dialog that has the option to remove multiple items from the folder. Clicking the button gives an error.

Possible solution
-----------------------
In onSelectedRowsChange, check to see if either the parent folder of the sample selected item has the 'isSmartFolder' flag. Optionally, check to see if the permissions of the item being selected has the 'canMove' permission flag set to false. If either of those are the case, do not show the dialog.

**Comment by caneruguz** [comment]
@brianjgeiger This is no longer an issue right?

**Comment by brianjgeiger** [comment]
Correct
