### ISSUE TITLE
[feature request] Filter for Search

### ISSUE THREAD

**Issue by KatyCain526** [CenterForOpenScience/osf.io#1266]
I have been exploring the search feature and I've found it to be less than intuitive when it comes to filtering out results. It would be useful to filter out specific keywords, like "posters" specifically.

**Comment by nanchen47** [comment]
The search backend actually support the filter, just need some front end work to make this be obvious to user.

**Comment by fabianvf** [comment]
Yes, this is definitely a UI issue primarily.

**Comment by Ghalko** [comment]
One thing that will ameliorate the * problem is by appending the * when the search is blank. This would at least address part of that issue.

Can we prepend and append "+" and "-" to a tag? If you hit + it adds it to the search, if you hit - it add the negative. This would mostly be in the results.

Or better on hover the symbols appear at either end? Just throwing ideas out there.

**Comment by Ghalko** [comment]
Here are two proofs of concept coming from different avenues: 
- http://jsfiddle.net/76zfycdz/

![hoverx](https://cloud.githubusercontent.com/assets/5169088/7071249/304e600e-deb2-11e4-9228-993caafbd4cf.gif)

With the fiddle I think using a fa-times-circle would work quite nicely.

**Comment by caneruguz** [comment]
@lbanner  @GaryKriebel  This issue has ready tag but the PR was merged. The issue needs to be updated.
