### ISSUE TITLE
[dev] Update modular-file-renderer

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1273]
The OSF is currently using an out-of-date, vendorized version of the MFR. We should remove this old version and use more up-to-date package [here](https://github.com/CenterForOpenScience/modular-file-renderer).

@asmacdo did much of this work in https://github.com/CenterForOpenScience/osf/pull/886 . @mfraezz , please take a look at this PR and see what else needs to be done.

All filetypes that were able to be rendered with the old version must also work in the new version.

**Comment by samanehsan** [comment]
Now that the MFR updates are in production, can this issue be closed? @mfraezz @lbanner @GaryKriebel

**Comment by lbanner** [comment]
Sounds good too --
