### ISSUE TITLE
Getting Ready navigation bar cuts into footer

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#1297]
![screen shot 2014-11-24 at 10 50 50 am](https://cloud.githubusercontent.com/assets/8591162/5167687/dde26694-73c7-11e4-8994-5e4751a4785f.png)

**Comment by GaryKriebel** [comment]
This is no longer an issue.
![screen shot 2015-02-24 at 10 46 38 am](https://cloud.githubusercontent.com/assets/9437946/6352709/7c1c9c66-bc12-11e4-9de5-8826cbf872fe.png)
