### ISSUE TITLE
[osfstorage] Caching functionality hashes based only on file content

### ISSUE THREAD

**Issue by mfraezz** [CenterForOpenScience/osf.io#1317]
# Steps
* Create project with two content-identical files with different file names/extensions 
* Render one of the files
* Attempt to render the other

# Expected
Second file would be rendered and then cached as though it were a unique file.

# Actual
The cache entry for the first file is displayed, regardless of the renderability of either file. Two test files Word.doc (not renderable) and Word.docx (renderable) I've used triggered this behavior.

**Comment by GaryKriebel** [comment]
This is no longer an issue.
