### ISSUE TITLE
[OSF registrations] Feature: When registering a project add an option to select the discipline - add as a tag

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#1332]
Another useful item, but not as urgent if it has any complexity.  If trivial, then great to sneak in.

-------------
Use the National Academy of Sciences breakdown of scientific disciplines to populate the drop-down list.

Make it easy for visitor to OSF registry page to view registrations for particular disciplines: see issue #1331 

Bonus: add open field in registration to encourage adding more tags (could be pre-populated with the current project tags)

**Comment by nanchen47** [comment]
Same issue as 2954. Continue discussion there.
