### ISSUE TITLE
Figshare deauthentication banner language fix

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1335]
# Steps
For this, it is helpful to have two user accounts:
1. Create a project where both accounts (A and B) have admin access.
2. Using account B, enable and authorize Figshare for the project but do not choose any content to link. The configure addons in settings page should look like this: 
![screen shot 2014-12-03 at 11 07 44 am](https://cloud.githubusercontent.com/assets/5975444/5284186/a2833f18-7ae0-11e4-88f6-3f06dd80eb6a.png)
3. Using account A, remove user B as a contributor on the project and save changes.

# Expected
When removing a contributor, a banner should show across the screen saying that authentication information for Figshare was deleted since it was authenticated by user B (who is no longer a contributor on the project). 

# Actual
The banner pops up, but with a language error: 
![screen shot 2014-12-03 at 11 25 30 am](https://cloud.githubusercontent.com/assets/5975444/5284229/ec3a9eee-7ae0-11e4-9a7b-cd56bef1aae9.png)
"Because Figshare add-on for this None..." 

If you perform the same steps but *do* choose to link content this time, here is the banner: 
![screen shot 2014-12-03 at 11 41 32 am](https://cloud.githubusercontent.com/assets/5975444/5284321/5c854c8a-7ae1-11e4-8605-966cf36c3d24.png)

The numbers refer to an article, as shown by this banner that gives info about public/private Figshare articles:
![screen shot 2014-12-03 at 11 41 13 am](https://cloud.githubusercontent.com/assets/5975444/5284336/705a7226-7ae1-11e4-92cc-21b0069f13e8.png)

**Comment by lbanner** [comment]
Looks to be completed with #1360
