### ISSUE TITLE
[filebrowser] "data is null" error on first load

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1336]
When loading the Files page of the RPP, I got the following error in the JS console:

```
data is null
```

The context includes these lines of HGrid (~L2131):

```js
    if (Array.isArray(data)) {

      toAdd = data;

    } else { // Data is an object with a `data` property

      toAdd = data.data;

    }
```

It appears that the server is returning `null` when loading the contents of the folders.

I haven't been able to reproduce the issue reliably (when refreshing the page, the error goes away).

**Comment by caneruguz** [comment]
@Steve is this still an issue in light of recent release?

**Comment by sloria** [comment]
Yes, this can be closed.
