### ISSUE TITLE
[staging & production] No error when authorizing two users' addon accounts for a project

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1338]
# Steps
1. With two different tabs (I suggest an incognito window), log in to two different user accounts (A & B).
2. Navigate to a project where both users are admins.
3. Go to Settings then Configure Addons. 
4. If it has not already been done, deauthorize Dropbox/Figshare/GitHub (have not tried with S3 or Dataverse, but I presume it is the same functionality as for the other addons).
5. Refresh the page on both tabs
6. Using user A's account, press Create/Import Access Token for an addon and wait for Success message.
7. Without refreshing the page, press Create/Import Access Token for the same addon using user B's account.
8. Refresh the page on both tabs.

# Expected
I expected that trying to authorize the same addon for user B would prompt some sort of error message saying that the addon has already been authorized using user A's account. 

# Actual
No such message pops up. Instead, user B proceeds as normal and does not receive a message saying that user A has already authenticated the addon. When user A refreshes the page, he will see that user B is now the one who has authenticated the addon and all of user A's files/repos/etc will be gone. 

After step 7 and before step 8 (no page refresh), it appears as though different two users have authenticated Dropbox on the same project.
![screen shot 2014-12-03 at 12 57 12 pm](https://cloud.githubusercontent.com/assets/5975444/5287508/9218a734-7afa-11e4-8a9e-b2455db45983.png)
Upon refresh, both windows show Yogi Bear's info.

# Suggestions
I suggest some message appears when user B tries to authenticate an addon that has already been authenticated by another user. Perhaps it could say something along the lines of "Addon_name has already been authenticated by User A. If you would like to override their authentication and replace it with your own, press OK. If not, press Cancel." 
The wording could obviously use some help, but that's the jist.

**Comment by nanchen47** [comment]
Will be considered when it comes with the chance to refactor the whole website.
