### ISSUE TITLE
Modals overlap with growlbox error messages

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#1340]
Steps
--------
On develop, in the code for adding a link to a large project, change the submit function so that it fails. I did this by changing this URL to something that does not exist: https://github.com/CenterForOpenScience/osf.io/blob/develop/website/static/js/pointers.js#L95

Expected
------------
I expected the modal to go away, showing the growlbox error message. 

Actual
--------
The growlbox error message shows up while the modal is still present, making it difficult to see: 
![screen shot 2014-11-25 at 5 54 10 pm](https://cloud.githubusercontent.com/assets/6414394/5193202/950e5c10-74cc-11e4-8887-1b7255da52ed.png)

Possible Solutions
-------------
- Dismiss the modal when an error occurs so that the growlbox can be seen 
- Show the error message in the modal 

All modals on the OSF should be checked for this behavior.

**Comment by brianjgeiger** [comment]
I was expecting that an enterprising intern would take this one on. A simple task repeated, so a good way to learn about variations in bootboxes and knockout and the like.
