### ISSUE TITLE
[OSF Registration] Not obvious when a project was registered

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#1342]
Behavior: A registration does not display the timestamp when a project was registered. It displays a timestamp of "last updated." There is a timestamp + note of registration in the log of the project, but not the log of the registration. 

![screen shot 2014-12-04 at 10 07 24 am](https://cloud.githubusercontent.com/assets/7749914/5300553/39b54188-7b9f-11e4-969f-d33c55669a17.png)

Expectation: There would be a clear indicator of when the project was registered. 

Proposed Solution:
In the blue box, add registration timestamp:
"This component is a registration of this component; the content of the component has been frozen and cannot be edited. This component was registered [timestamp]."

**Comment by saradbowman** [comment]
Reopening this issue, as the "Registration date" has disappeared from registrations. 

Here is a screenshot of what the header on the registration looked like 1/27/15:
![screen shot 2015-05-11 at 3 42 04 pm](https://cloud.githubusercontent.com/assets/7749914/7573579/b59225ba-f7f4-11e4-8ad8-ae18d1701ac0.png)


This is what the registration looks like today:
![screen shot 2015-05-11 at 3 42 27 pm](https://cloud.githubusercontent.com/assets/7749914/7573568/ab60185e-f7f4-11e4-817b-c0bf619677ca.png)


You will note that the date last modified is 4/13/15, even though the project was registered in October 2014. The corresponding date for this registration is correct on the registrations tab:

![screen shot 2015-05-11 at 3 44 05 pm](https://cloud.githubusercontent.com/assets/7749914/7573620/f4ab9060-f7f4-11e4-95a6-2cdd97efc7bf.png)



ping @GaryKriebel

**Comment by GaryKriebel** [comment]
Per a discussion with @JeffSpies and @HarryRybacki .... the following request seems to be the desired solution:
https://github.com/CenterForOpenScience/osf.io/issues/971

**Comment by JeffSpies** [comment]
I see that as a counter argument. Their point is that the date the project was updated BEFORE registration is important. That's fine, but probably hard to get with our current system given that log entries are happening for projects post-registration

Let's start here, Why are log entries happening post-registration?

**Comment by HarryRybacki** [comment]
This might be too confusing but perhaps we have three date(time)s presented to users from a registration page.

1. Date this registration was created
1. Date the parent project was created
1. Datetime the parent project was last modified?

**Comment by GaryKriebel** [comment]
@saradbowman @JeffSpies @bnosek ... thought's on Harry's question?

**Comment by HarryRybacki** [comment]
@JeffSpies I'm not sure how loggable actions on the parent of a registration would affect the logs on the registration itself. I manually ran through some test scenarios and the registrations logs were unmodified. 

Three fields are used for the template:
1. date_created -- pulled from Node.date_created -- copied from the parent project when the registration is created
1. date_modified -- pulls the date from the last item in Node.logs (returns empty string if None but that should never happen)
1. registered_date -- pulled from Node.registered_date (returns empty string if None)

**Comment by bnosek** [comment]
Creation date/time of parent project and creation date/time of registration are definitely essential.  What is the desire for the third - just so that someone knows if there is new stuff at the parent project to look at when they are at the registration?  

I don't see a problem with adding that info as long as we aren't crossing over into the territory of over-providing information when only a small portion would desire it and they'd get it with a single click.

**Comment by HarryRybacki** [comment]
@bnosek the third (date_modified) is, or at least should be, the date of the last logable action on the registration e.g. making it public **not** the date of the last logable action on the parent. I can't recreate that locally. Either way, I agree that it doesn't make sense to show the date of the last logable action on the parent.

**Comment by bnosek** [comment]
And, I don't think we need to show the last loggable action on the
registration as a general concept.  The kinds of actions that one can
perform are extremely limited.  The one that is of interest to surface is
"Date made public".  That way, the reader would know if the registration
had been embargoed and for how long.

**Comment by HarryRybacki** [comment]
Okay, well I propose we make the template have distinct **Date Parent Created** and **Date Registration Created** fields now. Once embargoes are in place adding the **Date Registration Made Public** will be a one line addition from the Embargo model.

**Comment by sloria** [comment]
The header now shows the Date Registered. @saradbowman Let me know if any further changes need to be made.

Closing the issue for now.

**Comment by saradbowman** [comment]
looks good! thanks!
