### ISSUE TITLE
[github] Uncaught GithubError when requesting a file > 1 Mb

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1344]
Caught by Sentry:

```
Stacktrace (most recent call last):

  File "framework/routing/__init__.py", line 96, in wrapped
    data = fn(*args, **kwargs)
  File "website/project/decorators.py", line 138, in wrapped
    return response or func(*args, **kwargs)
  File "website/project/decorators.py", line 181, in wrapped
    return func(*args, **kwargs)
  File "website/addons/github/views/crud.py", line 110, in github_view_file
    ref=sha or branch)
  File "website/addons/github/api.py", line 189, in contents
    return self.repo(user, repo).contents(path.encode('utf-8'), ref)
  File "github3/repos/repo.py", line 427, in contents
    json = self._json(self._get(url, params={'ref': ref}), 200)
  File "github3/models.py", line 100, in _json
    if self._boolean(response, status_code, 404) and response.content:
  File "github3/models.py", line 121, in _boolean
    raise GitHubError(response)
GitHubError: 403 This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.
```

**Comment by chrisseto** [comment]
@sloria Mind moving this to hold as it will be fixed when the file details page is moved to waterbutler?

**Comment by GaryKriebel** [comment]
@sloria and/or @chrisseto .... now that waterbutler files page is live, is this still happening?

**Comment by nanchen47** [comment]
now when you trying to upload a file bigger than 1 MB to github through osf, you will get a warning as
![screen shot 2015-04-04 at 1 26 14 pm](https://cloud.githubusercontent.com/assets/11743657/6993792/3abeda74-dace-11e4-9ccc-3706bd301c37.png)
however the warning will disapper after a few seconds and then what you will see is 
![screen shot 2015-04-04 at 1 25 59 pm](https://cloud.githubusercontent.com/assets/11743657/6993793/509b5f7a-dace-11e4-95fb-9a7000ba3d15.png)
and it just stay like that and nothing happens. We probably should just let user know that file >1MB can't be uploaded through osf to github. Thought? @chrisseto @sloria

**Comment by chrisseto** [comment]
When moving and copying comes out the limit will be increased to 100MB

**Comment by samanehsan** [comment]
Closing this issue since an error message is now shown to the user if they try to upload a file over the limit. As for the grayed out file persisting afterwards, that issue has been filed in #2822.
