### ISSUE TITLE
[dev] Improve mocking of 3rd party HTTP APIs

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1363]
@samanehsan found that we hit a Github API rate limit in a Travis Build: https://travis-ci.org/CenterForOpenScience/osf.io/builds/43103862 .

This indicates that one or more of the tests aren't properly mocked.

Mocking of 3rd party APIs is currently a manual process and thus very error-prone.

I propose we use a more automatic solution such as [httpretty](https://github.com/gabrielfalcao/HTTPretty) (h/t @jmcarp) in order to make testing easier and to prevent accidental requests to 3rd-party APIs.

**Comment by samanehsan** [comment]
@mfraezz @lbanner @GaryKriebel, might we close this issue now that the corresponding PR has been merged?

**Comment by lbanner** [comment]
Can, yes -- I'll close unless I hear differently from @sloria
