### ISSUE TITLE
[presentation service] possible to modify single event content?

### ISSUE THREAD

**Issue by AndrewSallans** [CenterForOpenScience/osf.io#1365]
BITSS2014 (https://osf.io/view/bitss2014/) won't be offering posters, so it doesn't make sense to include that in the title, "add your poster or talk", or in the instruction section.  Is it possible to have this as a configuration choice as well?

**Comment by jmcarp** [comment]
Shouldn't take more than an hour, plus testing.

**Comment by nanchen47** [comment]
@AndrewSallans has this problem been addressed yet?

**Comment by AndrewSallans** [comment]
I don't believe that this has been done.  

cc:  @saradbowman @jolene-esposito

**Comment by saradbowman** [comment]
Not done yet to my knowledge
