### ISSUE TITLE
[staging & production] Figshare file rendering is not immediate - gives error

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1370]
# Steps
1. Authorize Figshare for a project (make sure your figshare folder is public so that files will render)
2. Immediately after authorizing Figshare, go to the files page and click on a file. 
3. If the file renders, upload a new file to the Figshare folder via drag & drop and immediately click on it after upload.

# Expected
I expect that the file would render immediately after upload success.

# Actual
Clicking on a file immediately after upload or visiting the files page gives unable to resolve error. Waiting a few seconds and refreshing the page correctly shows files rendered. I talked with @brianjgeiger about this, and he said it is likely due to the time it takes for OSF to communicate with Figshare. If this is indeed the case, I suggest having an error message that says 'Wait a sec while we communicate' or grey it out until the communication is complete or something like that.

**Comment by nanchen47** [comment]
@chrisseto has fixed this problem.
