### ISSUE TITLE
[production] Long string in wiki overruns project overview page

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#1373]
Behavior: A long string in a wiki (i.e. a long URL) runs over the "wiki" area in the project overview page:

![screen shot 2014-12-08 at 1 14 40 pm](https://cloud.githubusercontent.com/assets/7749914/5344529/365f0504-7ede-11e4-96bc-62ce138bd08e.png)

Expected: String would be truncated or forced to wrap to the next line so as not to run into the "components" area of project overview page. 

Possible solution: I think it makes most sense to truncate the string.

**Comment by jlcohoon** [comment]
any updates on this?

**Comment by lbanner** [comment]
@caneruguz This in your arena? Maybe can/will be tackled via you and @brianjgeiger with 0.25.0 Wiki improvements?

**Comment by brianjgeiger** [comment]
This is a tiny change that nearly anyone could do in a hotfix if we wanted. Should just be adding {word-wrap: break-word;} to the css for the wiki widget.

**Comment by lbanner** [comment]
@huangginny You feel like knocking this one out? TY

**Comment by GaryKriebel** [comment]
I am not seeing this issue's behaviour.
![screen shot 2015-02-24 at 11 10 31 am](https://cloud.githubusercontent.com/assets/9437946/6353199/e5cf2e82-bc15-11e4-944e-5a38391006f8.png)
@jlcohoon and/or @saradbowman can you confirm?

**Comment by saradbowman** [comment]
I am still seeing it:

![screen shot 2015-02-24 at 12 02 57 pm](https://cloud.githubusercontent.com/assets/7749914/6354385/2ae3f906-bc1d-11e4-877e-5905f94b3b7b.png)

**Comment by GaryKriebel** [comment]
This is an issue with Chrome and Safari..... works fine with Firefox

**Comment by caseyrollins** [comment]
@lbanner @GaryKriebel I can quickly fix this.

**Comment by caneruguz** [comment]
FYI, site.css already has this helper class:
```css
.break-word {
    word-wrap: break-word;
}
```

so this will work 

```html 
<div class="break-word">
  longlonglonglonglonglongtext
</div>
```

**Comment by lbanner** [comment]
OK @caseyrollins  -- switched from @lyndsysimon -- he has other priorities in any case -- TY!
