### ISSUE TITLE
[hgrid/treebeard] Download count of deleted items - discussion

### ISSUE THREAD

**Issue by caneruguz** [CenterForOpenScience/osf.io#1376]
#### Steps: 
1. Open Files page in any of the projects
2. Upload a file
3. Download the same file, refresh
4. The download count should be 1, now delete the file
5. Reupload the same file.
6. Download the same file, refresh.
7. Now the download count is 2. 

### Actual:
The download count increments from the history of that file and does not reset to 0 when deleted.

#### Expected:
This is the discussion part. Here is an argument why it should reset:
- The user may be adding a file that has the same name but nothing else in common. In this case it looks like this brand new file has already been downloaded multiple times. Although technically this file has never been downloaded.
- The user has uploaded a file with the same name as one that is once deleted but they don't remember adding this file. When they see that the download count continues from an n number they will think this is a bug. 

I think a file is not the same as a wiki page, once deleted that file's download count should be set to 0. 

Alternatively we can save "All Time" Downloads, vs "This version" downloads. All time downloads can be shown in the File View page next to the version number.

**Comment by nanchen47** [comment]
same issue as https://github.com/CenterForOpenScience/osf.io/issues/1690. Close this one and continue discussion there.
