### ISSUE TITLE
[staging & production] Adding asterisks for partial name matching does not work in Add Links search

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1390]
# Steps
1. Navigate to a project where you are able to add links
2. In the search bar, type the name of a unique project and/or component to make sure it shows up (for mine, I used *Unicorn*)
3. Using Lucene search syntax, search with an asterisk for partial name matching:
     - Search for the beginning of the project/component name using an asterisk (eg, *icorn)
     - Search for the end of the project/component name using an asterisk (eg, Unico*)
     - Search for the middle of the project/component name using an asterisk (eg, Unic*n)
     - Search for the middle of the project/component name using two asterisks (eg, \*ico\*)

# Expected
Just as using asterisks for partial name matching works in site-wide search and contributors search, I expect that it would act in the same way here since all three searches use elastic search with Lucene search syntax.

# Actual
In searching for links to add, adding asterisks does not yield any results. Instead, searching for part of a name without asterisks yields the same results as using the asterisks would. In the examples above, the searches would look like the following:
- icorn
* Unico
* There is no substitute here since the asterisk is in the middle of the word.
* ico

# Solutions
Not sure why the asterisk thing doesn't work in this one case, but it is confusing. Perhaps as a solution we can add an info button to the Add Links search to let users know of the change in syntax?

**Comment by nanchen47** [comment]
Will be considered when we enhance the search function. Thanks.
