### ISSUE TITLE
[Staging and Production] ProjectOrganizer: Linked and then deleted project persist in childrenCount 

### ISSUE THREAD

**Issue by caneruguz** [CenterForOpenScience/osf.io#1410]
#### Steps: 
1. Create a project called "To Delete" (name is not essential) 
2. Create a project called "Parent Project" 
3. Create a subcomponent under "Parent Project" 
4. Link "To Delete" to " Parent Project" so that "Parent Project" has inside it the "To Delete" as a link
5. Delete project "To Delete"
6. Go back to Project Organizer and check the returned json for "Parent Project" 
7. Delete the sub component
8. Check the returned json for "Parent Project" 

#### Expected:
The field *childrenCount* should give the actual number of children without including the now deleted "To Delete" link or the sub component

#### Actual:
The field *childrenCount* shows the number that INCLUDES the deleted link and subcomponent. 

#### Repurcussions
Not many at the moment since the deleted project neither shows up as a link nor does the folder look toggled (although by looking at the code there should be a toggle there). However the value of childrenCount is wrong and will be unreliable, may also break other things. For instance Treebeard is using it as a check to show toggles. 

The children count in this example is wrong (You can check through https://staging.osf.io/api/v1/dashboard/-amp) 
![screen shot 2014-12-17 at 2 08 46 pm](https://cloud.githubusercontent.com/assets/1314003/5477108/50e7b212-85f6-11e4-8194-6f93465d2850.png)

**Comment by lyndsysimon** [comment]
IMO, the `Pointer` is distinct from the node, and should remain when its `Node` is deleted. Calling `is_deleted` on the `Pointer` is passed down to the `Node`, so it seems like we could treat them exactly the same.

**Comment by caileyfitz** [comment]
Hey I just checked this and I think it may not be an issue anymore. Can you confirm @brianjgeiger?

**Comment by brianjgeiger** [comment]
Did you check the json @caileyfitz ?

**Comment by caileyfitz** [comment]
Oh, no @brianjgeiger

**Comment by GaryKriebel** [comment]
Looking for updates concerning if this is still an issue.  @sloria @brianjgeiger @caneruguz

**Comment by brianjgeiger** [comment]
I've decided to just not count the children, rather than deleting the pointers. It was a much faster change than the discussion. If we want to delete pointers later, that can be a separate thing.

**Comment by lbanner** [comment]
Cool! ..... Your hotfix is merged -- shall we close this?

**Comment by brianjgeiger** [comment]
I'll do a quick test once it's on staging to be sure.
