### ISSUE TITLE
Custom Icon Font

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#1414]
FontAwesome is cool, but it is somewhat limited. In our case, it doesn't have good icons for projects, components, and smart folders. Any single icon set is going to have things, and multiple sets of icons will take up space.

We should consider using a service like http://fontastic.me to create a custom icon set that works for us. You can include the FontAwesome glyphs into the set (hopefully using the same names to allow us not to have to change everything by switching). If we can choose from multiple icons sets, add our own icons as necessary, and not have to jump through major hoops to change/upgrade font icons, then I think our lives will be easier and our site prettier.

**Comment by caneruguz** [comment]
We have found icons that work for some of our metaphors and the icons are in production. I think overall custom icon font is a good idea but not for the short term. I would keep this idea in the backburner but remove it from the issue tracker. Thoughts? 

In any case this should not have a Ready tag but rather discuss. If we went for this task we would still need to clarify which icons. 

@lyndsysimon @brianjgeiger

**Comment by brianjgeiger** [comment]
That's fine. Though we could take the first step of converting all the icons we currently use into a custom font, so it would reduce the amount of data transfer and get us ready to add icons easily. That being said, this is not a huge priority, it just gives us better flexibility down the line.

**Comment by lbanner** [comment]
OK ... removed 'ready' and ping: @erinmayhood for possible Epic task consideration. TY.

**Comment by nanchen47** [comment]
Will be considered in later enhancement.
