### ISSUE TITLE
[Staging & Production] Dropbox: Inconsistent warnings to user about deletion of files

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1415]
## Steps
1. Go to the user setting and authorize your Dropbox account.
2. Now go to a project and go into the settings tab, here authorize dropbox for this project. 
3. Click ok and then choose the files and folders from Dropbox to link to your project.
4. Return to the project files page. 
5. Click on the grey 'X' next to a file to remove that file that is linked to the project through your dropbox. You will get this user warning (hit cancel):
![screenshot 2014-12-18 11 02 34](https://cloud.githubusercontent.com/assets/9381062/5491248/6c6b2578-86a5-11e4-8432-4fa2845f0b08.png)
6. Now click on the file name to go to the file page and render an image.  Click on the red 'delete' button.  You will see this user warning:
![screenshot 2014-12-18 11 05 02](https://cloud.githubusercontent.com/assets/9381062/5491285/cf9e177c-86a5-11e4-9698-69829239d3f3.png)

Notice the awesome buck that I bagged!  My first one!!!!

## Expected
I would expect that the language/description in error messages to a user regarding the same function would be the same.  Specifically that it will be removed from your dropbox account upon deletion.

## Actual
The two error messages given when trying to delete a dropbox linked file are different.  One states that the action is 'irreversible' and the other 'Are you sure you want to delete IMG_9387.JPG from your Dropbox?'.  When both are going to be permanently deleted from the OSF and from the linked dropbox account, the user should be clearly warned of the implications of the action.

Also, when deleting a file from the file page that is uploaded from the desktop and not through dropbox, the error message is 'Are you sure you want to delete *file*?'

**Comment by brianjgeiger** [comment]
@chrisseto Could you mention in your PR that this issue will be fixed when it's merged?

**Comment by lbanner** [comment]
@brianjgeiger @chrisseto Files View PR, I assume? Got a number on that?

**Comment by chrisseto** [comment]
This is, currently, not fix in my PR. I can add this in if you'd like.

**Comment by lbanner** [comment]
Not too hard @chrisseto ?

**Comment by chrisseto** [comment]
@lbanner Not at all

**Comment by lbanner** [comment]
OK thanks @chrisseto -- yes, let's do it.

**Comment by GaryKriebel** [comment]
Everything looks the same now that WaterButtler Files has gone live.
