### ISSUE TITLE
[Staging & Production] Add-on: Dropbox configuration allowed for a registration

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1417]
## Steps
1. Go to a project and link dropbox to the project.
2. Now make a registration of that project.
3. Go to the settings of the registration and scroll down to the configure add-ons section.
4. Click to select a different folder from dropbox to link to the registration

## Expected
Registrations are  the freezing of a project and all of its content, therefore now editing should be allowed.  Also, a user should not even be tempted by the option to configure! I expect that the warning 'This project is a registration of this project; the content of the project has been frozen and cannot be edited'  would be true as stated.  

## Actual
The user can go to configure the dropbox add-on.  Can make a change and click submit.
![screenshot 2014-12-18 13 58 14](https://cloud.githubusercontent.com/assets/9381062/5494015/fe96950a-86bd-11e4-8b2b-12193b0b478f.png)
Furthermore, the error rendered asks the user to try again later.

**Comment by nicipfeiffer** [comment]
Some additional notes regarding Dataverse specifically, since it seems to have some unique behaviors:
## Steps
1. Go to a project with Dataverse linked.
2. Make a registration of that project.  Have your error console open.

## Expected
Since it is a registration the dataverse widget should not be populated on the overview page.

## Actual
The dataverse widget is not on the overview, but the error console reports an error: Uncaught No elements matching selector '#dataverseScope'.  

## Notes
With dataverse, once you have imported authorization you can currently change the dataverse user and studies that are linked...that seems incorrect for a registration.

**Comment by nicipfeiffer** [comment]
@sloria @JeffSpies @jmcarp @caileyfitz Bringing this issue back up again: consensus needed...I propose we disable all add-on configuration on a registration. It is imperative that a decision is made as it is affecting QA testing for the following PRs: 
https://github.com/CenterForOpenScience/osf.io/pull/1433 and
https://github.com/CenterForOpenScience/osf.io/issues/1428

**Comment by caileyfitz** [comment]
I think we should remove the configure add-on widget box (what Nici is saying)

**Comment by brianjgeiger** [comment]
I think the entire settings tab could go away. I do not believe it serves a purpose in a registration as things stand.

**Comment by GaryKriebel** [comment]
I agree with @brianjgeiger

**Comment by lbanner** [comment]
:+1: what @brianjgeiger said. Though, additionally, we do need language around add-on files not being frozen upon registration -- I like the 2nd bullet in @sloria 's earlier comment above (until we solve that via Archiver).

**Comment by caileyfitz** [comment]
+1 to @brianjgeiger's suggestion

**Comment by sloria** [comment]
@jmcarp has already changed the language to reflect the current behavior, which I put onto prod last night.

I have the code change for hiding the "Configure Addons" widget ready to go in https://github.com/CenterForOpenScience/osf.io/commit/aad05801c3a1d1436cd99684437af349e57b62c8 . If there are no objections to this by the end of today, I'll go ahead and merge it in

**Comment by JeffSpies** [comment]
What about for github? Repo name changes or is deleted, user can't change
the registration. Is that desired?

**Comment by brianjgeiger** [comment]
Github repos are identified by name and not an id? Hmph. So a registration with a github repo store as it stands could easily have its data swapped without notifying anyone (short of an investigation through the github repo itself)? I am looking forward to the archiver functionality going live.

**Comment by sloria** [comment]
@JeffSpies Valid point. Maybe we should disallow registering GH addons, like the other addons?

**Comment by lbanner** [comment]
A note on this issue: At Infrastructure meeting this week we decided to turn-off all Add-ons for registration (including) for GitHub -- other than OSF files -- via a HotFix (not an obstacle for 0.230 but critical in near term). I believe @jmcarp is working on this - Please reach out if more clarity is needed. FYI @nicipfeiffer Thanks!

**Comment by sloria** [comment]
As of #1433 , the "Settings" tab is no longer shown for registrations.
