### ISSUE TITLE
ampersand rendered in html in search results

### ISSUE THREAD

**Issue by mckidwell** [CenterForOpenScience/osf.io#1422]
<b>Steps:</b>
Search for "Dessalegn" in the search bar.

<b>Outcome: </b>
ampersand is rendered in html in search results:

![screen shot 2014-12-19 at 10 34 33 am](https://cloud.githubusercontent.com/assets/7945215/5506695/ae5b44fc-876a-11e4-8fe8-1caf206389f1.png)

ampersand renders correctly on actual project overview:

![screen shot 2014-12-19 at 10 35 49 am](https://cloud.githubusercontent.com/assets/7945215/5506709/d4e5d3ee-876a-11e4-8d92-75d802320c12.png)

<b>Expected Outcome:</b> Symbols should never be shown in HTML.

this is on production

**Comment by jlcohoon** [comment]
This is still occurring in most of my searches. Any updates?

**Comment by brianjgeiger** [comment]
There's a database migration that goes along with #1308 which will fix this. It won't be in 0.23.0, but should be in 0.24.0 or 0.25.0 at the latest. My guess is 0.24.0.

**Comment by lyndsysimon** [comment]
This will be resolved with #946, which is planned for release 0.24

**Comment by jlcohoon** [comment]
@lyndsysimon @brianjgeiger It's still not fixed...should I hold out for 0.25.0?

**Comment by brianjgeiger** [comment]
I would wait until the next Epic before anticipating this fix. March or so.

**Comment by brianjgeiger** [comment]
Since the underlying problem won't be fixed for a while, @chrisseto is going to apply a workaround that we had to use in the Treebeard grids. Should be in by 0.25.0

**Comment by sloria** [comment]
Closed by @chrisseto

**Comment by jlcohoon** [comment]
Still seeing this in some instances—are these trickier to work around or might they be able to get resolved as well?
![screen shot 2015-02-06 at 11 40 32 am](https://cloud.githubusercontent.com/assets/4965832/6083231/14da9b96-adf5-11e4-9c05-4bce021b5ed1.png)

**Comment by lbanner** [comment]
@chrisseto @brianjgeiger Insight? Should be resolved with #1308, but that's been put on the back-burner, after completion of current 30-month epic

**Comment by brianjgeiger** [comment]
We should see why this is happening at the very least.

**Comment by jlcohoon** [comment]
ps. This happens in the add contributors modal too: 
![screen shot 2015-02-09 at 2 57 49 pm](https://cloud.githubusercontent.com/assets/4965832/6114441/29410b14-b06c-11e4-9230-f91dccaf3e83.png)

But, this same project renders correctly in search results: 
![screen shot 2015-02-09 at 3 00 09 pm](https://cloud.githubusercontent.com/assets/4965832/6114474/5f147208-b06c-11e4-9b6d-581dd7c4cf90.png)

**Comment by mckidwell** [comment]
Just found that the ampersand is still being rendered as html in search results in some instances but not others (appears to be for component search results, but not project results in this case).

![screen shot 2015-02-16 at 3 06 53 pm](https://cloud.githubusercontent.com/assets/7945215/6231979/142b8aac-b697-11e4-9b92-be20e1346547.png)

**Comment by lbanner** [comment]
@mckidwell FYI: I am going to take your recent comment and post to a new issues around this - Freshen up the conversation. Thanks!
