### ISSUE TITLE
[production] GitHub Add On Doesn't Display Organizations You Own

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#1425]
_Behavior:_ GitHub Add-on returns your own repos and any repos for which you are on the team and have push access, but not repos that fall under an organization you own. 

Scenario: User A owns Organization A and created Repo 1 under that organization. User A thus owns the repo and can push to it, but is not included on a team. User A connects github to his OSF project, but Repo 1 does not show up in his list of available repos. _Work-around is User A adding himself to a team for Repo 1._ 

_Expected:_ All repos a user has push access to will display when the GitHub Add-on is enabled.

_Possible Fix:_ Request to list organizations through GitHub's API? https://developer.github.com/v3/orgs/#list-your-organizations

Related to a help desk ticket, case 3065.

**Comment by lyndsysimon** [comment]
@kushg - can you update this, even if it's only with a new estimate as to when you'll get to it?

**Comment by kushG** [comment]
Having a look into it now !

**Comment by kushG** [comment]
Currently the fix is to list all the repositories of the organizations to which user has access. This should be still open for discussion as there is no such way yet in github3.py to get the repositories to which user has write access. This fix only lists out all the repositories of all the organization that user has access to.

**Comment by lbanner** [comment]
@lyndsysimon @brianjgeiger @sloria Please let me know who is good to help discussion on this one w/ @kushG  --- And how big a deal this might be -- especially as I think we have few-to-none outside users taking advantage of GitHub?

**Comment by lyndsysimon** [comment]
I've closed the attached PR, and marked this is an intern task.

Whoever takes this on should take a look at the code @KushG added to make it work, and understand why that PR wasn't accepted. Based on his report on Github3.py's features, it may not be possible to do this entirely within that library - but it should be possible, one way or another.

**Comment by saradbowman** [comment]
As an FYI, I've received 3-4 more questions on the help desk about this
issue since the first report.

**Comment by lbanner** [comment]
OK

**Comment by hunterdayton** [comment]
A +1 bump on this from Desk case 12314, our most active engrXiv contributor. It appears the workaround for this no longer works, as he is both a team member of the desired repository and has admin privileges but is still unable to integrate the intended repo.

**Comment by Matherion** [comment]
I can confirm this no longer works. Adding yourself as collaborator or as team member for the repository in the organization has no effect. If I can assist in testing etc, let me know!

**Comment by asifm** [comment]
Not working. Would appreciate a solution to this.

**Comment by brianjgeiger** [comment]
This is a scope issue for authorizing the github addon. You need to re-authorize the addon, and be sure to add the organizations that you want to have access for in the oauth dialog. If need be, contact support@osf.io for extra information.

**Comment by BRosenblatt** [comment]
@asifm, we determined the issue and now have a help guide for connecting GitHub orgs here: http://help.osf.io/m/addons/l/837168-connect-to-a-github-organization

If you continue to have issues, feel free to follow up with us at support@osf.io.

**Comment by asifm** [comment]
@BRosenblatt That solved it. Thank you.

**Comment by lubianat** [comment]
Hello, the [help page](http://help.osf.io/m/addons/l/837168-connect-to-a-github-organization) @BRosenblatt posted is now broken. 

Are there any other workarounds?

**Comment by Matherion** [comment]
Is this the new one perhaps? https://help.osf.io/hc/en-us/articles/360019929813-Connect-GitHub-to-a-Project
