### ISSUE TITLE
private components indented too far in file tree

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1426]
In the file tree, private components are all listed together at the bottom, and are indented slightly more than other components, making them appear to be children. 
![indent](https://cloud.githubusercontent.com/assets/4965832/5538386/f96eb438-8a80-11e4-872f-f1d6acf5baa6.png)

They should be as equally indented as sibling components.

**Comment by sloria** [comment]
+1. @caneruguz Please take note to fix this in Treebeard/Fangorn.

**Comment by caneruguz** [comment]
In fangorn this is not an issue, private folders appear aligned with their siblings as expected. How can we tag this issue to revisit after 0.24?

**Comment by sloria** [comment]
Marked with "Hold" label, pending merge of treebeard/fangorn

**Comment by caneruguz** [comment]
This is what's happening now. Time to close this issue? @sloria @lbanner 

![osf___wiki_ui_workspace_files](https://cloud.githubusercontent.com/assets/1314003/6046586/95627bb0-ac71-11e4-8b7f-981e16fe01cf.png)

**Comment by lbanner** [comment]
Yes @caneruguz -- Got it -- Thank you!
