### ISSUE TITLE
files don't load on project load

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1427]
<h4>Steps to Problem</h4>
1. Visit a project and scroll so that you can see the file tree

<h4>Actual Outcome</h4>
1. <em>Sometimes</em>, the file loading progress bar spins infinitely and no files or components show up in the file tree
2. The console notes that a stylesheet for hgrid is not found
3. Refreshing the page loads all files successfully

Gif of problem here:
http://goo.gl/C3Blv1

<h4>Desired outcome</h4>
1. All files should load on the first try (ie. no refresh needed)
2. If files cannot load on the first try, then a timeout should occur and an error should be reported to the user

edited to add Gif

**Comment by sloria** [comment]
Yes, I have seen this before but have not been able to reliably reproduce it. I'm hoping that this will be fixed with the next release, which gets rid of asynchronous asset loading.

**Comment by caneruguz** [comment]
Not to mention treebeard will override the use of that loading bar so this issue should not exist thereafter.

**Comment by jlcohoon** [comment]
When is the next release? It's been doing this for weeks and happens about 50% of the time for me.

**Comment by brianjgeiger** [comment]
As soon as Monday, depending on how bug fixes go. Maybe a bit after.

**Comment by caneruguz** [comment]
this should be fixed now. everything about that loading experience is different.

**Comment by lbanner** [comment]
Good -- I will close this one. Thanks!
