### ISSUE TITLE
S3 registration file reference behavior

### ISSUE THREAD

**Issue by chrisseto** [CenterForOpenScience/osf.io#1428]
Current in the OSF when you register a project with the s3 addon attached we try to register the bucket by keeping a list of the current keys and their version ids.

This does not work nor has it ever worked.

Even when versioning is enabled on a bucket keys are given version ids *after* they are overwritten.
Meaning all the version ids being stored are just `None`.
So when you visit the registration all the files you see are still the latest.

We'd like to disable the functionality of registering the s3 addon until archiver is put into production.

I've run this by @sloria, @jmcarp, @icereval and they agree that it should be disabled.

Are there any additional thoughts or concerns on the matter?

For reference there are 3 registrations in prod that have s3 enabled, all of them are owned by us and are test projects.

@JeffSpies @lyndsysimon @brianjgeiger

**Comment by sloria** [comment]
As of #1433, all storage addons are not copied to registrations. Closing this for now
