### ISSUE TITLE
[Staging & Production] Dropbox: View File page reporting 500 internal server error

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1429]
## Steps 
1. Go to a project with the dropbox add-on linked
2. Go to the files overview page, choose a file from the linked dropbox folder
3. Click the file to go to the file view page
(Have the java console open)
4. Click the green download button

## Expected
The file view page should open, render a view of the file.  When the green download button is clicked the file should download.

## Actual
The file view page reports a 500 (INTERNAL SERVER ERROR) in the console.  Also, when the green download button is clicked, the page refreshes and the console reports the same 500 error and the file does not download.

![screenshot 2014-12-29 14 39 14](https://cloud.githubusercontent.com/assets/9381062/5572182/7ea20b3c-8f68-11e4-826a-f1f140f9c939.png)

**Comment by lbanner** [comment]
@nicipfeiffer I too have been unable to replicate this with other .jpg files -- If OK with you, we could have @caileyfitz try to reproduce (?) and if she is unable to, I recommend we close this one for now. OK?

**Comment by nicipfeiffer** [comment]
@lbanner and @caileyfitz I agree.  I removed the files from Dropbox and then added them again and now the download is successful, which I had attempted unsuccessfully previously.

**Comment by lbanner** [comment]
Cool! We'll close it up then -- Thanks!
