### ISSUE TITLE
PIWIK idSite is not found

### ISSUE THREAD

**Issue by icereval** [CenterForOpenScience/osf.io#1434]
https://osf.io/mfxpj/statistics/

![image](https://cloud.githubusercontent.com/assets/3111541/5593806/a6f037e2-91e5-11e4-8207-41a15493bf03.png)

**Comment by jmcarp** [comment]
@lyndsysimon

**Comment by lyndsysimon** [comment]
Not sure how this escaped my notice for two weeks. :-1:

I've resolved this specific issue, so I'm closing the ticket. We fixed a bug that was causing this to happen a few weeks ago, and migrated all known cases. I'm concerned that perhaps there has been a regression in the behavior that spawned this.

I'll investigate that possibility, but I'm closing this issue as this project is no longer broken.
