### ISSUE TITLE
[Staging & Production] Registration fails with all add-ons configured

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1435]
## Steps
1. Go to a project you have admin privileges on
2. Go to the settings tab and select all add-ons
3. Ensure there is a check by each add-on and submit
4. Now configure add-ons by: Import access tokens, Import credentials or authorize and giving an external link.
5. Link repos, files, folders, study or buckets and submit.  Confirm settings have been updated.
6. Go to 'registration' tab and create a 'new registration'

## Expected
A registration of the project would be made.  Appropriate user messages about add-ons would be given.

## Actual
The registration fails.  Either a modal/growlbox informs the user that the registration failed and/or console reports the error: GET https://staging.osf.io/api/v1/project/3j7d4/beforeregister/?_=1419964832873 500 (INTERNAL SERVER ERROR)
![screenshot 2015-01-05 12 55 27](https://cloud.githubusercontent.com/assets/9381062/5617213/27420e7e-94da-11e4-9e09-0a14229cfbb2.png)

**Comment by chrisseto** [comment]
Looking into it, seems to be an issue with the S3 add-on.

Did you by any chance remove and readd the add-on?

**Comment by nicipfeiffer** [comment]
@chrisseto I did remove and readd the S3 add-on and still get the 'error: registration failed'.

**Comment by chrisseto** [comment]
Sorry, did you remove and readd the add-on before you registered it?

That may be the cause of the issue.

**Comment by nicipfeiffer** [comment]
@chrisseto Yes, before attempting to register.

**Comment by chrisseto** [comment]
@nicipfeiffer found the issue just writing a few unittests before submitting the hotfix.

**Comment by nicipfeiffer** [comment]
@chrisseto Awesome!!  Thanks:)
