### ISSUE TITLE
[Staging & Production] Inconsistent search bar filter behavior on IE

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1448]
## Steps
1. Log in to the OSF/production using internet explorer
2. Also log in to the OSF/production using any other browser (chrome, firefox or safari)
3. In the search bar enter 'science'; do on both browsers
4. Should have 403 results or so
5. Now backspace/delete 'science' and type in 'brain' on both browsers and hit the enter key

## Expected
That the behavior would be the same from browser to browser for the same action. That the new search criteria entered would filter the results.

## Actual
The behavior is different on Internet Explorer than on other browsers.  Entering the new search 'term' and hitting enter does no action, hence the results are not filtered again.

**Comment by chrisseto** [comment]
Seems to be an issue with IE not reporting the updated value to knockout, I may have found a fix.

**Comment by brianjgeiger** [comment]
Interesting. I was expecting a form submission problem, since you can hit the magnifying glass button and it will search.

**Comment by chrisseto** [comment]
The value is updated when the field loses focus. So changing the element will "blur" the field where pressing enter will not.

**Comment by chrisseto** [comment]
Is this an issue in production as well?
