### ISSUE TITLE
[Mobile] Dashboard: Unable to upload a file

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1457]
## Steps
1. Using a mobile device log into the osf staging or production
2. From the dashboard try to upload a file

## Expected 
That by tapping the upload button there would be an action; a place to select photos at the least.  Or a message alerting the user that this is not available at this time.

## Actual
Nothing happens.  

## Notes
If a message appeared to let the user know that mobile file uploads are not supported might be helpful.  Also, maybe mentioning dropbox as a work around to the user to get files uploaded to their osf account without using the dashboard.

**Comment by caneruguz** [comment]
This process worked for me using an LG G3 phone with Android version 5.0. I was able to click the onboarding upload, select a photo and uplaod to a subcomponent and then view it in the files page. Might likely be something specific to which mobile device or software version.

**Comment by brianjgeiger** [comment]
Works on iOS 8, although it always sends it as image.jpg. It would be good to allow the ability to name the file under that circumstance.

**Comment by lbanner** [comment]
We might want to discuss this one -- how much do we want to support file-upload via mobile? File management is somewhat complex in mobile os, but for photos.

**Comment by nanchen47** [comment]
related issue https://github.com/CenterForOpenScience/osf.io/issues/2380

**Comment by caneruguz** [comment]
I think it's generally expected that people will not have much success on uploading from mobile mainly because in most cases the file system is not as open as on a computer. I think we should close this issue until we have good reason to open again. 

@lbanner @nanchen47

**Comment by nanchen47** [comment]
Totally agreed with @caneruguz
