### ISSUE TITLE
[production] Users with inconsistent `date_confirmed` and `date_last_login` fields

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/osf.io#1462]
# Expected
All users who have logged in have a non-null value of `date_confirmed`

# Observed
In production, 18 users have non-null values of `date_last_login` but null values of `date_confirmed`. Based on a user report to @mckidwell, these users can't reset their passwords (but I verified manually that it's still possible to log in).

To find users with inconsistent data, run: 
```python
User.find(Q('date_confirmed', 'eq', None) & Q('date_last_login', 'ne', None))
```

To fix, we would need to manually set the `date_confirmed` fields of the affected users. All affected users created their accounts in September or October of 2014, so this likely reflects a bug that's since been fixed, although I'm not sure what it might have been.

**Comment by jmcarp** [comment]
Based on discussion with @sloria, this reflects a bug in user claiming that was fixed in November 2014, and will require a simple migration to fix: affected users should have their `date_last_login` fields copied to `date_confirmed` and `is_registered` set to `True`.

**Comment by sloria** [comment]
@mfraezz is currently working on the migration script for this.

**Comment by GaryKriebel** [comment]
@sloria .... this can be closed, yes?

**Comment by nanchen47** [comment]
The fix has been merged in.
