### ISSUE TITLE
[Production and Staging] [Dataverse] JPG files don't render from Dataverse Add-on

### ISSUE THREAD

**Issue by kmjungersen** [CenterForOpenScience/osf.io#1463]
This file was uploaded to Dataverse and this is how it renders:

![screen shot 2015-01-08 at 1 33 50 pm](https://cloud.githubusercontent.com/assets/6546342/5668134/38206700-973b-11e4-8a3f-cd81311696f9.png)

I'm going to check out some other file types and see if this behavior happens there too.

**Comment by nicipfeiffer** [comment]
@kmjungersen and @jmcarp This also occurs when I try to render .pdf files
![screenshot 2015-01-11 21 48 30](https://cloud.githubusercontent.com/assets/9381062/5698432/9dcc99be-99db-11e4-9c39-562d4feb83c0.png)

**Comment by kmjungersen** [comment]
:+1:
