### ISSUE TITLE
Display of list of anonymous view-only links on public projects

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#1466]
Steps
-------
1) On a private project, create an anonymous view-only link
2) Turn the project into a public project
3) Look at the anonymous links

Expected
-------------
Because anonymous links don't do anything on public projects, there should be a warning that these links won't do anything

Actual
--------
Links look like links that will anonymize your project.

![screen shot 2015-01-08 at 4 48 56 pm](https://cloud.githubusercontent.com/assets/6599111/5671487/4f891ad4-9756-11e4-8071-3afd487bb5e9.png)

This came up during testing of anonymous view-only links.

**Comment by sloria** [comment]
@brianjgeiger Any suggestions as to where the warning should go? Should we just amend the help text below the "View-only Links" header?

**Comment by brianjgeiger** [comment]
I would be more obvious. I would make the visual look of the anonymous column indicate that such a functionality isn't a thing here, and also amend the text as you indicated. The look could be something like an overlay (kind of like we do with piwik stats on private projects), as simple as a strikethrough on the "Yes" in the anonymous column, or something in-between.

**Comment by sloria** [comment]
Added the following UI to the VOL table on public projects:

![osf___addons_testing_contributors](https://cloud.githubusercontent.com/assets/2379650/6066878/735b4fb0-ad3e-11e4-9735-6e1d4a43ef52.png)

@brianjgeiger Close this issue, or is there more to do here?

**Comment by brianjgeiger** [comment]
This should do. If we get confused again, we'll revisit.
