### ISSUE TITLE
[staging & production] 'Add poster or talk' button should be disabled for conferences not accepting submissions

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1471]
# Steps
1. Navigate to osf.io/presentations
2. Click on a conference that is not accepting submissions (as of 1/12/15, this is all of them)
3. At top of page, press *Add your poster or talk*

# Expected
Since the presentations page notes that the conference is no longer accepting submissions, pressing this button should either yield an error -- "This conference is no longer accepting submissions" -- or the button should be disabled or removed completely.

# Actual
The button is present on the page and appears to be enabled. Clicking the button appears to do nothing. No page reload, no message, no console error. The only thing is that *#submit* is appended to the end of the URL.

**Comment by lbanner** [comment]
Fixed by #1501 -- Deployed in 0.23.0 -- so I think we can close?
