### ISSUE TITLE
[production] Download Button Missing on File Renderer

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#1474]
Behavior: 

On (seemingly) one specific file, there is no download button on the file renderer page: 
![screen shot 2015-01-12 at 4 15 10 pm](https://cloud.githubusercontent.com/assets/7749914/5711147/380349ca-9a76-11e4-8adf-918f4d2670a8.png)
The file is here: https://osf.io/bu3mr/

There IS a download button on the file tab: 

![screen shot 2015-01-12 at 4 16 09 pm](https://cloud.githubusercontent.com/assets/7749914/5711166/56a676a4-9a76-11e4-9541-53fa0e7393a8.png)

I thought this may be related to files too large to display in the browser, but I have found both .jpg files (https://osf.io/k5bcg/) and another .pdf (https://osf.io/9xf6j/) too big to display, but both show the download button. 

Console displays this error when loading the file render page:
"Uncaught SyntaxError: Unexpected token ILLEGAL"

**Comment by brianjgeiger** [comment]
JS Errors in the MFR need to not break knockout. I wonder if there's an easy way to handle that (such as by modifying load order or similar).

**Comment by brianjgeiger** [comment]
No, I take it back, that's not the problem. 

```js
<script>
    $script(['/static/addons/osfstorage/storageRevisions.js'], function() {
        var revisionTable = new RevisionTable(
            '#revisionScope',
            'Tracing the Evolution of Starless Cores in a Molecular Cloud Simulation:  Comparisons with JCMT Data and Predictions for ALMA',
```

On the last like there, between the colon and Comparisons is a unicode line break (\u2028) that is not being handled, so the javascript is being broken.

**Comment by brianjgeiger** [comment]
I believe this will be fix with @lyndsysimon's Mako Safe HTML, but I have to look into it a bit more to be sure. That or we just have to sanitize the string. Since it's javascript in the source code, though, I'm fairly certain it's a Mako thing.

**Comment by GaryKriebel** [comment]
FYI, Mako Safe HTML will be pulled from 0.23 and will go shortly after 0.23 as a dot release or into 0.24 targeted for end of month-ish.

**Comment by nanchen47** [comment]
Checked on https://osf.io/bu3mr/. This problem doesn't exist anymore.
