### ISSUE TITLE
[Staging & Production] [UI] Info Modal partial obstruction by scroll bar

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1476]
## Steps
1. Go the the dashboard and click on the 'i' (info) for a project, registration or folder
2. While the modal is active, scroll up and down through the list of projects

## Expected
When a modal is active on the page; scrolling in the background would not interfere with the users' view of info in that modal.

## Actual
When a folder, project or registration info modal is active on the UI and the the user scrolls through the list of projects in the background the modal cannot be grabbed and dragged to move it from hindering the view of the project info in the background.  In addition, the scroll bar comes forward into the modal pane and obstructs some info display.
![screenshot 2015-01-12 22 30 01](https://cloud.githubusercontent.com/assets/9381062/5715620/9599ce36-9aaa-11e4-89ef-8899fc0205fc.png)

**Comment by GaryKriebel** [comment]
@nicipfeiffer, what browser were you using?  I am not seeing this with Chrome, Firefox, or Safari on staging.

**Comment by nicipfeiffer** [comment]
@GaryKriebel I'm using Chrome.  It does not occur on Firefox or Safari.

**Comment by brianjgeiger** [comment]
Confirmed in Chrome 38.0.2125.104 on Yosemite 10.10.1

![screen shot 2015-01-13 at 9 31 21 am](https://cloud.githubusercontent.com/assets/6599111/5722084/18880f04-9b07-11e4-97cf-dab1033a9427.png)

**Comment by GaryKriebel** [comment]
Looks like the fix is to upgrade chrome to 39.0.2171.95?
![screen shot 2015-01-13 at 9 32 08 am](https://cloud.githubusercontent.com/assets/9437946/5722104/50c6b898-9b07-11e4-9b69-9255012a01f2.png)

**Comment by brianjgeiger** [comment]
No, that didn't fix it for me.

**Comment by nicipfeiffer** [comment]
I am using 
![screenshot 2015-01-13 09 37 34](https://cloud.githubusercontent.com/assets/9381062/5722164/de70159a-9b07-11e4-92fb-3fba60d16b86.png)

**Comment by brianjgeiger** [comment]
Okay, @caneruguz and I have talked about it, and we have a plan to make this not a problem when Treebeard is released (should be the 0.24.0 milestone as things stand).

**Comment by caneruguz** [comment]
@lbanner This issue is resolved now with the new Project Organizer toolbar

**Comment by lbanner** [comment]
TY!
