### ISSUE TITLE
[staging & production] Some registrations showing None Contributions

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1478]
Seems to be related to #1318 

# Steps
1. Create a new project and add two components.
2. Link at least one add-on to the project and/or components.
3. Register the project
4. Return to the original project (not the registration) and click on the *Registrations* tab
5. Note the number of contributions listed under the registration information

# Expected
I expect that the number of contributions would be shown. Since components were created and add-ons were linked, the number of contributions should be non-zero.

# Actual
Registration widget shows None Contributions: 
![screen shot 2015-01-13 at 10 54 32 am](https://cloud.githubusercontent.com/assets/5975444/5723523/9995e53e-9b12-11e4-9519-c4d2e61e6b69.png)
despite there being contributions listed on the project overview page
![screen shot 2015-01-13 at 10 54 09 am](https://cloud.githubusercontent.com/assets/5975444/5723536/b416e606-9b12-11e4-9069-969025f03b92.png)

**Comment by huangginny** [comment]
@GaryKriebel This one is fixed now :) Please de-assign me and close this issue!

**Comment by lbanner** [comment]
Got it -- Thanks
