### ISSUE TITLE
[Staging & Production] Dataverse Hgrid error on Project overview page when attempting to drag and drop to upload

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1481]
## Steps
1. Go to a project and configure the dataverse add-on, linking a study with files that are released
2. Go to that projects' overview page and change the designation for the dataverse study linked from 'released' to draft'

![screenshot 2015-01-13 15 03 36](https://cloud.githubusercontent.com/assets/9381062/5728047/6672f5ca-9b35-11e4-9a33-11a3f39c1c91.png)
3. Once that has updated, drag and drop a file to the dataverse folder for upload

## Expected
A dataverse must be in the 'draft' configuration for a file to uploaded to a study.  If that criteria is met, then a file should be able to be uploaded.

## Actual
Files cannot be uploaded to a 'draft' dataverse study by way of drag and drop.  No action occurs when a file is dragged to the dataverse folder on the project overview page. 
The error console reports: Uncaught HGrid.Error: Upload permission denied.

**Comment by GaryKriebel** [comment]
@rliebz would this fall under the dataverse API?

**Comment by rliebz** [comment]
I'm not sure why this issue occurs. There is no reason that the behavior on the overview page should differ from the behavior on the files page.

**Comment by rliebz** [comment]
I have actually been able to replicate this in the files tab. It appears to be an issue with determining whether the dataverse is the released version or the study version. To reproduce:

1. Go to a project with the Dataverse enabled and visit the files tab
    - It may be important that the study has both released and unreleased files. Mine had both.
2. Click the dropdown to change the study from "Released" to "Draft"
3. Wait for HGrid to load the draft files.
3. Attempt to drag in a file. This should fail.
    - If you manage to drag the file in before HGrid is finished loading the draft files, it might succeed.
3. Additionally, click the name of the study to collapse the folder. The dropdown says "Released" when it should say "Draft".
    - This occurs whether or not you give HGrid time to load the files.
    - Draft files are displayed when HGrid is re-expanded, although the "Upload" and "Release" buttons are gone.

This leads me to believe that the study version is being reset to "Released" at some point(s) when it should not be. This would explain the permissions error, as the grid considers the study "Released" (uneditable) even though it displays it as a "Draft".

**Comment by lbanner** [comment]
@rliebz Worth an attempt to resolve prior to their release of updated API?

**Comment by rliebz** [comment]
As it stands, non-contributor file viewing with Dataverse should still be fine, but trying to manage files from the OSF is going to be particularly difficult for users. At the very least, it's worth an attempt.

**Comment by rliebz** [comment]
It appears as that step 5 that I outlined before is also an issue with the GitHub add-on. I'm going to go ahead and file that separately.

**Comment by rliebz** [comment]
This is no longer an issue as of the release of water butler, and can be closed.

**Comment by lbanner** [comment]
OK Thanks @rliebz
