### ISSUE TITLE
[staging/production] Input placeholders don't work in IE9

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/osf.io#1483]
# Steps
* Go to http://osf.io in IE9 while not logged in

# Expected
* Registration form includes placeholders

# Actual
* Registration form doesn't have placeholders, making it pretty hard to register

This is happening because IE <=9 doesn't support html5 input placeholders. To fix, we could conditionally show input labels in old browsers, or use a placeholder shim like https://github.com/mathiasbynens/jquery-placeholder.

![ie9](https://cloud.githubusercontent.com/assets/1633460/5740850/4ad0c1bc-9bd5-11e4-8295-626c76dcbcc2.png)

**Comment by GaryKriebel** [comment]
@jmcarp is showing input labels a really quick fix?

**Comment by lbanner** [comment]
We do have users on IE9 -- so this should be fixed .... @jmcarp @GaryKriebel make it a HotFix post 0.23.0 release?

**Comment by GaryKriebel** [comment]
If it is a really quick fix, I would even consider pushing it into 0.23.

**Comment by jmcarp** [comment]
@GaryKriebel adding labels (just in IE9) would be quick. The page would look different in IE( compared to modern browsers, but that seems tolerable.

**Comment by GaryKriebel** [comment]
I would think it would be tolerable as well.

**Comment by GaryKriebel** [comment]
@sloria @Ghalko has the fix gone live and thus closing this issue?
