### ISSUE TITLE
[staging] Attempt to register project gives Unable to resolve error

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1485]
# Steps
1. On any browser, go to a project
2. Click the Registrations tab and then **New Registration**
3. Select a registration option from the drop-down menu

# Expected
Selecting an option should lead the user to another page with a form and an input to type "register" to complete registration.

# Actual
Upon selecting an option, a user receives an Unable to resolve error
![screen shot 2015-01-14 at 10 35 50 am](https://cloud.githubusercontent.com/assets/5975444/5741465/2477a2ac-9bd9-11e4-87cd-3a0b8da8e9ff.png)

**Comment by GaryKriebel** [comment]
This is resolved with the following pull request -> https://github.com/CenterForOpenScience/osf.io/pull/1486

**Comment by sloria** [comment]
@GaryKriebel The fix has not been merged yet. This issue will automatically be closed when it is merged.

**Comment by GaryKriebel** [comment]
@sloria whoops.... mea culpa... need to click the green button, not the grey button
