### ISSUE TITLE
Go/Nogo for release 0.23.0

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1490]
milestone: https://github.com/CenterForOpenScience/osf.io/issues?q=milestone%3A%220.23.0+%28CommonJS%29%22+is%3Aclosed

changelog: https://github.com/CenterForOpenScience/osf.io/blob/release/0.23.0/CHANGELOG

Deployment actions:

- [x] Install webpack: `npm install -g webpack`
- [x] Install JS requirements: `npm install && bower install`
- [x] Update python requirements: `sudo pip install  -U -r requirements.txt`
- [x] Build assets: `inv assets`
- [x] Restart uwsgi: `sudo service uwsgi restart`

Post-release actions:

- [x] Check Piwik tracking
- [ ] Manual regression testing
-  [ ] Update developer docs : cache-busting mako filter (`webpack_asset`); commands for building assets locally; add "inv assets" to deployment commands

ping @JeffSpies @caileyfitz @nicipfeiffer @GaryKriebel @lbanner @samanehsan @jmcarp

**Comment by caileyfitz** [comment]
I'm a :-1: as of now with the bugs we have on the 0.23.0 board and the fact that @nicipfeiffer and I have not finished testing cache busting, profile changes, tooltip, and presentation/conference stuff.

**Comment by lbanner** [comment]
I hear you @caileyfitz -- and will support that -- TY

**Comment by sloria** [comment]
I'm also a no-go as of now. QA found some bugs that must get fixed before release. Some recent fixes will also need to go through another round of QA. Also, @brianjgeiger suggested--and I agree--that it would be good to go through the CommonJS Trello once more to make sure there aren't any missing stories.

**Comment by lbanner** [comment]
Following @GaryKriebel 's tradition!! http://youtu.be/zVf-rehP4b8

**Comment by GaryKriebel** [comment]
Hey, get your own movie clip!

**Comment by lbanner** [comment]
But I like / love that one!! :rocket:

**Comment by nicipfeiffer** [comment]
I am a go.  QA will complete a regression test after the release.

**Comment by sloria** [comment]
An update on the goings-on from yesterday to today:

All major bugs on `release/0.23.0` were fixed:

- Broken registrations (https://trello.com/c/TXyquW1V) fixed by https://github.com/CenterForOpenScience/osf.io/pull/1486
- Cache-busting fix: https://github.com/CenterForOpenScience/osf.io/pull/1497
- Profile input validation (https://trello.com/c/FGi3clTW) fixed by e59a4f87f8b9af0162e0ca770d1524cf69710904
- Invalid email confirmation links (https://trello.com/c/ZvD2ysrm) fixed by https://github.com/CenterForOpenScience/osf.io/commit/931c4ab5f9271cc36da2e68857c8526918284aff

Minor fixes were made as well:

- Broken tooltips (https://trello.com/c/7DbaUxsZ/37-various-tooltips-broken) fixed by https://github.com/CenterForOpenScience/osf.io/pull/1488
- IE "return" button behavior (https://trello.com/c/XKdqddl9) fixed by https://github.com/CenterForOpenScience/osf.io/pull/1480
- Conference service fixes: https://github.com/CenterForOpenScience/osf.io/pull/1487, https://github.com/CenterForOpenScience/osf.io/pull/1501
- Drag-and-drop reordering (https://trello.com/c/lIS9jeqc) fixed by e59a4f87f8b9af0162e0ca770d1524cf69710904

There is one known regression, a minor one: the tooltip for the gravatar on a user's profile page that says "Click here to change avatar" is not showing up. IMO, this should not hold up release.

There are also a few edge cases to test with the conference service, but given that the service will not be active until next month, these also do not have to hold the release.

**Comment by sloria** [comment]
I'm a go.

**Comment by sloria** [comment]
ping @JeffSpies @caileyfitz @GaryKriebel @samanehsan @jmcarp

**Comment by sloria** [comment]
On second thought, I'm in favor of releasing tomorrow morning, for the following reasons:

- We'll need to check that Piwik is still working correctly once this is deployed. Would be good to have @lyndsysimon on stand-by for that.
- A morning release will allow QA to do their full regression tests immediately after the release.
- This will give me some time to look into a better solution for https://trello.com/c/6suwhhIR than the temporary workaround I've done on staging.

I vote **no-go until the morning**.

**Comment by lbanner** [comment]
That is a good plan @sloria and I am with you and @nici on a go :+1: Thanks!

**Comment by caileyfitz** [comment]
I'm a go for morning release. I'll be there to do regression tests and report any problems immediately

**Comment by GaryKriebel** [comment]
I'm good with the morning.  Nice work all!

**Comment by samanehsan** [comment]
A morning release sounds good to me!

**Comment by JeffSpies** [comment]
If Lyndsy is around in the morning, we can go.

One note: I can't see the trello card you linked. Still valid?

**Comment by sloria** [comment]
@JeffSpies just added you to the board, so you should be able to see it now.

**Comment by sloria** [comment]
Looks like we're ready to release.

ping @JeffSpies @jmcarp @GaryKriebel

**Comment by caileyfitz** [comment]
:rocket:

**Comment by lbanner** [comment]
:+1:

**Comment by JeffSpies** [comment]
Holding until we hear about Courtney's workshop. See flowdock.

**Comment by GaryKriebel** [comment]
I'm a go for a window that does not interfere with Courtney's workshop.

**Comment by brianjgeiger** [comment]
There are still bugs on the Trello board. Those should be solved or deferred.

.:Brian

**Comment by lbanner** [comment]
The 'reset password' is being worked. I suggest deferring the other re: conference email -

**Comment by sloria** [comment]
@brianjgeiger The remaining bugs are also on production and will be hotfixed. They do not need to hold release

**Comment by sloria** [comment]
Release is now live. Lyndsy confirmed that Piwik is working as expected. Cailey is working on regression tests. I will update the dev docs.
