### ISSUE TITLE
Resend your account confirmation email will send you the original (and possibly expired) link

### ISSUE THREAD

**Issue by GaryKriebel** [CenterForOpenScience/osf.io#1492]
# Steps
1. Create a new account.
2. **DO NOT** click the link in the confirmation email you will receive.
3. Wait for more than 24 hours.
4. Now click the link in the confirmation email you received more than 24 hours ago.
5. As expected, you see the **Link Expired** page which directs the user to "log in to continue".
6. Log in with the credentials used in creating the account to continue.
7. Receive the message that states "This login email has been registered but not confirmed. Please check your email (and spam folder). *Click here* to resend your confirmation email."
8. Click *Click Here*
9. As directed by the next page, enter the email address used in creating the offending account and click *Submit* to "resend your confirmation link". 

# Expected
I receive a new email with a link that I can click to confirm my account.

# Actual
I received an email with a confirmation link.  However, the key words above were "resend your confirmation link".  That's exactly what happened, the same link from the very first email was sent.  Recently, links were made to expire after 24 hours.  One item not changed was this process.  We don't need the link "resent", we need the confirmation link "regenerated and sent".

**Comment by lbanner** [comment]
Reference this PR #1315 -- the link now expires, but appears there's no new functionality to create a new link!

**Comment by sloria** [comment]
Working on this now
