### ISSUE TITLE
Support for tex/latex syntax in Wiki pages?

### ISSUE THREAD

**Issue by mbudisic** [CenterForOpenScience/osf.io#1494]
Is it possible to add support for (a subset of) TeX/LaTeX to the Wiki pages of projects, e.g., like MediaWiki http://en.wikipedia.org/wiki/Help:Displaying_a_formula MediaWiki does? This would be of great help in math/physics projects (at the very least).

If this feature already exists, I couldn't find a note in documentation for it, and neither of the common syntaxes for TeX have shown up properly in preview. E.g. either of 
```
$x^2$
$$x^2$$
<math>x^2</math>
\(x^2\)
```
should show up as x<sup>2</sup>.

**Comment by sloria** [comment]
@mbudisic We do not currently support LateX/MathJax in the Wiki. We are currently working on significant frontend changes to the wiki, so we will evaluate possible solutions to this. Thanks for the suggestion!

**Comment by mbudisic** [comment]
I'm glad to hear that this is an area of active development. As an intermediate solution, any support for equations, e.g., AsciiMathML, would serve the community.

Thanks for listening!

**Comment by sloria** [comment]
Thanks for your input. 

@rliebz and @icereval : Please take this into consideration as you work on the wiki changes.

**Comment by JeffSpies** [comment]
@WenTingZhu, in further working on her javascript skills, is going to try to integrate mathjax and the rendered wiki to support a minimal version of latex/mathml.
