### ISSUE TITLE
[profile] Hitting Return/Enter button cancels rather than submits

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1495]
## Steps

- On the user settings page, go to the "Employment" tab
- Enter a change in the form
- Hit "return" button.

## Expected

The form is submitted.

## Actual

A modal pops up to confirm discarding changes, i.e. the cancel button is hit instead.

The same behavior happens on the Education tab.

**Comment by brianjgeiger** [comment]
On the social tab it will import your Github ID. I believe it's checking for the first button in the form and pressing that.

**Comment by lbanner** [comment]
I have been unable to reproduce (?) Just FYI

**Comment by sloria** [comment]
I saw the bug in Google Chrome  39.0.2171.95 on Mac OSX 10.9

**Comment by brianjgeiger** [comment]
You have to have your input in a field. Confirmed on Safari
