### ISSUE TITLE
[Staging & Production] Various 'static/public/img' errors

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1498]
## Steps
1. Go to a project you have admin privileges on
2. Go to the 'Sharing' tab and add several contributors to the project
3. Have your error console open and click on the 'Permissions' pop-over (it might be the word Administrative, Read+Write, or Read)

![screenshot 2015-01-15 10 28 52](https://cloud.githubusercontent.com/assets/9381062/5760602/e563d88a-9ca3-11e4-9185-a06c775018ae.png)

## Expected
That clicking on the 'Permissions' for a contributor to make a change would not result in an error

## Actual
When clicking on the 'Permissions" for a contributor and error occurs in the console: GET https://staging.osf.io/static/public/img/loading.gif 404 (Not Found). The function still works correctly.

**Comment by brianjgeiger** [comment]
Images are not currently being bundled, so they shouldn't be in static/public (or the img files should be in static/public/img, I'm not sure which). Though I would imagine the error is a little different on production?

**Comment by nicipfeiffer** [comment]
Another instance is on a wiki page that is not the home wiki.  When you click on the name to edit, the same console error occurs. 
![screenshot 2015-01-15 14 24 57](https://cloud.githubusercontent.com/assets/9381062/5764836/144b1964-9cc3-11e4-816a-0efb57122593.png)

**Comment by nanchen47** [comment]
@nicipfeiffer can't repo this problem. Can you verify this problem still exist? Thanks.

**Comment by nicipfeiffer** [comment]
@nanchen47 I no longer get these errors.

**Comment by lbanner** [comment]
Cool! -- Let's close it for now :smile_cat:
