### ISSUE TITLE
[staging & production] Quotation marks in tags yield no search results when clicked

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1502]
# Steps
1. Search for *hyperland* in the site-wide search bar on staging or production
2. Once results pop up, click the *"fourth dimension"* suggested search tag

# Expected
I expect that this would act like adding any other suggested search tag, ie: searching for projects/users/registrations with *hyperland* AND *"fourth dimension"*

# Actual
There are no search results listed, due to another set of quotation marks being added 
![screen shot 2015-01-15 at 3 10 15 pm](https://cloud.githubusercontent.com/assets/5975444/5765571/a3902f6a-9cc8-11e4-8e0f-9975c7a75dea.png)

Tagging @fabianvf because he has a fix

**Comment by brianjgeiger** [comment]
Adding quotes to new tags will currently replace them with &quot; though it's displayed inconsistently in different parts of the search display. Some of this may change with the Mako HTML-Safe modifications.

![screen shot 2015-01-15 at 3 17 43 pm](https://cloud.githubusercontent.com/assets/6599111/5765706/b6921a78-9cc9-11e4-92d7-29ca98fbf95f.png)

**Comment by nanchen47** [comment]
@fabianvf any update on this?
