### ISSUE TITLE
[github] [dataverse] [production] Dropdown for current branch on Files page resets to default on folder collapse

### ISSUE THREAD

**Issue by rliebz** [CenterForOpenScience/osf.io#1508]
This occurs similarly on both GitHub and Dataverse with branches and versions, respectively. While the backends are largely different, the issue is the same. I'm on OSX Yosemite using Google Chrome. 

Steps to reproduce for GitHub:
---
1. Go to a project with the GitHub enabled on a repo with multiple branches and visit the Files tab.
2. Click the dropdown and choose any branch other than the default. The files for that branch will be loaded.
3. Click the name of the repo or the [-] icon to collapse it. 
    - At this point, the dropdown display will reset to the default branch.
4. Re-open the folder. The dropdown displays the name for the default branch, while the contents of the repo are from the non-default branch that was selected in step 2. The action buttons for the repo correspond to the default branch as well. 

Expected Behavior
---
After collapsing the repo, the branch will not change from what is currently selected.

Actual Behavior
---
After collapsing the repo, the branch will always appear reset to the default branch. Contents of the repo are unaffected.

**Comment by rliebz** [comment]
It looks as though the repo row will always consider itself to be the default branch.

Any attempt to upload a file to a branch other than the default will instead upload it to the default. This makes it effectively impossible to upload a file to anything other than the default branch (which, in dataverse's case, makes uploads impossible), and the UI does not make it apparent to the user that this is the case.

**Comment by lbanner** [comment]
Interesting ..... looks like, for now, we need to write-up / enter in a disclaimer / explanation for the user?

**Comment by rliebz** [comment]
After discussing with @jmcarp, it appears this issue, as well as #1481, will be resolved with the release of Water Butler.

**Comment by rliebz** [comment]
This is no longer an issue.
