### ISSUE TITLE
Tags for individual files

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#1511]
Feature request for next epic:

If individual files can be tagged, then we can easily create views with our search and discover capabilities to produce an OSF manuscript sharing service, OSF data sharing service, etc.  Users just tag a file as "manuscript" and select some discipline keywords.  

Like the OSF Registry view request, these simple steps will broaden users mental horizons of what the OSF is and does, and provide more access points to projects.

**Comment by samanehsan** [comment]
Fixed in https://github.com/CenterForOpenScience/osf.io/pull/2637
