### ISSUE TITLE
[Feature Request][Onboarder] Automatic focus on search fields after drop

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1516]
Reported by @kmjungersen on the Onboarder Trello board

## Steps
1. Go to the dashboard and add a file

## Expected
This is a feature request that after adding a file on the dashboard, then the focus would move to the next step: 'Select a Project'.  And following that, it would allow the user to tab to the 'component' field to be completed.

## Actual
The typeahead fields do not receive focus after the previous step is complete.

![screenshot 2015-01-19 10 49 43](https://cloud.githubusercontent.com/assets/9381062/5803068/ed425a36-9fc8-11e4-9268-c1807fbefad0.png)

**Comment by hmoco** [comment]
I can give this a try

**Comment by lbanner** [comment]
Done!

**Comment by caneruguz** [comment]
@hmoco what's the status on this? The assignment was two months ago. 

@lbanner

**Comment by lbanner** [comment]
@hmoco ?

**Comment by hmoco** [comment]
@lbanner I never got to finish this as this was when I was between projects. I am now working on a bigger project, but can come back to this as soon as that is done, or have it assigned to someone else.

**Comment by caneruguz** [comment]
@hmoco Thanks for the update. For future remember that you need to keep these assignments up to date otherwise you are blocking others from tackling things.

**Comment by lbanner** [comment]
Ok @hmoco -- I am pulling you off for now. Thanks.

**Comment by hmoco** [comment]
@caneruguz @lbanner, yep, I should've gotten myself unassigned a while ago, sorry about that, will take a look at my other assignments to make sure everything is up to date
