### ISSUE TITLE
[Feature Request][Onboarder] No user warning if navigate away after adding files for upload

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1518]
Reported by @kmjungersen on the Onboarder Trello board

## Steps
1. Go to the dashboard and add a file for upload to a project
2. Now navigate to another page (click on settings or profile info, for example)

## Expected
The user would receive a warning about leaving the page.  An alert that they have files selected for upload that have not been submitted.

## Actual
Nothing warns the user about leaving the page.  When returning after navigating away all info previously entered is gone.

**Comment by kmjungersen** [comment]
+1, I could definitely see a user forgetting to submit and then losing the changes

**Comment by PatrickEGorman** [comment]
Would there be a way to do this without modifying the webpack javascript files?

**Comment by geeksnglitter** [comment]
@GaryKriebel Can I work on this?

**Comment by lbanner** [comment]
You are good to go -- Thanks!

**Comment by samanehsan** [comment]
Closed by #2945.
