### ISSUE TITLE
[feature request] [watchlist] Lazily load watch feed when tab is clicked

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1519]
Reported by @sloria on the Onboarder Trello board

# Current behavior
Initial logs are rendered on page load, resulting in logs being immediately available when a user clicks the Watchlist tab.

# Suggested behavior
Lazily load watch feed when tab is clicked to avoid unnecessary requests when going to the dashboard. @sloria mentioned that he is not sure whether this would be better in terms of UX, so maybe there can be some discussion here? @brianjgeiger @lyndsysimon

**Comment by brianjgeiger** [comment]
Not loading until it's rendered is fine. If we wanted to increase responsiveness, you could save the load until the pointer touches the tab; that prevents the loading from slowing down the initial load, and it reduces the lag between clicking on the tab and seeing the data.
