### ISSUE TITLE
Implement Event Tracking on Slide-in Footer Buttons

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#1521]
Requesting implementation of event tracking on the buttons on our slide-in footer. The slide-in footer appears when someone is viewing a project but is not logged into the OSF:

![screen shot 2015-01-19 at 11 57 09 am](https://cloud.githubusercontent.com/assets/7749914/5804247/5fb7552c-9fd2-11e4-9d68-2a272bfe0e05.png)

Event tracking (more here: https://developers.google.com/analytics/devguides/collection/analyticsjs/events) can tell us, via Google Analytics, when users click "Create an Account," "Learn more," or "dismiss this message" (or the x in the top right corner). This will help us evaluate effectiveness of the footer. We cannot understand user flow this way currently because there is at least one other way to get to "create an account" or "learn more" on each page (rather than from the footer buttons). This is in support of community priorities for this spring -- converting observers of the OSF into users of the OSF.

**Comment by lbanner** [comment]
@lyndsysimon Any chance you can / should knock this one out? -- or is it Intern worthy? Thanks!

**Comment by saradbowman** [comment]
any updates/further thoughts on this?

**Comment by lbanner** [comment]
@saradbowman I'll find someone to put on this one and get it done

**Comment by lbanner** [comment]
@HarryRybacki Can you take a look at this? TY

**Comment by saradbowman** [comment]
Thanks!

**Comment by HarryRybacki** [comment]
Yep!
