### ISSUE TITLE
[UI] Getting Started: Playing video leads to console error

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1522]
Reported by @huangginny  on the CommonJS Trello board

## Steps
Open console. Navigate to "getting started" and play a video.

## Expected
Console should show nothing

## Actual
![screen shot 2015-01-19 at 12 34 33 pm](https://cloud.githubusercontent.com/assets/9381062/5805707/515a9298-9fdf-11e4-9357-db6bbd7baf28.png)

**Comment by nanchen47** [comment]
@sloria any thoughts about this?

**Comment by samanehsan** [comment]
It looks like it's a google chrome issue, not an OSF issue. 

From http://stackoverflow.com/questions/25814914/chrome-youtube-cast-sender-js-console-error:

>... it appears that Chrome attempts to get cast_sender.js on pages that have YouTube content. I'm guessing when Chrome sees media that it can stream it attempts to access the Chromecast extension. When the extension isn't present, the error is thrown.

**Comment by lbanner** [comment]
OK @samanehsan ... good find ... I'm going to Close. But we'll have for reference if needed. Thanks.

**Comment by samanehsan** [comment]
I should add that the 404 error when trying to get the youtube video is a separate issue, but it doesn't prevent the videos from playing. Not sure if this one is us or the embedded youtube player.
