### ISSUE TITLE
[staging & production] Consistency in add-on deletion modal for user settings page

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1524]
# Steps
1. Enable multiple add-ons for two or more projects. 
2. Go to one of the projects where add-ons are enabled.
3. In the Settings tab, go to the Select Add-ons section and deselect two or more add-ons and press Submit.
4. Notice what happens after the Submit button is clicked.
5. Now, go to the user settings page and navigate to Configure Add-ons. 
6. Deselect two or more add-ons and press Submit. 
7. Notice what happens after the Submit button is clicked.

# Expected
I expect that the behavior would be the same when deselecting add-ons from project settings vs. the user settings page, ie: in terms of modals, success messages, etc.

# Actual
Deselecting add-ons from these two places does not yield consistent behavior. When deselecting from the project settings page, pressing Submit immediately removes the add-ons and then a success message appears. When deselecting from the user settings page, pressing Submit prompts a confirmation modal: 
![screen shot 2015-01-19 at 2 09 15 pm](https://cloud.githubusercontent.com/assets/5975444/5806210/1dccc512-9fe5-11e4-890a-c074bb935855.png)
listing the add-ons to remove. 

I think the behavior here should be consistent and that a confirmation modal should be added when deselecting add-ons via the project settings page, just as a precaution against accidental add-on removal. 

Additionally, I think that users could benefit from more information in the confirmation modal on the user settings page. The current modal does not adequately point to the potentially wide-spread reach of removing add-ons. For example, imagine that a professor in a lab authorizes his own Dataverse account for a project that his graduate students are working on. The professor doesn't work on the project in the OSF and is in fact not even an admin on the project -- the grad students are doing all of the uploading/downloading/editing on the site. Then, maybe the prof wants to clean up and deselects Dataverse, completely forgetting that it is *his* account which is linked for the project. There is no indication that deselecting the add-ons will remove them from **every** project to which his accounts are linked. Even just a sentence saying something like "Removing these add-ons will remove them from every project to which your accounts are linked, regardless of your permissions on the project -- are you sure you want to remove these add-ons?" could prevent users from accidentally removing add-ons when they didn't actually mean to.

**Comment by nanchen47** [comment]
same issue as https://github.com/CenterForOpenScience/osf.io/issues/1621
