### ISSUE TITLE
[Staging & Production] [UI] Info Modal does not scroll for lengthy project descriptions

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1525]
## Steps
1. Go to the dashboard page and click the 'i' next to a project that has a lengthy description
2. The info modal appears with the Project Name, Contributors and the Description

## Expected
When opening the info modal on the dashboard for a project with a lengthy description, the modal would allow the user to scroll to the end to read all the info.

## Actual
The modal cuts off the description at the end of the page and scrolling only scrolls the main dashboard page and not the modal.
![screenshot 2015-01-19 14 14 58](https://cloud.githubusercontent.com/assets/9381062/5806383/dbe8b082-9fe6-11e4-932d-01d7942b888e.png)

**Comment by brianjgeiger** [comment]
This will not be an issue in 0.24.0

**Comment by lbanner** [comment]
Clarification again @brianjgeiger : ) Functionality to be released in 0.24.0 will correct this? Thanks!

**Comment by brianjgeiger** [comment]
Yes. This will be more clear after the lunch presentation today.

**Comment by caneruguz** [comment]
@sloria @brianjgeiger Also needs an update. Maybe we should go over these milestone related issues.

**Comment by brianjgeiger** [comment]
No longer an issue.
