### ISSUE TITLE
[Staging & production] [UI] Firefox: Rename folder text obstruction

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1526]
## Steps
1. Using the firefox browser: Go to the project dashboard and click the 'i' beside a folder
2. Click on the pencil to 'edit' the name of the folder

## Expected
That the current name would be readable, and not obstructed and any typing done to edit would not be obstructed.
![screenshot 2015-01-19 15 03 49](https://cloud.githubusercontent.com/assets/9381062/5806980/6ba1a990-9fec-11e4-8482-6e4359fb3d6f.png)

(screenshot from Chrome browser)

## Actual
The text is not fully in view:
![screenshot 2015-01-19 15 02 28](https://cloud.githubusercontent.com/assets/9381062/5806966/36dbe0ea-9fec-11e4-8390-fb1ddcf90305.png)

**Comment by brianjgeiger** [comment]
Will not be an issue in 0.24.0

**Comment by JeffSpies** [comment]
What are we testing that continues to be followed with the message, "Will
not be an issue in 0.24.0"?

**Comment by brianjgeiger** [comment]
I think they're moving over issues from the Search trello board; cards from old sprints were not migrated from trello until now, but we are making changes regardless.

**Comment by lbanner** [comment]
Meaning @brianjgeiger that functionality or PR planned to release in 0.24.0 will correct this? -- If so, suggest we close it, yes? -- Thanks!

**Comment by brianjgeiger** [comment]
Yes. But it shouldn't be closed until it is actually corrected, though it should be assigned a 0.24.0 milestone, which I have just done.

**Comment by caneruguz** [comment]
@sloria @brianjgeiger  This needs an update.

**Comment by brianjgeiger** [comment]
Fixed.
