### ISSUE TITLE
Filters on search rearrange order 

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1527]
<h4>Steps/Results</h4>
1. Search for "henderson" (as an example)
2. Refer to the left hand side of the search results page where you can filter results by projects, components, registrations or users—in that order.
3. Conduct another search, this time for "plant" (another example)
4. Again, look at the filters; this time they are listed as registrations, components, and projects. 

The search filters appear in numerical order and exclude any categories that have 0 results.

<h4>Expected behavior</h4>
1. The filters should always appear in the same order. Because "Project" appears second most often, I anticipate finding it there all the time. 
If a user is employing these filters (as opposed to tags) they are probably looking for something in particular. A numerical sort is appropriate when suggesting possibilities that someone may not know about, but not when the user is hunting for a particular item. In the latter case, a consistent order for filters is more helpful. 
2. All categories to filter by, even if there are no results within that category, should appear. If a category is empty, it should display its count as "0"

**Comment by nanchen47** [comment]
@fabianvf  @brianjgeiger any thoughts on this?

**Comment by brianjgeiger** [comment]
Ideally, the Total should be at the top, SHARE at the bottom, and everything else in alphabetical order. Total should be visually distinct to indicate that it's a total. SHARE should be distinct to indicate that it takes you to a completely different search page. Total *could* go below the results that it's totaling, then SHARE below that. 

I don't necessarily agree that the filters that aren't valid should be shown. Right now, it's six one, half-dozen the other, but if we start increasing the filter categories (by, for example, including the project categories or similar), I think it's better not to give an option that results in empty search results. That's not a strong opinion, though, so I could be swayed with a good argument.

**Comment by fabianvf** [comment]
I agree with Brian. I think total - alphabetical - SHARE is the most intuitive. I also agree that showing 0 result categories is not interesting.

**Comment by jlcohoon** [comment]
I think it does say something though to have categories with 0 results. If
I'm expecting to find a project or component with that search result in it,
and there aren't any, seeing 0 results is meaningful. Since there are a
small, finite number of predefined categories, 0 means something. In cases
like tags, where there can be thousands of them, you wouldn't say that
there were no results for each of the tags that doesn't pull something up.
But, when you have five items that are examined in every single search and
one doesn't have anything, it's relevant information.

**Comment by lbanner** [comment]
I agree with @jlcohoon's point on this one: +1
