### ISSUE TITLE
[Feature request] Obvious visual for number of registrations for a project

### ISSUE THREAD

**Issue by csoderberg** [CenterForOpenScience/osf.io#1532]
Currently, to determine whether a project has any registration you have to go and actually click on the 'Registration' button. It would be a lot nicer if somewhere on the project dashboard there was a button or widget or something that showed the number of registration of that project (which would include the registrations at that level and in any nested levels), so you would know whether you might want to go into the 'registrations' tab or not.

**Comment by jlcohoon** [comment]
This one got discussed in the community repo (https://github.com/CenterForOpenScience/community/issues/218) and it was requested that we add a badge next to the link to registrations on a project that lists the number of registrations. If there are no registrations there should be no badge. No extra language needs to be added to the registration page itself. For example:
![screen shot 2015-07-14 at 2 05 47 pm](https://cloud.githubusercontent.com/assets/4965832/8680791/b34c2a70-2a31-11e5-9df7-275663ea0867.png)

Bootstrap talks about badges and active state badges <a href="http://getbootstrap.com/components/#adapts-to-active-nav-states">here</a>.

**Comment by brianjgeiger** [comment]
While they're there, would you want to add a badge for forks as well?

**Comment by jlcohoon** [comment]
I like the idea. @bnosek, @JeffSpies, thoughts? It would be a more obvious sign than the duplicate button's number, but it would also be redundant.

**Comment by bnosek** [comment]
Yes, okay with me.  Not sure if that badge conforms well to the style guide or not, but that should be checked (obviously).

**Comment by caneruguz** [comment]
The style guide doesn't have any section on badges, so default bootstrap badges would fit the style guide. 

My only concern is that badges on that navigation could proliferate quickly. Registration and Fork count makes sense but what we don't want is a badge for each of these page navigations (i.e. number of people accessing in Sharing, number of pages in wiki, number of comments etc.

**Comment by JeffSpies** [comment]
A badge is an easy answer for now, but I'm not sure this is the type of
information to go into a menu badge. As we think about dashboard changes, a
summary widget may be better.

**Comment by nanchen47** [comment]
Will be considered when refactoring the registration page interface.
