### ISSUE TITLE
Project Organizer isn't loading

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1535]
<h4>Steps</h4>
Visit your dashboard
<h4>Expected</h4>
All projects load and are displayed in the previously established folders.
<h4>Actual</h4>
Several times today, my project organizer has not loaded my projects or any folders, leaving it entirely blank. Refreshing the page does not always resolve it. 
The only relevant error in my console is that hgrid cannot find a stylesheet.

**Comment by lbanner** [comment]
Can you screen shot this for us @jlcohoon ? Maybe an expected vs actual?

**Comment by jlcohoon** [comment]
This same error has occurred a few times today. It's possible its an internet connection issue, but if that's the case, we should have a timeout error, should we not? 

Actual:
![screen shot 2015-01-26 at 3 13 13 pm](https://cloud.githubusercontent.com/assets/4965832/5907573/fb071e9a-a56d-11e4-964b-7e6e5af1c761.png)

Expected:
![screen shot 2015-01-26 at 3 13 20 pm](https://cloud.githubusercontent.com/assets/4965832/5907574/fb07c62e-a56d-11e4-8322-f23194b0d5b2.png)

**Comment by JeffSpies** [comment]
Can you open up your development console and see if you receive any error
messages when this happens? It might also be your machine--too much memory
being used--so if you see it again, come find me.

J.

**Comment by brianjgeiger** [comment]
Ended up being a plugin causing the trouble.
