### ISSUE TITLE
Dropbox settings cannot be adjusted

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1557]
<h4>Steps</h4>
1. Visit your user settings, scroll down to Dropbox
2. Clicking "Delete Access Token"
OR
1. At the top of your user settings page in "Select Addons", de-select "Dropbox" and submit your change.

<h4>Expected</h4>
1. Dropbox token should be deleted, allowing the user to click on "Create Access Token"
2. No projects should be listed as "authorized projects"
3. No projects should have Dropbox files listed in them.
OR
1. Dropbox should be removed as an add-on, meaning no settings are listed below in the "Configure Add-ons" section.
2. No projects should have Dropbox files listed in them.

<h4>Actual</h4>
1. When visiting the Dropbox settings, there is text alerting me that my settings cannot be retrieved:
![screen shot 2015-01-23 at 11 03 29 am](https://cloud.githubusercontent.com/assets/4965832/5877760/d95f4ac2-a2ef-11e4-9c2e-17ebb814e3fc.png)
2. Clicking on "Delete Access Token" produces an error that says that it could not be deleted:
![screen shot 2015-01-23 at 11 06 36 am](https://cloud.githubusercontent.com/assets/4965832/5877773/f2f8d872-a2ef-11e4-9412-49bb4e0eee76.png)
3. Dropbox files cannot be accessed by the OSF. Below is an example of a folder that I have confirmed does have the displayed path on my computer, and does contain files:
![screen shot 2015-01-23 at 11 11 49 am](https://cloud.githubusercontent.com/assets/4965832/5877871/b4abeee6-a2f0-11e4-8b28-05b983466fd2.png)

OR

1. A pop up notifies me that the request failed and that Dropbox could not be removed at this time:
![screen shot 2015-01-23 at 11 07 07 am](https://cloud.githubusercontent.com/assets/4965832/5877815/5193b4e2-a2f0-11e4-883c-5765882a0096.png)
2. Dropbox files cannot be accessed by the OSF.

I have been able to successfully log out and into Dropbox from the website, and the app appears to be working correctly on my computer.

**Comment by lbanner** [comment]
@jlcohoon Is this issue live / on Production?

**Comment by jlcohoon** [comment]
yes

**Comment by lbanner** [comment]
TY! Might not be a "bug" per se, but rather a need to clarify expected action after deactivating a DropBox Add-On -- I have label'd as "Bug: Production" with "Discuss" -- and we'll move this forward.

**Comment by jlcohoon** [comment]
As a followup to this, not all of my Dropbox-connected projects are displaying in my user settings. The ones shown below are only a few of the ones that I have connected. I assume this is because the OSF isn't able to properly connect with DropBox at the moment. 
![screen shot 2015-01-26 at 10 03 35 am](https://cloud.githubusercontent.com/assets/4965832/5901717/a54be15a-a542-11e4-869d-f8b41323dcdb.png)

**Comment by brianjgeiger** [comment]
Because of the interaction between this and #1583, we are trying removing all of the projects from the project setting page, then when they are all gone deleting the access token from the user account, then reapplying everything. If this works, this is obviously not how it should. It would seem that there's a bug in there somewhere.

**Comment by brianjgeiger** [comment]
There's an error on sentry. https://sentry.osf.io/osf/production/group/1705/

website/addons/dropbox/utils.py Line 55:
            'folder': self.node.get_addon('dropbox').folder
Attribute error: 'NoneType' object has no attribute 'folder'

**Comment by brianjgeiger** [comment]
In the meantime, this leaves @jlcohoon unable to use Dropbox on her production projects.

**Comment by sloria** [comment]
Looking into this

**Comment by jlcohoon** [comment]
I just deauthorized the OSF via Dropbox. My OSF user settings are still saying that they can't connect and are still not allowing me to delete the token.

**Comment by sloria** [comment]
OK, found the root cause of this: When creating a "node_deauthorized" log for all a user's Dropbox-authorized nodes, we weren't accounting for `DropboxNodeSettings` records that had the `deleted` field set `True`. This resulted in the `AttributeError` seen by Sentry.

Once the CI build passes, will merge the hotfix.
