### ISSUE TITLE
Users with no public projects or registrations show empty lists

### ISSUE THREAD

**Issue by JeffSpies** [CenterForOpenScience/osf.io#1576]
Actual
======

![screen shot 2015-01-24 at 3 55 14 pm](https://cloud.githubusercontent.com/assets/512000/5889022/67c046da-a3e1-11e4-8b2f-8043cec31e88.png)

Expected
=======
There is some message underneath the bottom two headings indicating that the user has none.

**Comment by brianjgeiger** [comment]
I don't think I saw the "expected" here the first time, so that eliminates my biggest problem with this one. The only thing really missing is if this also happens on production. If not, it should probably be in Trello, if so, it would be good to explicitly mention, since the url in the screenshot is for staging.

**Comment by lbanner** [comment]
Is the same on Production -- Tagged this with "Enhancement" + "UI" -- It would be more clear to state "0" or "None"

**Comment by Ghalko** [comment]
![screen shot 2015-04-17 at 10 06 50 am](https://cloud.githubusercontent.com/assets/5169088/7203568/7ffd4f2e-e4e9-11e4-9179-b183766cc288.png)

Mako solution.

**Comment by sloria** [comment]
@Ghalko Showing `None` looks awkward--sort of looks like a programmer error. How about just hiding the "Public Components" and "Public Projects" headers? ping @JeffSpies

**Comment by brianjgeiger** [comment]
Alternately, we could encourage users to make a public component or project, and maybe have a link to why they would want to do so.

**Comment by sloria** [comment]
@brianjgeiger If you're viewing your own profile, then we could that. But what if you're viewing someone else's profile?

**Comment by brianjgeiger** [comment]
Good point. Yeah, hiding is best, unless we have some really top-knotch "Here's why public is awesome" copy. But probably hiding.

**Comment by GaryKriebel** [comment]
"This user has no Public Components"?

**Comment by Ghalko** [comment]
"This user has no Public Components. Make your components public!" (link to instructions on how to make the public components.)

**Comment by brianjgeiger** [comment]
No, if it's on someone else's profile, it would seriously have to make them reconsider the whole notion of closed science to make it worth trying to redirect someone from viewing another person's profile to changing their own project settings. Without something that amazing, hiding the column makes the most sense, I think.

**Comment by Ghalko** [comment]
Truly amazing? Who can we source to write truly amazing copy?

**Comment by brianjgeiger** [comment]
No idea, so Steve's suggestion is probably the way to go.

**Comment by JeffSpies** [comment]
I think I prefer "This user has no public projects". If it's the user
looking at their own profile, "You have no public projects. Find out how to
make your projects public."

J.

**Comment by sloria** [comment]
Sounds good. @Ghalko Can you send a new PR implementing @JeffSpies' suggestion?

**Comment by Ghalko** [comment]
![screen shot 2015-04-21 at 8 53 57 am](https://cloud.githubusercontent.com/assets/5169088/7252915/d41a0dde-e806-11e4-83c2-ce2d3e60d5cb.png)

**Comment by lbanner** [comment]
Looks good! @JeffSpies can you confirm? Thanks.

**Comment by JeffSpies** [comment]
Looks good.
