### ISSUE TITLE
Upload file(s) in Quick Tasks on Project Dashboard should allow me to create a new project as well as selecting an existing project

### ISSUE THREAD

**Issue by JeffSpies** [CenterForOpenScience/osf.io#1577]
# Steps

1. Go to https://osf.io/dashboard
2. Drag a file into the "Upload a file" section on the right

# Actual

Choose existing project

# Expected/desired

Choose existing project or new project

**Comment by brianjgeiger** [comment]
This contains all of the requisite information, but in a form that takes a little cognitive overhead to parse. Breaking it up in the description wouldn't hurt. 

Also, technically this is part of the onboarding widget, not the project organizer. Which ordinarily would be a tiny pedantic thing, but there have been a lot of reports confusing the project organizer with the project overview page which is sometimes called the project dashboard for historical reasons, and I note there was similar confusion in your report.

If instead the steps were: 
1. Go to https://osf.io/dashboard
2. Drag a file into the "Upload a file" section on the right

With actual and expected results, then it would be clear which page you meant. It would also give a chance to expand on the proposed solution, if you had any thoughts about the implementation or UI (which you may not).

**Comment by lbanner** [comment]
OK @brianjgeiger help:
The "Project Overview Page" is my "Project Dashboard" -- On my "Project Dashboard" is the "Onboarding Widget" -- So the "Project Organizer" references .... ?

**Comment by brianjgeiger** [comment]
Project Organizer is the grid widget on the left side of the page of osf.io/dashboard that lets you organize your projects into folders and such.

The dashboard is the whole page osf.io/dashboard

The project overview page is the landing page when you go to a project or component with the two columns of widgets.

Project dashboard is a phrase that should never be used.

**Comment by lbanner** [comment]
Appreciate the clarity! However, "My Dashboard" is how I, as a user, see my overview of projects, even if we, as developers, see the construction of that page differently -- so we should take care with phrasing around a user's "Dashboard" and the term Project Dashboard. I will aim to pay attention to that.

**Comment by brianjgeiger** [comment]
Which is why I suggested the changes to this issue, even though they are otherwise pedantic. We've had a lot of confusion around these issues. @caneruguz and I discussed possibly re-working the interior look of osf.io/dashboard to make it more clear what was what, but we have some new UI options in the next sprint or two that will make that better.

**Comment by nanchen47** [comment]
Same issue as https://github.com/CenterForOpenScience/osf.io/issues/2146. Close this one and continue discussion and follow up there.
