### ISSUE TITLE
Dropbox files not loading

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1583]
<h4>Steps</h4>
1. On production, visit a project that has a Dropbox folder connected. For example: https://osf.io/siaqe/
2. Look at the file tree and find the Dropbox folder you have linked.

<h4>Expected</h4>
1. The files that are saved in that Dropbox folder should be listed on the OSF

<h4>Actual</h4>
1. No Dropbox files are shown:
![screen shot 2015-01-26 at 9 59 27 am](https://cloud.githubusercontent.com/assets/4965832/5901645/0c165a60-a542-11e4-9127-db89751d26c3.png)

2. The console produces the following error:
![screen shot 2015-01-26 at 9 55 02 am](https://cloud.githubusercontent.com/assets/4965832/5901637/ff8e868c-a541-11e4-87ec-d1fe8ab7a1f0.png)

3. Because of issue #1557 the Dropbox settings cannot be adjusted to try and "reset" the folder.

I have confirmed that the folder I am pointing to does exist and does contain files. This issue is occurring on all of my connected Dropbox folders.

**Comment by lbanner** [comment]
So, again -- this is Production, right @jlcohoon ? Not QA / testing work on Staging?

**Comment by jlcohoon** [comment]
correct

**Comment by sloria** [comment]
@jlcohoon Can you confirm that this is now fixed?

**Comment by jlcohoon** [comment]
Confirmed!
