### ISSUE TITLE
[production] Version history table occluded by image in word file

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1606]
# Steps
1. Upload multiple versions of a word file with images to production
2. Click on the file to render

# Expected
I expected that the version history table would be visible, despite the file images.

# Actual
The version history table is occluded
![screen shot 2015-01-27 at 11 52 06 am](https://cloud.githubusercontent.com/assets/5975444/5923131/08e101be-a61f-11e4-9922-ee24137c8b9d.png)

**Comment by samanehsan** [comment]
@GaryKriebel, @lbanner it looks like this issue is no longer happening. Tested the file from @caileyfitz on staging: https://staging.osf.io/zs6k8/

**Comment by lbanner** [comment]
Cool -- Thank you -- closing!

**Comment by caileyfitz** [comment]
@lbanner @samanehsan This is now an issue again on production. Can we re-open this? 
![screen shot 2015-03-19 at 10 50 05 am](https://cloud.githubusercontent.com/assets/5975444/6733007/bc316b9a-ce25-11e4-913b-d54b6d6768f4.png)

**Comment by nanchen47** [comment]
This is related to issue https://github.com/CenterForOpenScience/osf.io/issues/2254. and @mfraezz has a fix for that. https://github.com/CenterForOpenScience/modular-file-renderer/pull/168. Close this one and continue the topic on https://github.com/CenterForOpenScience/osf.io/issues/2254.

**Comment by mfraezz** [comment]
This is similar, but not directly related to https://github.com/CenterForOpenScience/osf.io/issues/2254. It's likely caused when PyDocX parses an image-containing document and [assigns](https://github.com/CenterForOpenScience/pydocx/blob/be828b94da1a05a4b021e7673697745dce7e89a6/pydocx/parsers/Docx2Html.py#L193) it fixed dimensions. The other possibility is just if the image is too large for the page without any style assigned. Either way, overriding DocX2HTML's `image` function in [here](https://github.com/CenterForOpenScience/modular-file-renderer/blob/dev/mfr/ext/docx/render.py#L11) to limit the width would be a simple way to fix it.

**Comment by nanchen47** [comment]
@mfraezz thanks for clarify. Reopen this one

**Comment by GaryKriebel** [comment]
This issue was also documented in https://github.com/CenterForOpenScience/osf.io/issues/2511

**Comment by caneruguz** [comment]
@GaryKriebel Any updates on this issue? MFR has seen some changes recently so we might need to test again!

**Comment by caneruguz** [comment]
With the new rendering this seems to unlikely repeat as an issue, is that correct? 

![screen shot 2015-07-27 at 3 20 16 pm](https://cloud.githubusercontent.com/assets/1314003/8915451/114bc4e6-3473-11e5-9c5b-a7cd2fa0a7c5.png)

**Comment by GaryKriebel** [comment]
@caileyfitz .... do you still have the project in question to do a quick test?

**Comment by GaryKriebel** [comment]
@caneruguz .... wasn't even thinking of the pdf rendering.... I believe you would be correct.... Let's verify with @caileyfitz

**Comment by caileyfitz** [comment]
No longer seeing this issue @GaryKriebel @caneruguz
