### ISSUE TITLE
"Modified" column time inaccuracy in dashboard. Chrome.

### ISSUE THREAD

**Issue by harrismendell** [CenterForOpenScience/osf.io#1611]
## Steps
1.) Modify a project.
2.) Immediately go to dashboard and check "modified" column for corresponding project.

## Expected
Time since last modification should be accurate, most likely in the seconds if following step 2.)

## Actual
Time always says at minimum "2 minutes" since last modification.

**Comment by lbanner** [comment]
Might need to discuss expectations here on accuracy to the second or minute -- Thanks for submitting @harrismendell

**Comment by brianjgeiger** [comment]
It's been a while since I made that, but I thought it would say "just now" or similar if it was below a minute or two. We may also just replace that with the date/time of the modification rather than the relative time to make it easier to sort by updated column (when we add that in).

**Comment by lbanner** [comment]
"date/time of the modification" -- I support that idea, clear and much simpler.

**Comment by JeffSpies** [comment]
I'm not a fan of relative times in general (except maybe on user
dashboards), but we should be able to have a "view" time and a "sort" time
with treebeard.

**Comment by GaryKriebel** [comment]
"2 minutes ago" is no longer the minimum timeframe listed.  I will close this and if we wish to update with a specific time format we can take that up then.
