### ISSUE TITLE
[production] update copyright date

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#1613]
Copyright on footer of OSF is currently: 
![screen shot 2015-01-27 at 4 39 43 pm](https://cloud.githubusercontent.com/assets/7749914/5928117/4c36e4e8-a646-11e4-9f84-e15dfc6d752d.png)

Should update to 2011 - 2015

**Comment by GaryKriebel** [comment]
Can this be dynamically built so that we don't have to submit another issue next year?

**Comment by brianjgeiger** [comment]
This issue is fixed by https://github.com/CenterForOpenScience/osf.io/pull/1704 - if we want to make the copyright end date dynamically built, that should be a new issue.
