### ISSUE TITLE
[Staging & Production] Add-ons: inconsistent list order in configuration table for Project Settings and user Settings

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#1616]
## Steps
1. Go to the user settings, add-on configuration table
2. Go to a project settings, add-on configuration table

## Expected
The order would be consistent from one to the other so a user would not mistakenly click incorrectly.

## Actual
Project settings for add-on configuration are listed alphabetically.  User settings are listed in a random, illogical order.

![screenshot 2015-01-27 18 09 30](https://cloud.githubusercontent.com/assets/9381062/5929412/9f53a246-a651-11e4-8e6b-7b5f2d6fc426.png)

![screenshot 2015-01-27 18 26 41](https://cloud.githubusercontent.com/assets/9381062/5929478/2b54e0de-a652-11e4-8527-13b56f3c8de5.png)

**Comment by brianjgeiger** [comment]
This is fixed.

![screen shot 2015-03-03 at 10 51 26 am](https://cloud.githubusercontent.com/assets/6599111/6466105/5591faba-c193-11e4-9284-22b32e79e822.png)
![screen shot 2015-03-03 at 10 50 14 am](https://cloud.githubusercontent.com/assets/6599111/6466106/55ad3bae-c193-11e4-904d-96c95209514b.png)
