### ISSUE TITLE
[production] Incorrect language for public component registration page for unauthenticated users

### ISSUE THREAD

**Issue by huangginny** [CenterForOpenScience/osf.io#1628]
Steps
-----------
1.DO NOT LOG IN.
2.Go to a public component that has not been registered.
3.Go to the registration page.

Expected
-----------
There should be a message telling the user that "there are no registrations for this project."

Actual
------------
![incorrect language](https://trello-attachments.s3.amazonaws.com/54c867eb200d6ff1ed579ede/1049x225/c210b02c86958db964b8552ef640dc03/Screen_Shot_2015-01-27_at_11.29.33_PM.png)
This would let first time users think that they might be able to register the parent project themselves.

**Comment by samanehsan** [comment]
I can look into this! @lbanner @GaryKriebel

**Comment by lbanner** [comment]
You got it!
