### ISSUE TITLE
Go/Nogo for release 0.24

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1635]
milestone: https://github.com/CenterForOpenScience/osf.io/issues?q=milestone%3A%220.24.0+%28OSF+Files%2C+Treebeard%2C+MFR%29%22+is%3Aclosed

changelog: https://github.com/CenterForOpenScience/osf.io/blob/develop/CHANGELOG

Deployment actions:

- [x] Change Tokumx log path (to prevent OS disk from filling up). 
- [x] Update python requirements
- [x] Install mfr requirements
- [x] Clear mfr cache
- [x] Clear mfr static assets `website/static/mfr/*`
- [x] Put up maintenance page (nginx)
- [x] Build assets
- [x] Take down maintenance page
- [x] Restart nginx
- [x] Restart celery
- [x] Restart uwsgi

Post release actions:

- [ ] Manual regression testing
- [ ] Update dev docs for installing/running waterbutler service

ping @JeffSpies @GaryKriebel @lbanner @caileyfitz @nicipfeiffer @brianjgeiger @caneruguz @chrisseto @jmcarp @icereval

**Comment by caileyfitz** [comment]
GO :raised_hands:

**Comment by chrisseto** [comment]
GO

**Comment by nicipfeiffer** [comment]
A long awaited, and my last :+1: GO!

**Comment by jmcarp** [comment]
:+1:

**Comment by caneruguz** [comment]
**GO** from Treebeard/Fangorn/Project Organizer

Harry's issue can't be replicated for now and is really minor (one line css that works with IE 5.5). 
Treebeard Tests repaired and running and is now part of Travis, (build passing).

**Comment by sloria** [comment]
Go

**Comment by GaryKriebel** [comment]
[Go Flight!](https://www.youtube.com/watch?v=zVf-rehP4b8)

**Comment by lbanner** [comment]
No argument -- 'Tis a GO! :+1: Woo Hooo! @nicipfeiffer 
..... Let's make sure @JeffSpies gets a chance to review and weigh in -- Thanks!

**Comment by icereval** [comment]
The issue with water butler servers going offline was tracked down to an auto update settings and FastStart option in the CSF Firewall, both have been set disabled (h/t @chrisseto).

Also a status page was added in water butler today allowing us to monitor the workers are online and accessible via the haproxy load balancer.

**Comment by lbanner** [comment]
Thank you @icereval  -- I know you noted it this morning -- just to reiterate for all: We've got multiple folk w/access to the status page + auto-notification to ping (via Text? Email?) if a server / workers down, correct?

**Comment by JeffSpies** [comment]
Brian G. is a go according to his text message.

**Comment by sloria** [comment]
@lbanner We have email notifications now. Michael will be setting up SMS notifications as well.

**Comment by JeffSpies** [comment]
go given verbally

**Comment by sloria** [comment]
Released!

**Comment by icereval** [comment]
@lbanner - Yes we have multiple dev's with access to the status page, monitoring has been setup to email on warnings/changes and page if it is critical.

**Comment by lbanner** [comment]
Thank you @icereval
