### ISSUE TITLE
JS console error appears after configuring two-factor authentication

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#1641]
Steps
--------
1) Go to the "Configure Addons" page for your user settings
2) Enable 2-factor authentication 
3) Refresh the page 
4) Check your JS console

Expected
-------------
No console errors

Actual
---------
The error message "No elements matching selector '#twoFactorScope'" appears in the console. 
![screen shot 2015-01-29 at 10 17 18 am](https://cloud.githubusercontent.com/assets/6414394/5960179/9adcdd6c-a7a1-11e4-8943-3461a5098cfc.png)

**Comment by brianjgeiger** [comment]
That's less than ideal. Everything works otherwise, though?

**Comment by sloria** [comment]
This is fixed now. @samanehsan Can you please verify this on production?
