### ISSUE TITLE
Renaming projects shows 404 in error console

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#1644]
Steps
--------
1. Go to a project you have admin rights for
2. Click on the project title to rename

Expected
------------
No 404s in error console

Actual
--------
404 in the error console. Nothing else seems to be affected. Projects rename, no errors visible unless you have the error console open.

The full error is "[Error] Failed to load resource: the server responded with a status of 404 (Not Found) https://osf.io/static/public/img/clear.png"

**Comment by lbanner** [comment]
@brianjgeiger Any impact on user here?

**Comment by brianjgeiger** [comment]
No. It's a minor, minor bug.

**Comment by GaryKriebel** [comment]
I did not see any 404s.... @brianjgeiger can you confirm?

**Comment by brianjgeiger** [comment]
Looks good.
