### ISSUE TITLE
Users should be able to log in from the landing page

### ISSUE THREAD

**Issue by HarryRybacki** [CenterForOpenScience/osf.io#1648]
### Problem

Unlike new users wanting to sign up for an account, existing users are required to navigate away from the landing page by clicking on the 'Create an Account or Sign-in' button at the top right of the navbar if they wish to log in to their accounts. ![screen shot 2015-01-29 at 3 34 36 pm](https://cloud.githubusercontent.com/assets/2614670/5965733/62b50574-a7cc-11e4-914a-2bb449dc4d42.png) This unintuitive and does not follow common patterns found on most mainstream web services. 

### Solution

Replace the 'Create an Account or Sign-in' button on the navbar with a sign-in widget on the landing page. All of the functionality that currently exists (standard username/password, two-factor input, and forgotten passwords) can be incorporated. 
![screen shot 2015-01-29 at 3 37 06 pm](https://cloud.githubusercontent.com/assets/2614670/5965790/c4cfb344-a7cc-11e4-845e-499c8e7c4558.png)

### Notes

1. This will not remove the page users currently use to sign in. It can still be used for redirects when unauthorized access is attempted e.g. a user who is not logged in navigates to a bookmark he/she has for a private project/component.
2. Two-factor input -- there are two routes for allowing users to enter two-factor codes
  1. Expand the new widget to include a third, optional field for two-factor codes like what currently exists.
  2. Create a more standard widget (only username/password) and redirect users that have two-factor auth enabled to another page after entering username/password where they can enter their two-factor code. This seems to be a common pattern.
3. I plan on working on this feature request

**Input requested!**

**Comment by brianjgeiger** [comment]
Rather than replacing the nav bar widget, what if you made the sign up box into a tabbed area defaulting to sign up that you could switch to log in?

**Comment by HarryRybacki** [comment]
@brianjgeiger interesting idea. I think this (and most UI) things should go up for a vote related to what 'feels' the most intuitive. Let's get some of the others to weigh in before I start working.

**Comment by brianjgeiger** [comment]
@caneruguz likes to be involved in things like this.

**Comment by fabianvf** [comment]
I like to be able to log in to a site without having to do any navigation whatsoever, and I don't really see much of a functional difference between clicking a link and clicking a tab.

**Comment by HarryRybacki** [comment]
I agree with @fabianvf . Facebook, Twitter, Google all do it this way and we know they've done the research.

**Comment by caneruguz** [comment]
I think this update should involve generally rethinking the sign up process and should include the current login page as well that has three different purpose forms in the same place. I think an incremental small step doesn't go far enough to improve the user login experience and an overhaul would need more time.

Having said that I'm not sure to what extent this fix aligns with our 3 month priorities. I'm wondering whether it would be best to start work on this in the next 3 month sprint.  I would ask Jeff about his thoughts on the timeline for a project like this.

**Comment by brianjgeiger** [comment]
@HarryRybacki I think I mis-interpreted your original proposal, my apologies. That sounds like a good plan. I'll be interested in how you do the two-factor, though. Three fields?

**Comment by HarryRybacki** [comment]
@brianjgeiger Do we have a way of easily determining what percentage of users have two-factor enabled?

**Comment by brianjgeiger** [comment]
Should be a simple db query. I don’t know what that query is off the top of my head. I expect the number to be very small right now.

**Comment by HarryRybacki** [comment]
Josh is grabbing that info for me. If it's small I'll opt for two fields (username/password) with a forward for two-factor to keep the landing page as clean as possible. This can be changed later on if the percentage grows.

**Comment by brianjgeiger** [comment]
Based on past discussions, the login procedure will have to be re-worked more that you may be anticipating in order to do a two-stage login. @lyndsysimon has been considering doing that re-work, but hasn't had the time, so you might want to check with him about that.

**Comment by HarryRybacki** [comment]
Will do, thanks!

**Comment by brianjgeiger** [comment]
If that doesn't work out, you could have the two factor field drop down, possibly with a submit button, if focus is in the username/password field. Or something similar.

**Comment by samanehsan** [comment]
@HarryRybacki, issue #879 has some discussion about re-working the login process that you might be able to address as well.
