### ISSUE TITLE
Empty fork screen

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#1654]
Steps
--------
1. Go to or project that:
    1. has no forks 
    2. you have only write permissions for
    3. is private
2. Go to forks tab

Expected
------------
Something that says that there are no forks of this project

Actual
---------
Between the project tabs and the footer is only empty space

![screen shot 2015-01-30 at 12 54 44 pm](https://cloud.githubusercontent.com/assets/6599111/5980526/365232d2-a87f-11e4-8b5b-9892cb2dcaec.png)

**Comment by caneruguz** [comment]
The current forks file (**forks.mako**) has this. There should probably be a change in the logic of if else there or an additional message

```html
<div class="row">
	<div class="col-md-8 col-md-offset-2">

	% if node['fork_count']:
	    <div mod-meta='{
	            "tpl": "util/render_nodes.mako",
	            "uri": "${node["api_url"]}get_forks/",
	            "replace": true
	        }'></div>
	% else:
	    <div>There have been no forks of this project.</div>
	% endif


	</div>
</div>
```

**Comment by brianjgeiger** [comment]
I would expect that to should the "No forks" message. I wonder why it's not. I presume there are forks that are, for some reason, not visible?

**Comment by nanchen47** [comment]
Also the message if there is no forks are no line up as registration page.
![screen shot 2015-04-03 at 4 13 06 pm](https://cloud.githubusercontent.com/assets/11743657/6988142/581c2368-da1c-11e4-9598-fa0e6c9814d5.png)
![screen shot 2015-04-03 at 4 12 59 pm](https://cloud.githubusercontent.com/assets/11743657/6988143/5be9f114-da1c-11e4-9a0f-3a6748a8cddc.png)

**Comment by fayetality** [comment]
Brian can you recreate the blank Forks page again? I can't seem to get it to happen on my end.

**Comment by brianjgeiger** [comment]
¯\_(ツ)_/¯ I think I ran across it last time. On production, it's at https://osf.io/api6f/forks/

**Comment by brianjgeiger** [comment]
To reproduce, I expect you will need two user accounts, one that can admin the project and one that only has write access. It's possible this needs to be a component rather than a project.

**Comment by brianjgeiger** [comment]
@fayetality You should now have write access to the project linked above on osf.io so you should be able to at least see the problem in production.

**Comment by chennan47** [comment]
This is what shown on the project now. 
![screen shot 2015-05-18 at 3 43 05 pm](https://cloud.githubusercontent.com/assets/4974056/7688693/a2c80492-fd74-11e4-9101-ad0105b10e1f.png)
I will take a look at sentry later.

**Comment by lyndsysimon** [comment]
The problem was with the return value of `_view_project` - `fork_count` was counting registrations of forked nodes as well as the forked nodes themselves, and in some cases it is possible for the forks to have been deleted while registrations of those forks remained.

 len(node.node__forked.find(
                Q('is_deleted', 'eq', False) &
                Q('is_registration', 'ne', True)
            )),
