### ISSUE TITLE
Add a feedback button that links to issue tracker or Desk.com

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1656]
It would be nice to have a quick way to capture user feedback. This was discussed informally a long time ago, but dismissed after we started using GH and Desk.com for issue tracking and support, respectively.

I like Gratipay's approach  in https://github.com/gratipay/gratipay.com/pull/3101 , which adds a feedback button that just links to the GH issue tracker. We could also link to a mailto link to our Desk.com email.

I think this would be a quick and effective way to encourage feedback without having to change our current processes.

**Comment by jmcarp** [comment]
:+1:

**Comment by lbanner** [comment]
:+1:
