### ISSUE TITLE
[production] Python files icons fail to show on hgrid

### ISSUE THREAD

**Issue by huangginny** [CenterForOpenScience/osf.io#1657]
Steps
--------------
1. Upload a python file to the osf storage, or link an addon that contains a python file to your project
2. Click on the "Files" tab

Expected
----------------
![screen shot 2015-01-30 at 2 35 50 pm](https://cloud.githubusercontent.com/assets/8628591/5982042/5a2cb142-a88d-11e4-90fc-a1f8cbf59c30.png)

Actual
------------------
![screen shot 2015-01-30 at 2 32 16 pm](https://cloud.githubusercontent.com/assets/8628591/5982019/2dd02b6a-a88d-11e4-8490-711a84be15d5.png)

Possible causes
-------------------
From @sloria on Flowdock: "wonder if the icon plugin is trying to load 2 different files for the .py extension?"

**Comment by sloria** [comment]
Hm, the permissions on `file_extension_py.png` is different from the other icon files. I'll try changing them and seeing if that fixes it.

**Comment by brianjgeiger** [comment]
I am not seeing that on any of my browsers.

**Comment by huangginny** [comment]
@brianjgeiger Chrome version 40

**Comment by brianjgeiger** [comment]
Just upgraded from 39 to 40 and it's not happening on my project (IE, Chrome, Safari, Firefox). Hmm.I've just added you to the project I'm using. Could you check it out and see if you see it there, too? https://osf.io/rcqxp/files/

**Comment by sloria** [comment]
@brianjgeiger Seems to be probablistic. I have only seen it once. After refreshing, it went away

**Comment by huangginny** [comment]
![screen shot 2015-01-30 at 2 51 55 pm](https://cloud.githubusercontent.com/assets/8628591/5982288/8e5cd076-a88f-11e4-88d8-2761d74ebc82.png)
@brianjgeiger 
On the file browser on the OVERVIEW's page it looks good though

**Comment by sloria** [comment]
Hm, was not able to reproduce. Deferring for now, since this is very minor. If anyone sees this again, please inspect the row element to see the path to the errant image.

**Comment by GaryKriebel** [comment]
I am not seeing this issue.  @sloria should this stay open or be closed.

**Comment by sloria** [comment]
I have seen this in the past, but I have not been able to reproduce it reliably. Let's close for now. Reopen if it happens again.
