### ISSUE TITLE
Modals disable scrollbar and shift navbar right

### ISSUE THREAD

**Issue by HarryRybacki** [CenterForOpenScience/osf.io#1663]
## Steps
1. Go to any page with a modal e.g. the login page
![screen shot 2015-02-02 at 9 42 01 am](https://cloud.githubusercontent.com/assets/2614670/6002525/106967f8-aac2-11e4-8888-32eea685aab7.png)

2. Click link that activates modal
![screen shot 2015-02-02 at 9 42 10 am](https://cloud.githubusercontent.com/assets/2614670/6002528/14d83558-aac2-11e4-87f9-0e6f00c0d43f.png)

## Expected
1. When the modal pops up the navbar should not move.

## Actual
1. When the modal pops up the navbar shifts to the right

## Possible Cause
1. This might have something to do with the scroll bar disappearing? The navbar seems to move to the right approx. the same distance as the width of the scroll bar.

## Environment
1. I was able to recreate this bug on Chrome (40.0.2214.94 (64-bit)), Firefox (35.01), and Safari (7.1.2 (9537.85.11.5) for production and development on Mac OS X 10.9.5.

## Additional Example:
![screen shot 2015-02-02 at 9 41 18 am](https://cloud.githubusercontent.com/assets/2614670/6002583/9aa9d6aa-aac2-11e4-9d35-57eaf8a3db56.png)
![screen shot 2015-02-02 at 9 41 32 am](https://cloud.githubusercontent.com/assets/2614670/6002584/9e79b8c2-aac2-11e4-909c-7b693a44fe3f.png)

**Comment by HarryRybacki** [comment]
@caneruguz

**Comment by brianjgeiger** [comment]
There's a handy animated gif in #1675 that shows off the effect

**Comment by caneruguz** [comment]
So this issue is prominently discussed in Bootstrap and there is a PR submitted for it: https://github.com/twbs/bootstrap/pull/15353

I recommend that we close this issue and wait for Bootstrap to resolve it. The only other alternative is to add a sitewide readjustment which may not be necessary and may require tests.

**Comment by lbanner** [comment]
OK @caneruguz -- I am good with that, thanks.
