### ISSUE TITLE
Dataverse file upload errors and file does not upload

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1665]
Reported by @nicipfeiffer on the 0.24 Trello board

# Steps
1. Go to a project that has dataverse configured
2. Go to the files page
3. Change the dataverse to 'draft'
4. Click on the 'upload' button
5. Select a new file to upload

# Expected
The file should say 'pending', then 'uploaded 100%', then the file should appear in the list of files

# Actual
First the file says 'uploaded 100%', then it says 'file pending', then I get an error '<html><head><title>504 Gateway' and then the file does not upload.

![image](https://cloud.githubusercontent.com/assets/5975444/6002678/7c3c08cc-aac3-11e4-8835-8d92c2f236dc.png)

**Comment by lbanner** [comment]
Let's Defer as the Dataverse work -- and their API -- gets resolved.

**Comment by nanchen47** [comment]
related to https://github.com/CenterForOpenScience/osf.io/issues/1673

**Comment by rliebz** [comment]
I have not seen this issue in particular since working with Dataverse 4.0 and Waterbutler. Because we have an open issue for Dataverse upload difficulties (https://github.com/CenterForOpenScience/osf.io/issues/2224) with a more in-depth/recent discussion, I recommend this issue be closed.

**Comment by lbanner** [comment]
:+1:
