### ISSUE TITLE
[staging & production] 'Server responded with 0 code' message when two users upload file at same time

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1668]
This is a problem for Safari and IE

# Steps
1. Have two users as contributors on the same project
2. Each user has a file with the same name but different content
3. Both users upload the file with the same name to the same project at the same time

# Expected 
An error message such as "Another file with the same name is currently being uploaded" should be seen by the user whose file did not upload

# Actual
The person who is some milliseconds slower got an error message that says "Server responded with 0 code" 

![image](https://cloud.githubusercontent.com/assets/5975444/6003237/e41c8b66-aac7-11e4-9e2b-4433f78b8da0.png)

**Comment by GaryKriebel** [comment]
With the recent waterbutler / files work, this is no longer an issue.
