### ISSUE TITLE
[staging & production] Cannot deauthorize GitHub for components on user settings page

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1670]
# Steps
1. Go to a component and authorize GitHub for that component
2. After authorization, go to your user settings page and the Configure Add-ons tab
3. Under Authorized Projects, press the red **x** to remove authorization

# Expected
I expect that the project would be deauthorized

# Actual
An error pops up saying that the project could not be deauthorized. This appears to only happen with components and not projects.

# Some helpful info from BrianG
![image](https://cloud.githubusercontent.com/assets/5975444/6003863/ef71945c-aacc-11e4-8b16-8086ae16ad22.png)

- It's getting a Bad Request (see image). I can't find a corresponding problem in Sentry, which is not surprising as it's a 400-series error.
- When successfully removing the auth from the Project Settings page rather than the User Settings page, it uses /api/v1/project/p7uvk/node/rvb89/ rather than the failed /api/v1/project/rvb89/ as in the screenshot.
- Useful context for anyone trying to fix this bug (please include with issue report): https://github.com/CenterForOpenScience/osf.io/blob/e209a3722a4ac554b308a57a93e852fc0c3cbe41/website/static/js/addonPermissions.js#L22 is not generating the url correctly for components. For components, it would be /project/\<pid\>/node/\<nid\>. There are helpers for creating the URLs correctly.

# CELEBRATE :tada: :cake: 
This is my 100th issue reported on GH! :tada: :balloon: :tada:

**Comment by huangginny** [comment]
:fireworks: :cake: :congratulations: :tada: Congrats Cailey :)

**Comment by GaryKriebel** [comment]
I am not seeing this behaviour.

@caileyfitz can you check again..

**Comment by caileyfitz** [comment]
Still happening on staging and production
![screen shot 2015-02-24 at 11 59 38 am](https://cloud.githubusercontent.com/assets/5975444/6354332/bea7b2d2-bc1c-11e4-84cf-1afc5f7ec9c3.png)
