### ISSUE TITLE
[staging & production] Files with ? in them can't be found

### ISSUE THREAD

**Issue by jeg3tw** [CenterForOpenScience/osf.io#1671]
Reported by @erinspace on the 0.24 Trello board.

# Steps
1. Upload a file with a ? in its name.
2. Attempt to view file.

# Expected
The file would be found and rendered.

# Actual
The file is not found at all by the OSF: "Page Not Found" error.

![](https://trello-attachments.s3.amazonaws.com/54c81f2bfc84a37ba34d9cdf/640x364/a3a5cc082e26c558b463da0bea05aea7/question.gif)

**Comment by GaryKriebel** [comment]
This is no longer an issue.
![screen shot 2015-02-24 at 11 18 59 am](https://cloud.githubusercontent.com/assets/9437946/6353378/fb0ead8a-bc16-11e4-8a66-6e94fca2061a.png)
