### ISSUE TITLE
[staging & production] Removing target project from onboard upload during process does not cancel upload

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1672]
# Steps
1. Navigate to the dashboard
2. Choose a large file to upload 
3. Drag and drop it onto the onboarder
4. Choose a target project 
5. Press 'Upload'
6. While the file is being uploaded, click the x by the project name

# Expected
I would expect that clicking the x would cancel the file upload, as there no longer appears to be a target destination for the file

# Actual
The file is uploaded as normal to the project which was selected at time of upload. There is no indication that a user even pressed the x at all.

# Suggestions
I would suggest either disabling the x during upload, or, consistent with pressing the x by the file name, I think that pressing the x by the project should cancel the upload.

**Comment by nanchen47** [comment]
Perhaps the cross should be disabled while uploading. I don't think we support the functionality to cancel upload right now.
