### ISSUE TITLE
[staging & production] Dataverse .jpg files give a redirect loop error

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1673]
Reported by @nicipfeiffer on the 0.24 Trello board

# Steps
1. Go to a project and configure the dataverse add-on
2. Go to the files tab of the project and click on a .jpg file to go the file detail page and render a view

# Expected
Should see a rendered view of the file

# Actual 
After waiting a long time: receive a redirect loop error.
![image](https://cloud.githubusercontent.com/assets/5975444/6004122/83a8a63c-aace-11e4-9cb8-d3513676e8aa.png)

When opening a PDF file -- the following error occurs:
{"code": 500, "referrer": "https://staging.osf.io/6wsre/", "message_short": "Unable to resolve", "message_long": "OSF was unable to resolve your request. If this issue persists, please report it to <a href=\"mailto:support@osf.io\">support@osf.io</a>."}

**Comment by lbanner** [comment]
With Dataverse work upcoming - I am going to defer this for now.

**Comment by nanchen47** [comment]
@caileyfitz check again after April 13th when dataverse update is done.

**Comment by rliebz** [comment]
I have checked several .jpg files and have not been able to reproduce this issue with Dataverse 4.0.

**Comment by lbanner** [comment]
Cool -- I will close. TY
