### ISSUE TITLE
[production] 'Add Link' does not retrieve all projects 

### ISSUE THREAD

**Issue by jeg3tw** [CenterForOpenScience/osf.io#1674]
Reported by @caileyfitz on the 0.24 Trello board.

# Steps
1. Create a project titled A
2. Go to another project
3. Click the 'Add Links' button
4. Search for "A"

# Expected
The project title A should show up in the search results, especially when searching directly under My Projects.

# Actual
The search results truncate and there is no way to find project A and add it as a link. This is more a problem for those who have a lot projects.  The list of projects truncates in the 'Add Link' modal.

**Comment by brianjgeiger** [comment]
This really is the same issue as #1695. The other one is probably a bit more useful of a report, so I'm closing this on.
