### ISSUE TITLE
[staging & production] IE: File names go past recent activity box

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1676]
Reported by @himicakumar on the 0.24 Trello board

# Steps - using IE
1. Upload a file name equal to or greater than 200 characters
2. Go to project page

# Expected
File names would stay inside the "Recent Activity Box"

# Actual
File names goes past recent activity box frame. 

![image](https://cloud.githubusercontent.com/assets/5975444/6004239/4e49ae5e-aacf-11e4-95ee-ca42e3aa0a5c.png)

**Comment by caneruguz** [comment]
For future reference, we need Browser version numbers and Operating Systems for these error reports, especially for IE.

**Comment by caileyfitz** [comment]
@caneruguz I agree that would be helpful info. I just asked @himicakumar and she said IE 11 and Windows 8.1

**Comment by caneruguz** [comment]
Very cool, thanks!
