### ISSUE TITLE
[staging & production] Console error when downloading file in all addons & OSF Storage

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1677]
Reported by @samanehsan on the 0.24 Trello board

# Steps
1) Go to a project with the figshare addon configured
2) In the files page, try to download the file (make sure it is published on figshare) 
3) Go to the file detail page and download the file. 

# Expected
The file downloads and there are no error messages in the console. 

# Actual
In both cases the file does download, but I see the following error message in the console. 
![image](https://cloud.githubusercontent.com/assets/5975444/6004363/4824276a-aad0-11e4-894a-bc0bb9300c76.png)

From Chrome: 
![image](https://cloud.githubusercontent.com/assets/5975444/6004369/4fbc2c66-aad0-11e4-9894-f13042f4d1e7.png)

# Updates 
This appears to affect all add-ons in Safari and Chrome. @chrisseto has linked a relevant stackoverflow question: https://stackoverflow.com/questions/12359600/failed-to-load-resource-frame-load-interrupted-agian

**Comment by nanchen47** [comment]
@caileyfitz can't repo this problem anymore. Can you verify if this problem still exist?

**Comment by caileyfitz** [comment]
@nanchen47 I cannot reproduce this problem either.

**Comment by lbanner** [comment]
Likely overcome with recent deployments around files -- I will close -- TY!
