### ISSUE TITLE
IE: OSF Allows you to move items form parent project to component, but it doesn't work.

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1680]
Reported by Harris on the 0.24 Trello board

# Steps
1.) Upload a doc/item to project.
2.) Create a component
3.) In file tab or on main project page drag and drop doc/item from parent project into collection

# Expected
OSF will not allow you to drag and drop items from parent project to collection (this is the case on other browsers and on production)

# Actual
Drag and drop works, item called file_extension_zip[1].png appears with "upload pending" indefinitely

# Updates
Himica says, "This is also happening to me when I try to move a file from dropbox to osf storage or vice versa."
![image](https://cloud.githubusercontent.com/assets/5975444/6005030/39248a34-aad5-11e4-80ea-bcbddfbeaf58.png)

**Comment by lbanner** [comment]
Assuming this is a bug on Production + Staging? @caileyfitz  --- Agreed - should not be allowed until we actually implement such.

**Comment by caneruguz** [comment]
What seems to be happening here is that the user is selecting the icon for a file and dropping it into Components. 

When this happens the browser is thinking that the item is the image file and makes it a droppable file. It will then try to upload that file regularly as if it was brought from somewhere else. The file itself is not being dragged, it is impossible to drag and drop files themselves, these are just the icon images (which are themselves files). 

Any suggestions on what to do about this? @sloria @brianjgeiger

**Comment by brianjgeiger** [comment]
@caneruguz I think the proper fix is to make the icon a background image rather than just an image, which should keep it from being draggable.

**Comment by caneruguz** [comment]
Yes that makes sense, it will need bit of an overhaul of the icon function but not a big deal. @lbanner can you assign me to this issue?

**Comment by lbanner** [comment]
Done!

**Comment by caneruguz** [comment]
@Steve I sent a PR for this.
