### ISSUE TITLE
[staging & production] Shift-select in Modified or Contributors column in Project Organizer also selects text

### ISSUE THREAD

**Issue by jeg3tw** [CenterForOpenScience/osf.io#1681]
Reported by @brianjgeiger on 0.24 Trello board.

# Steps
1. Have some projects in your dashboard folder
2. Click on the top project in the contributors column
3. Shift click on the last project in the contributors column

# Expected
The rows chosen by shift-select will selected.
*this does not occur when clicking in the Name column*

# Actual
The rows AND texts are being selected.

![](https://trello-attachments.s3.amazonaws.com/54c9617582f0402ba8250c01/668x394/14efaac34d3275a3d427bcf68e087b82/selecting-in-other-columns.gif)

**Comment by GaryKriebel** [comment]
Fixed with https://github.com/CenterForOpenScience/osf.io/pull/2606

**Comment by samanehsan** [comment]
Closing since #2606 has been merged.
