### ISSUE TITLE
[staging & production] Formatting issues on project organizer header

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1682]
# Steps
1. Go to the project organizer
2. Click on a project/component to rename it
3. Rename with a long name (some long words, add spaces, short words, more long words, etc)

# Expected
Project/component name would stretch across entire header

# Actual
With a long title, there is some weird formatting going on and title does not stretch across entire length of header. See images.
![image](https://cloud.githubusercontent.com/assets/5975444/6005173/3ff2161e-aad6-11e4-8e95-57748564a6fa.png)

@jlcohoon adds "It's still covering the same width. If I have one really long word, the column is wider (image two below), but if I add spaces to make multiple words, the column shrinks (image directly below)."
![image](https://cloud.githubusercontent.com/assets/5975444/6005179/50f7d282-aad6-11e4-89e6-6615afbc13c9.png)

ping @caneruguz

**Comment by caneruguz** [comment]
@lbanner This one is also something I should handle. Can you assign me?

**Comment by caneruguz** [comment]
It looks like this issue was fixed in the merged PR. @lbanner we can close this issue as well.

**Comment by lbanner** [comment]
OK -- Closing -- TY
