### ISSUE TITLE
[staging & production] MFR: Won't render files that have blank names and are only the extension

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1685]
Reported by @erinspace on the 0.24 Trello board

# Steps
1. In windows, create a file with just spaces for the name
2. This file will be saved as a file with no name and only an extension
3. Upload this file to the OSF
4. Click the file to render

# Expected 
- The file will be recognized and rendered 

# Actual
- The page times out once, and then renders a blank page subsequent times after that.

**Comment by lbanner** [comment]
Not an overly likely scenario -- good to be aware -- defer for now.
