### ISSUE TITLE
[staging & production] 'Add Existing Project' button does not work with tab selection

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1687]
# Steps
1. Navigate to the dashboard
2. Select a folder on the project organizer and then click 'Add Existing Project'
3. Start typing the name of a project
4. When the name of the project you are typing comes up, use the down arrow to select the project and then press tab
5. Try to add the project via the 'Add' button

# Expected
I would expect that this would sufficiently select the project and allow a user to add it to the folder. 

# Actual
The 'Add' button is disabled. The only way to enable the button to be able to actually add a project is to click with your pointer to select the project. Tabbing doesn't work, and simply typing the name of the project doesn't work.

**Comment by caneruguz** [comment]
Typeahead doesn't support this: https://github.com/twitter/typeahead.js/issues/726
We can try to look for ways around it or defer it for the moment. 

Thoughts @brianjgeiger ?

**Comment by brianjgeiger** [comment]
I vote for defer. At some point, we may have an intern or someone go through all of those widgets and unify them on a single widget, and we can point to this as a requirement, but I don't think we should try to change typeahead right now.

**Comment by nanchen47** [comment]
Will be worked on when we redesign the dashboard page.
