### ISSUE TITLE
[feature request] Add a 'cancel upload' button for file uploads in progress

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1688]
Reported by @HarryRybacki on the 0.24 Trello board

Related to https://github.com/CenterForOpenScience/osf.io/issues/758 but new issue since we are now using Treebeard

# Steps
(1) Navigate to a projects file section
(2) Click 'Upload Files'
(3) Select file to upload
(4) Click 'Open' and watch the file upload begin
(5) Realize you selected the wrong file after starting the upload
(6) Try to cancel the upload in progress

# Expected
Click a button that cancels the upload in progress.

# Actual
Either wait for the upload to complete and delete it afterwards or manually force the browser 'back' to kill the upload.

Both actual options are undesirable. One is inefficient and can take excessive time (especially for larger files). The other can throw off a workflow unnecessarily.

![image](https://cloud.githubusercontent.com/assets/5975444/6005601/8d36b30a-aad9-11e4-89d3-66a366bc1a4b.png)

**Comment by caneruguz** [comment]
This is not just a UI process, I think waterbutler needs to intervene here about what happens when file upload is canceled. Tagging @icereval @chrisseto @jmcarp

**Comment by lbanner** [comment]
Sounds good @caneruguz

**Comment by icereval** [comment]
If an upload is cancelled WaterButler will just disconnect the upload from the third party (Dropbox, S3 etc..) so you should be fine to just cancel the upload and report the operation back to the user via the frontend client.

**Comment by caneruguz** [comment]
Okay then @lbanner you can assign this to me as well.

**Comment by nanchen47** [comment]
related to https://github.com/CenterForOpenScience/osf.io/issues/2282. Discussion can be continued there.
