### ISSUE TITLE
[feature request] File browser should save collapse/expand state

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1691]
Reported by @sloria on the 0.24 Trello board

Unlike the project organizer, the file browser does not save folders' collapse/expand state, which can be a major annoyance when navigating between pages.

**Comment by caneruguz** [comment]
@lbanner This isn't something I can complete by myself, it's actually not a UI issue, there needs to be some backend that saves this information. Once I have that API path I can do the rest.

**Comment by brianjgeiger** [comment]
There are a bunch of potential issues with this as well. I think it would make the most sense to bundle it in with the eventual "customizable dashboard" talked about for a future epic.

**Comment by lbanner** [comment]
OK - Thanks!
