### ISSUE TITLE
[feature request] Success message when enabling add-ons in user settings

### ISSUE THREAD

**Issue by jeg3tw** [CenterForOpenScience/osf.io#1692]
Reported by @caileyfitz on 0.24 Trello board.

# Steps
1. Go to user settings page
2. Go to Configure Add-ons
3. Click a couple add-ons to enable
4. Press submit

# Expected
There would be a success message saying "Settings updated."

# Actual 
There is no message. The submit button lights up for a fraction of a second after clicking it without a message. Additionally, there is a success message on the project settings page.
*discovered that the success message doesn't happen until you authorize an add-on*

**Comment by nanchen47** [comment]
related to https://github.com/CenterForOpenScience/osf.io/issues/1621

**Comment by samchrisinger** [comment]
Related to, perhaps resolved in https://github.com/CenterForOpenScience/osf.io/pull/2414
