### ISSUE TITLE
[feature request] Reduce the number of colors used in File/project highlighting

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1693]
Reported by @jlcohoon on the 0.24 Trello board

The search bar, the highlighting of a selected folder in the project organizer, the highlighting when hovering over a file, the highlighting when hovering over a folder when uploading a file, and the file uploading progress bar all use different shades of green/yellow/blue. 

Can we reduce this number at all? Perhaps at least re-using the search-bar green as one or more of the highlight colors?

![image](https://cloud.githubusercontent.com/assets/5975444/6005809/31250ef2-aadb-11e4-94fc-2427aaaaf173.png)

![image](https://cloud.githubusercontent.com/assets/5975444/6005815/354be9ec-aadb-11e4-94d5-161ec7e330e9.png)

![image](https://cloud.githubusercontent.com/assets/5975444/6005818/39954a66-aadb-11e4-94b5-34aaf9ebaea0.png)

**Comment by brianjgeiger** [comment]
Why do you hate color, @jlcohoon?

That being said, a properly developed color palette would be a good idea.

**Comment by lbanner** [comment]
'properly developed color palette' -- it's on our list. Let's work with @brianjgeiger @caneruguz and @KatyCain526 on this -- I will try to remember to get us moving forward here.

**Comment by nanchen47** [comment]
Perhaps at some point, also include a color-blind board for color-blind user to adjust the color for themselves.

**Comment by caneruguz** [comment]
The color blind and accesibility issue should be handled more significantly throughout the site. I think it's worthy to be considered, but it's more than a single issue.

**Comment by lbanner** [comment]
Yes - that should be a separate issue, agreed. RE: this issue, specifically looking at our use of color in the file/project area -- Is this opportunity to apply what you are developing for scheme @caneruguz ?

**Comment by caneruguz** [comment]
My working version is already using colors from the palette I sent, there are now essentially only two colors for rows, the dark blue for selected and hover colors.

**Comment by samanehsan** [comment]
@lbanner, @GaryKriebel this has been fixed on production with Caner's changes and can be closed.
