### ISSUE TITLE
Dataverse download buttons are part of a "button group" when they should not be

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1694]
Reported by @jlcohoon on the 0.24 Trello board

The blue download buttons, as well as the grey upload button, for Dataverse have the "btn-group" class applied to them. This makes their right side not have rounded corners. 

![image](https://cloud.githubusercontent.com/assets/5975444/6005865/9a48ec8c-aadb-11e4-96d1-fca26cedfa1a.png)

This class should be removed for all instances except for the upload/release study buttons for "draft" dataverses.
![image](https://cloud.githubusercontent.com/assets/5975444/6005863/96615ece-aadb-11e4-9c58-c0ce0d07880d.png)

**Comment by lbanner** [comment]
@caner?

**Comment by caneruguz** [comment]
Yes I'm on it.
