### ISSUE TITLE
[staging & production] Add pagination for 'Add Link' results

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1695]
Related to https://github.com/CenterForOpenScience/osf.io/issues/1674

# Steps
1. Go to a project
2. Press 'Add Links' button near 'Add Component'
3. Search for "a" (but no quotes) and click 'Search all projects'
4. Scroll through all the search results

# Expected
I expect that after a certain number of search results, there would be some pagination so that there's not an endless list of results

# Actual
There is no pagination at all. The list just truncates with no indication that there are more projects (and I *know* there are more than 20 or so projects with the letter "a" in them). This is bad.

**Comment by nanchen47** [comment]
The paginator has already been added to 'Add Link' results and checked on production that this problem has been solved.
