### ISSUE TITLE
[staging & production] 'Add Links' modal scrolls out of darkened background

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1696]
Related to https://github.com/CenterForOpenScience/osf.io/issues/1695

# Steps
1. Go to a project
2. Press 'Add Links' button near 'Add Component'
3. Search for "a" (but no quotes) and click 'Search all projects'
4. Scroll through all the search results

# Expected
I expect the darkened background that is seen with pop-up modals would persist throughout scrolling. 

# Actual
The background only extends as far down as the current screen. Scrolling past that scrolls out of the darkened background. See gif.
![2015-02-02 13_32_04](https://cloud.githubusercontent.com/assets/5975444/6006386/1bc4fca2-aae0-11e4-81db-f7922b9b4a4e.gif)

**Comment by lbanner** [comment]
@caneruguz  -- This one for you?

**Comment by caneruguz** [comment]
Not actually a Treebeard issue but I can look into it. I believe modals should not themselves be very long, they should have internal scrolling. I can do the fix for this.

**Comment by lbanner** [comment]
TY!
