### ISSUE TITLE
Sign up field labels are not displayed in IE9

### ISSUE THREAD

**Issue by JeffSpies** [CenterForOpenScience/osf.io#1703]
From mycrowd....

# Summary of the Bug

Sign up field labels are not displayed in Internet Explorer v9.0

![1](https://cloud.githubusercontent.com/assets/512000/6014091/1976ed7e-ab2c-11e4-8377-078fa049d7d9.jpeg)

# Set of Steps to Reproduce:

1) Go to http://www.osf.io in Internet Explorer v9.0 
2) Observer Image attached. Sign up fields labels are not displayed. 
3) This make it difficult for user to enter what in which field. 
4) This is not happening in other browsers.

# System Config:

Operating System: Windows 7 6.1.7601
Browser: Internet Explorer 9.0

**Comment by sloria** [comment]
This was also reported in https://github.com/CenterForOpenScience/osf.io/issues/1483
