### ISSUE TITLE
Cannot delete .sta file from file details page

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1719]
<h4>Steps</h4>
1. Upload a file to the OSF. I uploaded a .sta file and this was producing the error. I have not yet replicated it with another file. You can access the file I used <a href="https://www.dropbox.com/s/7jac9ud8pvkox8u/Data%20-%20Harmon-Jones%202008%20Study%202%20Replication%20Project%20-%20Gable%20%26%20Mechin.sta?dl=0">here</a>.
2. From the file's detail page, click on delete.
3. When that fails, go to the file tree and delete the file from there by clicking the "x" in the action column

<h4>Actual</h4>
1. The user sees an error pop up when they try to delete the file from the file detail page. The console logs an error (shown below) as well.
![screen shot 2015-02-04 at 4 17 09 pm](https://cloud.githubusercontent.com/assets/4965832/6050039/6c9ead98-ac8a-11e4-895d-79d55fc55016.png)
2. From the file tree, deleting is successful.

<h4>Expected</h4>
1. The user should be able to delete files of any type from the detail or file tree pages.

**Comment by lbanner** [comment]
Replicated -- Ye, 'tis a :bug:  -- This is WaterButler arena? @brianjgeiger

**Comment by huangginny** [comment]
I can't replicate this bug on production.  @jlcohoon can you add me (Ginny Huang) as a contributor to your project so I can try there?

**Comment by jlcohoon** [comment]
It seems to be working now actually. @huangginny, it's wasn't the project that's the problem—it's that particular file. In any case, it seems to be fixed.
