### ISSUE TITLE
Don't allow user to select Dropbox root

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#1721]
Steps
-------
1. Add Dropbox plugin to a project and authorize it

Expected
------------
You should be able to select any folder in your dropbox except the root

Actual
--------
You can select any folder including the root

h/t @huangginny for finding this

**Comment by huangginny** [comment]
I can take this issue @sloria

**Comment by sloria** [comment]
We actually have been allowing users to choose the root folder. It should behave just like any other folder within a Dropbox.

Apologies for the misguidance.
