### ISSUE TITLE
Unconfirmed contributors do not show up in search results for a project

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1724]
<h4>Steps</h4>
1. Search the OSF for a project that has an unconfirmed contributor (ie. a non-OSF user added to it)
For example, search for "Halevy"

<h4>Actual Results</h4>
1. Only confirmed contributors show up in search results. For instance, if you visit the project, you see three contributors—one unconfirmed. The search results only show the two confirmed contributors.
![screen shot 2015-02-05 at 10 13 26 am](https://cloud.githubusercontent.com/assets/4965832/6062869/0062a854-ad21-11e4-9f5d-e92b9fc2a56e.png)

![screen shot 2015-02-05 at 10 13 30 am](https://cloud.githubusercontent.com/assets/4965832/6062861/e520f6cc-ad20-11e4-96a5-e9e926aed712.png)

<h4>Expected Results</h4>
1. I would expect that all contributors would show up in search results of projects, not just the confirmed contributors.

**Comment by brianjgeiger** [comment]
The reason it's not happening right now is that all of the information inside of the search results is based on what's indexed in Elastic Search. We could put in AJAX requests for contributor lists, but that's potentially 10 projects worth of gathering contributors, so if someone did a search for RPP and got it and 9 registrations of RPP, then there's a bunch of very slow requests to get that information.

Another option is to potentially index unconfirmed users as if they are real users. That's a good vector for spam there, and while we're not super-concerned about it now, we probably want to think about how we implement with that in mind. It's not the only vector, mind, and we'll have to deal with it at some point, so we could go ahead and implement regardless.

The only thing I'm not sure about is if there's any linkage between the contributors list and the users list. We wouldn't want to try to show unconfirmed users in the user search. I presume they're not, but I think @fabianvf could answer that for sure.

We might also need a little more logic in the search view model or template if we implement to ensure that contributors who are unconfirmed don't have links. That should be very easy.

**Comment by lbanner** [comment]
Agreed that ideally all contributors, confirmed or not, might be searchable -- but for now, and thank you @brianjgeiger for insight, let's defer until we analyze search again as a whole.

**Comment by fabianvf** [comment]
We currently purposefully filter unconfirmed users out of the search results, but they should still probably be displayed on projects. I just looked into it, and it would be a quick 1 line change to get all contributors indexed. This means that searching for an un{registered|confirmed} user would bring up all projects that they have been added to.

**Comment by lbanner** [comment]
Alright @fabian -- Want to make it happen? I tagged this to you - TY

**Comment by fabian** [comment]
Wrong @fabian, probably meant for @fabianvf ;-)

**Comment by lbanner** [comment]
Right!! Thank you @fabian : - ) ... This one is for you @fabianvf -- OK? TY

**Comment by fabianvf** [comment]
@lbanner  Is this a hotfix or feature?

**Comment by lbanner** [comment]
Feature @fabianvf  -- PR whenever you are ready
