### ISSUE TITLE
Cannot download .zip file 

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1733]
<h4>Steps</h4>
1. Try to download this file: https://osf.io/bimqw/

<h4>Outcome</h4>
1. "Not found" returned
2. Console logs "Failed to load resource: the server responded with a status of 404 (Not Found)"
"https://storage101.iad3.clouddrive.com/v1/MossoCloudFS_926294/osf_storage_p…700b801c93f63b8c435fbf7bdd566b2210c537bc&filename=Raw+Replicaton+Files.zip"

<h4>Expected</h4>
1. File should download.

**Comment by sloria** [comment]
Reopening this. Will close once @jmcarp and @icereval 's migration script is run (planning on doing this tomorrow morning).

**Comment by icereval** [comment]
This is now resolved, the file is available for download.

**Comment by lbanner** [comment]
TY!
