### ISSUE TITLE
[staging] [onboarding] expand button on create a new project doesn't aline up

### ISSUE THREAD

**Issue by chennan47** [CenterForOpenScience/osf.io#1738]
<b><big>Step</big></b>
logging into your dashboard and check on the onboarding part

<b><big>Expected</big></b>
The expand button icon should aline up with the create a project

<b><big>Actual</big></b>
![screen shot 2015-02-09 at 11 23 58 am](https://cloud.githubusercontent.com/assets/4974056/6110219/319de6e2-b04e-11e4-8331-a55019564d9c.png)

**Comment by lbanner** [comment]
Does look just to be on 'Staging' -- Which browser @chennan47 ? -- and can you check other browsers?

**Comment by chennan47** [comment]
@lbanner I am using chrome. Have tested this problem on Chrome 40, Safari 7, firefox 35 on OSX ver 10 and Chrome 40, firefox, IE 11 on windows 8.1. It appears that this problem only happen to Chrome and Safari.

**Comment by lbanner** [comment]
@caneruguz ?

**Comment by caneruguz** [comment]
There are some strange things happening on develop branch, most of which are issues that are not on production and some are things that were fixed earlier. This is something Steve showed me. We looked into it, and could not understand what could possibly cause this.  Before we go on trying to fix this I would like to make sure it's not a regression of recent changes to osf. 
@sloria .

**Comment by lbanner** [comment]
Sounds good @caneruguz TY

**Comment by sloria** [comment]
Yes, will look into this.

**Comment by caneruguz** [comment]
@lbanner this should be fixed after Steve's change to the css load, I'm not seeing it in production. We can close this issue.

**Comment by lbanner** [comment]
Got it -- TY
