### ISSUE TITLE
[production] special characters do not render for .docx files

### ISSUE THREAD

**Issue by mckidwell** [CenterForOpenScience/osf.io#1739]
Steps:

1. View a .docx file that contains a special character (example: https://osf.io/7dybc/)

Expected:
Rendered version of the .docx file should reflect its contents exactly.

Actual:
Special characters (é, ö, etc.) do not render when viewing the document on the OSF.

The first name of the author listed below should read Belén, not Beln. His last name should read Fernández, not Fernndez.

![screen shot 2015-02-09 at 11 46 03 am](https://cloud.githubusercontent.com/assets/7945215/6110779/225d103c-b052-11e4-9234-f81848c3604a.png)

**Comment by JeffSpies** [comment]
To start with, perhaps a message stating that the rendering of docx files
is imperfect would suffice?

**Comment by lbanner** [comment]
That's a sound approach -- Do we have any messaging like that currently? Around other file types?

**Comment by brianjgeiger** [comment]
I think a message might be nice, but I don't think that should be sufficient to close this issue. Special characters shouldn't be dropped; they should either be rendered properly (preferable) or converted to their closest ascii equivalent. There is potential for confusion and, in the case of scientific papers, entirely inaccurate data/results if characters are dropped.

Most of our rendering is an approximation of some sort or another. We don't really have a concept of paper size, we are missing a bunch of fonts, and so on. It could be useful in MFR to have some metadata for each plugin listing the known limitations, so people can see what they will be, but I think that would be a) a larger issue; and b) a completely separate issue.

**Comment by brianjgeiger** [comment]
I filed an issue for pydocx: https://github.com/CenterForOpenScience/pydocx/issues/109

**Comment by brianjgeiger** [comment]
Looks like it's MFR, not pydocx.

**Comment by brianjgeiger** [comment]
@mfraezz, since I suspect you have MFR all checked out and building and everything, could you make that change?

**Comment by lbanner** [comment]
@nanchen47 -- Did this one deploy to Production as well? Thanks.

**Comment by chennan47** [comment]
@lbanner this pr is merged into develop 28 days ago. I believe it should be on production.

**Comment by lbanner** [comment]
@mckidwell Can you do me a favor and just double-check this one on Production with some/one of your projects? TY

**Comment by mckidwell** [comment]
@lbanner .docx files are timing out and failing to render; will let you know when I'm able to check.

**Comment by sloria** [comment]
@mckidwell Looking into a fix for docx rendering now.

**Comment by lbanner** [comment]
.docx rendering fixed by @sloria now -- TY!

**Comment by mckidwell** [comment]
Thanks @sloria! Just checked a project - special characters in .docx files are rendered as expected.

**Comment by lbanner** [comment]
Marvelous -- Thank you @mckidwell -- all is good and closed with this one.
