### ISSUE TITLE
Profile pages with long links in the social media section that produce errors

### ISSUE THREAD

**Issue by lbanner** [CenterForOpenScience/osf.io#1746]
## Steps

Go to a users profile. Click on the user’s social media profile link — even a relatively long link.

## Expected

You should be directed to the user’s social media site

## Actual

The link does not direct to the proper page.

## Example

![socialmedialinkerror](https://cloud.githubusercontent.com/assets/2964829/6120980/55c955e0-b0aa-11e4-830d-e695aad832b7.png)

**Comment by brianjgeiger** [comment]
What's happening here is that the LinkedIn link should just be the Profile ID for the user, not the whole URL. See how twitter and ORCID are just the pieces of info and not the whole URL? LinkedIn should be that way as well. For example, here is my social profile:

![screen shot 2015-02-10 at 9 16 34 am](https://cloud.githubusercontent.com/assets/6599111/6128685/09a08b6e-b106-11e4-8b2c-df1cdef3267a.png)

When you go into the setting page, you can see the guides that we give for people. 

![screen shot 2015-02-10 at 9 16 47 am](https://cloud.githubusercontent.com/assets/6599111/6128703/34df75f6-b106-11e4-8c2a-f267ecf2eb29.png)

It's entirely possible that the LinkedIn ID was set before we had the new UI, and the old system was not nearly as explicit about what information it needed. I was confused for a while about LinkedIn as well. If this were done in the old UI, I'm not super-concerned. If it were done in the new UI, then we may have to keep an eye on it and see if other users have this trouble. It's fixable, but it's a high effort-to-reward ratio to get it perfect. If it's important enough, I would lean towards removing LinkedIn for a while until we have an opportunity to properly fix the interface.

**Comment by lbanner** [comment]
So @brianjgeiger -- Anyway we can script a correction to LinkedIn links that are input incorrectly? -- especially for long-time users who may have just dropped in the full link prior to our new UI that gives better direction.

**Comment by brianjgeiger** [comment]
I don't think so. There are at least 3 different ways you can mess up the LinkedIn ID, and some of them don't really provide you with a view that's visible to someone who isn't the person in question. We could find out who some of the users are, and we could fix some of the cases. but I don't believe we can automatically fix all of the cases.

**Comment by lbanner** [comment]
Going to defer + communicate with community/desk on how to respond to user's with this challenge.

**Comment by nanchen47** [comment]
Will be considered when update the profile pages.
