### ISSUE TITLE
Apparent Divergence of View-Only Link File Downloads

### ISSUE THREAD

**Issue by KatyCain526** [CenterForOpenScience/osf.io#1748]
This is a problem that a user found. 
1) Make a view-only link
2) Try to download files from "Files" tab
3) Try to download files from the individual file's page   

-------
We expect to be able to download files from both the "Files" tab and the individual file's page. 

We found that we could only download files from the "Files" tab, and that trying from the individual file's page leads to: 
![screen shot 2015-02-10 at 9 23 40 am](https://cloud.githubusercontent.com/assets/6306030/6129111/cd44bd76-b109-11e4-9f81-c3833b0ea24a.png)

**Comment by lbanner** [comment]
Michael is on this -- TY @icereval !

**Comment by KatyCain526** [comment]
:+1:

**Comment by sloria** [comment]
@KatyCain526 This should now be fixed. Can you verify?

**Comment by sloria** [comment]
ping @KatyCain526

**Comment by lbanner** [comment]
@KatyCain526 -- H

**Comment by lbanner** [comment]
@KatyCain526 -- Hey, can you double check this is no longer an issue? TY

**Comment by KatyCain526** [comment]
Jah. This is no longer a problem :D
