### ISSUE TITLE
[feature] Password field should have helper for account creation

### ISSUE THREAD

**Issue by HarryRybacki** [CenterForOpenScience/osf.io#1753]
## Purpose
Provide users tooltip with information regarding our password policy during account creation.

## Changes
Provide users with information about password policies during creation as opposed to after attempting submission (current behavior) -- see picture below for an example of a supposed user attempting to create an account with a password that is too short.

![screen shot 2015-02-10 at 3 06 54 pm](https://cloud.githubusercontent.com/assets/2614670/6135472/efdc3fe4-b136-11e4-9a5b-f22cb141f6d9.png)

## Side Effects
None?

**Comment by sloria** [comment]
Addressed by https://github.com/CenterForOpenScience/osf.io/pull/1998
