### ISSUE TITLE
Sort by All the Things

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#1761]
Steps
-------
1. View a presentation service or the "files" tab of a project
2. You can sort by Title and Author (on the presentation service) or by Title (on files tab), but not by Download count (either pres. service or files tab) or category (presentation service).

Expected
------------
You can sort by any of the columns.

Actual
--------

You can't sort by items mentioned above in step 2.

**Comment by caneruguz** [comment]
@lbanner I added a downloads sort a while ago but there is no sorting for Category. I can quickly add that if that is desired.

**Comment by lbanner** [comment]
@caneruguz Yeah -- I think so as this was requested by Community. Estimate on time? Thanks

**Comment by caneruguz** [comment]
I can do this PR today, it would take about 20 minutes altogether.

**Comment by lbanner** [comment]
Make it so :smiling_imp:

**Comment by caneruguz** [comment]
@lbanner PR is here: https://github.com/CenterForOpenScience/osf.io/pull/2147

It took me a while because I had to change my trial poster categories to be able to test it, which required digging through OSF code.

**Comment by lbanner** [comment]
Nice - Thank you.
