### ISSUE TITLE
User Metrics Aren't Counted in the Same Way

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#1768]
There is a script reporting number of users (among other things): https://github.com/CenterForOpenScience/osf.io/blob/f533483945056724d05088eaccb7f5d9f087e080/scripts/analytics/benchmarks.py

There is another script reporting the domains of email addresses registered in the 24 hour period prior to the script running: https://github.com/CenterForOpenScience/osf.io/blob/1471cadbd979f0bcee73d74a8123b60230c16a97/scripts/analytics/tabulate_emails.py

The two scripts do not count the number of users in the same way. The first specifies: 
        Q('is_registered', 'eq', True) &
        Q('password', 'ne', None) &
        Q('is_merged', 'ne', True) &
        Q('date_confirmed', 'ne', None)

It would be good for the scripts to be consistent. I would recommend updating the second script to match the first.

**Comment by lbanner** [comment]
@jmcarp Did you originate these? If so, can you take a look? -- Thanks!
