### ISSUE TITLE
Go/Nogo for release 0.25.0

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1780]
Branch: https://github.com/CenterForOpenScience/osf.io/tree/release/0.25.0
Changelog: https://github.com/CenterForOpenScience/osf.io/blob/release/0.25.0/CHANGELOG

Deployment actions:

- [x] Update production waterbutler servers with latest code
- [x] Add sharejs supervisor config
- [x] Update python requirements
- [x] Pull down codebase
- [x] Build citation records: `inv update_citation_styles`
- [x] Build assets
- [x] Start shareJS
- [x] Restart uwsgi
- [x] Restart celery
- [x] Clear mfr cache

Post-release actions:

- [x] Add supervisor configs to private-configs repo
- [ ] Update dev docs with instructions on starting sharejs

ping @JeffSpies @GaryKriebel @lbanner @icereval @jmcarp @chrisseto @caileyfitz @rliebz

**Comment by sloria** [comment]
There is one last set of fixes to merge. After that, Michael and I will each do one last pass over each of the addons to make sure rendering is working.

Once that is finished. I am a go.

**Comment by GaryKriebel** [comment]
After talking with the boys post beCraft, I am a go pending the run through by Steve and Co. 

http://m.youtube.com/watch?v=zVf-rehP4b8

**Comment by lbanner** [comment]
Thanks @sloria and @GaryKriebel  -- I am a GO -- This has been good work all around. Let's here from The @caileyfitz :smiley_cat:

**Comment by sloria** [comment]
Update: we ran into some bugs when testing rendering. I can't confidently say that this is release-ready  Will try to address the remaining bugs tonight but will likely need some time in the morning with the waterbutler team. Once that is finished, we should do one last pass over file rendering for each addon.

No go for now

**Comment by chrisseto** [comment]
No go

**Comment by lbanner** [comment]
OK @sloria and @chrisseto -- we'll regroup in the AM -- Thanks for the work!

**Comment by icereval** [comment]
No go, certainly not due to anyone's lack of effort. We'll need to revisit and rethink the way we are handling Celery/MFR File Rendering and WaterButler interactions in depth come the morning.

e.g. (once we saw this we knew it was time to take a break)

![image](https://cloud.githubusercontent.com/assets/3111541/6181722/4f088f3e-b305-11e4-8a62-3f02cc62898b.png)

**Comment by JeffSpies** [comment]
What seems to be the problem?

On Thu, Feb 12, 2015 at 10:23 PM, Michael Haselton <notifications@github.com

**Comment by lbanner** [comment]
Blocker at present: WaterButler <---> GitHub and how it deals with branches + revisions (short version of my understanding). @icereval @sloria @chrisseto are continuing to focus their efforts here. In checking in with them, I propose they take the evening + weekend, as they can, to continue the focus and resolve the issue, with a deployment possible Sunday eve -- or Monday. Other route would be to cherry-pick out the Files View code, but that would require a pass of QA yet again, and not guarantee all bugs would be gone. Keeping on current path seems most efficient. @JeffSpies You might want to check in with the team w/idea generation as needed. Any other thoughts welcome - Thanks!

**Comment by lbanner** [comment]
@sloria and @icereval ... GitHub issue has passed QA w/ @Gary and I. Recognize that the IE10 bug might still be with us, but that is low impact to the value of the whole. Do we think we want to go for an evening/early AM release? I'd like to see it happen if there is high-percentage confidence. Thoughts from the "Go-NoGo" team?

**Comment by JeffSpies** [comment]
What is the IE10 bug?

**Comment by GaryKriebel** [comment]
PDFs do not render.

**Comment by JeffSpies** [comment]
We're sure it's limited to IE10? Can we notify users that it's an IE
problem temporarily?

**Comment by GaryKriebel** [comment]
PDFs now rendering in IE10.

**Comment by sloria** [comment]
Merging @icereval 's latest fixes for rendering files with `#` characters in the filename. 

We have tested CRUD on all the addons and have verified it is working.

Once, the travis build is passing, I am a go.

**Comment by lbanner** [comment]
Thanks @sloria  -- @gary and I have been running through some IE file rendering issues w/PDFs (IE 11), but looks like they exist in Production too, and so we think it should not hold release on the whole, but will require checking and potential follow-on fixes. I am a "go" on release 0.25.0.

**Comment by GaryKriebel** [comment]
Here is the GH issue for IE11 PDFs.
https://github.com/CenterForOpenScience/osf.io/issues/1806

Otherwise I'm good.

**Comment by lbanner** [comment]
:rocket:

**Comment by sloria** [comment]
Michael, Chris, and I are looking into the PDF bug on IE11 now.

**Comment by sloria** [comment]
Chris is putting in a fix that will proxy downloads through the OSF for IE11 only (which is the same behavior on production right now). Other browsers will be able to stream downloads through waterbutler. We will run through rendering on IE11 once that is merged.

ping @JeffSpies @GaryKriebel  @jmcarp @caileyfitz @rliebz for go/no-go response.

**Comment by lbanner** [comment]
Sounds good @sloria and thanks @icereval and @chrisseto

**Comment by GaryKriebel** [comment]
With that workaround I am a go.

**Comment by chrisseto** [comment]
@GaryKriebel we think we have a fix for the IE11 bug.

**Comment by GaryKriebel** [comment]
Excellent.

**Comment by JeffSpies** [comment]
If those are fixed and tested, and we don't need to discuss further,
consider me a go.

**Comment by icereval** [comment]
Go

**Comment by rliebz** [comment]
I'm a go

**Comment by gary** [comment]
28 replies later and you still haven't figured it out. You've got the wrong
Gary, guys.

On Sunday, February 15, 2015, Robert Liebowitz <notifications@github.com>
wrote:

> I'm a go
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/issues/1780#issuecomment-74455229>
> .
>


-- 
Sent from Gmail Mobile

**Comment by caileyfitz** [comment]
Go! :hamster:

**Comment by sloria** [comment]
@gary Apologies. You were automatically subscribed to this thread because you were @ mentioned by accident. You can click Unsusbscribe in the sidebar.

**Comment by jmcarp** [comment]
:+1:

**Comment by lbanner** [comment]
Looks like my bad on the wrong Gary! .... Larry, Gary, Harry, 'arry ... hard to keep up with :smiling_imp: .... apologies. :+1: Appreciate all the work on this release.

**Comment by sloria** [comment]
Deployed!
