### ISSUE TITLE
PDFs cause IE11 to stop working in production

### ISSUE THREAD

**Issue by GaryKriebel** [CenterForOpenScience/osf.io#1806]
Steps
-------
1. Using IE11, go to a project with pdf files.
2. Click on a pdf file to view the files page.

Expected
------------
PDF should render.

Actual
--------
PDFs do not render and cause IE11 to stop working.
![screen shot 2015-02-15 at 8 52 26 pm](https://cloud.githubusercontent.com/assets/9437946/6206317/257dd352-b555-11e4-8bc5-4960cb369cd3.png)

**Comment by sloria** [comment]
Fixed by @chrisseto
