### ISSUE TITLE
MathJaX in Wiki does not recongnize certain (common) symbols

### ISSUE THREAD

**Issue by mbudisic** [CenterForOpenScience/osf.io#1814]
MathJaX does not recognize full set of symbols entered using TeX/LaTeX syntax.

For example ```$x^2$``` and ```$\frac{a}{b}$``` work well, while ```$x \to 8$```, ```$x \leq 7$``` and ```$\lim$``` do not. They should be available per http://docs.mathjax.org/en/latest/tex.html however.

Thank you for adding MathJax to Wiki!

**Comment by lbanner** [comment]
Thank you @mbudisic !

**Comment by brianjgeiger** [comment]
As of right now, everything but \lim and its variants seems to be working from your list above.

![screen shot 2015-03-03 at 9 50 30 am](https://cloud.githubusercontent.com/assets/6599111/6464800/c8388e2a-c18a-11e4-8d2b-700b14c7b0a4.png)

**Comment by lbanner** [comment]
Thank you @brianjgeiger -- please give me a Close/NoClose on this if / when you feel we are where we need to be at present.

**Comment by brianjgeiger** [comment]
Mathjax has a live edit mode that you can find on http://www.mathjax.org. I tested out $\lim_{x\to x_0\atop x\in I}$ on there and it renders as it does on ours. However, when I tested $$\lim_{x\to x_0\atop x\in I}$$ on it, it rendered properly on their live demo, so I tried that on ours and it gave us:

![screen shot 2015-03-03 at 10 19 25 am](https://cloud.githubusercontent.com/assets/6599111/6465407/eebd7dfe-c18e-11e4-961c-f9ee4ca5c295.png)

So it appears to be a MathJax issue.

**Comment by lbanner** [comment]
OK!
