### ISSUE TITLE
[staging & production] Non-visible contributors show up in citations

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1815]
# Steps
1. Go to a project
2. Add a new contributor
3. Check citations for the project
4. In Sharing tab, make the contributor non-visible
5. Check the citations again

# Expected
I expect that only the visible contributors will show up in citations

# Actual
ALL contributors are listed in citations

**Comment by sloria** [comment]
Will look into this.

**Comment by sloria** [comment]
Fixed by https://github.com/CenterForOpenScience/osf.io/commit/d0ac123bd768a911b2d21e7f1f0250148f4c584b
