### ISSUE TITLE
[staging & production] No delete button for unpublished figshare files on files details page

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1816]
# Steps
1. Go to a project and authorize figshare
2. Connect to an unpublished figshare fileset
3. Go to files page
4. Hover next to a figshare file in this folder and note the red x 
5. Click on the file to view it in the files page

# Expected
I expect that there will be a Delete button on the files detail page since a user can delete files on the files grid

# Actual
There is no Delete button. I think this is because the Delete button was showing up for published files (which it shouldn't have), so when it got removed there it accidentally got removed in this case too. 

pinging @chrisseto

**Comment by chrisseto** [comment]
@caileyfitz @sloria Can we close this if it's fixed

**Comment by sloria** [comment]
This is awaiting 2nd pass of QA. ping @lbanner @GaryKriebel

**Comment by chrisseto** [comment]
@sloria Thanks for the update

**Comment by lbanner** [comment]
OK - On it @sloria

**Comment by lbanner** [comment]
@sloria @chrisseto Confirmed. "Delete" button for Figshare file-view on both Staging and Production. TY :wolf:

**Comment by GaryKriebel** [comment]
Concur, I see a delete button as well.
