### ISSUE TITLE
[bug] OSF Helper slideInFooter no longer appearing

### ISSUE THREAD

**Issue by HarryRybacki** [CenterForOpenScience/osf.io#1817]
## Steps
1. Navigate to [http://osf.io](http://osf.io) in a private browser (to ensure no cache).

## Expected
1. The helper slideInFooter should appear 

## Actual
1. It doesn't appear.

## Notes:
I've confirmed the two conditions, window.localStorage.getItem('slide') != 0* and *$('#footerSlideIn').length > 0*, required for the slider to appear are met. However, I think the issue might have something to do with the viewmodel not being bound like we would assume it should [here](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/static/js/pages/base-page.js#L62).

This is a blocker for issue #1521 as well as PR #1749

**Comment by HarryRybacki** [comment]
Ping @sloria

**Comment by lbanner** [comment]
Thanks @HarryRybacki

**Comment by sloria** [comment]
Fixed by https://github.com/CenterForOpenScience/osf.io/commit/35b74f0eb51bd1f464f4c3d87fb948bcae7ac9eb
