### ISSUE TITLE
[Staging & Production] Can't delete GH files if viewing previous version

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#1818]
Reported by @caileyfitz on the 0.25 Trello board

# Steps
1. Go to a project and connect to your GH account
2. Click on a file that has multiple versions
3. When viewing the file, click on a previous version (not the most recent)
4. Now, click the delete button
5. In the confirmation modal, press OK

# Expected
I expect that this will delete all versions of the file

# Actual
The file is not deleted and a growlbox message pops up saying that the file cannot be deleted

**Comment by lbanner** [comment]
I think we need some clarity on expected functionality here: Should you be able to delete past versions of a file? If so, should it delete only the version you are deleting? or should it delete all versions prior to that version? or should it delete the entire file, all versions?

**Comment by caileyfitz** [comment]
All other add-ons will delete a file, even if you are viewing a previous version. The Delete button isn't tied to a specific version like the individual download buttons are. Deleting a file should delete all versions.

**Comment by GaryKriebel** [comment]
Closed
