### ISSUE TITLE
[staging & production] Visiting a file page after add-on has been removed

### ISSUE THREAD

**Issue by ginavuu** [CenterForOpenScience/osf.io#1819]
# Steps
1. Clicked on an add-on file. (any external add-on)
2. Copied the url for the file.
3. Went to Settings and removed the add-on for that project.
4. Visited the url, again.

# Expected
Not really sure...

# Actual
Depending on the add-on, you get an "unable to resolve" or a "bad request." 
Tagging @chrisseto

**Comment by chrisseto** [comment]
Bit of an update, the bad request is expected and will occur when you remove the **node** addon settings. The unable to resolve comes from removing **user** addon settings.
