### ISSUE TITLE
Include Metrics on Users Added as Unregistered Contributors

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#1829]
Currently, stats count number of users at a point in time (this script: https://github.com/CenterForOpenScience/osf.io/blob/f533483945056724d05088eaccb7f5d9f087e080/scripts/analytics/benchmarks.py)

It would be helpful to know how many of those users signed up themselves vs. how many of those users were added to projects as unregistered contributors.

**Comment by lbanner** [comment]
@jmcarp  --  Can you help with this?
