### ISSUE TITLE
Ampersand being rendered as html in search results

### ISSUE THREAD

**Issue by lbanner** [CenterForOpenScience/osf.io#1832]
The ampersand is still being rendered as html in search results in some instances but not others (appears to be for component search results, but not project results in this case). See example:

![searchresults](https://cloud.githubusercontent.com/assets/2964829/6235685/2f573f90-b6b2-11e4-91ed-98c973c5afef.jpg)

**Comment by lbanner** [comment]
For reference see close issue #1422

**Comment by brianjgeiger** [comment]
This looks to be fixed now. 

![screen shot 2015-03-06 at 4 04 44 pm](https://cloud.githubusercontent.com/assets/6599111/6536316/95921bd4-c41a-11e4-90c5-626a9e3581ad.png)

**Comment by lbanner** [comment]
Right -- Very good!
