### ISSUE TITLE
magnifying glass icon disappears in nav bar

### ISSUE THREAD

**Issue by mckidwell** [CenterForOpenScience/osf.io#1834]
When I was searching for a study, the magnifying glass icon disappeared from the nav bar although the search bar stayed visible, making it impossible for a user to close the search bar. This persisted after refreshing the page.

However, I opened the OSF in a new tab and the magnifying glass icon appeared as expected in the new window.

On production using chrome.

![screen shot 2015-02-17 at 4 59 10 pm](https://cloud.githubusercontent.com/assets/7945215/6238158/de99563c-b6c6-11e4-94c8-98bf0360c45d.png)

**Comment by lbanner** [comment]
Good catch -- @brianjgeiger I ask: What is intended functionality here for exiting search? Thanks.

**Comment by brianjgeiger** [comment]
I talked with @mckidwell; this is as intended. She's on the search page, so there is always search capability there. If she were bothered by the behavior, it might be worth examining, but she just thought it wasn't intended.

**Comment by JeffSpies** [comment]
Perhaps the search icon could sit in front of the text input? Would that
clarify what's going on?

**Comment by GaryKriebel** [comment]
That's not a bad idea.
