### ISSUE TITLE
Getting-Started left nav bar not scrolling correctly

### ISSUE THREAD

**Issue by HarryRybacki** [CenterForOpenScience/osf.io#1843]
## Steps
1. Go to the [getting started page](https://osf.io/getting-started/)
2. Scroll down the page and watch the respective section header **become bold** on the left nav bar
3. Scroll until the current section is beyond the bottom of the left nav bar

## Actual
1. Left nav bar doesn't scroll with the window

## Expected
1. Left nav bar should scroll with the window

**Comment by nanchen47** [comment]
I verified this has been fixed on production.
