### ISSUE TITLE
Do not display "Join the OSF" on signup page

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#1844]
Steps
-------
1. Go to any page that lets you create an OSF account

Expected
------------
You can create an account without being pestered

Actual
--------
A big box rises from the bottom of the screen saying "Hey, you want to join the OSF? Joining the OSF is very cool. You should totally join." Any page that doesn't give you the ability to join is fine, but on those pages, it's excessive.

**Comment by JeffSpies** [comment]
+1 @hrybacki could also tackle this one if he's waiting for CR

**Comment by sloria** [comment]
This was already implemented. I've verified on production. @brianjgeiger Are you seeing this on production or staging?

**Comment by sloria** [comment]
@brianjgeiger , Also what is the URL when you see the sliding footer?

**Comment by brianjgeiger** [comment]
Local development.

**Comment by sloria** [comment]
@brianjgeiger What URL?

**Comment by sloria** [comment]
That explains it. This is a quick fix. @HarryRybacki were you already working on this, or should I go ahead and make the change?

**Comment by HarryRybacki** [comment]
I'm not sure I follow -- will get with @brianjgeiger in person

**Comment by HarryRybacki** [comment]
This definitely shouldn't show up on /forgotpassword/ -- will submit add it to NO_FOOTER_PATHS and submit a PR. As for the landing page -- @saradbowman can you weigh in?

**Comment by saradbowman** [comment]
My opinion is it's probably not necessary on osf.io

**Comment by HarryRybacki** [comment]
@sloria -- this was resolved in pr #1852 -- can you close this for me?

**Comment by lbanner** [comment]
Thanks @HarryRybacki -- Got it.
