### ISSUE TITLE
SHARE text abuts logo 

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1855]
<h4>Steps</h4>
1. Open SHARE search (https://osf.io/share/)  in a large window (mine is 2545 x 5169 px)
<h4>Outcome</h4>
1. The text directly below the logo, "What is SHARE? Notice....." overlaps with the SHARE logo.
![screen shot 2015-02-20 at 9 25 49 am](https://cloud.githubusercontent.com/assets/4965832/6287884/f40ce5c4-b8e2-11e4-99e7-57a61d034f89.png)

2. The spacing is correct in a smaller window. 
<h4>Expected Outcome</h4>
1. The text and logo should have spacing between the two so that they do not touch.

**Comment by lbanner** [comment]
Browser? @jlcohoon

**Comment by jlcohoon** [comment]
Chrome, Firefox, and Safari
Unsure about IE but it seems a safe bet.

**Comment by JeffSpies** [comment]
Got it. Thanks!

**Comment by erinspace** [comment]
This is fixed now! Can be closed whenever!

**Comment by lbanner** [comment]
Thanks @erinspace !
