### ISSUE TITLE
Upload times are not accurate for older files

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#1885]
<h4>Steps</h4>
1. I visited a file (https://osf.io/ezrsc/) on the RPP page and looked at its details, noting the download counts and times of upload. 
2. I visited another file (https://osf.io/5wup8/) with multiple versions and also looked at the download counts and times of upload

<h4>Outcome</h4>

![screen shot 2015-02-25 at 2 55 08 pm](https://cloud.githubusercontent.com/assets/4965832/6379644/d449ee12-bd01-11e4-8247-6143bb37af51.png)

![screen shot 2015-02-25 at 2 52 24 pm](https://cloud.githubusercontent.com/assets/4965832/6379648/df25685c-bd01-11e4-8a3e-df4891790c3d.png)

1. Multiple versions of the file are reported to have been uploaded at the same time. The two files' times were not identical to one another but the repetitive upload times are both within 24 hours of one another (Nov 18/19, 2014)
2. Those versions have very high and very disparate download counts, indicating that the upload times of at least some of them are inaccurate. 
3. The download counts for these files are plausible, but I can't guarantee that they are accurate

<h4>Expected Outcome</h4>
1. File uploads will almost always have different upload times.
2. If files have the same file upload times, the first one will have a very small download count.

**Comment by lbanner** [comment]
@jmcarp Pinging you on this one too. We found a couple with this apparent issue, so not consistent -- But would be good if we could search for such inconsistencies and correct -- Let me know thoughts.

**Comment by jmcarp** [comment]
Should be resolved in #2034 after review and merge.

**Comment by sloria** [comment]
Ran @jmcarp's migrations script; these should now be resolved. @jlcohoon Can you verify?

**Comment by jlcohoon** [comment]
looks good to me
