### ISSUE TITLE
[bug] FigShare Oauth cancellation redirects incorrectly

### ISSUE THREAD

**Issue by HarryRybacki** [CenterForOpenScience/osf.io#1888]
## Steps
1. Login to production
2. Go to user settings
3. Go to configure add-ons
4. Select FigShare
5. Click Submit
6. (optional) Log into FigShare
7. Click **Deny**

## Expected
1. User is returned to the configure addons page for their settings */settings/addons/*
![screen shot 2015-02-25 at 3 59 29 pm](https://cloud.githubusercontent.com/assets/2614670/6380468/e13c7b2a-bd07-11e4-95b7-bd19f3f143e4.png)

## Actual 
1. User is returned to the main settings page */settings/*

![screen shot 2015-02-25 at 3 59 22 pm](https://cloud.githubusercontent.com/assets/2614670/6380463/dbdfa6ca-bd07-11e4-975c-ee5b9e0d4e85.png)

## Notes
This is also broken when configured from a project's settings page. This is an even bigger break as it forwards you to the user settings rather than the project settings from which the request was initiated.

**Comment by sloria** [comment]
Fixed by https://github.com/CenterForOpenScience/osf.io/pull/1910
