### ISSUE TITLE
IE9: Cannot add Contributor

### ISSUE THREAD

**Issue by Ghalko** [CenterForOpenScience/osf.io#1907]
Production and Staging

## Steps
1. Go to project with admin access
2. Choose a project
3. Go to sharing
4. Click add contributor
5. Search for and/(or just) add contributor to "Adding" list
6. Click submit

## Expected
New contributor is added to list of contributors.

## Actual
New contributor is not added, not even just a rendering issue, refreshes and checking other browsers confirms that contributor was not added.

**Comment by sloria** [comment]
@Ghalko Is this happening on any other browser?

**Comment by Ghalko** [comment]
I haven't tried newer versions of IE, but firefox, safari, and chrome are all fine.

**Comment by huangginny** [comment]
mental note to self: happens because selection users do not add users to the selection pool when picking contributors
Might be a knockout issue

**Comment by Ghalko** [comment]
Works for me!

**Comment by wisherp** [comment]
Tested in IE11 and Chrome. Works fine!
