### ISSUE TITLE
Go/nogo: release 0.27.0

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1938]
ping @JeffSpies @GaryKriebel @lbanner @icereval @chrisseto @caileyfitz @lyndsysimon @brianjgeiger

**Comment by lbanner** [comment]
Update from this AM (Friday): Two bugs still remain, being worked by Chris. With those resolved, we can run some regressions, add-ons + authentication most important, with a goal of deploying this chunk to Production by mid-day. @sloria will ping on status for QA and go/nogo. TY

**Comment by sloria** [comment]
Once QA has finished 2nd passes and their final checks for authorizing/deauthorizing all addons, I am a go.

**Comment by caileyfitz** [comment]
QA is done with one pass of authorizing/deauthorizing addons. Go! :whale:

**Comment by chrisseto** [comment]
Go go gadget 0.27 :rocket:

**Comment by GaryKriebel** [comment]
![Go Flight](https://www.youtube.com/watch?v=zVf-rehP4b8)

**Comment by brianjgeiger** [comment]
Wiki seems good, so I'm a go.

**Comment by caileyfitz** [comment]
WAIT I'M A NO!

**Comment by brianjgeiger** [comment]
Why do you hate progress, @caileyfitz

**Comment by caileyfitz** [comment]
Just doing my job @brianjgeiger

**Comment by sloria** [comment]
@caileyfitz Fixing that now.

**Comment by lbanner** [comment]
GO if QA says so!

On Friday, February 27, 2015, Cailey Fitzgerald <notifications@github.com>
wrote:

> Just doing my job @brianjgeiger <https://github.com/brianjgeiger>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/issues/1938#issuecomment-76455121>
> .
>


-- 
Larry Banner
Technical Project Manager
Center for Open Science <http://centerforopenscience.org/>
210 Ridge McIntire Road, Suite 500
Charlottesville, VA 22903-5803
804.432.9522

-----
"We are such little men when the stars come out" - Hermann Hagedorn, 1882
-----

**Comment by caileyfitz** [comment]
After most recent fix, I am once again a Go

**Comment by icereval** [comment]
Go @jmcarp

**Comment by samchrisinger** [comment]
:100:

**Comment by JeffSpies** [comment]
If we're a go, let's go.

**Comment by sloria** [comment]
Deployed.

**Comment by GaryKriebel** [comment]
Nice work all.  5 of 6 Features down.... 1 to go.
