### ISSUE TITLE
Clicking on any Contributor name in sharing tab asks for Save/Discard

### ISSUE THREAD

**Issue by kushG** [CenterForOpenScience/osf.io#1957]
<h3>Steps</h3>

1. Go to Sharing tab of any project.
2. Click on any contributor name.

<h3> Expected </h3>
 Should be redirected to Profile page.

<h3> Actual </h3>
Confirmation modal is displayed along with Save & Discard changes option on the page.
![screen shot 2015-02-27 at 1 22 24 pm](https://cloud.githubusercontent.com/assets/8779995/6418532/c3e020d6-be83-11e4-8636-92891ac69532.png)

**Comment by lbanner** [comment]
@kushG This is on Production?

**Comment by kushG** [comment]
Yes it is !

**Comment by lbanner** [comment]
OK

**Comment by kushG** [comment]
@steve, is the fix merged? I can still replicate this in production

**Comment by sloria** [comment]
@kushG The fix is currently on staging only.

**Comment by kushG** [comment]
Got you.....I thought hotfix goes directly into production !

**Comment by sloria** [comment]
@kushG It usually does, yes, but since this one is easy to test, I wanted it to be verified on staging first. 

Anyway, this is on production now. =)
