### ISSUE TITLE
[Bug][Presentation Service] SPSP 2014 presentation page vs spsp 2014 presentation page

### ISSUE THREAD

**Issue by KatyCain526** [CenterForOpenScience/osf.io#1958]
The SPSP 2014 presentation page has two pages, one doesn't have any posters. 

https://osf.io/view/SPSP2014/ takes you to a blank presentation page. 
https://osf.io/view/spsp2014/   takes you to the real presentation page. 

I would expect both to take you to the same presentation page. 

Katy 

@jmcarp

**Comment by lbanner** [comment]
Thanks @jmcarp -- This would be good to resolve asap, I think.
