### ISSUE TITLE
Go/nogo on 0.28.0

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#1977]
@JeffSpies @GaryKriebel @lbanner @icereval @jmcarp  @samanehsan @brianjgeiger @HarryRybacki @chrisseto @caileyfitz

**Comment by sloria** [comment]
Once QA's pass is finished, I am a go.

**Comment by JeffSpies** [comment]
Same.

**Comment by icereval** [comment]
go go gadget copter!

**Comment by chrisseto** [comment]
GOOOO :8ball:

**Comment by HarryRybacki** [comment]
+1

**Comment by GaryKriebel** [comment]
I cleared out the last two bug cards from 2nd pass...... I am [Go Flight](https://www.youtube.com/watch?v=zVf-rehP4b8)

**Comment by caileyfitz** [comment]
Go!

**Comment by brianjgeiger** [comment]
Unless there's something not covered by the Trello board, I'm a go.

**Comment by samanehsan** [comment]
I'd like my question on email styling cleared up first...then I'm a go.

**Comment by lbanner** [comment]
OK -- GO by me -- Long as @samanehsan is good -- Thanks!

**Comment by samanehsan** [comment]
Email templates fixed and tested! I'm a GO!

**Comment by lbanner** [comment]
Go Go! .... Time for the Wiki Dance @brianjgeiger !! 
https://www.youtube.com/watch?v=krVXRCcr2M4
