### ISSUE TITLE
Uploading files through the 'Drop file' option is unresponsive 

### ISSUE THREAD

**Issue by trevinovnc** [CenterForOpenScience/osf.io#1993]
Steps

1. Go to 'My Dashboard'.
2. Drop file or click the upload button under the 'Upload file(s)' tab.
3. Select project and upload.

Expected

Should upload intended file within a reasonable time under the appropriate folder

Actual

Loading bar under the file name shows 0% uploaded and is frozen at that percentage. 

![screen shot 2015-02-28 at 4 28 08 pm](https://cloud.githubusercontent.com/assets/11246619/6428433/1608c8de-bf67-11e4-9062-cd0936ca786d.png)

**Comment by brianjgeiger** [comment]
Hi, @trevinovnc. Which browser were you using?

**Comment by trevinovnc** [comment]
I tried uploading on both chrome and safari.

**Comment by brianjgeiger** [comment]
Hmmm. Should work on Chrome, but Safari is a known bug. We'll take a look, thanks.

**Comment by brianjgeiger** [comment]
Ah, no, I see the problem. You haven't actually selected a project. That's a search box, and you have to choose from a list of projects that show up in that list. If you don't have a project called Lab 1 yet, go ahead and make one, then you can drag files into it. In Chrome, at least. I think it's still not working in Safari.

**Comment by trevinovnc** [comment]
Ah okay, thanks for the tip! I'll keep that in mind for next time.
