### ISSUE TITLE
"Popular public registrations" section of Activity page is empty

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/osf.io#2002]
### Summary
On the "Public Activity" page of the OSF, there are four parts to the page. One of those sections- "Popular Public Registrations"- has no entries as of 9pm EST March 1, 2015.

**Severity**: Probably minor

Link to affected page: https://osf.io/explore/activity/#popularPublicRegistrations

![screen shot 2015-03-01 at 9 32 08 pm](https://cloud.githubusercontent.com/assets/2957073/6434621/88996b8a-c05a-11e4-9d40-58d70033dcf6.png)

### Links to files/ views
This is the template that renders the page:
https://github.com/CenterForOpenScience/osf.io/blob/develop/website/templates/public/pages/active_nodes.mako#L40

The desired template variable is indeed being passed in from the corresponding view:.
https://github.com/CenterForOpenScience/osf.io/blob/develop/website/discovery/views.py#L77

### Additional notes
I don't currently have a dev environment set up to run the OSF (or full knowledge of the internal data structures), so I can only speculate. It appears that popularity is gauged by a call to the Piwik API:

```
        popular_project_ids = [
            x for x in client.custom_variables if x.label == 'Project ID'
```

There do appear to have been several new registrations in the relevant timeframe ( https://osf.io/explore/activity/#newPublicRegistrations ), so it doesn't seem likely that the empty list is due to a lack of matching nodes.

The list of popular projects AND registrations is generated by filtering the single above query based on node type- perhaps there's something in the logic for identifying what is a registration?
https://github.com/CenterForOpenScience/osf.io/blob/develop/website/discovery/views.py#L22

**Comment by lbanner** [comment]
Thank you @abought

**Comment by lyndsysimon** [comment]
Since I've been working with Piwik for the past couple of days, I should be able to knock this one out quickly. I'm on it! :fast_forward:
