### ISSUE TITLE
[experimental] Account merging

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#201]
Experimental support for merging duplicate has been added to the development version of the OSF. 

Certain details about this feature require discussion.

Here is the plan for how it will work:

For a user with name "John Doe" and a duplicate user with name "Joseph Doe", to be merged:

- John Doe merges Joseph Doe's account by going to the settings page, clicking "Merge Duplicate Account", and providing the email of the duplicate account, password of the duplicate account, and password of master account
- Once merged, Joseph's Doe's profile page has an alert at the top saying :

"This account has been merged with https://osf.io/johndoesid"

- Joseph Doe **can no longer log in with the merged account**
- John Doe is now owner of any project created with the Joseph Doe account
- John Doe is now a contributor to any project that Joseph Doe was a contributor to
- **Past log events will be unchanged** , i.e. they will still show "Joseph Doe" (but future log events will show "John Doe")

Bolded items were discussed recently. Further discussion pending.

**Comment by caneruguz** [comment]
@GaryKriebel is it time to revisit this issue?

**Comment by chennan47** [comment]
I think this is covered by @lyndsysimon account merging. Can you confirm that, @lyndsysimon ?

**Comment by lbanner** [comment]
Yeah -- this is covered by recent merge functionalities -- I think we are good and am going to close. TY
