### ISSUE TITLE
Inconsistency between file versions and download counts

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/osf.io#2015]
Follow-up to #1883.

For a small number of old files, there are download counts in the `pagecounters` collection that don't correspond to existing file versions. For example, files that only have a single version may have download counts for version 1 (which exists) and version 2 (which doesn't). This is the source of the bug reported by @jlcohoon in #1883 such that download counts can be inconsistent between the files page and the file detail page.

I'm running a script now to check how many files are affected. Once that's finished, I'll update this issue with a proposed fix.

**Comment by lbanner** [comment]
This has been sitting for a while ... @sloria , have we overcome all these inconsistencies? I'd like to close.

**Comment by sloria** [comment]
@jlcohoon Can you confirm that the download counts for the files in question are now correct?

**Comment by jlcohoon** [comment]
Actually, they still aren't consistent. For "mlewis_sfn13.pdf" the detail page lists 16 downloads and the file tree says 37: https://osf.io/jret9/
