### ISSUE TITLE
[Staging & Production] Zotero and Mendeley enabled even after removing add-on from user settings

### ISSUE THREAD

**Issue by reh4fd** [CenterForOpenScience/osf.io#2016]
# Steps
1. Enable both Mendeley and Zotero for a project
2. Configure Mendeley and Zotero for the project (link to a folder)
3. Go to user settings page
4. Uncheck the boxes next to Mendeley and Zotero to remove them
5. Press Submit and then OK to successfully remove the add-ons
6. Scroll down to see that Mendeley and Zotero are no longer listed in the configuration table
7. Go back to the project where Mendeley and Zotero were configured 

# Expected
I expect that removing the add-ons from user settings would remove the access tokens and thus yield a configuration error for any projects where Mendeley and Zotero were configured.

# Actual
The project still has Mendeley and Zotero working as normal. Removing the add-ons in user settings did not remove the access tokens for projects.

![screen_shot_2015-02-26_at_7 36 34_pm](https://cloud.githubusercontent.com/assets/5785124/6469888/0f6f0fbc-c1ae-11e4-9e69-1b6b09f495b8.png)

**Comment by GaryKriebel** [comment]
@reh4fd this is on Production, yes?

**Comment by reh4fd** [comment]
@GaryKriebel im not sure.  im moving all the deferred cards from trello to github.  i think it might be staging actually

**Comment by reh4fd** [comment]
@GaryKriebel i accidentally moved this over when i shouldnt have.  im sorry for the confusion.
