### ISSUE TITLE
[Staging & Production] Scrolling bar overlaps header

### ISSUE THREAD

**Issue by reh4fd** [CenterForOpenScience/osf.io#2017]
Reported by @caileyfitz on the 0.27 Trello board

# Steps
1. Link Mendeley to a project
2. Choose a folder in Mendeley that has a sufficient number of documents that you would need to scroll in the widget to see all of the citations
3. Go to the project overview page and scroll through citations

# Expected
The scroll bar would not overlap page header

# Actual
Scrollbar overlaps page header. See scroll bar in image overlapping "Help" tab 
![screen_shot_2015-02-20_at_3 31 30_pm](https://cloud.githubusercontent.com/assets/5785124/6470189/cf3fe66c-c1af-11e4-8038-2de1ca2b49a4.png)

**Comment by reh4fd** [comment]
@caileyfitz

**Comment by caileyfitz** [comment]
Reported in the 0.29 Trello board

**Comment by caileyfitz** [comment]
From @caneruguz on the Trello card: 
> This seems to be a problem in Chrome, and this css addition fixes it: 
-webkit-transform: translate3d(0, 0, 0)

**Comment by lbanner** [comment]
@caneruguz -- Did we ever include your fix above?

**Comment by caneruguz** [comment]
I found that this problem occurs in other parts of the website as well and is most likely related somewhat to browser, OS. The fix does work but I would rather do a site wide fix and test. I'll send a PR for it.

**Comment by lbanner** [comment]
TY

**Comment by caneruguz** [comment]
So after about an hour of trial and error I realized the solution I suggested may cause other problems down the line and is not idea. The other alternative is to draw a scrollbar ourselves for webkit, chrome/safari. We have then the option to make it look like anything we like. Any ideas about how to go about with this? Options are
- Ignore issue
- Make scrollbar look like OSX Yosemite (we need to pick an OS version)
- Make scrollbar look custom (for instance in the image below)

This change will apply to only specific elements like Treebeard grids. 
![screen shot 2015-03-04 at 4 11 19 pm](https://cloud.githubusercontent.com/assets/1314003/6493511/26860a94-c289-11e4-8109-f025d0df345a.png)

**Comment by caneruguz** [comment]
Also @brianjgeiger and @sloria, any thoughts on this?

**Comment by brianjgeiger** [comment]
Probably the scrollbar like the one in your image would be ideal of the custom options.

**Comment by sloria** [comment]
Fixed
