### ISSUE TITLE
[Staging & Production] Zotero lists file attachments as separate citations

### ISSUE THREAD

**Issue by reinaH** [CenterForOpenScience/osf.io#2018]
Reported by @GaryKriebel  on the 0.27 Trello board
# Steps
1. Go to the Zotero site
2. Create a new folder 
3. In that folder, add a citation (fill in title, author, etc)
4. After pressing Save, press Upload Attachment
5. Add an attachment to the citation
6. Go to a project on the OSF that is linked to your Zotero account
7. In the folder picker, choose your newly added folder to link to the project
8. After linking the folder, go to the Zotero widget on the project overview page
# Expected

I expect there to be one citation listed in the widget, since we only added one via the Zotero site
# Actual

There appear to be two citations listed. One is the citation that was manually added and the other is the attachment for that citation. On the Zotero site, there is only one citation listed for the folder, which is correct since the attachment is part of the citation, not a new citation in itself.
![screen_shot_2015-02-25_at_4 51 29_pm](https://cloud.githubusercontent.com/assets/5785124/6470240/2b0a2c28-c1b0-11e4-8b22-3bfecedabe55.png)

**Comment by reh4fd** [comment]
@GaryKriebel

**Comment by caileyfitz** [comment]
Reported in the 0.27 Trello board

**Comment by reh4fd** [comment]
from @GaryKriebel on the Trello Card: 

talking with jeff, he suggested trying to key off the URLs returned for each. In the example below, the zotero.org url is my cited reference and the files.zotero.net is the attachment. !image

**Comment by reh4fd** [comment]
from @samchrisinger on the Tello card: 

Zotero appears to be using some sort of guid system rather than path/hierarchical urls. This approach will not work.

**Comment by saradbowman** [comment]
I believe this is a similar issue, reported on the help desk:

Zotero is used to scrape metadata in website and manage the full text. Most entries in user's library have one snapshot of the original website and one path to the full text. The entries in Zotero have the column "notes and attachments" for the storage of snapshot and path. In the OSF, the add-on shows three entries for each reference: reference, snapshot, and path of file.

**Comment by samchrisinger** [comment]
Answering this with complete certainty will require spending more time with the Zotero API, but my current impression is that there is no reliable way to differentiate attachments and citations.
