### ISSUE TITLE
[Staging & Production] MathJax Wiki View not right in Safari

### ISSUE THREAD

**Issue by reh4fd** [CenterForOpenScience/osf.io#2019]
Reported by @lbanner on the 0.27 Trello board

# Steps
Use Browser = Safari
Create a new Wiki
Use Math-Inline to add math text
Like this $more math 3+5=8$

# Expected
Edit + Previews should look the same

# Actual
The text is duplicating in Preview
See attached --
![screen_shot_2015-02-26_at_10 58 45_am](https://cloud.githubusercontent.com/assets/5785124/6470273/8107bc44-c1b0-11e4-8c59-902d4892a37c.png)

**Comment by reh4fd** [comment]
@lbanner

**Comment by caileyfitz** [comment]
Reported in the 0.27 Trello board

**Comment by brianjgeiger** [comment]
This is not correct. Edit and Preview should not look the same.

**Comment by brianjgeiger** [comment]
Ah, and the issue for duplication is an occasional one that is being addressed by https://github.com/CenterForOpenScience/osf.io/pull/2008

**Comment by brianjgeiger** [comment]
This is fixed, @lbanner

**Comment by lbanner** [comment]
Thank you!
