### ISSUE TITLE
[Staging & Production] .aspx error

### ISSUE THREAD

**Issue by reinaH** [CenterForOpenScience/osf.io#2020]
Reported by @ginavuu on the 0.27 Trello board

# Steps
1. connect a folder from Google drive to a project
2. make sure the folder has a .aspx file
3. open and view it

# Expect
The file appears without errors.

# Actual
The file renders, but there are errors throughout the doc.

![error2](https://cloud.githubusercontent.com/assets/5785124/6470298/d66cb78e-c1b0-11e4-861e-7e36ada8d769.PNG)
![error](https://cloud.githubusercontent.com/assets/5785124/6470301/d7ed67d4-c1b0-11e4-8b94-c3843f9552d0.PNG)

**Comment by caileyfitz** [comment]
Reported in the 0.27 Trello board

**Comment by reh4fd** [comment]
from @ginavuu on the Trello card:

I believe, I was told that aspx files are not technically suppose to work, but I am not quite sure if there is more to that.

**Comment by brianjgeiger** [comment]
ASPX files are not supported. We are currently rendering text-like files as text, and other things we show as being not-renderable. We should not try to render these files, we should say that there is not a renderer. We should be selective about what things we try to render as text.

**Comment by caileyfitz** [comment]
+1 to @brianjgeiger

**Comment by lbanner** [comment]
We should look into error handling here, so that at minimum we catch it and deliver some user notification.

**Comment by nanchen47** [comment]
Will be considered in later MFR development. Thanks.
