### ISSUE TITLE
[Staging & Production] "Copy citations" icon whites out upon hover in IE10

### ISSUE THREAD

**Issue by reinaH** [CenterForOpenScience/osf.io#2021]
Reported by @caileyfitz on the 0.27 Trello board

# Steps
1. Access staging on IE10
2. Go to a project where Mendeley is configured
3. On the overview page, find the Mendeley widget
4. Hover over the "Copy citations" icon to view tooltip

# Expected
Tooltip would display and icon would not change

# Actual
Icon whites out upon hover. In the image below, no tooltip is displayed, but that is only because my pointer wasn't over the icon anymore when I took the screenshot. Main thing to look for is the whited-out icon. This particular citation did not have a link to an original document, so only the left icon is whited-out (the other icon was never there in the first place): 
![icon](https://trello-attachments.s3.amazonaws.com/54ef508e15f5e445e5aaf056/451x95/69dad9475df577911a6d494c232a3ee9/Screen_Shot_2015-02-26_at_11.53.20_AM.png)
![screen_shot_2015-02-26_at_11 53 20_am](https://cloud.githubusercontent.com/assets/5785124/6470436/9ef82fd0-c1b1-11e4-9344-9e8592147307.png)

**Comment by reh4fd** [comment]
@caileyfitz

**Comment by caileyfitz** [comment]
Reported in the 0.27 Trello board

**Comment by lbanner** [comment]
@samchrisinger or @lyndsysimon ?

**Comment by samchrisinger** [comment]
I believe both @icereval  and @jmcarp could not duplicate this.

**Comment by lbanner** [comment]
OK - Thanks

**Comment by nanchen47** [comment]
@caileyfitz can you verify if this problem still exist?

**Comment by caileyfitz** [comment]
@nanchen47 Yes, this is still a problem.
