### ISSUE TITLE
[Staging & Production] Error when pressing syntax links before they render

### ISSUE THREAD

**Issue by reh4fd** [CenterForOpenScience/osf.io#2022]
Reported by @caileyfitz on the 0.27 Trello board

# Steps
1. Go to a wiki page
2. Insert new syntax links (@youtube, @service, @vimeo, etc)
3. Press save
4. In the wiki view, press these links before they render (are embedded in page. Note that @service remains a clickable link even after the others don't)

# Expected
I'm not really sure what I expect here. I don't expect an error. Maybe if the link goes nowhere, it should just point to the current wiki page?

# Actual
Clicking these links redirects to a Page not found error. @thefoodgeek said this isn't really an issue because people shouldn't be clicking these links, but it can definitely happen. This is also an issue with people who may have inserted these links before the new wiki and registered the project, such as https://staging.osf.io/2kr94/.

**Comment by reh4fd** [comment]
@caileyfitz

**Comment by caileyfitz** [comment]
@brianjgeiger says: 
> We can potentially make modifications to the plugin, or make an alternate plugin, so that during debouncing we have a view that’s not Linky. Or we could turn off all links during debounce. The first we couldn’t do today, the second may be a tiny change that we could do today. It’s something we could easily fix next week so as not to slow down the release unless people feel it’s super-critical.

**Comment by lbanner** [comment]
@brianjgeiger -- We tackling this?

**Comment by brianjgeiger** [comment]
Sure

**Comment by brianjgeiger** [comment]
@lbanner PR created, now ready for review

**Comment by lbanner** [comment]
@brianjgeiger -- Thank you!
