### ISSUE TITLE
[Staging & Production] Mendeley adding multiple folders without using "All Documents"

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#2023]
Reported by @ginavuu on the 0.27 trello board

Option for multiple folders without selecting "All Documents"

# Steps
1. Connect an Mendeley account in a project.
2. Select a folder to connect to.

# Expected
Allow a user to select multiple folders without having to select "All Documents."

# Actual
Only one folder or "All Documents" is allowed to be selected.

**Comment by GaryKriebel** [comment]
Closed
