### ISSUE TITLE
[Staging & Production] Wiki category inconsistent

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#2024]
Reported by @chennan47 on the 0.27 Trello board

# Steps
1. Create a project 
2. Create a component which don't set its category (called Uncategorized)
3. Go to the project wiki page
4. Go to the wiki page of the component which doesn't have its category set

# Expected
I expect that the wiki page views would be similar for projects and components.

# Actual
The first image (screenshot at 4.09) is the project wiki view and the second image (screenshot 4.11) is the component wiki view. The "Uncategorized Wiki Pages" doesn't make much sense to users.

![screen_shot_2015-02-27_at_4 11 29_pm](https://cloud.githubusercontent.com/assets/10926926/6471561/f662bf94-c1b9-11e4-91d9-8626cebc0e6a.png)

![image](https://cloud.githubusercontent.com/assets/10926926/6471575/17345048-c1ba-11e4-9624-018c56ce76cb.png)

**Comment by brianjgeiger** [comment]
I think "Wiki Pages" for the current level and "Component Wiki Pages" for anything below this level would be fine for now. Long term, something other than "Component" would be ideal, so if we can think of it now, that would be a good idea. Essentially "Child Wiki Pages" would make sense from a development standpoint, but is terrible for users.

**Comment by lbanner** [comment]
Is this the product of the Component "categories" @brianjgeiger ? -- and might this be overcome with upcoming, "make all things projects" task, in next Epic?

**Comment by brianjgeiger** [comment]
Partially. I agree, whether or not we did change the structure, that this display is confusing. But my immediate-term / long-term suggestion dichotomy is because of making everything a project, so the terminology may change. It would be good to get ahead of that.
