### ISSUE TITLE
[Staging & Production] Toggle buttons are too small

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#2026]
Reported by @caileyfitz on the 0.27 Trello board

The toggle buttons are pretty small compared to other text on the wiki page. I missed them the first time, and I even knew what I was looking for. It might make sense to make them a bit bigger and more pronounced since they are smaller font size than the titles in the wiki columns. 
![wiki](https://trello-attachments.s3.amazonaws.com/54ef3dab47a4693bf3490967/600x239/2a64ae4e8052fe690f0c379cabcc65d6/Screen_Shot_2015-02-26_at_10.33.34_AM.png)

From @brianjgeiger : They are bigger than the pull-down menu controls. They may be a tiny bit smaller than the revert save buttons, but I suspect that’s just because they’re a button bar. They are about 5 px shorter than the button bar on the project overview page. Eh. It doesn’t bother me, but @caneruguz what are your thoughts?

From @caneruguz : I tried them with bigger icons, they look too big, and really out of place. I don't think this issue is significant enough to venture into making our own button styles for this. I agree that the design can improve, there is some cohesiveness in the panels but we are lacking a standard title/toolbar combination. I would leave this for later.

**Comment by sloria** [comment]
Maybe deserves to be another issue, but the "Current version to Version 4" is also misaligned.

**Comment by caileyfitz** [comment]
@sloria Yeah that's what I thought too, but the "version 4" did move to be next to "Current version to" after increasing the page width

**Comment by sloria** [comment]
Still, that panel should respond correctly to smaller screen sizes.

**Comment by caileyfitz** [comment]
@sloria ah, yes :whale:

**Comment by brianjgeiger** [comment]
Agreed that it should be a separate issue. @caneruguz has been working on dealing with columns at awkward size combinations.

**Comment by caneruguz** [comment]
Those involved, can we resolve this issue by either discarding it or suggesting a method? 

This is what it would like with medium buttons (the same size as in Project dashboard(summary) page. 

**Medium size** 
![screen shot 2015-03-10 at 5 01 15 pm](https://cloud.githubusercontent.com/assets/1314003/6585290/396686ee-c747-11e4-9e41-c35407570c05.png)

**Original Size**
![screen shot 2015-03-10 at 5 01 37 pm](https://cloud.githubusercontent.com/assets/1314003/6585289/37c31898-c747-11e4-8bda-2433cfe30c87.png)




My vote is to not change these button sizes, I personally don't think they are too small but then again I drive a tiny coupe so...

**Comment by caileyfitz** [comment]
I think they look much better being bigger. With the original size, the toggle "VIew" is not even as big as the "View" in the column header.

**Comment by caneruguz** [comment]
Well okay, somebody needs to decide this, once we do I can be assigned to complete it.

**Comment by nanchen47** [comment]
This is related to issue https://github.com/CenterForOpenScience/osf.io/issues/2362

**Comment by lbanner** [comment]
Not quite the same/related on this one I think. However, I am going to go with @caneruguz in this case - presently - barring any reported user confusion as yet, let's not put the work into changing the buttons. Closing for now - Thanks.
