### ISSUE TITLE
[hotfix] ga should be mocked of not set in settings.py

### ISSUE THREAD

**Issue by HarryRybacki** [CenterForOpenScience/osf.io#2027]
ga object should be mocked to handle click events for environments where no google_analytics_id is set e.g., in staging and most development environments.

**Comment by lbanner** [comment]
@HarryRybacki and @nanchen47 -- Is this deployed to Production as yet? Thanks.

**Comment by chennan47** [comment]
@lbanner This pr is merged to develop on March the 4th. As a result, I think this should be on production.

**Comment by HarryRybacki** [comment]
Yep, this has been in production for a bit now.

On Mon, Apr 6, 2015 at 9:11 AM, Nan Chen <notifications@github.com> wrote:

> @lbanner <https://github.com/lbanner> This pr is merged to develop on
> March the 4th. As a result, I think this should be on production.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/issues/2027#issuecomment-90057817>
> .
>



-- 
*Harry Rybacki* - Developer, Center for Open Science
Research: http://scinet.osf.io
Blog: http://rybacki.io
[image: http://github.com/harryrybacki]
<http://github.com/HarryRybacki> [image:
https://twitter.com/HarryRybacki] <https://twitter.com/HarryRybacki> [image:
http://www.linkedin.com/in/HarryRybacki/]
<http://www.linkedin.com/in/HarryRybacki/> [image:
https://plus.google.com/+HarryRybacki]
<https://plus.google.com/+HarryRybacki>

**Comment by lbanner** [comment]
Cool!
