### ISSUE TITLE
[Staging & Production] S3: Access and Secret Key boxes remain up after successful submit

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#2028]
Reported by @ginavuu on the 0.27 Trello board

# Steps
1. Go to user settings.
2. Connect to S3.

# Expected
After typing in the keys, the secret and access key type box should go away if successful, and a success message should be displayed.

# Actual
After success, both boxes remain up, and a success message is display below. Only when a user navigates away from the page and returns do the boxes disappear.

![image](https://cloud.githubusercontent.com/assets/10926926/6471964/289bbb48-c1bd-11e4-94c7-7f6f1b8e4bfe.png)

**Comment by lbanner** [comment]
We should check how this functionality compares to the other add-ons -- do they all do this?

**Comment by ginavuu** [comment]
The other add-ons do not ask for username and password on the same page but instead goes to a different page.

**Comment by jinluyuan** [comment]
https://github.com/CenterForOpenScience/osf.io/issues/3793 is the updated version of this issue.
