### ISSUE TITLE
[staging & production] Inconsistencies in user settings add-on configuration

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2031]
# Steps
1. Go to user settings 
2. Enable all Storage add-ons.
3. Delete any current access tokens and create them all again.

# Expected
I would expect that there would be consistency in how add-ons look in user settings after authorization. 

# Actual
There are many inconsistencies, noted below. 

![screen shot 2015-03-03 at 3 44 47 pm](https://cloud.githubusercontent.com/assets/5975444/6472086/dad28382-c1bd-11e4-89a5-ea58a41ffd33.png)

- Two of the add-ons (Box and Dropbox) have messages about connecting them to a project, but the other add-ons do not. 
- S3 and Figshare do not have any information about who authorized the add-on, whereas all other add-ons have an "authorized by XYZ" note.
- For the add-ons which denote who authorized them, some are full names and some are usernames for that particular add-on (not sure if this can be changed based on what is being returned via add-on API)
- Pretty sure this is already an issue, but clicking the GH username redirects to GH, whereas pressing the Dataverse username (or full names for any other add-ons) does not redirect

**Comment by lbanner** [comment]
Agreed: We need to work on consistency of add-on functionality. Part of that may well be undertaken in next Epic.

**Comment by samanehsan** [comment]
The success message was there for all addons after they were configured, but if access was revoked through the provider (e.g. from your dropbox account settings instead of through the OSF) before any projects were configured, you would see both the success message above and an error message saying that your credentials may no longer be valid. 

Since each addon must handle what happens in the case of the user revoking access through the addon instead of through the OSF, they all need to individually handle the case I described previously. I actually have two pending PRs that do just that for Amazon S3 and Figshare: #1325 and #1326 that were in response to issue #332.  

In both cases, the success message will be shown when the addon is configured. And if access is revoked through the user's S3 or Figshare account instead of the OSF, that success message will change to a warning message that the account credentials may no longer be valid.

**Comment by samchrisinger** [comment]
Perhaps these could get rolled into https://github.com/CenterForOpenScience/osf.io/pull/2014?

**Comment by samchrisinger** [comment]
On second thought after talking with @jmcarp he mentioned that some of @lyndsysimon's current work with OAuth is highly relevant to and may resolve this. We should get his comments before doing any new work on this.

**Comment by lbanner** [comment]
@lyndsysimon Yes, based on our today conversation, your input/insight here would be helpful as to what or how much your work might resolve. Thanks.

**Comment by kushG** [comment]
I had a PR that dealt with handling this consistency for Github https://github.com/CenterForOpenScience/osf.io/pull/1305. This may not be required though after @samchrisinger and @lyndsysimon 's Addon refactoring PRs.

**Comment by lbanner** [comment]
OK -- thank you -- insight from @samchrisinger or @lyndsysimon or @sloria on this one would be good. Based on above ^^ we could close this + the PR.

**Comment by samchrisinger** [comment]
This is addressed in two PRs:
https://github.com/CenterForOpenScience/osf.io/pull/2014
https://github.com/CenterForOpenScience/osf.io/pull/2107
and @harrismendell is working on bringing GitHub up to date

**Comment by jinluyuan** [comment]
It appears that add-on configuration success messages are still inconsistent. 
![screen shot 2015-06-26 at 4 25 41 pm](https://cloud.githubusercontent.com/assets/8591162/8386888/ecb53b26-1c21-11e5-917b-7d35b55de755.png)

**Comment by hmoco** [comment]
I will be looking at this/including it in my UI changes under #3396 as per @samchrisinger's request.

**Comment by caneruguz** [comment]
@hmoco what's the status of this issue?

**Comment by hmoco** [comment]
@caneruguz This was under my addon refactor. Since that has been pretty much put on hold, I have not worked on this. I was under the assumption this fell under the scope of some of @samanehsan's changes.

**Comment by lbanner** [comment]
You are right @hmoco -- I am tagging this 'hold' as it is likely to be overcome by Project Settings refactor -- Thanks.

**Comment by jinluyuan** [comment]
@caneruguz @hmoco This [Trello card](https://trello.com/c/GgLMwMOf/86-box-and-dropbox-green-success-message-for-connecting-an-account-persists-indefinitely) addresses the issue about the green success message persisting for Box & Dropbox. @samanehsan should be fixing that at some point.

#3786 and #3835 address the problems with "authorized by" inconsistencies.

**Comment by lbanner** [comment]
Actually -- strike that, reverse -- This is user settings. It has been recognized that for a number of technical reasons, these inconsistencies will remain. I am keeping this on hold for review in the future.

**Comment by nanchen47** [comment]
Will be worked on when refine the user settings page.
