### ISSUE TITLE
[Staging & Production] Inconsistent Add-On behavior after configuring in project settings

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2035]
Reported on the 0.27/0.28 Trello by @caileyfitz and Gina

## Steps
1. Go to user settings and authorize Github
2. Now go to a project's setting page and import the access token for Github
3. Link a repo; submit.
4. Do the same for Mendeley and Dropbox

## Expected
The success message should be consistent with other add-ons.  If there is a link to the files or overview page then it should be consistent for all add-ons.  Also, the success message should remain with the link.

## Actual
For the following add-ons there is a success message with a link:
Dropbox
Mendeley
Figshare

For the following there is not:
S3
Dataverse
Github

The success message with links disappear after a short time.
![screenshot 2015-03-04 09 09 57](https://cloud.githubusercontent.com/assets/9381062/6484985/412c9dd0-c24e-11e4-8d1d-4d2bd80ce84e.png)

**Comment by samchrisinger** [comment]
Still WIP, but some progress worth noting:
- PR for updating S3: https://github.com/CenterForOpenScience/osf.io/pull/2107
- @harrismendell has begun updating Github, and will resume work the week of 3/16/15
- PR for updating Box, Dropbox, Figshare, GoogleDrive, Mendeley, and Zotero: https://github.com/CenterForOpenScience/osf.io/pull/2014

**Comment by samchrisinger** [comment]
It's taking me > 30 min to try to get a dataverse account/link that account to OSF. Probably more effective to have @rliebz take a look when he's in tomorrow.

**Comment by rliebz** [comment]
If you are running into a lot of trouble, I would recommend checking to make sure that `HOST` in your `dataverse/settings/local.py` file is pointing to their production server (thedata.harvard.edu). Either way, I can certainly take a look at this tomorrow.
