### ISSUE TITLE
[Staging & Production] Can't select Figshare content in folder picker

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/osf.io#2036]
# Steps
* Enable Figshare on a project
* Click the change folder button
* Select a project

# Expected
* Submit button appears

# Actual
# No submit button appears; can't select a project

![screen shot 2015-03-04 at 9 31 39 am](https://cloud.githubusercontent.com/assets/1633460/6485400/7daad0f8-c251-11e4-8d93-216be53e2330.png)

**Comment by lbanner** [comment]
@jmcarp ?

**Comment by GaryKriebel** [comment]
You are specifically talking about files in your account versus folders, yes?

**Comment by brianjgeiger** [comment]
This is in project settings where you choose the base folder.

**Comment by GaryKriebel** [comment]
![screen shot 2015-03-04 at 9 36 06 am](https://cloud.githubusercontent.com/assets/9437946/6485462/e92c7bce-c251-11e4-9095-5a12d1387ff9.png)

**Comment by GaryKriebel** [comment]
So... in the screenshot above ... there is no submit button.... I can't change my selection... and if you previously had not made a selection, you won't be able to.

**Comment by samchrisinger** [comment]
Resolved in this PR: https://github.com/CenterForOpenScience/osf.io/pull/2006

**Comment by GaryKriebel** [comment]
@sloria This issue is on production and should be reviewed sooner than later.

**Comment by sloria** [comment]
Fixed.
