### ISSUE TITLE
Wiki page should have syntax guidelines

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2039]
Steps
-------
1. Edit a wiki page.
2. Try to figure out what is possible.

Expected
------------
There would be some way to know what is possible to do with the wiki. Probably with a clickable question mark like search has. That should give a link to an OSF wiki that shows examples of our wiki syntax. The wiki would then have examples of what it could do and how it looks when you use it. It would also have links to the CommonMark specification, Markdown-It, MathJax, our Markdown-It extensions, and anything else we use to create a wiki.

Actual
--------
There is no guidance at all.

**Comment by lbanner** [comment]
Agree 100% ... question is whether this resides in community for developing user documentation or other group/individual. I will clarify. TY!

**Comment by brianjgeiger** [comment]
Markdown-it is our markdown parser. We are using the following extensions:
* [markdown-it-video](https://www.npmjs.com/package/markdown-it-video)
* [markdown-it-toc](https://github.com/samchrisinger/markdown-it-toc)
* [markdown-it-sanitizer](https://www.npmjs.com/package/markdown-it-sanitizer)

We are highlighting code with [highlight-js](https://highlightjs.org)

Markdown-it optionally supports the [current Commonmark spec](http://spec.commonmark.org/0.18/) and we have enabled that option.

We are doing math rendering with [Mathjax](http://www.mathjax.org). Mathjax is using the following configuration: TeX-AMS-MML_HTMLorMML

This is not great for the end user, but anyone who wants to use this documentation should have all the information they need from these links.

**Comment by lbanner** [comment]
That's good and helpful ^^ -- thank you @brianjgeiger

**Comment by KatyCain526** [comment]
@brianjgeiger I agree that this is a problem, and I've had to do some googling around and asking tons of questions just so I understand markdown, let alone all the fanciness that we can instill in the wiki pages. 

So I've made a getting started video and I was thinking of including some of the more useful things on the actual getting started page in text. If there is something you want linked or a particularly useful tool that you want mentioned in the getting started page then I can probably include that without much trouble.

http://en.wikibooks.org/wiki/LaTeX/Mathematics 
http://assemble.io/docs/Cheatsheet-Markdown.html

**Comment by KatyCain526** [comment]
https://www.youtube.com/watch?v=2RVJS7nYX8k&feature=youtu.be

**Comment by jlcohoon** [comment]
Community team has 3 +1s on this. They also suggested just adding a small indication/link that the wiki uses Markdown, like how Github does:

![screen shot 2015-06-19 at 12 28 01 pm](https://cloud.githubusercontent.com/assets/4965832/8257901/d71d3262-167e-11e5-84b4-f287e5b25cfb.png)

**Comment by brianjgeiger** [comment]
This is a fairly simple thing for someone to do. All of the information is collected.
