### ISSUE TITLE
Remove Collaborator Network

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2044]
Steps
--------
Go to Explore->Collaborator Network

Expected
------------
A cool visualization of the current state of the OSF

Actual
--------
Currently, the Collaborator Network is out of date and problematic. 

Proposed solution
------------------------
I recommend removing it for the moment until we can get something to replace it. There's some discussion in #98 that might also be relevant to a replacement Collaborator Network. If we are super-clever, we can leverage Elastic Search to make a live replacement.

**Comment by HarryRybacki** [comment]
Harsh critics.
