### ISSUE TITLE
Wiki snippets appear for every word

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#2055]
In the wiki editor, the snippets suggestions popup appears for virtually every word the user enters. This can be pretty annoying.

Expected:

The snippets popup only appears after entering at least a few characters of a word.

**Comment by lbanner** [comment]
@brianjgeiger ?

**Comment by brianjgeiger** [comment]
I have no special knowledge of the snippets; that was implemented before my time on the wiki. Anyone would be as good at that as I would be, and one or two others would be better.

**Comment by Ghalko** [comment]
I can't find any more specific settings on the ace editor autocomplete than enable autocompletion. No simple way to change when it should start from a cursory glance.
