### ISSUE TITLE
Wiki view only pages should not be fixed to a height [Enhancement]

### ISSUE THREAD

**Issue by caneruguz** [CenterForOpenScience/osf.io#2056]
Based on a conversation with @brianjgeiger  and his conversation with @JeffSpies  the idea is to remove the box around View section of the wiki when it's the only visible item and make the entire page scroll. 

This makes sense because when only one wiki panel is active there is no need for the containment to happen. However I suggest that we do this only for the case where View is the only visible panel (of the three Wiki functions). 

So BEFORE: 

![screen shot 2015-03-05 at 10 30 09 am](https://cloud.githubusercontent.com/assets/1314003/6507880/25789154-c323-11e4-9186-2d16f9587755.png)

and suggested AFTER: 

![screen shot 2015-03-05 at 10 31 03 am](https://cloud.githubusercontent.com/assets/1314003/6507887/2d9c06e0-c323-11e4-899c-fc03e913e1ef.png)

**Comment by JeffSpies** [comment]
That's a fine starting point.

**Comment by caneruguz** [comment]
@brianjgeiger Do we still want menu bar to be closed initially?

![screen shot 2015-03-05 at 10 47 02 am](https://cloud.githubusercontent.com/assets/1314003/6508159/06608eaa-c325-11e4-97b1-aa4956170253.png)

**Comment by brianjgeiger** [comment]
@caneruguz For the RPCB and RPP links in the footer, I believe so, but not for general functionality. That could be a separate PR, however.
