### ISSUE TITLE
No pagination for file versions

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/osf.io#2059]
# Steps
* Upload >10 versions of a file to a project
* Go to the file detail page

# Expected
* The most recent 10 versions of the file are listed, with a link to view more versions

# Actual
* The most recent 10 versions are listed, with no way to view more versions

Additional fun fact: users can access older versions by manually changing the URL, but if a user does this, the most recent version of the file will be highlighted in the revisions table. This is also kind of a regression, since we had pagination for OSF Storage file versions before.

**Comment by brianjgeiger** [comment]
If we switch file view to match the wiki display, this will not be an issue.

**Comment by chennan47** [comment]
i will grab this one.
