### ISSUE TITLE
Create project "+" icon is misaligned

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#2062]
![osf___dashboard](https://cloud.githubusercontent.com/assets/2379650/6513229/73669630-c347-11e4-88ac-496e4237137d.png)

This seems to have regressed after recent CSS changes.

**Comment by caneruguz** [comment]
When you add this custom tag like other boxes are using, it fixes it; 

![screen shot 2015-03-05 at 3 45 21 pm](https://cloud.githubusercontent.com/assets/1314003/6514230/ca655c1c-c34e-11e4-9a03-5f62159a94e8.png)

...which tells me there is a class affecting based on child but I can't find where it is, normally inspecting css should help but it looks identical. I'm super baffled about this.

**Comment by samanehsan** [comment]
I can't tell what's causing this to happen either, but moving the icon tag above the "Create a project" heading fixed the problem for me. https://github.com/CenterForOpenScience/osf.io/blob/develop/website/templates/dashboard.mako#L57-63. If this seems like an okay solution, I can put in a PR for it.

**Comment by lbanner** [comment]
Maybe @sloria or @caneruguz can weight in, but I am good with it.

**Comment by nanchen47** [comment]
This problem only occurs in "Chrome". It doesn't happen in Firebox, safari and IE.
