### ISSUE TITLE
Warning messages for missing local.py files are need location and/or module information.  

### ISSUE THREAD

**Issue by billyhunt** [CenterForOpenScience/osf.io#2070]
After a fresh installation, when running 

`invoke server`

I get the following warnings

[website.addons.box.settings]  WARNING: No local.py settings file found
[root]  WARNING: No local.py settings file found
[website.addons.dropbox.settings]  WARNING: No local.py settings file found
[website.addons.figshare.settings]  WARNING: No local.py settings file found
[website.addons.github.settings]  WARNING: No local.py settings file found
[root]  WARNING: No local.py settings file found
[root]  WARNING: No local.py settings file found
[root]  WARNING: No local.py settings file found

Several of the messages (the ones listed as [root]) could list the module or location where the local.py file is missing so the local.py files can be added.

**Comment by brianjgeiger** [comment]
Warnings should be fine. Does it run? Does it show anything?

.:Brian

**Comment by lbanner** [comment]
Thanks for noting @billyhunt

**Comment by sloria** [comment]
This is an easy fix. Will submit a patch shortly.

**Comment by lbanner** [comment]
TY!
