### ISSUE TITLE
[dev] Faster CI builds using Travis CI's container-based insfrastructure

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#2072]
Discussed with @icereval : We could see significant increases in build speed by taking advantage of Travis CI's new container-based system: http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

The only barrier right now is that we are installing TokuMX with `sudo`: https://github.com/CenterForOpenScience/osf.io/blob/0ef4524c590a14a14abad0df1bd55662238ccb28/.travis.yml#L14-15 . If we could figure out how to install Toku as the build user, we could then set `sudo: false` and enjoy faster builds.

**Comment by lbanner** [comment]
I think we should consider an "internal" label? .... maybe DEV should have a label? But also we get "enhancement" and "feature" requests from Community. Insights anyone?

**Comment by JeffSpies** [comment]
I believe Megan is working on this.

**Comment by sloria** [comment]
We may also need to remove any usage of `npm install -g <something>`. We shouldn't need to install any npm packages globally. We would just need to change the invoke tasks to run, e.g.

```
./node_modules/bower/bin/bower install
```

instead of using global CLIs.
