### ISSUE TITLE
[production] View-only link doesn't display wiki content

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2073]
Steps: 
1. Click on view-only link: https://osf.io/26mer/?view_only=b31fa8c0a2b742fca1822549814b47b5

2. See that there is content in the wiki page from the widget on the project overview page

3. Go to the wiki page, either by clicking Wiki in the nav bar or by clicking the open button on the widget

4. The wiki content is not visible.

Expected:

Clicking to open the wiki would display the wiki content

Actual:

It does not.

**Comment by brianjgeiger** [comment]
Interestingly, we are getting Forbidden errors with the API wiki links.

![screen shot 2015-03-05 at 8 43 07 pm](https://cloud.githubusercontent.com/assets/6599111/6518939/3ad5161e-c37b-11e4-8fd6-6e0a795b103a.png)

The routes seem to be decorated properly https://github.com/CenterForOpenScience/osf.io/blob/develop/website/addons/wiki/views.py#L226-L229 unless @must_be_contributor_or_public isn't valid for things that work with view-only links. @chennan47 ?

**Comment by sloria** [comment]
The problem seems to be related to modifying the query params. On page load the `view_only` query param is removed. Removing the calls to `history.replaceState` fixes the problem.

I will look into a fix shortly.

**Comment by sloria** [comment]
Should be fixed now @saradbowman
