### ISSUE TITLE
Email to project

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2078]
Proposal
------------
Give projects email addresses which would allow users to send content and conversations to the project. Only emails that match contributors with write permission would be allowed to use the email address. Email content would be archived and viewable. Files would be saved. Files with the same name but different content would be added as new versions. Files with the same name but the same content would be ignored.

To start with, I would suggest not going too crazy on the email display, unless there's a good webmail client we could use to handle email threading and the like. But just an archive that people could go through on a message-by-message basis if they are interested. Later, perhaps adding threaded views or what-have-you might be a nice flourish.

Additional features could be giving wikis their own email address, so the subject of the email would be the page name, and the body would be the entry.

I expect the main use case would be that people would CC their project when they have offline conversations so they can ensure that data is not lost. It's also a convenient start at adding ubiquitous capture to the OSF that doesn't require custom mobile clients.

We already have the start of this with the Presentation service, so there might not be a long distance to get this integrated.

**Comment by TimErrington** [comment]
+1

**Comment by GaryKriebel** [comment]
Closed
