### ISSUE TITLE
wiki - find does not behave as expected

### ISSUE THREAD

**Issue by erinspace** [CenterForOpenScience/osf.io#2080]
## Steps
- Go to a wiki page with lots of content
- Click edit 
- Click within the edit text box
- Find text in page (with command+F on a mac or Edit > Find in the browser menu)

## Expected
Find will search within the edit text box and let you jump to the selection you've searched for so you can start editing there.

## Actual
- Activating find using a keyboard shortcut does nothing
- Activating find using the browser menu or by first clicking outside of the edit box and using the keyboard shortcut only searches within the rendered text

![find_in_edit](https://cloud.githubusercontent.com/assets/801594/6528573/e16901a0-c3f0-11e4-837b-657334b9c5d4.gif)

@brianjgeiger says that it probably has something to do with the Ace editor?

**Comment by nanchen47** [comment]
It works when the content is inside the current editing window. When the search content is not in current ace editor window which is hidden as it goes beyond the wondiw height, the search function from your browser can't find it that it seems to be the right behavior. The possible solution can be adding a search function inside the ace editor.

**Comment by lbanner** [comment]
So -- It does work even in the above scenario if my curser is in the Wiki Edit window when I do the Find -- Unless I hear :scream: 's, I am tempted to drop this to low and defer for now (?)

**Comment by brianjgeiger** [comment]
Does it work if you command-f while the ace editor has focus?

**Comment by brianjgeiger** [comment]
Really, the Ace editor has the capability to find from within the editor. It is probably just involves adding a plugin. And this would be good functionality to have for the end user.

**Comment by brianjgeiger** [comment]
And, in fact, this looks like default behavior that Ace has that we may have disabled. http://stackoverflow.com/questions/13677898/how-to-disable-ace-editors-find-dialog

@rliebz Did we disable Ace's find on purpose?

**Comment by rliebz** [comment]
I don't believe we did. As far as I know, all settings are configured here:
https://github.com/CenterForOpenScience/osf.io/blob/d92df8b804a7ecffdfb930f8726db3080e75a59b/website/addons/wiki/static/ShareJSDoc.js#L21-L33

The only command we manually remove is `showSettingsMenu`.

**Comment by brianjgeiger** [comment]
Huh. So it probably is a bug not a feature.

**Comment by lbanner** [comment]
A bug that we can fix? Anyone?

**Comment by rliebz** [comment]
Possibly. My guess would be that Ace is using its default behavior (find is special cased only when Ace is given focus), which is inconsistent with what we want. It's hard to say how easy it would be to fix, but I imagine there is a solution out there.
