### ISSUE TITLE
'Current Status' Page

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2086]
We should have a persistent place for people to go if they want to know if we think everything is currently working. As we have many different services, some of which are not in our direct control (add-on providers, Piwik, MailChimp, Elastic Search, and so on) that may not be functioning for periods of time independent of the rest of the site, it would be great if they could check to see if we know about the problem, what the likely cause is, and when we expect things to be working. We can tweet these things, or we can hotfix warnings or something, but having something we can update without affecting the rest of the site will make communication much easier and more professional.

An added flourish would be to have a status widget available everywhere (say, in the navbar) that would be color coded to indicate whether things are good, good but with minor issues, or bad, and they could click it to see the status page. 

Ideally, we wouldn't have any problems, but they will happen, so being able to communicate our understanding and progress with them will help greatly.

**Comment by fabianvf** [comment]
:+1:

**Comment by samanehsan** [comment]
This is a repeat of https://github.com/CenterForOpenScience/osf.io/issues/1003

**Comment by lbanner** [comment]
Yes - it is a good one. @brianjgeiger can we add your comment/description on this one to #1003?

**Comment by brianjgeiger** [comment]
So it is.

**Comment by lbanner** [comment]
TY
