### ISSUE TITLE
[IE9] Website responsivenes broken in IE9

### ISSUE THREAD

**Issue by caneruguz** [CenterForOpenScience/osf.io#2088]
## Steps: 
1. Go to a project page on IE9
2. Check to see if there is horizontal scrolling

## Expected
There shouldn't be page wide horizontal scrolling since width of the page should adjust to the width of the window

## Actual
There seems to be a fixed width to the entire website, there is scrolling. Columns respond to width changes but it's not fully responsive. See screenshot:

![screen shot 2015-03-06 at 2 52 35 pm](https://cloud.githubusercontent.com/assets/1314003/6535248/8c9f77b4-c411-11e4-8bb3-0d9f41de7bfa.png)

Can a second person check this?

**Comment by caseyrollins** [comment]
I have a Windows VM I can check this in.

**Comment by lbanner** [comment]
Thanks @caseyrollins

**Comment by caseyrollins** [comment]
@caneruguz I'm getting the same horizontal scrolling problem in IE 9. And the horizontal scrolling doesn't allow me to see the whole page -- even when I scroll all the way over, I can never see the end of my name in the top right.

![screen shot 2015-03-06 at 4 08 15 pm](https://cloud.githubusercontent.com/assets/7913604/6536463/c88dad5e-c41b-11e4-991f-5481b7b525f9.png)

**Comment by nanchen47** [comment]
Will be considered based on further user's feedback. Thanks.
