### ISSUE TITLE
User does not come up in search

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#2090]
# Steps
* search for user "Simine Vazire" or "Simine" or "Vazire" - occurs in general search and when adding an author

# Expected
* This profile should be found: https://osf.io/gmjz6/

# Actual
* Nothing is found

**Comment by brianjgeiger** [comment]
Hmmm. Do we need to do a search migration, @sloria @icereval ?

**Comment by sloria** [comment]
Migrated. Simine shows up in search now.

**Comment by lbanner** [comment]
Thanks @sloria
