### ISSUE TITLE
[Staging & Production] Profile page obscured view for really long names

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2100]
## Steps
1. Change your profile name to a really long name.
2. Go to your profile page.

## Expected 
For long names the entire name would be visible and not obscured.

## Actual
For long names the portion that moves above is half obscured.

![screen shot 2015-03-09 at 10 05 05 am](https://cloud.githubusercontent.com/assets/9381062/6556433/dc82728e-c643-11e4-877e-48973e93a8ba.png)

**Comment by samanehsan** [comment]
Looking into this one! @lbanner @GaryKriebel

**Comment by lbanner** [comment]
Thanks!

**Comment by samanehsan** [comment]
I have a fix for this issue, but it introduces another problem where long profile names are misaligned with the gravatar. I can't seem to get the alignment right, so I'll let someone else pick up this issue. I've pushed up my code to https://github.com/samanehsan/osf.io/tree/feature/fix-profile-name in case it may be useful.

**Comment by lbanner** [comment]
OK thanks

**Comment by samanehsan** [comment]
@NatashaRichter noticed this happening again on both staging and production.

**Comment by caneruguz** [comment]
@ticklemepierce can you send an update on this? What is your plan to resolve it?

**Comment by lbanner** [comment]
@caneruguz ... @ticklemepierce has moved on from his internship. We'll need to reassign. Thanks.
