### ISSUE TITLE
[staging & production] Can incorrectly delete Figshare file from files view page

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2101]
# Steps
1. Link a public figshare fileset to a project
2. Go to the files tab for that project
3. Hover near the download button and see if you can delete a file
4. Click on a file to go to the files view page
5. Look for a Delete button 
6. Click the Delete button

# Expected
I expect that for public figshare filesets, you should not be able to delete a file. 

# Actual
On the files tab, there is NOT a red x to delete the file, but on the files view page, there is a Delete button that appears briefly. Pressing the button before it disappears actually allows a user to delete the file completely. See gif.
![2015-03-09 10_35_10](https://cloud.githubusercontent.com/assets/5975444/6556991/ff0d94ce-c647-11e4-94e3-839d46df2132.gif)

**Comment by chrisseto** [comment]
@jmcarp Should this even be possible given the figshare API?

**Comment by jmcarp** [comment]
@chrisseto no, this shouldn't be possible, and they don't let you delete files from public filesets through their web interface. I'll just hide the delete button.
