### ISSUE TITLE
[Staging] (& Probably Production) Add-On: Github Unable to resolve error in Project Settings

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2103]
## Steps
1. Create a project
2. Go to project settings and enable Github
3. Import the access token

## Expected
When enabling the Github add-on for a project the access token would authorize the add-on and not create an error for that add-on and the settings page for the project.

## Actual
After enabling Github for the project and attempting to import the access token to link a repo to the project, an 'Unable to Resolve' error is received.  Now each time the setting tab is clicked for the project the same 'Unable to Resolve' error occurs. 
This occurred on staging but likely would occur on production if the specific circumstances that produce the error were enabled.

![screen shot 2015-03-09 at 10 21 43 am](https://cloud.githubusercontent.com/assets/9381062/6557252/083af846-c64a-11e4-9617-49e54ae610ee.png)

**Comment by nicipfeiffer** [comment]
@jmcarp I think you know what this is all about.

**Comment by jmcarp** [comment]
@nicipfeiffer yes, this is probably happening because we don't handle the case where a user's tokens are revoked or expired outside of OSF. I'll get this resolved today.

**Comment by samanehsan** [comment]
@jmcarp, I remember @chennan47 was working on a fix for when users revoke access tokens through github so you two may want to discuss
