### ISSUE TITLE
Error: Duplicate headers received from server

### ISSUE THREAD

**Issue by lbanner** [CenterForOpenScience/osf.io#2113]
![screen shot 2015-03-09 at 11 37 18 am](https://cloud.githubusercontent.com/assets/2964829/6560966/34444266-c664-11e4-90dd-d659666c46e2.png)

Error received trying to download a file from GitHub.
Same error with google drive.
Error occurred with file name having a comma.
Could be a 'Chrome' specific defect, as the error does not crop up with other browsers.

**Comment by lbanner** [comment]
Reported by @caileyfitz --

**Comment by nanchen47** [comment]
I verified on production that this problem has been solved. 
![screen shot 2015-04-01 at 4 58 03 pm](https://cloud.githubusercontent.com/assets/11743657/6952492/50a166da-d890-11e4-8088-168c5ebd4b99.png)
