### ISSUE TITLE
[Feature Request] Allow navigation to presentations page on the OSF

### ISSUE THREAD

**Issue by KatyCain526** [CenterForOpenScience/osf.io#2115]
**Summary**
I went to the OSF, tried to get to the presentations page, could not get there without the link. 

**Expected:**
1) I expect to be able to navigate to the presentations page from the OSF. 

2) I also expect to be able to navigate from osf.io to my individual conference's page. 

**Actual:**
1) I cannot navigate there unless I have the link. 

2) I cannot navigate there unless I have the link and there are more than 5 presentations in the conference I am attending. 

**Suggestion:**

1) Add a link under the "Explore" tab that says "Presentations" 

2) Add a link  that says "See All" on the Presentations page that allows you to see all presentations if clicked, placed next to the "Only conferences with at least five submissions are displayed here." text for context.  

@jmcarp 
@lbanner

**Comment by KatyCain526** [comment]
It deals with two things, the first one is the main one.

**Comment by lbanner** [comment]
I have no obstacles to this proposal, and think the need for a direct link is there -- labeling with "discuss" as I'd like to hear from Community @saradbowman or @AndrewSallans on proposed solution (?)

**Comment by fabianvf** [comment]
It seems like a no-brainer to me, considering how popular the presentation service has been.

**Comment by saradbowman** [comment]
I think this is a great idea. 

I wonder about what to call it - would "Presentations" convey the right meaning to users?  other options: Presentations and Posters, Conferences, Presentation Hosting?

After all that, I think I vote for Presentations...

**Comment by samanehsan** [comment]
This has been reported in https://github.com/CenterForOpenScience/osf.io/issues/1418 and there is also some discussion there!!

**Comment by lbanner** [comment]
@samanehsan Looks like you have a PR on that (#1418) ? Up-to-date? Thanks!

**Comment by samanehsan** [comment]
@lbanner, that is a reference to this issue, not a PR!

**Comment by lbanner** [comment]
Ha! Right .... infinity mirrors! :arrows_counterclockwise:

**Comment by caseyrollins** [comment]
@lbanner I can go ahead and add "Presentations" to the Explore dropdown if that seems like the solution we're going with. I could also easily add it to the footer as well.

**Comment by lbanner** [comment]
Had put/suggested @Ghalko on this one -- BUT -- If you are open and can tackle it, I think that'd be good @caseyrollins -- Unless he :scream: 's
