### ISSUE TITLE
[dev] Remove dependency on handlebars.js / project organizer refactor

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#2119]
Handlebars is only used in one module right now, projectorganizer.js . This module diverges from the rest of the codebase's style and architecture (which use either Knockout or mithril). I propose to refactor this module such that we can remove Handlebars as a dependency and make projectorganizer.js more consistent with the codebase.

I realize that removing handlebars is probably part of a larger refactor of the project organizer; we can break this up into smaller issues if need be.

**Comment by brianjgeiger** [comment]
If you can use the templating independently from the rest of the frameworks, then switching the template system should be a fairly small and focused change.

**Comment by Ghalko** [comment]
@sloria, was this addressed with the 0.36 release?

**Comment by sloria** [comment]
Yes, this was addressed. We still use Handlebars, for the Onboarder, but it has been removed from the project organizer, which was what this issue was about.
