### ISSUE TITLE
[Production] Wiki  generating potentially wrong URLS

### ISSUE THREAD

**Issue by caneruguz** [CenterForOpenScience/osf.io#2132]
As you toggle views in the Wiki the URL generated shows long and unnecessary "undefined" in many places which may lead to wrong URLs. Here's a walk through with screenshots and urls.
This does not affect which panels are shown, everything else is working fine, saving, loading version within applet, showing hiding etc. 

#### 1. Open a wiki page

``` 
https://osf.io/w925b/wiki/Something%20new/?=undefined
```

![screen shot 2015-03-10 at 10 30 21 am](https://cloud.githubusercontent.com/assets/1314003/6576929/bccf5290-c710-11e4-8701-4828e35707b2.png)

#### 2. Toggle Edit to show two columns: Edit and View 

```
https://osf.io/w925b/wiki/Something%20new/?=undefined&edit=undefined&view=current&menu=undefined&edit&view&menu
```

![screen shot 2015-03-10 at 10 32 32 am](https://cloud.githubusercontent.com/assets/1314003/6576940/d5f8a30c-c710-11e4-97cc-943c71010a97.png)

#### 3. Reload the current URL:  Reloading page at this point changes View from "Preview" to "Current" (I added some versions in the meantime) 

![screen shot 2015-03-10 at 10 36 38 am](https://cloud.githubusercontent.com/assets/1314003/6577034/603f0498-c711-11e4-8c21-67929004dcfb.png)

#### 4. Add Compare:

```
https://osf.io/w925b/wiki/Something%20new/?=undefined&edit=undefined&view=current&menu=undefined&edit&view=current&compare&menu
```

![screen shot 2015-03-10 at 10 37 05 am](https://cloud.githubusercontent.com/assets/1314003/6577045/71a4e25c-c711-11e4-8555-70d5e6f6f2c0.png)

#### 5. Reload existing page:

First reload loads it, second reload says Invalid request 

![screen shot 2015-03-10 at 10 39 43 am](https://cloud.githubusercontent.com/assets/1314003/6577103/cfa009e0-c711-11e4-96c4-af7f54a47ab3.png)

#### 6.Change comparison version and reload also resulted in Invalid Request

```
https://osf.io/w925b/wiki/Something%20new/?=undefined&view=undefined&compare=undefined&menu=undefined&view&compare=1&menu
```

**Comment by caneruguz** [comment]
@brianjgeiger I added you as administrator to this project in osf.io

**Comment by brianjgeiger** [comment]
Yeah, going to the wiki is definitely adding the ?=undefined right after page load, which certainly didn't happen before. I wonder what changed. Okay, working on this now.

**Comment by brianjgeiger** [comment]
Talked with @sloria; it was apparently a change that he had made. He is fixing now.

**Comment by sloria** [comment]
Yep, looking into this now.
