### ISSUE TITLE
New wikis without JS are not shown in pages

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2135]
Steps
--------
`curl` a wiki page that has been edited in the last week

Expected
-------------
The wiki text will appear in the HTML that is received

Actual
--------
Wiki text is not on the page

We are currently returning data in the html for pages that are older than the recent one-page wiki updates. However, newer pages are not getting that data. So we need to ensure that the raw markdown is sent and shown with the page and replaced with the rendered version when the JS finishes loading. Not doing so will affect SEO of those wiki pages. 

Along with that, a webtest should be added to verify that the behavior is correct.

**Comment by sloria** [comment]
Fixed by #2141
