### ISSUE TITLE
Can't upload to a new project from onboarder widget

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#2146]
Suggested by @JeffSpies : there is no way to upload a file to a new project from the "Upload a file" onboarder widget. This would be nice to add.

**Comment by kushG** [comment]
I can work on this.
@lbanner @sloria ?

**Comment by lbanner** [comment]
I'm good with that -- I'll add you. Thanks.

**Comment by nanchen47** [comment]
@kushG any update on this one?

**Comment by kushG** [comment]
@nanchen47 , I got involved into another feature request which is almost into its final stages. Once this PR https://github.com/CenterForOpenScience/osf.io/pull/2231 is merged I'll get back to continue working on this !

**Comment by lbanner** [comment]
:+1:
