### ISSUE TITLE
[staging / prod] Rendering spss files throws a celery error

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/osf.io#2149]
# Steps
* Upload an spss data file (.sav)
* Render it

# Expected
* The file renders
* OR message is displayed indicating that we can't render this file type
* No errors are thrown in celery

# Actual
* The render waits until the timeout interval, then times out
* Errors are thrown in celery

# Proposed fixes
* Add r, rpy2 to mfr tabular dependencies
* OR disable support for spss files

I don't remember, but we may have decided to drop support for spss rendering at some point--installing r, rpy2, and the `foreign` library might not be worth the headache. If we do want to drop spss support, then we shouldn't even try to render these files. Or, if we want to render spss files without dealing with r, we might try https://bitbucket.org/fomcl/savreaderwriter.

Original error at https://sentry.osf.io/osf/production/group/2324/

**Comment by jmcarp** [comment]
FWIW, .sav files are the 12th most common file type on OSF by upload count, at 1977.

**Comment by brianjgeiger** [comment]
It's a shame the build is failing on savreaderwriter.

**Comment by brianjgeiger** [comment]
Maybe we could put a bounty out on someone converting that C code to python?

**Comment by lbanner** [comment]
How big a user issue is this? And who else might need/want to weigh in?

**Comment by mfraezz** [comment]
The most common reason for savreaderwriter's recent build failures: `Build execution time has reached the maximum allowed time for your plan (40 minutes).` on 1-2 environments of 6 per build, with pip not being installed on the server (?) a distant second.

If .sav's are the 12th most common file type among user uploads, we should definitely support rendering them. I'll look deeper into savreaderwriter, (and run their tests locally, etc.) and see whether or not it's a cleaner viable solution than r

**Comment by mfraezz** [comment]
Savreaderwriter looks like it would probably function well enough, but its [license](https://bitbucket.org/fomcl/savreaderwriter/wiki/LA_en) might be prohibitive, nor does it seem particularly actively maintained.

A promising alternative to both that and r/rpy2/foreign could be SciPy, an open source library that can read and write `.sav`'s. It depends on NumPy and is somewhat coupled with IPython, and Pandas, (see [PyData](http://pydata.org/downloads/)) all three of which we currently use. It would also open the door to adding Matlab support to the osf, as it has `.mat` IO capabilities as well. Thoughts/opinions?

**Comment by brianjgeiger** [comment]
https://github.com/scipy/scipy specifically? Well, the first thing they do is explain how to pronounce the name, which is better than most OSS products, so I'm immediately favorable towards it. That being said, I have otherwise not looked at all.

**Comment by brianjgeiger** [comment]
A little concerned that the [installation instructions](https://github.com/scipy/scipy/blob/master/INSTALL.rst.txt) are more involved than ours.

**Comment by mfraezz** [comment]
Yes, that one. The [docs](http://docs.scipy.org/doc/scipy-dev/reference/generated/scipy.io.readsav.html#scipy.io.readsav) say they'll give you a dict from a `.sav` file

If by 'involved' you mean 'thoroughly documented', yeah. It's pip-installable, and the instructions boil down to:
1. Use Python 2.6 or higher
2. Install NumPy 1.5 or newer
3. Run `python setup.py install` after cloning it (or, without cloning, run `pip install git+http://github.com/scipy/scipy/`) 
4. Pray that none of the known problems happen   `¯\_(ツ)_/¯`

**Comment by mfraezz** [comment]
I used this and matplotlib for a project or two in college, and found them generally easy to work with. I do recall it taking a while to install, though.

**Comment by mfraezz** [comment]
It turns out there's a difference between IDL .sav files and SPSS .sav files... though I'd be interested to know if the 1977 .sav's are all SPSS. If not, this would give me an excuse to implement an extra layer of validation with the *nix `file` utility.

**Comment by csoderberg** [comment]
Just fyi @lbanner , An article just published in PLOS (http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0134808) links to an OSF project with all their data as SPSS files.

**Comment by lbanner** [comment]
Good heads-up! But those SPS files are rendering for me @csoderberg -- Not for you?

**Comment by csoderberg** [comment]
Sorry, should have been more clear, the .sav files are SPSS data files, which are not rendering. The .sps field are SPSS syntax files.

**Comment by lbanner** [comment]
Oh -- OK -- @mfraezz can you and @sloria provide insight and update on this issue, please? ASAP? Thanks.

**Comment by mfraezz** [comment]
pypi is currently down, but when I try to render it locally I'm getting an `ImportError` coming up through pandas. `rpy2` apparently isn't being installed by the build script. Including it in requirements might fix it.

**Comment by mfraezz** [comment]
pypi is back up, and installing `rpy2` fixed it locally (.sav taken from the above project): 
<img width="1280" alt="screen shot 2015-08-06 at 14 18 01" src="https://cloud.githubusercontent.com/assets/5659262/9119710/288a1182-3c46-11e5-8260-dcaa65741864.png">

**Comment by mfraezz** [comment]
The underlying issue has been addressed, but it requires devops intervention to fix. I've notified the appropriate people.

**Comment by icereval** [comment]
Fixed with MFR [hotfix/0.3.9](https://github.com/CenterForOpenScience/modular-file-renderer/commit/fb4c52efa7223fc2d5cc968316e313357d7b8165) and Dockerfile [build](https://github.com/CenterForOpenScience/docker-library/commit/0a8eee0e5438af09ef5bb70e95c7867313785a9f).

h/t @mattclark & @mfraezz
