### ISSUE TITLE
[dev] Add cross-browser testing with SauceLabs

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#2153]
Run our JS unit tests across many browsers with SauceLabs.

**Comment by sloria** [comment]
@huangginny Has begun work on this.

**Comment by sloria** [comment]
@huangginny has added the ability to run against sauce labs locally. Before this issue is closed, we should also add CI support.

**Comment by lbanner** [comment]
You undertaking that @sloria -- or should we look for new assignee?

**Comment by sloria** [comment]
Yes, this will need to be me or @icereval , as we'll need to create a SauceLabs account for COS and set up the secure envvars in our `.travis.yml`

**Comment by lbanner** [comment]
Thanks

**Comment by nanchen47** [comment]
@sloria any update on this one? Thanks.

**Comment by sloria** [comment]
We are able to run our tests using `inv karma --sauce`.

I think we can close this issue once we have integrated it with Travis CI.

**Comment by nanchen47** [comment]
The jsunit tests have been integrated with Travis CI.

**Comment by sloria** [comment]
While we are running are tests against PhantomJS on TravisCI, we are not yet running our tests on SauceLabs through TCI.

This issue is still open.
