### ISSUE TITLE
Project organizer not always storing state

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2154]
Steps
-------
1. Go to dashboard
2. Expand a collapsed item that is not a smart folder
3. Collapse that item
4. Reload the page

Expected
------------
The item that was expanded and collapsed will be collapsed on reload

Actual
--------
The item is expanded.

It seems to be doing the collapse/expand REST request for the first action, but not the second, so collapsing an item that was expanded on load will work, but clicking again will not make the request.

**Comment by lbanner** [comment]
@caneruguz ^^ -- Thanks

**Comment by GaryKriebel** [comment]
@caneruguz will this be fixed with the toolbar changed?

**Comment by caneruguz** [comment]
@nanchen47 @lbanner a PR for this is sent so it is pending review.
