### ISSUE TITLE
[Staging & Production] Add-on Configuring Confirmation Modal

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2155]
## Steps
1. Go to the user settings page; configure add-ons
2. Check the box to enable a new add-on
3. Once PR# https://github.com/CenterForOpenScience/osf.io/pull/1327 is merged you will now need to hit 'OK' to agree to the terms for that add-on
4. Now click on 'Profile Information' on the left side (do not hit 'submit')
5. Go to the Employment tab and change a date or something
6. Click on 'Configure Add-ons' on the left side again to return to the add-ons
7. Click 'leave the page' on the confirmation modal.
8. Return to the configure add-ons and note that the check box previously checked is now no longer checked.
9. Check the same check box you checked earlier again; you will see the same terms that you already agreed to again.

## Expected
That the same behavior for leaving a page when there is unsaved information would occur.
![screen shot 2015-03-12 at 10 00 39 am](https://cloud.githubusercontent.com/assets/9381062/6619154/c1fc4d74-c89e-11e4-8891-3e75c6fda6d9.png)

## Actual
When the user is configuring add-ons by checking the box to enable one but doesn't complete the process by hitting the submit button there is no confirmation modal alerting the user that they have made a change in their settings and have not saved before leaving the page.  The same occurs if you input user name and password information in the add-ons to authorize but fail to hit submit before leaving the page; there is no confirmation modal alert.  Likewise, if you are in the profile information settings and update or change the information there, a confirmation modal does alert the user to save before leaving.

**Comment by haoyuchen1992** [comment]
@lbanner Can I grab this one?

**Comment by lbanner** [comment]
Yours -- Thanks.

**Comment by sloria** [comment]
Fix merged into develop. Will be released with 0.41.0
