### ISSUE TITLE
Parent projects improperly displayed on child projects for project admins

### ISSUE THREAD

**Issue by lyndsysimon** [CenterForOpenScience/osf.io#2159]
## Steps to Reproduce

1. Create two users: User A, User B
1. As User A, create three nested projects: Grandparent > Parent > Child
1. Add User B as an administrator for the Grandparent project
1. As User B, visit the Child project.

## Expected

* The Parent project's name should be header.
* The "up to parent project" link in the project navbar should take you to the parent project.

## Actual

* The Parent project's name is not displayed in the header - instead, "Private Project" is shown.
* The "up to parent project" link in the project navbar is linked to nothing.

![screen shot 2015-03-12 at 12 57 12 pm](https://cloud.githubusercontent.com/assets/131414/6623132/75008832-c8b7-11e4-8d3d-d0fb0e0dbe21.png)

**Comment by nanchen47** [comment]
@caileyfitz could you verify this issue has been solved in production.

**Comment by caileyfitz** [comment]
@nanchen47 Yes, this is fixed on prod :+1:
