### ISSUE TITLE
[Staging & Production] Add-on Terms Available for users

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2160]
## Steps
1. Go to user settings; configure add-ons
2. Check the checkbox next to various add-ons to enable
3. Click 'OK' when the terms modals appear.

## UI Question
How can a user return to these terms?
I think ethically we need to have those available to users at any time.
Especially if the Two Factor terms are taken from the configuring section and changed to be consistent with other add-ons in a terms modal.

## Possible Solution
There certainly is a need for a user to revisit the terms agreed to without having to deauthorize the add-on and authorize it again to see the terms modal.  
If there could be a link or a way on hover you can have them pop up for review, I think that would be great.

**Comment by nicipfeiffer** [comment]
Linking this other issue as they are related, sort of. https://github.com/CenterForOpenScience/osf.io/issues/2161

**Comment by GaryKriebel** [comment]
Closed
