### ISSUE TITLE
[Production] Error handling entity encoded project name for OSF storage on File Detail Page

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2163]
Reporting this for @lyndsysimon 

## Steps
1. View a file from OSF storage with an entity encoded into the project title
An example is https://osf.io/wtbm6/

## Expected
That the project title '2015: March -> May' would appear the same in the breadcrumb pathway as it does for the project.

## Actual
It looks like this:
![screen shot 2015-03-12 at 3 25 47 pm](https://cloud.githubusercontent.com/assets/9381062/6626312/1abf3278-c8cc-11e4-934a-520aa38a9eac.png)

Where the project title has different language for '->'

**Comment by brianjgeiger** [comment]
This also happens in the Project Organizer. 

![screen shot 2015-03-13 at 4 04 30 pm](https://cloud.githubusercontent.com/assets/6599111/6646407/eb9646e2-c99a-11e4-9bc9-443d458c0bb6.png)


As a first step for this task, it would be a good idea to survey the interface and find all the other places this happens. Also, I believe there are a couple of functions that are fixing ampersands in these circumstances; ideally you should just have to add < and > into that to fix it most places.

**Comment by samanehsan** [comment]
Closed by #2857
