### ISSUE TITLE
Change class of "Revert" button in wiki

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2167]
Steps
-------
1. Make some changes to a wiki in live edit mode

Expected
------------
Revert button would be appropriately warning of the lossy nature of clicking revert

![screen shot 2015-03-12 at 4 03 19 pm](https://cloud.githubusercontent.com/assets/6599111/6639369/6148853e-c965-11e4-8eb7-848f78d9d398.png)

Actual
--------
Revert button is a jaunty, successful green.

![screen shot 2015-03-13 at 9 43 31 am](https://cloud.githubusercontent.com/assets/6599111/6639377/6fa1f156-c965-11e4-9b3c-4007fedf2759.png)

Proposed solution
------------------------
Change the class of the revert button to "danger". Probably should change the save button to "success", as opposed to the screen shot above which leaves the save button alone.

Requested by @lbanner

**Comment by caneruguz** [comment]
I sent a PR for this.
