### ISSUE TITLE
[staging & production] figshare revoked access not handled properly

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2169]
Related to #332 but a special case 

# Steps
1. Link and configure figshare for at least one project/component
2. Follow the steps listed in https://trello.com/c/vvQwHOdE/63-staging-handle-revoked-api-access-through-figshare to revoke API access through figshare
3. Visit user settings page
4. Visit the node settings page for the project/component linked to figshare
5. Open the dev console and then click 'Change' button to change the folder associated with figshare
6. If able, change the linked folder to a private folder
7. Go to the files tab for node
8. *If* the files are showing in the files tab, click on a file to render it

# Expected
I expected that there would be an error message similar to that seen for dropbox when API access is revoked, explaining what has occurred:
![dropbox](https://cloud.githubusercontent.com/assets/9381062/6625679/e7f3e388-c8c7-11e4-991d-6d6e8190f930.png)

I also expected that when access is revoked, current figshare folders should not be able to load and, furthermore, that files/filenames should not be able to load in the files tab.

# Actual
There is no error message displayed to the user. Additionally, here are other unexpected actions related to the step numbers listed above:
3. No error message on user settings page
4. No error message on project settings page
5. Figshare folders load most of the time, but sometimes the console shows a '400 Bad Request' and it appears to the user as though the folders are just taking forever to load
6. When the folders load, linked folders can be changed
7. Files some of the time. The three situations I have encountered are: 
- Files load and all filenames can be seen
- Files do not load but the figshare icon is present but appears collapsed, and when the plus sign is pressed to expand it, an error occurs in the grid saying that 'Files couldn't load, please try again later' and the console shows a '401 Unauthorized' error
- The figshare icon does not appear in the grid at all, even though the settings page says that a folder is linked

.8 When the files load in the files grid, a file can be clicked and the user is redirected to the files view page. The file does not render though, and a '401 Unauthorized' error is shown in the console and the user sees a message on the page saying that the file could not be rendered.

**Comment by nanchen47** [comment]
As the new folder which is https://github.com/CenterForOpenScience/osf.io/pull/2014 by @samchrisinger just go on staging, the pr is just under testing and modifying a lot of parts of the current addon backend. It's better to address addon issues after this is quite settled. Besides revoking api process itself is quite an edge case and it will be solved in the process when we refactor the old addons into the new oauth system. Put this to defer and change the priority to low.
