### ISSUE TITLE
[dev] Internal inconsistency in naming for presentation sharing service

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#2171]
The internal naming for the presentation sharing service is all over the place:

- The URL for listing presentations is `/presentations/`
- The URL pattern for a single presentation is `/view/<meeting>/`
- The module is `website.conferences`. Views are called `conference_view`, `conference_results`, etc.
- Templates are called `meeting.mako`, `meeting_body.mako`, etc.

Publicly, we use the term "Presentation Sharing Service", so it would makes sense to use the `presentation` namespace consistently.

**Comment by sloria** [comment]
Thanks @caneruguz for catching this a while back.

**Comment by sloria** [comment]
Perhaps the only changes to be made:

- Change url pattern to `/view/<conference>/`
- Change templates to `conference.mako`, `conference_body.mako`, etc.

That way, we establish the terminology:

presentation=a submission of a poster or presentation
conference=an event that used the Presentation Sharing Service

**Comment by lbanner** [comment]
@saradbowman ... there have been some suggestions / discussions around this, maybe? Does this remain an issue?

**Comment by sloria** [comment]
@lbanner The poster service was recently rebranded as "OSF for meetings". The issue of the internal naming inconsistencies still stands.

**Comment by saradbowman** [comment]
related #2744 and @chennan47's PR

**Comment by chennan47** [comment]
This is covered in https://github.com/CenterForOpenScience/osf.io/pull/2742

**Comment by nanchen47** [comment]
The pr has been merged.

**Comment by sloria** [comment]
The PR only changed the URL route to `/meetings/`. There are still inconsistencies (e.g. usage of "conference" in the views) to be addressed. Reopening.

**Comment by chennan47** [comment]
@sloria does is mean to change all the "conference" in the backend code to meeting?

**Comment by sloria** [comment]
@chennan47 Yes, that would be an improvement.
