### ISSUE TITLE
Canceling Dropbox Token Doesn't Return User to Project Settings

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2177]
Steps
-------
1. From a project or component, go to "Settings" and choose Dropbox.
2. Click okay, then click to create access token.
3. Enter username/password, click okay
4. Modal appears: "Open Science Framework would like to access your Dropbox account." Click Cancel.
5. You are returned to your user settings page.

Expected
------------
You would be returned to the settings page for the project or component you were on originally.

Actual
--------
You are returned to the user settings page.

Other notes
--------
I have tested this with Google Drive and the behavior is not the same (canceling access token creation returns you to component settings page).

Reported on the help desk.

**Comment by lbanner** [comment]
Thank you fro grabbing this @chennan47

**Comment by chennan47** [comment]
@lyndsysimon talk with Lyndsy and the new Oauth system may fix this issue? Can you confirm that, Lyndsy? If not I have a quick hotfix for this https://github.com/CenterForOpenScience/osf.io/pull/2180

**Comment by lyndsysimon** [comment]
Since the hotfix is done, I think it's fine to merge it in.

Until the next release, it might be prudent for us to make sure that issues having to do with OAuth are double checked to make sure that we aren't duplicating effort.

**Comment by nanchen47** [comment]
Talked with @lyndsysimon. The new OAuth system has already been merged in and verify on production that this bug is gone.
