### ISSUE TITLE
Presentation service does not respect "sent on behalf of" email addresses

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/osf.io#2179]
# Steps
* Set up one email address (e.g. a gmail address) to send mail on behalf of another (e.g. a university address)
* Submit a presentation to OSF using the first address, sent on behalf of the second

# Expected
* The presentation is created for the second email address

# Actual
* The presentation is created for the first address

# Proposed solution
The "sent on behalf of" header can be spoofed, so we can't just create the presentation for that address. To use this address, we could add a confirmation step to the submission process, so that the owner of the "on behalf of" address would have to verify that the submission belongs to them:
* User sends email from one address on behalf of second address
* The presentation project is created but marked private
* OSF sends confirmation email to second address
* The user confirms that the submission is genuine
* The presentation project is marked public

It sounds like @KatyCain526 is getting a bunch of questions about this aspect of the presentation service, and the proposed fix would save a significant amount of time for the people managing the service.

**Comment by lbanner** [comment]
@saradbowman .... can you weigh in on this approach to solution as well, please? TY

**Comment by saradbowman** [comment]
I was about to create an issue for this- so glad to see it already raised and with a potential solution!

This sounds reasonable to me -- my only concern is that users don't always read their emails/follow instructions. Am I correct in assuming that confirming the submission is genuine will be a "click here" step and that will automatically turn the project public? (i.e., it won't tell the user, "go to your project and make it public")

**Comment by lbanner** [comment]
@jmcarp -- I think that ^ was the proposal, yes?

**Comment by jmcarp** [comment]
@saradbowman agreed that users might not notice that they're supposed to do something in response to the confirmation email. I think that using a subject like "Confirm your submission to conference <conference name>" and putting the confirmation link at the top of the message would help. We can also send a reminder if they haven't confirmed after a day.

**Comment by saradbowman** [comment]
+1

**Comment by lbanner** [comment]
This looks to be resolved with multiple emails per account -- Closing.
