### ISSUE TITLE
[Production] MFR rendering pdb file error

### ISSUE THREAD

**Issue by jeg3tw** [CenterForOpenScience/osf.io#2182]
# Steps
1.  Go to the MFR project
2.  Attempt to render a pdb file.

# Expected
A pdb file will render.

# Actual
The user sees a black screen that disappears into a blank white one.
*This problem occurs in Firefox and Safari as well as IE*

**Comment by lbanner** [comment]
Is it expected that pdb files should render? And do they, in fact, render in any browser currently? -- Thanks

**Comment by brianjgeiger** [comment]
They are expected to render. Also, any files that aren't meant to render should have an "unsupported file type" style message.

**Comment by lbanner** [comment]
'K

**Comment by mfraezz** [comment]
This is a CORS issue for FF/IE/Safari, and seemingly only when using OSF Storage. It's also present for .pdf's under the same circumstances

**Comment by lbanner** [comment]
Can it be overcome?

**Comment by mfraezz** [comment]
Yes, though there are currently more important issues that would take less effort to fix. There was a similar albeit broader problem before, and these were the deferred cases from that fix.

**Comment by mfraezz** [comment]
Also, regarding your earlier question about browsers: this isn't an issue in Chrome because it's a bit more liberal with allowing redirects

**Comment by lbanner** [comment]
OK -- I prioritized low -- and thank you.

**Comment by sloria** [comment]
This should now be fixed on develop/staging. @jeg3tw Can you verify?

**Comment by samanehsan** [comment]
This works in firefox on staging and production.

**Comment by lbanner** [comment]
Opens in Safari -- Looks cool! -- Tested and working in IE as well @sloria

**Comment by sloria** [comment]
Thanks for checking @samanehsan and @lbanner
