### ISSUE TITLE
[Staging & Production] Figshare Deletion

### ISSUE THREAD

**Issue by jeg3tw** [CenterForOpenScience/osf.io#2183]
# Steps
1.  Link both a private and public fileset dataset to a project
2.  Go to the file viewer
3.  Hover near download button of a public file attempting to delete

# Expected
The user is allowed to delete files from public file sets unless there’s only one file left in the fileset.

# Proposal 
This is currently working, but seems unclear to the user that should be the case.  Perhaps the terms modal should be edited to explain this scenario.

**Comment by lbanner** [comment]
The clarity from @jmcarp on this one: It is a FigShare restriction: you’re allowed to delete files from public file sets unless there’s only one file left in the file set - then you cannot delete that last file.

It can be assumed that a FigShre user might know this (?) But: Suggestion is put some language around that in the terms modal.

**Comment by brianjgeiger** [comment]
I think the Terms modal is the wrong place for this. Presuming a collaborative project, most users will not see the terms modal. Limitations should be made clear in the interface near where it would be used.

**Comment by lbanner** [comment]
Good point @brianjgeiger .... do we do any such communication on add-on limitations for any other add-on in any spot on OSF? -- or can I assume this would be introduction of a new feature?

**Comment by jmcarp** [comment]
@lbanner right, this is a figshare restriction. The behavior on OSF mirrors the behavior on the figshare site. I personally didn't realize that this was the expected behavior when I was browsing the figshare site, so I'm not sure whether it will be obvious to other figshare users. Agree with @brianjgeiger that explanations close to the delete functionality would be best (i.e. on the files page and the file detail page), but would hesitate to add more clutter esp. to the files page.

**Comment by samanehsan** [comment]
If my understanding of Figshare is correct, users should not be able to delete published files at all. When I try to delete a published Figshare file from the files grid, I get a 400 error in the console along with the following error message:  
![screen shot 2015-06-22 at 5 26 41 pm](https://cloud.githubusercontent.com/assets/6414394/8293520/e0f2531c-1903-11e5-8ae4-f12c854df387.png)

Also, when I go to the file detail page, the delete button is there for a few seconds before disappearing from the page which makes me think it shouldn't be there in the first place.

**Comment by lbanner** [comment]
So -- messaging then on this can be improved? i.e. Instead of "delete failed" should we articulate "Delete failed. Published files cannot be deleted from Figshare" ?

**Comment by samanehsan** [comment]
@lbanner, my current fix won't show the delete button in the files toolbar if the user cannot delete that figshare file. I think if the delete is guaranteed to fail we shouldn't show it to the user or the button should be disabled. Thoughts?

**Comment by lbanner** [comment]
Much better idea!
