### ISSUE TITLE
Odd Behavior in Nav Bar: Component of Private Project

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2184]
Steps
-------
1. Visit a component on which you are a contributor, but not a contributor on its parent. Parent should be private. 
2. The arrow in the nav bar is mirrored and unclickable:
![screen shot 2015-03-16 at 1 16 42 pm](https://cloud.githubusercontent.com/assets/7749914/6671919/14a8816c-cbdf-11e4-9ce2-867d737280a1.png)

Expected
------------
One of these: 
*Able to click on the up arrow and be told I can't access the resource because it's private
*I can't click on the up arrow, but the up arrow appears normally (perhaps a tooltip telling me why I can't click on the arrow, and the arrow is grayed out):
![screen shot 2015-03-16 at 1 16 50 pm](https://cloud.githubusercontent.com/assets/7749914/6671963/548ad262-cbdf-11e4-8ad4-50982c229843.png)
*There isn't an arrow at all.

**Comment by brianjgeiger** [comment]
I learn towards resolution 2 including the tooltip. That's what it was supposed to be.

**Comment by caneruguz** [comment]
@sloria @lbanner  PR sent.

**Comment by lbanner** [comment]
:+1:
