### ISSUE TITLE
Wiki TOC links do not scroll page

### ISSUE THREAD

**Issue by lyndsysimon** [CenterForOpenScience/osf.io#2185]
## Steps to reproduce

1. Create a wiki page that is longer than the container on the page.
1. Add a header near the bottom of the wiki page.
1. Add a TOC to the top
1. Save the wiki page
1. Click the TOC link to the bottom header

## Expected

The wiki page should scroll to the appropriate section

## Actual

Wiki page does not scroll, the containing web page jumps to the bottom.

**Comment by brianjgeiger** [comment]
Fixed by #2047

**Comment by lbanner** [comment]
'K -- thanks -- noted as 'Pending Review'

**Comment by caneruguz** [comment]
Just an update that the fix is now in this PR: #2200
