### ISSUE TITLE
Associate multiple email addresses with one account

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2190]
Currently, a user can request two accounts be merged under one, but there is not a way to associate two emails with one active account. 

User story:
User has an account with email address X. User submits presentation to presentation service using email Y. User requests account merge, all under email X.

A year later, user submits to another presentation service using email Y. User must request account merge again under email X. 

You can also imagine users being added as unregistered contributors under a university email address, but may already have an account under a personal email address. 

Related to #2179

**Comment by JeffSpies** [comment]
@lyndsysimon

**Comment by lyndsysimon** [comment]
This is one of the tasks I'm working on for this epic - I'm awaiting Saman's PR #2094 to be merged before starting on it.

**Comment by lbanner** [comment]
Hey @lyndsysimon -- This is a slight extension as regards requirements for accounts: The ability not just to change a single associated email w/account, but actually have two (2) email addresses for accounts. Interested in your thoughts re: our single point of ID for accounts and complications of two email addresses associated (?) Data-wise, what serves as ID ... email addy or numerical designation?

**Comment by lyndsysimon** [comment]
We've used emails to this point, and I see no reason to change that. The `username` field will contain the account's "primary" email, which will be the address we use for communications as well. That address will also be in the `emails` field, to make it easier to keep email addresses associated with only one account at a time.

**Comment by nanchen47** [comment]
@lyndsysimon https://github.com/CenterForOpenScience/osf.io/pull/2289 should solved this problem.

**Comment by lbanner** [comment]
Correct @nanchen47  -- I will close this in favor of @lyndsysimon 's new work.
