### ISSUE TITLE
[staging & production] Change language in add-on authorization error message

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2201]
# Steps
1. Authorize Dropbox for a project
2. Go to Dropbox and revoke OSF API access (steps listed here: https://trello.com/c/QrFH1npQ/46-production-handle-revoked-api-access-through-dropbox)
3. Return to the OSF and go back to project settings 
4. You should now see an error saying that credentials may no longer be valid and giving instructions on how to remedy the situation

# Expected
I expect that the directions given to the user would solve the problem appropriately. 

# Actual
The directions read as follows
![screen shot 2015-03-17 at 10 17 40 am](https://cloud.githubusercontent.com/assets/5975444/6690338/68a71d7a-cc96-11e4-9d24-770adb8efabe.png)
BUT deauthorizing and reauthorizing on the project settings page does not actually solve the problem. On the project settings page, pressing Deauthorize unlinks the node from the access token (or something... I don't think I'm using the right words here), and reauthorizing via pressing Import Access Token just imports the old, incorrect access token. The real solution to the problem is going to the user settings page and deleting the faulty access token and creating a new one. The text should reflect this.

**Comment by samanehsan** [comment]
@caileyfitz, by "Try deauthorizing and reauthorizing Dropbox", I did mean deleting the access token and re-authorizing (creating a new access token). Would it be clearer if instead it said "Please delete your access token and create a new one"?

**Comment by caileyfitz** [comment]
@samanehsan Yes, definitely more clear.

**Comment by nanchen47** [comment]
The hotfix pr has been merged in and checked on production.
![screen shot 2015-04-01 at 5 05 26 pm](https://cloud.githubusercontent.com/assets/11743657/6952615/6536995c-d891-11e4-980c-d971cd51b3a3.png)
