### ISSUE TITLE
[staging & production] Dropbox files grid 404 Not Found

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2203]
Sort of related to #2201 

# Steps
1. Authorize Dropbox for a project and open the dev console
2. Go to Dropbox and revoke OSF API access (steps listed here: https://trello.com/c/QrFH1npQ/46-production-handle-revoked-api-access-through-dropbox)
3. Return to the OSF and go back to project settings 
4. You should now see an error saying that credentials may no longer be valid and giving instructions on how to remedy the situation
5. Press the Deauthorize then Import Access Token buttons
6. Note the messages in the console

# Expected
I expect that deauthoring and reauthorizing would work as described (this is the issue noted in #2201) but also that if there is an error with the folder picker, that should be communicated to the user. 

# Actual
The console shows a 404 Not Found error: 
![screen shot 2015-03-17 at 9 56 21 am](https://cloud.githubusercontent.com/assets/5975444/6690975/046b5408-cc9a-11e4-9167-66180468e95c.png)

but the user only sees the loading status in the folderpicker. 
![screen shot 2015-03-17 at 9 57 18 am](https://cloud.githubusercontent.com/assets/5975444/6690972/fd215616-cc99-11e4-9080-017c77b3281d.png)

The user would have no idea that an error was received unless their console was open. A visible error message here saying that an error occurred loading the folders would be helpful to inform the user more fully.

**Comment by samanehsan** [comment]
When you refresh the page, the error message is there. I think this will only happen if the user is on this page while access is revoked and then they try to change the selected folder.

**Comment by nanchen47** [comment]
All the old addons needs to refactor auth to the new oauth system. Once the refactor is in, this problem should be solved. Defer after the 31 release of @samchrisinger 's folder cleanup is on production.

**Comment by lbanner** [comment]
Good - yes.

**Comment by samchrisinger** [comment]
We might actually have regressed on this in the latest iteration. Will put up a PR to resolve this.
