### ISSUE TITLE
[staging & production] Absent custom tooltip for 'Duplicate' icon on project overview

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2211]
# Steps
1. Go to a project
2. Hover over the icons on the top-right hand side of the screen. 
3. There should be three icons that give tooltips: *Add/Remove from Dashboard*, *Watch/Unwatch*, *Duplicate*

# Expected
I expect that all three tooltips would look the same and be consistent with other tooltips on the site: black background with white text.

# Actual
*Add/Remove from Dashboard* and *Watch/Unwatch* both have the expected tooltip: 
![screen shot 2015-03-17 at 4 27 18 pm](https://cloud.githubusercontent.com/assets/5975444/6696824/84f02a2c-ccc2-11e4-9113-d838af69ca2c.png)

![screen shot 2015-03-17 at 4 23 55 pm](https://cloud.githubusercontent.com/assets/5975444/6696804/5c7887c4-ccc2-11e4-811a-baea7a58938e.png)

 *Duplicate*, however, does not show the custom tooltip. Instead, a default tooltip is displayed after hovering for a while:
![screen shot 2015-03-17 at 4 24 01 pm](https://cloud.githubusercontent.com/assets/5975444/6696812/717e9c1c-ccc2-11e4-98ba-7260ecdbe2df.png)
Maybe there is a tooltip class or formatting missing here or something?

**Comment by brianjgeiger** [comment]
This is a regression of something that happened during the Webpack/CommonJS sprint. The first two are bound to Knockout contexts, so they work through that mechanism. The last is being done with a separate function that @sloria did. I'm not sure what broke it, but if someone was refactoring anything low down (base.mako, navbar.mako, or the JS related to those), that may have done it.
