### ISSUE TITLE
Admin view to control the conference page

### ISSUE THREAD

**Issue by lbanner** [CenterForOpenScience/osf.io#2220]
For a number of reasons, it is important to have an admin role for our OSF based presentation (conference) service:

General concerns about non-conference attendees emailing in posters/presentations that didn't belong. To our knowledge, this hasn't been a problem thus far -- but it's not hard to imagine such a scenario, in particular when/if the service grows in popularity. 

Mail spam filter not consistent - many emails coming in are often marked as spam.

An administrative role will allow for monitoring submissions in both the above cases, and intervening as necessary. But this administrative role would not allow access to or visibility of the individual projects created when submitting presentations.

**Comment by nanchen47** [comment]
Will be considered when refine the meetings page.
