### ISSUE TITLE
Project parent page link for Private Parent page is disabled but with insufficient feedback

### ISSUE THREAD

**Issue by caneruguz** [CenterForOpenScience/osf.io#2225]
## Steps
1. Create a Project condition where parent project is private
2. Go to child project and click on the upwards arrow link to access the parent project

## Expected
Since you can't go to the link the icon color should be more muted
There should not be a hover effect on the arrow

## Actual
There is a hover and the icon is muted but still too dark, to a user looks like a proper link and the user may not know why the link is not working. 

Screenshot of element:
![osf___2015__march_to_may](https://cloud.githubusercontent.com/assets/1314003/6710923/350f9464-cd5a-11e4-8011-b4f920d9603e.png)

**Comment by lbanner** [comment]
Quite possibly similar and related to this issue #2184

**Comment by huangginny** [comment]
@caneruguz @lbanner  I think a more serious problem that arises her is that the icon there is flipped vertically.

Parent project inaccessible:
![screen shot 2015-03-18 at 10 52 37 am](https://cloud.githubusercontent.com/assets/8628591/6711360/f1835926-cd5c-11e4-93af-a99b3b49501a.png)

Parent project accessible:
![screen shot 2015-03-18 at 10 52 52 am](https://cloud.githubusercontent.com/assets/8628591/6711366/f84f65a6-cd5c-11e4-8951-97dd26c64a16.png)

**Comment by caneruguz** [comment]
@Larry yes these are related, and the mirroring Ginny is referring to is also mentioned there. We can close this and if you like you can assign me to the other one, I did the logic for the arrow there and I know how it can be fixed.

**Comment by lbanner** [comment]
Done @caneruguz - Thanks!
