### ISSUE TITLE
[production & staging] Folder Picker Unavailable after 2nd Import

### ISSUE THREAD

**Issue by icereval** [CenterForOpenScience/osf.io#2235]
Steps
------
Go to a project's settings page
Select an add-on such as dropbox
Import or Create the access token
Expand the folder picker by clicking Change if not already displayed
Deauthorize the add-on (dropbox)
Reauthorize the add-don (dropbox)
Attempt to expand/collapse the folder picker

Expected
------
The folder picker expands/collapses upon clicking the Change button.

Actual
------
The folder picker is never displayed, only a line where it would be. The user must refresh the page to reenable folder picker functionality.

![folder picker](https://cloud.githubusercontent.com/assets/3111541/6716038/fd9890ca-cd78-11e4-8f91-e6be5f39eb69.gif)

**Comment by samchrisinger** [comment]
Can I get assigned to this?

**Comment by brianjgeiger** [comment]
Done.

**Comment by samchrisinger** [comment]
Resolved in: https://github.com/CenterForOpenScience/osf.io/pull/2250

**Comment by nanchen47** [comment]
This problem is actually fixed on staging but not yet on production. The fix is possibly included in https://github.com/CenterForOpenScience/osf.io/pull/2014. Once the 31 release is out. Need QA to verify this has been fixed on production.

**Comment by lbanner** [comment]
:+1: ... closing for now.
