### ISSUE TITLE
[Production & Staging] IE Search bar placeholder not visible

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2248]
## Steps
1. Using Internet Explorer, login to your account
2. Click the magnifying glass in the navbar at the top of the page

## Expected 
The placeholder 'Search' would appear in the green search bar as it does in the other browsers
![screen shot 2015-03-19 at 9 52 54 am](https://cloud.githubusercontent.com/assets/9381062/6731822/0c71ff78-ce1e-11e4-956f-b0242f26d07a.png)

## Actual
The search bar has no placeholder.
![screen shot 2015-03-19 at 9 54 48 am](https://cloud.githubusercontent.com/assets/9381062/6731824/113ed3d2-ce1e-11e4-9f4b-1d4d5435eb9f.png)

**Comment by sloria** [comment]
@nicipfeiffer Which IE version?

**Comment by nicipfeiffer** [comment]
IE 11
