### ISSUE TITLE
[Production & Staging] Rendering issue with .csv, .xls and .gsheet files

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2254]
## Steps
1. Go to a project and select on a file with a .csv, .xls or .gsheet extension
2. On the file detail page, shrink the browser size then expand

## Expected
The file would expand and contract within the proper border on the right so that all information is visible on the page.

## Actual
The cells will spill into the widget to the right, obstructing the view of the file information.  Occurs on all browsers.
![screen shot 2015-03-20 at 8 39 50 am](https://cloud.githubusercontent.com/assets/9381062/6751667/f743ff42-cedc-11e4-80c3-713324904b10.png)

**Comment by nanchen47** [comment]
@mfraezz can you help to fix this problem? Thanks.

**Comment by mfraezz** [comment]
The width appears to be hard-coded to 700 pixels (and height to 600). Don't know why that was set in the first place, but I'll work on getting it to scale to the parent container.

**Comment by lbanner** [comment]
:+1:

**Comment by chennan47** [comment]
related issue https://github.com/CenterForOpenScience/osf.io/issues/1606. After the fix being merged, need to test word file as well.

**Comment by AndrewSallans** [comment]
Still seeing this problem on an .xls file on a private project right now.  What's the timeline for getting this resolved?

**Comment by mfraezz** [comment]
@AndrewSallans I have an open PR that fixes the scaling issue, needs review: https://github.com/CenterForOpenScience/modular-file-renderer/pull/168

**Comment by saradbowman** [comment]
Also just reported on the help desk.

**Comment by lbanner** [comment]
@sloria This issue has been sitting around for a while -- Can you get a review in of @mfraezz 's CenterForOpenScience/modular-file-renderer#168 ? Thanks!

**Comment by samanehsan** [comment]
Closing this since CenterForOpenScience/modular-file-renderer#168 has been merged and I this no longer seems to happen on production or staging (E.g. https://staging.osf.io/hq2md/).
