### ISSUE TITLE
MFR PDF renderer cut off for portrait documents

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2255]
Steps
-------

1. Render a PDF document that is portrait

Expected
-----------
The renderer would be completely shown on the page

Actual
--------
The bottom of the render is cut off. 

Suggestion
-------------
If there is an option to zoom to width rather than showing the whole page, that should allow the bottom of the page to fit in the constrained height.

**Comment by icereval** [comment]
working on

**Comment by icereval** [comment]
Resolved by https://github.com/CenterForOpenScience/modular-file-renderer/pull/165
