### ISSUE TITLE
[Production & Staging] When Javascript disabled user profile information not available for external search

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2256]
## Steps
1. Go to a public user profile page with information input for social, employment and education
2. Disable the javascript on the page

## Expected
The information on the page about a user should still be there when JavaScript is disabled so that it can be returned in searches.
![screen shot 2015-03-20 at 9 09 17 am](https://cloud.githubusercontent.com/assets/9381062/6752026/04d64c2e-cee1-11e4-8deb-7781236544a7.png)

## Actual
The information is not on the page, or it is hidden in tabs, therefore not searchable through external searches.
![screen shot 2015-03-20 at 9 09 49 am](https://cloud.githubusercontent.com/assets/9381062/6752031/13da6b38-cee1-11e4-9a6c-cdef83b8ebd6.png)

**Comment by nicipfeiffer** [comment]
@brianjgeiger You know of this issue, yes?

**Comment by brianjgeiger** [comment]
I saw when you put it in. That's not as important as having the public projects and components, but I think it would probably help our SEO by providing links between a user and existing services, but also for being able to find you by specifying what school you went to or your employment history. 

So yes, I think it would be a good thing to fix. I'm not sure how much work it would be or the priority.

**Comment by nicipfeiffer** [comment]
@brianjgeiger Ok, I didn't think you missed it.  But, I don't want this to get lost at the bottom of the list... @lbanner how can we label so it is considered in planning?

**Comment by lbanner** [comment]
Labeled as enhancement -- I suggest we review those, along with labels of "Feature" -- in planning for next Epic. I'll remember to make that happen. Thanks.
