### ISSUE TITLE
[staging & production] Public User Profile name obscured on mobile site

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2260]
When viewing public user profiles on mobile devices the top line of information is cut off.

![screen shot 2015-03-20 at 10 45 14 am](https://cloud.githubusercontent.com/assets/9381062/6753695/48407ffe-ceee-11e4-9d18-04fdf586ec1b.png)

Occurs for iphone 5 and 4

Also, the 'edit profile' link is obscured using Nexus 4 mimicking, if you have a longer last name with descenders.

![screen shot 2015-03-20 at 10 51 21 am](https://cloud.githubusercontent.com/assets/9381062/6753858/6e72b5f6-ceef-11e4-8a82-7dd33e0d9574.png)

**Comment by jinluyuan** [comment]
This occurs on the full site as well, if you put a long enough name.
![screen shot 2015-06-11 at 9 26 21 am](https://cloud.githubusercontent.com/assets/8591162/8108051/0e58ebb8-101c-11e5-8dda-aa08af226a6d.png)

**Comment by lbanner** [comment]
Reopening the issue: Fixed in Mobile but not in full site. @ticklemepierce ? Want to carry over that fix? Thanks.

**Comment by ticklemepierce** [comment]
@jinluyuan @lbanner Should be fixed from https://github.com/CenterForOpenScience/osf.io/pull/2806

**Comment by lbanner** [comment]
Alright -- looks like #2806 forecast release w/0.39.0 today -- We'll test on Production post release, @jinluyuan

**Comment by jinluyuan** [comment]
@ticklemepierce Looks good

**Comment by samanehsan** [comment]
Fixed in #2806
