### ISSUE TITLE
Add-on icons are draggable in IE

### ISSUE THREAD

**Issue by jeg3tw** [CenterForOpenScience/osf.io#2263]
# Steps
1. In **Internet Explorer**, go to a project with at least one component
2. Enable a few external storage add-ons for the project
3. Go to either the files tab or the project overview page
4. Collapse all the add-ons so that you can see them all (helpful if you have a ton of files)
5. Click an icon and drag it slightly to the left and then drag it into another add-on (even OSF Storage)

# Expected
I expect that the icons would be non-draggable 

# Actual
The icons are draggable in IE, and dropping them into another add-on results in an upload of a tiny image of the add-on icon. Image below is an example of a file that is in my OSF Storage that resulted when I dragged the figshare icon onto the OSF Storage icon. 

![](https://trello-attachments.s3.amazonaws.com/54fdd40970c8f608f065b3ce/298x137/73480b127e3c64921fb35e4a260916ef/Screen_Shot_2015-03-09_at_1.18.08_PM.png)

**Comment by leb2dg** [comment]
I'm looking into this one.

**Comment by lbanner** [comment]
Great @leb2dg

**Comment by samanehsan** [comment]
Closed by #2793.
