### ISSUE TITLE
[production] IE: OSF Functionality Site Wide: Adding project to dashboard

### ISSUE THREAD

**Issue by ginavuu** [CenterForOpenScience/osf.io#2264]
Steps
1. Using IE (version 11), go to a project
2. Add the project to the Dashboard from the project page

Expected 
In order to do this, I would expect an icon to add the project to the Dashboard from the project page.

Actual
The icon is not there for IE.

**Comment by chennan47** [comment]
@ginavuu not quite sure about what the issue is. Could you provide some screen shoot to help explain? Thanks.

**Comment by brianjgeiger** [comment]
@ginavuu I am unable to reproduce this. Is there a public project that you can point me to that you aren't seeing the add to dashboard button for? Also, could you go to https://osf.io/e81xl/ and give me a screenshot of what you see? I am getting the Add to Dashboard with that project in IE 11. So it could be a problem with a specific project, or maybe a difference in minor versions of IE.

![screen shot 2015-03-23 at 11 10 45 am](https://cloud.githubusercontent.com/assets/6599111/6782921/4e67796c-d14d-11e4-9505-c7bd448ffef7.png)

If you could bring up your developer tools and see if there are any javascript errors when you don't get the button, that might help as well. Thanks!

**Comment by ginavuu** [comment]
@brianjgeiger I have attached a screenshot. It's weird because the buttons shows up sometimes and not other times
![screenshot](https://cloud.githubusercontent.com/assets/11032617/6785908/1ffd7d58-d15f-11e4-8887-c3b5c9b144ed.PNG)

![screenshot2](https://cloud.githubusercontent.com/assets/11032617/6785997/bb6c3824-d15f-11e4-9a54-51324c07da17.PNG)

**Comment by brianjgeiger** [comment]
Thank you much. That looks like it could be very helpful.

**Comment by brianjgeiger** [comment]
@ginavuu When testing, we are getting the control, but it is very slow in our IE 11 on a Virtual Machine. Could you reload the page and wait for a little while to see if it eventually shows up? And it could be that we need better performance on IE 11, or IE 11 needs better JS performance.

**Comment by ginavuu** [comment]
@brianjgeiger It seems to be working now a lot better. I've noticed that it doesn't load when it is having trouble loading the page, so I think it is just really slow.

**Comment by brianjgeiger** [comment]
Thanks. If you see it again and it isn't just slowness, comment here and we'll reopen. We may have to address the slowness, however, so please try out the site with your computer sometime in chrome or firefox vs IE and see if the experience seems different. If so, file another bug with that info and we can look into seeing if it's something we are doing or just IE having a slow JS interpreter.

**Comment by ginavuu** [comment]
@brianjgeiger I have been trying it with Chrome, and there is a slight lag but it always appears. Only IE is having this trouble of loading. I am having trouble with recreating the problem, because it is so inconsistent.
