### ISSUE TITLE
Text not wrapping on project comments section

### ISSUE THREAD

**Issue by markhahnel** [CenterForOpenScience/osf.io#2265]
Hyperlinks here

![screen shot 2015-03-20 at 12 31 34](https://cloud.githubusercontent.com/assets/7058167/6755961/138369a2-cefd-11e4-9d10-5788b67584f1.png)

**Comment by JeffSpies** [comment]
Thanks, Mark!

@caneruguz, can you please get a hotfix in on this?

**Comment by caneruguz** [comment]
@JeffSpies on it!

**Comment by sloria** [comment]
Fixed by https://github.com/CenterForOpenScience/osf.io/commit/f935a0ecdd4e02f7d90a57788955cab92314a0b0 .

**Comment by sloria** [comment]
In investigating this I noticed that @markhahnel 's hyperlinks were not turned into proper hyperlinks and are therefore not clickable.

A logical solution would be to allow users to use Markdown in their comments; we can enable the same markdown syntax as the Wiki.

I will send a follow-up patch soon.
