### ISSUE TITLE
contributors list in search does not match list on project overview

### ISSUE THREAD

**Issue by mckidwell** [CenterForOpenScience/osf.io#2266]
**Steps:**
1. Search for "Murray"
2. View the project titled "Replication of SL Murray...Exp. 8" in the search results and take note of the contributor list.

![screen shot 2015-03-20 at 12 41 32 pm](https://cloud.githubusercontent.com/assets/7945215/6756198/9b9c497a-cefe-11e4-982a-a315216d37c1.png)
3. Go to this project's overview. Look at the list of contributors on the overview.

![screen shot 2015-03-20 at 12 43 18 pm](https://cloud.githubusercontent.com/assets/7945215/6756214/b589b246-cefe-11e4-92ea-cc9d11a4f4f4.png)

**Expected outcome:** Lists will match each other exactly.

**Actual outcome:** Contributors are listed in the same order, but Mallorie Miller and Rebecca Goldberg have disparities in their OSF profile links.

ALSO,

**Steps:**
1. View the project titled "Replication of SL Murray...Exp. 8" *in the search results* again.
2. Click on Rebecca Goldberg's name.

**Expected outcome:** User will be taken to Rebecca Goldberg's OSF profile.

**Actual outcome:** User is taken to Sining Wu's profile.

**Comment by lbanner** [comment]
Fishy enough it appears to me that we should dig into the underlying issue -

**Comment by huangginny** [comment]
Also happens on this project: https://osf.io/w6fp4/
I'll look into it

**Comment by lbanner** [comment]
OK!

**Comment by huangginny** [comment]
Found the problem. This is what happens when you add a unreg contributor first and add a registered contributor later. I guess the search results are just applying the contributor links returned to the first few contributors.

**Comment by lbanner** [comment]
Do we know how to resolve?

**Comment by huangginny** [comment]
Not yet. Looking at it.

**Comment by huangginny** [comment]
This is a result of the format of elasticsearch. Calling <code>es.search(index=index, doc_type=doc_type, body=query)</code> returns a formatted output that is specified in <code>website/search/elasticsearch.py:update_node</code>. That format stores contributor names and contributor urls in separate lists, which results in the bug. My suggestion is to use the following format in that method:

    {
        'contributors': [
            {
                'url': '/a1b2c'
                'name': 'Ginny Huang'
            },
        ],
        ...
    }

However if I change the format, the format would only take effect when <code>update_node</code> is called. 

@lbanner In this case I think I need help from @fabianvf or you can just re-assign this issue to him.

**Comment by lbanner** [comment]
OK - maybe you reach out to @fabianvf ?  --  recognizing he has SHARE priorities right now, but might give quick insight.

**Comment by fabianvf** [comment]
@huangginny I think that format would be much better. We have a migration script ready, so the impact on the elasticsearch data is irrelevant - if you make the change to the schema, we can migrate all users and nodes to make use of it.

**Comment by huangginny** [comment]
@fabianvf Thanks, I'll try it out :)
