### ISSUE TITLE
[staging & production] Bold HTML tag not sanitized for wiki and comments

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2269]
# Steps
1. Go to the wiki on staging or production
2. Type `<b>Oreo</b>`
3. Press Save
4. Input the same text into a comment on staging

# Expected
I expect that the HTML would be escaped and the text would render as `<b>Oreo</b>`.

# Actual
The text renders as **Oreo** and the tags are not escaped.

**Comment by nanchen47** [comment]
I think we allow the html tag in wiki at least. Any thought? @brianjgeiger @rliebz

**Comment by brianjgeiger** [comment]
Yes, we allow a limited number of tags to be rendered as HTML. https://www.npmjs.com/package/markdown-it-sanitizer
