### ISSUE TITLE
[feature request] Storage add-on for ownCloud

### ISSUE THREAD

**Issue by cosenal** [CenterForOpenScience/osf.io#2277]
OSF already supports several storage back-end options (Dropbox, S3, Google Drive, ...). Support for [ownCloud](https://github.com/owncloud/) would be a great addition to the list. 

It is open-source and it is suitable for privacy-sensitive projects. Further, it is becoming fairly spread among schools and universities.

Integration in OSF should be simple enough through the following library: https://github.com/owncloud/pyocclient

The UI modal of the plugin would be a bit different from the one for Dropbox, as an ownCloud instance can reside at any location, so the address should be specified. Plus, it doesn't support OAuth yet (https://github.com/owncloud/core/issues/10400), but it requires Basic Authentication, so there should be a form for username and password.

If it is of interest, I will try to make a PR as soon as I manage to get OSF up and running -- tokumx package seems to be broken on archlinux at the moment :(.

**Comment by lbanner** [comment]
Hey @cosenal -- thank you for the effort -- We can give direction on setting up OSF -- check in as you progress.

**Comment by cosenal** [comment]
Hi @lbanner, thanks for the reply. 
Which branch should I be working on, `master` or `dev`?
Also, what's the right channel to ask for setup directions? So far I have been getting helped by @lyndsysimon  on IRC (#cos)

**Comment by lbanner** [comment]
You should use `dev` @cosenal -- and glad you got some setup guidance from @lyndsysimon - that works!

**Comment by sloria** [comment]
@cosenal Thank you for offering to take this on! ownCloud certainly looks like a service worth integrating.

Much of the development of storage addons happens in https://github.com/CenterForOpenScience/waterbutler , the service that abstracts all the CRUD functionality for storage providers. I recommend that as a starting point. Here is the Dropbox module as an example: https://github.com/CenterForOpenScience/waterbutler/tree/develop/waterbutler/providers/dropbox

**Comment by lyndsysimon** [comment]
:+1:

I've been interested for some time in implementing a storage provider that is under the control of the person/institution, as opposed to third party providers. This looks like it might fit the bill while still being not too different from the cloud providers we've already implemented :)

**Comment by cosenal** [comment]
I kind of understand how WaterButler works (it reminds me of KDE's akonadi), but I couldn't find any documentation on the it. For instance, does it have a specialized API to communicate with the core server?

**Comment by lbanner** [comment]
@chrisseto or @icereval -- can you assist @cosenal ? Thanks.

**Comment by chrisseto** [comment]
@icereval and I will take some time this week to write up documentation for WaterButler.

**Comment by cosenal** [comment]
@chrisseto awesome, thanks!

**Comment by chrisseto** [comment]
@cosenal Documentation can be found at [waterbutler.io](http://waterbutler.io)

**Comment by cosenal** [comment]
@chrisseto many things are still unclear :( Maybe we should have a chat on IRC. If you happen to be there, please ping me (cosenal on #cos).

**Comment by sloria** [comment]
@cosenal A number of people from COS are currently at PyCon doing sprints on waterbutler. They will likely be available for help on IRC. ping @lyndsysimon @brianjgeiger

**Comment by cosenal** [comment]
@sloria thanks. I am chatting with @chrisseto already :)

**Comment by cosenal** [comment]
I am working on the waterbutler provider here: https://github.com/CenterForOpenScience/waterbutler/pull/41

**Comment by remram44** [comment]
Looks like the add-on has been released with #6075. Close this?

**Comment by mfraezz** [comment]
You're correct, @remram44. Thanks for the reminder :octocat:

**Comment by cosenal** [comment]
Thanks @remram44 for closing this and to @kwierman for implementing the plugin.
I haven't tested it yet, but I will soon!
Just a note: the ownCloud project has been forked to [Nextcloud](https://nextcloud.com/) and many core developer moved to the new project. The API are basically the same, so the plugin should support both a probably be called "ownCloud/Nextcloud".
