### ISSUE TITLE
SHARE links for ASU datasource are broken

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/osf.io#2278]
The new SHARE page ( https://osf.io/share/ ) provides a number of datasources. In most cases, choosing the datasource from the pie chart creates clickable links to each resource.

However, for the ASU datasource, the URL is malformed and can't be clicked:

So for this search...
https://osf.io/share/?q=source:asu

A given result would be displayed as shown:
```
Thermal dark matter implies new physics not far above the weak scale
JHEP is an open-access journal funded by SCOAP3 and licensed under CC BY 4.0
Csaba Balazs · Tong Li · Jayden Newstead


Released on 2015-03-20 06:00 PM
```

The URL does appear to contain linkable DOI information, but by default it appends the entire citation and can't be clicked to reach the desired resource:

https://osf.io/share/Balazs,%20Csaba,%20%20Li,%20Tong,%20%20&%20%20Newstead,%20Jayden%20L.%20(2014).%20Thermal%20dark%20matter%20implies%20new%20physics%20not%20far%20above%20the%20weak%20scale.%20JOURNAL%20OF%20HIGH%20ENERGY%20PHYSICS,%202014:61.%20http://dx.doi.org/10.1007/JHEP08(2014)061

From a quick examination, only this particular datasource is affected.

**Comment by lbanner** [comment]
Thank you @abought -- @fabianvf or @erinspace take a look, please? Thanks.

**Comment by chrisseto** [comment]
[Fixed](https://osf.io/share/?q=source:asu)!
@lbanner Would you mind both confirming this is fixed and closing the issue?

**Comment by lbanner** [comment]
Will do!

**Comment by lbanner** [comment]
Alright -- looking good @chrisseto -- Thank you @abought !

**Comment by abought** [comment]
Confirmed working for me in production. Speedy fix!
