### ISSUE TITLE
Update markdown-it and plugins to 4.0

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2279]
Our Markdown renderer has updated to 4.0 and changed its internals. We should upgrade at some point, which will involve updating our plugins to match the new internals.

**Comment by Ghalko** [comment]
Submitted 2 PRs:
https://github.com/samchrisinger/markdown-it-toc/pull/3 @samchrisinger 
https://github.com/brianjgeiger/markdown-it-video/pull/4 @brianjgeiger 

Waiting for review/merging before continuing with integration.

**Comment by sloria** [comment]
@brianjgeiger @Ghalko  Are there breaking changes in the syntax that would affect OSF users?

**Comment by Ghalko** [comment]
@sloria There aren't any syntax changes to the markdown itself. I am sorry to have confused that. The syntax is within the module and the plug-ins, no API was changed/broken.

**Comment by samchrisinger** [comment]
:+1:
