### ISSUE TITLE
invoke setup breaks on asset bundles building

### ISSUE THREAD

**Issue by cosenal** [CenterForOpenScience/osf.io#2280]
I get the error below when I run `invoke setup`. This is at the moment when the asset bundles are built. In fact, it can be reproduced also by running `invoke assets -d`.

The execution stops, but the prompt is not returned (and it doesn't seem to be in a "watch" status either).

Probably related to https://github.com/webpack/webpack/issues/424

I don't know if this is dependent on the platform, that is, Archlinux.

```
WARNING in ./~/knockout/build/output/knockout-latest.debug.js
Critical dependencies:
22:24-31 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./~/knockout/build/output/knockout-latest.debug.js 22:24-31

WARNING in ./~/knockout/build/output/knockout-latest.js
Critical dependencies:
7:222-229 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./~/knockout/build/output/knockout-latest.js 7:222-229

WARNING in ./~/markdown-it/dist/markdown-it.js
Critical dependencies:
1:522-529 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/markdown-it/dist/markdown-it.js 1:522-529

WARNING in ./~/markdown-it-sanitizer/dist/markdown-it-sanitizer.js
Critical dependencies:
1:549-556 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/markdown-it-sanitizer/dist/markdown-it-sanitizer.js 1:549-556

WARNING in ./website/addons/wiki/static/ace.js
Critical dependencies:
5:52-59 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./website/addons/wiki/static/ace.js 5:52-59

**Comment by lbanner** [comment]
@sloria ..... when you get a chance? Thanks!

**Comment by sloria** [comment]
Thanks @cosenal . Those warnings (not errors) can safely be ignored. Some of the npm packages use their minified as their "main" file, which webpack does not recommend. The knockout warnings can also be ignored; we'll see if webpack addresses that issue.

**Comment by brianjgeiger** [comment]
@sloria could we get a statement after the warnings to say that it's watching for changes, maybe with a timestamp if we wanted to go mad with power? This is the second time I've seen this confusion. The timestamp would just be for developers to be able to easily see when it's been recompiled.

**Comment by cosenal** [comment]
@brianjgeiger @sloria what is confusing that `invoke assets -d`, that is without the `w` option (i suppose it stands for watch), still doesn't terminate.

**Comment by sloria** [comment]
@brianjgeiger Not a bad idea. Will see if webpack exposes that functionality.

@cosenal That was fixed recently on `develop`. `inv assets -d` will only do a single run; `-w` must be passed to enter "watch" mode.

**Comment by cosenal** [comment]
@sloria pulling from the latest develop fixes it indeed.

Now `invoke setup` fails here: https://github.com/CenterForOpenScience/osf.io/blob/develop/tasks.py#L561
It looks like that was broken in https://github.com/CenterForOpenScience/osf.io/commit/bf12b7bcb715855ee8ebc970a5696a9f0a53e899

**Comment by sloria** [comment]
@cosenal Good catch. Fixed on `develop`.
