### ISSUE TITLE
[Enhancement] [Feature] Toolbar for files

### ISSUE THREAD

**Issue by caneruguz** [CenterForOpenScience/osf.io#2282]
There are some features and enhancements we are working on that will add functionality to files (Add folders, cancel uploads) and some others have been requested or may potentially come in the future (Delete multiple, add search box to Project Organizer) . We may need to do a general and consistent approach to Files/Folders related actions through a toolbar. 

## The problem: 
- We currently rely on inline buttons on an action column. Some folders have a few buttons but we may need the functionality when folders come; for instance rename folder. 
- We will have actions that are not specific to a row in files, for instance Cancel all Uploads, Multiple Delete
- Currently the methods used in Project Organizer (PO) and Files pages are separate. PO uses a contextually changing menu. Files uses inline buttons in an Action column. These uses need to be unified to be the same method (though not the same toolbars)

### A : Keep things as they are make best use of inline icons through the action column
- Pros: 
  * Takes less time
  * less likely to create regression errors
  * Can make use of existing notification tools
  * Current suggestion for cancel uploads can be used. 
- Cons:
  * Doesn't actually solve the problem, pushes the issue to later
  * Add folder will need to use a modal 
- **Estimated Time: 3 days** that includes
  * Finalize cancel upload design
  * Work with chris to turn Add folder into modal

### B : Use the exact same method that PO uses for contextual buttons.
- Pros: 
  * Known method, familiar to users
  * Some time to develop but not as long as C
- Cons:
  * Doesn't provide a cohesive toolbar experience, not all options are visible
- **Estimated Time: 1 week** that includes
  * Adding to Files page
  * Adding to project overview page

### C : Design new toolbar structure that will require revising PO and adding to Files. 
- Pros: 
  * Allows thinking through and unifying all actions
  * Potentially get rid of action column
  * Extendable for future
- Cons:
  * More time to develop 
  * Needs more testing
- **Estimated Time: 2 weeks** that includes
  * Adjusting Treebeard to work with the toolbar
  * Adding to Files page
  * Adding to project overview page
  * Revising Project Organizer page
  * Checking compatibility with other Treebeard instances

## Suggestions for C:

![toolbar_2](https://cloud.githubusercontent.com/assets/1314003/6783590/ea3a9808-d150-11e4-9b4e-916ea59f4eb2.png)
Edit: Added cancel buttons to search and rename to go back to toolbar.

![files_page](https://cloud.githubusercontent.com/assets/1314003/6782929/5e7999c0-d14d-11e4-8ca6-ca0443cdb99d.png)

![project_overview_page](https://cloud.githubusercontent.com/assets/1314003/6782933/6a88be4e-d14d-11e4-8792-b4166919105b.png)

Open to discussion and contributions; especially from @JeffSpies , @brianjgeiger , @lbanner and @GaryKriebel

**Comment by brianjgeiger** [comment]
I like.

**Comment by JeffSpies** [comment]
Perhaps cancel uploads does the same as search/rename--do we want multiple
actions available when canceling? It will be greyed out most of the time
anyway.

**Comment by caneruguz** [comment]
In that case Cancel Uploads would be the only thing possible to do while uploads are in progress until the user clicks X to go back to icons. 

Another idea is to go back to contextual buttons like Project Organizer and only show buttons if they can be clicked. I think combining that with the new toolbar design would still give good outcomes. So a combination of B and C.

**Comment by caneruguz** [comment]
@lbanner this suggestion is now in production so we can close the issue.
