### ISSUE TITLE
[staging & production] Malformed links on osf.io/faq

### ISSUE THREAD

**Issue by GaryKriebel** [CenterForOpenScience/osf.io#2284]
# Steps
1. Go to the FAQ on staging ( https://staging.osf.io/faq/ ) or production ( https://osf.io/faq/ )
2. Find the malformed link under the following sections:
   *  ***How can I license my data/code/etc.?***
      * Creative Commons licenses can be found [here](https://osf.io/faq/%E2%80%9Dhttps://creativecommons.org/licenses/%E2%80%9D).
   *  ***How do I create a lab group/organizational group?***
      * For an example, check out the [Reproducibility Project: Psychology](https://osf.io/faq/%E2%80%9Dhttps://osf.io/ezcuj/%E2%80%9D).

# Expected
I expect that the links would work.

# Actual
The link was stored incorrectly and each one is prefixed with _https://osf.io/faq/"_ causing the link to be malformed

**Comment by lbanner** [comment]
Aha!!!! :crocodile:
