### ISSUE TITLE
Inconsistent icons

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#2293]
Steps
-------

- Go to a component whose parent project you do not have read access to
- Go to a component whose parent project you do have read access to

Expected
------------

Both scenarios use the same icons in the project title and the navbar

Actual
--------

- The 1st scenario uses a slash as separator, e.g. "Private Project / My component"  and the "up" arrow is backwards
- The 2nd scenario uses a downward arrow as separator, and the "up" arrow is correct

![image](https://cloud.githubusercontent.com/assets/2379650/6802501/81654190-d207-11e4-853f-d53f789322d5.png)

![image](https://cloud.githubusercontent.com/assets/2379650/6802512/971b6474-d207-11e4-855c-5d8ca9043fe8.png)

**Comment by lbanner** [comment]
Reported and related in a fashion to #2184

**Comment by caneruguz** [comment]
@sloria @lbanner  PR sent.
