### ISSUE TITLE
[staging & production] Image hangover in comment pane

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2297]
# Steps
1. Go to a project
2. Open the comment pane
3. Paste this text as a comment: `![darryl](https://trello-attachments.s3.amazonaws.com/55031b6e62565b1f59d83707/600x400/72271891efe9cc3f450f1a57de9676c2/pupsicle.jpg)`
4. Press submit

# Expected
The image would stay within comment pane borders

# Actual
The image overhangs the border:
![screen shot 2015-03-24 at 1 23 20 pm](https://cloud.githubusercontent.com/assets/5975444/6808168/f8f8a668-d228-11e4-869a-48e48e0579c3.png)

**Comment by lbanner** [comment]
Interesting -- wonder what the % edge-case of photos in comments might be! But I am putting a "Hold" here for now in anticipation of #1762 -- @huangginny Did you consider using pics in comments? Thanks -

**Comment by huangginny** [comment]
@lbanner I haven't considered that, since the markdown syntax with comments are just starting to be used... I will look at it now

**Comment by huangginny** [comment]
Okay I will fix that in #1762 
I think the intended behavior is that we shrink the image so that it fits the pane size...right?

**Comment by lbanner** [comment]
I think that sounds right -
