### ISSUE TITLE
[Staging & Production] Comments: can't scroll to bottom

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2298]
## Steps
1. Go to a project
2. Open the comment pane
3. Type in several comments, so that they are past the bottom of the current comment pane
4. Scroll to the bottom, look for the buttons to edit, reply or delete the bottom comment

## Expected
The buttons for edit, reply or delete to the comment a the bottom should be visible

## Actual
The buttons for edit, reply or delete are not visible making those actions inactive.

![screen shot 2015-03-24 at 1 27 50 pm](https://cloud.githubusercontent.com/assets/9381062/6808285/9b494a08-d229-11e4-8a66-157d08663c62.png)

**Comment by lbanner** [comment]
@huangginny 's new comment code #1762 should overcome this issue -- So I am putting a "Hold" here for now - Thanks!

**Comment by huangginny** [comment]
@lbanner @nicipfeiffer Yes it does. I noticed this issue when i was upgrading the pane, and fixed it

**Comment by caileyfitz** [comment]
I am still having this problem on staging and production. This makes it impossible to reply to some comments, which is not ideal.

**Comment by lbanner** [comment]
Yeah -- I think that will exist until we get the new comment code integrated.

**Comment by samanehsan** [comment]
This is fixed in production now.
