### ISSUE TITLE
[Staging & Production] Project Settings scrolling for Mobile

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2307]
## Steps
1. Go to the project settings page of any project on the Chrome browser
2. Open the developer tools > javascript console
3. Click on the mobile icon in the tope left of the console to change the browser display configuration to mimic and iphone 5
4. Refresh to update
5. Begin scrolling down from the top

## Expected
That all menus and widgets for project settings would be visible on the page.

## Actual
The left side widget with add-on links takes the behind position on the page and as you scroll floats behind the add-on widgets.  It is never in the forefront on the page, thus cannot be used.
![screen shot 2015-03-25 at 11 28 18 am](https://cloud.githubusercontent.com/assets/9381062/6828079/1e3206a4-d2e2-11e4-9cd9-1ef65a845f94.png)
![screen shot 2015-03-25 at 11 28 28 am](https://cloud.githubusercontent.com/assets/9381062/6828083/2207c368-d2e2-11e4-8748-1c0f33d091d9.png)

**Comment by lbanner** [comment]
@caneruguz -- Your insight here, please -- Thanks.

**Comment by caneruguz** [comment]
There is a fixed placement that should be removed when window is narrower than 768 pixels. This should be an easy fix, you can assign it to me.

**Comment by ginavuu** [comment]
Wondering if this issue has been fixed? I am still experiencing this issue when my window is narrow.

**Comment by nanchen47** [comment]
This is also related to issue https://github.com/CenterForOpenScience/osf.io/issues/2314

**Comment by lbanner** [comment]
@caneruguz ?

**Comment by caneruguz** [comment]
Yes, they are related, Nan brought this to my attention last week, I will be fixing both today.

**Comment by caneruguz** [comment]
@sloria and @lbanner what's the status on this? It looks like the changes are not merged.

**Comment by lbanner** [comment]
@sloria and @caneruguz - Has this been reviewed? Can we tag w/release 0.34.0? If it is not a HotFix.
