### ISSUE TITLE
[Staging & Production] Box Add-on Share Copy 404

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2308]
## Steps
1. Go to a project you have admin privileges on 
2. Go to the project's sharing tab and add a few contributors to the project (not necessary if there are already contributors)
3. Go to the project's settings tab and authorize/import the access token for the box add-on
4. Select a folder to link to the project, confirm that the settings have updated.
5. Click the button to 'Share on box', confirm that the email addresses for the contributors on the project populate the text box that appears.
6. Click the icon to the right of the box with the email addresses to copy them to the clipboard (so then the user can click the link below to 'continue to box' to then paste the addresses to share)

## Expected
When a user clicks on the icon next to the email addresses to share on box, the icon would copy all the email addresses to the clipboard.

## Actual
Nothing happens when the icon is clicked, and there is a 404 error in the console.  No message to the user regarding the error to copy.

![screen shot 2015-03-25 at 11 50 16 am](https://cloud.githubusercontent.com/assets/9381062/6828629/300db154-d2e5-11e4-8ef8-84590b00fc46.png)

**Comment by lbanner** [comment]
OK -- Let's connect this with #2310 as the potential security concern may impact a fix being needed or not here.

**Comment by nanchen47** [comment]
This is fixed by 8dede15. The share button is no longer available on box and dropbox addon.
