### ISSUE TITLE
Email links not logged to console when running `invoke server`

### ISSUE THREAD

**Issue by lyndsysimon** [CenterForOpenScience/osf.io#2309]
h/t @cosenal for helping us find this issue on IRC.

When `USE_EMAIL` is set to `False` in `website.settings` and a new user is registered, the email that would have been sent to the user is printed to the console as part of the log output. This is important for development, as copying and pasting this link is how a developer can confirm the registration of an account on their local copy.

This log no longer prints. Upon investigation, @HarryRybacki and I discovered that while it doesn't print when the server is run through `invoke server`, it does print when it is invoke through `python main.py`. The log lever for the email is `DEBUG`, and it appears that the logger's threshold is being changed somewhere when `inv server` is run, as no logs of that level are being printed.

Since our documentation tells devs to run the OSF locally through Invoke, by running `inv server`, this issue is preventing community developers from creating and registering accounts locally.

**Comment by lbanner** [comment]
@lyndsysimon Is this new? -- Occurs to me that few times over while reviewing commenting funciton @GaryKriebel and I have been able to create + confirm accounts locally [at least for me I use `inv server`] -- I can double check as well.

**Comment by lyndsysimon** [comment]
As far as I know, yes.

I didn't track down where the log level is getting changed, so I can't say for sure. I didn't get the problem first-hand, because I use `python main.py` to run the server locally.

**Comment by sloria** [comment]
I found the source of this. I will send a patch shortly.

**Comment by GaryKriebel** [comment]
'Invoke Server' is still not logging emails to the console, though `python main.py' is.  @sloria asked me to reopen the issue and he will investigate.

**Comment by sloria** [comment]
This is due to `python-livereload`'s configuration of the root logger, which is a known issue (https://github.com/lepture/python-livereload/issues/85). I've submitted a patch to python-livereload.

**Comment by cosenal** [comment]
@sloria I will keep my PR open, I believe it's still better to import livereload only in the live mode.

**Comment by sloria** [comment]
@cosenal Merged. 

Will close this ticket once this is no longer an issue in both livereload and non-livereload modes.

**Comment by cosenal** [comment]
@sloria Great that livereload patch is already merged ;-) 
I was just having second thoughts about my PR. According to PEP8, all imports should always be put at the top of the file, see https://www.python.org/dev/peps/pep-0008/#imports

**Comment by sloria** [comment]
@cosenal Indeed, and we follow that guideline everywhere except for:

- `tasks.py`, so that invoke can be used without having all the dev requirements installed (otherwise you wouldn't be able to run `inv requirements`
- When a circular import is at play

**Comment by cosenal** [comment]
@sloria I see, thanks for clarifying this.

**Comment by nanchen47** [comment]
The fix is done and I verified this has been fixed on develop branch.
