### ISSUE TITLE
[staging & production] Potential security issue exposing email addresses with 'Share on Box' option

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2310]
# Steps
1. Go to a project where you are an admin
2. Add contributors to the project
3. Go to the project settings page
4. Enable Box and Dropbox for the project
5. Configure Box and Dropbox for the project by selecting folders to link
6. Next to the 'Change' buttons to select a different folder, press the 'Share on Box' button

# Expected
I'm not really sure that I even expected that this could be an option...

# Actual
Pressing the 'Share on Box' button opens a field that is pre-populated by all the contributors' email addresses. This could be a potential security issue. For example, suppose I wanted to know Brian Nosek's email address. I can add him as a contributor on my project (since he does not need to approve this) and then press the 'Share on Box' button to see the email address that he has associated with his OSF account. I could theoretically add every OSF user as a contributor on my project, press the 'Share on Box' button to get all of their emails, and then remove them all as contributors, and they would have no idea that anything even happened (because confirmed users do not get notifications when they are added/removed from projects).

**Comment by lbanner** [comment]
Good catch @caileyfitz -- I think @mfraezz worked on this -- But maybe @samchrisinger can provide feedback/insight here?

**Comment by sloria** [comment]
Let's just remove the Share button for now. I'll send a hotfix shortly.

@samchrisinger Can you update #2014 to remove the "Share" UI?

**Comment by samchrisinger** [comment]
Will do
