### ISSUE TITLE
[Staging & Production] Project Settings scrolling for Reduced Browser Windows overlaps footer on page

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2314]
## Steps
1. Go to the project settings page of any project 
2. Open the developer tools > javascript console OR resize the browser window  to be short in vertical
2. Begin scrolling down from the top

## Expected
The left side widget with links to select/configure settings would not extend past the page footer when the browser window is reduced in the vertical axis to overlap into the footer and the bottom of the page.

## Actual
The widget scrolls into the footer and overlaps it's links and text with the footer's links and text.

![screen shot 2015-03-25 at 12 20 26 pm](https://cloud.githubusercontent.com/assets/9381062/6829365/6b0afd44-d2e9-11e4-8452-88ea7d31f7f3.png)
![screen shot 2015-03-25 at 12 20 48 pm](https://cloud.githubusercontent.com/assets/9381062/6829368/6e90e5a0-d2e9-11e4-9885-933dfd80f046.png)

**Comment by ginavuu** [comment]
This is happening to me too when browser has been re-sized.
