### ISSUE TITLE
[staging & production] SHARE: Table of provider results obscures points on graph

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2328]
# Steps
1. Go to the SHARE page on staging or production
2. Search for a single asterisk *
3. Hover over the SHARE graph below the search bar
4. Starting at the left, move your mouse to the right to view the table of provider results for each set of data points

# Expected
I expect that as the user moves his cursor to the right, the table of results would shift so that the line highlighting the data points would be visible.

# Actual
The table of provider results obscures the points on the right-side of the graph. 
![screen shot 2015-03-26 at 1 22 24 pm](https://cloud.githubusercontent.com/assets/5975444/6853118/7171e3a6-d3bf-11e4-9282-ceba8747bd07.png)

I drew a dotted line where the actual line is behind the provider table. Ideally, this line would be visible.

**Comment by samanehsan** [comment]
Closing, since there is no longer a table of provider results being shown. Instead, there's just one provider shown when you hover over a data point: 
![screen shot 2015-06-18 at 10 34 12 am](https://cloud.githubusercontent.com/assets/6414394/8233699/bbb6c81e-15a5-11e5-8a5e-120854a3ff15.png)
