### ISSUE TITLE
[Staging & Production] SHARE: Pie chart filter for contributor list leaves null results

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2330]
## Steps
1. Go to the SHARE page on staging or production
2. Search for a single asterisk *
3. Click on a provider on the pie chart to the left of the graph to filter your results to only show that provider
3. Hover over the SHARE graph below the search bar

## Expected
Since the results are being filtered for only one provider then the provider table that moves with the curser over the graph should only show the filtered provider.

## Actual
The provider table shows the list of all providers with '0' for all of the providers except for the one the user selected on the pie chart to filter.  Also, you cannot scroll to the bottom of the provider table on the graph to see the entire list.  There is no way to click on it to keep it in focus to then scroll on it.

![screen shot 2015-03-26 at 3 24 12 pm](https://cloud.githubusercontent.com/assets/9381062/6855149/34fdf0ba-d3cc-11e4-8ae5-34e487f14c47.png)

**Comment by samanehsan** [comment]
Closing, since this has been resolved on production: 
![screen shot 2015-06-18 at 10 05 12 am](https://cloud.githubusercontent.com/assets/6414394/8233018/dee39488-15a1-11e5-9782-bc88032db876.png)
