### ISSUE TITLE
[Staging & Production] Graph blank when results published longer than 3 months ago

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2332]
## Steps
1. Go to the SHARE page on production
2. Enter 'nosebleed' into the search query

## Expected
The graph of events would update showing the events from the search. Updating the x-axis from 'Last 3 months' to index a longer length of time to include the search results.

## Actual
The graph retains the length of time of 'Last 3 months' and is blank.

![screen shot 2015-03-26 at 4 13 38 pm](https://cloud.githubusercontent.com/assets/9381062/6855969/1a1c70a8-d3d3-11e4-91dd-a13cd466422d.png)

**Comment by nanchen47** [comment]
The released data on this event is 2014-11-04 and the other one is 2014-10-29, which is more than 3 months ago. I assume this is the right behavior since there are actually no event going on in the last three months. @nicipfeiffer @erinspace

**Comment by lbanner** [comment]
@erinspace -- Can you provide insight on whether this is an issue or not? Thanks.

**Comment by nanchen47** [comment]
Will be addressed in @bdyetton 's search page ui update.
