### ISSUE TITLE
[staging & production] SHARE graph percentages overhang

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2335]
# Steps
1. Go to the share page on staging or production
2. On production, search for 'experiment'
3. On staging, search for 'converse'
4. Look at the pie charts for each query

# Expected
I expected that the percentages in the pie chart would be fully visible and easy to read. 

# Actual
The percentages frequently overhang the colored part of the graph, making them difficult or even impossible to read. 

Search for 'experiment' on production:
![screen shot 2015-03-27 at 9 30 56 am](https://cloud.githubusercontent.com/assets/5975444/6868708/31d37f16-d464-11e4-85cb-140f162281b6.png)
The 42 looks like a 12. 

Search for 'converse' on staging: 
![screen shot 2015-03-27 at 9 29 41 am](https://cloud.githubusercontent.com/assets/5975444/6868726/52e467ec-d464-11e4-9c50-45bc5505d30f.png)
The 56 is hard to read and the 5.0%s overhang the other colors.

**Comment by caileyfitz** [comment]
@erinspace @fabianvf Realized that I should have tagged you guys. Also... I may have put this in the wrong repo?

**Comment by fabianvf** [comment]
No, this is the correct repo. We will address this in the next few days. Erin has an incremental graph improvement PR up already. I don't think it addresses this issue though.

**Comment by caileyfitz** [comment]
Okay, great! Thanks, @fabianvf

**Comment by GaryKriebel** [comment]
@erinspace or @fabianvf ... is this still happening?

**Comment by PatrickEGorman** [comment]
Just noticed this myself.  Seems like a pretty important bug to fix

**Comment by erinspace** [comment]
@GaryKriebel @fabianvf this is now updated in production, this issue can be closed

**Comment by erinspace** [comment]
Just a note - the labels still overhang when the screen is a medium size - this is a c3 issue and we are not going to touch this until we redo the visualization completely sometime in the future
![screen shot 2015-06-02 at 3 27 32 pm](https://cloud.githubusercontent.com/assets/801594/7945003/0caa9ab4-093c-11e5-8f5e-162dcf8699a2.png)
