### ISSUE TITLE
Sluggish scrolling in file browser

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#2341]
### Steps 

- Go to the files tab on a project with lots of files
- Scroll through the filebrowser at a reasonably quick speed

### Expected

Scrolls smoothly

### Actual

Scrolls partly down the filebrowser, stops, then the whole page scrolls down, causing the page to jitter.

![issue](https://cloud.githubusercontent.com/assets/2379650/6870824/dab6ec84-d474-11e4-9e7b-1028dbff43f9.gif)

**Comment by lbanner** [comment]
This in your wheelhouse @caneruguz ?

**Comment by caneruguz** [comment]
@sloria can we consider this fixed?

**Comment by sloria** [comment]
Yes.
