### ISSUE TITLE
Very sluggish dropbox add-on

### ISSUE THREAD

**Issue by csoderberg** [CenterForOpenScience/osf.io#2343]
After I have authorized dropbox on a project and imported and access token, the subfolders of my dropbox never appear. I let it go for two minutes, and they still had not appeared, only the top dropbox folder had appeared (see attached image for what it looked like at the 2 minute mark). This was in safari. Other add-ons, like github, seem to be working fine. I'm not sure if this is just due to the size of my dropbox folder (5.84GB), or if something else is going on. 

![screenshot 2015-03-27 13 00 50](https://cloud.githubusercontent.com/assets/7332030/6872805/fd0c989e-d481-11e4-9394-561e545022e1.png)

**Comment by nanchen47** [comment]
@chrisseto any idea on this issue?

**Comment by chrisseto** [comment]
@csoderberg Link to the project please

**Comment by csoderberg** [comment]
It happens on any project I try it on, but here is one example:
https://osf.io/5hj4a/

On Fri, Apr 3, 2015 at 12:11 PM, Chris Seto <notifications@github.com>
wrote:

> @csoderberg <https://github.com/csoderberg> Link to the project please
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/issues/2343#issuecomment-89339315>
> .
>



-- 
Courtney Soderberg, Ph.D
Statistical and Methodological Consultant
Center for Open Science

**Comment by chrisseto** [comment]
@csoderberg Looks like Dropbox isn't linked to that project.

**Comment by csoderberg** [comment]
Right, after I de-authorized the the dropbox add-on since the folders never
loaded I just went ahead and unlinked dropbox entirely, since that's the
project i use for workshops and try to keep it clean. I just re-linked it.

On Mon, Apr 13, 2015 at 9:13 AM, Chris Seto <notifications@github.com>
wrote:

> @csoderberg <https://github.com/csoderberg> Looks like Dropbox isn't
> linked to that project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/issues/2343#issuecomment-92346890>
> .
>



-- 
Courtney Soderberg, Ph.D
Statistical and Methodological Consultant
Center for Open Science

**Comment by chrisseto** [comment]
Have you selected a folder as well?

**Comment by chrisseto** [comment]
@nanchen47 Resolved with @csoderberg, can you close this?
