### ISSUE TITLE
[production] Mendeley citation view shows an error when not logged in, but works when logged in

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#2350]
Project: https://osf.io/y5gr9/

Shows this in anonymous mode:

![screen shot 2015-03-30 at 9 21 50 am](https://cloud.githubusercontent.com/assets/1761504/6897013/a17a5a5e-d6be-11e4-93db-38b361b568f9.png)

And this when logged in:

![screen shot 2015-03-30 at 9 25 13 am](https://cloud.githubusercontent.com/assets/1761504/6897032/b3ec1d94-d6be-11e4-8269-0e9df076ec81.png)

**Comment by bnosek** [comment]
I replicated issue reported by a user using Chrome.  User reports that problem occurred on Chrome, IE, and Firefox.

**Comment by lbanner** [comment]
Thank you @bnosek -- @nicipfeiffer or @caileyfitz -- can you please do a double check replication on this? Also pinging @lyndsysimon and @samchrisinger for consideration of fix. Thanks.

**Comment by samchrisinger** [comment]
I can take this issue if someone wants to assign it to me.

**Comment by lbanner** [comment]
You go it, @samchrisinger - TY

**Comment by caileyfitz** [comment]
Verified this is an issue

**Comment by sloria** [comment]
Fixed by @samchrisinger
