### ISSUE TITLE
[staging & production] long wiki page on project overview

### ISSUE THREAD

**Issue by jeg3tw** [CenterForOpenScience/osf.io#2351]
# Steps
1. Go to https://staging.osf.io/spedc/

# Expected 
The wiki widget would truncate the wiki contents to end at about the same place that 'Recent Activity' ends.

# Actual
The wiki widget extends far beyond that.

![](https://trello-attachments.s3.amazonaws.com/55145d5ea152815a90633066/1440x900/b53aa6f31fb59ae781e18ff81d52b1cc/2015-03-26_15_31_44.gif)

*The cut off is based on how many characters (or maybe words) that you have in the markdown source. So if you have things that are bigger than their source characters, such as images, tables of contents, math, or videos, they will cause a larger wiki preview box to appear.*

**Comment by lbanner** [comment]
I set this as 'low' given likelihood that someone *might* use in such a fashion i.e. large  items in the Home Wiki. But pinging @brianjgeiger and @caneruguz on this for now - just in case.

**Comment by brianjgeiger** [comment]
Easy fixes, and has always been possible. It's a question of whether we want to give people the ability to do this or we want to ensure that the widgets are size-restricted. I have no firm preference on this, but I think organizationally we are currently leaning towards a consistent project summary page.

The proper fix is to set the max-height for the widget and hide the overflow.

**Comment by lbanner** [comment]
:+1: on your approach from my pov @brianjgeiger -- I tagged with 'discuss' in case of any dissension in the ranks -- and am handing to you.

**Comment by brianjgeiger** [comment]
Not that I couldn't handle this quickly, but this is a good one for someone who is just starting out on the OSF and wants a quick introduction to the process. It might be good to save it for a new intern or similar.

**Comment by caneruguz** [comment]
One point on that, several widgets do their own sizing, the logs paginate now and treebeard has a fixed height. So I think it's not wrong to expect wiki widget panel doing it's own sizing.

**Comment by caneruguz** [comment]
@nanchen47 @brianjgeiger any news on this?

**Comment by chennan47** [comment]
@caneruguz isn't this a site-wide problem that the redirect always cut-head. I remembered you did some pr to fix the problem on the other place. Not sure about the wiki

**Comment by brianjgeiger** [comment]
Nobody's chosen to work on this yet. It'll still be a pretty easy one, but I don't think anyone's touched it.

**Comment by raklein** [comment]
So in trying to create the front page for the Many Lab we found it a little difficult to work with this hard height restriction. My preference as a user would be one of the solutions below:
(1) instead of "..." truncating the content, there could be a "[read more]" link that expanded the wiki to show the full content (directly on that page). Or, that could link them to the full wiki (this strikes me as more intuitive than clicking the arrow in the corner, although users may not want to be taken off the overview page).
(2) give the admin of the project the ability to customize the height displayed on the front page through drag and drop or by setting a limit in the wiki editing page
(3) alternatively, simply increasing the max height might resolve most of these frustrations

**Comment by cebersole** [comment]
I echo Rick's concerns.  I don't think that the arrow in the corner of the box is the most intuitive.  If you want to keep the box consistent across pages (and I see some value in that) the "read more" button that Rick references above seems like a pretty easy fix to this issue.  For the Many Lab, people will need to read longer entries on the Wiki, so having an easy way for folks to find that content would be very helpful.

**Comment by cebersole** [comment]
To be more specific, I would suggest that the "read more" button take people directly to the wiki page, and not expand the box on the project homepage.  This would maintain consistent formatting on home pages and get people to wiki content quickly.
