### ISSUE TITLE
[staging & production] multiple tooltips on IE

### ISSUE THREAD

**Issue by jeg3tw** [CenterForOpenScience/osf.io#2352]
# Steps
1.  Open IE
2.  Go to a project 
3.  Authorize several add-ons so that folders are displayed
4.  Download a file
5.  Return to the files page
6.  Hover over another file

# Expected
Tooltips would only display on hover and disappear after the mouse moves off.

# Actual
Tooltips are displayed long after the mouse moves off, they also moves from item to item (like hover on the download button and 'download' tooltip appears, then move to mouse to hover over a file name 'view file' tooltip should appear, but download is still showing and also view file will also appear)

![](https://trello-attachments.s3.amazonaws.com/55160630a780c78fde1b37a4/1440x900/6b1d50db89e9cd99728222d4be2a70f7/Screen_Shot_2015-03-27_at_9.33.20_PM.png)

**Comment by lbanner** [comment]
Insight @caneruguz + @brianjgeiger ?

**Comment by chennan47** [comment]
@caileyfitz I tried on IE 11 Windows 8.1. Can't repo this problem. Can you verify this problem still exist? Thanks.

**Comment by caileyfitz** [comment]
@nanchen47 Actually I talked with Caner about this and I think it was a caching issue.

**Comment by caneruguz** [comment]
Is this still happening?

**Comment by chennan47** [comment]
@caneruguz I tried again on IE11 on windows 8.1. This problem doesn't happen. Close it for now
