### ISSUE TITLE
[staging & production] two factor deauthorization button

### ISSUE THREAD

**Issue by jeg3tw** [CenterForOpenScience/osf.io#2354]
# Steps
1.  Go to user settings
2.  Go to configure add-ons
3.  Under security, check "two-factor authorization"
4.  Hit submit
5.  Authorize two-factor
6.  Now attempt to deauthorize add-on 

# Expected
There will be an option to deauthoirze.

# Actual
The only way to de-authorize the two-factor is by unchecking the add-on option and hitting submit in which you get a message reading "successfully deauthorized two-factor..."

![screen shot 2015-03-30 at 10 13 56 am](https://cloud.githubusercontent.com/assets/9021353/6898396/064f12fe-d6c8-11e4-9f01-155cc1334fe2.png)

![screen shot 2015-03-30 at 10 21 21 am](https://cloud.githubusercontent.com/assets/9021353/6898393/04eb5666-d6c8-11e4-95eb-d375b4240ac8.png)

**All other add-ons have this option. See figshare above.*

**Also, should we require the two-factor code to deauthorize it? @lyndsysimon*

**Comment by chennan47** [comment]
talked with @lyndsysimon, it doesn't make sense to have a button to deauthorize twofactor and the only way to deauthorize this addon should be to remove this addon. But probably we can add link there to remove the addon. Thoughts @brianjgeiger @lbanner @sloria @GaryKriebel

**Comment by brianjgeiger** [comment]
From a UI Standpoint, make sure it's consistent, which may just mean having a "Disable two factor authentication" in the same place that a "Deauthorize Github" link might show.

**Comment by brianjgeiger** [comment]
That's presuming it's presented in the same way. I may change my mind when I have a chance to look over the current workflow.

**Comment by lbanner** [comment]
Yes -- agree it is needed and agree with consistency .. and this possible approach from @brianjgeiger  .. a "Disable two factor authentication" in the same place that a "Deauthorize Github" link might show.

**Comment by lyndsysimon** [comment]
:+1: on adding a button that deactivates the addon.
