### ISSUE TITLE
[staging & production] Redirected to another page for incorrect email

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2355]
# Steps
1. Go to either staging or production
2. If you are logged in, sign out 
3. In the navbar, click the 'Forgot Password?' link
4. On the Forgot Password page, enter an email that is not in the database (a way to do this would be to change one letter of your email)
5. Press 'Reset Password'

# Expected
I expect that the user should get an error message saying that the email is not found and stay on the Forgot Password page so that the user can enter his/her correct email. 

# Actual
The user receives the error message but is redirected to the login page: 
![screen shot 2015-03-30 at 2 40 49 pm](https://cloud.githubusercontent.com/assets/5975444/6903806/ca27d590-d6ea-11e4-888b-252c507dc763.png)

 @HarryRybacki said that this is because when something interacts with the database (checking if the email belongs to an OSF user), it automatically redirects to the login page. I think it is more intuitive for the user to remain on the page that he/she was originally on and receive the error, rather than being redirected away from the page and having to press another button to return.

**Comment by HarryRybacki** [comment]
This is an interesting point of discussion. There are two ways to do handle incorrect email/usernames submitted to a *Forgot my password* service.

1. Quietly fail. E.g., tell them the account information associated with notARealEmail@pewpew.com has been sent there. 
2. Inform the user that notARealEmail@pewpew.com is not registered with the site and allow then to try again.

The former is more inline with best security practices. By silently failing we aren't accidentally informing a potential attacker if the account actually exists or not. With the latter the user has more information but as I just stated, we can leak potentially sensitive information by leaving this vector open. I'm going to defer this to @sloria, @JeffSpies, and the community team for a decision as it has potentially serious ramifications. I'm happy to patch in whatever way we opt for as a team though.

**Comment by JeffSpies** [comment]
It should quietly fail, and the message should indicate that they will only
be receiving an email if it was a valid account. If they dont' receive an
email, and believe they should, contact support at osf.

J.

**Comment by lbanner** [comment]
Sounds right -- @HarryRybacki is this in your realm to be able to pick up?

**Comment by HarryRybacki** [comment]
@JeffSpies -- I thought that was what you'd say but wanted to make sure. @lbanner I'll throw it into the queue. Priority level?

**Comment by lbanner** [comment]
Gave it a 'Medium' dependent upon your Epic work priorities -- but it's security concern, to me, makes it a worthwhile change to get deployed. TY.

**Comment by JeffSpies** [comment]
If it's production, it needs to change now.

**Comment by HarryRybacki** [comment]
Rodger, shifting priorities.

**Comment by lbanner** [comment]
Got it --"High" -- appreciate it @HarryRybacki

**Comment by nanchen47** [comment]
![screen shot 2015-04-02 at 9 35 59 am](https://cloud.githubusercontent.com/assets/11743657/6964939/cb5efbcc-d91b-11e4-8a8b-85a227020a5b.png)
This has been fixed on production.
