### ISSUE TITLE
[Box][Figshare] File breadcrumbs should match file path 

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#2356]
Steps
--------
1) Configure the figshare addon for a project 
2) View a figshare file
3) Repeat with the box addon

Expected
-------------
I expect the breadcrumbs to say `<OSF Project Name> / figshare / <filename>`  or `<OSF Project Name> / Box / <filename>` like with the other addons. 

E.g. github breadcrumbs: 
![screen shot 2015-03-30 at 10 45 24 am](https://cloud.githubusercontent.com/assets/6414394/6898778/01dd3ba4-d6ca-11e4-9709-8d148be11e2e.png)

Actual
---------
For figshare files, it looks like the project and file ids are included in the path instead of their names. 
![screen shot 2015-03-30 at 10 41 03 am](https://cloud.githubusercontent.com/assets/6414394/6898659/5c06f42c-d6c9-11e4-9238-7419c3a5e638.png)

For Box, it seems to be including the id of the linked folder in the path instead of its name: 
![screen shot 2015-03-30 at 10 39 16 am](https://cloud.githubusercontent.com/assets/6414394/6898588/13479124-d6c9-11e4-8b83-0d2c93b366c4.png)

Solution
-----------
Use folder and file names instead of their ids in figshare and box file paths.

**Comment by lbanner** [comment]
Although a good point, I wonder if this is just default to how Figshare manages data path and naming - and we just pull from them (?) -- I'll ask @chrisseto this one?

**Comment by chrisseto** [comment]
This has been addressed before by @nicipfeiffer.
The numeric structure is how figshare and box handle pathing of files.

A nice fix for this would be to build the full path from the file grid when it gets added to the page.

**Comment by lbanner** [comment]
Nice fix? Not too difficult a fix? Your wheelhouse, @chrisseto, kind of fix if we decide to undertake?

**Comment by chrisseto** [comment]
That would be a question for @samanehsan, who is working on the file grid integration.

**Comment by lbanner** [comment]
OK -- @samanehsan -- post your current work, we can discuss :smiling_imp:

**Comment by samanehsan** [comment]
Sounds good @lbanner!

**Comment by nicipfeiffer** [comment]
This is the issue @chrisseto is referring to https://github.com/CenterForOpenScience/osf.io/issues/2221. Referencing it here for any additional info it can provide.

**Comment by samanehsan** [comment]
Thanks @nicipfeiffer! @chrisseto, I looked into this earlier and I can't pull the path off of the grid because of lazyloading. Instead, I think the path with all of the folder/file names will have to be constructed on the backend.

**Comment by nicipfeiffer** [comment]
With the release to Dataverse 4.0 the file path for dataverse files has been changed to be like above.
Reported on the 0.33 Trello Testing board by QA:
## Steps
1. Click to view a dataverse file
2. Look at the breadcrumb information

## Expected Prior to the Release of Dataverse 4.0
The breadcrumb should give the user information about the file.  On production the breadcrumb path is:
Projectname / Dataverse / Filename

![dataverse](https://cloud.githubusercontent.com/assets/9381062/7253659/40d4d6d4-e80c-11e4-8131-3f838e853350.png)


## Actual After the Release of Dataverse 4.0
The breadcrumb is not giving any useful information to the user.  Currently the path is: 
Projectname / dataverse / some number

![screenshot 2015-04-21 09 53 44](https://cloud.githubusercontent.com/assets/9381062/7253663/50c62b7e-e80c-11e4-9c7d-05b28258201c.png)


@rliebz commented:
According to @chrisseto  , the ability to change breadcrumbs will not be available until CenterForOpenScience/osf.io: Pull Request #2327 is merged in.

**Comment by chrisseto** [comment]
Extra note: Most if not all path related issues, breadcrumbs and logs, will be resolved with the addition of moving/copying.

**Comment by lbanner** [comment]
OK .... moving/copying is in an upcoming release. How about we HOLD on this for now .... until then.

**Comment by samanehsan** [comment]
As an update, this has been fixed in box:
![screen shot 2015-06-03 at 2 11 59 pm](https://cloud.githubusercontent.com/assets/6414394/7967842/d96ed25e-09fa-11e5-8ecb-fe584419eed8.png)

But figshare still has file ids instead of the file name: 
![screen shot 2015-06-03 at 2 15 20 pm](https://cloud.githubusercontent.com/assets/6414394/7967864/079568c8-09fb-11e5-84bc-5d49c69b7abd.png)

**Comment by samanehsan** [comment]
I'm removing the "hold" tag now that we have moving/copying

**Comment by nicipfeiffer** [comment]
@samanehsan It looks like with the release of 0.38 there will no longer be any breadcrumbs for files. @chrisseto is this correct?

**Comment by chrisseto** [comment]
@nicipfeiffer Yes, you are correct. We're relying on the file tree expanding and highlighting the current file.

**Comment by lbanner** [comment]
OK -- Yes -- I will close this @samanehsan
