### ISSUE TITLE
Long load times on first visit to osf.io

### ISSUE THREAD

**Issue by billyhunt** [CenterForOpenScience/osf.io#2357]
Steps
-------
1.  Log out of osf.io
2.  Clear your cached data from a browser.
3.  Go to or reload https://osf.io
4.  Repeat steps 1-3 until the error occurs.  (Sometimes it happens every other time, at others, one time in ten)

Expected
------------

The page should load within 10 seconds for first time users with no cached data.

![screenshot 2015-03-30 11 26 57](https://cloud.githubusercontent.com/assets/6232068/6899614/b8b9f52e-d6cf-11e4-9107-410a8ccfa50d.png)

Actual
--------

When going to osf.io for the first time (no cached data), there can be load times longer then 30 seconds.  It doesn't happen every time, so multiple attempts to recreate might be necessary.  I have seen the behavior in Chrome, Firefox, and Safari (mostly Firefox and Safari).  While the page is hung, the message that is visible to users  is "Transferring data from code.jquery.com" 

![osf io long load times](https://cloud.githubusercontent.com/assets/6232068/6899660/f5dc67de-d6cf-11e4-8d35-06d3b45d5fd0.png)

Occasionally (but not always), after the extended wait, the following errors appear in the terminal:

ReferenceError: jQuery is not defined
        jquery-ui.min.js (line 5, col 1)
TypeError: window.jQuery is undefined
	osf.io (line 47)
ReferenceError: jQuery is not defined
	vendor....f34b.js (line 1, col 3731)
TypeError: o.support is undefined
	base-pa...a28c.js (line 9, col 744)

![screenshot 2015-03-30 11 12 00](https://cloud.githubusercontent.com/assets/6232068/6899704/2b74b32e-d6d0-11e4-8bff-62675855299d.png)

**Comment by lbanner** [comment]
Ping @sloria for followup/Insight on this as well -- TY

**Comment by sloria** [comment]
Yes, looks like one of more of the servers on the CDN from which we download jquery and jquery-ui is being sluggish. 

We can certainly just add jquery and jquery-ui to our vendor bundle. We might lose out on the caching benefit of the CDN, but that is probably outweighed by the reliability and reduced roundtrips of serving the assets ourselves.

Will send a patch soon.
