### ISSUE TITLE
[Production] Let's Brand [OSF frame] the Log-in page

### ISSUE THREAD

**Issue by lbanner** [CenterForOpenScience/osf.io#2358]
# Current

Page is here: https://osf.io/login/

![screen shot 2015-03-30 at 11 55 59 am](https://cloud.githubusercontent.com/assets/2964829/6900358/f3e7f53e-d6d3-11e4-8cb5-5c0e75debe62.png)
# Desired
This log-in screen should have OSF branding/Page framing, rather then the mysterious floating along look.

**Comment by lbanner** [comment]
@HarryRybacki -- Can you make this improvement?

**Comment by HarryRybacki** [comment]
This was done explicitly. Single use forms (e.g. log in, forgot password, and two factor) look like this. This was also brought up by a UX person in town. I wouldn't be opposed to changing the color scheme of these forms to match the navbar though. Much more than that would be time inefficient for me as styling is pretty far from my realm of knowledge.

**Comment by lbanner** [comment]
OK -- @JeffSpies raised as legitimate concern from a brand/recognized log-in security concern, so I will tag w/'discuss' -- and ping @caneruguz on the UI/UX.

**Comment by JeffSpies** [comment]
Let me check out that document. The feel is off too me. I felt like I was
getting phished.

**Comment by HarryRybacki** [comment]
We can make everything more congruent with the rest of the site but we don't want the overhead of a complete navbar and footer. Again, we should have discussed this stuff pre-release =/

**Comment by JeffSpies** [comment]
We did discuss this. Either way, I can't see evidence of unbranded forms
being recommended in the document.

Getting that template hot-fixed would be fine.

**Comment by HarryRybacki** [comment]
Okay, I've got the security related changes prepped in my mind. How do we want to change the template to match our branding?

**Comment by JeffSpies** [comment]
The simple thing would be to just throw the form in the body of the base
mako template--like create account/sign-in but with just one form.

**Comment by HarryRybacki** [comment]
Alright

**Comment by caneruguz** [comment]
As Harry said there are many examples of these types of pages being relatively barren; the reason is they are focused actions, the goal is not conversation or distraction but getting the process completed. 

I can see why Jeff thought it looks off, because it is different than other pages. I think Github is hitting a good balance and we could follow their example:

![screen shot 2015-03-30 at 12 26 23 pm](https://cloud.githubusercontent.com/assets/1314003/6900967/0a645524-d6d8-11e4-9628-e8111dd9c2ef.png)

**Comment by HarryRybacki** [comment]
Thanks @caneruguz -- I'm adding an OSF themed panel class to our CSS and testing out the look
