### ISSUE TITLE
Unexpected CSS Token on First Load in Safari

### ISSUE THREAD

**Issue by billyhunt** [CenterForOpenScience/osf.io#2361]
Steps
-------
1. Log our of OSF.io
2.  Clear cache in Safari
3.  Open Console
4.  Go to https://osf.io

Expected
------------

![screenshot 2015-03-30 14 01 45](https://cloud.githubusercontent.com/assets/6232068/6903011/792e9c6e-d6e5-11e4-95e3-66b7347e68b2.png)

Actual
--------
There are some CSS Javascript warnings on the first load of osf.io in Safari.  They do not occur after the initial load.

[Warning] Unexpected CSS token: : (bootstrap.min.css, line 5, x3)
[Warning] Invalid CSS property declaration at: * (select2.css, line 10)
[Warning] Unexpected CSS token: : (select2.css, line 55)
[Warning] Unexpected CSS token: : (select2.css, line 71)
[Warning] Unexpected CSS token: : (select2.css, line 204)
[Warning] Unexpected CSS token: : (select2.css, line 309)
[Warning] Unexpected CSS token: : (select2.css, line 321)
[Warning] Unexpected CSS token: : (select2.css, line 585)

![screenshot 2015-03-30 13 32 19](https://cloud.githubusercontent.com/assets/6232068/6903035/9cc1101c-d6e5-11e4-83c9-283fd4f969d9.png)

**Comment by lbanner** [comment]
I tagged "low" as this doesn't appear to impact user experience, but we shouldn't be throwing errors -- ping @caneruguz for insight?

**Comment by caneruguz** [comment]
These are all from libraries that we use but they are not our own css; plus the errors themselves are still legitimate css, Safari's evaluation is not very accurate, it refers to an edge use of css. 

These are not really errors we can do anything about, so I think we can close this issue.

**Comment by lbanner** [comment]
OK -- appreciate the feedback -- There any better way to approach use of libraries not owned by us? - or generally, is it to be expected that certain browsers will handle CSS and os 'errors' differently?

**Comment by caneruguz** [comment]
Not really, we don't want to touch library code unless it's a version we have forked, but that's very rare. 

CSS; we can easily override if necessary; but  this is not a case where we need to intervene. I think the best process is to err on the side of creating the issue or notifying developers; we can then eliminate what is not actionable.
