### ISSUE TITLE
Remove "previous" from version view options

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2362]
**Steps**
1. Visit a wiki with more than two versions
2. In the top right of the display frame, there is a dropdown that has "current" selected. Click on the dropdown and view the options.

**Outcome**
1. The version that was last instantiated is listed as "previous" and all of the other preceding ones are numbered in the dropdown. For example, in a case where there are three versions of the wiki, the 3rd version is listed as current, the second as previous, and the first as Version 1.
![screen shot 2015-03-30 at 1 38 24 pm](https://cloud.githubusercontent.com/assets/4965832/6902514/5a6a45ce-d6e2-11e4-9881-6764ca896fca.png)

**Expected**
1. Only the current version should not be numbered. For example, if there are three versions of the wiki, the 3rd version would be listed as current, the second as Version 2, and the first as Version 1.

**Comment by brianjgeiger** [comment]
The reason for this is that Previous is a useful shortcut for comparisons. As a general rule, you're probably always going to want to compare the current version with the previous version.

That being said, when we implemented it, it was originally going to have the versions listed and previous would be along with, so you'd have version 1, version 2, version 3, previous, current, and preview, where 2 would equal previous and 3 would equal, but that seemed weird, so we simplified.

From a consistency standpoint, each column has a "natural" default (edit is Preview, View is either Current or Preview depending, and compare is Previous).  I'm trying to remember if there's some complication with the view model or similar if we ditched the Previous label, and I'm not sure, so hopefully no.

Is there a particular reason not to have "Previous" as a version?

**Comment by jlcohoon** [comment]
If you're looking at the project logs, it can say that you updated to
version 5. But if you look at the dropdown in the wiki view, it only lists
up to 3, which is confusing at first. If the versions are in chronological
order, won't the version with the greatest number always be the previous
version? Meaning that it's still easy to compare current to the previous
(highest numbered) version?

**Comment by brianjgeiger** [comment]
So comparing with the logs is weird. I can see that. We might be able to do something like:
```
Preview
Version 5 (Current)
Version 4 (Previous)
Version 3
Version 2
Version 1
```
Or, of course, we could ditch the Previous altogether as an identifier. The main reason to keep it is because it does show up in the URLs that can be shared, and there's no real indication of what Previous means if it's not listed in the UI somewhere. And we could still honor previous and no longer put it in the URL. 

I think I, personally, like the version above, though I don't know if it's strictly necessary.

**Comment by lbanner** [comment]
:+1: ... With no other context, I can see it's not clear that 'Version 5' is current and 'Version 4' is most recent i.e. previous.
