### ISSUE TITLE
[staging & production] Search bar occluded with certain screen sizes

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2363]
# Steps
1. Go to either staging or production
2. Log out of whichever site you are on
3. Press the magnifying glass to open the search bar
4. Resize the screen to be at a width between 768 and 991 pixels

# Expected
I expect that no matter what the screen size, the green search bar should be visible.

# Actual
Between these screen widths, the navbar obscures the search bar: 
![screen shot 2015-03-30 at 2 40 01 pm](https://cloud.githubusercontent.com/assets/5975444/6903792/b1265652-d6ea-11e4-8c16-a593cfbaeca5.png)

**Comment by caileyfitz** [comment]
Tagging @caneruguz here for input.

**Comment by caneruguz** [comment]
Yes the expectation is correct. This size issue happens between certain intervals which is a small amount of possible size but it needs to be addressed.  @HarryRybacki might have suggestions or fixes for this, if not I can take a look as well.

**Comment by HarryRybacki** [comment]
@lbanner I chatted with @caneruguz about this. It'll be a quick fix if he's assigned to it. Otherwise I'll get to it when I have a few hours to learn up on this stuff and hack it it for a bit.

**Comment by nanchen47** [comment]
The fix by @caneruguz has been merged and deployed. Checked on production. This problem doesn't exist anymore.

**Comment by lbanner** [comment]
:+1: Thanks all.
