### ISSUE TITLE
[staging & production] Inconsistencies with guids of figshare files

### ISSUE THREAD

**Issue by huangginny** [CenterForOpenScience/osf.io#2364]
**Steps**
Prereq: Make sure you have a figshare project, and have a folder inside this project, and then have a file inside this folder
1. Link your OSF project to your figshare project
2. Open the file and make note of the GUID
3. Change the link so that your OSF project links to the figshare folder, not the project
4. Open the file again and make note of the GUID

**Expected**
Two GUIDs should be the same

**Actual**
They are not the same. This means that two GUIDs are used for the same file

**Comment by nanchen47** [comment]
There is no way to compare those two files since they are in two different folder in the third party service. I think the behavior is right. The files should have 2 different GUID. @chrisseto @sloria @brianjgeiger Thoughts?

**Comment by nanchen47** [comment]
Talked with @chrisseto , this should no longer be a problem. If it happens again, please reopen it.
