### ISSUE TITLE
[Staging & Production] Add-on folder linking in Log inconsistent

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2368]
## Steps 
1. Go to your dropbox account and create a folder inside your dropbox 
2. Do the same for your box account. (create a new folder in the account)
3. Go to a project that you have admin privileges on

4. In the project's setting import the access token for dropbox
5. Select the new folder inside the dropbox folder from the folder picker widget
6. Submit
7. Do the same for the box add-on. Import access token and link a folder in the folder picker.
8. Submit
9. Repeat for S3 and Google Drive
10. Go to the project overview page
11. Look at the log on the lower right of the page
12. Notice the recent change made with the dropbox, box,  add-on linking the new folder

## Expected
The log of a dropbox folder would contain the folder name as it does for other add-on folders being linked to a project.

## Actual
The log contains a / after the dropbox add-on and before the folder name.
![screen shot 2015-03-31 at 9 25 40 am](https://cloud.githubusercontent.com/assets/9381062/6919784/f70e72f6-d787-11e4-8d69-787ab325049b.png)
For Google Drive, the log contains test% files for a folder called 'test files'
![screen shot 2015-03-31 at 9 27 03 am](https://cloud.githubusercontent.com/assets/9381062/6919826/394a0e14-d788-11e4-8fd6-38689aca0b21.png)

The log for a box folder linked to a project simply states that box was linked, and does not give the folder name unlike for other other add-ons.
![screen shot 2015-03-31 at 9 23 50 am](https://cloud.githubusercontent.com/assets/9381062/6919760/c7aaa93a-d787-11e4-90fc-a5baa6025be1.png)

The log for S3 calls it S3 in one entry of the log and then in another calls it Amazon Simple Storage Service.
![screen shot 2015-03-31 at 9 20 47 am](https://cloud.githubusercontent.com/assets/9381062/6919722/7938d858-d787-11e4-9c5d-1a90c5110063.png)

## Notes
There are major inconsistencies among the behavior for add-ons and thus the log shows varying styles for reporting the actions of the add-ons.  This issue seeks to conform the log to report as similarly as possible for the benefit (less confusion) of the user.

**Comment by lbanner** [comment]
Interesting question would be: Who has write control currently for text/language in the logs? Do we interpret/alter and write? Or do we depend upon info out of the Add-on itself and simply display? @brianjgeiger (going to you first) ?

**Comment by nanchen47** [comment]
This pr has been merged and deployed on production.
