### ISSUE TITLE
Github & Dataverse files select buttons do not show with long repo/study names

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#2369]
Steps
--------
1. Configure the dataverse addon for a project using a study with a long name 
2. Go to the project dashboard page and look at the files widget 
3. Repeat for the github addon

Expected
-------------
Only the study name should be truncated and the "released/draft" select button for dataverse and the branch select for github should still show in the grid. Example using dataverse: 
![screen shot 2015-03-31 at 9 52 51 am](https://cloud.githubusercontent.com/assets/6414394/6920764/756d2ee8-d78e-11e4-9f0e-4ae5aa4ad470.png)

Actual
---------
The long study/repo names are truncated but the select menus are either cut off or out of view: 
![screen shot 2015-03-31 at 10 09 53 am](https://cloud.githubusercontent.com/assets/6414394/6920731/4b648bc8-d78e-11e4-9fb6-31d9fc7aa91f.png)

**Comment by nanchen47** [comment]
Put this issue to deferred since @samanehsan has a PR https://github.com/CenterForOpenScience/osf.io/pull/2229 which will change the file page user interface. It's probably better to have that pr merged first

**Comment by rliebz** [comment]
Now with the file tree on the file view page at a relatively small width, this issue will be more prevalent than it was before and no longer needs to be deferred.

For both Dataverse and GitHub, it is not clear what branch/version you are working on on the files and the file view page. It also may be impossible through the UI to view other branches/versions. For Dataverse, it may not be possible to upload, delete, or publish anything, since the default version is read-only. For those reasons, I recommend this issue be bumped up in priority.

**Comment by lbanner** [comment]
Done @rliebz -- would a solution here be handled in the Dataverse API/connection, or   with alterations in the File View Page itself, possibly specific to Dataverse? <--- Anyone with insight.

**Comment by rliebz** [comment]
I don't think a solution would be specific to the file view page—I've seen names on Dataverse that are too long to fit on the regular files page.

I would imagine a solution would be to take the length of the select element into account when trimming the content of the name column in Fangorn/Treebeard.

**Comment by samanehsan** [comment]
This is fixed for github on the files page and the project overview page. The branch select box is now in the toolbar: 
![screen shot 2015-06-12 at 5 22 17 pm](https://cloud.githubusercontent.com/assets/6414394/8140243/bb17fa2c-1127-11e5-895e-05c59ea3fe7e.png)

It's still not fixed on the file detail page, where this issue is much more likely to happen. Or for the dataverse addon.
