### ISSUE TITLE
Comments tab icon off-center 

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#2376]
Steps
--------
1. Go to the overview page for one of your osf projects
2. Look at the comments tab 

Expected
------------
The comment bubble icon is centered on the comment pane tab. 

Actual
--------
The icon is slightly higher than it should be:  
![screen shot 2015-04-01 at 1 52 52 pm](https://cloud.githubusercontent.com/assets/6414394/6947611/715df4c0-d876-11e4-8c77-f705a2802f08.png)

**Comment by huangginny** [comment]
I fixed this in #1762 !

**Comment by GaryKriebel** [comment]
Will be fixed with comment updates.

**Comment by samanehsan** [comment]
@GaryKriebel, I think we should keep this issue open until #2534 is on production.

**Comment by GaryKriebel** [comment]
keeping this issue open until #2534 is on production.

**Comment by haoyuchen1992** [comment]
This bug is also fixed in the [osf branch](https://github.com/caneruguz/osf.io/tree/feature/styleguide) which apply style guideline.  If it merges with develop branch, then this issue can be closed.

**Comment by samanehsan** [comment]
This is fixed on production now:  
![screen shot 2015-07-23 at 12 11 20 pm](https://cloud.githubusercontent.com/assets/6414394/8855604/05e0038e-3134-11e5-92e6-65fda72f44cd.png)
