### ISSUE TITLE
No "remove" link if only 1 Employer listed on profile

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2384]
Steps
-------
1. Go to your user profile settings page. 
2. Enter your employer:
![screen shot 2015-04-02 at 10 32 53 am](https://cloud.githubusercontent.com/assets/7749914/6966078/4c41ebfc-d924-11e4-8b31-7fb3eebcdfa9.png)
3. Click "Add another:"
![screen shot 2015-04-02 at 10 33 00 am](https://cloud.githubusercontent.com/assets/7749914/6966090/5e44cbc6-d924-11e4-80f9-792c8c3c9b54.png)
4. "Remove" links appear in both 1st and 2nd employer

Expected
------------
"Remove" link would appear after you've entered information in the first employer entry.

Actual
--------
"Remove" link only appears after you've entered 2 or more.

Reported on the help desk.

**Comment by nanchen47** [comment]
The current behavior is that once you have ever entered an employment you need to have at least one employment info there and you can't remove any employment info anymore if there is only one. Possible solution will be add a button allow you to clear up the employment info if there is only one and allow you to update. @lbanner @GaryKriebel Thoughts?

**Comment by nanchen47** [comment]
related issue https://github.com/CenterForOpenScience/osf.io/issues/1230

**Comment by lbanner** [comment]
I agree -- this would be right approach @nanchen47 : 'add a button allow you to clear up the employment info if there is only one and allow you to update.' -- Want to take this on?

**Comment by nanchen47** [comment]
@billyhunt 's https://github.com/CenterForOpenScience/osf.io/pull/2531will fix this problem

**Comment by samanehsan** [comment]
@lbanner, there is already a PR resolving this issue in the old repo: https://github.com/CenterForOpenScience/osf/pull/1224

But since it hasn't been updated since November, my suggestion is to close it in favor of @billyhunt 's PR

**Comment by lbanner** [comment]
Good plan -- TY
