### ISSUE TITLE
[2factor]the warning message doesn't update properly

### ISSUE THREAD

**Issue by chennan47** [CenterForOpenScience/osf.io#2385]
Current behavior:

1st issue
When user clicks to enable 2-factor, there is an incorrect success message. This message should not appear until after the user successful enters their verification code.

2nd issue:
After entering the verification code, the user does not get a success message within the form (when they should).

3rd issue:
Status messages appearing at the top of the screen are not needed and should be removed.

Specification for the fix:

1. When user clicks to enable 2-factor, they should be taken to the two factor security form. The form should have:
*the description of the process
*the QR code
*a box to put in the code user receives
*No status/success message should appear on this step.

2. After the user enters the security code, a success message should appear in the form. 
*the message reads: "You have successfully enabled two-factor authentication"

3. No status messages should appear at the top of the screen. 

For testing:

Double check deactivation with this change (in addition to testing the above):
When you deactivate, user sees a modal confirming deactivation (no change here just verify it still works). User should see no status message at the top of the page or in the form. The link changes to Enable two-factor authentication.

_______
Documentation of former issues:

<b>Steps</b>
1. log in to osf
2. go to your user settings page
3. enable two factor addon and don't authorize it yet
then you will see
on top:
![screen shot 2015-04-02 at 10 38 55 am](https://cloud.githubusercontent.com/assets/4974056/6966127/8dcf89c6-d924-11e4-9eea-74d5f228c1c2.png)
cilck on the active your device link will redirect you to
![screen shot 2015-04-02 at 10 38 47 am](https://cloud.githubusercontent.com/assets/4974056/6966157/d6886412-d924-11e4-8a65-1269eea0404f.png)
4. authorize the two factor addon
you will see the two factor filed becomes
![screen shot 2015-04-02 at 10 42 46 am](https://cloud.githubusercontent.com/assets/4974056/6966188/0f491a4e-d925-11e4-8031-906485a444b0.png)
but the warning message on top is still 
![screen shot 2015-04-02 at 10 38 55 am](https://cloud.githubusercontent.com/assets/4974056/6966193/23d7c6c2-d925-11e4-9f67-1c0dda10dc16.png)

and click on the link doesn't take you anywhere.

<b>Expected</b>
The warning message on top should be changed to "Your two factor addon has been successfully authorized".

**Comment by MPNussbaum** [comment]
@chennan47 @GaryKriebel Was not able to recreate. 

![screen shot 2015-05-19 at 6 30 40 pm](https://cloud.githubusercontent.com/assets/2239453/7715417/51a3bd68-fe55-11e4-8710-aec40f57893e.png)
![screen shot 2015-05-19 at 6 31 07 pm](https://cloud.githubusercontent.com/assets/2239453/7715416/519f3108-fe55-11e4-8c2d-f49a25f3db1a.png)

**Comment by chennan47** [comment]
The problem is that, if you don't click to dismiss the message. It persist even you active the addon.

**Comment by zkraime** [comment]
@GaryKriebel I'll grab this one real quick
