### ISSUE TITLE
Failure to Render Unicode Characters 

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2389]
Steps
-------
1. Upload a txt file with unicode characters (UTF-8)
2. Attempt to view the file via the file renderer
3. Characters appear garbled.

Expected
------------
Characters would render as they appear in the text file: 
![screen shot 2015-04-02 at 11 24 28 am](https://cloud.githubusercontent.com/assets/7749914/6967172/b05102a2-d92b-11e4-9495-66a1600cad96.png)

Actual
--------
Characters do not:
![screen shot 2015-04-02 at 11 28 22 am](https://cloud.githubusercontent.com/assets/7749914/6967182/bd217fc0-d92b-11e4-9280-38980f09bac2.png)

You can see my example here: https://osf.io/d93ih/

Reported on the help desk. @brianjgeiger indicates that the expected behavior is that the characters will render.

**Comment by lbanner** [comment]
Set this as "high" as it came in via Help Desk -- @brianjgeiger any thoughts on realm of solution (i.e. dev expertise) within which this might reside? TY

**Comment by chennan47** [comment]
This is a mfr problem. Prolly goes to @mfraezz

**Comment by brianjgeiger** [comment]
What @chennan47 said. It's probably just that we aren't handling unicode properly through the stack, so it's probably a fairly simple solution. But Matt's the one with the most recent experience doing just that sort of thing.

**Comment by lbanner** [comment]
OK - @mfraezz is on "walk-about" until April 18 -- I'll tag him with this, but also would like insight on user priority @saradbowman ?

**Comment by mfraezz** [comment]
I don't actually leave for another ~36 hours. I'm on it

**Comment by lbanner** [comment]
OK @mfraezz -- Thank you!

**Comment by sloria** [comment]
Should be fixed on production now. The problem was that we were opening text files assuming ascii encoding. The minor change in https://github.com/CenterForOpenScience/osf.io/commit/8cd0b05f87c9ce32139196262a95ddae593f029a opens files with UTF-8 encoding.
