### ISSUE TITLE
Notification email_transactional should not depend on comments

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/osf.io#2392]
As discussed with @sloria, the function `email_transactional` in `website/notifications/emails.py` should not depend on comments. (line 37) It should be able to handle other notification types and not expect a "commenter" field to be present in the template context.

**Comment by lbanner** [comment]
Question: Does this represent a user-facing issue? -- or rather improved, more better, functionality on the back-end? ... trying to measure approach and priority. Thanks @abought

**Comment by abought** [comment]
This issue does not affect users at present. But from a design standpoint, it hinders the ability to roll out new email notification features that users might want in the future. Essentially, your general function (send notification) is tightly coupled to one particular type of notification (comments).

For example, this would be a blocking issue for wiki @ person notifications.

**Comment by lbanner** [comment]
Indeed! Apologies sir! :smiling_imp:

**Comment by Ghalko** [comment]
The only parameters that don't make sense to more general notifications is parent_comment and commenter. parent_comment is currently required, even though a blank string can be put through, but removing the need for this might be good. On the other hand the commenter would be nice to have no matter what the notification, but with a more generic name, such as user. However, commenter implies that they were the one that did something, whereas user is almost too generic.

**Comment by abought** [comment]
If we do keep this in `email_transactional`, then perhaps "sender", or something to describe their specific role in the transaction?

Whatever it's named, one other thing discussed with @sloria is that it would help to have documentation of what this function needs in order to be called.

Currently, it (and the transactional email template that wraps email content) explicitly depend on a number of variables/parameters that are not present in the call signature. This can lead to subtle bugs when it comes time to use the function or add new notification types.

**Comment by lbanner** [comment]
+1 on that point re: documentation.

**Comment by samanehsan** [comment]
I agree `commenter` should be given a more general name to accommodate other notification types. `User` could work if there is documentation that clarifies it is the user who performed the action, not the user receiving the notification. 

@abought, +1 on moving required variables into the call signature -- that should also help clarify what is required for this function vs. the notification email template.

@Ghalko, `parent_comment` is required by the email template `comment_replies.html.mako`, not `email_transactional`.

**Comment by abought** [comment]
Also, here is the "wrapper" email template I referred to. It goes around any individual email template, so it contains additional template variables required by just about any email. This may be worth including in the documentation.

https://github.com/CenterForOpenScience/osf.io/blob/develop/website/templates/emails/transactional.html.mako

**Comment by Ghalko** [comment]
The function *needs* the listed parameters plus "commenter", "node_id", and "title" from **context. Other than that the **context is passed onto:

subject = Template(constants.EMAIL_SUBJECT_MAP[event]).render(**context)

which uses a template that can be defined differently and use as many variables from **context as you want. Documenting all the templates that this has access to would be over the top in the future.

**Comment by abought** [comment]
Documenting every possible template would be over the top... I totally agree about limiting the scope of this issue.

But documenting the single wrapper shared by every individual template seems more reasonable.

**Comment by Ghalko** [comment]
A possible reason that some of those variables are in the ```**context``` is because they are used by the template mentioned by @abought. Though I could certainly refactor either the calling function and/or the template to be more self-documenting.

**Comment by nanchen47** [comment]
The pr has been deployed.
