### ISSUE TITLE
Production test server

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2393]
As we increase the capability for third parties to work with our data and services, we need to have a place for them to play and test a stable and feature-complete version of the site. Essentially a copy of all of our active services, but with a minimal set of data. This includes all of the SHARE, Waterbutler, and ElasticSearch services, but in a way that won't corrupt the SHARE stream if they create registrations or similar. We might provide a set of sample data (maybe all of our public projects/registrations, or maybe a faked set of projects and users) as well.

We have staging, but for third-party users, there's no guarantee that it will be available at any given time nor stable. This should be something that matches production at all times.

**Comment by GaryKriebel** [comment]
This would be good for the 3rd party regression testing to be conducted in the near term.  They asked today about the test server.
