### ISSUE TITLE
[production]delete files tooltip stays even you deleted the file and move your cursor to other place

### ISSUE THREAD

**Issue by chennan47** [CenterForOpenScience/osf.io#2394]
<b>Steps</b>
1. go to a project files page on production
2. choose a file and click on the remove cross
3. the remove tooltip will show up and stay there forever unless you refresh the page

![screen shot 2015-04-03 at 3 35 51 pm](https://cloud.githubusercontent.com/assets/4974056/6987633/45dcbe6a-da17-11e4-8255-7624aedf2176.png)
![screen shot 2015-04-03 at 3 32 48 pm](https://cloud.githubusercontent.com/assets/4974056/6987636/4a759fbe-da17-11e4-9180-31b22b1b82d3.png)

**Comment by chennan47** [comment]
related issue https://github.com/CenterForOpenScience/osf.io/issues/2352

**Comment by lbanner** [comment]
This was also noted in relation to the new 'create folder' PR #2327
"When I hover over the new folder button on the files page, the tooltip "sticks", i.e. it does not disappear after hovering off of the button. Refreshing the page removes the tooltip, but then the tooltips don't show at all after that."

**Comment by caneruguz** [comment]
@nanchen47 this isn't happening for me in production. Can you provide details like browser? Is it replicable with different add ons?

**Comment by nanchen47** [comment]
This problem only happens in production but not staging and even if you localhost branch on master. You can't repo this problem locally. Perhaps it can be solved with the new release. Talk with @sloria, @caneruguz . Put this to defer

**Comment by nicipfeiffer** [comment]
@nanchen47 @lbanner I am seeing this on production when using Chrome and Safari browsers for 'create folder', 'delete' and 'view file' tooltips.
![screenshot 2015-05-07 13 48 18](https://cloud.githubusercontent.com/assets/9381062/7522022/6b6d937a-f4c0-11e4-8533-c10d8f95be00.png)
Can we un-defer?

**Comment by caneruguz** [comment]
We should defer because my changes for 0.36 will get rid of actions column and these tool tips. 



—

**Comment by lbanner** [comment]
Agreed .. this is tagged "deferred" for that reason. Reference #2606

**Comment by caneruguz** [comment]
@lbanner This is no longer an issue, the entire column is removed from that page with the changes in the last few releases.

**Comment by lbanner** [comment]
Excellent!
