### ISSUE TITLE
[production] tooltip doesn't show up for public project's anonymous link

### ISSUE THREAD

**Issue by chennan47** [CenterForOpenScience/osf.io#2395]
<b>Steps</b>
1.create a public project
2. create a anonymous link for this public project

<b>expected</b>
As of issue https://github.com/CenterForOpenScience/osf.io/issues/1466 and commit https://github.com/CenterForOpenScience/osf.io/commit/3912ffdb0c44f0fbcc0b504c7d4f206ff67841ef by @sloria, it should look like 
![image](https://cloud.githubusercontent.com/assets/4974056/6989341/4da65528-da28-11e4-9733-2a184b352e27.png)

<b>Actual</b>
![screen shot 2015-04-03 at 5 35 38 pm](https://cloud.githubusercontent.com/assets/4974056/6989355/6128c69e-da28-11e4-9b1f-1e04836cefe8.png)

**Comment by lbanner** [comment]
Good catch -

**Comment by nanchen47** [comment]
This pr has been merged and this fix already imply in production
