### ISSUE TITLE
signin form and forgot password shouldn't show up when you are on two factor code page

### ISSUE THREAD

**Issue by chennan47** [CenterForOpenScience/osf.io#2396]
<b>Steps</b>
1.have two osf accounts one of which has two factor enabled
2. log in to the one with two factor account but stop at the two factor verification
you will see
![screen shot 2015-04-04 at 2 15 05 pm](https://cloud.githubusercontent.com/assets/4974056/6993972/584a8546-dad5-11e4-849f-d0dac641b483.png)
3. then use the right top bar to log into another account, you will see
![screen shot 2015-04-04 at 2 15 19 pm](https://cloud.githubusercontent.com/assets/4974056/6993975/7001a3ea-dad5-11e4-91d2-b1d817b73a56.png)

4. then if you enter the two factor code. You will log in as the first account.

<b>Suggest Solution</b>
Disabled the right top log in and forget password form when on two factor page.

**Comment by sloria** [comment]
I'm thinking this should be put on hold, pending @icereval 's CAS integration, which will involve changing the UI for sign-in/2fa.

**Comment by lbanner** [comment]
Agreed -

**Comment by samanehsan** [comment]
This issue has been fixed in production. Now the navbar is not included on the page with the two-factor form: 
![screen shot 2015-06-22 at 5 06 52 pm](https://cloud.githubusercontent.com/assets/6414394/8293124/6742de30-1901-11e5-90b0-0af5e1aa2360.png)
