### ISSUE TITLE
[production] .docx rendering timeout

### ISSUE THREAD

**Issue by jeg3tw** [CenterForOpenScience/osf.io#2400]
# Steps
1.  Go to a project
2.  Go to the files tab
3.  Try to render a .docx file

# Expected
The file will render.

# Actual
A timeout will occur.

![screen shot 2015-04-06 at 10 48 52 am](https://cloud.githubusercontent.com/assets/9021353/7005898/926766c4-dc4a-11e4-851a-0c9f220a0d2a.png)

**Comment by lbanner** [comment]
@sloria -- can we get a guess on why this might have cropped up? Recent changes? Or is there some instability around rendering that pops-up-its-ugly-head once and awhile? FYI @mfraezz is away at present -- so if need to dig in -- suggestions?

**Comment by sloria** [comment]
@lbanner Will take a look

**Comment by sloria** [comment]
Fixed now.
