### ISSUE TITLE
Adding a blank Institution in Profile causes Internal Server Error Message

### ISSUE THREAD

**Issue by billyhunt** [CenterForOpenScience/osf.io#2412]
Steps
-------
1.  Go to User Profile
2.  Go to Education Tab
3.  Change Institution Field
4.  Click "Add Another"
5.  Click "Submit"

Expected
------------

If there is a blank Employment or School object, it should be ignored with the save happening, and no Internal Server Error should happen in the console.  

Actual
--------

The save is not possible, and the following error shows in the console.

PUT https://osf.io/api/v1/settings/schools/ 500 (INTERNAL SERVER ERROR) jquery-1.11.2.min.js:4

![screenshot 2015-04-08 09 24 41](https://cloud.githubusercontent.com/assets/6232068/7046101/7b5add84-ddd1-11e4-9f0c-b19c6428e614.png)

**Comment by lbanner** [comment]
You want this @billyhunt -- since you are working in this area at present?

**Comment by billyhunt** [comment]
Sure.  Makes sense to me.

**Comment by lbanner** [comment]
You got it -- TY

**Comment by nicipfeiffer** [comment]
@billyhunt I think you are saying that this also occurs with employment and leaving the first field for 'Institution / Employer' blank when it has 'Required' in the text box.
If you have an incorrect date range, the error will tell you what is incorrect, like 'End date must be greater than or equal to the start date.'  
I think the same sort of error needs to be happening here to inform the user that the required field of 'blah blah' is blank.

**Comment by lbanner** [comment]
Those fields are "required?" -- I agree with @nicipfeiffer 's 'blah blah' idea.

**Comment by billyhunt** [comment]
I was going to handle it by allowing a blank employment or school object.  That is the original state, and you can never get back to that.  To me, it makes sense to allow you to have no job and/or no school.  Sad, but very possible.  As it stands, I don't think you can reset to that original blank state.  

So, I think the logic should be as follows when you hit "Submit"

1.  If any field is filled in an Employment or Education object, then the Institution is required. An error message appears saying as much to let users know they messed up.
2.  If no fields are filled in a new Employment or Education object, it is ignored.  
3.  If no fields are filled in an existing Employment or Education object, then that object is deleted from the database.

Does this make sense to you two?

**Comment by nicipfeiffer** [comment]
Yes, I agree!

**Comment by lbanner** [comment]
:+1: from me, thanks.

**Comment by billyhunt** [comment]
OK.  I have been holding off on completion of this until I finish adding the multiple websites to the profile, but if you think this takes priority, let me know.

**Comment by lbanner** [comment]
As a :bug: @billyhunt , I'd say yes on this one first -- thanks.
