### ISSUE TITLE
[Staging & Production] Add-ons folder path calling inconsistent

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2415]
## Steps
1. Log into your account and create a brand new project
2. Go to the project settings page and go through the steps to authorize and link content for each add-on (except external link and two factor)
3. Include linking a nested folder for the add-ons box, Dropbox and Google Drive
4. For each add-on look at the folder path calling in 4 locations: the folder picker widget for the add-on, the current folder selected above the folder picker in the add-on widget, the project overview page logs, and the project/files overview pages.

## Expected
I would expect to see consistent folder path calling in all locations and consistency across all add-ons.

## Actual
It varies, here is a table with the best visualization I can create to show where and how the behavior is inconsistent.

![screenshot 2015-04-08 12 20 06](https://cloud.githubusercontent.com/assets/9381062/7049707/9eb988bc-dde9-11e4-969d-0cf05008f86b.png)

Basically, the inconsistencies that I see that should be easy to implement are:
 - In the add-on widget on the project settings page, for the Github to show the name of the linked repo after 'Current repo:' to consistent with Amazon S3 and Dataverse.
![screenshot 2015-04-08 12 22 22](https://cloud.githubusercontent.com/assets/9381062/7049750/181a0592-ddea-11e4-99dc-17000c002eba.png)
![screenshot 2015-04-08 12 24 05](https://cloud.githubusercontent.com/assets/9381062/7049756/2fd812c8-ddea-11e4-8ec4-9670c678c479.png)
 - For the 3 add-ons box, dropbox and google drive that manage files and folders: I think that folders and nested folders should have consistent path calling.  The visual shows where these inconsistencies lie.  The project log handles the folder path differently for each add-on and then also on the file tree.

**Comment by nanchen47** [comment]
The pr has been deployed and the settings page interface has been modified.
