### ISSUE TITLE
[production] Unable to import contributors from parent project

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2432]
Steps
-------
1. Navigate to a project with multiple contributors
2. Create a new component in the project.
3. Go to "Sharing" and click "Import contributors from [parent project]"

Expected
------------
imported contributors will populate the add contributors modal

Actual
--------
Nothing happens

I have experienced this in both Chrome (Version 41.0.2272.118) and Safari (Version 7.1.3 (9537.85.12.18)). In Chrome, console shows this error:
Uncaught TypeError: undefined is not a function

**Comment by sloria** [comment]
Fixed by #2433
