### ISSUE TITLE
[production] Presentation service unexpectedly added submission to another project of same name

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#2447]
What you did (step by step)

> I posted my talk for RMPA on their presentation page. I used the same
> title as a previous talk at APS. Instead of creating a new project, the
> system added the file to the existing project of the same name. If
> accidental, that seems like a reasonable behavior. However, I also receive
> a message that the email had been marked as spam even though the project
> does appear in the list. 

Where does this happen on the OSF?

> Submitting to presentation service

What you expected

> a new project for that submission, not being marked as spam

What actually happened

> combined with an existing project, marked as spam (though apparently without consequence), and a "presentation service" contributor added to the project

Additional notes from Sara:

The project also lists "presentation service" as a contributor on the
project. Presentation Service is the account associated with the 'admin'
contributor we've discussed before - Josh wrote a migration script to
replace personal accounts as invisible contributors with a generic OSF
account. Here is the pull request for that script:
https://github.com/CenterForOpenScience/osf.io/pull/2188

Issues:
*Script replaces emails with the staff email "presentations@cos.io" but
should have been "presentations@osf.io"
*New admin account should be non-bibliographic contributor but is not
*Script added "Presentation Service" as a contributor even to conferences
that did not have an "admin" account listed

Last item (I should have thought about this before, but didn't) is that we
never modified the populate_conferences.py script to remove those personal
email accounts -- so projects created after the migration script ran have
the personal accounts as admins. Likely does not affect many projects, but
I will modify the populate_conferences.py script now so it does not affect
any more submissions.

Spam message received (and osf id of project):

> Hello Brian Nosek,
>
> Congratulations! You have successfully added your Rocky Mountain
> Psychological Association 2015 talk to the Open Science Framework (OSF).
>
> Your Rocky Mountain Psychological Association 2015 submission has been
> added to the Open Science Framework. You now have a permanent, citable URL,
> that you can share: [ https://osf.io/86g2i/ ]. All submissions Rocky
> Mountain Psychological Association 2015 may be viewed at the following
> link: [ https://osf.io/view/rmpa2015/ ].
>
> Your email was flagged as spam by our mail processing service. To prevent
> potential spam, we have made your project private. If this is a real
> project, please log in to your account, browse to your project, and click
> the "Make Public" button so that other users can view it.
>
> Get more from the OSF by enhancing your page with the following:
>
> - Collaborators/contributors to the submission
> - Charts, graphs, and data that didn't make it onto the submission
> - Links to related publications or reference lists
> - Connecting your GitHub account via add-on integration
>
> To learn more about the OSF, visit [ http://osf.io/getting-started ]!
>
> Follow the COS at @OSFramework <https://github.com/OSFramework> on
> Twitter [ https://twitter.com/OSFramework ]
> Like us on Facebook [ https://www.facebook.com/OpenScienceFramework ]
>
> Sincerely yours,
>
> The OSF Robot

**Comment by lbanner** [comment]
This is a good catch -- I think some discussion is needed on resolution. The 'flagged as spam' is standard response, as I have understood it, for presentation services and generally does not coincide with reality, even if a named project or conference already exists -- that is in addition to any Admin migration issues that remain I'd like to suggest that Community take lead as a Product Owner in proposing approach/solutions (?) -- Happy the help.

**Comment by GaryKriebel** [comment]
@nanchen47 is this covered in your recent Presentation Service fixes?

**Comment by chennan47** [comment]
@JeffSpies The email "presentations@cos.io" is not managed by anyone and is shown up on some project as visible contributor and the email "presentation@osf.io" is managed by @saradbowman. One possible solution is writing a script to merge these two user and make it to be non-visible user over all its projects contributed. Thoughts?

**Comment by nanchen47** [comment]
This pr has been merged and deployed on production and I verified that the user "Presentation Service" no longer show up in production search.

**Comment by saradbowman** [comment]
Thank you!
