### ISSUE TITLE
[production bug] Adding emails non-functional

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#2454]
Going to account setting and adding emails resulted in error messages.

![screen shot 2015-04-12 at 5 34 36 pm](https://cloud.githubusercontent.com/assets/1761504/7107665/3b7dd268-e13a-11e4-85a9-a5b072ce3126.png)

**Comment by GaryKriebel** [comment]
@bnosek what action did you take for that error to show?  I just added two alternate emails and it properly placed them in the "unconfirmed" list and then clicking the link in the received email properly placed then in the "alternate" list.

**Comment by bnosek** [comment]
Clicked on "Edit your profile"
Clicked on "Account settings"
In "unconfirmed emails" I typed in an email address
Clicked on "Add email"

received error message

**Comment by lbanner** [comment]
Interesting -- To too walked through this without error. If you log out and log back in, are those input 'unconfirmed' emails still there? But maybe you have not received a confirmation email? ... wonder if we can dig into a specific account error log @sloria ?

**Comment by GaryKriebel** [comment]
I just tried again on Chrome, Firefox, and Safari with desired results on all browsers.

**Comment by bnosek** [comment]
Looks like I might need to clear my cache.  Hang on.

**Comment by sloria** [comment]
I just saw the error pop up in Sentry and made a patch. @bnosek Can you try again please?

**Comment by bnosek** [comment]
clearing cache addressed it.

can close.

**Comment by GaryKriebel** [comment]
@sloria when did you make the patch?  Wonder if it was the patch or Brian clearing the cache that fixed it.

**Comment by sloria** [comment]
I don't believe the bug was cache-related; there was an edge case that was unhandled in the code, which I patched on prod. I'll make a proper hotfix shortly.

**Comment by GaryKriebel** [comment]
I'll keep this open until your proper hotfix is complete.

**Comment by sloria** [comment]
Should be fixed now.
