### ISSUE TITLE
[production] Creator of DOI not the correct user

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#2455]
I created a DOI for a registration, but the EZID page lists the creator as another member of the project:

![screen shot 2015-04-12 at 6 18 33 pm](https://cloud.githubusercontent.com/assets/1761504/7107841/7ebf4862-e140-11e4-9426-a9083d90736b.png)

**Comment by lbanner** [comment]
That's interesting too -- @sloria path for delivering account info to EZID? Are we grabbing the wrong contributor name somehow?

**Comment by sloria** [comment]
@bnosek The Creator of the DOI will be the full name of the creator of the project (not necessarily the user who clicked "Create DOI...").

Should the behavior be changed?

**Comment by bnosek** [comment]
That is probably sensible behavior.  Perhaps in the future, we can give the
user an option for who is named (assuming that it must be a single
person).  Fine for now.

**Comment by JeffSpies** [comment]
Does it have to be a single person? Given that they're creating a preview
citation, that doesn't seem right.

**Comment by lbanner** [comment]
Wonder if EZID allows for multiple creators? May be a limitation on their end, but we can look into that.

**Comment by bnosek** [comment]
That would certainly be ideal for our use case.  All authors on the project
are listed.

**Comment by GaryKriebel** [comment]
I will look over the API documentation to see if there is any mention on
number of creators.

**Comment by GaryKriebel** [comment]
Yes, multiple names are allowed.  It looks like they should be separated with ;

**Comment by sloria** [comment]
This is fixed. All contributor names will show up under creators now.
