### ISSUE TITLE
[Staging & Production] [SHARE] Clicking 'More' and scrolling to top causes navbar to jump

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2456]
## Steps
1. Go to https://osf.io/share/?
2. Type in a search that returns a lot of results, can enter "*" to get all results
3. Scroll to the bottom and click on 'More'
4. Repeat step 3 a few times, without scrolling to top
5. Scroll to the top quickly (pay attention to the navbar)

## Expected
That scrolling to the top with many results on the page would have no errors on the page

## Actual
When scrolling up to the top quickly with many results on the page, the navbar jumps around.

![navbarjump](https://cloud.githubusercontent.com/assets/5975444/7116721/b8fe8fac-e1c1-11e4-9b6d-5f3005d7a950.gif)

**Comment by chrisseto** [comment]
I'm not sure if theres much that we can do about that.
@caneruguz and @brianjgeiger, thoughts?

**Comment by brianjgeiger** [comment]
There should be something we can do. That's an odd thing.

**Comment by brianjgeiger** [comment]
Interesting. This seems to be browser-specific, as Safari is fine with it. Although I'm having a hard time replicating with Chrome as well. I can get the navbar to pull away from the top of the window in Chrome, but it always shows the "background" from chrome rather than our web content underneath.

**Comment by caneruguz** [comment]
I tried to replicate it too and it seems like when a lot of content is on the page it does lag. 

My best guess is that as the element size in the page increases (with the number of items) the scroll height increases so a fast scroll needs a very quick repainting which depending on the machine the browser might not be able to catch up with. This is just a guess though. The chart below does show that the scrolling at the end is causing a lot of repaint (the green part). 

![screen shot 2015-04-19 at 10 44 04 am](https://cloud.githubusercontent.com/assets/1314003/7219853/168484a0-e682-11e4-8a3b-1f1cda22712a.png)

So I would say working on this would be a small optimization that would take time so maybe we should defer it.

**Comment by lbanner** [comment]
We have other more pressing issues -- I am going to defer. Thanks all.

**Comment by nanchen47** [comment]
Verified with @fabianvf , this is fixed.
