### ISSUE TITLE
Contributors permissions are forgotten after adding unregistered contributor/hitting back

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2459]
<h4>Steps</h4>
1. Go to the sharing page of a project. Click to add a contributor.
2. Search for a user's name, click to put them into the "adding" column.
3. Adjust their permissions so that it is not the default "admin" setting.
![screen shot 2015-04-13 at 10 41 37 am](https://cloud.githubusercontent.com/assets/4965832/7118036/a71f37e2-e1ca-11e4-8ab4-c401b6482a56.png)
4. Hit next
5. On the next page where you can select components to add them to, click back to return to the add contributors page.
![screen shot 2015-04-13 at 10 41 51 am](https://cloud.githubusercontent.com/assets/4965832/7118064/c4d39922-e1ca-11e4-9156-9b521462bcd3.png)

**or**

1. Go to the sharing page of a project. Click to add a contributor.
2. Search for a user's name, click to put them into the "adding" column.
3. Adjust their permissions so that it is not the default "admin" setting.
4. Search for another user who does not have an account
5. Click to add them as an unregistered user, enter their email address and submit. You will be brought back to the add contributors page
![screen shot 2015-04-13 at 10 42 24 am](https://cloud.githubusercontent.com/assets/4965832/7118090/f1242cbc-e1ca-11e4-8385-d6803d3583c5.png)

<h4>Outcome</h4>
1. In each case, when you return to the add contributors page, the permissions for the first user have been returned to "administrator" even though you adjusted them previously. 

**Case 1**
![screen shot 2015-04-13 at 10 41 57 am](https://cloud.githubusercontent.com/assets/4965832/7118097/f98b1078-e1ca-11e4-9f11-d65623adcb53.png)

**Case 2**
![screen shot 2015-04-13 at 10 42 28 am](https://cloud.githubusercontent.com/assets/4965832/7118073/dcd0e08e-e1ca-11e4-846b-ab6a00d67a53.png)

<h4>Expected</h4>
1. Permissions should be remembered, especially in the case where they are adjusted then an unregistered user is added. If a user adjusts the permissions of one new contributor during the adding process, that should be remembered the entire time the modal is opened.

**Comment by lbanner** [comment]
Probably the case that those Permission settings are not auto-saved; They are saved when you click "submit" -- Given potential security aspects, I'd suggest we at least offer up some direction/warning on this -- unless some dev has a clever auto-save solution?

**Comment by brianjgeiger** [comment]
Or when we re-work this page so that it doesn't require batching everything, we could also find an in-line way to add contributors rather than using a modal dialog box.

**Comment by Ghalko** [comment]
Any suggestions for examples or sites for inlining everything @brianjgeiger ? I was going to take this on. Thinking that the back button was going to be a hassle, but if we just want to redo the whole thing?

**Comment by Ghalko** [comment]
This might be fixed by my PR #2223. But I still want to work on redesigning how contributors are added.

**Comment by nanchen47** [comment]
The fix pr has been merge and deployed on production.
