### ISSUE TITLE
Add contributor search results not updated when looking for user with special character

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2460]
<h4>Steps</h4>
1. Visit the sharing page of a project and click to add a contributor
2. Search to add a current user with special characters in their name (try Bélén Fernández or Marcus Möschl)

<h4>Outcome</h4>
1. The results, which show recently added contributors when you first open this modal, are not updated. They do not show results for the name you searched, nor do they return that no users were found.
2. "Add [your search term] as an unregistered contributor" is  displayed below the results.
![screen shot 2015-04-13 at 11 07 09 am](https://cloud.githubusercontent.com/assets/4965832/7118577/16ff4054-e1ce-11e4-86ad-1b70149e260e.png)

3. The console logs a 500 error
4. Searching for the name without the accents included does return the correct result. 

![screen shot 2015-04-13 at 11 07 19 am](https://cloud.githubusercontent.com/assets/4965832/7118578/1bcea412-e1ce-11e4-9868-72022b9abfd6.png)

<h4>Expected</h4>
1. If no users are found, the results should note this.
2. If a matching user is found, then they should be returned as a result. When the results are not updated at all but "Add XYZ as an unregistered contributor" is shown, it seems like the user was not found and that they do not have an account. Clicking to add them as an unregistered contributor will tell you otherwise, however, when you enter their email. It seems that if the user has a special character in their name the results are just not being populated, even if they have an account.

**Comment by lbanner** [comment]
@jlcohoon -- this on Production, I assume? @nicipfeiffer -- can you replicate? Thanks.

**Comment by nicipfeiffer** [comment]
@lbanner I was able to replicate the issue on Production and Staging

**Comment by samanehsan** [comment]
Closed by #2787.
