### ISSUE TITLE
[Staging & Production] Registration page link to Popular Registrations

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2461]
## Steps
1. Go to a public project with no registrations (here's one: https://osf.io/btc75/ )
2. Click on the registration tab
3. See the text 'There have been no registrations of this project. For a list of the most viewed and most recent public registrations on the Open Science Framework, click here. '
4. Click on 'here' a link to most viewed and most recent public **registrations**

## Expected
The link to the most viewed and most recent public registrations link would take me to the registration section of our popular projects and registrations.

## Actual
The link takes you to the top of the page for Public Activity which starts with projects.

## Notes
I think that the link should have the page open where the 'Newest Public Registrations' begin, instead of opening at 'Newest Public Projects'.

**Comment by nanchen47** [comment]
This pr has been merged and deployed on production.
