### ISSUE TITLE
[IE] Confirmed email does not show as alternative email

### ISSUE THREAD

**Issue by ginavuu** [CenterForOpenScience/osf.io#2462]
Steps
1. Log into primary account
2. Go to user settings
3. Click account settings tab
4. Input an email address tha is already assoicated with an  unconfirmed user (someone who started to make an osf account but never confirmed their email)
5. Click "Add Email"
6. Confirm the email

Expected
The email address should now be listed under alternative emails instead of unconfirmed email

Actual
The email address stayed as an unconfirmed email.

![confirm](https://cloud.githubusercontent.com/assets/11032617/7119684/81a9e024-e1d5-11e4-9a3d-2f21797c6537.PNG)

**Comment by lbanner** [comment]
I assume you received the confirmation email and clicked to confirm? Have you logged out and returned to that page, double checking the email remains in "unconfirmed?" -- Can you double-check functionality in another browser? Thanks @ginavuu

**Comment by ginavuu** [comment]
I think I got this working now. It may be that I was confirming to the wrong confirmation which makes it a new account instead of merging the two address.

**Comment by lbanner** [comment]
Alright -- Let's close for now, unless it comes up again. Thank you!
