### ISSUE TITLE
[IE] Small window makes navigation behind video

### ISSUE THREAD

**Issue by ginavuu** [CenterForOpenScience/osf.io#2464]
Steps
1. Using IE, go to https://osf.io/9ubcv/.
2. Shrink the window's width
3. Click on project navigation

Expected
The drop down menu would drop over the video.

Actual
Only in IE the window drops behind the video.

![navi](https://cloud.githubusercontent.com/assets/11032617/7119875/4211130e-e1d7-11e4-8337-ccd852ad5b98.PNG)

**Comment by lbanner** [comment]
@caneruguz  -- Thoughts here?

**Comment by ginavuu** [comment]
Seems to be only on IE

**Comment by ticklemepierce** [comment]
Unable to reproduce on my Windows virtual machine.

**Comment by geeksnglitter** [comment]
I can take a stab at this one. @lbanner @GaryKriebel

**Comment by lbanner** [comment]
@geeksnglitter .... If you cannot reproduce (as @ticklemepierce was unable to), we can close this issue for now -- Let us know. TY

**Comment by geeksnglitter** [comment]
I can reproduce it. It's real.

**Comment by lbanner** [comment]
Thanks -- you got it :smiling_imp:

**Comment by geeksnglitter** [comment]
Okay so I think IE 11 fixes the problem. Should I proceed trying to get it to work with IE 10? @GaryKriebel

**Comment by chennan47** [comment]
@geeksnglitter go ahead and try with IE10 but anything below IE 9 may not
be worth the time.

**Comment by lbanner** [comment]
Yes -- what @chennan47 said.

**Comment by geeksnglitter** [comment]
I was wrong - the issue still appears in IE 11 on saucelab, but when I try it on IE 11 on my virtual box virtual machine it does not appear. The same is true from IE10.

**Comment by geeksnglitter** [comment]
Can we defer this for now @lbanner? 

On another note, this might be the fix http://stackoverflow.com/questions/2625166/flash-video-playing-on-top-of-everything-else-in-ie7

**Comment by lbanner** [comment]
Appreciate the work on this @geeksnglitter -- we'll defer for now.
