### ISSUE TITLE
[IE] GitHub: Add-ons

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#2465]
STEPS
1. Select and enable add-ons (user settings)
2. Configure add-ons (user settings)
3. Import credentials into a project.
4. Configure add-on for the project (link a folder, repo, etc)
5. View a file in the linked folder (check for breadcrumbs, version table, download and delete buttons) 

EXPECTED
The GitHub folder would render and the files associated with the folder could be viewed.

ACTUAL
An error message pops up when attempting to expand the GitHub folder in the project overview page: "Files could not load, please try again later"

Link to the original trello card: https://trello.com/c/szO2yNd8/170-ie-github-add-ons

![github not rendering](https://cloud.githubusercontent.com/assets/10926926/7119897/6187770a-e1d7-11e4-9ff5-31feb38c344f.png)

**Comment by lbanner** [comment]
Just with IE? ..... this a WaterButler thing @icereval or maybe you have insight @samchrisinger ? Thanks.

**Comment by wisherp** [comment]
The testing was intended to be done in IE but getting the same issue in Chrome also.

**Comment by chrisseto** [comment]
Please provider a link to the project.

**Comment by chrisseto** [comment]
@wisherp And make it public please.

**Comment by wisherp** [comment]
No longer seeing this issue, so am closing it for now.
