### ISSUE TITLE
[staging & production] Overflow for folderpicker confirmation section

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2466]
# Steps
1. Go to a project on which you have admin access
2. Enable an add-on which has folderpicker (Google Drive, figshare, Mendeley, Zotero, Box, Dropbox)
3. For whichever add-on you have selected (I found the problem after selecting Google Drive), go to the service's site and add a folder that has an extremely long name
4. In the folder picker, select that folder with the long name to connect to the project

# Expected
I expect that the name of the folder would wrap to fit within the borders of the confirmation section. 

# Actual
For Firefox, Safari, and Chrome, the folder name overflows.
Chrome/Safari: 
![screen shot 2015-04-13 at 12 19 07 pm](https://cloud.githubusercontent.com/assets/5975444/7120136/d7176e02-e1d8-11e4-8972-4ed19402446c.png)

Firefox:
![screen shot 2015-04-13 at 12 30 56 pm](https://cloud.githubusercontent.com/assets/5975444/7120173/2b02230e-e1d9-11e4-990f-9c0ab9052ac4.png)

**Comment by sloria** [comment]
Fixed on staging
