### ISSUE TITLE
Buttons on slide in footer do not lead anywhere

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2467]
<h3>Steps</h3>
1. Visit an OSF page while logged out.
2. On the footer that slides up from the bottom, click on the "Create an Account" or the "Learn More" buttons.

<h3>Outcome</h3>
1. The buttons do not link you to a new page, nor do they open a new tab.

<h3>Expected</h3>
1. The buttons should open a new tab with the desired URL.

**Comment by lbanner** [comment]
My guess it that these broke when we instituted the new log-in pages? Can we get a quick fix on this @chennan47 or maybe @Ghalko ?
