### ISSUE TITLE
[IE] Entering a blank email box

### ISSUE THREAD

**Issue by ginavuu** [CenterForOpenScience/osf.io#2468]
Steps
1. Log into your primary account on staging.
2. Go to user settings
3. Click the account settings tab
4. Enter nothing into the box above 'Add Email' button
5. Hit submit.

Expected
To get a message that email cannot be blank

Actual
The message does not appear after clicking submit,

**Comment by lbanner** [comment]
This is expected -- If you enter in a space (#) and click submit, you will get the error -- But the case simply clicking "add email" is highly improbable -- the use will just enter an email or not -- But I'll defer in the off chance this does become point of confusion. TY

**Comment by ginavuu** [comment]
Sounds good. Thanks.

**Comment by nanchen47** [comment]
This issue is now fixed.
