### ISSUE TITLE
No sign up link from navbar or sign in page

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2469]
<h3>Present Behavior</h3>
As a logged out user, the OSF only allows you to sign up via the homepage or by clicking on one of the buttons (<a href="https://github.com/CenterForOpenScience/osf.io/issues/2467">that don't work</a>) that appear in the pop up footer. This means that if you reflexively hide the footer and navigate the OSF by viewing projects and avoiding the homepage, you cannot create an account. 

<h3>Expected Behavior</h3>
Many sites have a sign up feature on the sign in page, or at least a link to the sign up page. I'd suggest adding this for ourselves so that users who browsed the site and then decided to create an account have an obvious way to do so.

Requirements:

-Add a Sign Up Button to the OSF Header
-Sign Up button should be distinct from the Login to avoid user error (different color)
-Sign up button should:
* open to allow the user to sign up to the OSF with their name, email, and password
* sign up rules are the same as implemented on the OSF homepage
* After signing up, users should follow the standard sign up onboarding process (email verification, land on dashboard, welcome modal + welcome email)

**Comment by sloria** [comment]
@jlcohoon Does the UI in https://github.com/CenterForOpenScience/osf.io/pull/2528 satisfy the requirements for this issue?

**Comment by jlcohoon** [comment]
@sloria Looks like it to me!

**Comment by jlcohoon** [comment]
This is happening again. The only place to sign up is the homepage—user should be able to easily find a sign up page.

**Comment by lbanner** [comment]
I get it, I think -- You mean, if I as a public user am exploring projects on the OSF, I should be able to easily find a sign-up for account option on any page, right? Did this change w/the implementation of the new homepage?

**Comment by jlcohoon** [comment]
Yes that is what I mean, and yes I do think it changed.

**Comment by jlcohoon** [comment]
Actually, I think what we did was have a sign up button on the log in page. That no longer exists.

**Comment by lbanner** [comment]
OK -- going to change this back to 'ready'
