### ISSUE TITLE
Cannot change primary email

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2470]
<h3>Steps</h3>
1. Visit your account settings on the OSF
2. If you do not have an alternate email set up already, add one
3. Click on "make primary" to the right of your alternate email. The picture below shows my settings before clicking on the make primary link.
![screen shot 2015-04-13 at 12 57 56 pm](https://cloud.githubusercontent.com/assets/4965832/7120784/b09a1b58-e1dd-11e4-8dff-3b446586aa61.png)

<h3>Outcome</h3>
1. An error shows up in the top right saying that the user profile was not updated.
2. The primary and alternate emails do switch places, but refresh shows that the swap did not take place
3. An error appears in the console
![screen shot 2015-04-13 at 12 58 03 pm](https://cloud.githubusercontent.com/assets/4965832/7120772/9faa0dda-e1dd-11e4-9cdc-31d207ecb0b4.png)

4. If you click "make primary" again—this is now next to the email that says it is alternate but is actually primary—an alert pops up saying that the email was made primary. This doesn't mean anything in reality because you have simply made the primary email primary
![screen shot 2015-04-13 at 1 01 36 pm](https://cloud.githubusercontent.com/assets/4965832/7120778/a674ba70-e1dd-11e4-854f-ef3f4ebd0c07.png)

<h3>Expected</h3>
1. It is confusing that even if the primary email was not successfully changed, it appears to have worked because they swap places. Furthermore, if I get an alert that it did not work, and I click the button again and am told that it did work, I might not pay enough attention to realize that it did not.
2. I would expect the alternate email that I want to make primary to become the primary email.

**Comment by lbanner** [comment]
@sloria -- This per-chance the same issue BrianN was dealing with in #2454?

**Comment by sloria** [comment]
Will look into this shortly

**Comment by GaryKriebel** [comment]
And just like yesterday, it is working as expected for me.

**Comment by GaryKriebel** [comment]
@jlcohoon did you get an email confirmation that you changed the primary email address?

**Comment by jlcohoon** [comment]
No email alerts, just the pop up notifications

**Comment by sloria** [comment]
@jlcohoon Are you still seeing any errors when switching the primary email?

**Comment by jlcohoon** [comment]
I am :(

![screen shot 2015-04-13 at 3 32 04 pm](https://cloud.githubusercontent.com/assets/4965832/7123748/57ff2992-e1f2-11e4-9ab3-7db02a8a077b.png)

**Comment by sloria** [comment]
Johanna had two accounts, `edb8y` and `yq4ke`. `yq4ke` was merged into `edb8y`; however, `yq4ke` still has a username set. Therefore, when changing the primary email to the gmail address, a validation error occurs because the uniqueness constraint on primary emails is violated. 

I've manually set the duplicate account's (yq4ke) username to `None`, which is consistent with the current merge procedure. @jlcohoon Can you try changing your primary email address again?

Previous logs show that these previously accounts went through a manual merge. @lyndsysimon Is there code to handle accounts that have already been merged?

**Comment by lbanner** [comment]
Good find @sloria -- though an edge case, there are likely others out there similar to this -- We should look into a catch here @lyndsysimon -- Thanks.

**Comment by chennan47** [comment]
Talked with @sloria yesterday. Actually we can write a migrate script to
fix this problem.

**Comment by GaryKriebel** [comment]
Sounds great, @chennan47 .... are you writing that script or someone else?

**Comment by jlcohoon** [comment]
@sloria it worked!

**Comment by GaryKriebel** [comment]
Will keep this open until the script is completed and run.

**Comment by nanchen47** [comment]
The script has already been merged into produciton.
