### ISSUE TITLE
[production] Replies to comments does not override project settings

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2473]
# Steps
1. Log in as user A on production
2. Go to your user settings
3. Click Notifications, then set 'Replies to your comments' to Emails
4. Go to one of your public projects
5. Go to Settings > Configure Commenting
6. Select the option *When the project is public, any OSF user can post comments* and press Submit
7. Go to Settings > Configure Notifications
8. Set 'Comments Added' to None
9. As user A, add a comment to your public project
10. In another window, log into production as user B
11. As user B, go to that public project and add a comment 
12. Now, add a comment as a reply to user A's comment

# Expected
I expect that user A would get one notification -- the notification of the second comment since it was a reply. I assume that global settings (replies to comments) override project settings (comments added). 

# Actual
User A receives **no** notifications. As expected, there is no notification for the comment added by user B that is not a reply. Unexpectedly, however, there is also no notification for the comment that was a reply to user A. 

@Ghalko is looking into this.

**Comment by Ghalko** [comment]
Not necessary to use a public project.

**Comment by lbanner** [comment]
I would actually expect the opposite @caileyfitz, as in: Project settings override the global settings, so that the user can make more specific adjustment for preference at the project level (and so the above would not be an error) -- Likely @samanehsan can give insight on expected functionality?

**Comment by Ghalko** [comment]
```notify``` in comments.py returns a list of subscribers including the one that the comment was in reply to. Except that I turned off all subscriptions, so I get a list of three that really aren't subscribed, but are returned into a variable that is called ```sent_subscribers``` which is a bit concerning. It looks like the logic in this case would never get to the second call of notify.

**Comment by caileyfitz** [comment]
@lbanner In our testing scenarios, we tested that users would still get replies even if the project settings were set to no notifications. Whether or not the current situation is desired behavior, it has changed since the last time this was checked.

**Comment by Ghalko** [comment]
@caileyfitz It seems to work on staging as expected. Please confirm.

**Comment by samanehsan** [comment]
The project settings for comments override the user level settings for comment replies. The reasoning was that if a user sets comment replies to None but configures comments for a project, any replies to their comments on that project should not be excluded from the notifications they receive.

**Comment by lbanner** [comment]
:+1: Appreciate the clarification - make sense - So I believe this is functioning as presently expected (even if there is sense of a change) @caileyfitz ? I'd like to close for now. Thanks.

**Comment by caileyfitz** [comment]
Oh... Maybe I got confused about something else. I'll close this.
