### ISSUE TITLE
[Staging & Production] Dataverse: Delete fails when trying to delete a draft file

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2474]
## Steps
1. Go to a public project with Dataverse authorized (link: https://osf.io/9jtkg/ )
2. Go to the files tab
3. Switch the Dataverse folder from Released to Draft
4. Wait for the folder to re-load with draft files
5. Click on the red 'x' next to a file to delete it
6. Hit 'OK' to confirm

## Expected
That a dataverse draft file can be deleted from the files tab

## Actual
There is an error in the file grid stating that 'Delete failed'. Also the console reports a 500 error.

![screenshot 2015-04-13 14 36 20](https://cloud.githubusercontent.com/assets/9381062/7122722/3d3b595c-e1eb-11e4-92ef-bfc4b2bae79b.png)

**Comment by lbanner** [comment]
@rliebz  -- Thoughts? Are we yet running into new version/API issues? Thanks.

**Comment by rliebz** [comment]
The http://thedata.harvard.edu (the Dataverse server we're connected to) has just changed to read-only mode as Dataverse 4.0 is going live. There are a number of backwards incompatible changes that prevent us from using 4.0 in its current state, so the OSF will not be able to upload or delete files until we we merge https://github.com/CenterForOpenScience/osf.io/pull/2426 and the corresponding waterbutler PR, https://github.com/CenterForOpenScience/waterbutler/pull/32.

**Comment by GaryKriebel** [comment]
@sloria with Dataverse 4.0 going live, can we get this included?

**Comment by pdurbin** [comment]
I'm hoping #2426 can be merged soon. @rliebz has done some fantastic work. See also #1219.

**Comment by lbanner** [comment]
Agreed @pdurbin -- working it in --- and appreciate the support you have provided here! Thanks!

**Comment by rliebz** [comment]
The read-only issue is resolved, but we will still run into some unintuitive behaviors while https://github.com/IQSS/dataverse/issues/1784 is still open.

Essentially, after publishing a dataset, you have to upload at least one file before you can delete any files.

**Comment by samanehsan** [comment]
@nicipfeiffer, was this error only when trying to delete draft dataverse files through the files grid? Or were you also getting errors when deleting files from the file detail page? 

Right now, there is no option to delete draft dataverse files through the files grid and deleting from the file detail page is successful.

**Comment by samanehsan** [comment]
Closing since dataverse draft files can now be successfully deleted from the files tab.
