### ISSUE TITLE
[Staging & Production] Google Drive Folders: incorrect error handling with file upload to deleted folders

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2480]
## Steps
1. Go to a project you have admin privileges on
2. Configure the Google Drive Add-on
3. Import Access token
4. Link a folder with no files in it
5. Log in to Google Drive in a separate tab
6. Delete the folder that you have linked on the OSF project
7. Go to the trash folder in GDrive
8. Click on the folder again
9. Click to 'permanent delete' the folder, confirm
10. Return to the OSF project with the now deleted GDrive folder linked
11. Go to the Files Tab
12. Upload a file to that folder

## Expected
I would first, not expect the folder to be listed in the folder tree on the files tab.  In attempting to upload the file, an error that the folder has been deleted should be given to the user.

## Actual
The folder is in the file tree for the project on the files tab.
When attempting to upload a file to the folder, an error "Could not upload file. The file may be invalid.' is given to the user, which is incorrect.  And the console reports a 404, not found error.

![screenshot 2015-04-14 09 54 33](https://cloud.githubusercontent.com/assets/9381062/7138128/4cfa886c-e28c-11e4-9853-501c6fd14337.png)

**Comment by GaryKriebel** [comment]
@nicipfeiffer staging / production / both ?

**Comment by nicipfeiffer** [comment]
@GaryKriebel It happens on both.

**Comment by lbanner** [comment]
@nicipfeiffer When you "Return to the OSF project with the now deleted GDrive folder linked" did you refresh the page? We may be able to improve the error messaging, but there'd be no way for the page to know the folder was deleted unless you refresh. Now if you refresh and the deleted folder is still there -- that is a problem.

**Comment by nicipfeiffer** [comment]
@lbanner Yes, the folder is still showing in the grid after refresh.

**Comment by lbanner** [comment]
Uh Oh ... OK. Thanks.

**Comment by nicipfeiffer** [comment]
@lbanner The folder shows only after deletion, if it is the selected folder in the folder picker.

**Comment by chennan47** [comment]
Although the folder is removed in google drive, it just moved to the Trash tab and you still have the option to restore it or delete forever. You can still see that folder in OSF file page and upload files to it. When that folder is restored from trash tab, the files you upload through OSF are inside it.

However, if you delete that folder forever from google drive trash tab. You still can see the folder on OSF file page after refresh but with no file inside. But you will not be able to upload files to that folder anymore. It will give an error warning.

**Comment by lbanner** [comment]
@chennan47 Do you think we can clean this communication up further? At least such that, if you delete the folder forever from google drive trash tab, after refresh on OSF, the folder will not longer exist?

**Comment by chennan47** [comment]
https://github.com/CenterForOpenScience/osf.io/pull/2588 partially solves the current issue by improving the warning message. But the delete folder will be still showing up on the file page. We can make external request to verify the folder's existence but it will slow down file page's rendering. 

Talked with @sloria @lbanner, after https://github.com/CenterForOpenScience/osf.io/pull/2588 is merged. Put this issue to Hold
