### ISSUE TITLE
[staging & production] Citations widget not updated until refresh after DOI creation

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2486]
# Steps
1. Go to a project that you have admin on
2. Make a registration of the project
3. Make the registration public
4. Go to the project overview page for the registration
5. Click 'Create DOI/ARK' in the Identifiers widget
6. Confirm that a DOI/ARK is now shown after Identifiers on the project overview page
7. Go to citations widget on project overview page, click to expand

# Expected
I expect that the appropriate citations would now include the DOI/ARK identifiers

# Actual
The citations do not include DOI/ARK identifiers until after page refresh. This is potentially confusing for users because it is not necessary for a page refresh for the DOI/ARK identifiers to appear on the project overview page, so it makes sense to assume that they would show up in the citation widget without refresh as well.

**Comment by lbanner** [comment]
I think this will have to function in this manner -- Citations are generated based on a call of some sort, so a refresh will be required. But it is good thinking re: better usability, so I'll defer rather than close. Thanks.

**Comment by samchrisinger** [comment]
This might be a very quick fix. I believe we're already loading this asynchronously.

**Comment by lbanner** [comment]
I'll take your word on that -- Let me know what you find out. Thanks.

**Comment by samchrisinger** [comment]
Should be as simple as calling ViewModel#fetch: https://github.com/CenterForOpenScience/osf.io/blob/develop/website/static/js/citationList.js

**Comment by lbanner** [comment]
Want it? -- or maybe @chennan47 ? Thank you!

**Comment by samchrisinger** [comment]
If @chennan47 isn't busy, that'd be great.

**Comment by rohan-bajaj** [comment]
I'll grab this one. @lbanner

**Comment by GaryKriebel** [comment]
@rohan-bajaj .... all yours
