### ISSUE TITLE
[staging & production] Unclear on how to resend email confirmation

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2487]
# Steps
1. Log into staging
2. Go to the user settings page
3. Click on Account Settings
4. Add an email address that is not already associated with your account
5. Check that it is added to the list of Unconfirmed Emails
6. Go to your email and delete the confirmation email
6. Input the same email address again and press 'Add Email' to resend confirmation email

# Expected
I think it would be helpful if there were some option to resend the confirmation email if the initial one is lost. Maybe in addition to the Duplicate email growlbox error, there could be some information on how to resend the email. Or some information tooltip at the top of the section? 

# Actual
There is no clear way to resend a confirmation email. The only way to do it currently is to remove the email from the list of Unconfirmed emails and then add it again. This is not really intuitive and users may not even think of this (I didn't until Steve suggested it).

**Comment by lbanner** [comment]
@chennan47 Do you want to take this on now as an enhancement to the multiple email functionality? Thanks -
