### ISSUE TITLE
[Production & Staging] Improve error handling for expired tokens in project settings for box add-on

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2495]
## Steps
1. Log in to staging or production
2. Go to a project you have admin access on 
3. Go to the project settings
4. Authorize the box add-on and import an access token
5. Link a folder in the folder picker to the project
6. Confirm success message for the folder
7. Go to box.com
8. Click on your name in the upper right
9. Choose 'Account Settings in the dropdown list
10. On the account page, scroll down to the 'Password Information' section
11. Click to 'edit password'
12. Enter the old password, new password and confirm password.  
13. Click the checkbox next to "Log out of all Box applications using this account." and hit 'Submit'
14. Now return to the project files tab
15. Click the '+' to expand the box linked folder (make note that there is a folder linked and it's name)
16. Go to the project settings page, go to the box folder picker
17. Make note of the Selected folder as 'none'
18. Click on the deauthorize link
19. Click to import access token

## Expected
There would be a message to the user on the files tab indicating why the folder cannot be expanded and no files can be shown.
The only available option on the project settings page is to deauthorize, then to import access token.  In doing so, the user should be told that the user settings needs to be updated for the box add-on.
The project setting page would give some useful information indicating what the problem is; why files aren't available.

## Actual
There is an error in the console of a 401 (Unauthorized), but nothing for the user to know what is the problem.
If the user went to the project settings page to look into this further, they would see that the folder selected in 'None' and have no option to change the folder (the folder picker will not appear). If the user clicks to deauthorize then import an access token, the folder picker just loads forever and in the console there is a 404 (NOT FOUND) error.
In the user settings, when this occurs the error message is much more useful: "Could not retrieve Box settings at this time. The Box add-on credentials may no longer be valid. Try deauthorizing and reauthorizing Box."
![screenshot 2015-04-15 14 52 10](https://cloud.githubusercontent.com/assets/9381062/7166913/09c1cecc-e37f-11e4-986e-8210cf3bab90.png)

![screenshot 2015-04-15 15 12 23](https://cloud.githubusercontent.com/assets/9381062/7167347/4ff79fe0-e382-11e4-9472-0c004c6119ec.png)

**Comment by nicipfeiffer** [comment]
Also, the same happens with S3. Except the dropdown that is in the project settings instead of the folder picker is blank. 
![screenshot 2015-04-15 16 11 24](https://cloud.githubusercontent.com/assets/9381062/7168267/1e9fc1fe-e38a-11e4-8fef-7d63512de7f5.png)

So, if the user did not know that the access token had expired, then they would go to the project settings and try to change the bucker linked in S3 and see that it is blank. 
Again, improve the error message to the user.
Going to the user settings doesn't tell the user any information.  In fact, it tells the user that everything is ok and the project is in the 'Authorized Projects' list
![screenshot 2015-04-15 16 13 15](https://cloud.githubusercontent.com/assets/9381062/7168306/814bfe76-e38a-11e4-8fc1-d4fbc56ee04c.png)

**Comment by lbanner** [comment]
@samchrisinger ... wonder if you are overcoming this user issue w/ #2414?

**Comment by samchrisinger** [comment]
This feels beyond the scope of that PR. 

We might address this in a number of places, but likely each of the addons' node-settings javascript will need to incorporate some better error handling.

**Comment by lbanner** [comment]
OK

**Comment by lbanner** [comment]
Looks like I can close this, yes @samchrisinger ? Due to merge of #2523?
