### ISSUE TITLE
No confirmation before removing alternate email

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#2496]
Unlike other "destructive" actions on the site, clicking the "x" to delete an alternate email does not have any confirmation dialog.

**Comment by lbanner** [comment]
Good catch: @nanchen47 or @lyndsysimon ?

**Comment by chennan47** [comment]
This is an easy fix. Will address this after I finished the disk storage
mode update.

**Comment by lbanner** [comment]
Thanks!
