### ISSUE TITLE
No visible validation for create user form 

### ISSUE THREAD

**Issue by samchrisinger** [CenterForOpenScience/osf.io#2498]
![screen shot 2015-04-15 at 3 42 38 pm](https://cloud.githubusercontent.com/assets/2207561/7167778/25f7617c-e386-11e4-9bcd-7d4cb7fbcc3a.png)

In the image above, my emails mismatch. I click 'Sign Up' but get no indication that my info is malformed. 

Broken on Prod and Staging.

**Comment by samchrisinger** [comment]
@GaryKriebel @lbanner 

This may be high priority.

**Comment by lbanner** [comment]
This introduced somehow new? -- or has it always been that way? @HarryRybacki This arena you coded in previously? -- got insight and/or do you want to take on? Thanks.

**Comment by sloria** [comment]
It's faint, but there is a red outline around the invalid email field. This should certainly be made more visible with an error message though.

**Comment by lbanner** [comment]
Yeah, that's awfully subtle :smile_cat:

**Comment by sloria** [comment]
Looking into this.

**Comment by HarryRybacki** [comment]
I never got around to changing this section of the code. Has something changed or has it always been like this?

**Comment by sloria** [comment]
Error messages used to display next to the input fields.
