### ISSUE TITLE
Zotero Group Library integration

### ISSUE THREAD

**Issue by evomellor** [CenterForOpenScience/osf.io#2505]
Currently, only personal Zotero libraries are supported in OSF, but a great feature of Zotero over Mendeley is that their group collaboration libraries are free. When possible, please add support for Zotero group libraries. Thank you!

**Comment by lbanner** [comment]
Good thought -- on the list @evomellor -- Thank you.

**Comment by saradbowman** [comment]
+1 help desk request

**Comment by pkraker** [comment]
This feature would be most helpful for collaborative projects.

**Comment by sebkopf** [comment]
I agree, this feature would make OSF integration with zotero much more useful for collaborative projects
