### ISSUE TITLE
[staging & production] Google Drive deletion logs do not handle non-ascii characters

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2509]
# Steps
1. Log into staging
2. Go to a project on which you have admin access
3. Go to the settings tab
4. Enable and configure Google Drive for the project
5. Go to the files tab
6. Upload a file with non-ascii characters in the file name to Google Drive
7. After successful upload, delete the file from Google Drive
8. Go to the project overview page and look at the log

# Expected
I expect that the log would correctly note what file was added and removed, with correct rendering of the file name. 

# Actual
The file name is rendered correctly for the file added log but has weird characters (HTML escapes?) for the file removed log. See below: 
![screen shot 2015-04-16 at 1 42 21 pm](https://cloud.githubusercontent.com/assets/5975444/7187644/09bad704-e440-11e4-967b-6a8a2bed70e8.png)

Additionally, the deleted file name looks like it is a link, but pressing it goes nowhere. It should not be blue and underlined.

**Comment by caileyfitz** [comment]
This also affects folder names in Google Drive: 
![screen shot 2015-04-16 at 1 57 03 pm](https://cloud.githubusercontent.com/assets/5975444/7187698/81fc46e4-e440-11e4-8fdb-5a2e5af4c759.png)

**Comment by hmoco** [comment]
The issue mentioned above doesn't happen anymore/is not reproducible. However, the folder name mess up still happens on the settings page only. I have fixed that, and am now on the process of testing to make sure my fix doesn't break anything else.

**Comment by lbanner** [comment]
Cool @hmoco -- when you get coding solution done, go ahead and still reference this issue # in your PR. Thanks.

**Comment by hmoco** [comment]
Would this be considered a feature fix or a hotfix?

**Comment by lbanner** [comment]
"feature fix" -- merged to Develop @hmoco

**Comment by hmoco** [comment]
As @caileyfitz has pointed out, this has been solved, while my fix is actually for #2537, so this should be closed. I have update the pull request to reflect that. Sorry for the confusion.

**Comment by lbanner** [comment]
OK
