### ISSUE TITLE
[Staging and Production] Some Files are Rendering and Extending Pass the Window

### ISSUE THREAD

**Issue by ginavuu** [CenterForOpenScience/osf.io#2511]
#Steps
1. Go to https://staging.osf.io/f6wxz/

#Expected 
The file should render so that everything is within the window without needing to scroll like a normal word doc

#Actual
Some files render with lines extending pass the window.

![extended](https://cloud.githubusercontent.com/assets/11032617/7188705/c3bd2eac-e447-11e4-9ac7-fcf4fa621c62.PNG)

**Comment by caileyfitz** [comment]
Also happening for me on production!! 
![screen shot 2015-04-16 at 3 48 56 pm](https://cloud.githubusercontent.com/assets/5975444/7189878/1c4b4cae-e450-11e4-9bda-2a79e623de07.png)

**Comment by brianjgeiger** [comment]
Once again wondering if we can come up with a generalized solution for this. It happens 2 or 3 times per epic with various renderers. Possibly the MFR refactor will fix, or possibly not, but we should probably put some effort to ending this properly.

**Comment by lbanner** [comment]
Still exits on Production with .xlsx files as well -- and is noticeable as well w/new File-Index-View functionality..

**Comment by GaryKriebel** [comment]
This issue is also discussed in 
https://github.com/CenterForOpenScience/osf.io/issues/1606

WIll close this issue and track progress there.
