### ISSUE TITLE
Public Profile Plus Sign

### ISSUE THREAD

**Issue by Ghalko** [CenterForOpenScience/osf.io#2514]
## Steps
1. Go to public profile with at least one project.
2. Click on the '+'

## Expected
Displays recent activity

## Actual
Displays only the string "A user"

**Comment by GaryKriebel** [comment]
@Ghalko ..... what browser .... and perhaps a screenshot?  I don't seem to be getting the error in Chrome, but I may also not be testing the same way you did.

**Comment by Ghalko** [comment]
Changed issue to match production and staging issue.

**Comment by GaryKriebel** [comment]
I'm not sure what is going on with this issue.  I see that behavior on both stating and productions, but no my local instance.

**Comment by nicipfeiffer** [comment]
I am also seeing this on staging and production.
![screenshot 2015-04-17 11 30 49](https://cloud.githubusercontent.com/assets/9381062/7205163/4158b090-e4f5-11e4-9b86-9f28d9b637a3.png)

**Comment by GaryKriebel** [comment]
Well... I WASN"T seeing it on my local system (@Ghalko saw it) .... I AM seeing that behavior on my local system now with latest develop.

![screen shot 2015-04-17 at 11 48 49 am](https://cloud.githubusercontent.com/assets/9437946/7205493/bc177f26-e4f7-11e4-98dd-e76749e9da4c.png)


If I pull @HarryRybacki "add_registration_retraction" code, it DOES work.

![screen shot 2015-04-17 at 11 47 12 am](https://cloud.githubusercontent.com/assets/9437946/7205465/8f1ef09e-e4f7-11e4-98c5-ceb11d022fd5.png)

**Comment by nanchen47** [comment]
This pr already go on production and I verify this issue has been fixed.
