### ISSUE TITLE
Login from home page does not work with 1Password

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2517]
Steps
-------
1. On a machine with 1Password (and possibly other password managers, though not LastPass(see comments)), log out.
2. Go to https://osf.io/
3. Hit command-\ to fill in password

Expected
------------
Sign-in fields would be filled in.

Actual
--------
Login fields are filled in.

![screen shot 2015-04-17 at 10 49 14 am](https://cloud.githubusercontent.com/assets/6599111/7204374/957274d2-e4ef-11e4-8680-5e5c8b3bcea9.png)

**Comment by GaryKriebel** [comment]
@brianjgeiger ... is this browser specific with 1Password?

**Comment by GaryKriebel** [comment]
LastPass fills in the information in the correct place, BTW.
![screen shot 2015-04-17 at 11 11 44 am](https://cloud.githubusercontent.com/assets/9437946/7204765/ba3888ee-e4f2-11e4-8940-5a41e908805c.png)

**Comment by brianjgeiger** [comment]
Could very well be. 1Password is the only password manager I use.

**Comment by sloria** [comment]
Hm, been using 1Password on the OSF, and it's been working correctly.

**Comment by brianjgeiger** [comment]
Okay, I'll try updating.

**Comment by brianjgeiger** [comment]
No still happens to me. To be clear, this only happens on the OSF home page (and possibly the sign-up page, if there's a separate one).

**Comment by brianjgeiger** [comment]
I have just verified with @sloria that he does have the same problem that I do.

**Comment by sloria** [comment]
This should help: https://support.1password.com/compatible-website-design/

**Comment by leb2dg** [comment]
Looking into this.

**Comment by brianjgeiger** [comment]
Yay!

**Comment by lbanner** [comment]
:+1:
