### ISSUE TITLE
[staging & production] figshare file downloads do not keep name

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2518]
# Steps
1. Log into staging or production
2. Go to a project on which you have admin access
3. Go to the settings page for that project
4. Enable figshare and configure for project by linking a folder
5. Go to the files tab
6. Click on a file to view it in the files detail page
7. Click on the download button on the right hand of the screen to download the file
8. Go back to the files tab
9. Click to download the same file from the files tab 

# Expected
I expect that downloading the file would yield the same results in both places, whether in the files tab or file detail page.

# Actual
Downloading a file from the files detail page works as expected, and the file is downloaded with the correct name. Downloading a file from the files tab, however, does not keep the file name and instead downloads all files as file.extension (file.png, file.pdf, file.jpeg, etc).

**Comment by chennan47** [comment]
@chrisseto has already fixed this in the new waterbulter.

**Comment by lbanner** [comment]
Deployed @chennan47 and @chrisseto ? So I can close ... (?)

**Comment by chennan47** [comment]
@lbanner talked with @chrisseto. It needs a while to be ready.

**Comment by lbanner** [comment]
OK - thanks.

**Comment by chrisseto** [comment]
Can anyone confirm this is fixed?

**Comment by lbanner** [comment]
@caileyfitz can you do a double check here? Thanks

**Comment by caileyfitz** [comment]
@lbanner @chrisseto Yes, this is fixed!
