### ISSUE TITLE
[staging & production] Project deletion logs incorrectly list file name for figshare

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2520]
Probably related to #2509 

# Steps
1. Log into staging or production
2. Go to a project on which you have admin access
3. Go to the settings page for that project
4. Enable figshare and configure for project by linking a folder
5. Go to the files tab
6. Upload a new file to figshare
7. After upload, click the red x to delete the file you just uploaded 
8. Confirm that you want to delete the file
9. Go to the project log

# Expected
I expect that the log would correctly note what file was added and removed, with correct rendering of the file name.

# Actual
The file name is rendered correctly for the file added log but lists numbers rather than the file name for the file removed log. See below: 
![screen shot 2015-04-17 at 11 13 26 am](https://cloud.githubusercontent.com/assets/5975444/7205252/febaa152-e4f5-11e4-8669-76a449452926.png)

**Comment by lbanner** [comment]
I think some work has been done to translate number designations for certain add-ons to names, yes? -- possibly we have not captured all instances.

**Comment by chennan47** [comment]
This is a waterbulter problem. Maybe @chrisseto has made some changes https://github.com/CenterForOpenScience/osf.io/blob/develop/website/addons/figshare/model.py#L206 the metadata comes back from waterbulter only has {'path': 'file id/id'} in it.

Another related problem is that if you have figshare enabled on production or staging. Link some figshare folder and visit file page. You will get an error
![screen shot 2015-04-18 at 1 36 23 pm](https://cloud.githubusercontent.com/assets/4974056/7216509/f0cc1410-e5cf-11e4-939e-50d503091e82.png)

It actually points to https://github.com/CenterForOpenScience/osf.io/blob/develop/website/static/js/fangorn.js#L846
here the value of the file is none. It can be an easy fix like

if (file && file.provider === 'figshare') {
        for (var i = 0; i < tree.children.length; i++) {
            var child = tree.children[i];
            if (nodeID === child.data.nodeId && child.data.provider === file.provider && child.data.path === file.path) {
                tb.currentFileID = child.id;
            }
        }

But @chrisseto is more expert here. Thoughts?

**Comment by lbanner** [comment]
@chrisseto  Your insight here: Should this be posted to WaterBulter Issues?

**Comment by chrisseto** [comment]
@lbanner this should be resolved as of moving/copying.

**Comment by lbanner** [comment]
Cool - closing
