### ISSUE TITLE
[staging & production] Cannot authorize Google Drive for a project

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2522]
**This only happens for *some* projects... not sure the distinguishing features that cause this to fail**

# Steps
1. Log into either staging or production
1. Go to user settings and delete the access token for Google Drive
2. Go to a project on staging where you have admin access
3. Enable Google Drive
4. Click to create an access token
5. Go through the steps to allow OSF access 
6. Press 'Accept' to authorize OSF access to Google Drive

# Expected
I expect that going through these steps would enable and connect Google Drive to a project.

# Actual
The user is faced with a 500 error displayed as JSON: 
![uu](https://trello-attachments.s3.amazonaws.com/55282d29bed2788b6a714c7b/600x107/bea138acbc591ee80271478e022defd5/Screen_Shot_2015-04-10_at_4.16.29_PM.png)

More info:
![screen shot 2015-04-17 at 1 54 09 pm](https://cloud.githubusercontent.com/assets/5975444/7207690/55ef25ac-e509-11e4-830b-ace8b6e84cbd.png)

In the very least, the error should be handled and not be displayed as JSON, even if we cannot identify the problem at this point.

@icereval and @chrisseto spent a lot of time last Friday looking at this and said they had it figured out... but the problem has returned :angry:

**Comment by lbanner** [comment]
@chrisseto @sloria -- Is this a regression due to any recent changes/deployments -- Insight? Hate to repeat again. Thanks.

**Comment by caileyfitz** [comment]
Was just able to duplicate this on **production** with my project *42 Wallaby Way & P. Sherman and my personal gmail account.

**Comment by jinluyuan** [comment]
I just reproduced this issue in User Settings on *staging*. After I tried again, it worked. 
![screen shot 2015-07-30 at 3 59 26 pm](https://cloud.githubusercontent.com/assets/8591162/8993641/2444989e-36d4-11e5-8520-835544f05e1d.png)

**Comment by chrisseto** [comment]
This is likely an issue with sessions, @lyndsysimon any thoughts?
We may just want to add a scratch field to the User object to store intermediate values that are being dropped in these cases.
