### ISSUE TITLE
[Production] [Presentation Service] Listed as a contributor on projects and has Profile

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2530]
## Steps
1. Log into production
2. Go to https://osf.io/rsfbq/
3. Look at the contributors listed on the project
4. Hover over the 'Presentation Service' contributor. Notice the tooltip.
5. Click on the magnifying glass in the navbar to search
6. In the search bar enter 'Presentation Service'
7. Click on the users filter on the left
8. Click on the user 'Presentation Service'
9. Click on the only public project listed on the user profile page (Repetitive Extragenic Palindromic PCR (rep-PCR) of Oral Streptococci using DiversiLab™)

## Expected
If a user uses the email presentation service to submit a poster or talk I would not expect that the presentation service would be listed as a contributor on the project, or have a tooltip for user claiming.
I would not expect that the Presentation Service would have a user profile page and have a project listed on the user profile page.

## Actual
The Presentation Service is a listed contributor on projects creating using the service.
The Presentation Service has a user profile.

![screenshot 2015-04-20 09 49 28](https://cloud.githubusercontent.com/assets/9381062/7231314/903f769a-e742-11e4-92cb-332403a729ea.png)

![screenshot 2015-04-20 09 48 55](https://cloud.githubusercontent.com/assets/9381062/7231298/7eea7eee-e742-11e4-91e2-f6b96882798a.png)

**Comment by nicipfeiffer** [comment]
Linking this issue, as it mentions similar findings. https://github.com/CenterForOpenScience/osf.io/issues/2447

**Comment by GaryKriebel** [comment]
@nanchen47 is this covered in your recent Presentation Service fixes?

**Comment by nanchen47** [comment]
https://github.com/CenterForOpenScience/osf.io/issues/2530
