### ISSUE TITLE
[Production] [Presentation Service] User Profiles created from Spam to service

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2532]
## Steps
1. Go to osf.io
2. Click on the magnifying glass in the navbar
3. Enter 'seo' in the search bar
4. Click on Users to see the users returned

## Expected
That spam to the presentation service would not create user profiles

## Actual
Spam to the presentation service is creating user profiles

![screenshot 2015-04-20 09 55 06](https://cloud.githubusercontent.com/assets/9381062/7231462/590e50c8-e743-11e4-8c56-199b156d987a.png)

Some that I have found that are likely spam:
https://osf.io/7wyv4/
https://osf.io/93jwg/
https://osf.io/9rpyk/
https://osf.io/bev4i/
https://osf.io/btgev/
https://osf.io/eyvj7/
https://osf.io/i97kl/
https://osf.io/izsmz/
https://osf.io/k28s4/
And lots more...

**Comment by lbanner** [comment]
Ugh ... that is not good at all! Can we assume that is is "Spam to the presentation service" ? -- or might there be other ways a spam account can be created. I set priority High for this @sloria -- insight?

**Comment by GaryKriebel** [comment]
@nanchen47 is this covered in your recent Presentation Service fixes?

**Comment by chennan47** [comment]
@JeffSpies @sloria This is the user who is spamming osf to create user thro presentation service. I checked all his project is private. But this user is shown up in the search. Any thought on what we want to deal with this?

**Comment by JeffSpies** [comment]
Nan, are they still showing up in search?

**Comment by chennan47** [comment]
@JeffSpies Those users are sill showing up in search. Should you deactive those user or just make them disappear from search?

**Comment by JeffSpies** [comment]
Let's have Michael disable the user and remove them from search. The spam
service should help on this in the future.

**Comment by samanehsan** [comment]
Ping @icereval

**Comment by icereval** [comment]
I've disabled all SEO spam users found in search and most of the users listed in the issue with a few exceptions which could be real users or organizations.

https://osf.io/i97kl/
https://osf.io/bev4i/
https://osf.io/9rpyk/

Our current spam system did mark most of the user's as spam however this only prevents the project from being made public by default via the conference service, not the user showing up in search results.
