### ISSUE TITLE
[staging & production] Plus sign for Create a Project is misaligned

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2535]
# Steps
1. Log into staging or production
2. Look at the onboarder to the right of the project organizer

# Expected
I expect all UI to be consistent.

# Actual
The plus sign next to **Create a Project** is misaligned: it should be at the top of the box, rather than the bottom. All other plus/minus signs are aligned at the top of their boxes:
![screen shot 2015-04-20 at 3 44 34 pm](https://cloud.githubusercontent.com/assets/5975444/7238955/34209fec-e774-11e4-9f08-b65bc4f11547.png)

**Comment by samanehsan** [comment]
Closing, since this is a repeat of #2062

**Comment by lbanner** [comment]
Thank you - Good catch.
