### ISSUE TITLE
[staging & production] Google Drive folder names with special characters, ([]()#&<>) listed incorrectly in folder picker

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2537]
## Steps
1. Go to a project that you have admin priveleges on
2. Go to the project settings tab
3. Authorize the Google Drive Add-on, import access token, link a folder/repo/bucket/project
4. Go to the files tab
5. In the Google Drive folder, click on the '+' to create another new folder
In the modal
6. Enter the name of the folder using '&' in the name
7. Click Ok
8. Look at the project log
9. Go to the settings page
10. Click 'Change' in the settings for Google Drive to display folder picker
11. Find the folder just created

## Expected
The project log would have the correct name of the folder
The folder picker would have the correct folder name as entered in the modal

## Actual
The '&' is written as '%20%26%20' in both the log and folder picker folder tree

Even though @sloria mentions that this will be fixed by #2231, which is scheduled for 0.33, I wanted to put it on GH so we didn't forget about it.

**Comment by hmoco** [comment]
Like https://github.com/CenterForOpenScience/osf.io/issues/2509 this has also been fixed.

**Comment by lbanner** [comment]
@hmoco -- Did you submit a PR for these fixes? Can you remind me (note here) the GH # for that PR? Thanks.

**Comment by hmoco** [comment]
No, this was not fixed by me, it might have been fixed by Steve or just a byproduct of something else

**Comment by caileyfitz** [comment]
@hmoco Where are you seeing the fix? I still have the problem in staging & production 
![screen shot 2015-05-27 at 10 31 37 am](https://cloud.githubusercontent.com/assets/5975444/7838590/a4ccecba-045b-11e5-935b-b33f371df5cd.png)

**Comment by caileyfitz** [comment]
@hmoco Where are you seeing the fix? This is not resolved in staging or production for me: 
![screen shot 2015-05-27 at 10 31 37 am](https://cloud.githubusercontent.com/assets/5975444/7838683/3bd6d486-045c-11e5-9a35-5c2724142415.png)

**Comment by hmoco** [comment]
@caileyfitz This is what I see on both staging and production

![screen shot 2015-05-27 at 11 10 33 am](https://cloud.githubusercontent.com/assets/6268982/7839567/107d6408-0461-11e5-9051-c1a62daa411d.png)

**Comment by hmoco** [comment]
Just checked with Haoyu and he gets the same behavior I do on Google folders.

**Comment by caileyfitz** [comment]
@hmoco Steps 9-11 are not resolved, as they relate to the folder picker in the Settings page.

**Comment by hmoco** [comment]
@caileyfitz Yep, you're right, I skipped those steps... my bad. Will change pull request to reflect that.

**Comment by samanehsan** [comment]
Closed by #2964.
