### ISSUE TITLE
[staging & production] Box does not list deleted folder name

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2539]
# Steps
1. Go to a project that you have admin priveleges on
2. Go to the project settings tab
3. Authorize the Box Add-on, import access token, link a folder
4. Go to the files tab
5. In the Box folder, click on the '+' to create another new folder
6. Enter the name of the folder
7. Click Ok
8. Now, delete the folder
9. Look at the project log

# Expected
The project log would list the name of the deleted folder, just as it does for other add-ons.
![sf](https://trello-attachments.s3.amazonaws.com/552d5ab92d89277a4e366881/526x94/5b7c908b31b009fcb09839d4a557cd8f/Screen_Shot_2015-04-14_at_2.23.11_PM.png)

# Actual
Instead of listing the folder name, the log reads
![yy](https://trello-attachments.s3.amazonaws.com/552d5ab92d89277a4e366881/522x34/e95d90970ac9de616c591de40b7caeac/Screen_Shot_2015-04-14_at_2.25.07_PM.png)

@chrisseto notes that files in Box have the same behavior

**Comment by hmoco** [comment]
Apparently this is a result of the water_butler logging system not getting the folder name when deleting a folder from box. Chris mentioned this is being worked as a low priority item, but it is not inherently a osf problem.

**Comment by lbanner** [comment]
@chrisseto should we remake this in WaterButler and close this issue here? Thanks.

**Comment by chrisseto** [comment]
This should no longer be an issue

**Comment by lbanner** [comment]
Cool -- Thanks -- I'll close.

**Comment by chrisseto** [comment]
Well, wait for the release to verify :P
