### ISSUE TITLE
[Production & Staging] Dataverse: Deleting a Published version of a file is allowed, but not really.

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2541]
## Steps
1. Go to a project with dataverse configured
2. Click to view a published file that is also in draft version
3. Click on the delete button the files detail page
4. Confirm that you want to delete the file
5. Return to the Files tab
6. Look for the file in the grid under Published files

## Expected
Completing the steps to delete the published version of a file should not be allowed since those are read-only. Returning to the file tab and seeing the file remain when the steps for deleting were completed with no errors.

## Actual
By completing the steps with no errors, the user is led to believe that they in fact, deleted a published file.  However, they only deleted the draft version of the file.

**Comment by lbanner** [comment]
@nicipfeiffer After the steps above, is the Published file still visible? But not any longer the Draft file?

**Comment by nicipfeiffer** [comment]
@lbanner Yes, the published file is still visible.  The draft file is now deleted.  The inconsistency, in my opinion, is that the user is completing the deleting action from the published file.  I think this is misleading.

**Comment by lbanner** [comment]
@rliebz Did your resolving commit here get merged into Production? Thanks.

**Comment by rliebz** [comment]
I'm bundling the commit with a few other changes, which includes a better distinction between draft/published files and some related permissions fixes. Still a WIP.

**Comment by lbanner** [comment]
OK cool :+1:

**Comment by caileyfitz** [comment]
@lbanner @GaryKriebel This has regressed. I am seeing a Delete button on the files detail page for my published Dataverse files. I think we need to reopen this.

**Comment by lbanner** [comment]
Ugh - got it.

**Comment by lbanner** [comment]
@caileyfitz can you have a QA team member replicate to verify? Thanks.

**Comment by nicipfeiffer** [comment]
@lbanner and @caileyfitz I am also seeing the delete button on the files detail page.
![screenshot 2015-08-21 15 14 05](https://cloud.githubusercontent.com/assets/9381062/9417062/54a942a6-4817-11e5-8838-07b58ba79f2a.png)
