### ISSUE TITLE
[Production & Staging] Dataverse: Citation gives draft version after a published dataset

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2542]
## Steps
1. Go to https://osf.io/9jtkg/
2. Look at the dataverse widget
3. Notice the citation listed

## Expected
The citation to give accurate information about the dataverse dataset linked to the project

## Actual
 The citation has DRAFT VERSION at the end, indicating it is in a draft state and not published.  This is incorrect, the dataset it published
![screenshot 2015-04-21 10 09 16](https://cloud.githubusercontent.com/assets/9381062/7254041/7ed80b7a-e80e-11e4-8e45-65ef4b7ec634.png)

## Notes
A comment from @rliebz on the citation given:
It is possible to prefer published citations over draft citations, which is currently not being done.

**Comment by rliebz** [comment]
It is actually only possible to access published citations consistently through the search API, which I don't think is a very viable solution—we'd have to check two endpoints, one of which is a search, and potentially still have to fall back on the draft citation.

I've opened up an issue at https://github.com/IQSS/dataverse/issues/2059 to see if they can provide a better option. For now, I recommend deferring the issue.

**Comment by nanchen47** [comment]
Will be considered in later dataverse addon refactor. Thanks.
