### ISSUE TITLE
Bad Request from Profile when Going to Dashboard

### ISSUE THREAD

**Issue by billyhunt** [CenterForOpenScience/osf.io#2543]
Steps
-------
1. Go to https://osf.io/dashboard/
2.  Look At Console

Expected
------------

No Error Message

Actual
--------
 On going to link already signed in, you get the following console message.

PUT https://osf.io/api/v1/profile/ 400 (BAD REQUEST)  jquery-1.11.2.min.js:4

With the response being 

{"code": 400, "referrer": "https://osf.io/dashboard/", "message_short": "Bad request", "message_long": "\"id\" is required"}

![screenshot 2015-04-21 11 31 52](https://cloud.githubusercontent.com/assets/6232068/7255874/0bd12894-e81a-11e4-80b8-a63d38ab6adb.png)

**Comment by lbanner** [comment]
Assume to be a js error on Production @billyhunt ?

**Comment by brianjgeiger** [comment]
I can't think of any reason why anything on the dashboard should be trying to PUT to the user profile route at all, much less just for loading the dashboard page.

**Comment by lbanner** [comment]
Anyone want to replicate and examine the output?

**Comment by brianjgeiger** [comment]
Looks like it's coming from https://github.com/CenterForOpenScience/osf.io/blob/develop/website/static/js/pages/dashboard-page.js#L61-L68 to get the user's current timezone which is important for knowing when to send out notifications. It's complaining about the ID, so maybe it's trying to send the request before it has the ID, or perhaps it's not grabbing the proper ID. Should be fairly easy for someone to fix.

**Comment by lbanner** [comment]
TY

**Comment by nanchen47** [comment]
The pr has been merged and fix has been deployed on production.
