### ISSUE TITLE
Requirements conflicts

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2545]
Steps
-------
1. invoke requirements
2. invoke requirements --addons
3. invoke requirements

Expected
------------
Any given module should be installed only once.

Actual
--------
Some modules are installed multiple times because different places are requesting different versions of the same modules. A couple of modules get installed every time because they are pointing at a github commit and.

**Comment by brianjgeiger** [comment]
For MFR and Modular ODM, we need to pin those to a commit rather than to a branch. Then if there are updates, the commit number will need to be changed.

**Comment by brianjgeiger** [comment]
If I do an `invoke requirements --addons` then an `invoke requirements` and then do the process again, here's what is successfully installed or uninstalled on the second go through:
```bash
(osf-clean)idris:osf bgeiger$ invoke requirements --addons | grep Successfully | grep install
      Successfully uninstalled mfr-0.1.0a0
      Successfully uninstalled modular-odm-0.2.1
Successfully installed mfr-0.1.0a0 modular-odm-0.2.1
      Successfully uninstalled lxml-3.4.1
      Successfully uninstalled requests-2.5.3
Successfully installed lxml-3.4.3 requests-2.6.2
Successfully installed dataverse-0.1.1
      Successfully uninstalled mendeley-0.2.5
      Successfully uninstalled requests-2.6.2
Successfully installed mendeley-0.2.5 requests-2.4.3
      Successfully uninstalled requests-2.4.3
      Successfully uninstalled feedparser-5.2.0
      Successfully uninstalled pytz-2014.9
Successfully installed feedparser-5.2.0 pytz-2015.2 requests-2.6.2
```

```bash
(osf-clean)idris:osf bgeiger$ invoke requirements | grep Successfully | grep install
      Successfully uninstalled mfr-0.1.0a0
      Successfully uninstalled modular-odm-0.2.1
      Successfully uninstalled requests-2.6.2
      Successfully uninstalled pytz-2015.2
      Successfully uninstalled lxml-3.4.3
Successfully installed lxml-3.4.1 mfr-0.1.0a0 modular-odm-0.2.1 pytz-2014.9 requests-2.5.3
```

**Comment by GaryKriebel** [comment]
@sloria has this been updated?

**Comment by sloria** [comment]
@GaryKriebel No, this has not yet been addressed.

**Comment by hmoco** [comment]
So this behavior is due, I believe, to (in tasks.py)

--exists-action -w, which I am unsure of why it is used
-U, which I understand why is necessary, but might be causing the issue as mentioned in this issue:
https://github.com/pypa/pip/issues/2472

by removing those two from tasks.py functions: requirements and addon_requirements, the invoke commands behave as expected, but I am not sure if removing -U is wanted.

**Comment by lbanner** [comment]
@brianjgeiger? ^^  Thanks @hmoco

**Comment by hmoco** [comment]
Actually upon further testing --exists-action doesn't create any problems, it is all due to -U. Using a commit instead of a branch for pip install for MFR and modular ODM seems to have no effect.
