### ISSUE TITLE
[Production] Dataverse: Improve download error handling

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2547]
## Steps
1. Go to https://osf.io/9jtkg/
2. Click on the files tab
3. Toggle the dropdown for the Dataverse folder to 'Draft'
4. Click on the file 'test_slide_pdf_1.pdf' to render
5. See the time out message
6. Click the green download button on the right

## Expected
If the file is unable to be rendered or downloaded, I would expect the user to get an informative error message as to the cause.

## Actual
The user sees the following when trying to download:
![screenshot 2015-04-21 11 46 12](https://cloud.githubusercontent.com/assets/9381062/7256320/656dffe2-e81c-11e4-8eaa-814a220c4d2a.png)

Upon further investigation on the dataverse site, trying to download the file on their site shows the user the following for the same file:
![screenshot 2015-04-21 11 51 32](https://cloud.githubusercontent.com/assets/9381062/7256389/cb73feae-e81c-11e4-831c-88e6c625e206.png)

**Comment by nicipfeiffer** [comment]
Linking this issue, as it is related https://github.com/IQSS/dataverse/issues/2063

**Comment by nanchen47** [comment]
This problem no longer appear.
