### ISSUE TITLE
[bug][production] User name displays in anonymous view-only link

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2549]
*Steps*
1. Create anonymous view-only link for a project containing a file
2. Sign out, use view-only link to view project
3. contributor list and logs are anonymized, but user's name is NOT anonymized on file detail page

Here's a view-only link to a file of mine: https://osf.io/nh8t3/?view_only=d3f5970aab394228a7b7aad96aec1ad3

Reported on the help desk.

**Comment by chrisseto** [comment]
Are you able to view the file?

**Comment by GaryKriebel** [comment]
I'm going to be no since @samchrisinger and I are both seeing this.
![screen shot 2015-04-21 at 4 56 23 pm](https://cloud.githubusercontent.com/assets/9437946/7262420/6f3cf6ba-e847-11e4-93e0-0deb8af09a4b.png)

**Comment by lbanner** [comment]
Was this an issue i.e. ability to see a user's name, even via anonymous link, in the file info / version bar before deployment of new file-index-view?

**Comment by sloria** [comment]
@chrisseto is currently writing a hotfix for this

**Comment by chrisseto** [comment]
Fixed via https://github.com/CenterForOpenScience/osf.io/pull/2558
