### ISSUE TITLE
[production] File tree jumpy when expanding folders

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2550]
Not a problem on staging - just production. @caneruguz says that he put in a fix for this, but for some reason production is still affected.

# Steps
1. Log into production
2. Go to a project on where multiple add-ons are authorized and configured
3. If there are not already folders within the add-ons, go to the add-on sites and add folders (and subfolders)
4. Click on a file in the files tab to view it in the files detail page
5. Ensure that the selected file is highlighted at the top of the file tree
6. Scroll up or down and click on a folder in an add-on to expand the folder

# Expected
The folder would expand and its contents would immediately be shown. 

# Actual
It seems like there is some sort of refresh happening with the file tree. The folder is expanded, but after its contents load, the tree scrolls back to have the selected file highlighted at the top of the tree. This is an annoyance when trying to access files in subfolders. See gif below

![2015-04-21 13_55_29](https://cloud.githubusercontent.com/assets/5975444/7258984/15abd4e0-e82e-11e4-84d0-c2ad4cafbba1.gif)

**Comment by caneruguz** [comment]
I checked the master files and they have the latest treebeard commit (or at least same as develop). 

Can we rule out a few things first:
- inv assets has run on production, or related treebeard install is done 
- treebeard is not cached on  @caileyfitz's laptop

**Comment by caileyfitz** [comment]
@caneruguz I opened an incognito window and found that I have this same problem there. Would this address the caching issue?

**Comment by caneruguz** [comment]
@caileyfitz and @GaryKriebel can we recheck this?  It should be resolved.

**Comment by caileyfitz** [comment]
@caneruguz this is now resolved :whale:
