### ISSUE TITLE
[Production & Staging] ESearch: Does not give intuitively relevant results

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2552]
## Steps
1. Go to osf.io
2. Click on the magnifying glass in the navbar at the top of the page
3. Enter 'horse' into the search bar

## Expected
I have a public project by the name of 'horses', so I would expect to see that on the results page.  The project description also contains the word 'horse'.
![screenshot 2015-04-21 15 10 23](https://cloud.githubusercontent.com/assets/9381062/7260513/906c3b0c-e838-11e4-976d-9c779cc91d22.png)

## Actual
The results page does not have the horses project listed when searching for 'horse'.  Instead gives a project that does not contain 'horse' in the title.  The project that is returned for the search also does not have 'horse' in the description.  Doing a find on the wiki page does return 2 instances of 'horse'.
![screenshot 2015-04-21 15 12 11](https://cloud.githubusercontent.com/assets/9381062/7260546/d11240fc-e838-11e4-95e5-5fd96a63e549.png)
![screenshot 2015-04-21 15 13 47](https://cloud.githubusercontent.com/assets/9381062/7260594/1dd41f46-e839-11e4-9421-bb5e51b00d5e.png)

## Notes
Asking @fabianvf about the elasticsearch behavior, he pointed me to http://www.elastic.co/guide/en/elasticsearch/guide/current/relevance-intro.html.
I think that the search results return can be improved/optimized to meet what users would expect.

**Comment by brianjgeiger** [comment]
@nicipfeiffer Try doing a search for horse* and let me know what happens, please.

**Comment by fabianvf** [comment]
This is strange. It looks like the search isn't wildcarding/fuzzy matching for some reason.

**Comment by brianjgeiger** [comment]
Lucene search syntax

**Comment by brianjgeiger** [comment]
![screen shot 2015-04-21 at 4 03 51 pm](https://cloud.githubusercontent.com/assets/6599111/7261478/0bc79650-e840-11e4-8e32-2dcc379d2c24.png)

**Comment by nicipfeiffer** [comment]
@brianjgeiger shouldn't a project with 'horse' in the title be returning as a more relevant result than these others?

**Comment by brianjgeiger** [comment]
Possibly. The first question is, what's causing them to show at all? If they have horse things 200 times in the wiki, that might be one reason. I don't know, as I haven't looked at the projects closely at all.

**Comment by nicipfeiffer** [comment]
@brianjgeiger and @fabianvf I did some investigating further.  And found that when I enter horse* into the search bar I get the following returns for projects:
 - Effects of Superstition and Adversity on Performance. Description: This project examines how superstition influences performance under normal and adverse conditions.

Doing search for horse on project returns = 0 on project overview page, and 1 horse found in this string (clover, horseshoe, triple 7s) found on the wiki page in the 3rd paragraph

 - RRR-Schooler-MTurk

Doing search for horse on project returns = 0 on project overview page, and 2 horse found on the wiki page, both in quotes and in the 12th paragraph 

 - Study 1 - Initial MTurk Study

Doing search for horse on project returns = 0 on project overview page, and 1 horse found on the wiki page, found in this string (four-leaf clover, horseshoe, triple 7s/Vegas) in the 3rd paragraph

 - Horses
Description: I like horses

Doing search for horse on project returns = 12 on the project overview page, and 0 on the wiki

It still appears to me the the project 'Horses' should be on top of the list.  However, it gives insight that perhaps the search is only looking at the wiki when sorting relevance?

**Comment by lbanner** [comment]
Are we sorting by "relevance" in search returns?

**Comment by brianjgeiger** [comment]
Essentially. We're using Elastic's relevance, and I think the Lucene query is feeding into that, based on the 45 seconds of research I've done. I expect, when implementation time comes, <http://jontai.me/blog/2013/01/advanced-scoring-in-elasticsearch/> will be important. But we will also need to decide what's important to us as far as search relevance. Some of this may come out of the Open Science Barn Raising (a.k.a. Hack on Open Science) work that gets done soon.

**Comment by jhwhite** [comment]
As Brian points out in his comment it looks like the title field needs to have a boost applied. Here's a good stackoverflow about different times to do boosting, index time vs. query time. 

http://stackoverflow.com/questions/12590587/elasticsearch-mapping-config-file-boost-field.

**Comment by softwaredoug** [comment]
Hey guys, @jhwhite pointed me here. John Berryman and I are actually writing a book on [search relevance](http://manning.com/turnbull). I am happy to come by and hangout and chat with you guys (for free of course) for an hour or so if you wanted to pick my brain...

**Comment by csoderberg** [comment]
On a related note, when you search for the exact title of a project on the system (for example, if you search for Reproducibility Project: Psychology, or "Reproducibility Project: Psychology") you'd think the project with that title would be the first thing to come up, or at least near the top. It is in fact on the 6th page of results, and oddly enough most of it's child projects appear in the search results far before it:

![screenshot 2015-05-01 14 54 06](https://cloud.githubusercontent.com/assets/7332030/7436822/42416116-f01f-11e4-8219-f73425f8d873.png)

**Comment by brianjgeiger** [comment]
@softwaredoug Thank you for the offer. We'll need to find a good time for this, but we would love to get the benefit of your research and knowledge. @fabianvf

**Comment by softwaredoug** [comment]
Sure feel free to ping me on email: dturnbull@opensourceconnections.com

-Doug

**Comment by GaryKriebel** [comment]
@fabianvf have you given this a look lately?

**Comment by brandonPurvis** [comment]
I'll take this one.

**Comment by lbanner** [comment]
@brandonPurvis -- We might want some insight from @fabianvf on this one and it's practicality to tackle outside of full ElasticSearch re-look .... @fabianvf ??

**Comment by fabianvf** [comment]
There are definitely incremental improvements that could be made. I'd be happy to help get started.

**Comment by lbanner** [comment]
Thank you @fabianvf -- Alright @brandonPurvis -- you got it.
