### ISSUE TITLE
Published Dataverse files are not highlighting in file tree

### ISSUE THREAD

**Issue by ginavuu** [CenterForOpenScience/osf.io#2553]
# Steps
1. Select and enable the Datverse add-on (user setting)
2. Configure add-on (user-setting)
3. Go to a project and import credentials
4. Configure add-on for the project (like one that is published)
5. Go to the files tab
6. Click on a file to view it in the file details page
7. On the file details page, look at the file tree

# Expected
I expect that the file being viewed would be highlighted in the file tree.

# Actual
The file is not highlighted. 
![highlighting](https://cloud.githubusercontent.com/assets/11032617/7260781/b6838a3c-e83a-11e4-8966-1702d5941502.PNG)

**Comment by lbanner** [comment]
This maybe a know inconsistency with File-Index-View functionality?
