### ISSUE TITLE
Show wiki delete button on hover

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2554]
<h4>Steps</h4>
1. Visit a component with at least 3 wiki pages
2. Click on a wiki page other than the home page
3. Hover over the title of another non-home-page wiki. 

<h4>Outcome</h4>
1. When the user clicks on a wiki page, a trashcan shows up to the right of the name, allowing them to delete it.
2. When the user hovers over a wiki page title, the trashcan does not show up. This means that to delete a wiki page, the user has to visit each one they want to remove, one by one.

<h4>Expected outcome</h4>
1. Hovering over the wiki page title will allow the user to click on the trashcan to delete the page. This is consistent with how file deletion works. There is also a confirmation prompt already, meaning that the user is unlikely to accidentally delete the page.

**Comment by brianjgeiger** [comment]
Ideally, the wiki list will become a Treebeard instance just like the File View page is. Once that happens, this interface will be the same. That being said, making the change to the current version probably wouldn't be all that difficult if it's very troublesome the way it is now. 

But ultimately, File View and Wiki will work exactly the same way before too long.

**Comment by jlcohoon** [comment]
I wouldn't think it's very troublesome right now—I suspect not many people have multiple wiki pages (though we could investigate that). If the wikilist will use Treebeard soonish, I'd consider that a resolution to this issue.

**Comment by samanehsan** [comment]
#2990 will make the wiki menu use treebeard

**Comment by caneruguz** [comment]
@samanehsan the changes in that PR are applied but it still doesn't address the original issue. @jlcohoon can you take a look at current production behavior and let us know if this issue should close or not?

**Comment by jlcohoon** [comment]
Technically the problem of not being able to delete a page without visiting it still exists. However, I'm under the impression that that would be difficult to implement. I still think that it would be helpful to quickly delete multiple wiki pages at once, but perhaps hover isn't the answer.
