### ISSUE TITLE
Tabular file rendering not responsive; overlaps with file info

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2555]
<h4>Steps</h4>
1. Visit a tabular file (https://osf.io/8rvb3/, for example)
2. Reduce your window size to be 1400px wide or less

<h4>Outcome</h4>
1. The file rendering does not reduce in size as the window shrinks. 
2. The file details sidebar on the right continues to move to the left as the window shrinks, and overlaps with the file rendering.
![screen shot 2015-04-21 at 11 05 42 am](https://cloud.githubusercontent.com/assets/4965832/7261817/a1e4ba80-e842-11e4-94d4-2f0fafcc03b6.png)

3. At about 990px wide, the right sidebar moves below the file rendering and no longer overlaps. It does not have any padding/margin between itself and the rendering, however.
![screen shot 2015-04-21 at 4 22 51 pm](https://cloud.githubusercontent.com/assets/4965832/7261826/b1248eee-e842-11e4-8562-a65ec7eea649.png)

<h4>Expected Outcome</h4>
1. As the window width decreases, the rendering pane would decrease in size so that fewer columns of data would be shown. This would prevent overlap. 
2. When the right sidebar moves below the rendered file, at 990px, a small amount of padding would give it space to separate it from the rendered file.

**Comment by lbanner** [comment]
Thank you @jlcohoon -- This is a known issue, but you articulate it well here -- If I can find the similar issue #, I'll tie this together. But meantime, I will leave this is a noted bug here.

**Comment by jlcohoon** [comment]
Ah sorry—found it #2254

**Comment by lbanner** [comment]
All good! Appreciate the find.

**Comment by lbanner** [comment]
Related and potential resolved in PR #168

**Comment by samanehsan** [comment]
UPDATE: the overlap issue has been fixed on production. However, there is still not much padding between the file and the revisions table at narrow screen widths: 

![screen shot 2015-06-18 at 5 33 26 pm](https://cloud.githubusercontent.com/assets/6414394/8243014/7c6c81bc-15e1-11e5-8fb8-c01f7a49add0.png)

**Comment by lbanner** [comment]
OK -- Good detail to note, but close this for now.
