### ISSUE TITLE
Treebeard height doesn't expand to page height

### ISSUE THREAD

**Issue by chrisseto** [CenterForOpenScience/osf.io#2561]
Treebeard should take advantage of the entire page rather than just leaving white space at the bottom.

Additionally could the footer be removed on the file page? It feels a bit cramped currently.

![osf___osfstorage_file_ops_files_and_downloads](https://cloud.githubusercontent.com/assets/5532905/7276288/a3f5d248-e8d6-11e4-9379-40fd23426f1e.png)

**Comment by caneruguz** [comment]
This fix is already done, it will be bundled in the toolbar changes release. @lbanner  can you assign me with low priority and working on it tags? 

@chrisseto Right now the height adapts to window resize and becomes shorted if window height is short, is that desired behvaior for you? The alterntive is that is gets larger but does not get smaller; which I think is not ideal.

**Comment by lbanner** [comment]
Done!

**Comment by caneruguz** [comment]
To clarify the fix refers to the height of the files box, the footer is not touched. I think the discussion about footer is a bigger one and should not be specific to this page.

**Comment by GaryKriebel** [comment]
I would agree with @caneruguz concerning the footer.... I would actually expect it to be on all pages, but good to defer that portion.

**Comment by caneruguz** [comment]
@JeffSpies any thoughts on the footer discussion here? 

Here's an example with minor footer stuck to the bottom: 

![screen shot 2015-04-23 at 1 18 39 pm](https://cloud.githubusercontent.com/assets/1314003/7302986/5bc639b4-e9bb-11e4-9c48-3d2e675ac0f7.png)

**Comment by JeffSpies** [comment]
I think that's a nice compromise. Thinking about expandability in the
future could be good if there's critical info we want in there, but, for
the time being that seems to be what every user needs to see. The question
remains as to what we lose from a marketing perspective if people land
there, but we do have the popup. Thoughts on different footers based upon
whether someone is logged in or not?

**Comment by GaryKriebel** [comment]
I quite like that.... I think that a footer is good in that the user knows "that's it" and on a busy page it's not overwhelming.

**Comment by caneruguz** [comment]
Please continue discussion in the PR linked above. Download and check out the PR and let me know if there are suggestions.

**Comment by caneruguz** [comment]
@lbanner  This original issue can be closed, it is fixed in Files page where the height readjusts on window resize.

**Comment by lbanner** [comment]
Thanks.
