### ISSUE TITLE
[staging & production] Add warning about add-ons for anonymized links

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2562]
# Steps
1. Go to a project on which you have admin access
2. Go to the Settings tab and enable and configure Dataverse
3. Go to the project overview page to ensure that the Dataverse widget is present
4. Go to the Sharing tab 
5. Click to create a view-only link
6. Check the Anonymize box and Submit to create the link
7. Open a private window
8. Paste the view-only link 
9. Check that the link is anonymized

# Expected
I expect that user names should be removed in all places where it appears.

# Actual
The user name is removed in all places where it appears through OSF actions, but NOT for add-ons. For example, when I viewed my anonymous link created above, my name is anonymized in logs:
![screen shot 2015-04-22 at 10 11 50 am](https://cloud.githubusercontent.com/assets/5975444/7276656/36d50b9a-e8d9-11e4-82fa-ffac0965d38d.png)

but to the left of logs, this is displayed prominently on the page:
![screen shot 2015-04-22 at 10 11 41 am](https://cloud.githubusercontent.com/assets/5975444/7276662/44601188-e8d9-11e4-8f35-377643135d3d.png)

Something similar occurs in #1090 

# Suggestions
The current anonymize warning message reads
![screen shot 2015-04-22 at 10 14 02 am](https://cloud.githubusercontent.com/assets/5975444/7276671/6324161e-e8d9-11e4-8f64-93ee65a001d7.png)

I think there should be additional warnings about add-ons exposing the user's name. There is currently no mention of add-ons in the warning, although it is very likely that add-ons will reveal identifying information. Additionally, we still have the issue of names being viewable in wiki logs, as is documented in https://github.com/CenterForOpenScience/osf.io/issues/1168

I suggest that we draft a more robust warning to users creating anonymized links, alerting them to all of these possible scenarios.

**Comment by nanchen47** [comment]
The pr has already been merged. Close this issue.
