### ISSUE TITLE
[staging & production] Versions history is not correct

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2575]
# Steps
1. Log into either staging or production
2. Go to a project on which you can upload files
3. Upload a pdf, jpg, or png file (confirmed that it happens with all these file types - does not happen with docx files) named pink.pdf (use appropriate extension -- here I will use pdf)
4. Find another file of the same type and name that pink.pdf
5. Upload the second version of pink.pdf 
6. In the files tab, click to view pink.pdf
7. Ensure that two versions are shown
8. Check that the first version is the first file you uploaded
9. Check that the second version is the second file you uploaded
10. Go back to the files tab and click the red x to delete pink.pdf
11. Find a third file of the same type and name it pink.pdf as well
12. Upload the third pink.pdf 
13. In the files tab, click to view pink.pdf
14. Look at all three versions
15. Go back to files tab
16. Upload a fourth version of pink.pdf, this time without deleting the existing file
17. Click to view pink.pdf in the files detail page
18. Look at all four versions

# Expected
I expect that even if files are deleted, uploading a new version would resurrect the deleted files so that the files in the version history table would correlate to the files that were uploaded. Specifically, I expect that all versions of pink.pdf would be distinct, even though it was deleted once from the files tab.

# Actual
After deleting pink.pdf once, all versions thereafter are the most recently updated version of pink.pdf. For the example above, we have these steps and results:

### After first upload:
One version: 
- pink1.pdf -- is actually pink1.pdf

### After second upload
Two versions: 
- pink2.pdf -- is pink2.pdf
- pink1.pdf -- is pink1.pdf

### Now we delete pink1.pdf and pink2.pdf via the red x and upload pink3.pdf
Three versions:
- pink3.pdf -- is pink3.pdf
- pink2.pdf -- is pink3.pdf
- pink1.pdf -- is pink1.pdf

### Upload a fourth version 
Four versions:
- pink4.pdf -- is pink4.pdf
- pink3.pdf -- is pink4.pdf
- pink2.pdf -- is pink4.pdf
- pink1.pdf -- is pink1.pdf

What seems to happen is that after the first time you delete a file, then the most recent version before delete and all versions thereafter are replaced by the most current file.

**Comment by lbanner** [comment]
@GaryKriebel ... this seems in line with your / our discussions re: How to we handle deleted files, yes? I will tag with "discussion."

**Comment by nicipfeiffer** [comment]
@lbanner @GaryKriebel @chrisseto This seems like something worth revisiting with the File Quota work, especially considering a use case where there is a big difference in file size of pink2.pdf and pink3.pdf.

**Comment by lbanner** [comment]
Agree @nicipfeiffer

**Comment by chrisseto** [comment]
Versions have not behaved like this for quite a while now.
When a file is deleted it's versions are are no longer resurrected when any file with the same name is uploaded to the same project.
![screen shot 2015-08-19 at 09 20 37](https://cloud.githubusercontent.com/assets/5532905/9357266/08a3da02-4654-11e5-83c5-1c6f5e6ef44f.png)
![versions](https://cloud.githubusercontent.com/assets/5532905/9357269/0b680330-4654-11e5-9993-db39f2b718cc.gif)

**Comment by GaryKriebel** [comment]
@chrisseto is correct that deleted files no longer come back.  Therefore, I am closing this issue.
