### ISSUE TITLE
Add Google Analytics Event tracking to User Registration form

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2593]
In order to track where how new users find the OSF, it would be helpful to set up event tracking on the ajax form creating a new account - much like the event tracking we use on the buttons on the slide in footer.

User conversion was tracked using a goal setting in analytics previously - but this broke when registration was changed at the end of March.

**Comment by lbanner** [comment]
@saradbowman I assume you have the event tracking code you'd like embedded in form, yes? Thanks.

**Comment by saradbowman** [comment]
Yep! I think everything you would need is here (but can provide ID number if that's needed) https://developers.google.com/analytics/devguides/collection/analyticsjs/events

**Comment by lbanner** [comment]
@kmjungersen Can you knock this one out fairly quickly? Thanks.

**Comment by kmjungersen** [comment]
Absolutely - I'm looking into it now. :rocket:

**Comment by kmjungersen** [comment]
Fixed with PR #2669, so this issue can be closed 😎

**Comment by saradbowman** [comment]
Thank you!!!
