### ISSUE TITLE
[Production] 'New Folder' and 'Delete' flags never disappear under Files tab

### ISSUE THREAD

**Issue by reinaH** [CenterForOpenScience/osf.io#2604]
The small pop-up flags that appear when you create a new folder ('new folder') or delete a folder ('delete') do not disappear once the action has taken place. This does not apply to deleting files and the error can be reproduced anywhere in the File manager under any extension. The only way to get rid of the tags is to reload the page or leave the tab and come back.  Was successfully reproduced in Chrome, Safari, IE, and Firefox

# STEPS
1. Go to a project
2. Go to the Files tab
3. create a couple of new folders in OSF storage or under any extension (does not matter if they are nested or not)
4. After the new folders have been created, you should see that the 'new file' flag never disappeared. There should be as many hovering 'new file' flags as folders that were created. Do not refresh/leave the page. 
5. Delete one or more folder(s). Do not refresh/leave the page. 
6. After the folder has been deleted, you should notice that the 'delete' flag never disappeared. There should be as many flags as folders that were deleted. 

# EXPECTED
The 'new file' flag should only appear when the '+' is being hovered over or clicked. The same is expected for the 'x' and the 'delete' flag. 

# ACTUAL
The flags do not disappear after a new folder has been created and after a folder has been deleted. The tags (those that do not disappear) even shift from right to left sometimes. 
![screen shot 2015-04-29 at 2 52 39 pm](https://cloud.githubusercontent.com/assets/5785124/7398607/11c15d4a-ee7e-11e4-903f-05b4ddae95c5.png)

**Comment by reh4fd** [comment]
@lbanner Nici mentioned that you had noticed this behavior yesterday.

**Comment by lbanner** [comment]
Yep!

**Comment by caneruguz** [comment]
The entire actions column will disappear soon. So I recommend holding this.

**Comment by lbanner** [comment]
OK -- HOLD

**Comment by GaryKriebel** [comment]
Fixed by https://github.com/CenterForOpenScience/osf.io/pull/2606

**Comment by nanchen47** [comment]
Since the file page interface has been changed by @caneruguz, this is no longer a problem
