### ISSUE TITLE
Numbered lists in wiki split words between lines

### ISSUE THREAD

**Issue by evomellor** [CenterForOpenScience/osf.io#2605]
When a numbered list in the wiki has a sub item, words are cutoff between lines.
![screen shot 2015-04-28 at 2 32 37 pm](https://cloud.githubusercontent.com/assets/11249723/7399896/03edf242-ee87-11e4-82e2-5cbf0f366abe.png)

**Comment by brianjgeiger** [comment]
That does not look like a properly formatted sub item. It looks like it's wrapping it in a pre tag instead. Is this on a public project?

**Comment by evomellor** [comment]
Yes, it is on this page: https://osf.io/x5w7h/wiki/01%20Overview%20of%20Workflow/

**Comment by brianjgeiger** [comment]
Take out the tab after the 3. and put three more spaces in before the 3.

**Comment by brianjgeiger** [comment]
![screen shot 2015-04-29 at 3 55 07 pm](https://cloud.githubusercontent.com/assets/6599111/7400055/26846de4-ee88-11e4-9469-6e33294a116f.png)

**Comment by evomellor** [comment]
Thank you! :)
