### ISSUE TITLE
[staging and production] file upload times do not match versions; versions are not rendered properly

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2608]
<h4>Steps</h4>
1. Upload a file to the OSF
2. Make changes to that file, save it, and upload a new version to the OSF.
3. Visit the file's detail page and look at the version history.

<h4>Outcome</h4>
1. The times and dates of the versions are incorrect. They appear to be listed in reverse chronological order, such that if you have three versions, Version 1 has the most recent upload time, Version 2 has the middle upload time, and Version 3 has the earliest upload time. 
For an example visit this file: https://staging.osf.io/ynx7i/

<h4>Expected Outcome</h4>
1. Upload times should become more recent as the version numbers rise so that version 1 is the oldest version.

**Comment by sloria** [comment]
@jlcohoon This should now be fixed. Can you verify?

**Comment by jlcohoon** [comment]
looks good!

**Comment by sloria** [comment]
Thanks!
