### ISSUE TITLE
[production] Incorrect error message when attempting to delete project

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2612]
Steps
-------
1. Create a project.
2. Nest a component in the project.
3. From the Project settings, try to delete the Project.

Expected
------------
1. There will be an error message telling you to delete the component before you can delete the project. 

Actual
--------
1. You get a different error message: 
![screen shot 2015-04-30 at 4 12 30 pm](https://cloud.githubusercontent.com/assets/7749914/7421623/38fd5df6-ef54-11e4-8dc8-8f31df2a0023.png)

**Comment by lbanner** [comment]
So I understand correctly @saradbowman : Expected functionality is that I, as a user, cannot delete a Project if it has one ore more components, correct?

**Comment by saradbowman** [comment]
Yes, that's correct. Must delete components before you can delete the
project
