### ISSUE TITLE
Sections of URL's Are Not Searchable in User Profiles

### ISSUE THREAD

**Issue by billyhunt** [CenterForOpenScience/osf.io#2617]
Steps
-------
1. Go to https://osf.io/search/?q=mywebsiteisthebestwebsiteever.com&page=1

Expected
------------

Searching for mywebsiteisthebestwebsiteever.com should return results with www.mywebsiteisthebestwebsiteever.com in them.

![screenshot 2015-05-01 16 10 26](https://cloud.githubusercontent.com/assets/6232068/7436539/a64ff698-f01c-11e4-98d6-f2ec815ed6d8.png)

Actual
--------

The profile that contains http://www.mywebsiteisthebestwebsiteever.com is not found.  Search is not searching parts of the URL.  

![screenshot 2015-05-01 16 11 18](https://cloud.githubusercontent.com/assets/6232068/7436586/023272ec-f01d-11e4-8835-10f98044ad87.png)

**Comment by brianjgeiger** [comment]
https://osf.io/search/?q=*mywebsiteisthebestwebsiteever.com&page=1

Check out the documentation linked by the ? on the search bar. At some point we may want to make the lucene search syntax optional and make it a simple substring search (or something smarter) under other circumstances, but for now, it's all Lucene search syntax.

**Comment by lbanner** [comment]
So this is functioning as expected? Though maybe not ideally?

**Comment by brianjgeiger** [comment]
Functioning as designed. At some point we will want to look at making search better. 

.:Brian

**Comment by lbanner** [comment]
'K Thanks!
