### ISSUE TITLE
[production] Search occasionally gets...stuck

### ISSUE THREAD

**Issue by csoderberg** [CenterForOpenScience/osf.io#2618]
So, occasionally, when I type a search term into search and hit enter absolutely nothing happens. I can hit enter as many times as  you want and the search will never run. However, other things on the internet are still working, so it's not that my internet went out. If I change the search term even slightly and hit enter again it will usually run. I can't seem to find any pattern to it in terms of when it will happen, what search terms cause it to happen, or what particular OSF project I'm on when it happens. It know it has happened with the following search terms, but there might be others, and these search terms often don't cause any problems:

Soto
soto
RP:P
Reproducibility
Reproducibility Project: Psychology

It's definately happened a few times on safari. I'm not sure if it has happened on other browsers. @fabianvf

**Comment by brianjgeiger** [comment]
I was going to suggest hitting the search button, but apparently we got rid of that. If you see this again and you're in the office, please call me over. If you know how to use the developer tools in Safari, you can check for errors.

**Comment by csoderberg** [comment]
Screenshot of what version of safari I was running when it happened:
![screenshot 2015-05-01 16 53 48](https://cloud.githubusercontent.com/assets/7332030/7437146/16f54636-f023-11e4-86a3-a6c4967f750a.png)

**Comment by brianjgeiger** [comment]
There are no JS errors on Courtney's machine. It looks as though the event just isn't firing for some reason, but no obvious causes.

**Comment by fabianvf** [comment]
Very strange. So is the request going out at all?

**Comment by brianjgeiger** [comment]
No, and history isn't being updated either. I suspect from a "make it work better for @csoderberg" perspective, she should update her Safari. I think that 7.1 is not the best version of Safari out there. 7.0.3-7.0.5 were definitely troublesome (see #1250), but maybe 7.1 was not quite ideal either?

**Comment by nanchen47** [comment]
Can't repo this problem anymore. If this happens again. please reopen it.
