### ISSUE TITLE
[Staging] Can't create new folder on Dashboard

### ISSUE THREAD

**Issue by ginavuu** [CenterForOpenScience/osf.io#2619]
# Steps
1. Only in staging
2. Go to my dashboard.
3. Click add a folder
4. Enter a name and hit add

# Expected
To create a new folder.

# Actual
An error message comes up and a new folder is not created.
![no new folder](https://cloud.githubusercontent.com/assets/11032617/7437089/4a1df9b4-f022-11e4-82e7-d44f9f39fbf8.PNG)

**Comment by lbanner** [comment]
@ginavuu This is just Staging? And is / has this been a consistent error for you?

**Comment by abought** [comment]
I am also seeing this- both in staging and production, consistently. The selected top-level folder at the time was "dashboard".

Possibly helpful: when the error occurs, the following message appears on the console:

`PUT 
https://staging.osf.io/api/v1/folder/ [HTTP/1.1 404 NOT FOUND 26ms]`

**Comment by brianjgeiger** [comment]
Yeah, that's bad. https://github.com/CenterForOpenScience/osf.io/blob/develop/website/routes.py#L979 should be catching that route.

**Comment by abought** [comment]
Thanks to @lyndsysimon , we've traced the problem: the route has a decorator `@must_be_valid_project`, which raises a 404 if there is no `<pid>` or `<nid>` in the URL. (broke on April 20 when the decorator was added)

The decorator was necessary to ensure that the specified dashboard node exists (and explains the 404 error code), but it makes assumptions that do not match the form of this API route.

One proposed solution is to change the route to one of the form `/folder/<pid>` and update all pages that use that route. It would also help to add a test. Will discuss with @brianjgeiger   after QA.

**Comment by lbanner** [comment]
Who wants it? :smiling_imp:

**Comment by abought** [comment]
Apparently, @samchrisinger  and @sloria do, as of ~3pm.  See:
4589170aff0537af87648e456b96e6a8762c45c0

A regression test on the `add_folder` route might still be helpful. Otherwise, folder creation is now working for me in production and on staging.

**Comment by sloria** [comment]
@abought That commit was only merged into develop. Are you still seeing this bug on production?

**Comment by abought** [comment]
I am able to create folders on production. (Not sure what was happening yesterday- it's possible I had two open tabs mixed up. Glad it's working.)

**Comment by lbanner** [comment]
Going to close this now - TY
