### ISSUE TITLE
Including a  "/" in search throws an error (Unable to Resolve)

### ISSUE THREAD

**Issue by alexschiller** [CenterForOpenScience/osf.io#2622]
**What I did:**

Any search containing a / that is not escaped

**What I expected:**

Searches that include / to show up

**What happened:**
On production
Error message:
"Unable to resolve
OSF was unable to resolve your request. If this issue persists, please report it to support@osf.io."

JS: POST https://osf.io/api/v1/search/ 400 (BAD REQUEST)

**Potential cause:**
/ not being properly escaped by default

**Comment by fabianvf** [comment]
On production, I get this message instead, locally and on Prod. Do you still get the same exception? 
![screen shot 2015-05-05 at 11 50 16 am](https://cloud.githubusercontent.com/assets/2431974/7476654/0559871e-f31d-11e4-85cb-e9ac79ad3c3c.png)

**Comment by alexschiller** [comment]
No, I'm getting the "bad search query" now. Can't replicate the 500 anymore.

**Comment by GaryKriebel** [comment]
Closing this for now.... If it appears again we can reopen.
