### ISSUE TITLE
Public components not displaying on profile

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#2623]
## Steps

- Go to a user profile for a user who has public components

## Expected

Their public components display in the Public Components list.

## Actual

It always displays "This user has no public components"

-----

This was a regression introduced in https://github.com/CenterForOpenScience/osf.io/pull/2515. I will make a hotfix shortly.

**Comment by JeffSpies** [comment]
@ghalko should be tracking this fix.

**Comment by Ghalko** [comment]
https://osf.io/m7n9p/

Is it a user who is not self?

**Comment by Ghalko** [comment]
@sloria did you apply the hotfix yet?

**Comment by sloria** [comment]
@Ghalko I am almost done with the hotfix. It was happening for any user (self or otherwise). The problem is in this check: https://github.com/CenterForOpenScience/osf.io/blob/27969d652c226fbc0b1226256378b0b4182679c2/website/templates/profile.mako#L170 . 
`"number_public_components"` isn't in the mako context, so the condition is always `True`.
