### ISSUE TITLE
[production] APA Citations

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2626]
Steps
-------
1. Go to project: https://osf.io/r9pqe/?view_only=8be7e07f6c4a4b0aa21ba44c97a4608a
2. Go to Mendeley Add-on, choose format "American Psychological Association 6th Edition"
3. Copy citation for the last entry, "De Jong, K.P.,...."
4. Go to Son of Citation Machine with same information (http://old.citationmachine.net/index2.php) and generate APA 6th edition citation
5. Go to Mendeley Desktop and generate same citation

Expected
-----------
All citations would have the same format. 

Actual
--------
Citations generated by Mendeley desktop and Son of Citation Machine are the same:
De Jong, K. P., & Geus, J. W. (2000). Carbon Nanofibers: Catalytic Synthesis and Applications. Catalysis Reviews, 42(4), 481–510. http://doi.org/10.1081/CR-100101954

but citation generated by Mendeley Add-on on the OSF is different:
De Jong, K. P., & Geus, J. W. (2000). Carbon Nanofibers: Catalytic Synthesis and Applications. doi:10.1081/CR-100101954

**Comment by lbanner** [comment]
Interesting. @lyndsysimon, when you get a moment. Thanks.

**Comment by lyndsysimon** [comment]
I'm fairly sure the issue here is that we're missing some attributes in the conversion between what Mendeley's API returns and the CSL-Data format.

This can be fixed by setting the appropriate keys in [`website.addons.mendeley.model#Mendeley._citation_for_mendeley_document`](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/addons/mendeley/model.py#L129).

It looks like the missing keys are: `source`, `pages`, `issue`, and `volume`.

Here is the API result for that object, when accessed from Mendeley's Research Catalog via their public API explorer:

```json
{
  "title": "Carbon Nanofibers: Catalytic Synthesis and Applications",
  "type": "journal",
  "authors": [
    {
      "first_name": "KRIJN P.",
      "last_name": "DE JONG"
    },
    {
      "first_name": "JOHN W.",
      "last_name": "GEUS"
    }
  ],
  "year": 2000,
  "source": "Catalysis Reviews",
  "identifiers": {
    "isbn": "0161-4940",
    "issn": "0161-4940",
    "doi": "10.1081/CR-100101954"
  },
  "keywords": [
    "Carbon",
    "Carbon filaments",
    "Carbon nanofibers",
    "Carbon nanotubes",
    "Catalyst support",
    "Catalytic synthesis",
    "Filamentous carbon",
    "Gas storage",
    "Graphite"
  ],
  "pages": "481-510",
  "volume": "42",
  "issue": "4",
  "websites": [
    "http://www.tandfonline.com/doi/abs/10.1081/CR-100101954"
  ],
  "month": 11,
  "day": 30,
  "id": "d47b0015-2fec-3c6b-b091-1b2120defcec",
  "accessed": [
    2012,
    10,
    4
  ],
  "file_attached": false,
  "link": "http://www.mendeley.com/research/carbon-nanofibers-catalytic-synthesis-applications-3",
  "reader_count": 52,
  "reader_count_by_academic_status": {
    "Professor": 2,
    "Post Doc": 4,
    "Ph.D. Student": 9,
    "Researcher (at an Academic Institution)": 2,
    "Researcher (at a non-Academic Institution)": 1,
    "Student (Postgraduate)": 1,
    "Student (Master)": 5,
    "Student (Bachelor)": 2,
    "Doctoral Student": 2
  },
  "reader_count_by_subdiscipline": {
    "Engineering": {
      "Miscellaneous": 6,
      "Nanotechnology": 1
    },
    "Earth Sciences": {
      "Miscellaneous": 1
    },
    "Chemistry": {
      "Miscellaneous": 9,
      "Petroleum": 2,
      "Applied Chemistry": 1
    },
    "Materials Science": {
      "Miscellaneous": 4,
      "Plastics": 2
    },
    "Physics": {
      "Miscellaneous": 2
    }
  },
  "reader_count_by_country": {
    "United States": 2,
    "Ukraine": 1,
    "Netherlands": 1,
    "United Kingdom": 1
  },
  "group_count": 1,
  "abstract": "<snipped for brevity>"
}
```

**Comment by lbanner** [comment]
You want to make it happen @lyndsysimon ? -- or you think good for an intern project?

**Comment by lyndsysimon** [comment]
Sorry - yes, it's a suitable intern task. It touches on a lot of things (OSF, addons, external APIs, citations, the CSL-JSON data format), but the change is a small one and there should be enough information above to keep the problem space small enough to be manageable.

@ticklemepierce reached out to me over chat, and I let him know that I'm happy to help with this if there are any major roadblocks.

**Comment by lbanner** [comment]
:+1:
