### ISSUE TITLE
Add clarifying message when Registering a Project re: It's components

### ISSUE THREAD

**Issue by lbanner** [CenterForOpenScience/osf.io#2627]
Similar to language added to Component (sub-project) Registration #2615, let's add the following message when a user clicks to Register a Project:

'You are about to Register the project "Parent Project Name" and everything that is inside it. If you would prefer to register just a particular component of "Parent Project Name", please click back and navigate to that component and then initiate registration.'

**Comment by bnosek** [comment]
assuming the part "of the ," is fixed to indicate the project name, yes, looks good.

**Comment by lbanner** [comment]
Interesting ... was actually using field indicators in the text above, and GH took them literally -- should have known! Updated above with quotes instead to indicate variable fields per project. Thanks.

**Comment by sloria** [comment]
On staging now.
