### ISSUE TITLE
[Production & Staging] Linking 2 projects to one another causes endless loop 

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2629]
## Steps
1. Go to a project (A) that you have admin access on
2. Add a link to another project (B) that you have admin access on
3. Now go to project (B)
4. Add a link to project (A)

## Expected
That linking 2 projects together would be allowed, but only once

## Actual
Linking 2 projects together creates an endless loop for the 2 projects.  
Causes issues with the project organizer

![screenshot 2015-05-04 21 55 50](https://cloud.githubusercontent.com/assets/9381062/7465950/6fab3c4a-f2a8-11e4-81e0-a78551cf75c5.png)

**Comment by brianjgeiger** [comment]
This one is expected. As long as it doesn't cause the folders to automatically open, and as long as the folders only open once for any given link on reload, it's fine. That's an odd situation that will happen in testing but less in normal life. 

On the other hand, imagine links that are four or five projects apart that eventually link to one that was part of that chain. You will want them to open at any given point of that chain. There are also times where you'll want to directly link two projects together.

.:Brian

**Comment by lbanner** [comment]
OK -- with that explanation ... I think I will close this for now. TY.
