### ISSUE TITLE
Dataverse Addon: let user choose between installations of Dataverse

### ISSUE THREAD

**Issue by pdurbin** [CenterForOpenScience/osf.io#2636]
As of this writing https://osf.io/getting-started/#dataverse indicates that the Dataverse Addon can only be used with https://dataverse.harvard.edu

@rliebz and I have been chatting (most recently at http://irclog.iq.harvard.edu/dataverse/2015-05-05#i_19527 ) about how it would be fantastic is users could choose between installations of Dataverse when making use of the Dataverse Addon.

**Comment by rliebz** [comment]
This feature is currently in early stages of development at https://github.com/rliebz/osf.io/tree/feature/select-dataverse

**Comment by lbanner** [comment]
Yes -- going to mark this as 'enhancement' and 'working' and tag you @rliebz  - TY @pdurbin
