### ISSUE TITLE
Getting started videos - YouTube player interface bug

### ISSUE THREAD

**Issue by AndrewSallans** [CenterForOpenScience/osf.io#2640]
What you did (step by step)
-tried to advance video in embedded getting started videos 

Where does this happen on the OSF?
-https://osf.io/getting-started

What you expected
-to be able to advance the video

What actually happened
-control bar would disappear as the cursor neared it.  Tested this with Michael as well and he experienced the same issue.  

Potential causes
-maybe related to an update that Youtube made in the player

Suggest a solution

What will it look like when this issue is resolved?
-user will be able to advance video from within the embedded video player

**Comment by sloria** [comment]
@AndrewSallans What browser are you seeing this on?

**Comment by GaryKriebel** [comment]
@AndrewSallans what browser?  I don't seem to be experiencing it.

**Comment by AndrewSallans** [comment]
@sloria and @GaryKriebel Chrome Version 42.0.2311.135 (64-bit)

**Comment by GaryKriebel** [comment]
Chrome Version 42.0.2311.90 (64-bit) seems to work.... let's see what happens when I'm no longer "nearly up-to-date".

![screen shot 2015-05-06 at 8 38 37 am](https://cloud.githubusercontent.com/assets/9437946/7493016/4f9b2d38-f3cb-11e4-8b07-32bc0284bea6.png)

**Comment by GaryKriebel** [comment]
Still works for me.

**Comment by GaryKriebel** [comment]
Ok... here is the clarification.  It does not happen with all videos.  It does happen with the videos under the following sections:
 * Project Organizer
 * Dashboards
 * User Profile
 * Projects
 * 2nd video under Projects
 * Files
 * Links
 * Forks
 * Registrations
 * Contributors
 * Privacy
 * View-only Links
 * Mendeley
 * Citations
 * Statistics

**Comment by PatrickEGorman** [comment]
All of the videos appear to have the same css selectors.

```html
    <div class="col-md-8 col-md-offset-2 col-sm-12">
        <div class="gs-video embed-responsive embed-responsive-16by9">
            <div class="embed-responsive-item youtube-loader" id="(video id)"></div>
        </div>
    </div>
```

Could the problem be with the youtube account?

**Comment by PatrickEGorman** [comment]
Actually the first 3 videos are of a different container class and are embedded in the getting_started.mako template.  I will continue to investigate this error

**Comment by PatrickEGorman** [comment]
After spending a fair chunk of time on this error and trying pretty much everything I could think of, I've found that it is tedious and has no obvious solution.  I feel like my time would be better spent elsewhere and unless somebody else wants to invest a lot of time in a minor, obnoxious error, I'd recommend ignoring it.
