### ISSUE TITLE
Getting started videos - menu overlap

### ISSUE THREAD

**Issue by AndrewSallans** [CenterForOpenScience/osf.io#2641]
What you did (step by step)
-resized getting started videos page

Where does this happen on the OSF?
-https://osf.io/getting-started

What you expected
-resizing to happen without menu overlap

What actually happened
-menu and video/text sections overlapped

![screen shot 2015-05-06 at 8 20 26 am](https://cloud.githubusercontent.com/assets/2151933/7492700/c533cada-f3c8-11e4-9002-458be642660b.png)

Potential causes

Suggest a solution

What will it look like when this issue is resolved?
-overlap will not occur

**Comment by ginavuu** [comment]
This is also happening to me when browser window is small. However, the outline re-sizes when you scroll by the videos and then goes back to overlapping after.
![resize](https://cloud.githubusercontent.com/assets/11032617/7522118/256f5092-f4c1-11e4-8d44-73534691310c.PNG)

**Comment by zkraime** [comment]
@GaryKriebel I'm interested in taking a jab at this

**Comment by lbanner** [comment]
OK @zkraime -- We can assign it directly in GH if you accept your invite to the COS org. -- Did you get one? Thanks.

**Comment by zkraime** [comment]
@GaryKriebel I forgot to check my other email yesterday afternoon - just accepted! 
Thanks

**Comment by lbanner** [comment]
Done!

**Comment by sloria** [comment]
Fix has been merged. Will be released in 0.41.0
