### ISSUE TITLE
[staging & production] Alerts with contradicting content for forked projects

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2644]
Related to #2616 in that there are 18 separate alerts, which is absolutely absurd. 

# Steps
1. Log into staging or production 
2. Go to a project on which you have authorized several add-ons for the project and components but where another user has also authorized add-ons (https://staging.osf.io/q57ph/ is an example on staging and https://osf.io/b9v2w/ is on production -- let me know if you want to fork this so that I can briefly make it public)
3. Attempt to fork the project
4. Read the modal messages about add-on authorizations
5. Confirm and submit to complete forking the project

# Expected
I expect that the add-on authorization for the fork would act in a manner that is consistent to the modal description.

# Actual
The modal description and the fork alerts are either contradictory or not clear. 

In the modal, it says that Dropbox will be authorized for the fork:
![screen shot 2015-05-06 at 10 28 11 am](https://cloud.githubusercontent.com/assets/5975444/7495498/6045f81e-f3dc-11e4-8db0-00b33ac37560.png)

But then there are two alerts with contradictory information. See the first and seventh alert:
![screen shot 2015-05-06 at 10 25 53 am](https://cloud.githubusercontent.com/assets/5975444/7495525/876653e4-f3dc-11e4-9c42-ff2f43004caa.png)

Then the alert that is second from the bottom reads that authorization is transferred to the forked project
![screen shot 2015-05-06 at 10 25 35 am](https://cloud.githubusercontent.com/assets/5975444/7495542/9f5927d8-f3dc-11e4-84a7-64b45ec83d06.png)

Additionally, the modal only refers to the forked *project* not forked *components*, but most of the alerts are related to "forked component." It's unclear which component these alerts are referring to, since there are multiple components in this project. Are they referring to different components? Is authorization the same for all components? It is really confusing.

**Comment by caileyfitz** [comment]
This is also troublesome for our project vs component distinction. @samchrisinger @sloria @GaryKriebel @lbanner

**Comment by samchrisinger** [comment]
@sloria , I can address this here: https://github.com/CenterForOpenScience/osf.io/pull/2643

**Comment by lbanner** [comment]
The "contradictory" notification for Dropbox? ... let's be sure to keep the focus tight for now. Thanks.

**Comment by nanchen47** [comment]
The fix pr by @samchrisinger has been merge and deployed.
