### ISSUE TITLE
[staging & production] Language change for added files in logs

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2649]
# Steps
1. Go to a project/component on staging or production
2. Go to Settings > Select Add-ons
3. Enable and configure an add-on for the project/component
4. Go to the Files tab
5. Add a file to the project/component
6. Return to the project/component overview page
7. Look at the logs for the file and add-on additions

# Expected
I expect that since both logs start with **User added**, that the preposition for adding would be the same.

# Actual
The preposition for adding an add-on is "to", whereas the preposition for adding a file is "in"

Add-on:
![screen shot 2015-05-06 at 12 06 24 pm](https://cloud.githubusercontent.com/assets/5975444/7497431/5a3c0efc-f3e8-11e4-8fbd-34eb06c86c0f.png)

File:
![screen shot 2015-05-06 at 12 06 11 pm](https://cloud.githubusercontent.com/assets/5975444/7497432/5f29ab18-f3e8-11e4-8d9f-cdf94e8eea37.png)

As per discussion with @brianjgeiger and @sloria, the preposition should be "to" in both cases.

**Comment by leb2dg** [comment]
I'm looking into this.

**Comment by chennan47** [comment]
@leb2dg this is already fixed in https://github.com/CenterForOpenScience/osf.io/pull/2772

**Comment by leb2dg** [comment]
@chennan47 Great! Does #2772 fix the preposition issue as well? The difference is still on production (see below screen shot).
![screen shot 2015-05-22 at 4 04 22 pm](https://cloud.githubusercontent.com/assets/7131985/7778759/81628d38-009c-11e5-874e-3c07a5eefe27.png)

**Comment by chennan47** [comment]
@leb2dg that pr fixes this problem but just haven't been merged yet.

**Comment by lbanner** [comment]
Nice dialog @leb2dg and @nanchen47 -- appreciate it.

**Comment by nanchen47** [comment]
The fix has been deployed.
