### ISSUE TITLE
Comments should no longer be GUID objects?

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#2650]
Currently, comments have GUIDs. There has been discussion of making them non-GUID objects.

Discussed in https://github.com/CenterForOpenScience/osf.io/pull/2534. This should be resolved before merging that PR.

**Comment by lbanner** [comment]
Agreed, and will hold this until post-Epic. Thanks for noting.

**Comment by samanehsan** [comment]
Comments are still GUID objects, but now they use 12-character guids instead of the 5-character ones that get assigned to projects, files, users, etc.
