### ISSUE TITLE
[staging & production] Removed component still recorded as registered in log

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2656]
# Steps
1. Go to a project which has multiple components
2. Delete one of the components
3. Register the project
4. Look at the log

# Expectation
I expect that the logs would only record registrations of non-deleted nodes.

# Actual
The log records that the deleted component was registered. Clicking the name of the deleted component redirects to "Resource deleted" page. 
Log:
![screen shot 2015-05-06 at 5 26 47 pm](https://cloud.githubusercontent.com/assets/5975444/7504050/201212ee-f415-11e4-8ed4-5a9b497f9902.png)
After pressing **EOS**:
![screen shot 2015-05-06 at 5 26 57 pm](https://cloud.githubusercontent.com/assets/5975444/7504051/22d8745a-f415-11e4-854b-719129f7f6a1.png)

**Comment by nanchen47** [comment]
This pr has been merged and deployed to production.

**Comment by samchrisinger** [comment]
This hotfix is definitely an improvement, but registrations with deleted components will now get 500's instead. 

I'm proposing this as a better fix: https://github.com/samchrisinger/osf.io/commit/9dd9a657c192564cc4cc86ce49aa4b7572868d5a,
and will include this in Archiver

**Comment by chennan47** [comment]
Isn't this the same as
https://github.com/CenterForOpenScience/osf.io/pull/2724/files#diff-b4b50a4acab364147a53259fa3fe9b3fR1695

**Comment by samchrisinger** [comment]
Sorry @nanchen47, your hotfix has yet to make it into release/0.39.0... or maybe regressed during a merge. Will make sure the release branch gets updated.
