### ISSUE TITLE
Rename project organizer "folders" to "collections"

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2663]
Steps
-------
1. Go to the Project Organizer

Expected
------------
Button in the status bar will say, "New Collection"

Actual
--------
Button in the status bar says, "New Folder"

Now that the OSF can make folders in the grid view, the things in the project organizer should be referred to as Collections (and Smart Collections) to keep people from  getting confused. This will need changing in all the relevant status bar buttons and in the legend.

**Comment by GaryKriebel** [comment]
The upcoming PR from @caneruguz takes care of this, yes?
![screen shot 2015-05-07 at 2 56 28 pm](https://cloud.githubusercontent.com/assets/9437946/7523387/6724ab42-f4c9-11e4-823c-67c72bf2e5db.png)

![screen shot 2015-05-07 at 2 57 26 pm](https://cloud.githubusercontent.com/assets/9437946/7523392/6baa40a0-f4c9-11e4-94e9-abaf11084968.png)

**Comment by brianjgeiger** [comment]
Yes. Is that slated for 36?

**Comment by lbanner** [comment]
If it is related to this #2606 then yes!

**Comment by brianjgeiger** [comment]
:+1:

**Comment by GaryKriebel** [comment]
it is

**Comment by GaryKriebel** [comment]
Fixed by https://github.com/CenterForOpenScience/osf.io/pull/2606

**Comment by caneruguz** [comment]
@GaryKriebel this issue can be closed.
