### ISSUE TITLE
[Production & Staging] Dropbox add-on does not show folder picker on auth

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2666]
## Steps
1. Go to a project you have admin privileges on
2. Go to the project settings page
3. Enable the dropbox add-on
4. Click to import the access token
5. If the folder picker appears, refresh the page. If not, Deauthorize and import the access token again
6. Attempt to click on 'change' to change the selected folder (which is none)

## Expected
When importing the access token, the folder picker would appear or an error message would be shown to the user if the token is invalid. Clicking to 'change' the folder would show the folder picker to the user.

## Actual
The folder picker does not appear, clicking the 'change' button to envoke the folder picker below to change the folder does no action.
![screenshot 2015-05-07 15 04 35](https://cloud.githubusercontent.com/assets/9381062/7523547/69a015d6-f4ca-11e4-9000-5f6c8fd95335.png)

**Comment by samchrisinger** [comment]
@lbanner  @GaryKriebel 

Can you please assign me?

**Comment by lbanner** [comment]
You got it!

**Comment by samchrisinger** [comment]
Resolved in https://github.com/caneruguz/treebeard/pull/81,
defer until @caneruguz's next feature PR for OSF goes in

**Comment by caneruguz** [comment]
@lbanner the PR @samchrisinger is referring to has been merged and it is in production. Can we test this and close based on result?

**Comment by samchrisinger** [comment]
:+1:, this is already tested

**Comment by lbanner** [comment]
OK good -- I'll close -- TY
