### ISSUE TITLE
OSF favicon changes

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2667]
Sometimes, when I visit the OSF, the favicon for the site is a black box that says "OSF." Other times, it is the COS open symbol. I cannot find a rule for when it is one over the other. In fact, I can visit the same page and get different icons:

![screen shot 2015-05-07 at 3 26 35 pm](https://cloud.githubusercontent.com/assets/4965832/7524113/d2361494-f4cd-11e4-9922-955ebdb1e2de.png)

The icon should remain consistent and not switch between the two. In choosing one, I would suggest the black on that says OSF to maintain separate branding.

**Comment by GaryKriebel** [comment]
I believe I have only seen the COS logo.  Are you getting some cached version from your history?  When was this changed from the black OSF?

**Comment by jlcohoon** [comment]
I've definitely seen both on multiple occasions. I think it was actually changed from the black to the open symbol at one point, but it seems like there is some way that it uses the old version on occasion. I'll keep on the lookout for the next time it happens.

**Comment by brianjgeiger** [comment]
It was changed at the end of August.

**Comment by GaryKriebel** [comment]
I don't see the old icon in the code with my local instance.  It wouldn't still be on the server would it?

**Comment by samanehsan** [comment]
Closing this, but feel free to re-open if it happens again!
