### ISSUE TITLE
Disable making public registrations private

### ISSUE THREAD

**Issue by GaryKriebel** [CenterForOpenScience/osf.io#2670]
With the advent of DOIs/ARKs, it does not make sense to let a user change a Registration back to Private after they made the Private registration Public.   Once public, you can create a DOI.  If the user makes the project private again, then those linking via the DOI will land on a page where they don't have access.  This is not a behavior we desire.

**Comment by brianjgeiger** [comment]
Is the DOI/ARK completely under our control, or can people make DOIs outside of the OSF?

**Comment by HarryRybacki** [comment]
@GaryKriebel to confirm, are we disabling the make private functionality for **all** registrations or just those with a DOI/ARK?

**Comment by GaryKriebel** [comment]
@brianjgeiger ... only available after you make your registration public.

**Comment by GaryKriebel** [comment]
@HarryRybacki .... you are correct... All public registrations will no longer be able to be made private again.

**Comment by HarryRybacki** [comment]
@GaryKriebel on it

**Comment by samanehsan** [comment]
Now that public registrations can only be retracted and not made private, is this still an issue? @HarryRybacki @GaryKriebel

**Comment by GaryKriebel** [comment]
Correct.  

I'll close.
