### ISSUE TITLE
"Recent activity" on dashboard and project overview say they are in UTC time when they are not

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#2671]
Steps:
---------
1) Do some action on the OSF (i.e. create a project)
2) Go to the dashboard page's watchlist
3) Check the timestamp on the log 

Expected: 
--------------
Since there's a sentence at the top saying all times are displayed in UTC offset, I expected the timestamps to be UTC time. 

Actual:
----------
The timestamps are localized! 
![screen shot 2015-05-07 at 8 15 57 pm](https://cloud.githubusercontent.com/assets/6414394/7528454/2526c7fc-f4f6-11e4-8750-58a5b4946fc8.png)

And the tooltips are UTC: 
![screen shot 2015-05-07 at 8 15 48 pm](https://cloud.githubusercontent.com/assets/6414394/7528561/cddce2b8-f4f7-11e4-93b7-803b5a8ef37a.png)

The sentence "All times displayed at -0400 UTC offset" should be taken out since it's no longer true!

**Comment by nanchen47** [comment]
From what I am understanding, UTC offset doesn't mean UTC time. It means the difference between your local time zone and the UTC time. I think the current behavior is correct. Close for now.
