### ISSUE TITLE
Presentation service - non-bibliographic contributors appear in search results

### ISSUE THREAD

**Issue by AndrewSallans** [CenterForOpenScience/osf.io#2672]
***Need to clarify this tomorrow, observed at usability session but having tough time recreating now***

Problem
1) Search of OSF discovers project with named contributor and "Presentation Service" as second contributor
2) Click on project and contributor list does not show "Presentation Service" as a listed contributor (presumably is on as a non-bibliographic contributor)

Correct behavior
Neither search results or project contributor list should show "Presentation Service" as a contributor, as it is non-bibliographic

**Comment by nanchen47** [comment]
Same issue as https://github.com/CenterForOpenScience/osf.io/issues/2447. Close this one.
