### ISSUE TITLE
[Production & Staging] Files search does not clear on delete

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2673]
## Steps
1. Go to this project that has files in OSF storage: https://osf.io/9jtkg/
2. Go to the files tab and enter the letters 'sn' into the search field
3. When the file 'snowmen' is the only one listed, click it to view and go to the files detail page
4. Make note of the files listed in the file tree (should see: Boston City Flow.jpg, IMG_6126.JPG, test.txt, snowmenQA.jpg, and Seussical.pdf listed) with 'snowmenQa.jpg highlighted.
5. Now in the search bar above the file tree on the right, enter the letters 'te' to search for another file in the list
6. Should now only see the file 'text.txt' listed in the file tree
7. Hit the backspace or delete button 2 times to clear out the 2 letters entered
8. Now make note of the files listed in the file tree.  There is now 1 less file listed.  The file 'Seussical.pdf' is not longer showing in the list in the file tree

## Expected
I would expect that by entering search criteria and then deleting the criteria, I would be returned to the initial state of the folder and files listed.

## Actual
The search does not allow deleting and starting over with out refreshing the page.  The search is not cleared when deleting.

**Comment by chennan47** [comment]
@caileyfitz can you verify this problem still exists?

**Comment by caileyfitz** [comment]
Am not seeing this problem anymore. @nicipfeiffer can you check that this is resolved for you?

**Comment by nicipfeiffer** [comment]
Looks to be fixed @chennan47 @caileyfitz
