### ISSUE TITLE
[staging & production] No pointer icon for x in legend modal

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2674]
Reported on the 0.35 Trello board:

# Steps
1. Log into staging or production 
2. Press the **i** button next to Projects above the project organizer.
3. In the legend modal, hover over the **x** to close the modal

# Expected
I expect that the **x** in the legend modal would have a pointer cursor.

# Actual
There is no pointer cursor. 

@samchrisinger said that this is a treebeard issue and that @caneruguz has a PR with a fix up for this already.

**Comment by caneruguz** [comment]
@GaryKriebel this issue should be resolved now

**Comment by GaryKriebel** [comment]
This is good now.
