### ISSUE TITLE
[staging & production] Can't see all components when permission to one is denied

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2677]
Reported by @nicipfeiffer on the 0.35 Trello board:

## Steps
1. Go to a project you have admin on that has many nested components/projects
2. Give read access to all but one of the components
3. Make all components public, except the one that hasn't been granted access to
4. Log in as the read access contributor
5. Look at the project page, try to see all components nested beneath the one not granted access to
6. Go to the project settings and configure notifications page

## Expected
I would expect that all other components would be visible to the read access user, including those nested in the component not granted access to.  

## Actual
The user with read access cannot see the nested components/projects below the one they are not given access to.  
![f](https://trello-attachments.s3.amazonaws.com/5547447fbd6976efb3ff519a/588x576/d7cd1b5f479eb51d85a6c309b0b2d029/Screenshot_2015-05-04_06.03.34.png)

However, on the project settings page in the configure notifications section the read access user can see all the nested projects/components.
![r](https://trello-attachments.s3.amazonaws.com/5547447fbd6976efb3ff519a/600x379/8d4a7db090ac11ab1816f22d29e0707a/Screenshot_2015-05-04_06.02.21.png)

@samchrisinger suggested waiting until https://github.com/CenterForOpenScience/osf.io/pull/2563 is merged to fix some of these issues. 

@brianjgeiger also noted that if rubeus.py hasn't been updated to handle this case, it likely will not work well.

**Comment by brandonPurvis** [comment]
Can I take this one?

**Comment by lbanner** [comment]
@brandonPurvis Based on notes above, let's hold on this for #2563 Thanks

**Comment by GaryKriebel** [comment]
closed with release 0.81.0
