### ISSUE TITLE
[feature request] Show icons on project overview page

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2678]
Reported by @nicipfeiffer on the 0.35 Trello board:

## Suggestion
The new icons are GREAT!

Why not improve the user experience by adding them on the project overview page for the components and linked projects??
![addicons](https://trello-attachments.s3.amazonaws.com/55482a0ae96b275cbf56cc97/1077x553/589eb5890f57ec7edb5ea33fd62edde5/add_icons.png)

**Comment by leb2dg** [comment]
I can look into this one as well since it is related to the icons.

**Comment by GaryKriebel** [comment]
@ticklemepierce .... are you already looking at this one and it just wasn't updated? If not, @leb2dg will take it.

**Comment by ticklemepierce** [comment]
@GaryKriebel No I am not.

**Comment by GaryKriebel** [comment]
It's all you, @leb2dg ... thanks!
