### ISSUE TITLE
Confusing wording in pre-registration question

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2679]
Reported by @abought on the 0.35 Trello board:

## Summary
When choosing the third registration type (`Replication Recipe (Brandt et al., 2013): Pre-Registration`), the experimenter is given a detailed questionnaire to fill out before they can register.

A question on page 3 refers to `#22`... but the questions are not numbered.
![das](https://trello-attachments.s3.amazonaws.com/554a23a77b0f30afdb1ba733/600x167/c52c0b795d8e50a1fb5029e738ff776a/Screen_Shot_2015-05-06_at_10.24.11_AM.png)

## Proposed change
Either number the questions, or make sure that the wording is updated to reflect the user interface.

**Comment by sloria** [comment]
I'm not sure that we can change this language, as it has been prescribed by a 3rd-party registration supplement. Ping @JeffSpies or @bnosek for feedback.

**Comment by JeffSpies** [comment]
Ah, I'll ping the leads.

**Comment by JeffSpies** [comment]
Mark agreed to just change "#22" to the question content.

**Comment by sloria** [comment]
The suggested change in @ticklemepierce's PR is:

> I have taken the following steps to test whether the differences listed in the previous question will influence the outcome of my replication attempt 

@JeffSpies Is this accesptable?

**Comment by JeffSpies** [comment]
+1

Thanks @ticklemepierce.
