### ISSUE TITLE
[Production & Staging] Read permission contributors cannot add comments

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2684]
## Steps
1. Go to a private project that you have admin access to
2. Go to the sharing tab and click to add a contributor
3. Add a contributor that you have log in access for also
4. Give the contributor you are adding 'read' permissions to the project
5. Go to the project settings tab
6. In the Configure commenting section, ensure that 'Only contributors can post comments' is selected (if not please update)
7. Log out as the admin contributor
8. Log in as the 'read' contributor
9. Go to the project
10. Try to add a comment

## Expected
I would expect that the 'read' contributor would be able to add a comment to the project, per the verbiage in the project settings "Only contributors can post comments".  A user with 'read' permissions is a contributor, after all.

## Actual
The user with 'read' permissions that is a contributor on the project is not allowed to add comments.
So either, read contributors should not be allowed to post comments on projects OR the wording in the project settings page needs to made more clear to users, which currently is not accurate.

**Comment by sloria** [comment]
@bnosek and/or @JeffSpies -- unsure if the expected behavior in the OP is correct. Should "read-only" contributors be allowed to post comments?

**Comment by bnosek** [comment]
I agree with Nici.  Read-only contributors are not allowed to change the wiki, files, etc., but they are a contributor on the project making the minimal case of offering comments on what *should* be done to the project a desirable function.

**Comment by sloria** [comment]
Ok, this has been changed on production.
