### ISSUE TITLE
[Production & Staging] Projects renamed on the dashboard are not returning in the 'Go to project' dropdown

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2685]
Renaming a project from the dashboard, then search in go to project and it will not appear
## Steps
1. Go to the project dashboard
2. Highlight a project that you have admin or read+write access to
3. In the grey bar at the top, you should see the name of the project with a pencil icon to the right
4. Click on the pencil icon to edit the name of the project
![screenshot 2015-05-08 11 33 47](https://cloud.githubusercontent.com/assets/9381062/7539604/25e34cb2-f576-11e4-978d-f845275b0b0d.png)
5. Enter a change to the name of the project (preferably with the beginning of the name)
6. Hit 'Rename'
7. Notice in the project dashboard that the name change has been picked up
![screenshot 2015-05-08 11 35 05](https://cloud.githubusercontent.com/assets/9381062/7539645/56735c3c-f576-11e4-94f8-b2730b6bd408.png)
8. Now on the right side onboarder widget, click to 'Go to a project'
9. Begin entering the new name for the project
10. Notice that the dropdown does not pick up the new name for the project
![screenshot 2015-05-08 11 36 57](https://cloud.githubusercontent.com/assets/9381062/7539684/9a910b26-f576-11e4-9498-69949c35cbd9.png)

## Expected
I would expect that the 'go to project' would pick up a renamed project

## Actual
When renaming the project on the dashboard, then using 'go to project' the dropdown search is not picking up the renamed project.

**Comment by brianjgeiger** [comment]
As I recall, you can pre-populate the typeahead dropdown so that it doesn't have to do a search under certain circumstances, but I though it would go ahead and search as well. Might just be a matter of adjusting some settings on typeahead.

**Comment by sloria** [comment]
This is the expected--but not ideal--behavior. We load the project data for the "Go to project" on page load. Therefore, a rename on the project organizer will not be reflected on "Go to project" (or any other onboarder widget) until the page is reloaded.

It's a tradeoff; loading the project data on page load means that the typeaheads respond faster. IMO, this benefit outweighs the cost of handling the edge case Nici described.

**Comment by zkraime** [comment]
@GaryKriebel 
Is this still an issue? Or are we keeping the current tradeoff?

**Comment by lbanner** [comment]
Good question @zkraime -- I think we accept the current trade-off, it makes sense, and likely most users will not try to search immediately post name-change i.e. without reload -- I am going to close. Thanks.
