### ISSUE TITLE
[Production & Staging][figshare] Delete 'x' showing for 'read' contributors on files tab

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2687]
Read-only access users of a component see the ‘x’ next to draft figshare files.  Clicking the ‘x’ gives a message that the user does not have permission to delete the file.  Maybe the ‘x’ should not even be there?  With all add-ons authorized, figshare is the one one that shows the ‘x’ to delete

## Steps
1. Go to a private project that you have admin access to
2. Go to the sharing tab and click to add a contributor
3. Add a contributor that you have log in access for also
4. Give the contributor you are adding 'read' permissions to the project
5. Go to the project settings tab
6. Enable, authorize and link a repo for the github add-on
7. Log out as the admin contributor
8. Log in as the 'read' contributor
9. Go to the project
10. Go to the files tab for the project
11. Move the mouse to a draft figshare file, mouse over the action column beside the file
12. A red 'x' appears
13. Click the 'x' to delete the draft figshare file
14. See the error message 'You don't have permission to delete this file.'

## Expected
I would expect that since read contributors are described on the Getting Started page as: "Assigning "read" privileges means that the contributor can see any project or component they are listed as a contributor on" the delete red 'x' would not appear on the files tab for any files.

## Actual
With all add-ons configured, the only folder that has the 'x' next to files when in 'read' access is figshare.
![screenshot 2015-05-08 12 56 28](https://cloud.githubusercontent.com/assets/9381062/7541249/ac0e90ac-f581-11e4-9814-8df4c9edab40.png)

**Comment by hmoco** [comment]
I can work on this.

**Comment by lbanner** [comment]
You got it -

**Comment by samanehsan** [comment]
Closed by #2866.
