### ISSUE TITLE
[Production & Staging] Importing Github access token causes the project settings page to jump

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2690]
## Steps
1. Login as a contributor with admin on a project
2. Go to the project settings tab
3. Enable the github add-on
4. Click to import the access token
5. Pay attention to the page after clicking

## Expected
That the page would stay anchored at the github configuration section, nothing would jump or move expect for the repo dropdown being added.

## Actual
The page jumps, sometimes to the very top of the settings page and other times it jumps slightly with extra lines added.  The project navbar shifts back and forth also.

(I had a gif, but it's not cooperating)

**Comment by haoyuchen1992** [comment]
Hi Nici, I just followed the steps and tried to replicate the problem. But it looks good. Here is the gif.
![github-addon](https://cloud.githubusercontent.com/assets/5420789/7866156/8a9ffe32-053b-11e5-8082-3a6393bd3e02.gif)
#### Do you still remember what browser you used when you found this issue?

**Comment by haoyuchen1992** [comment]
I just tested IE, firefox, and Safari. In summary, IE and Safari will jump the page while firefox and chrome not.

**Comment by lbanner** [comment]
@haoyuchen1992 ... want to take this one on? @caneruguz could be resource.

**Comment by haoyuchen1992** [comment]
@lbanner I can take it!

**Comment by haoyuchen1992** [comment]
Sorry, I made a mistake in old statement. Only IE would jump the page. Because in our code, we use `window.location.reload();` to refresh our page. And all the browsers, except IE, could remain the old position.

**Comment by lbanner** [comment]
OK ... make it so!
