### ISSUE TITLE
Metrics Update

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2692]
Currently there is a script that runs daily (automatically): https://github.com/CenterForOpenScience/osf.io/blob/573d098d071eb8930225d88721e8f25d6b6014bc/scripts/analytics/benchmarks.py

There is also a script that gets run, manually, every month or so: https://github.com/CenterForOpenScience/osf.io/blob/develop/scripts/metrics.py

Should track the items from the second script daily (number projects, number registrations, etc.). Combining the two scripts would be more efficient.

**Comment by hmoco** [comment]
Would this simply entail rewriting the non-overlapping code to benchmarks.py, and add those values to the table written to 'main.txt'?

**Comment by lbanner** [comment]
@sloria -- insight for @hmoco above? TY

**Comment by Johnetordoff** [comment]
@sloria this has been merged, can we close it?
