### ISSUE TITLE
[feature request] Provide indication of deactivation request

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2694]
Same suggestion for production... just didn't want people to request deactivation on their production accounts.

# Steps
1. On staging, go to user settings
2. Go to Account Settings
3. Scroll to Deactivate Account
4. Press 'Request Deactivation' 
5. Confirm that you want to deactivate account 
6. Refresh the page

# Expected
I expect that there would be some indication that the Deactivate Account button has been pressed. 

# Actual
Immediately after pressing the button, it grays out and is disabled, but upon refresh, the button appears as normal:
![screen shot 2015-05-08 at 4 39 50 pm](https://cloud.githubusercontent.com/assets/5975444/7545098/0043a1ca-f5a1-11e4-96e5-b5d59bee3e74.png)

Even though an OSF admin will follow up with users about deactivation requests, I think it would be helpful to know if they have already requested deactivation. For example, if I leave my computer open and Nici presses Deactivate Account, I will have no knowledge that she has done so. Or, if I press Deactivate Account and do not immediately hear back from an admin, I may think that my request hasn't gone through and send multiple deactivation requests. I guess I just don't see any reason why we would want to re-enable the button to allow users to press Deactivate Account a second time.

**Comment by GaryKriebel** [comment]
Closed via https://github.com/CenterForOpenScience/osf.io/pull/5732
