### ISSUE TITLE
Project Tags with Special Characters.

### ISSUE THREAD

**Issue by GaryKriebel** [CenterForOpenScience/osf.io#2696]
#Steps to Reproduce
1. Open a project which which you have write/admin access.
2. Tag the project with an apostrophe in it. (e.g. "1 o'clock") and hit enter.
3. See the tag is correct.
![screen shot 2015-05-11 at 11 14 32 am](https://cloud.githubusercontent.com/assets/9437946/7568102/eac1e6ec-f7ce-11e4-842c-6c1bc95d3364.png)
4. Refresh the page.
5. See that the tag has had the apostrophe removed.
![screen shot 2015-05-11 at 11 15 08 am](https://cloud.githubusercontent.com/assets/9437946/7568117/ff67a640-f7ce-11e4-9ef7-cbaeb9f32379.png)
6. Now add a tag that contains both an apostrophe and a question mark.
![screen shot 2015-05-11 at 11 15 37 am](https://cloud.githubusercontent.com/assets/9437946/7568262/c4b1009a-f7cf-11e4-8796-f6664f8477d0.png)
7. See that the tag is correct.
![screen shot 2015-05-11 at 11 20 02 am](https://cloud.githubusercontent.com/assets/9437946/7568269/d088ac7e-f7cf-11e4-9c7a-ad6dbf940a8a.png)
8. Refresh the page and see that the tag was never saved.
![screen shot 2015-05-11 at 11 21 32 am](https://cloud.githubusercontent.com/assets/9437946/7568286/e62eb622-f7cf-11e4-8545-b4495fcab6ed.png)

**Comment by lbanner** [comment]
@zobairAlijan will be taking a look at this one.

**Comment by ZobairAlijan** [comment]
It looks like, It is working now.

**Comment by chennan47** [comment]
@ZobairAlijan just verified on production. The problem still exists.

**Comment by PatrickEGorman** [comment]
I can give this one a look through if nobody else is working on it

**Comment by ZobairAlijan** [comment]
Patrick, I'm working on it and it is almost done.

**Comment by PatrickEGorman** [comment]
I just finished it a couple of hours ago....  I figured since you hadn't worked on this in almost a week, it'd be fine if I took over
