### ISSUE TITLE
Two $ signs in a single section of a wiki causes odd formatting

### ISSUE THREAD

**Issue by evomellor** [CenterForOpenScience/osf.io#2697]
Hello,
I was editing a wiki and wanted to refer to a dollar amount twice in a paragraph. However, two dollar signs in the same paragraph resulted in some very odd formatting between the two $ signs. Attached is a screenshot of the formatting (under "The Prize" section). This is the page in which that behavior was seen (https://osf.io/x5w7h/wiki/home/), but I have since edited the page to spell out the dollar amount to avoid this behavior. Thanks! David
![screen shot 2015-05-11 at 2 13 25 pm](https://cloud.githubusercontent.com/assets/11249723/7572258/cacbd7be-f7ea-11e4-89d5-65d0ef1ca6a7.png)

**Comment by GaryKriebel** [comment]
@brianjgeiger does the dollar sign signify any special formatting?

**Comment by brianjgeiger** [comment]
Yes, it's for MathJax.

**Comment by brianjgeiger** [comment]
#2039

**Comment by GaryKriebel** [comment]
Is one able to escape the $ in the wiki?

**Comment by brianjgeiger** [comment]
I'm not sure. I know very little about the implementation of MathJax; it was done before my changes and I don't really use LaTex, so ¯\_(ツ)_/¯. Sometimes these things are particular about where spaces go in relation to the special character, but it could be a matter of an escape sequence.

**Comment by brianjgeiger** [comment]
It looks like we need to change the mathjax settings a bit. http://docs.mathjax.org/en/latest/tex.html#tex-and-latex-math-delimiters

**Comment by sloria** [comment]
Looking into this.

**Comment by sloria** [comment]
@evomellor You should now be able to escape dollar signs like so:

```
\\$1,000,000 to 1000 researchers... We believe that $1,000...
```

I believe only the opening `$` needs to be escaped.

**Comment by evomellor** [comment]
Yes, that worked, thank you!
