### ISSUE TITLE
[staging & production] Cannot add project to dashboard when having only admin read access

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2715]
# Steps
1. Log into staging or production as user A
2. Go to a project on which user A and user B have admin access
3. Open another window and log in as user B
4. As user B create a component within that project and *not* add user A as a contributor to that component
5. Confirm that user A has read access via being an admin on the parent project (user B can go to Sharing page of the component and ensure that user A's name is listed under 'Admins on Parent Projects')
Here, user A is Cailey and user B is Muffin:
![screen shot 2015-05-14 at 9 56 02 am](https://cloud.githubusercontent.com/assets/5975444/7633091/fdd72172-fa1f-11e4-883c-9ed72c277184.png)
6. As user A, go to the project
7. Look at the top-right of the page to add project to dashboard 
8. Look for the icon to watch project

# Expected
I expect that user A would be able to add the project to the dashboard and watch the project.

# Actual
User A does not have the option to add the project to the dashboard (button is completely missing) or watch the project (button is disabled). 
![screen shot 2015-05-14 at 10 47 08 am](https://cloud.githubusercontent.com/assets/5975444/7634094/967de07c-fa26-11e4-8b79-539eb7082fd8.png)

**Comment by chennan47** [comment]
It's still a private component. User A can view it only because he has
admin right on parent project. User A can still see all the logs of the
component from parent project log. But I don't think we should offer user A
the right to track the private component from watch log. In real world,
User A can just ask User B to add him as a contributor to that component to
track it.

**Comment by caileyfitz** [comment]
@sloria what are your opinions on this?

**Comment by brianjgeiger** [comment]
If you can see it without the use of a special link, you should be able to put it in your project organizer.

**Comment by caileyfitz** [comment]
+1 to @brianjgeiger -- that is my thought

**Comment by chennan47** [comment]
Talked with @lbanner @saradbowman , you can view that project just becasue you are the admin of the parent project. You have the right to be aware what's going on. However, as the fact you are not a contributor of that child component, you should not be able to include that in your project organizer as your project or a public project. Neither should you be able to watch it to track it. @sloria thoughts?

**Comment by brianjgeiger** [comment]
If they can make a bookmark to go to the project whenever they want (which they could), they should be able to use the project organizer to go to it. Also, they could go around the "don't use the project organizer" restriction by going to their project organizer, expanding the project that they are administrator on, and dragging the component into another folder.

What disabling that button does is to create an inconsistent user interface for reasons that are opaque to the end user. If they can view it, they should be able to add it to their project organizer in all they ways they can other projects.

**Comment by bnosek** [comment]
Just chatted with Nan about it.  I agree with Brian G.

**Comment by sloria** [comment]
Should now be fixed.
