### ISSUE TITLE
[presentation service] List aggregate number of downloads on presentation page

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2720]
On the main presentation sharing service page (https://osf.io/presentations), we list the names of conferences and number of submissions for each.
![screen shot 2015-05-14 at 3 43 13 pm](https://cloud.githubusercontent.com/assets/7749914/7640230/fc24f0ea-fa4f-11e4-8ab7-30d3477f670d.png)

On each individual conference site (osf.io/view/spsp2015, for example), we list all talks and include number of downloads of each.
![screen shot 2015-05-14 at 3 42 26 pm](https://cloud.githubusercontent.com/assets/7749914/7640222/e663391a-fa4f-11e4-8c03-243ee3e6e9f7.png)

It would be great for marketing purposes to also list the aggregate number of downloads of all the posters/talks for a particular conference on osf.io/presentations, to show the impact the work is having.

**Comment by nanchen47** [comment]
Talk with @lyndsysimon. This will be included in the new piwik update.
