### ISSUE TITLE
redirect presentation service URL

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2744]
As we're rebranding the Presentation Sharing Service as "OSF for Meetings," we should change the URL from osf.io/presentations to osf.io/meetings. It would be best to retain osf.io/presentations and have it redirect to osf.io/meetings.

**Comment by nanchen47** [comment]
Once https://github.com/CenterForOpenScience/osf.io/pull/2742/files gets merged in, this can be closed.

**Comment by nanchen47** [comment]
The redirect fix has been merged.
