### ISSUE TITLE
Some private component titles are publicly visible in logs

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2745]
Some, but not all, names of private components are listed in logs. For example, "Materials" is named as a component in this registration even though the component title is listed as private in the component list: 
![screen shot 2015-05-18 at 11 08 16 am](https://cloud.githubusercontent.com/assets/4965832/7683753/19fb2650-fd4f-11e4-8fc7-e86e67853dd4.png)

Also, here, the private registered component "Materials" has its name listed in the logs even though the name is hidden in the component list:
![screen shot 2015-05-18 at 10 54 16 am](https://cloud.githubusercontent.com/assets/4965832/7683719/e9a490ae-fd4e-11e4-992d-70033c55999d.png)

I have not been able to reproduce this myself. I have tried:
1. Creating a public project
2. Creating a private component within that public project
3. Viewing the public parent project in an incognito tab to see if the component name is shown in the log. It is not—no logs for this private component are shown at all. 
4. Registering the public project and its private component
5. Viewing the registration in an incognito tab to see if the component name is shown. It is not.

**Comment by sloria** [comment]
@jlcohoon This should now be fixed. Can you verify?

**Comment by jlcohoon** [comment]
looks good to me
