### ISSUE TITLE
[Production & Staging] Importing Github access token gives 500 error

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2758]
## Steps
1. Go to a project you have admin privileges on
2. Open the javascript error console for the current browser tab
3. Go to the settings tab and import the access token for the Github add-on
4. Select a private repo and hit Submit

## Expected
I would expect the private repo to be linked to the project successfully

## Actual
There is an error message 'Settings not updated'
And a console error of 500 internal server error

![screenshot 2015-05-19 10 39 34](https://cloud.githubusercontent.com/assets/9381062/7711832/48bee188-fe3b-11e4-9fe0-2b4e0d06c715.png)

Linking this issue also: https://github.com/CenterForOpenScience/osf.io/issues/2603#issuecomment-103205734
And @icereval and @chrisseto as I showed them the error and they looked into the sentry logs of the event.

**Comment by PatrickEGorman** [comment]
Would I be able to work on this?

**Comment by lbanner** [comment]
OK -- see if you can replicate it first @PatrickEGorman

**Comment by PatrickEGorman** [comment]
I seem to be getting a 404 error instead.  The repo is failing to link to the project

**Comment by PatrickEGorman** [comment]
I realized that my repo was empty.  Also, I'm thinking you need a private repo in github which I believe costs money.  I think I'll have to find a new issue.

**Comment by chennan47** [comment]
@PatrickEGorman if you are using a edu email for github registration and verify you are a student, you will enjoy the right to create a free private repo.

**Comment by PatrickEGorman** [comment]
I applied for the free private repo but have yet to hear back.  I hope to hear back and start work by or before Monday.

**Comment by PatrickEGorman** [comment]
I have yet to hear back from github.  I double checked and I definitely made the request.  I might suggest passing this issue to somebody who has permissions to create a private repo

**Comment by jinluyuan** [comment]
@nicipfeiffer @lbanner I'm able to successfully connect my private repos. Maybe this isn't an issue anymore?

**Comment by chennan47** [comment]
I don't think this is a problem anymore. I did link to my private github repo on production and staging.
