### ISSUE TITLE
[Production & Staging] Forgot Password does not recognize alternate emails

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2759]
## Steps
1. Log in to your account on osf.io
2. Go to the User Settings, Account Settings
3. Add a new email to your account
4. Confirm the email through the link that is emailed
5. Check that the new email is now listed as an alternate email 
6. Log out
7. Log in using the alternate email and your usual password (should work)
8. Log out
9. Click the Forgot Password link on the log in page
10. In the email field on the Forgot Password Request form, enter the alternate email

## Expected
Since I can use an alternate email to log into my account, I would expect to receive an email at the alternate email address to reset the password if I forget the password

## Actual
There is no email sent to the alternate email address

**Comment by chennan47** [comment]
@caileyfitz Can you verify this problem? I looked at the code. It looks fine and then I tried on production myself and got the reset  password email sent to my alternative email.

**Comment by caileyfitz** [comment]
@chennan47 I get the email also.

**Comment by nanchen47** [comment]
Closed for now and if you got this problem again @nicipfeiffer. Reopen it.
