### ISSUE TITLE
[Production & Staging] Add-on Icons are Draggable in Google Chrome

### ISSUE THREAD

**Issue by leb2dg** [CenterForOpenScience/osf.io#2761]
## Steps

In Google Chrome, go to a project with at least one component
Enable a few external storage add-ons for the project
Go to either the files tab or the project overview page
Collapse all the add-ons so that you can see them all (helpful if you have a ton of files)
Click an icon and drag it out of the container 
Unlike issue #2263 that occurs in IE the icon cannot be dragged into another add-on

## Expected

I expect that the icons would be non-draggable

## Actual

The icons are draggable in Google Chrome, and dropping them outside of the container causes an error in the Javascript code. Image below is a screen shot of the error that occurs when an add-on icon is dragged outside of the add-on container.
![capture](https://cloud.githubusercontent.com/assets/7131985/7713475/f35aa7bc-fe45-11e4-86cd-69d1156ea019.PNG)
.

**Comment by lbanner** [comment]
Good catch! You want to take this one on too @leb2dg ? Thanks.

**Comment by leb2dg** [comment]
Yes, I'll take this one as well!

**Comment by lbanner** [comment]
OK good - Thanks.

**Comment by samanehsan** [comment]
Closed by #2793
