### ISSUE TITLE
Slashes in Files logs awkward/confusing

### ISSUE THREAD

**Issue by samchrisinger** [CenterForOpenScience/osf.io#2763]
![screen shot 2015-05-20 at 9 11 27 am](https://cloud.githubusercontent.com/assets/2207561/7726474/57a9c20e-fed0-11e4-93eb-e538f99214d1.png)

The folder name is adad, looks like adadl (really adad /).

**Comment by chennan47** [comment]
According to previous discussion with @GaryKriebel @sloria , we left the end slash for folder only. But we may remove it if user feel confusing

**Comment by lbanner** [comment]
I'll agree with @samchrisinger here -- Would it be difficult to remove? I think that is preferable.

**Comment by chennan47** [comment]
@lbanner will do
