### ISSUE TITLE
Mobile site - dashboard layout issues

### ISSUE THREAD

**Issue by ticklemepierce** [CenterForOpenScience/osf.io#2774]
Expected
-------------
On the home page (dashboard), the projects table should fit on the screen.
Also, "Quick Tasks"/"Watchlist" should be right under this instead of having so much whitespace.

Actual
--------
![screen shot 2015-05-20 at 3 34 48 pm](https://cloud.githubusercontent.com/assets/8229937/7734838/260bade8-ff07-11e4-9084-957926605e97.png)
Table is too wide

<br>
![screen shot 2015-05-20 at 3 45 21 pm](https://cloud.githubusercontent.com/assets/8229937/7734852/3d2e5246-ff07-11e4-9e17-4049a164172a.png)
Tons of unnecessary whitespace

**Comment by revanthkolli** [comment]
@GaryKriebel can I work on this?

**Comment by GaryKriebel** [comment]
@revanthkolli ... all yours

**Comment by caneruguz** [comment]
Well hold on a second though. About these two issues:

1. The project table not fitting the screen is because treebeard scrolls below certain widths. I don't knwof if we want to change this. Can you test in mobile and see how the scrolling works? 

2. The white space is because we have a fixed height for treebeard. Changing this is definitely possible (check for instance the individual file view page) but proceed with caution. It is NOT a pure css issue because what will happend when the user expands folder when you already made the height fit the two rows only?

**Comment by caneruguz** [comment]
@GaryKriebel and @lbanner when interns open issues we need to review them first, in some cases they may not in fact be issues and/or they might need further discussion.

**Comment by ticklemepierce** [comment]
@caneruguz Does treebeard have to be a static height?

**Comment by caneruguz** [comment]
Treebeard needs to know the height to know how many things to draw. We have a solution for this in file view page. The point is you can't fix it to what is visible, it needs to be able to expand with toggling of folders.  There are a few steps to doing this. in fileViewTreebeard.js for instance there is 

```js
        ontogglefolder : function (tree) {
            Fangorn.DefaultOptions.ontogglefolder.call(this, tree);
            var containerHeight = this.select('#tb-tbody').height();
            if (!this.options.naturalScrollLimit){
                this.options.showTotal = Math.floor(containerHeight / this.options.rowHeight) + 1;
            }
            this.redraw();
        },
```

So you need to study what is going on there.

**Comment by revanthkolli** [comment]
@GaryKriebel So should I continue working on this or move onto another issue?

**Comment by GaryKriebel** [comment]
@revanthkolli Let's hold for now for discussion.

**Comment by lbanner** [comment]
@caneruguz Good insight -- keep catching these -- and thanks for prompting dicussion @revanthkolli

**Comment by nanchen47** [comment]
Will be considered when we enhance treebeard.
