### ISSUE TITLE
Mobile site - OSF logo is not vertically centered

### ISSUE THREAD

**Issue by ticklemepierce** [CenterForOpenScience/osf.io#2775]
Expected
-------------
OSF logo should be vertically centered and even with the magnifying glass and menu buttons

Actual
--------
![screen shot 2015-05-20 at 3 47 29 pm](https://cloud.githubusercontent.com/assets/8229937/7734892/8be714fe-ff07-11e4-8b97-73f59be663dc.png)

**Comment by nanchen47** [comment]
Duplicated as https://github.com/CenterForOpenScience/osf.io/issues/2781
