### ISSUE TITLE
The tag disapears in develop stage.

### ISSUE THREAD

**Issue by ZobairAlijan** [CenterForOpenScience/osf.io#2776]
1. After adding a tag and refresh the page using cmd + shift + r, the tag disappear.
2. When adding something in tag section and hit enter throws 500 internal error
3. POST XHR http://localhost:5000/api/v1/project/zkpfx/addtag/tag/

4. "TypeError: clean_tag() argument after ** must be a mapping, not unicode " will popup in console.

![screen shot 2015-05-20 at 2 01 47 pm](https://cloud.githubusercontent.com/assets/9525062/7735196/acdec01a-ff09-11e4-9613-38e0d55761df.png)

![screen shot 2015-05-20 at 2 02 01 pm](https://cloud.githubusercontent.com/assets/9525062/7735198/ae6b8c42-ff09-11e4-911c-79af572366c1.png)

**Comment by lbanner** [comment]
@ZobairAlijan Can you provide a bit more clarity here -- also, best to follow the submission format guidelines: https://github.com/CenterForOpenScience/osf.io/blob/develop/CONTRIBUTING.md
Thanks!

**Comment by chennan47** [comment]
@ZobairAlijan Can't repo this problem on my localhost, staging or production.

**Comment by samanehsan** [comment]
@ZobairAlijan, what tag did you type in that gave you the 500 error?
