### ISSUE TITLE
[staging & production] Text hangover in add links modal

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#2778]
Similar to #1778 

### Steps

1. Go to project on which you have admin access
2. From the Project Overview page, click "Add Links" from the toolbar on the right
3. On staging, search for "super" and then click "supercalifragilisticexpialidocious"
4. Click the plus sign to add the link.

### Expected
I expect that all text will stay within the modal outlines.

### Actual
Some text hangs over if the name is long:
![screenshot 2015-05-20 17 29 41](https://cloud.githubusercontent.com/assets/7093086/7737190/47a72a94-ff17-11e4-83e3-af7ebeffdebe.png)

**Comment by haoyuchen1992** [comment]
Hi Natasha, I just tried to replicate the bug, but it didn't show me the same problem. And also I don't see the example link --"supercalifragilisticexpialidocious" any more. Is it because of the length of the name?

**Comment by NatashaRichter** [comment]
Hi Haoyu, I'm able to replicate it on staging and on production. If you search for just "super" when on staging, that project will appear and you'll see that the name extends past the modal. The same problem occurs on production (I just created a private sample project with a similar name) and it extends past the modal, as well. If you have trouble replicating again, come and find me!
