### ISSUE TITLE
Navbar refactoring

### ISSUE THREAD

**Issue by ticklemepierce** [CenterForOpenScience/osf.io#2781]
Expected
-----------
Everything in the navbar should be centered vertically.

Actual
--------
Similar to #2775, the logo is a bit off center on the full site, as is the gravatar/user name.

![screen shot 2015-05-21 at 9 56 49 am](https://cloud.githubusercontent.com/assets/8229937/7750013/b913be30-ff9f-11e4-8c02-f86c64808255.png)

**Comment by caneruguz** [comment]
This issue covers everything in #2775 , we can remove that one. The solution will require the same code.
