### ISSUE TITLE
Github markdown style checklists for the wiki

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2798]
## Steps
1. Create a github-style markdown checklist in the wiki
## Expected (well, kinda)

There would be a cool checklist 
## Actual

No cool checklist exists.

This is actually a feature request for something like https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments within our wiki syntax. It would involve a markdown-it plugin that has configurations for ajax-endpoints for handling checklist items, and the back-end changes necessary to support it. This is much more involved than the normal markdown-it plugins, but would be super-cool.

**Comment by BenPortner** [comment]
This would be great. Even greater would be a GitHub-style issues feature allowing assignment of labels and responsible contributors.
