### ISSUE TITLE
deleting files from a repo

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#280]
When the repo is linked to two components of a project, and, when looking at the parent project's file tree, you delete a file from the repo in one component, the other component doesn't update until page refresh. (see pretend-repo and it's discordant files in the picture) 
![screen shot 2014-03-06 at 11 33 19 am](https://f.cloud.github.com/assets/4965832/2347493/4cf0ccc8-a54d-11e3-961d-75b538a116e8.png)

**Comment by nanchen47** [comment]
Will be considered when we do a full refactor of the file pages.
