### ISSUE TITLE
Wiki Page "open_science_projects"

### ISSUE THREAD

**Issue by PatrickEGorman** [CenterForOpenScience/osf.io#2808]
I notice that the wiki page has a link for "open_science_projects".  I'm not sure if this a local problem or a universal problem for the whole site but I think "Open Science Projects" would look far more professional.  As far as I can tell, it's not hard coded in the site by the way.
![screen shot 2015-05-22 at 2 13 47 pm](https://cloud.githubusercontent.com/assets/7470770/7776959/2473f706-008d-11e5-8100-dabbe48d14c4.png)

**Comment by GaryKriebel** [comment]
@PatrickEGorman, where are you seeing this?

**Comment by PatrickEGorman** [comment]
The fact that you don't see it hints that it might be a local problem as I see it right here: https://osf.io/4znzp/wiki/home/ in the wiki homepage.  I do see it whether or not I'm logged in, so I thought it might be worth a check

**Comment by brianjgeiger** [comment]
Fixed.

**Comment by brianjgeiger** [comment]
That being said, if someone had a link to that page, it's broken now, so it may get changed back. Looking forward to Wikis being addressed by GUID rather than title.
