### ISSUE TITLE
Upload more than 100mb files

### ISSUE THREAD

**Issue by chennan47** [CenterForOpenScience/osf.io#2822]
<b>Steps</b>
1. log in to OSF
2. go to the file page
3. choose any file folder or addons
4. upload a file more than 100mb
5. It will pop up a message saying "can't upload files for more than 100mb"
then you will see
![screen shot 2015-05-25 at 11 07 16 am](https://cloud.githubusercontent.com/assets/4974056/7798956/57694ede-02ce-11e5-9cb7-8e064faa4a40.png)

<b>Expected</b>
Click on the red cross will dismiss that column, since the file is over size and is not actually uploading at all

<b>Actual</b>
Click on the red cross does nothing, you need to refresh the page to make the column goes away.

**Comment by zkraime** [comment]
@lbanner, Can I grab this?

**Comment by lbanner** [comment]
:+1:

**Comment by zkraime** [comment]
Finally got my file uploading to work. 
Tried to recreate - and I was able to except it looks a little different: 
![screen shot 2015-06-04 at 4 04 50 pm](https://cloud.githubusercontent.com/assets/11323460/7993353/96b5e00e-0ad3-11e5-9850-d362edeb4680.png)

It flashes a message saying: One of the files is too large (200.46 MB). Max file size is 128 MB.

The button doesn't work though, so it's the same issue essentially. 
Further though, there seems to be an issue with canceling a file that is in progress uploading. The same 'x' button doesn't do anything: 
![screen shot 2015-06-04 at 4 07 59 pm](https://cloud.githubusercontent.com/assets/11323460/7993459/40b83c78-0ad4-11e5-80b3-bf580e6b7df0.png)

@chennan47 @lbanner 
Should I create a separate issue for this, or just fix it as part of this issue's PR? thanks

**Comment by chennan47** [comment]
@zkraime They have done some UI change on the front end, but basically the error is the same. Thanks for the update for the issue.

**Comment by lbanner** [comment]
@zkraime You got this?

**Comment by zkraime** [comment]
@lbanner Yes, I'd like to complete this
