### ISSUE TITLE
[presentation service] search for tags on presentation service

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2831]
Each conference's list of talks/posters has a search bar to search within projects for that conference:

![screen shot 2015-05-26 at 12 49 32 pm](https://cloud.githubusercontent.com/assets/7749914/7817836/b75e44c0-03a5-11e5-915b-6e739f86fbf7.png)

The search function searches project title (I am not sure what else) - but does not search tags. Adding ability to search tags would make it possible to group and find presentations from the same session of a conference right from the presentation interface. (it is possible to use regular OSF search to do this now, but is less user-friendly)

**Comment by caneruguz** [comment]
@lbanner this is something I can quickly address if you give a go.

**Comment by lbanner** [comment]
Make it so! : )

**Comment by caneruguz** [comment]
Fix has been sent here, @sloria should review these before they go in, but there is no urgency. 
https://github.com/CenterForOpenScience/osf.io/pull/2855

**Comment by saradbowman** [comment]
damn you're fast! Thanks!

**Comment by nanchen47** [comment]
The pr already got in.
