### ISSUE TITLE
Downloading a file from Google Drive addon sends user to 500 error page

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2832]
<h4>Steps</h4>
1. Visit this file: https://osf.io/tj4is/
2. Download any version of the .gdoc file

<h4>Outcome</h4>
1. The file is not rendered
2. The user is brought to a page reporting a 500 error.
3. The console logs a 404 error for the favicon.

![screen shot 2015-05-26 at 1 49 37 pm](https://cloud.githubusercontent.com/assets/4965832/7819212/13340944-03ae-11e5-82be-2bebff3830d7.png)

<h4>Expected Outcome</h4>
1. The file should be downloaded
2. If there is an error in downloading the file, an error message should pop up on the OSF

**Comment by chrisseto** [comment]
@GaryKriebel or @lbanner this issue can be closed.
@jlcohoon this was fixed correct?

**Comment by lbanner** [comment]
Working fine -- I'll close. Thanks.
