### ISSUE TITLE
Cannot shift + select items below current view

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2843]
Reported on the 0.37 Trello board 

**This problem appears in Firefox and Chrome**

# Steps
1. Go to a project on which you have admin access that also has multiple add-ons enabled and many files
2. On the project overview page, scroll to the files grid
3. Within an add-on (preferably one with many files), click to select the first file listed in the grid
4. Scroll in the grid so that the highlighted file row is out of view 
5. Hold shift and select a file below the highlighted file (but still within the same add-on) to select all files

# Expected
I expect holding shift and scrolling to click will highlight all files in between the two selected files. 

# Actual
Nothing appears to happen. Clicking a file below the initial file (as long as the initial file is out of view) does not select the file, nor does it select all files between the two selected files.

**Comment by chennan47** [comment]
@caileyfitz I tried on production just now. It actually works for me. Can you verify that? And it should only not work if you shift select across different addons.

**Comment by caileyfitz** [comment]
@chennan47 I just tried on production as well, and I am seeing the same issue. Did you scroll so that the highlighted file (first click) was out of view? If it is still in view, shift + click *does* highlight all files between the two clicked files. This also only appears on Firefox and Chrome.

**Comment by samanehsan** [comment]
^ Since this is an issue with treebeard, @caneruguz suggested filing the issue in that repo
