### ISSUE TITLE
File Widget on Project Summary:  closing add-on folders and then scroll up makes the grid blank

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#2845]
**Reported on 0.37 board by @nicipfeiffer** 

## Steps
1. Go to https://staging.osf.io/nsdzh/
2. On the project overview page, in the files widget click the - to close expanded folders....do this for all add-on folders
3. Try to scroll the grid

## Expected
I would be able to scroll the grid and have collapsed folders

## Actual
The grid is blank, white even.

![screenshot_2015-05-22_14 12 41](https://cloud.githubusercontent.com/assets/10926926/7837309/404342c8-0454-11e5-975a-f9e04ccad92b.png)

Comments from the card: https://trello.com/c/9qPLUPDh/151-project-organizer-closing-add-on-folders-and-then-scroll-up-makes-the-grid-blank

@caneruguz said...I can't replicate this issue in the link given above. The scrolling is happening fine. Also the wording is strange, Project Organizer is not the files page. @nicipfeiffer I need more information on this. :/
@nicipfeiffer : @caneruguz I am still seeing this. It's on the Project Overview page, in the files widget. You have to have add-on folders and then close them all and scroll up to replicate.
@caneruguz : @nicipfeiffer, I'm closing all the folders and not seing. Do you mean subfolders and not add on root folders?

**Comment by nicipfeiffer** [comment]
@caneruguz I am still seeing this, now on production.

**Comment by lbanner** [comment]
Good catch -- This has been hard to intentionally replicate.

**Comment by caneruguz** [comment]
Can we check if anyone else is seeing this and update the issue for a link on production?

**Comment by lbanner** [comment]
I have seen it a couple times, but I don't think it persists on link over time ... If I or @nicipfeiffer see it again, we'll add a link.

**Comment by nicipfeiffer** [comment]
@caneruguz and @lbanner 
Here is an update:
Steps:
1. Go to https://osf.io/6hjum/
2. On the project overview page, in the files widget click the - to close expanded folders....do this for all add-on root folders, starting at the bottom
3. Try to scroll up on the grid

Here is a screenshot from production:
![screenshot 2015-06-02 11 50 57](https://cloud.githubusercontent.com/assets/9381062/7940502/4cc0f7b4-091f-11e5-9aa0-67ee3d107633.png)

**Comment by caneruguz** [comment]
Okay I'm finally seeing this, and I have a suspicion about why. My theory is that it only happens when a toggle reduces the row count to less than 50 and only when enough scroll down has already happened; which is why it happens when you close starting from the button and close amazon s3 specifically. 

@nicipfeiffer you are a genius! I'm sorry I ever doubted you.

**Comment by nicipfeiffer** [comment]
@caneruguz YAY!  I am so relieved that I am NOT crazy!  And YOU are a genius figuring out the S3 relationship to this issue!

**Comment by lbanner** [comment]
Cool @caneruguz - TY

**Comment by nicipfeiffer** [comment]
@caneruguz I am still seeing this issue on production. https://osf.io/6hjum/

**Comment by caneruguz** [comment]
@sloria or @icereval can you confirm that these changes are pushed to the server? The PR referenced here solved my local copy problems but production still has this bug.

**Comment by caneruguz** [comment]
@nicipfeiffer can you add me to the project https://osf.io/6hjum/ ? I get a forbidden message.

**Comment by nicipfeiffer** [comment]
@caneruguz done.  And I just checked and I can still reproduce this.

**Comment by GaryKriebel** [comment]
Closed
