### ISSUE TITLE
Renaming files not logged correctly in Activity Log

### ISSUE THREAD

**Issue by HayleyBance** [CenterForOpenScience/osf.io#2846]
Reported by: Rick Klein on May 20, 2015

**This problem appears in Chrome** 

# Steps:
1. Go to an OSF project page where you have admin/read write permissions
2. Click "files" tab at top of page
3. Upload a file
4. Click next to the file name to select it
5. A toolbar with "rename" should pop up
6. Click rename, and input a new file name.
7. Click rename again to make the change.
8. Check the activity log.

# Expected behavior:
Activity log will display that the file was renamed.

# Actual behavior:
Activity log displays a series of new uploads and file movements but it is unclear that a file was renamed.

@caileyfitz said: Example of renaming a folder: was named perro, is now named dog! 

![screen_shot_2015-05-26_at_12 13 09_pm](https://cloud.githubusercontent.com/assets/12612547/7837351/759f9bc4-0454-11e5-93a8-4094a8cb2e2c.png)

**Comment by revanthkolli** [comment]
@lbanner can I work on this?
