### ISSUE TITLE
No DAZ option for Dataverse Add-on

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#2848]
Reported on the 0.37 Trello board by @nicipfeiffer 

## Steps
1. Go to a project on which you have admin access that also has the Dataverse add-on enabled 
2. On the project overview page, scroll to the files grid
3. Within the Dataverse add-on, click to select the Dataverse add-on name and any folders within the add-on.
4. Check the toolbar to see if the "Download as Zip" option appears.

## Expected
I expect that the "Download as Zip" button will appear in the toolbar.

## Actual
The "Download as Zip" option does not appear in the toolbar.

**Comment by lbanner** [comment]
In current state DAZ is not supported for Dataverse.

**Comment by nanchen47** [comment]
Will be considered later when the obstacle it solved.
