### ISSUE TITLE
No DAZ Option for Github Add-on

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#2849]
Reported on the 0.37 Trello board by @nicipfeiffer 

# Steps
1. Go to a project on which you have admin access that also has the Github add-on enabled
2. On the project overview page, scroll to the files grid
3. Within the Github add-on, click to select the Github add-on name and any folders within the add-on.
4. Check the toolbar to see if the "Download as Zip" option appears.

# Expected
I expect that the "Download as Zip" button will appear in the toolbar.

# Actual
The "Download as Zip" button does not appear in the toolbar.

**Comment by PatrickEGorman** [comment]
I checked this error out.  If you click the download button, it downloads it as a .zip file.  It'd be an easy edit to change "download" to "download as zip" but I wonder if there would be space for that in the Files editor bar

**Comment by lbanner** [comment]
Though @PatrickEGorman is correct about the parent folder, in current state of DAZ, GitHub is not supported for sub-folders and DAZ.

**Comment by nanchen47** [comment]
Will be considered later when the obstacle it solved.
