### ISSUE TITLE
[production] Add-on permissions modal do not mention folders

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2854]
The permissions modals that appear when a user connects an add-on have not been updated to include folder permissions, now that users can create/modify folders in add-ons. 

The modals should be updated to indicate what actions users can take with regard to folders for a given add-on:
![screen shot 2015-05-27 at 1 23 19 pm](https://cloud.githubusercontent.com/assets/7749914/7842820/b3afc17c-0473-11e5-9c76-0b53d0fb9122.png)

Example: Add/update Files/folders and view/download files and folders

**Comment by lbanner** [comment]
@samchrisinger -- How does / or does your add-on UI work impact these modals?

**Comment by samchrisinger** [comment]
All I plan to change is the bottom row, i.e. content is registered but versions are lost.

@brianjgeiger and I discussed a possible rework of this UI. Now might be the time
