### ISSUE TITLE
Increase password character limit

### ISSUE THREAD

**Issue by binoculars** [CenterForOpenScience/osf.io#2856]
When I went to reset my password on osf.io: 

	Password is too long. Password should be at most 35 characters.

My random password generator generates passwords of at least 50 characters. For reference: [Recommended policy on password complexity](http://security.stackexchange.com/questions/3248/recommended-policy-on-password-complexity)

**Comment by brianjgeiger** [comment]
Agreed. Unless there's some technical limitation, I don't see a reason to limit password length like that.

**Comment by revanthkolli** [comment]
Can I work on this? @lbanner

**Comment by lbanner** [comment]
You got it @revanthkolli -- TY

**Comment by GaryKriebel** [comment]
@revanthkolli please accept the github invite request for the organization so that we can assign the issue to you.

**Comment by revanthkolli** [comment]
@GaryKriebel My bad, just did.
