### ISSUE TITLE
Replace social media logo bar in footer with counter/share bar

### ISSUE THREAD

**Issue by AndrewSallans** [CenterForOpenScience/osf.io#2860]
Footer currently has this:  
![screen shot 2015-05-28 at 9 37 25 am](https://cloud.githubusercontent.com/assets/2151933/7861288/3f961f5c-051d-11e5-8d55-8529ce77aadd.png)

Recommending that we switch to one like this to increase follows:
![screen shot 2015-05-28 at 9 38 23 am](https://cloud.githubusercontent.com/assets/2151933/7861300/4c26c122-051d-11e5-89c3-6049a945f91a.png)

**Comment by GaryKriebel** [comment]
I would think that this would be a relatively easy change and perhaps appropriate for the intern pool.  Do we need further discussion on this? @JeffSpies @bnosek ?

**Comment by JeffSpies** [comment]
@AndrewSallans, you're recommending we display how many people have shared the main page of the OSF?

**Comment by AndrewSallans** [comment]
Possibly recommending that we include the count, but definitely recommending that a follow only requires clicking the button there on the bar and not necessarily going to the 3rd party service and then clicking the button.  Trying to reduce steps.

**Comment by JeffSpies** [comment]
Discussion is required off-line. Closing for now.
