### ISSUE TITLE
Pagination component for logs is left-aligned.

### ISSUE THREAD

**Issue by JeffSpies** [CenterForOpenScience/osf.io#2861]
Steps
-------
1. Go to project dashboard of a project with many log entries.
2. View the log widget on the project dashboard.

Expected
------------
The bootstrap pagination component should be centered.

Actual
--------
The bootstrap pagination component is left-aligned.

See ![screen shot 2015-05-28 at 10 17 17 am](https://cloud.githubusercontent.com/assets/512000/7862318/0f6147b6-0523-11e5-8c2c-1e54a08680c9.png)

@jlcohoon Are there other pagination components that are left aligned on the OSF?

**Comment by chennan47** [comment]
The other place has the pagination is the add contributor and add link modal:
![screen shot 2015-05-28 at 10 40 30 am](https://cloud.githubusercontent.com/assets/4974056/7862800/3fc7107c-0526-11e5-987c-47809d54245b.png)

@JeffSpies do you want there to be centered as well?

**Comment by lbanner** [comment]
We don't like the left-align?

**Comment by JeffSpies** [comment]
If we get a vertical separator between Results and Adding similar to the
horizontal separators we currently have.

**Comment by JeffSpies** [comment]
@lbanner traditionally that would be centered or full-width. The latter making some sense because we have "..." indicating we don't have space to fill out the pagination (while we do). 

Left-aligned looks off to me, but it is subjective.

**Comment by ZobairAlijan** [comment]
@GaryKriebel Can I work on this?

**Comment by lbanner** [comment]
I am good with that @ZobairAlijan -- you are tagged. Check with @chennan47 w/any questions -- he did the foundational work.

**Comment by ZobairAlijan** [comment]
@lbanner Thank you

**Comment by jlcohoon** [comment]
One more place with left align—the watchlist:

![screen shot 2015-05-29 at 12 42 51 pm](https://cloud.githubusercontent.com/assets/4965832/7887623/82beeb40-0600-11e5-9c65-c9f5d7882c01.png)

**Comment by chennan47** [comment]
The watch log is using the same template as logs. So change on one place
will affect the other. It's good for people who did this fix to verify that.

**Comment by ZobairAlijan** [comment]
This issue has been fixed and waiting to be merged.

**Comment by nanchen47** [comment]
Will be considered in later pagination enhancement. Thanks.
