### ISSUE TITLE
[Feature Request] Add hint for enabling Add-on(Amazon s3) 

### ISSUE THREAD

**Issue by haoyuchen1992** [CenterForOpenScience/osf.io#2863]
## Steps
1) Go to a project and select setting tab
2) Enter user credentials and press Submit.
3) Enable Amazon s3 
4) It asks me for user credentials (Access Key and Secret Key) for Amazon S3

## Expected
Since I am new to both osf add-on and Amazon S3,  I would like to see some hints to explain what are these credentials and how can I get them. 

## Actual
There is no hint.
![screen shot 2015-05-28 at 10 12 09 am](https://cloud.githubusercontent.com/assets/5420789/7862892/de438c12-0526-11e5-925c-0a313269deb3.png)

## Suggested Solution
We may add question marks at the end of titles(such access key) and when users hovers their mouse on it, it will give them some text explanation and hyperlinks. For example the explanation in this [link](http://blogs.aws.amazon.com/security/post/Tx1R9KDN9ISZ0HF/Where-s-my-secret-access-key) is helpful.

**Comment by hmoco** [comment]
Dataverse's is similar in the sense that it is not a simple button click to connect, but it provides a 'hint' button that makes the process very easy. Something like that for Amazon might be useful
![screen shot 2015-05-28 at 11 31 57 am](https://cloud.githubusercontent.com/assets/6268982/7863966/56ed20aa-052d-11e5-9ce8-6c3b96c49077.png)
