### ISSUE TITLE
Mobile site cutting long names in half on profile

### ISSUE THREAD

**Issue by GageGaskins** [CenterForOpenScience/osf.io#2877]
# Steps to Reproduce
1. Go to osf.io and search for any users.
2. Find someone with long name, >12 characters

# Expected
Full name is shown like others on the site

# Actual
![screen shot 2015-05-28 at 2 24 25 pm](https://cloud.githubusercontent.com/assets/7023074/7867704/a3fc449e-0545-11e5-9cc6-76c6c7c41b7b.png)

Name is cut in half. This is emulation, but has been repeated on production site.

**Comment by ticklemepierce** [comment]
This is a duplicate of #2260

**Comment by lbanner** [comment]
Cool -- I'll close this one. TY
