### ISSUE TITLE
No easy way to access mid date range logs in large projects.

### ISSUE THREAD

**Issue by PatrickEGorman** [CenterForOpenScience/osf.io#2882]
# Steps to Reproduce 
1. Go to https://osf.io/ezcuj/ or any other large project
2. Look at recent logs
3. Try to make it to a page in the middle of the logs

# Expected
An easy way to scroll through page numbers.  (Possibly by clicking the three dots)

# Actual
One has to scroll through the pages individually
![screen shot 2015-05-28 at 4 45 12 pm](https://cloud.githubusercontent.com/assets/7470770/7870694/fbf36836-0558-11e5-8f43-c589defe43bd.png)

**Comment by lbanner** [comment]
Thanks @PatrickEGorman -- @ZobairAlijan has a PR that, I believe, helps overcome this: #2880

**Comment by nanchen47** [comment]
Will be considered in later pagination enhancement. Thanks.
