### ISSUE TITLE
Add tooltip on hover over project or component names

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2888]
We get many questions about how to change the name of a file or component. The answer is simple - click on the title from the project or component overview page.

A simple solution would be to add a tooltip on hover - "Rename." This is how Google docs handles renaming a file.

**Comment by brianjgeiger** [comment]
This functionality is currently being moved to the settings page.

**Comment by lbanner** [comment]
@brianjgeiger -- thanks -- is this change in functionality discoverable via a PR or WIP or Proposal?

**Comment by brianjgeiger** [comment]
https://github.com/CenterForOpenScience/osf.io/issues/2686

**Comment by lbanner** [comment]
OK-Will put 'working' via #2686

**Comment by nanchen47** [comment]
Same issue as #2686. Close this one and track this problem there.
