### ISSUE TITLE
Wiki menu lists components with empty wiki pages for non-contributors

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2891]
From the Community Github Repo, @bnosek :

It is very strange to navigate the component wikis of a project that I am visiting and have no content appear. If the component wiki does not have content, then it shouldn't appear in the menu (at least for visitors, not project contributors). Instead, that wiki page should not be listed in the left navigation bar.

For an example of the issue, navigate to "Data" in the left menu here:

https://osf.io/b98zw/wiki/home/

**Comment by caseyrollins** [comment]
@lbanner @GaryKriebel Can I grab this one?

**Comment by GaryKriebel** [comment]
done
