### ISSUE TITLE
Component widget shows on project overview even when no components exist

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2892]
<h4>Steps</h4>
1. Visit a project with no components that you are not a contributor on (https://osf.io/wj643/ for example).

<h4>Outcome</h4>
1. The component widget appears and says that there are no components.
![screen shot 2015-05-29 at 12 31 49 pm](https://cloud.githubusercontent.com/assets/4965832/7887431/fad0757e-05fe-11e5-9543-e1a712310b89.png)

<h4>Expected Outcome</h4>
1. The component widget should not appear if no components have been added and you are not a contributor.

**Comment by PatrickEGorman** [comment]
Would I be able to take a look at this?

**Comment by caneruguz** [comment]
I want to bring to attention again what Johanna said in Expected outcome. So @PatrickEGorman the logic here is not just
- if there are no components don't show 

but 
-If this user is not a contributor AND there are no components, don't show. 

Sorry if this was clear but I wanted to avoid a potential issue.

**Comment by samanehsan** [comment]
@jlcohoon, @caneruguz what about registrations? I think for consistency, if it's not on the project page it should not show up on the registration.

**Comment by chennan47** [comment]
I think for registration if there is not component the widget shouldn't
show up at all. Since even you are a contributor, you can't modify the
registration anymore.

**Comment by jlcohoon** [comment]
Right. The main point is that if you can't do anything with the
(nonexistent) components, you shouldn't see the widget. So, for a
registration, you also would not see the widget. In the case of a
registration neither non-contributors nor contributors should see the
widget if there are no components (like Nan said).

**Comment by samanehsan** [comment]
That makes sense -- thanks for the clarification! @PatrickEGorman, can you make this change in #2905?

**Comment by PatrickEGorman** [comment]
I thought it was too easy to be true.  I'll hop on that once I finish the profile settings issue

**Comment by jlcohoon** [comment]
is this closed because it got fixed? or because we decided no? It's definitely still happening (or happening again). See: https://osf.io/a8g32/

**Comment by lbanner** [comment]
Interesting .. @PatrickEGorman want to take a look? @sloria did we regress something? Thanks.

**Comment by sloria** [comment]
Hm, this was fixed before. @PatrickEGorman, would you mind taking a look at this again?

**Comment by PatrickEGorman** [comment]
Okay.  I'm between tasks anyway so I can investigate

**Comment by PatrickEGorman** [comment]
I took a look at it.  I added an simple if statement:
```% if ('write' in user['permissions'] and not node['is_registration']) or node['children']:```
to decide whether it was shown or not.  It appears that this project seems to have found some way through this if statement.  I'm not exactly sure.  At the moment I'm pretty busy with the api so I was wondering if somebody else could possibly take a look.
