### ISSUE TITLE
Login redirects the user back to their dashboard; should stay on page

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2893]
From the community repo, @evomellor:
When a user that is not logged in navigates or follows a link to a particular OSF project, the large instructions at the bottom encourage them to login, and this takes them to their dashboard. A login from a particular page should default to keeping the user on the page in which they logged in.

Example: 
1) log out of OSF
2) go to TOP guidelines: https://osf.io/9f6gx/
3) log in to OSF
4) user is on their dashboard and must hit back to continue reading the page they were on
5) the back button makes it look like the user is not logged in (a refresh of the page corrects this)

**Comment by Ghalko** [comment]
@jlcohoon Is this still happening? I can't seem to reproduce the behavior.

**Comment by evomellor** [comment]
I don't think it is, I first noticed this weekend that login now redirects user back to the page they are on. Perhaps this was part of 0.38 release.

**Comment by jlcohoon** [comment]
Looks good to me too—both when I log in from the toolbar or via the dedicated log in page.

**Comment by lbanner** [comment]
Closing -- and thank you.
