### ISSUE TITLE
Login Email Confirmation is Case Sensitive

### ISSUE THREAD

**Issue by geeksnglitter** [CenterForOpenScience/osf.io#2902]
I don't believe it should be.
![screen shot 2015-06-01 at 11 10 58 am](https://cloud.githubusercontent.com/assets/7839433/7915962/f9a929f0-084e-11e5-9df8-a0e526426e50.png)

**Comment by lbanner** [comment]
Upper + lower makes no difference - always - in email addresses? I think they might be case sensitive?

**Comment by brianjgeiger** [comment]
The internet would stop functioning if email were case sensitive. Agreed with @geeksnglitter, this form should be more permissive.

**Comment by lbanner** [comment]
:+1:
