### ISSUE TITLE
Dashboard File Upload Pretends to Upload to Nonexistent Projects

### ISSUE THREAD

**Issue by geeksnglitter** [CenterForOpenScience/osf.io#2913]
If you drag a file for upload on the dashboard and start typing in the "Select a Project" searchbar but then hit enter before you have selected a project, the file pops up with an empty status bar. The file cannot be uploading because it has nowhere to go.

![screen shot 2015-06-01 at 4 45 12 pm](https://cloud.githubusercontent.com/assets/7839433/7923017/04ee8b0a-087e-11e5-8194-2bf7fd32fcff.png)

This even happens when you have typed the name of one of your existing projects, but hit enter before you actually select it.

If you then try to select the name of a real project, you still cannot upload your file because the system believes it is still uploading the old file.

![screen shot 2015-06-01 at 5 04 05 pm](https://cloud.githubusercontent.com/assets/7839433/7923349/48d285f4-0880-11e5-8e43-97a464db6adf.png)

**Comment by lbanner** [comment]
Now this is an interesting one -- @caneruguz Do you have any insight here? Thanks.

**Comment by caneruguz** [comment]
I didn't do the coding for the onboarder but it seems to me like there is an Enter key binding on the form that should not be there because the typeahead selection still needs you to click on a row. 

@alexschiller can provide some insight but someone can go ahead and check out a fix for this.

**Comment by nanchen47** [comment]
Will be considered in on boarding refactor.
