### ISSUE TITLE
Forgotten Password Requests Do Not Check If Email Belongs to OSF User

### ISSUE THREAD

**Issue by geeksnglitter** [CenterForOpenScience/osf.io#2915]
I get a confirmation that a password reset email has been sent to my account no matter what email I enter into the password reset request box.

![screen shot 2015-06-01 at 5 19 37 pm](https://cloud.githubusercontent.com/assets/7839433/7923684/4fa47e16-0883-11e5-8796-49e694f0eb9d.png)

![screen shot 2015-06-01 at 5 20 05 pm](https://cloud.githubusercontent.com/assets/7839433/7923687/515b47d0-0883-11e5-8885-d4c9b35c1709.png)
 

It is expected that there would be an error sating "Email not in system" if there is no record of that email. If a user believes that they have signed up for the OSF, but haven't, it will leave them waiting for an email that will never come.

**Comment by chennan47** [comment]
I believe this is what we want. Provide information like "Email not in system" will leak user information since ppl can tell which email is registered or not. @lbanner @GaryKriebel Thoughts?

**Comment by geeksnglitter** [comment]
Could we say something like "if registered and email has been sent..." That
way the user knows what to do if they don't get an email?

**Comment by lbanner** [comment]
Yes, it is intentional for the reasons you note, I believe, @nanchen47 -- That's not a bad suggestion @geeksnglitter, but the notification to contact OSF support is already there.

**Comment by geeksnglitter** [comment]
Okay! Didn't realize it was expected behavior. Makes sense.

**Comment by lbanner** [comment]
NP -- good to point it out! I'll close this, thanks.
