### ISSUE TITLE
Add link to Google doc file if file cannot render

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2926]
This comes from the community repo: https://github.com/CenterForOpenScience/community/issues/183

<h4>Steps</h4>
1. Visit a Google slides file
2. Visit a Google doc file

<h4>Outcome</h4>
1. The slide file does not render, and gives the user a timeout error.
![screen shot 2015-06-02 at 10 30 08 am](https://cloud.githubusercontent.com/assets/4965832/7938280/b595b2dc-0912-11e5-855d-e978f1f92c1b.png)

2. The doc file (usually) does render, as a word document.

<h4>Expected outcome</h4>
1. As the document can be accessed elsewhere on the web, a link could be provided to users instead of the error message when a Google file of any kind does not render. This link could be provided for files that are never rendered, like slides, or files that just timed out but normally would render.
![screen shot 2015-06-02 at 10 34 05 am](https://cloud.githubusercontent.com/assets/4965832/7938351/0808fe34-0913-11e5-9b4f-28f440c02820.png)

**Comment by jlcohoon** [comment]
In today's infrastructure meeting, Jeff specified that users should have the option to visit the file even if it renders. This might mean that we need an additional button. That additional button could also be there for other services like Figshare or Dataverse. Maybe like this?
![screen shot 2015-06-02 at 2 53 31 pm](https://cloud.githubusercontent.com/assets/4965832/7944188/39c5378e-0937-11e5-898a-8b9ce191fa3a.png)

**Comment by lbanner** [comment]
Looks like this baby is on Epic list in present form, so prioritized as "high" and if stays on list, we'll get it assigned. Thanks.

**Comment by samanehsan** [comment]
@caseyrollins is working on adding links to the original addon files.

**Comment by jlcohoon** [comment]
fixed!
