### ISSUE TITLE
Who is using the OSF and what are they doing?

### ISSUE THREAD

**Issue by meg3c** [CenterForOpenScience/osf.io#2927]
Hayley and I are thinking about ways of cataloguing what users are doing with the OSF, which would be valuable knowledge, both for what is being done and also for what is not--what other projects should be on the OSF and are not appearing.  Input on this idea is welcome, including ways that users are being tracked that we are not aware of.

**Comment by nanchen47** [comment]
Will be considered in future analysis enhancement.
