### ISSUE TITLE
[Production & Staging] No add-on icon for Amazon S3 folder on Project Overview

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2931]
## Steps
1. Go to a project with Amazon S3 configured
2. Look on the project overview page in the files widget
3. Scroll down and find the Amazon S3 add-on folder
4. Look at the icon for the folder
5. Go to the files tab
6. Scroll down and find the Amazon S3 add-on folder
7. Look at the icon for the folder

## Expected
I would expect that the S3 add-on folder would be consistent with the other add-ons and have an icon for the folder.

## Actual
The icon is missing.

**Comment by nanchen47** [comment]
This pr has been merged and deployed on production.
