### ISSUE TITLE
[staging] github file icon is oversized and cut-off

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#2940]
Steps:
--------
1. Configure the github addon for a project on STAGING
2. Go to the project's overview page
3. Take a look at the files widget

Expected: 
-------------
I expected to see the circular github icon next to the github addon folder:
![screen shot 2015-06-02 at 7 52 44 pm](https://cloud.githubusercontent.com/assets/6414394/7949896/056e6594-0961-11e5-8015-dc228c5c85b2.png)

Actual:
----------
The icon is oversized and cut-off: 
![screen shot 2015-06-02 at 7 49 04 pm](https://cloud.githubusercontent.com/assets/6414394/7949873/ca3ce7c0-0960-11e5-8fca-7b43c08b8475.png)

**Comment by lbanner** [comment]
@caneruguz ? Any insight here.

**Comment by chennan47** [comment]
I think this is a bug on production, too. Didn't notice that when I trying to fix the S3 icon, I will address this.

**Comment by lbanner** [comment]
OK -- good.

**Comment by samanehsan** [comment]
@chennan47, I do not see this happening on production

**Comment by chennan47** [comment]
@samanehsan They roll back commits on master which revert the change the icon from img to span, fix all the icon problem on production with the side effect that now on some browser the icon is draggable.

**Comment by caneruguz** [comment]
The icons should not be images, we worked to make sure that they wouldn't be because of the draggable issue. Those changes should not have been reverted.

**Comment by brianjgeiger** [comment]
Just change the CSS like so, getting rid of background-position and background-repeat and replacing it with background-size. The icons were too large, so just needing shrinking.

![screen shot 2015-06-03 at 9 39 57 am](https://cloud.githubusercontent.com/assets/6599111/7961293/9272bf30-09d4-11e5-9cce-89ee0e125bde.png)

**Comment by brianjgeiger** [comment]
Also, is that inline CSS? It should not be inline.

**Comment by caneruguz** [comment]
Brian's fix is correct; but there is something fishy here. @nanchen47 is this on "develop" branch?

**Comment by chennan47** [comment]
@caneruguz They roll back the commits as occasionally merged develop into master. So the fix for the icon from img to span should be still on "develop" branch, I will do the shrink img based on develop and check all addons. If you have any other better plan, let me know. Thanks.

**Comment by nanchen47** [comment]
The pr is merged and deployed on production.

**Comment by sloria** [comment]
I'm still seeing this on staging.

**Comment by sloria** [comment]
Right now, the `release/0.40.0` branch is what is on staging. I will cherry pick Nan's fix into that branch before today's release.

**Comment by sloria** [comment]
Should be fixed now.
