### ISSUE TITLE
Onboarder renders some special characters in HTML

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2958]
<h4>Steps</h4>
1. Using the onboarder on the user dashboard, search for a project in the "Go to my project" field or in the "search for a project" field in the file upload section of the onboarder—be sure this project has an ampersand (&) in its name.

<h4>Outcome</h4>
1. Some, but not all project titles render the ampersand in HTML. Percent signs, exclamation points, and dollar signs all render properly.

![screen shot 2015-06-04 at 10 13 43 am](https://cloud.githubusercontent.com/assets/4965832/7986124/8201ca54-0aa3-11e5-82e5-a5df705e2005.png)

![screen shot 2015-06-04 at 10 14 01 am](https://cloud.githubusercontent.com/assets/4965832/7986128/87bd4428-0aa3-11e5-8305-6371849ab073.png)

<h4>Expected Outcome</h4>
1. Special characters should not be rendered in HTML anywhere on the OSF.

**Comment by haoyuchen1992** [comment]
I will look at it!

**Comment by abought** [comment]
To add a wrinkle:

It appears that these special characters are what is being stored in the database. Some (but not all) of our front end code is converting it back to HTML for display.

In the future, we will not be storing special characters in the database, and our front-end code will need to switch from **un-escaping** HTML special characters (or displaying them as-is) to **escaping** them for safety.

This back-end database change and migration will happen sometime after #2933 (markupsafe in frontend) lands. Suggestions on the best way to handle this are welcome.

**Comment by samanehsan** [comment]
I believe @lyndsysimon did a lot of work with escaping HTML site-wide.

**Comment by brianjgeiger** [comment]
As a general rule, we are explicitly converting a few characters during various parts of the process. Specifically &amp; &gt; &lt; and maybe one other. See https://github.com/CenterForOpenScience/osf.io/pull/2857 for an example.

**Comment by abought** [comment]
Indeed, Saman- I've been picking up from where #1308 left off. It didn't touch many JS files, though; phase 1 would just be Mako.

Currently, we store data as "markupsafe" in the database (see above example), but this will change ([https://github.com/CenterForOpenScience/osf.io/pull/2857#issuecomment-106866212](ref) - good find, @brianjgeiger ). 

Phase 2 of a markupsafe-move would be to take sanitization/encoding out of the back end.  Any Javascript that is currently trusting raw database contents will have to be checked for safety.

**Comment by haoyuchen1992** [comment]
@abought Since my pull request for this problem is based on JQuery HTML API, it assumes that the title doesn't contain any executable Javascript or HTML code. If the sanitization is out of the backend, it  need be replaced with non-JQuery solution.

**Comment by jlcohoon** [comment]
Did this get fixed? I'm still seeing the issue.

**Comment by sloria** [comment]
@haoyuchen1992 Can you take a look at this?

**Comment by haoyuchen1992** [comment]
@jlcohoon I just tested in both staging and production. Both work well. Where did you test it? What's the project name you used for testing?

**Comment by jlcohoon** [comment]
I'm sorry—this was from the regular search, not the onboarder. Should I log elsewhere? 

I saw the issue on production: 
![screen shot 2015-06-24 at 10 49 28 am](https://cloud.githubusercontent.com/assets/4965832/8334040/ccf52554-1a63-11e5-971a-962403e76ea5.png)


I searched for "Masicampo"

**Comment by nanchen47** [comment]
@jlcohoon So this is a problem of elastic search?

**Comment by jlcohoon** [comment]
Looks like it. originally when I logged this issue I was talking about the onboarder. But then found additional instances in OSF search. That last example is using elastic search.

**Comment by nanchen47** [comment]
This problem has been fixed.
