### ISSUE TITLE
[production] Dataverse Terms Modal doesn't reflect 4.0 changes

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2960]
There were several updates to Dataverse in version 4.0. The Modal doesn't reflect all changes. Current view:
![screen shot 2015-06-04 at 10 39 25 am](https://cloud.githubusercontent.com/assets/7749914/7986527/12629e6e-0aa6-11e5-9eb8-945d020ce6a5.png)

Revised Text should read:

Permissions
---
"Making an OSF project public or private is independent of making a Dataverse study public or private. The OSF allows you to release the latest draft version of a Dataverse dataset. "

---
The Dataverse community meeting is next week, and an ambassador will be presenting on the OSF - Dataverse connection. Would appreciate getting this update in before then if possible.

**Comment by lbanner** [comment]
Stealing from the interns @GaryKriebel ? :smiling_imp:

**Comment by GaryKriebel** [comment]
Fixed it prior to your tag. :angel:

**Comment by samanehsan** [comment]
@GaryKriebel, relevant issue about language in the dataverse terms modal: #623
