### ISSUE TITLE
View-only Link icon update

### ISSUE THREAD

**Issue by chennan47** [CenterForOpenScience/osf.io#2971]
<b>Steps</b>
Since the project organizer is using the new icon.  The view-only link's project/component icon needs an update accordingly.

Go to the sharing page of any project and checkout the view-only link table.
![screen shot 2015-06-04 at 1 54 48 pm](https://cloud.githubusercontent.com/assets/4974056/7990784/4aa0931a-0ac1-11e5-826f-7b4133552695.png)
![image](https://cloud.githubusercontent.com/assets/4974056/7990806/6c6536a4-0ac1-11e5-9a80-d6e39dc964ee.png)

It is a similar issue as https://github.com/CenterForOpenScience/osf.io/issues/2783

**Comment by leb2dg** [comment]
I can probably fix this after I finish the current issue I'm working on...may be a few days. If someone else wants to tackle it feel free! (I resolved #2783)

**Comment by lbanner** [comment]
Yours for now @leb2dg - TY
