### ISSUE TITLE
[Production & Staging] [Firefox] File version table has incorrect time

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2972]
## Steps
1. Log in to osf.io on the Firefox browser
2. Go to a project you have admin on 
3. On the project overview page click on the osf storage folder to select it
4. In the toolbar, click to upload a file
5. Refresh the page and look at the project log.  You should see a log entry for the file you just uploaded.  Make note of the time showing.
6. Click on the link in the log to go to the file
7. Look to the right of the rendered image at the version table for the file
8. Make note of the time.

## Expected
I would expect the time showing in the project log for a file upload and the time in the version table for the file to be the same.  I would expect the time in the version table to be the accurate time.

## Actual
The log for the file upload is showing the correct time.  However, the version table shows the incorrect time; it is 4 hours ahead of the current time.

![screenshot 2015-06-04 13 55 40](https://cloud.githubusercontent.com/assets/9381062/7990807/6d192240-0ac1-11e5-9661-e9c3e707388d.png)
![screenshot 2015-06-04 13 55 23](https://cloud.githubusercontent.com/assets/9381062/7990810/70ef3a1c-0ac1-11e5-96ea-fbadd56613ef.png)

Appears to only happen on Firefox.

**Comment by haoyuchen1992** [comment]
I will work on this.
