### ISSUE TITLE
[Production & Staging] Github: Creating a new repo on Node Settings gives many errors

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2976]
## Steps
1. Go to a project on osf.io that you are admin on
2. Go to the settings tab for the project
3. Enable the Github add-on
4. After importing the access token, click to create a new repo
5. Name the rep and Sumbit
6. Go to the projects' files tab
7. Open the error console
8. Find the folder for the Github add-on
9. Click on the + to expand the folder
10. Click on the folder to select and look in the toolbar
11. Click on the Upload button to upload a file

## Expected
I would expect the newly created repo to have no errors on the files tab.  
I would expect the toolbar to show branch selections in the toggle or not show the blank toggle if there are none yet.
I would expect to be able to upload a file to the new repo
I would be expect to be able to create a folder within the repo

## Actual
None of the actions for the toolbar buttons to create a folder or upload a file, or toggle the branch are working.
There is an error when uploading a file that 'Error
Could not upload file. The file may be invalid or the file folder has been deleted.'
The folder will not expand and shows an error when clicking the + next to the folder.

![screenshot 2015-06-04 15 57 25](https://cloud.githubusercontent.com/assets/9381062/7993373/b9c7230a-0ad3-11e5-90a3-5244be165576.png)

**Comment by lyndsysimon** [comment]
I'm fairly sure I know what's happening here.

Whenever a new repo is created on GitHub, it's uninitialized - there are no branches. The OSF assumes that there is at least one branch (usually `master`), and doesn't handle the case where one doesn't exist. Fixing this defect will fix this problem - I suggest showing a placeholder (like "---") and return a list of zero files. If a file is uploaded and no branch exists, then create a branch through the API and upload to that.

Another way to fix this specific issue might be to create a branch immediately after creating the repo. That leaves the addition defective case though where a repo is created on GitHub through the web interface, is left uninitialized, and is then connected to and OSF project.

**Comment by PatrickEGorman** [comment]
I'd be willing to take a look at this

**Comment by samanehsan** [comment]
@lyndsysimon, would creating a branch when a user tries to upload to an uninitialized repo go into waterbutler?

**Comment by samanehsan** [comment]
I have a fix for this issue, but it does not address a similar issue where a user tries to upload a file to an empty repository created through github. Since it's not a common case, perhaps we can create a separate issue for it and mark it as either deferred or low-priority? @lbanner @GaryKriebel

**Comment by GaryKriebel** [comment]
I am good with that path, @samanehsan

**Comment by bdyetton** [comment]
@I have a fix for the upload part of this issue in my hotfix for waterbutler (PR#55), and the branch not displaying issue in my fix for the osf issue #3122 (PR#3378)
