### ISSUE TITLE
[Production] Project with 500 error when loading files grid

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2980]
## Steps
1. Go to the project https://osf.io/5xk9m/ (may need to ask @caileyfitz to be added)
2. See that the files grid never loads
3. Open the console and see the 500 error

## Expected
I would expect the project's overview page to load in it's entirety with no errors. (I am a contributor)
I would also expect that I would see the project overview page and all components that I have permissions to see.

## Actual
The project overview page gives a 500 error.
The settings page has only 3 add-ons configured: S3, box and Google Drive (no errors)

Did some debugging with @lyndsysimon and it seems that there is a call to check for permissions for the components.  For a component that I do not have permissions to see, dataverse is configured, and apparently the 500 error is because I do not have permissions for the dataverse enabled component.

![screenshot 2015-06-05 08 48 43](https://cloud.githubusercontent.com/assets/9381062/8006217/bb7c6638-0b5f-11e5-9280-42987b7273c4.png)
![screenshot 2015-06-05 08 48 55](https://cloud.githubusercontent.com/assets/9381062/8006218/c24f5b6e-0b5f-11e5-9e76-904c07924c2c.png)

{"code": 500, "referrer": null, "message_short": "Unable to resolve", "message_long": "OSF was unable to resolve your request. If this issue persists, please report it to <a href=\"mailto:support@osf.io\">support@osf.io</a>."}

**Comment by caileyfitz** [comment]
Having a similar issue... getting a 500 when trying to load the files tab on a project for which one of the components has Dataverse enabled, but I *do* have access to see that component, unlike @nicipfeiffer. On the user settings page, I see this error:
![screen shot 2015-06-08 at 9 48 29 am](https://cloud.githubusercontent.com/assets/5975444/8036159/05212d94-0dc4-11e5-8b39-3c2459b8b87c.png)
But **no** option to delete my access token. 

On the overview page for the component where Dataverse is enabled, I get these two errors in the console:
![screen shot 2015-06-08 at 9 52 45 am](https://cloud.githubusercontent.com/assets/5975444/8036187/3a3a5c9e-0dc4-11e5-810e-52e8fbdd3d0c.png)
and I see this on the project settings page:
![screen shot 2015-06-08 at 9 53 00 am](https://cloud.githubusercontent.com/assets/5975444/8036192/44e4d20a-0dc4-11e5-9da5-e63c2700e569.png)
Again, no option to deauthorize Dataverse here. 

@saradbowman has a user reporting the same issue.

**Comment by chrisseto** [comment]
This should be fixed now, if dataverse does encounters an issue it will no longer stop the entire file grid from loading.

**Comment by lbanner** [comment]
Can we confirm and close?

**Comment by nanchen47** [comment]
According to @chrisseto, this should be fixed. If this comes up again, reopen this.

**Comment by nicipfeiffer** [comment]
@nanchen47 Let's reopen this issue as I have see this today and @sloria is looking into it too.

**Comment by chrisseto** [comment]
@nicipfeiffer Does this still involve dataverse?

**Comment by nicipfeiffer** [comment]
@chrisseto Yes, the projects that have dataverse are currently giving 500 errors and not loading the files tree.

**Comment by chrisseto** [comment]
This should be fixed now, one of dataverse's servers was being problematic.

**Comment by lbanner** [comment]
@nicipfeiffer can you confirm fix here? Is this same issue we are presently dealing with? Thanks -

**Comment by chrisseto** [comment]
Original issue(s) were fixed. Dealing with a new one now but same symptoms.
