### ISSUE TITLE
[Production & Staging] Scrolling long file grids reverts to page scrolling at arbitrary scroll points

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2982]
## Steps
1. Go to a project that you have lots of components/files/folder on
2. Go to the files tab
3. Scroll inside the files grid at different speeds
4. Notice when you scroll faster

## Expected
I would expect the scroll to keep up and not stop, and definitely not arbitrarily stop and scroll the entire page when scrolling inside the file grid.

## Actual
When scrolling faster down, the grid reverts to a page scroll and moves the entire page down instead of scrolling down in the grid.

@caneruguz and I discussed this and he saw what I am talking about.

**Comment by caneruguz** [comment]
@chrisseto I remember you said you had some suggestions for this. Any leads I can follow?

**Comment by chrisseto** [comment]
@sloria found a much better solution that I had.
Take a look here: https://jsfiddle.net/sloria/6pskpL3g/1/

**Comment by GaryKriebel** [comment]
Closed
