### ISSUE TITLE
[Production] PDFs not rendering

### ISSUE THREAD

**Issue by csoderberg** [CenterForOpenScience/osf.io#2999]
What I did: Went to this project (https://osf.io/cek6t/) to upload slides

Expected behavior: Clicking on uploaded PDF content should lead to the PDF rendering. 

What actually happened: 

![screenshot 2015-06-08 10 09 54](https://cloud.githubusercontent.com/assets/7332030/8036651/421eb524-0dc7-11e5-9c1b-0492a495c090.png)

This happened in both firefox 38.0.5 and Safari 7.1.6, but not in chrome.

**Comment by lbanner** [comment]
@csoderberg Is this error occurring for this file only?

**Comment by brianjgeiger** [comment]
Definitely happens for all PDFs stored in OSF Storage (and not, say, Github and S3, which work fine). Images and Text in OSF Storage render fine.

**Comment by csoderberg** [comment]
Nope, that was just an example. It's occurring on pretty much every PDF on
the OSF I try.

On Mon, Jun 8, 2015 at 2:19 PM, LarryB <notifications@github.com> wrote:

> @csoderberg <https://github.com/csoderberg> Is this error occurring for
> this file only?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/issues/2999#issuecomment-110096599>
> .
>



-- 
Courtney Soderberg, Ph.D
Statistical and Methodological Consultant
Center for Open Science

**Comment by lbanner** [comment]
Ping @sloria @nicipfeiffer -- This is a problem needing resolved ASAP, please. TY

**Comment by nicipfeiffer** [comment]
@lbanner I am not seeing this.  All pdfs are rending fine for me,  including the examples.

**Comment by brianjgeiger** [comment]
I'm still getting it. Safari. You're not testing in Chrome, right?

![screen shot 2015-06-08 at 3 12 18 pm](https://cloud.githubusercontent.com/assets/6599111/8042976/dd4dbb7a-0df0-11e5-8918-3bd36fe61f15.png)

**Comment by csoderberg** [comment]
I'm also still getting it in Safari and Firefox

On Mon, Jun 8, 2015 at 3:13 PM, Brian J. Geiger <notifications@github.com>
wrote:

> I'm still getting it. Safari. You're not testing in Chrome, right?
>
> [image: screen shot 2015-06-08 at 3 12 18 pm]
> <https://cloud.githubusercontent.com/assets/6599111/8042976/dd4dbb7a-0df0-11e5-8918-3bd36fe61f15.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/issues/2999#issuecomment-110110601>
> .
>



-- 
Courtney Soderberg, Ph.D
Statistical and Methodological Consultant
Center for Open Science

**Comment by nicipfeiffer** [comment]
@csoderberg I do see it now!

**Comment by nicipfeiffer** [comment]
Just thought I would also note that pdfs are rending OK in IE.

**Comment by nicipfeiffer** [comment]
Also, worth noting:
![screenshot 2015-06-08 15 31 12](https://cloud.githubusercontent.com/assets/9381062/8043349/7c144e52-0df3-11e5-980d-3d2e6305d510.png)
This is from Chrome, even though the pdf renders there is this error in the console.

**Comment by geeksnglitter** [comment]
Has this been fixed? PDFs rendering fine on my local.

**Comment by brianjgeiger** [comment]
It's not fixed on Production.

**Comment by csoderberg** [comment]
Nope. Still not working on Safari or Firefox on production.

**Comment by lbanner** [comment]
No PR / fix yet, can you take this @geeksnglitter ?

**Comment by geeksnglitter** [comment]
I believe Steve said @icereval was working on it?

**Comment by lbanner** [comment]
OK @geeksnglitter ..... @icereval What do you need to assist in knocking this one out? Thanks.

**Comment by GaryKriebel** [comment]
Jeff's presentation was recently tweeted and posted on Facebook and is having the render problem on Firefox.
https://osf.io/3sxgr/?utm_content=buffer18385&utm_medium=social&utm_source=facebook.com&utm_campaign=buffer

**Comment by lbanner** [comment]
No good [It's good in Chrome] ..... :red_circle: Priority up on this one -- Who can help?

**Comment by sloria** [comment]
Fixed by @icereval

**Comment by GaryKriebel** [comment]
Jeff's presentation is now correctly rendering on Firefox as well.

Thanks @icereval
