### ISSUE TITLE
[staging & production] Able to edit previous versions of a file when clicking away then back to most recent version (versions table)

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3011]
# Steps
1. Go to a project on which you have admin or read/write access on production
2. Go to the files tab
3. Click on a text file to view it in the detail page
4. If the file does not have previous versions, make edits so that the file has at least four versions
5. Click to view an older file version and confirm that there is no edit tab
6. Click on the most recent version of the file in the revisions table and confirm that there is an edit tab
7. Take note of the current URL
8. Toggle the edit tab to edit the file (make sure the versions table is also still open)
9. Make a few changes to the file and press save
10. Take note of the file view and the versions table updates
11. Repeat steps 9 and 10 a couple more times

# Expected
I expect that clicking to view the most recent version of the file in the versions table would yield a URL that is simply osf.io followed by the file guid. I also expect that only the most recent version of a file can be edited and that editing the most recent version of a file would automatically update the view after save.

# Actual
After step 6, upon pressing the most recent version of the file in the revisions table, the URL does not simply have a guid following osf.io. Instead, the guid is followed by ?version=8 (or whatever version of the file is most recent). The edit tab *is* available, which makes sense here since version 8 is the most recent version. After editing the file and pressing save, however, a new version of the file is created (version table shows a version 9) BUT the view does not update and the edit tab remains on the page. From there, we can edit to create versions 10, 11, 12, etc. This means that version other than the most recent version of the file can be updated. 

# Suggestion
I think the smartest thing to do here is to simply have the URL  read osf.io/guid   (ie: the URL that is displayed upon visiting the file from the files grid) when a user clicks on the revisions table to view the most recent version of a file. Then the view would update upon pressing save and previous file versions would not be editable.

**Comment by lbanner** [comment]
Looks like a bug in .TXT editor @chrisseto ? Thanks.

**Comment by samanehsan** [comment]
Fixed in #3247
