### ISSUE TITLE
[Production & Staging] Files tab filter does not filter upon typing in search bar

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3013]
## Steps
1. Log in to osf.io
1. Navigate to a project that has many add-ons enabled and a lot of files
2. Go to the files tab 
3. In the toolbar, click on the 'Search' button
4. Type a common letter to initiate filtering
5. Look at the files grid

## Expected
I expect to see the files filtered according to what I entered in the search bar. Sometimes scrolling in the files grid after typing results in filtering, but this is inconsistent.

## Actual
No filtering occurs upon typing. 

## Screenshots

![screen shot 2015-06-08 at 4 51 52 pm](https://cloud.githubusercontent.com/assets/7093086/8045051/bed5f1d6-0dfe-11e5-9913-6b24ab913a0a.png)

![screen shot 2015-06-08 at 4 53 00 pm](https://cloud.githubusercontent.com/assets/7093086/8045074/dfeeaa3e-0dfe-11e5-88b2-7fd3d3f52c7a.png)

**Comment by lbanner** [comment]
@NatashaRichter Is this consistent behavior? Or solely related to a project with many add-ons? And do we think this relates to the inability to filter files in window ##2779?

**Comment by NatashaRichter** [comment]
Yes, this is consistent behavior and regardless of number of add-ons and files. Having more files when testing makes it easier to see how filtering does not occur. I'm not sure if it relates to #2779, because even when I have my files out in the open (not in a folder), no filtering occurs (see screenshot below).


![screenshot 2015-06-10 09 58 15](https://cloud.githubusercontent.com/assets/7093086/8084188/b672a5f2-0f57-11e5-850b-569a072fce6b.png)

**Comment by Johnetordoff** [comment]
This error seems to only occur when there are nested components.

**Comment by Johnetordoff** [comment]
@samanehsan can we close this issue? Its been fixed by an another update.

**Comment by samanehsan** [comment]
Sure, what was the PR that fixed this issue?

**Comment by Johnetordoff** [comment]
I'm not sure, there have been many changes, but you can no longer replicate the issue.

**Comment by NatashaRichter** [comment]
No longer happening! Closing.
