### ISSUE TITLE
"download as zip" is shown as an option when there are no files to download

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3018]
<h4>Steps</h4>
1. Visit a project or component with no files
2. Visit the files page and click on a storage add-on (like OSF Storage)

<h4>Current Behavior</h4>
1. The "Download as zip" button appears in the top right as an option
![screen shot 2015-06-09 at 10 28 17 am](https://cloud.githubusercontent.com/assets/4965832/8060317/9637120c-0e92-11e5-8cf9-d97a94f279a6.png)

<h4>Expected Behavior</h4>
1. As there are no files to download, the download button should not appear.

**Comment by jinluyuan** [comment]
"Download as zip" appears even if there's only one file in the add-on. When I click it, the file downloaded is NOT a zip, but just the original file. Could we also get rid of the "Download as zip" option if there's only one file in the add-on?

**Comment by sloria** [comment]
I think we still want to allow downloading as zip even if there's only one file, but the button should actually download the file as a zip. That seems to be a separate bug. @jinluyuan Could you please open  a separate issue?

**Comment by jinluyuan** [comment]
Right, meant to say that as the other option. I'll open this as a separate issue. @sloria
