### ISSUE TITLE
[Production & Staging] Error message does not persist when Unable to configure figshare in Project settings

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3021]
Bug found on the 0.38 testing board:

## Steps
1. Go to a project you have admin on
2. Go to the settings tab
3. Enable the figshare add-on
4. Click to import access token

## Expected
I would expect to import the token and see the folder picker appear to complete the configuration.  However, I seem to have an expired token.

## Actual
In this case, the error message to the user in the project settings page should remain.
The folder picker never appears.
There is an error that flashes briefly, but does not persist.
The console reports a 400 error.

![screenshot_2015-06-03_10 09 08](https://cloud.githubusercontent.com/assets/9381062/8061795/94f85466-0e9a-11e5-9ddf-22b40a8cdb31.png)
![screenshot_2015-06-03_10 08 30](https://cloud.githubusercontent.com/assets/9381062/8061802/976dcb90-0e9a-11e5-81d8-4fbcc37afa81.png)
![screenshot_2015-06-03_10 03 33](https://cloud.githubusercontent.com/assets/9381062/8061805/995708ea-0e9a-11e5-8750-44f2408ba7c8.png)

Comments from @chrisseto : This only happens when you first authenticate figshare.
The message stays after you refresh.
I'm attempting to test on prod but figshare wont expire my tokens.

**Comment by lbanner** [comment]
If driven by communication issue w/Figshare ... well ... @chrisseto let us know sense on possibility of resolving. TY
