### ISSUE TITLE
[Production & Staging] White space below edit pane

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3022]
Bug reported on the 0.38 testing board:

## Steps
1. Go to a project with a .txt file in osf storage
2. Go to the files tab
3. Click on the .txt file to render it
4. In the upper right, click on the edit toggle to see the edit pane appear
5. Look for the save and revert buttons

## Expected
I would expect that the save and revert buttons would be easily visible for the user.

## Actual
With my browser at 100% I cannot see the save and revert buttons.  Even very short text files have lots of white space added to the end which makes these buttons not seen unless the user scrolls down the page to see them.
![screenshot_2015-06-03_08 55 56](https://cloud.githubusercontent.com/assets/9381062/8061937/2101a9a8-0e9b-11e5-8f63-3f76609f4509.png)
![screenshot_2015-06-03_08 56 06](https://cloud.githubusercontent.com/assets/9381062/8061941/263fc738-0e9b-11e5-8053-a6ebbf54525f.png)

**Comment by chennan47** [comment]
I believe @caneruguz set it to be a fixed height by purpose.

**Comment by lbanner** [comment]
Thoughts @caneruguz ?

**Comment by nanchen47** [comment]
Will be considered in file pages enhancement.
