### ISSUE TITLE
[Production] Cannot upload files with '%' in the name to OSF storage

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3025]
## Steps
1. Go to a project you have admin access to on osf.io
2. Find a file with a '%' in the filename or change a file so that the filename has % in it.
3. Click on the file tab
4. Locate the OSF storage folder, click on it to highlight it
5. In the toolbar, click the upload button
6. Upload the file with % in the name

## Expected
I would expect the file to upload successfully

## Actual
Error
Could not upload file. The file may be invalid or the file folder has been deleted.
There is also a 400 error in the console
![screenshot 2015-06-09 13 24 22](https://cloud.githubusercontent.com/assets/9381062/8064759/dc2b11f6-0eaa-11e5-86d7-cd199774f533.png)

Error also occurs when uploading files with % in the filename to:
Dropbox

Unable to test Dataverse and box at the time of this issue report due to another issue.

**Comment by lbanner** [comment]
Assume we should allow the character "%" in file names? Any reason it might not be allowed?

**Comment by brianjgeiger** [comment]
It's an escape character, but I expect that the sequences in the filenames are the escaped version. One way or another it should handle it, however, unless there's something secret I don't know. If we absolutely cannot handle %s for some reason, it would still need to be handled better than by using a generic error.

**Comment by Johnetordoff** [comment]
I tried to replicate this issue and couldn't. Seems to work fine.

![screen shot 2015-06-11 at 10 49 14 am](https://cloud.githubusercontent.com/assets/9688518/8110008/e09f1402-1027-11e5-9df0-66e1730805e0.png)

**Comment by nicipfeiffer** [comment]
@Johnetordoff what file type?  I consistently get the error with .txt and .jpg.

**Comment by chennan47** [comment]
@Johnetordoff Just tried out on staging and production, this problem still exists. It just doesn't occur when you try it locally.

**Comment by samanehsan** [comment]
@chennan47 any idea why that's the case? What would be the best way to debug if it doesn't happen locally?

**Comment by chennan47** [comment]
@samanehsan I don't have a clue yet. Maybe @chrisseto @icereval will have some thoughts?

**Comment by chrisseto** [comment]
Fixed as of https://github.com/CenterForOpenScience/waterbutler/releases/tag/0.6.1

**Comment by lbanner** [comment]
Merged?

**Comment by nanchen47** [comment]
The code has been deployed and I tested on production that this is no longer a problem.
