### ISSUE TITLE
Rebrand sign in page to say OSF not COS

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3026]
This comes from the community repo: https://github.com/CenterForOpenScience/community/issues/199

<h4>Steps</h4>
1. Log out of the OSF
2. Visit a private project on the OSF so that you can get to the login page

<h4>Current Behavior</h4>
1. The user is brought to a page that says COS at the top, even though they are logging into the OSF:
![screen shot 2015-06-09 at 2 12 17 pm](https://cloud.githubusercontent.com/assets/4965832/8065783/b19b4c6a-0eb1-11e5-902b-8bebd3728e7c.png)

<h4>Expected Behavior</h4>
1. The user should be brought to a page that says OSF, so that we maintain consistent branding and don't confuse the user:
![osf_logo](https://cloud.githubusercontent.com/assets/4965832/8065787/b712ee64-0eb1-11e5-9937-ed34746ec543.png)

I have the image file, using the correct font, for whoever addresses this issue.

**Comment by haoyuchen1992** [comment]
Is this what we want? Honestly, COS log is more beautiful!

![screen shot 2015-06-09 at 11 00 39 pm](https://cloud.githubusercontent.com/assets/5420789/8074088/8a01a40c-0efb-11e5-8a9b-41dac5b53ab1.png)

**Comment by lbanner** [comment]
@AndrewSallans @jlcohoon -- We'll want a review on this ^^^ -- Thanks.

**Comment by brianjgeiger** [comment]
It's worth mentioning that this will be a login for all COS services, not just the OSF, and eventually for other services that want to use our login. It's not wrong to call it an OSF login, but think about the generic presentation for all of the cases, not just the one we're using now.

**Comment by AndrewSallans** [comment]
Could we not use this?  This is the logo/text that is presented when using the small-sized OSF window via responsive design.

![screen shot 2015-06-10 at 9 31 53 am](https://cloud.githubusercontent.com/assets/2151933/8083594/bb582e60-0f53-11e5-9126-eb587849b0ff.png)

**Comment by lbanner** [comment]
If we can reverse it, i.e. blue text on white with O logo -- that could be a sound approach.

**Comment by AndrewSallans** [comment]
That'd be fine.  I just think that structure and pairing is what we should go with.

**Comment by chrisseto** [comment]
:+1: to @brianjgeiger 
Think of this like google's auth servers. when you log into gmail, youtube, etc. the auth server still says google.

**Comment by lyndsysimon** [comment]
Another :+1: for leaving it as "COS". Perhaps a clarification to something like "COS Tools" or "The COS Suite" - but not yet. That can and should wait until we get it more consolidated in terms of branding.
