### ISSUE TITLE
[Production] Component activity bars inconsistent in appearance

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3032]
## Steps

1. Log in to osf.io
2. Navigate to a project for which you are admin and have some components; add a couple more if need-be
3. Look at the activity bars for the components

## Expected

I expect that activity (number of contributions) will be displayed in green along the blue activity bar. I also expect there to be consistency in activity bar appearance.

## Actual

The activity bars look different when only one contribution has been made. In this case, the activity bars shows up as a thin green line (without the rest of the bar present). If the rest of the blue activity bar showed up, with the green demarcating number of contributions, then it would be clear. Notice more inconsistency in activity bar appearance in the third screenshot below.

## Screenshots

![screenshot 2015-06-10 09 53 27](https://cloud.githubusercontent.com/assets/7093086/8084462/25971f66-0f59-11e5-8048-13d5c953bb54.png)

![screenshot 2015-06-10 09 49 19](https://cloud.githubusercontent.com/assets/7093086/8084467/32dd7a30-0f59-11e5-96c7-3d8a051a9f17.png)

![screenshot 2015-06-10 09 49 47](https://cloud.githubusercontent.com/assets/7093086/8085126/81b49226-0f5c-11e5-8c6b-70be6f4300d9.png)

**Comment by GaryKriebel** [comment]
I believe the contribution bars are scaled to be proportional among all of your components.  A quick glance above shows that the "Donut" component has had orders of magnitude more contributions that "Taho" has.

If all of your components have the same number of contributions, the lines will be of equal length.
![screen shot 2015-06-10 at 11 02 49 am](https://cloud.githubusercontent.com/assets/9437946/8085880/783fe692-0f60-11e5-9d50-296b50c0f849.png)

**Comment by NatashaRichter** [comment]
Thanks @GaryKriebel Yes, they are scaled to be proportional. I just think a design change would make activity clearer (or maybe just look better) in screenshot #2.

**Comment by jlcohoon** [comment]
I think the UI changes take care of this? There is a light grey outline to indicate that when the bar isn't full, it's a portion of something.
![screen shot 2015-07-14 at 12 18 59 pm](https://cloud.githubusercontent.com/assets/4965832/8678427/8971d588-2a22-11e5-87fa-d29d31effbf4.png)

**Comment by NatashaRichter** [comment]
UI changes fixed this problem, so closing now!
