### ISSUE TITLE
[Production] Icons in Configure Notifications widget are incorrect

### ISSUE THREAD

**Issue by leb2dg** [CenterForOpenScience/osf.io#3033]
# Steps

Log in to osf.io
Navigate to a project
Go to the settings page for that project and scroll down to the Configure Notification widget
Look at icons next to project/components

# Expected

I expect that the icons displayed would be the same as the ones on the project organizer and the file grid on the project dashboard page.

# Actual

The icons are all folders
.
# Screenshots
![screen shot 2015-06-10 at 11 13 49 am](https://cloud.githubusercontent.com/assets/7131985/8086127/ce4982cc-0f61-11e5-9319-a55916f238f8.png)

**Comment by leb2dg** [comment]
I'll fix this.

**Comment by sloria** [comment]
Fix is merged; will be released in 0.41.0
