### ISSUE TITLE
Make filtering work for complex fields

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3040]
Currently, filtering only works for built-in field types. We have a custom properties field that we are going to want to be able to filter on, so the user would be able to, say, access /api/v2/nodes/?filter[properties.registration]=true to get all of the available registrations. Ideally, we want to do this in a generic way for future custom field types. If things become tricky, we can do this in a less reusable way for now and explore the best way to handle it in the future.

Moved from https://github.com/brianjgeiger/osf.io/issues/19

**Comment by samchrisinger** [comment]
@brianjgeiger @billyhunt 

I'm a bit confused about the FilterMixin#is_filterable_field method. What exactly does it do? Looking at this impl.: 
```python
def is_filterable_field(self, key):
        try:
            return key.strip() in self.serializer_class.filterable_fields
        except AttributeError:
            return key.strip() in self.serializer_class._declared_fields
```
The code seems to say: A field is filterable if it's in the special set of filtered fields, or if its a field of the serializer at all. To me this seems like an implicit condition of the implementation-- if the field is not known by the serializer it is not filterable.

The point of this is: As we discuss implementing complex field filtering it becomes less and less trivial to make assertions about whether or not a field is filterable. For example, if I add 'user.name' to the filtered fields set, how do I know 'name' is a filterable field for a 'user'? Maybe if I had access to the relevant serializer, but this really doesn't fit with my perception of what this feature is meant to accomplish. 

I offer the alternative that the serializers are the authoritative implicit representation of the filterable fields for a given serializer. Using an error tolerant method like here: https://github.com/samchrisinger/osf.io/commit/33f7cb460a888e554d671d29f7fdafa03d94c4ff to fetch values means if an invalid filter is provided then a None is used in it's stead.

**Comment by brianjgeiger** [comment]
The point of filterable_field is to limit the fields that can be used for serialization. If you haven't set a `fliterable_fields` variable, then it defaults to `declared fields`. This way we don't do expensive searches on unindexed fields.

**Comment by brianjgeiger** [comment]
(At least, that's what it was intended to do. Reading through, it looks more like what you interpreted, so it may have been changed, or it may have been implemented wrong, or I may be misinterpreting as well.)
