### ISSUE TITLE
Add UI for adding OAuth applications

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3041]
Via @sloria:
```
Developer users will need a way to registering OAuth applications on their account.

@icereval points out that this can be done in parallel with his work on CAS.
```

From https://github.com/brianjgeiger/osf.io/issues/30

**Comment by brianjgeiger** [comment]
The first people who are going to need this will be @himanshuo and @jamiehand so please let them know when you might have something testable.

**Comment by abought** [comment]
Will do; the document I sent them should contain instructions for an interim solution. They'll still need realCAS to use that though.

But remember that access tokens are very... tricky... to acquire for humans; they were never designed for API clients. Any thoughts on #3097?

**Comment by brianjgeiger** [comment]
My thoughts on #3097 haven't changed, but I'll post details there.

**Comment by brianjgeiger** [comment]
That being said, @jamiehand could make a quick web server in Tornado that used her API client if need be. It's a little excessive, but Tornado makes for quick prototypes, and it would allow a test of the oauth workflow. I'm not sure about @himanshuo's best path, though. Tokens or similar would be keen.

**Comment by himanshuo** [comment]
I could do the tornado server route as well.

**Comment by brianjgeiger** [comment]
Or, as Andy suggests, you could do a Flask server if you're into that kind of thing.

**Comment by abought** [comment]
Adding a comment to this issue:

I wrote a sample Flask application to demonstrate the flow here. It has very minimal error handling; improvements welcomed. 
https://github.com/abought/osf_oauth2_demo

It could probably be modified to just print token details for API client users. 

To cross-reference: this issue covers partial requirements towards #3323.
