### ISSUE TITLE
Create registrations with API

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3046]
This one is a little different from other create views. We want to enforce a confirmation capability with registrations to ensure that people understand the consequences of creating a registration. So I think it should work something like:

POST /v2/nodes/{pk}/registrations/
{ "public": true }

will result in an error that will give a confirmation message intending to be displayed and a token (and likely a self link) that will indicate that the user has acknowledged the confirmation message in some manner. Then the API client will:

POST /v2/nodes/{pk}/registrations/{token}
{ "public": true }

which will create the registration. The API client will not be able to do a single post in order to create a registration. This pattern will be reused. It should maintain RESTfulness because the route to post is different from the original route. We should require the public information (and the rest of the registration information including the type, embargo date, etc) in the original post as well as the follow-up so that we can give the appropriate message to the user (for example, that public registrations can't be made private).

Note: This will change somewhat with registration functionality in the new epic.

From https://github.com/brianjgeiger/osf.io/issues/76

**Comment by brianjgeiger** [comment]
*I'm still working on this, but I wanted to save it so it doesn't go away*

Okay, based on our meeting, we'll want to do the following. There's a lot we'll have to change, so I'm mostly going to describe routes and how they should work now, and then we'll go through and take out a bunch of the stuff that we have to do to make up for not having the model there when Sam has the model ready.

 - [ ] POST for `/nodes/{node_id}/registrations/` - To start with, it will just create a new with fake data (or you can pull the title from the current node and add "DRAFT REGISTRATION" to the end or something). For the moment, just make a pointer to the new node and attach it to the existing node.
 - [ ] POST for `/registrations/` that takes a node_id as the source. Treat it the same as above.
 - [ ] GET for `/registrations/` that gets nodes where is_registration is True.
 - [ ] Make `/registrations/{registration_id}/` a copy of what `/nodes/{node_id}` is.

**Comment by brianjgeiger** [comment]
What we'll do is start by making the /registrations/ views and serializers subclasses of /nodes/ views and serializers, then we'll restrict functionality. The first restriction will be for registration listing so that it only shows nodes that are registrations. Once we're sure that works the way we want it to (and it should), further work should be easy.

**Comment by pattisdr** [comment]
Can I just checkout a new branch for this? I know I have a pull request in on the old one but everything is changing.

**Comment by brianjgeiger** [comment]
Yeah, that makes sense. You can close your old PR as well.

**Comment by pattisdr** [comment]
I have GET `/registrations/` inheriting from `NodeList` to get all registrations where is_registration is True.  Tests are returning all non-deleted, public registrations and user-contributed registrations.

**Comment by brianjgeiger** [comment]
Hooray!

**Comment by brianjgeiger** [comment]
Okay, so let's see if we can get something that is usable before we change it all for Sam. Can you try to disable all of the write routes for registrations, so that it's completely read-only to start with?

**Comment by brianjgeiger** [comment]
Or, if that's how it is but you only have /registrations/, then add on all the detail view GET routes.

**Comment by pattisdr** [comment]
<ul>
<li> Regarding GET for /registrations/ that gets nodes where is_registration is True: </li> </ul>
Is the route GET `/v2/registrations/` instead of GET `/v2/nodes/registrations` ?

**Comment by brianjgeiger** [comment]
Yes. /v2/registrations/{registration_id} etc.

**Comment by brianjgeiger** [comment]
Differences worth thinking about between nodes and registrations: registrations could have a related link to their source project. Also, registrations/registration_id/registrations won't make much sense, but it might make sense to have a list of other registrations from the same source project. I'm not sure the best thing to call that off the top of my head.

**Comment by pattisdr** [comment]
- [X] GET `/registrations`.  Return all registrations where is_registration = True
- [X] POST `/nodes/{node_id}/registrations` . Clones node, appends DRAFT_REGISTRATION to title, adds pointer from node to registration
- [ ] GET `/registrations/{registration_id}/`
- [ ] PUT `/registrations/{registration_id}/`
- [ ] PATCH `/registrations/{registration_id}/`

**Comment by pattisdr** [comment]
What is the difference between POST for /nodes/{node_id}/registrations/ and POST for /registrations/? Is POST /registrations/ the final draft?

**Comment by brianjgeiger** [comment]
Thinking about it, I don't think that POST for /registrations/ makes sense. Don't do that. To start with, let's just do the GET routes, so, so the detail route and whatever related routes make sense (pointers and children, for example)

**Comment by pattisdr** [comment]
Here are the current routes:
![screen shot 2015-06-19 at 1 14 31 pm](https://cloud.githubusercontent.com/assets/9755598/8258762/9ea7ca3a-1685-11e5-935c-c55d723d85bc.png)

**Comment by pattisdr** [comment]
Why do you want GET `registrations/{registration_id}/registrations`? I thought the user made a registration of the node (now a registration draft).  The user continues to work on draft until finished and registration becomes frozen.  Are people registering registrations?

**Comment by brianjgeiger** [comment]
We don't. But we will want a link for the source node, and we might want a link for other registrations that belong to the same source node. https://github.com/CenterForOpenScience/osf.io/issues/3046#issuecomment-113522702

**Comment by pattisdr** [comment]
Should GET /v2/registrations/{registration_id} return details for both registration drafts and registrations?

**Comment by brianjgeiger** [comment]
Yes

**Comment by brianjgeiger** [comment]
Any of the GETs should work for both, the POST/DELETE/PUT/PATCH should only work for drafts. And, of course, they shouldn't work at all for nodes that are neither registrations nor registration drafts.

**Comment by pattisdr** [comment]
GET /v2/nodes/{node_id}/ will return any node, registration or otherwise.  Should this be changed to only return nodes where is_registration is False?

**Comment by brianjgeiger** [comment]
No, let's keep /nodes/ generic for now.

**Comment by pattisdr** [comment]
Should a user be able to POST a final registration without making a registration draft first?

**Comment by brianjgeiger** [comment]
No, I don't think that fits with our current workflow.

**Comment by pattisdr** [comment]
Should a user be able to create a registration draft of a registration?  I don't know why you would want to, but should this be allowed/not allowed?

**Comment by brianjgeiger** [comment]
I don't *think* so. Let's limit it for now, as it would be easier to add in later if we thought it was worth doing.
