### ISSUE TITLE
DRY waterbutler_url_for

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3049]
There's some sort of circular dependency between api.base.utils and `website.util, so Steve suggests, "Would it be possible to define the function in this module but then import it in website.util, so it can be imported from there as well?"

We also cannot import the Auth model into that class, which is inconvenient.

From brianjgeiger#80

**Comment by abought** [comment]
Initial diagnosis (while working on a fix):

`website.util` imports `rubeus`

`rubeus` imports `framework.auth.core` (...well, indirectly)

The `User` class (in `auth.core`) depends on `from api.base.utils import absolute_reverse`


The key is this line:
https://github.com/CenterForOpenScience/osf.io/blob/develop/website/util/__init__.py#L15

And in particular the associated comment... apparently, convenience has a price. :scream_cat: 
`# Keep me: Makes rubeus importable from website.util`

Options include:
1. Not insisting that rubeus be importable from website.util
2. Moving the offending circular import inside the sole function that uses it. (seems to work when testing with API view that would fire this import... but I'd want to check further for side effects)

https://github.com/CenterForOpenScience/osf.io/blob/develop/framework/auth/core.py#L416
```
    @property
    def absolute_api_v2_url(self):
        from api.base.utils import absolute_reverse
        return absolute_reverse('users:user-detail', kwargs={'pk': self.pk})
```

**Comment by brianjgeiger** [comment]
Rubeus in all will be removed eventually, but not soon enough. Moving the import into the function seems like a good way to go. @sloria ?

**Comment by sloria** [comment]
Yeah, In the absence of a better, quick solution, just do the import in the function.

**Comment by abought** [comment]
With option 2, all unit tests pass. Sample implementation in #3101. I'll go ahead and start building on that.

Option 1 (removing rubeus entirely) is probably the ideal long-term, but it would involve checking a lot more files that reference rubeus.

**Comment by brianjgeiger** [comment]
Circular imports are fixed, so now we just need to DRY the function.

**Comment by brianjgeiger** [comment]
I expect this is going to be handled with upcoming changes to the files endpoint.
