### ISSUE TITLE
Make /users/me/ route

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3053]
User detail information is accessed by going to /users/{user_id}/. If a user is logged in, they should be able to access that information (and anything under) by going to users/me/.

Even better if there are other places in the API that can use a user ID (for example, nodes/{node_id}/contributors/{user_id}/, which I don't think is a thing yet, but will be one day), the same thing should work there.

from brianjgeiger#93

**Comment by brianjgeiger** [comment]
Take a look at https://github.com/CenterForOpenScience/osf.io/pull/3051 for how to do this. It is using /collections/dashboard as a shorthand for the dashboard node. I believe most of that happens in the views.

**Comment by barbour-em** [comment]
For the sake of reference being available here instead of the PR, all this would involve is creating a url for `/users/me` then in the `get_user` method in the view adding something like:

```python
key = self.kwargs[self.node_lookup_url_kwarg]
        if key == 'me':
            return find_profile(self.request.user)
```

assuming `find_profile` is a helper function returning the same page `/users/{user_id}/` would

**Comment by brianjgeiger** [comment]
Would you even need the URL, or would /users/{user_id} take care of that?

**Comment by reinaH** [comment]
i will take this issue.

**Comment by lbanner** [comment]
Alright @reinaH -- give it a shot!

**Comment by barbour-em** [comment]
@brianjgeiger You may be right, I haven't tested it without the url but it's likely that the view method would handle this no problem. I guess @reinaH will find out!

**Comment by reinaH** [comment]
testing phase:

method names:
me_test_anonymous_gets_400
me_test_authorized_gets_200
me_test_get_projects_logged_in
me_test_get_projects_not_logged_in

should work:
	users/{user_id}
	users/me
	users/me/nodes
	users/{user_id}/nodes

should not work:
	users/{user_id}/me
	users/{user_id}/nodes/me
	nodes/me
	nodes/{user_id}
