### ISSUE TITLE
Make helper functions to facilitate cross-domain AJAX requests

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3056]
To avoid redundant code, update and modify osfhelpers.js with helper functions for cross-domain requests. These will mainly be used within the OSF, eg for devs to query the API (or other services) when running locally.

Split from brianjgeiger#90 so that separate tasks get separate issues.

From brianjgeiger#97

**Comment by abought** [comment]
Currently being implemented as part of #3082, as `ajaxJSON` in `osfHelpers.js`. PR could be split out if needed sooner.
