### ISSUE TITLE
Nodes created by the API are not showing in Project Organizer smart folder

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3057]
Steps
-------
1. Create some nodes via POSTing to /v2/nodes/
2. Go to project organizer/All My Projects smart folder

Expected
-------------
Nodes created will show up in the smart folder

Actual
--------
Not all nodes are showing up. This is especially true for test folders created by runscope. I don't know if there are other mitigating factors.

From brianjgeiger#100

**Comment by pattisdr** [comment]
One thing that is interesting is every time you create a node through Runscope, it affects which nodes are visible in the project organize. They're not always the same.  A node may be visible at one instance, then you create another node through Runscope, and now the first isn't visible. (I've also observed this with creating pointers).

In the example below, I created 26 nodes consecutively through Runscope, labeled 2A, 2B...2Z.  Each time a node was created, it changed which nodes were visible in the project organizer.  You could always access the node through the proper URL, they just weren't in proj organizer/couldn't be found through search.  So when I created node and gave it a title of '2O', projects 2A, 2I, 2M, and 2O were in the project organizer.  Then when I created node titled '2P', projects 2D, 2G, 2J, 2K, 2L, 2N, 2P were visible.

![screen shot 2015-06-12 at 4 57 04 pm](https://cloud.githubusercontent.com/assets/9755598/8139761/30e2d582-1124-11e5-8648-2c25f1ed3790.png)

**Comment by brianjgeiger** [comment]
That's just weird.

**Comment by pattisdr** [comment]
To start, I ran an identical test to above, creating 26 consecutive nodes and checking the dashboard each time to see what nodes were visible.  This time, everything persisted.

![screen shot 2015-07-27 at 9 47 34 am](https://cloud.githubusercontent.com/assets/9755598/8907511/6f7f23a2-3444-11e5-97e6-4c88b5ba4abe.png)

**Comment by brianjgeiger** [comment]
Well, fantastic! Okay, let's consider this closed then.
