### ISSUE TITLE
Pointer delete occasional failure

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3058]
My external tests on Runscope have the pointer delete failing non-deterministically. When they do fail, they fail with a 500. We need to figure out what's happening there, fix it, and handle failures properly.

From brianjgeiger#101

**Comment by pattisdr** [comment]
<h3> Current Runscope test: </h3>

1) Creates first node :white_check_mark: <b> Passing </b>
2) Creates second node :white_check_mark: <b> Passing </b>
3) Creates pointer from first node to second node :white_check_mark: <b> Passing </b>
4) Deletes pointer :x: <b> Inconsistent 500 error </b>

I'm getting the same thing.

**Comment by brianjgeiger** [comment]
I occasionally cannot create the pointer either, but it's much more likely to fail on the deleting the pointer. That being said, focus for now on trying to find out why deleting doesn't work sometimes. I will be very curious to see how this turns out.

**Comment by pattisdr** [comment]
Yes, I was having problems creating a pointer when the test was only 3) create pointer and 4) delete pointer.   If the pointer didn't delete, I'd manually delete it and try again, and create still wouldn't work.  You're right that there seems to be a problem there too. 

But to focus on just the delete portion, I'm creating fresh nodes every time which keeps the create pointer from failing. It's very strange.

**Comment by brianjgeiger** [comment]
Yeah. It really shouldn't be weird. It could be a timing issue. It could be something to do with some kind of caching (which we shouldn't be doing, but maybe). It could be something to do with our storage. ¯\_(ツ)_/¯

**Comment by brianjgeiger** [comment]
In case it's useful, here is the last 10 test results from Runscope. You can see if there are any patterns based on that.

![screen shot 2015-06-12 at 3 25 13 pm](https://cloud.githubusercontent.com/assets/6599111/8138278/6104daba-1117-11e5-8c37-a4c1de3dc100.png)
![screen shot 2015-06-12 at 3 25 04 pm](https://cloud.githubusercontent.com/assets/6599111/8138284/611a5fd4-1117-11e5-8e23-d726b07bd66d.png)
![screen shot 2015-06-12 at 3 24 54 pm](https://cloud.githubusercontent.com/assets/6599111/8138280/61145f9e-1117-11e5-807e-f124d41f184b.png)
![screen shot 2015-06-12 at 3 24 42 pm](https://cloud.githubusercontent.com/assets/6599111/8138282/61165a06-1117-11e5-8eae-2d98620a9240.png)
![screen shot 2015-06-12 at 3 24 31 pm](https://cloud.githubusercontent.com/assets/6599111/8138281/61163a62-1117-11e5-93bb-2dbfc73d8198.png)
![screen shot 2015-06-12 at 3 24 18 pm](https://cloud.githubusercontent.com/assets/6599111/8138283/6116a178-1117-11e5-9301-6d384d417347.png)
![screen shot 2015-06-12 at 3 24 08 pm](https://cloud.githubusercontent.com/assets/6599111/8138279/61130fe0-1117-11e5-9308-8854aa3d9506.png)
![screen shot 2015-06-12 at 3 23 56 pm](https://cloud.githubusercontent.com/assets/6599111/8138287/61293b6c-1117-11e5-9b30-213464a90d21.png)
![screen shot 2015-06-12 at 3 23 46 pm](https://cloud.githubusercontent.com/assets/6599111/8138285/61272ef8-1117-11e5-88fa-fa2585065b74.png)
![screen shot 2015-06-12 at 3 23 37 pm](https://cloud.githubusercontent.com/assets/6599111/8138286/61277c96-1117-11e5-9f37-ba1c3a0922ed.png)

**Comment by abought** [comment]
A 500 error does suggest something unexpected happening on our end. To aid in debugging, are there any relevant server logs associated with these events? If so, where would I go to access them?

**Comment by abought** [comment]
With quick hack script designed to mirror what the runscope tests are doing, did ~250 total runs on a single local development environment; 0 failures encountered.

https://gist.github.com/abought/0814e30017494ce5542c

Next will explore the effect of running multiple local server workers to see if this is something in the caching layer (eg modularodm).

**Comment by brianjgeiger** [comment]
Thank you.

**Comment by brianjgeiger** [comment]
So, if what's happening is what I think is happening, https://github.com/brianjgeiger/osf.io/issues/21#issuecomment-101862513 is relevant. Essentially, we need to associate the user's information with the toku proxy. This should cause requests from the same user to be in the same toku context. Right now, a new context is being made for each request.

**Comment by abought** [comment]
Ran same mass-action script again locally, this time using 8 workers. Still no obvious failures, even when the pointer creation/deletion were scattered against different PIDs

```
cd osf.io/api/base
gunicorn --pythonpath=/Users/andyboughton/code/cos/osf.io -w 8 --access-logfile access.log --error-logfile errorog --log-level debug --access-logformat '"%(h)s %(l)s %(p)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'   wsgi:application
```

```
"127.0.0.1 - <29989> - [17/Jun/2015:13:46:02 -0500] "POST /v2/nodes/ HTTP/1.1" 201 868 "-" "python-requests/2.5.3 CPython/2.7.9 Darwin/14.3.0"
"127.0.0.1 - <29988> - [17/Jun/2015:13:46:03 -0500] "PATCH /v2/nodes/euft9/ HTTP/1.1" 200 859 "-" "python-requests/2.5.3 CPython/2.7.9 Darwin/14.3.0"
"127.0.0.1 - <29991> - [17/Jun/2015:13:46:03 -0500] "PUT /v2/nodes/euft9/ HTTP/1.1" 200 874 "-" "python-requests/2.5.3 CPython/2.7.9 Darwin/14.3.0"
"127.0.0.1 - <29986> - [17/Jun/2015:13:46:04 -0500] "POST /v2/nodes/euft9/pointers/ HTTP/1.1" 201 218 "-" "python-requests/2.5.3 CPython/2.7.9 Darwin/14.3.0"
"127.0.0.1 - <29989> - [17/Jun/2015:13:46:04 -0500] "DELETE /v2/nodes/euft9/pointers/4cu8f/ HTTP/1.1" 204 - "-" "python-requests/2.5.3 CPython/2.7.9 Darwin/14.3.0"
```

**Comment by brianjgeiger** [comment]
Harrumph. Such a pain when we can't reproduce locally.

**Comment by abought** [comment]
I can reproduce it locally (at random trial #s) using the following commands:

```bash
cd osf.io/api/base
uwsgi --http :8000  --pythonpath=/Users/andyboughton/code/cos/osf.io -p 8  --logto=uwsgirun.log --wsgi-file wsgi.py
```

This works in dev mode- no need to toggle production settings or change anything other than how the app is run.

In 199 trials of the runscope-like test (see previous script), it failed ~29.5% of the time.

As a side note, I've confirmed that uwsgi is what we use in production and also works well locally, so this will be what tests are done with going forward. Although gunicorn does have a `--worker-class` option, setting it to gevent (instead of the default class "sync") caused the apiserver to lock up. 

As we expected, the cause is an uncaught ValueError raised by rm_pointer. I'll now work on tracing the root cause in more detail.


```
Traceback:
File "/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)
File "/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)
File "/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  452.             response = self.handle_exception(exc)
File "/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rest_framework/views.py" in dispatch
  449.             response = handler(request, *args, **kwargs)
File "/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rest_framework/generics.py" in delete
  273.         return self.destroy(request, *args, **kwargs)
File "/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rest_framework/mixins.py" in destroy
  86.         self.perform_destroy(instance)
File "/Users/andyboughton/code/cos/osf.io/api/nodes/views.py" in perform_destroy
  231.         node.rm_pointer(pointer, auth)
File "/Users/andyboughton/code/cos/osf.io/website/project/model.py" in rm_pointer
  1251.             raise ValueError
```

**Comment by brianjgeiger** [comment]
Yay! And yes, that matches the rate I'm seeing via Runscope fairly well.

**Comment by abought** [comment]
In 600 runs: 159 failures (26.5%). 

The database caching hypothesis seems very plausible, based on two points from processing logs:

1. All of these failures occurred when the PID associated with pointer deletion had been used for at least one other node create/update task
2. None of these failures occurred when the same PID was used for pointer creation and deletion

This fits the theory that the deletion task is:
- Reusing stale node data, and,
- Fetching new pointer data from the database (eg when no pointer data was available yet)

Will coordinate with @lyndsysimon to investigate how caching is handled in DRF.
https://github.com/brianjgeiger/osf.io/issues/21#issuecomment-101862513

**Comment by brianjgeiger** [comment]
Ideally, we want to find out what the key is at https://github.com/CenterForOpenScience/modular-odm/blob/develop/modularodm/ext/concurrency.py#L39 at the same time as we find out the thread id (or worker id or whatever we might have access to at that point). What I was expecting from code inspection is that the key would change on each request, but on a single threaded system, the dummy req… oh, right.

So, each thread will, when it instantiates, create this dummy_request object. https://github.com/CenterForOpenScience/modular-odm/blob/develop/modularodm/ext/odmflask.py#L15 For whatever reason, I was thinking that happened on each request, but I apparently wasn't looking closely enough. This dummy request is being used as the proxy decorator to key the caching. So, since the dummy_request is only instantiated once, it means the key being used is the same per thread, which would do exactly what we are seeing.

Sooo, if we can pass another get_key function into the with_proxies decorator, and then key that to the django request object or something equally useful specific to the individual transaction, then we can take advantage of the caching. Alternately, we could instantiate a new DummyKey each time it's called, which would negate any caching at all, though I don't know details about how that may affect memory usage and the like. There may be some other alternatives. 

I do not have a good sense yet for exactly how we pass in a new key. If we could work it into the transaction system for Toku, then we could at least keep transactions cached, which might split the difference on performance and should be roughly equivalent to doing it by request. Probably in the middleware is the place to set the get_key function, or creating an equivalent to odmflask.py for django.

**Comment by abought** [comment]
Submitted #3303, a fix based on pushing a flask dummy request context in Django middleware. I've also updated https://gist.github.com/abought/0814e30017494ce5542c to include the latest versions of mass-request-generation code (used with uwsgi command described above) that I used for testing this bug locally.
