### ISSUE TITLE
Pointer creation failure

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3059]
Via @geeksnglitter: 

When you try to create a new pointer, if you pass an incorrect node_id, the api will give a 500 response instead of the expected 404, 405.

These errors only occur when you have access to the first pk you enter. If you do not have access, it knows to send a 403.
1.So, when you put in a real pk, but a fake node - it send a 500 only if you had access to the first pk.
2.If you try to connect a node to itself - 500.
3.When you do not have access to the second node - 500. ~Somewhat inconsistent
4.When nodes are already connected -500 ~Somewhat inconsistent.

from brianjgeiger#103

**Comment by pattisdr** [comment]
The two errors I am seeing:
1) Creating a fake pointer while logged in/contributor to first node: 500 error
2) Creating a pointer that already exists: 500 error

**Comment by brianjgeiger** [comment]
Both of those look pretty easy to fix, hopefully.

For the inconsistent ones reported above, it might be worth trying multiple requests in the same test to see if that changes anything. Another possibility is to use a webtest rather than a view test to see if that changes anything.

**Comment by pattisdr** [comment]
<b> Error verification </b>
These errors only occur when you have access to the first pk you enter. If you do not have access, it knows to send a 403. :white_check_mark: <b> Also getting 403 </b>
1.So, when you put in a real pk, but a fake node - it send a 500 only if you had access to the first pk. :white_check_mark: <b> Error verified. Also getting 500 </b>
2.If you try to connect a node to itself - 500. :x: <b> Not able to reproduce. Getting 201 as long as the node hasn't been connected before and you have access. </b>
3.When you do not have access to the second node - 500. ~Somewhat inconsistent :x: <b> Not able to reproduce. If you have access to first and not to second, you get a 201.  If the first node is fake, linking to a node have access to/don't have access to, you get a 404 </b>
4.When nodes are already connected -500 ~Somewhat inconsistent. :white_check_mark: Error verified.  Getting 500 <i>consistently</i>.
