### ISSUE TITLE
File uploads and new Waterbutler Features

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3060]
Via @alexschiller:

1. File upload via url currently requires adding file name to the middle of the url string (see image)
2. File self link lists access is via POST it is supposed to be PUT (see here: https://staging2.osf.io/api/v2/nodes/4s8q3/files/

![screen shot 2015-06-05 at 4 09 53 pm](https://cloud.githubusercontent.com/assets/1322421/8014318/ba44350a-0b9d-11e5-962f-349fb12a81f2.png)

Example code for upload currently (note the bolded matched text for emphasis)
f = open('/Users/alexanderschiller/Desktop/<b>stupid.txt</b>', 'rb')
r = requests.put("https://files-api-staging2.osf.io/file?path=%2F<b>stupid.txt</b>&nid=4s8q3&provider=osfstorage&cookie=5571f2f6404f77020c09dcbf.ve8ATKGiyIYI9dc3kaLA89cV8wM", f.read())

---
Could be fixed by having file added at the end or writing a wrapper to make it more accessible.

Current plan is `/nodes/{}/downloads/` url for handling getting and putting files. Also, we need to add in waterbutler moves/copies while we're here.

From brianjgeiger#106

**Comment by brianjgeiger** [comment]
Planning to write a wrapper.

**Comment by brianjgeiger** [comment]
Or maybe using HEAD verb for metadata and GET for downloads. Possibly both.

**Comment by brianjgeiger** [comment]
So, how this should work is:
 - the download link and the metadata link should both be the same and should be api/v2/nodes/{node-id}/files/{query parameters}
 - The links should be wrapped so that they are:
```json
"links" : {
    "metadata": {
        "href": "https://api.osf.io/api/v2/nodes/{node_id}/files/?{query_parameters}",
        "meta":{
            "method": "HEAD"
        }
    },
    "download":{
        "href": "https://api.osf.io/api/v2/nodes/{node_id}/files/?{query_parameters}",
        "meta":{
            "method": "GET"
        }
    },
    "create":{
        "href": "https://api.osf.io/api/v2/nodes/{node_id}/files/?{query_parameters}",
        "meta":{
            "method": "PUT"
        }
    }
```

And so on. Valid query parameters should show in the swagger documentation. All links should redirect to the Waterbutler url. Folders won't have a download. "Metadata" for folders might be replaced with a "list" item instead. Maybe.

Now that copy and move are in, it would be keen to get those in as well, but if that seems out of scope, add a new issue for it before closing this issue.

**Comment by brianjgeiger** [comment]
Oh, and very specifically for this issue, when creating a new file via the api, the path file parameter will be separate from the filename parameter, and we will construct the waterbutler url from the combination of those parameters.

**Comment by abought** [comment]
As discussed with @brianjgeiger , the `metadata` field on `NodeFileSerializer` should not be serialized as a dictionary. All fields meant to be presented to the user should be explicitly and individually called out, such as is done with [user social fields](https://github.com/CenterForOpenScience/osf.io/blob/develop/api/users/serializers.py#L24).

This is a safeguard in case sensitive information is ever added to the `metadata` field in the future. Explicit (rather than automatic) serialization is a security consideration, consistent with the design philosophy of DRF and [Django Forms](https://docs.djangoproject.com/en/1.8/topics/forms/modelforms/#selecting-the-fields-to-use).

>It is strongly recommended that you explicitly set all fields that should be edited in the form using the fields attribute. Failure to do so can easily lead to security problems when a form unexpectedly allows a user to set certain fields, especially when new fields are added to a model. Depending on how the form is rendered, the problem may not even be visible on the web page.

**Comment by mr-c** [comment]
What is the correct way to upload a file today?

At https://staging-api.osf.io/v2/nodes/wyfvt/files/ I see the the 'upload' field under 'links', but that URL doesn't have documentation.

**Comment by brianjgeiger** [comment]
Well, we will have to move that documentation over. If you have a self link on a file, click on that, or go to https://staging-api.osf.io/v2/files/asdfg/ but we will make that more findable.

.:Brian

**Comment by mr-c** [comment]
Thanks; I've been able to create a file if I first create a folder via the website. How does one create the first file in a project via the API?

**Comment by brianjgeiger** [comment]
Should work the same way; go to the /nodes/files link and it will list your providers. Each provider (osfstorage will definitely be there, and more if you add them through the OSF gui) will have links such as  new folder and upload. Just use the upload link. The documentation has been updated on staging to be more explicit, so hopefully that will help.
