### ISSUE TITLE
Keep from having to override swagger_settings.info.description

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3061]
Django settings have to be in local.py in order to by at all dynamic. At the moment, this means that we have to have the entirety of the SWAGGER_SETTINGS in local.py, which causes us to have to copy the big description text into the local.py, which is terrible.

Instead, we should try setting swagger_settings to the configured version, then override with subsequent lines the additional behaviors. Ultimately, the goal is to ensure that the API_PATH is dynamic while allowing as much as possible of the rest to be in defaults.py.

From brianjgeiger#108

**Comment by jamiehand** [comment]
It looks like SWAGGER_SETTINGS is in defaults.py and not in local.py, which seems to contradict this. Am I wrong?

![screen shot 2015-06-16 at 1 40 13 pm](https://cloud.githubusercontent.com/assets/10687411/8189904/4eaab8ee-142d-11e5-8ede-91952cc12ff4.png)
![screen shot 2015-06-16 at 1 40 26 pm](https://cloud.githubusercontent.com/assets/10687411/8189907/511c568c-142d-11e5-9424-d2c3ea94021f.png)

**Comment by brianjgeiger** [comment]
I think that, currently, the only local.py that has that is on staging. I thought maybe it was put into local-dist.py, but no. So you are not wrong.

The problem is that because swagger_settings.api_path is defined in defaults.py, it's never picking up the API_PREFIX from local.py. So the thing to figure out is how to get the API_PATH into the swagger settings without having to modify everything else in swagger_settings.

To test, change the API_PATH and API_BASE in your local.py and still make the swagger docs work, especially with the `try it out` buttons.

**Comment by brianjgeiger** [comment]
Putting this on hold until we finalize how we are hosting the API.

**Comment by brianjgeiger** [comment]
This should no longer be necessary.
