### ISSUE TITLE
Update all tests to use URLs relative to API_BASE

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3062]
All API unit tests currently point to URLs of the form `v2/<endpoint>`, which is a form of hard-coding and could break if the URL prefix in Django ever changes.

These URLs should be modified to add the prefix based on `osf.io/api/base/settings/defaults.py: API_BASE`. 

This would affect anything that lives under `tests/api_tests`.

From brianjgeiger#109

**Comment by jamiehand** [comment]
Just wanted to note for future/others' reference that I used API_PREFIX (which is based on API_BASE) instead of API_BASE itself.

**Comment by brianjgeiger** [comment]
There was a lot of back and forth on this, and I think we've finally found the root of the back and forth. There'll be another PR on this soon that will fix this and #3061
