### ISSUE TITLE
Uploading a file bigger than 128mb does not let the user "X" out of the stuck file

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3064]
### Steps
1. Go to [osf.io](http://www.osf.io) on Safari, Chrome, or Firefox.
2. Go to a project in which you have admin access.
3. In the Files viewer, click on OSF Storage.
4. Click the "Upload" button.
5. Upload a file that is bigger than 128 mb.
6. Try to press the "X" button next to the stalled loading bar.

### Expected behavior
I expected that I would be able to "X" out of the un-uploadable file.

### Actual behavior
Pressing the "X" button does nothing. In order to get the file out of the file viewer, I have to refresh the page.

![screen shot 2015-06-10 at 4 34 34 pm](https://cloud.githubusercontent.com/assets/8591162/8093624/27b82894-0f90-11e5-9bb3-9fbc9fb9f6ed.png)

**Comment by nanchen47** [comment]
This is a duplicate issue as https://github.com/CenterForOpenScience/osf.io/issues/2822. Close this one. And continue discussion there.
