### ISSUE TITLE
Implement includes

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3072]
It would be useful under some circumstances to be able to do requests that include information that is currently only available with extra requests. The query parameter is documented at <http://jsonapi.org/format/#fetching-includes>. We wouldn't want to have this on for everything by default. The most likely first use case will be for collections/ to make implementing the Project Organizer interface a little easier. It's also possible we'll want to limit the clients that can use that capability, depending.

**Comment by brianjgeiger** [comment]
Hi, @PatrickEGorman. Have you had a chance to work on this?

**Comment by PatrickEGorman** [comment]
My internet is still a wip so I haven't been online too much.  I also have been wondering if anybody has been tracking my pr's as I completed my node contributors one a couple weeks ago and it has yet to finish review.  Looks like it has some merge conflicts but if you'd be interested in considering it still, I'd like to finish that one first.

**Comment by brianjgeiger** [comment]
That just needs merge conflicts aside from review, yes? Go ahead and bring it up to date, but you'll have to do it again soon so feel free to wait on that. 

.:Brian J. Geiger

**Comment by PatrickEGorman** [comment]
Okay.  I have limited internet access so ping me when it's ready, if you don't mind
