### ISSUE TITLE
[Production and Staging] [Chrome] [Safari] [Firefox] "How to use the file Browser" close button cut off

### ISSUE THREAD

**Issue by WillBanner** [CenterForOpenScience/osf.io#3076]
# Steps:

1. Go to osf.io and log in.
2. Go to your dashboard.
3. Go to a project on which you are an administrator.
4. Under the "files" header in the upper right corner click on the "i" information button.

# Expected result:
The "How to use file browser" information page would pop-up overtop of the file browser and would be spaced to fit within the file browser.

# Actual Result:
The "How to use file browser" page is displayed, however it does not fit within the file browser ( it is too long from top to bottom) which results in the "close" button for the information page being partially cut off when the page is displayed (you can still scroll down on this information page to get to the close button, but the information is little enough that, if the close button were moved up slightly, this wouldn't be necessary).

![screenshot 2015-06-11 13 53 49](https://cloud.githubusercontent.com/assets/12799635/8114264/5ba02196-1041-11e5-8cc3-48bb4f20b52b.png)

**Comment by chennan47** [comment]
You can always scroll down to get the close button, if the language
description is longer. It serves its functional purpose to make the user
read through. Well, even you don't want to, there is a cross sign on right
top. @lbanner <https://github.com/lbanner> @GaryKriebel
<https://github.com/GaryKriebel>thoughts?

**Comment by lbanner** [comment]
The functionality is not ideal from a user perspective. Would this be a @caneruguz fix @chennan47 ? Difficult?

**Comment by chennan47** [comment]
@lbanner This is not a hard task. But since the person fix this should check all other similar modal under different browser under different scale to ensure it doesn't happen elsewhere in the osf. It can be an intern task.

**Comment by lbanner** [comment]
:ok_hand:

**Comment by rohan-bajaj** [comment]
Can I grab this issue?

**Comment by lbanner** [comment]
OK -- you got it.

**Comment by caneruguz** [comment]
Actually @lbanner and @nanchen47 this seems to me like a treebeard issue so if we try to fix it with OSF it will be a hack. I recommend we open an issue in treebeard for this. Whichever intern wants to deal with it can fix it there. I'm happy to help with onboarding.

**Comment by lbanner** [comment]
@rohan-bajaj You catch that above ^^ Let me know if you still want to tackle.

**Comment by rohan-bajaj** [comment]
Yeah I still want to work on this issue. I'll start looking into treebeard

**Comment by caneruguz** [comment]
Check this: https://github.com/caneruguz/treebeard/wiki/Modal

Some of it migt be a bit outdated but that's the code for the modal, you will need to regulate height and scroll body content.

**Comment by rohan-bajaj** [comment]
Thanks!

**Comment by lbanner** [comment]
@rohan-bajaj  ... @WillBanner is noting this as no longer an issue -- You OK if I close? Status on any work here? Thanks -

**Comment by rohan-bajaj** [comment]
I haven't been able to fix it. Was it fixed on staging? The problem seems to be the text it self. If you decrease the box size so that it fits perfectly in a shrunk browser the text would need to be shrunk to so that might just lead to a complaint about font size... It isn't a problem if the screen is full.

**Comment by lbanner** [comment]
OK -- since we are cleaning up some things in GH issues, I am going to close this for now. Thanks!
