### ISSUE TITLE
"Download as zip" does not actually produce a zip file if only one storage file is present

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3077]
### Steps
1. Go to [osf.io](http://www.osf.io).
2. Go to a project that has only one file in OSF storage (or another storage add-on).
3. Click the "OSF Storage" line.
4. Click the "Download as zip" button from the menu bar.
5. Check your downloads folder.

### Expected behavior
I expected that the "Download as zip" button would produce a .zip of the contents of OSF Storage (in this case, one file).

### Actual behavior
The downloaded file is simply the single file, not a .zip.

**Comment by chennan47** [comment]
I like the current behavior. Even if you unzip the zip file, it's only one file in it. @lbanner @GaryKriebel thoughts?

**Comment by jinluyuan** [comment]
It would help with organization to download as a zip. For example, a user might want to save the contents of multiple storage add-ons onto his computer. If the user downloads as zip from OSF Storage, Box, and Dropbox all at once, he would expect that there would be three different folders in his Downloads, and this would help him remember which files were in which storage add-ons. However, in this case, the single file is folderless, and the user would have to make his own folder to house the file, for clarity's sake.
If we don't change this to an actual zip folder of the single file, then we should take away/rename the "Download as zip" button for the case of a single file in a storage add-on. Otherwise, it's misleading.

**Comment by GaryKriebel** [comment]
My only thought for the proposed change is if it is a rather large file, but on the face of it, I'm not opposed to keeping it the way it is.

**Comment by lbanner** [comment]
@jinluyuan You make a good point, but I think general use case for 'download as zip' will be w/multiple files. So for consistency sake re: options for files. I'm in favor of keeping functionality as is. Based on @GaryKriebel and @nanchen47 discussion, I'll close for now, but let's be aware if user feedback comes in. Thanks.
