### ISSUE TITLE
[production] User not receiving confirmation email

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#3088]
Reported on help desk:
1. User creates new account.
2. User does not receive email to confirm account.
3. User checks spam folder, does not find email. 
4. User adds OSF email to  "trusted senders" list and asks to resend confirmation email.
5. User does not receive confirmation email.

@sloria checks sendgrid; no bounces associated with that email and reports there is a bug. I am sure he will add more detail on this when he's no longer tied up with this release; just logging this so it's not forgotten.

**Comment by samanehsan** [comment]
@sloria @saradbowman was this resolved?

**Comment by samanehsan** [comment]
Updates from @sloria: 
> the help desk issue was resolved; i ended up having to manually generate a confirmation link, and Sara sent it to the user
>however, it's still unclear why that user didn't receive the email
>it seems to have to do with the user's educational mailserver
>because another email from the same domain had the same issue

**Comment by erinmayhood** [comment]
@saradbowman can this issue be closed? In the past I've dealt with these issues by suggesting the user contact their IT department about making our emails "safe" since the holdup is most likely on their end.

**Comment by lbanner** [comment]
+ 1 on @erinmayhood approach. I'm actually going to close this as it appears the user in this case was taken care of, and this 'bug' is not consistent ... unless @saradbowman :scream: 's at me.

**Comment by saradbowman** [comment]
@erinmayhood great suggestion, thanks!
