### ISSUE TITLE
Mendeley Subfolders appear but do not display content

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#3096]
Steps
-------
1. Login to Mendeley
2. Create a folder, "Folder A" and put documents in it
3. Create a subfolder, "subfolder" inside "folder A", and put documents in "subfolder"
4. Login to the OSF, connect "Folder A" to a project
5. Go to the project overview page
6. See Mendeley widget, with Folder A's contents and the subfolder "subfolder" with a + to expand it
7. Click "+" to expand
![screen shot 2015-06-12 at 10 26 26 am](https://cloud.githubusercontent.com/assets/7749914/8132159/b3131a80-10ed-11e5-89cf-64c0344b7c00.png)

Expected
------------
Subfolder would expand to show contents of the subfolder

Actual
--------
"+" turns to "-" but contents of subfolder are not displayed 
![screen shot 2015-06-12 at 10 26 33 am](https://cloud.githubusercontent.com/assets/7749914/8132168/c1f45b22-10ed-11e5-96b5-db77401268e5.png)

**Comment by GaryKriebel** [comment]
@lyndsysimon, @caneruguz - is this a front or back end issue?

**Comment by GaryKriebel** [comment]
Fixed with https://github.com/CenterForOpenScience/osf.io/pull/3103
