### ISSUE TITLE
Easier token process for non-web applications

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3097]
Current and immediate-term plans for authentication for the API require a web browser to authenticate a token. Many of our expected uses will not involve a web browser. We need a streamlined way to get people into authenticated APIs that give them appropriate project permissions. This task will require a short proposal and will involve UI as well as possible CAS interaction.

**Comment by abought** [comment]
As mentioned on flowdock, one option (which would eliminate the need for a separate API key model or cruft) would be to issue personal access tokens a la Github:

https://github.com/settings/tokens

These tokens (which presumably would be of a special non-expiring variety) would be bearer instruments not tied to a specific client secret. Basically, they'd be non-expiring access tokens.

One other nice feature is that they track the date of last use (which helps to determine whether the tokens are being used for malicious means). I'm not sure if our current CAS tokens have a date field, but it seems like a useful idea on paper.

**Comment by brianjgeiger** [comment]
Someone needs to come up with a proposal, try it out, and implement it. I don't know the right answer, though I can pass along some suggestions. Personal access tokens seem like the right sort of thing. I don't know details like CAS integration or whatever either.

**Comment by abought** [comment]
I have some notes in phase 3 of my proposal. Touching that up is next priority after #3082.

**Comment by brianjgeiger** [comment]
Sounds great.
