### ISSUE TITLE
[Production & Staging] IE: folder '+/-' expand/collapse icons Spin

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3104]
## Steps
1. Login to osf.io on the Internet Explorer browser
2. Go to the Project Dashboard 
3. Click on the '+/-' to expand/collapse collections (folders) 
4. Notice the behavior
5. Click on a project to go to the project overview page
6. In the files widget, Click on the '+/-' to expand/collapse folders
7. Notice the behavior

## Expected
The '+/-' preceding collections and folders would not spin, especially when the content is fully loaded

## Actual
On the Project Organizer:
![project organizer](https://cloud.githubusercontent.com/assets/9381062/8134337/5f79f056-10fc-11e5-916f-ee91934d666c.gif)

On the Project Overview:
![project overview](https://cloud.githubusercontent.com/assets/9381062/8134338/637020a4-10fc-11e5-982f-dfa9fa5dceeb.gif)

On the Files Tab:
![files tab](https://cloud.githubusercontent.com/assets/9381062/8134343/67b11d62-10fc-11e5-8c47-8404321c6d5e.gif)

**Comment by lbanner** [comment]
Interesting! .... @caneruguz ?

**Comment by caneruguz** [comment]
Is this only for IE? 

That button should never be rotating but be replaced with a refresh icon that does rotate. 

if this is happenign for all browsers then someone broke this switch to refresh icon, otherwise IE might not be catching it, but this was tested in IE previously and was workin.

**Comment by lbanner** [comment]
Think'n just IE ... @nicipfeiffer ?

**Comment by nicipfeiffer** [comment]
@lbanner @caneruguz Yes, I checked the other browsers and it is only happening for IE.
