### ISSUE TITLE
GitHub: Cannot upload files to empty github repo

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#3122]
Related to #2976 

Steps
--------
1. Create a new repository on github 
2. Configure the github addon for a project and select the new repository
3. Go to the project's files tab 
4. Click on the github addon folder and look at the branch select menu
4. Upload a file to the linked github repo

Expected
-------------
The branch select menu is set to "master" and I can upload files to the repository. 

Actual
---------
The select menu is empty:  
![screen shot 2015-06-12 at 4 51 58 pm](https://cloud.githubusercontent.com/assets/6414394/8139759/3018dffc-1124-11e5-90e7-04c11b67296d.png)

When I try to upload a file, I get an error message:  
![screen shot 2015-06-12 at 4 55 01 pm](https://cloud.githubusercontent.com/assets/6414394/8139716/ddd77082-1123-11e5-8311-09de52e0c18d.png)

**Comment by bdyetton** [comment]
@GaryKriebel I will work on this

**Comment by lbanner** [comment]
Got it @bdyetton -- and we'll get you added to COS org so we can assign directly.

**Comment by chrisseto** [comment]
This should be fixed now thanks to @bdyetton

**Comment by sloria** [comment]
Yes, this fix will be in release 0.43.0

**Comment by chrisseto** [comment]
@sloria Uploading is already fixed on prod.
