### ISSUE TITLE
[Production] [Bug] "Create Project from Template" not copying structure

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#3124]
Steps
-------
1. Create a new project, using Project TIER: Protocol 2.0 DEMO (https://osf.io/he87a/) as the template

Expected
------------
The new project will have 2 components: "Original Data and Supporting Information" and "Processing and Analysis." "Original Data and Supporting information" will have 2 components nested in it: "Original Data" and "Supporting Information." "Supporting information" will have one nested component, "Supplements."  "Processing and analysis" will have 2 nested components: "Importable Data" and "Command files."

Actual
--------
The new project has no components.

**Comment by sloria** [comment]
@saradbowman On what browser are you seeing this issue?

**Comment by saradbowman** [comment]
It was chrome - but I just tested again, and I'm no longer experiencing the issue.

**Comment by lbanner** [comment]
I will close for now -- Thanks.

**Comment by wisherp** [comment]
I'm seeing this issue on production while doing regression testing. It could be that the template project listed above has been deleted. Would you mind testing it one more time @saradbowman ?

**Comment by saradbowman** [comment]
The template project listed above has been changed and it no longer has components - so creating a project using it as a template will produce just a project with no components.

**Comment by wisherp** [comment]
That explains the issue I am seeing. Thanks!
