### ISSUE TITLE
[osf] rendered CSV and text in edit window don't match

### ISSUE THREAD

**Issue by csoderberg** [CenterForOpenScience/osf.io#3126]
Steps:
* Go to a project and open a .csv file (https://osf.io/zvj9w/)
* Click on the 'edit' button

Expected Behavior:
You would expect that, when the editing window first appears, what is in the editing window should match the rendered .csv content

Actual behavior:
For some .csv files, though not all of them, the content in the editor and in the rendered image are not the same (see examples below).  If you download the current version you get what is in the editor window, rather than what is rendered.

![screenshot 2015-06-15 09 21 52](https://cloud.githubusercontent.com/assets/7332030/8160819/9f4aa59a-1340-11e5-9a57-8243cd2f0fa4.png)

Possibly related to #3015

**Comment by lbanner** [comment]
Did this one get resolved with @icereval 's recent fix on render of .CSV files?

**Comment by icereval** [comment]
@csoderberg showed me this today, I'll have a look as soon as I get a chance.

**Comment by icereval** [comment]
[MFR hotfix 0.2.9](https://github.com/CenterForOpenScience/modular-file-renderer/releases/tag/0.2.9) now correctly handles duplicate column names in csv/tsv files, also enabled basic column sorting in the grid.
