### ISSUE TITLE
[Production & Staging] Comments on discussion board can't be deleted and restored

### ISSUE THREAD

**Issue by haoyuchen1992** [CenterForOpenScience/osf.io#3127]
### Steps
1. go to the project page
2. click the discussion board on the up-right corner. 
![screen shot 2015-06-15 at 9 50 37 am](https://cloud.githubusercontent.com/assets/5420789/8161322/2eeccbe4-1344-11e5-8545-9640caa65f4f.png)
3. Add a comment and then delete it

### Expected
The comments disappear and don't left anything

### Actual
A restore option is still there. What's more, after you click restore, it doesn't bring the comment back but remain the restore option the same. So the result is that we can never totally clear a comment.

Here is the key process in gif image:
![commentsissue](https://cloud.githubusercontent.com/assets/5420789/8161413/bd816ef0-1344-11e5-95c0-f0aff871204a.gif)

**Comment by nanchen47** [comment]
This should be fixed by https://github.com/CenterForOpenScience/osf.io/pull/2534. Close for now.

**Comment by haoyuchen1992** [comment]
Oh, I don't notice that! Next time I should search the existing issues before I make one！ Thanks, Nan!
