### ISSUE TITLE
[Production] Buttons in "Delete" modal in dashboard & file viewer do not conform to OSF style

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3136]
### Steps
1. Go to [osf.io](http://www.osf.io).
2. Go to your dashboard.
3. Create a new collection.
4. Click the collection to highlight it. 
5. Click the "Delete" button in the menu bar.
6. View the modal that pops up.
7. Go to a project with files in any storage add-on.
8. Click one of the files to highlight it.
9. Click the "Delete" button in the menu bar.
10. View the modal that pops up.

### Expected behavior
I expected that the buttons in the "Delete" modal would follow the style of the rest of the [OSF style] (http://caneruguz.github.io/osf-style/#buttons). 

### Actual behavior
The "Cancel" and "Delete" buttons have the same background color, and furthermore, they are in all caps (which does not happen anywhere else in the OSF). The "Cancel" button should have black text against a gray background, and the "Delete" button should have white text against a red background.

![screen shot 2015-06-15 at 2 33 50 pm](https://cloud.githubusercontent.com/assets/8591162/8167343/a90ad232-136b-11e5-80d5-f8b75f255c4e.png)
![screen shot 2015-06-15 at 2 33 29 pm](https://cloud.githubusercontent.com/assets/8591162/8167344/abd2856e-136b-11e5-9523-d4b08d10221a.png)

**Comment by lbanner** [comment]
@caneruguz --- This potential handled with your UI updates to align with Style Guide? If not as yet, probably we add it in -- Yes? Thanks.

**Comment by caneruguz** [comment]
Yes we will cover this in our sweep of the style related bugs. Can you assign me just to make sure it's in my radar?

**Comment by jinluyuan** [comment]
Noticed that this also occurs in the information modal (clicking "i" button).
![screen shot 2015-07-09 at 9 54 16 am](https://cloud.githubusercontent.com/assets/8591162/8596985/930b695c-2620-11e5-946a-ba101c65fd16.png)

**Comment by caneruguz** [comment]
A fix for this issue is sent here: https://github.com/CenterForOpenScience/osf.io/pull/3733
