### ISSUE TITLE
[Production] empty folders/OSF storage appear like they can be expanded

### ISSUE THREAD

**Issue by csoderberg** [CenterForOpenScience/osf.io#3138]
Steps:
* Go to a project that has organizational components (https://osf.io/bfp8g/)

Expected behavior:
On the file tree, '+' next to things like folders and OSF storage should indicate that there is content in these sections that you cannot currently see, and if you click the plus these sections will expand to reveal hidden content. So, in the picture below, you would expect that the 'OSF Storage' under 'Project: Second Level Nested' should have content, as should the 'Empty Folder'

![screenshot 2015-06-15 15 02 27](https://cloud.githubusercontent.com/assets/7332030/8168574/b221cf6e-1371-11e5-8ad0-cbc84997b7b9.png)

Actual Behavior:
Folders and OSF storage have '+' next to them whether they have content in them or not. 
![screenshot 2015-06-15 15 02 43](https://cloud.githubusercontent.com/assets/7332030/8168584/d23787b2-1371-11e5-89db-f90ff56a6de8.png)

This makes it more difficult to efficiently skim through a project because you end up uselessly opening up sections that have no content.

**Comment by brianjgeiger** [comment]
Agreed in general. There are some technical reasons why this doesn't happen right now, mostly having to do with all of the information that is needed for that is located all over the internet. Essentially, the cause and the solution will be the same as for #2779 with the addition that items with the addition of a little front-end code that should be in there already but looks like it isn't.

**Comment by lbanner** [comment]
@brianjgeiger and @csoderberg : This is also referenced in #2536 ... We put that on 'Hold' as it was noted by BrianG that API V2 would overcome -- Assume this is true here as well? TY

**Comment by bdyetton** [comment]
@brianjgeiger Will API V2 overcome the problem? if not i will work on this issue.

**Comment by brianjgeiger** [comment]
Not directly. The FileTree mentioned in #2356 became not a requirement for the API, but that's the thing that's necessary. I do not have any insight on when it's intended to be implemented at this point. So without that, you would need to do the "procrastinating loading", which is like lazy loading except it loads everything currently visible without necessarily expanding them.

**Comment by nanchen47** [comment]
Same issue as https://github.com/CenterForOpenScience/osf.io/issues/2536. Continue tracking of this issue there.
