### ISSUE TITLE
Public components not appearing on profile page

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3141]
# Steps
1. Log into production
2. If you do not already have one, make a component of a private project public 
3. Go to your profile page by clicking on your name in the top-right corner

# Expected
The public component of the private project would appear under the **Public Components** heading on the profile page. 

# Actual
No components are displayed beneath the **Public Components** heading on the profile page, even if public components exist: 
![screen shot 2015-06-15 at 3 41 50 pm](https://cloud.githubusercontent.com/assets/5975444/8169236/48f696b4-1376-11e5-9858-b6e5596cb03f.png)

**Comment by lbanner** [comment]
I did replicate this --

**Comment by Johnetordoff** [comment]
For some reason it can only display public components when there are no public projects.

**Comment by GageGaskins** [comment]
Strange because the view returning the component works.

**Comment by sloria** [comment]
Fixed by @GageGaskins
