### ISSUE TITLE
[bug][production] Front-end URL validation not working as expected

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/osf.io#3149]
## Summary
The logic used to validate URLs on the front-end does not seem to fire correctly. If an invalid URL is entered, the server sends a response "400/ BAD REQUEST", but this result is not displayed to the user. The field is not updated.

## Steps to reproduce
1. Go to https://osf.io/settings/
2. Click the "Social" tab
3. In the "Personal Site" box, type: `http://notaurl`
4. Click "submit"
5. Check the console for error messages. Refresh the page to confirm the value in the box was not saved to the server.

### Expected result
The user should not be allowed to submit an invalid value. Furthermore, the existing Knockout "url" validator should display an error message underneath the "personal site" box to warn of the problem and guide towards a solution.

### Actual result
Even though URL validation is turned on for this field, no error message is displayed. The "submit" button can be clicked, but no result is saved. Looking in the error console (which is not normal behavior for a user) gives the following:

`PUT https://osf.io/api/v1/settings/social/ 400 (BAD REQUEST)`

## Browsers tested
Same behavior in Firefox, Chrome

## References
- osf.io/website/static/js/profile.js : The "url" validator *appears* to be registered to the "personal" field in `SocialViewModel`
- osf.io/website/static/js/koHelpers.js : definition of the custom "url" validator.

**Comment by lyndsysimon** [comment]
I disagree.

First of all, `http://notaurl` *is* a valid URL, per [RFC 3986](http://tools.ietf.org/html/rfc3986). It refers to the TLD (Top-Level Domain) `noraurl`, which of course isn't in existence - but it's still valid :)

Unless the proposal is to actually retrieve the URL, there's really no way to do this with any accuracy. I say leave it be ;)

**Comment by abought** [comment]
If it's a valid URL, than the server shouldn't throw a 400 error without telling the user. 

I'm ok with accepting the value, but not with using two inconsistent validators that result in data not being saved, and errors not being caught.

**Comment by lyndsysimon** [comment]
> I'm ok with accepting the value, but not with using two inconsistent validators that result in data not being saved, and errors not being caught.

Agreed. One validator to rule them all, and one validation to bind [to] them.

**Comment by abought** [comment]
> Agreed. One validator to rule them all, and one validation to bind [to] them.

In which case perhaps it would make more sense to classify this as a bug for tracking purposes? Calling `http://----` a valid URL is rather a stretch, but the submit button is allowing that to go to the server.

**Comment by billyhunt** [comment]
Not sure if its helpful, but I noticed that different urls are failing validation through different paths on the server.  For example, the url

http://<scan> 

gives a 400 error and  

&lt;/script&gt;&lt;script&gt;alert(“Now I am doing bad stuff”)&lt;/script&gt; 

gives a 500 error.

**Comment by abought** [comment]
Both of those error messages are server-side... this issue should relate to only what happens in the browser (before the input ever hits the server). I can help you walk through that if needed, but it's probably a separate scope from the one.
