### ISSUE TITLE
[Production][Staging]File Revision Table gets cutoff when resizing

### ISSUE THREAD

**Issue by Ghalko** [CenterForOpenScience/osf.io#3152]
## Steps
1. Open a file page where you can see the revisions table
2. Resize to a smaller screen

## Expected
The revisions table would resize appropriately.

## Actual
![screen shot 2015-06-11 at 11 19 42 am](https://cloud.githubusercontent.com/assets/5169088/8184875/e2e7b59e-140e-11e5-8b64-5f1ef5cb833a.png)
The table resizes for most wider widths, at 1100 or smaller the table starts going off the edge of the page while the revisions table header does not.

## Suggestions
Since I have been working in this area recently (osf.io/website/static/js/filepage/revisions.js) I have noticed that it uses an actual table instance that may not be as robust as treebeard or some other method. Switching up the way this table is built may fix this issue.

**Comment by haoyuchen1992** [comment]
I can work on this! Thanks :)

**Comment by lbanner** [comment]
You got it -- Thanks!
