### ISSUE TITLE
OSF storage logo off center

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3155]
<h4>Steps</h4>
1. Visit the files page or a project over view
2. Look at one of the rows that OSF storage is listed in

<h4>Actual Behavior</h4>
1. The logo is too far toward the top of the row
![image](https://cloud.githubusercontent.com/assets/4965832/8190371/1e6dec98-1430-11e5-806c-c2736d026674.png)

<h4>Expected Behavior</h4>
1. The logo should be centered in the row

**Comment by XTech2K** [comment]
@sloria I think this may need to be reopened, since it looks like the removal of site.css has rendered some of my changes null, and the OSF Storage icon is right back to where it when this issue was made.

**Comment by lbanner** [comment]
Yours @XTech2K ... was this due to style changes @caneruguz ?

**Comment by XTech2K** [comment]
actually, it looks like not only the ones in site.css, but all of the changes from my commit for this were undone at some point.

**Comment by XTech2K** [comment]
A new fix has been created, and is now a hotfix rather than a feature fix since I believe the functionality has already been looked at now.

If that sounds like a bad idea, just tell me and I will change it to a feature fix.

**Comment by caneruguz** [comment]
@XTech2K I already fixed this through our trello bugs and it will go out soon. 

My solution uses much less code change so I recommend we go with that one. 

@sloria

**Comment by XTech2K** [comment]
Understood. In that case, I will leave it to you.
