### ISSUE TITLE
[production] [bug] Not all Mendeley Folders and Subfolders displaying

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#3157]
User is experiencing problems with Mendeley. In add-on configuration, not all of her folders nor all of her subfolders are displaying to be selected: 

"I have been having some trouble with Mendeley/OSF integration. I've synced
my account and created the access token for a project, but my OSF project
does not update if I create a new folder in Mendeley and some of my
sub-folders do not appear properly. I've ensured that my Mendeley account
is up to date and I've tried de-authorizing, deleting the access token, and
setting everything up again but I still cannot solve the problem. In
addition to this, I know that the account is actually connected because if
I change the name of a folder that does appear, the name updates properly.
Do you have any suggestions?"

@lyndsysimon has investigated and believes there is a caching issue - he can likely provide more detail about a possible cause/fix.

**Comment by saradbowman** [comment]
I have a very similar case on the help desk, but the user is experiencing the problem in Zotero.

Is there an update on this issue?

**Comment by GaryKriebel** [comment]
@lyndsysimon .... do you have any insight to a possible fix that could be handed over to an intern?

**Comment by saradbowman** [comment]
ping @lyndsysimon

**Comment by lyndsysimon** [comment]
What I thought might have been a caching issue wasn't. Without digging into the issue more fully, I don't have a specific suggestion as to where the problem might be.

I do think it's a realistic task for an intern, though. Also, another person to ask for insight might be Sam, as he worked extensively with the Medeley and Zotero addons during the epic where they were released.

**Comment by mfraezz** [comment]
It appears that we're not passing in a limit to the API, and with the default of 20, the user is only getting the first 20 folders she created. I'm assuming something similar is happening with Zotero.

**Comment by GaryKriebel** [comment]
@saradbowman .... do you know how many folders the user has?

**Comment by saradbowman** [comment]
I have more information on hand about the Zotero case- it appears he has 20 top-level folders. Only 5 top-level folders are displaying on the OSF - but there are an known (to me) number of subfolders. 

Are folders displayed in the order in which they were created? 

I can get more information from the user if that is helpful.

**Comment by mfraezz** [comment]
Based on my testing, Mendeley seems to sort folders based on creation time

**Comment by mfraezz** [comment]
I've successfully replicated and solved this for Mendeley locally. I'm working on testing it for Zotero.

**Comment by mfraezz** [comment]
@lyndsysimon @GaryKriebel @saradbowman Are those limits sufficient for a sufficiently high percentage of use cases, or should I complicate things with pagination?

**Comment by GaryKriebel** [comment]
I would think that 500 is good for now and if it remains a problem we can deal with pagination then.  Thoughts @saradbowman ?

**Comment by mfraezz** [comment]
I agree about Mendeley. What about Zotero's 100?

**Comment by GaryKriebel** [comment]
I would say that for the short term let's proceed with the fix as it stands and we can revisit for pagination if there are still immediate needs from the userbase.

**Comment by saradbowman** [comment]
Turns out the user has 900 Zotero folders. Can we reopen this?

**Comment by GaryKriebel** [comment]
This will have to become a feature request as we have designed the system to handle the maximum number of returned folders per their API.  Allowing for more will require new requirements and design work.

**Comment by GaryKriebel** [comment]
@erinmayhood ... this will require discussion/decision on UI.

**Comment by mfraezz** [comment]
@GaryKriebel, 100 for Zotero (or 500 for Mendeley) is only the max number of returned items *per request*. It wouldn't require much to keep sending requests with a different starting index until all the items had been returned, but depending on the total number of items a user has, this could either break folderPicker or dramatically slow the UI response time.

**Comment by GaryKriebel** [comment]
@mfraezz I was thinking that there would have to be pagination in the returning sets. 

Slowing the response time, I have no problem with... a user with 1,000 folders should expect it might take some time to load those folders.

Breaking the folder picker is certainly a different thing, though.

**Comment by mfraezz** [comment]
The most likely way of it 'breaking' would be the browser noticing that it's taking a long time, and giving one of those `Unresponsive Script` warnings that you've probably seen before. I'm not even certain that this would happen for anything other than a very large set (~50,000+ items). An easy way to avoid this would be capping the number of possible requests at some value at or less than 20 (~2000 items). 

Pagination would be a slightly more complicated way of handling this, as `folderPicker` isn't really designed with that in mind. It would also require a lot of discussion on UI, as I don't know of anything else like it on the site that uses pagination. For example, what happens if a user has 100,000 files in a connected Dropbox folder?

**Comment by mfraezz** [comment]
One possibility would be loading about 500 items, then having a `Load More` link at the bottom that triggers another (up to) 5 requests.
