### ISSUE TITLE
Add Sentry logging to DRF

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3163]
Currently, the API is not logging errors to Sentry. It probably should be.

**Comment by lyndsysimon** [comment]
Here's the documentation for Raven's Django integration: http://raven.readthedocs.org/en/latest/integrations/django.html

**Comment by abought** [comment]
Can't assign myself, but as discussed with @brianjgeiger , I'm going to start implementing as part of the effort to trace #3058 .

**Comment by abought** [comment]
#3192 merged. @brianjgeiger and @icereval  , let me know when this is deployed to Staging2 and I'll commence with testing the feature.

**Comment by icereval** [comment]
@abought this has been deployed to staging2.

**Comment by abought** [comment]
I used the runscope test to confirm that Sentry is logging API errors; thanks, @icereval . Both the API and OSF loggers are called root, but we can always change that in the future if needed.

![screen shot 2015-06-25 at 4 18 44 pm](https://cloud.githubusercontent.com/assets/2957073/8364673/f171f400-1b55-11e5-8e6a-5ce939b393a2.png)
