### ISSUE TITLE
add contributor language is misleading

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3166]
<h4>Steps</h4>
1. Visit a project with at least one component
2. Add a user to the component—not the project
3. Now search to add a user to the project—stop before confirming on the "select components" page.

<h4>Actual Behavior</h4>
1. The user is asked "Would you like to add these contributor(s) to any children of the current component?" even if they are contributors on those components.

![screen shot 2015-06-17 at 9 44 38 am](https://cloud.githubusercontent.com/assets/4965832/8208671/c8565168-14d6-11e5-83c2-b50d5c0c3eed.png)

<h4>Expected Behavior</h4>
1. The user should instead be told "Select any other components that you would like to apply these settings to." This would encompass the fact that users may be updating settings, but that the contributor being added might already be on one of the subcomponents.

**Comment by lbanner** [comment]
Thanks @jlcohoon

**Comment by brandonPurvis** [comment]
I can take care of this.

**Comment by lbanner** [comment]
You got it!
