### ISSUE TITLE
add link to project in email to unregistered users and sticky alert to claim account to OSF

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3170]
This comes from the community repo: https://github.com/CenterForOpenScience/community/issues/235

<h4>Current Behavior</h4>
Users that are added as unregistered contributors receive an email alerting them that they have been listed in an OSF project. This email tells the recipient that they can register on the OSF and it tells them the project name, but does not actually link them to the project itself. Often, these OSF projects will be private, so they cannot see the project they were added to until they have created their account.

![screen shot 2015-06-16 at 1 30 07 pm](https://cloud.githubusercontent.com/assets/4965832/8209420/d6476a4c-14da-11e5-82e0-fa16549079cd.png)

<h4>Expected Behavior</h4>
In the email to unregistered users, the project that they were added to should be linked. Upon clicking, users should have read-only access to the parts of the project (perhaps via a view only link?) that they were added as a contributor to. 

![screen shot 2015-06-17 at 10 48 21 am](https://cloud.githubusercontent.com/assets/4965832/8210104/7f626548-14de-11e5-9ef3-0f8425ac84b1.png)

When they visit the OSF via that link, a non-dismissable alert should be visible at the top of every page, asking them to claim their account ("You have been added by [User Name] as a contributor to [Project Title]. Click here to claim your account."). The link in that alert should have the token to enable them to claim their account.

![screen shot 2015-06-17 at 10 44 57 am](https://cloud.githubusercontent.com/assets/4965832/8210106/816cd544-14de-11e5-8e29-af47de7db4fa.png)

**Comment by jlcohoon** [comment]
As a note, the emails to registered contributors do send a link to the project. Only unregistered users do not get a link to the project. As mentioned above, a view-only link could be a good solution to ensure that they can view the contents if it is private.

**Comment by GaryKriebel** [comment]
Closed via https://github.com/CenterForOpenScience/osf.io/pull/5868
