### ISSUE TITLE
[Production] File Edit: No Indication of Save

### ISSUE THREAD

**Issue by Ghalko** [CenterForOpenScience/osf.io#3171]
## Steps
1. Open a text file in view files
2. Edit it
3. Save it

## Expected
Indication that file was saved, and current version is current (and saved) until changes are made.

## Actual
Only the versions pane updates to show that the file has been saved. However, this can be hidden. The only way a user knows that there are no changes is to press save again to receive an alert (Bad!) that there are no changes that need saving.

![screen shot 2015-06-17 at 10 41 54 am](https://cloud.githubusercontent.com/assets/5169088/8209976/e08ff160-14dd-11e5-8972-0e57d1103500.png)

## Suggestions
- ***Remove the Alert*** as it is not helpful and causes people to click on the alert to get rid of it. Not Useful.
- Look at Google's Documents or Evernote for how they indicate the saved state of text editors.
- Implement subtle yet consistent indicator of saved state.
- (Possible but not necessary) Make saving automatic whenever the user pauses (or periodically), and make the button into a version button that will allow a user to set the current document state as a new version.

**Comment by haoyuchen1992** [comment]
I can work on this.

**Comment by haoyuchen1992** [comment]
The suggestion is really good! Caner and I have discussed about it. The enhancement will be considered and implemented when we have time  to design new UI for wiki and editor.
