### ISSUE TITLE
templates do not copy folders

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3180]
This comes from the community board: https://github.com/CenterForOpenScience/community/issues/247

<h4>Steps</h4>
1. Visit a project with a folder created within OSF storage ("Apples" in the image below)
![screen shot 2015-06-17 at 12 26 02 pm](https://cloud.githubusercontent.com/assets/4965832/8212868/4689a82c-14ec-11e5-8d77-fbdfd726bffa.png)

2. Click the "Duplicate" button and select "Template From"

<h4>Outcome</h4>
1. The folder within OSF storage is not copied as part of the project structure
![screen shot 2015-06-17 at 12 25 53 pm](https://cloud.githubusercontent.com/assets/4965832/8212873/4c403c22-14ec-11e5-95d7-861bc9d8f41a.png)

<h4>Expected Outcome</h4>
1. Because folders are part of project structure, they should be copied as part of the template

**Comment by lbanner** [comment]
Do we know if this is expected functionality based upon the current code? I will assume yes for now, and tag w/Enhancement vs bug. Thanks.

**Comment by brianjgeiger** [comment]
If files aren't copied, then it is understandable that folders wouldn't be copied as well. Changing that will almost certainly warrant a proposal, as it has implications.

**Comment by jlcohoon** [comment]
Close this then and add it to the needs proposal list?

**Comment by lbanner** [comment]
Yeah -- I'll close. Thanks @jlcohoon
