### ISSUE TITLE
Should be able to upload a new version of a file on the file details page

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3181]
From the community repo/usability review: https://github.com/CenterForOpenScience/community/issues/209

<h4>Steps</h4>
1. Visit the project overview or the files page (e.g. osf.io/abcde/files)
2. Drag and drop a file onto the file tree on either page
3. Visit that file (or any other file)
4. Drag and drop a file onto the file tree on the left side of the file's detail page

<h4>Actual Behavior</h4>
1. Step four above (dragging and dropping on the file's detail page) is unsuccessful

<h4>Expected Behavior</h4>
1. Because in most places where the user sees a file tree, they can drag and drop to upload a file, one would expect to be able to drag and drop a file from the detail page. This would be especially useful because people often visit a file to view it and then upload their newer version.

**Comment by lbanner** [comment]
This gets at the greater question of when/if we move to the Files-View page as sole Files page, I think -

**Comment by remram44** [comment]
Was about to open the same issue! Since the whole file list is shown on a "file details" page, people are bound to interact with it. If I can select a folder, it is not clear to me why I can't upload a file to it.

![screenshot: drag&drop a file over a folder](https://user-images.githubusercontent.com/426784/41175506-5090fbca-6b2b-11e8-998d-886111f441da.png)

**Comment by remram44** [comment]
As you can see the "files" entry of the navbar is selected too, so it is not clear why I would need to click on it to get to a very similar-looking file list, but that one will accept drag&drop. This took me a while to figure out.

I remember already encountering this issue in the past, opened the files list from Chrome, and when drag&drop worked there I just assumed OSF didn't support upload from Firefox. This is really confusing.

**Comment by remram44** [comment]
This is not fixed @futa-ikeda...

**Comment by futa-ikeda** [comment]
Hello @remram44, sorry for closing this issue without any context! We've taken this feature request and added it to our internal issue tracker. We are looking to improve the files interface so user feedback is greatly appreciated.

If you have any further feature requests or feedback, we would love to hear from you here: https://help.osf.io/hc/en-us/requests/new or if you have a support related question, you can contact support@osf.io
