### ISSUE TITLE
surface file copying feature

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3182]
This is from the OSF suggestion box/community repo: https://github.com/CenterForOpenScience/community/issues/220

<h4>Current behavior</h4>
In order to copy files and folders on the Project Overview page, you have to hold down the "option" button (on Macs) while dragging and dropping a file or folder. Most users are entirely unaware that you actually can copy a file because there is no instruction on how to do so.

<h4>Desired Behavior</h4>
To alert users to the fact that they can copy files, add information about copying a file to the information button with directions about the file tree:

![screen shot 2015-06-17 at 1 19 39 pm](https://cloud.githubusercontent.com/assets/4965832/8213924/90723c36-14f3-11e5-9f67-3a5232988796.png)

**Comment by brandonPurvis** [comment]
I can take this.

**Comment by lbanner** [comment]
You got it! thanks!
