### ISSUE TITLE
Allow drag and drop image uploading and embedding

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3183]
From the OSF suggestion box/community repo: https://github.com/CenterForOpenScience/community/issues/222

<h4>Current Behavior</h4>
Presently, to include an image in the wiki, users must type in the correct markdown or click on the image button. 

<h4>Desired Behavior</h4>
On github, you can drag an image into a text field like a comment or a PR description. If you do that, it uploads the file and automatically inserts the tag for the image wherever the cursor was in the text. This would be a fantastic feature to steal for our wiki.

**Comment by brianjgeiger** [comment]
Plus one.

**Comment by chrisseto** [comment]
+1
