### ISSUE TITLE
[Staging and Production] Multiple clicks on create project button creates many of same project

### ISSUE THREAD

**Issue by WillBanner** [CenterForOpenScience/osf.io#3187]
# [Firefox] [Safari] [Chrome]
# Steps
1. Go to staging.osf.io and log in.
2. Go to your dashboard.
3. Look at the right hand side of the screen and click on the + next to "create project."
4. Enter in a random project name and double click on the "create" button.

# Expected 
I would create one project

# Actual 
Two projects were created with that exact same name.

![image](https://cloud.githubusercontent.com/assets/12799635/8215231/b100813e-14fc-11e5-9539-fcd3dd6c5943.png)

**Comment by haoyuchen1992** [comment]
Just replicate the problem. I could work on it!

**Comment by lbanner** [comment]
You got it!
