### ISSUE TITLE
[Production & Staging] Dragging project or component in Dashboard to ineligible row causes highlight to persist

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3191]
### Steps
1. Go to [osf.io](http://www.osf.io).
2. Go to your Dashboard.
3. Click the row of one of your projects or components.
4. Drag and drop to the "All my projects" row.
5. Click any other row.

### Expected behavior
I expected that dragging and dropping a project or component around to any row (other than a collection) would cause the highlight on that other row to disappear. 

### Actual behavior
When I drag a project into the "All my projects" row, a light blue highlight stays over that row even when I click another row. (You can replicate this effect in more ways as well). 

Projects and components can only be dragged successfully into a collection, which will flash a green highlight.

![screen shot 2015-06-17 at 3 17 08 pm](https://cloud.githubusercontent.com/assets/8591162/8216848/32d4a1b8-1507-11e5-8b52-c94707fff692.png)

**Comment by haoyuchen1992** [comment]
I just replicated the issue.  Can I grab this one? Thanks :)

**Comment by lbanner** [comment]
:+1:
