### ISSUE TITLE
[Staging & Production] Dataverse: Improve Error Handling when unable to render and download files

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3197]
## Steps
1. Log in to osf.io and go to a project that you have admin access on
2. Go to the project's settings tab 
3. Enable the dataverse add-on
4. Configure and link a dataset to the project
5. Go to the project's files tab
6. Click to toggle the folder displayed from published to draft
7. Click in the toolbar to upload a file (or use an existing file)
8. Now click on the file to render a view on the files detail page (either a draft or published file)
9. Click to download the file
## Expected

I would expect to be able to render common file types and to be able to download them
## Actual

The files do not render, and give a 404 error.  The files also do not download and show incorrect information and no error to the user.

![screenshot 2015-06-18 08 22 04](https://cloud.githubusercontent.com/assets/9381062/8231023/7ef3d974-1593-11e5-82aa-9a7ca40800b0.png)

![screenshot 2015-06-18 08 23 04](https://cloud.githubusercontent.com/assets/9381062/8231030/85d36566-1593-11e5-87d8-25d9605f9448.png)

**Comment by lbanner** [comment]
Is this consistent? Or possibly a blip on the part of Dataverse?

**Comment by nicipfeiffer** [comment]
@lbanner It very likely is an error on that part.  I think this is more about the error handling

**Comment by lbanner** [comment]
OK -- good point. Let's rename with an eye toward error handling?
