### ISSUE TITLE
[Production & Staging] "Files couldn't load" error message in Files viewer is unhelpful and wrong color

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3205]
### Steps
1. Go to [osf.io](http://www.osf.io).
2. Go to one of your projects.
3. Go to your project's Settings page.
4. Enable a storage add-on with an empty storage folder/bucket.
5. Go to the project's Files page.
6. Click on the row of the add-on you selected.
7. Observe the error message in the add-on's row.

### Expected behavior
I expected that the error message would tell me something like "No files found."

### Actual behavior
The error message is the same for every situation of files not loading, so it is not helpful to the user. It also distracts the user too much since the message replaces the name of the empty add-on, folder, or file, and it is centered in the row instead of left-aligned like the rest of the text. The user's eyes have to jump around too much. 

The red color is also too bright compared to the OSF standard ([style guide](http://caneruguz.github.io/osf-style/style.html#colors)).

![screen shot 2015-06-18 at 2 28 53 pm](https://cloud.githubusercontent.com/assets/8591162/8238879/643f0828-15c6-11e5-83cb-1a2bc122557b.png)

Standard red error message:
 ![screen shot 2015-06-18 at 2 33 56 pm](https://cloud.githubusercontent.com/assets/8591162/8239014/33d34dec-15c7-11e5-8414-27065f50b3de.png)

**Comment by lbanner** [comment]
Good point on lack of consistency + usefulness. @caneruguz ... style thoughts?

**Comment by caneruguz** [comment]
@lbanner assign me and I'll work on this.

**Comment by lbanner** [comment]
Done!
