### ISSUE TITLE
[Production & Staging] 'Error rendering template' error message in Registrations view of project

### ISSUE THREAD

**Issue by TimErrington** [CenterForOpenScience/osf.io#3210]
<h1> Steps </h1>

1. Go to osf.io
2. Go to a project that has a registration (example: https://osf.io/7zqxp/)
3. View Registrations tab
4. Observe error message

<h1> Expected behavior </h1>
I expect to see the registration that is there with the link to it.

<h1> Observed behavior </h1>
The error message  "Error rendering template util/render_nodes.mako: NameError('Undefined',)" appears

![screen shot 2015-06-18 at 4 22 00 pm](https://cloud.githubusercontent.com/assets/5816601/8241244/310f2d2e-15d6-11e5-8cf0-df6e3f57c3c9.png)

**Comment by GaryKriebel** [comment]
Ping @sloria

**Comment by sloria** [comment]
Looking into this

**Comment by chennan47** [comment]
I think @lyndsysimon has solved a problem similar before.

**Comment by sloria** [comment]
Fixed now.
