### ISSUE TITLE
[Production & Staging] unlogged in view of registrations of a project has link to register parent project

### ISSUE THREAD

**Issue by TimErrington** [CenterForOpenScience/osf.io#3211]
<h1> Steps </h1>

1. Go to osf.io
2. Go to a project without being logged into the osf
3. Go to a public project that is a child project/component of another project and view registrations page (example: https://osf.io/sd7kg/registrations/)

<h1> Expected behavior </h1>

I expect to see any registrations that are there. If there are no registrations I expect to see a link to the most viewed and most recent public registrations on the OSF.

<h1> Observed behavior </h1>

While the registration link, or the link to the most viewed and pubic registrations on the OSF appears, there is also text that reads that to register the entire parent project to click here (with a link to the registration page of the parent project). This is expected if I am logged into the account (along with the option to register that given project/component), but not if I'm viewing another project I'm not a contributor on.

![screen shot 2015-06-18 at 4 31 09 pm](https://cloud.githubusercontent.com/assets/5816601/8241458/728a679a-15d7-11e5-9a79-dc9f6f079193.png)

**Comment by GaryKriebel** [comment]
@TimErrington ... I'm not seeing what you saw.

![screen shot 2015-06-22 at 3 11 05 pm](https://cloud.githubusercontent.com/assets/9437946/8290437/070552ba-18f1-11e5-8b0d-83e881c3b7e7.png)

**Comment by TimErrington** [comment]
I'm not seeing it now either. Maybe it is gone now that the other registration problem was addressed (the template error one - https://github.com/CenterForOpenScience/osf.io/issues/3210#issuecomment-113280336)

**Comment by GaryKriebel** [comment]
I'll close this and we can reopen/resubmit if the behavior is experienced again.
