### ISSUE TITLE
[Production & Staging] Component log just reads "A user" while loading

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3216]
## Steps

1. Log in to osf.io.
2. Navigate to one of your projects.
3. Make sure the project has components.
4. Click the "+" sign to the right of a component's title.
5. Look at the component's log as it loads the recent activity.

## Expected behavior

I expect that while loading the component log will remain empty or have a spinning blue bar, as the project log does while loading.

## Actual behavior

The words "A user" appear, and if one's internet connection is slower, those words remain for more than a few seconds (long enough to take a screenshot), which is confusing for the user.

![components log](https://cloud.githubusercontent.com/assets/7093086/8241540/daccdcd4-15d7-11e5-94d9-5524a60a2f2a.png)

**Comment by haoyuchen1992** [comment]
@lbanner I just replicated the issue, I can work on it! Thanks!

**Comment by NatashaRichter** [comment]
Fixed. Closing.
