### ISSUE TITLE
[production] version numbers of .gdocs aren't stable

### ISSUE THREAD

**Issue by csoderberg** [CenterForOpenScience/osf.io#3231]
Steps to recreate the issue:
* Connect the google drive add-on to a project (https://osf.io/54hqf/)
* Create a new google document on google drive
* Add some text
* Refresh the OSF page, the document will appear with 1 version
* Go back to google drive and make some more changes to the google doc
* Refresh the OSF page again

Expected Behavior:
* You would expect to see at least two versions of the .gdoc listed on the OSF

Actual Behavior:
* There is still only one version, but the version ID has changed drastically.

![screenshot 2015-06-19 11 12 53](https://cloud.githubusercontent.com/assets/7332030/8256526/962ee3bc-1675-11e5-98a4-3f28e4884135.png)
![screenshot 2015-06-19 11 12 27](https://cloud.githubusercontent.com/assets/7332030/8256525/962c4544-1675-11e5-9d32-cee79838acc3.png)

**Comment by chrisseto** [comment]
I'll take a look at this, @lbanner

**Comment by lbanner** [comment]
Thanks @chrisseto

**Comment by chrisseto** [comment]
So this is a bit of an odd one. Google does not give back revision history when come to google docs. All we have in terms of version information is the "etag" which is why the version id changes but there are no additional versions displayed.

**Comment by csoderberg** [comment]
So sometimes google docs on the OSF have multiple versions displayed (e.g. https://osf.io/uk59r/), but I'm not sure which causes it to create a whole different version vs. just change the version ID on one version.

**Comment by nanchen47** [comment]
Will be considered in later enhancement. Thanks.
