### ISSUE TITLE
[Production & Staging] Quickly clicking through project logs leads to "No logs to show" page

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3233]
## Steps

1. Log in to osf.io.
2. Navigate to one of your projects that has a lot of activity in the log (at least 8 or 9 pages) or go to the "Center for Open Science" project, which has many pages
3. Click the right arrow in the log very quickly to try to navigate to the last page of the log.
4. Check what the last page of the log is.

## Expected behavior

I expect that the last page of the log will list my earliest activities on the project.

## Actual behavior

I end up on a page that says "No logs to show. Click the watch icon on a project's page to get activity updates here." In the instance below it appeared even when there were logs (although the activity is, "Could not render log."). See screenshot below. The page number I am on in the screenshot is not highlighted at this point either. Is this perhaps an issue with not being able to render the log under certain circumstances?

The project below is: https://osf.io/5936d/

Ping me for access if you'd like to replicate on this project on production.

## Notes

This issue is related to https://github.com/CenterForOpenScience/osf.io/issues/3230, although that one deals with the inconsistency of landing on the "No logs to show" page. If you click slowly through the logs, you won't arrive at this page.

## Screenshots

![notrenderlog](https://cloud.githubusercontent.com/assets/7093086/8259450/90d093ce-168a-11e5-8176-30ab767ed3d3.png)

**Comment by nanchen47** [comment]
This looks like a log template error. Can be an intern task.

**Comment by nanchen47** [comment]
This pr has been merged and deployed on production.
