### ISSUE TITLE
Registration component contribution counts incorrect 

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3238]
Sort of reviving #1478 but this is a little different

# Steps
1. Log into production
2. Go to a registration that has at least one component (can expand 'All my registrations' collection in project organizer to find one)
3. Look at the component list on the right side of the registration project overview page
4. Check for number of contributions

# Expected
I expect that the number of contributions for that component would be shown. Since components were at least created, the number of contributions should be non-zero.

# Actual
Some components show *None contributions:* 
![screen shot 2015-06-19 at 3 05 37 pm](https://cloud.githubusercontent.com/assets/5975444/8260922/b0d16b9e-1694-11e5-9f09-b711d9848170.png)
despite the components having files added. 

The registration project log does not show any contributions for the components that have *None contributions* displayed. Visiting the component registration page shows an empty log: 
![screen shot 2015-06-19 at 3 07 23 pm](https://cloud.githubusercontent.com/assets/5975444/8260960/ec24e7c0-1694-11e5-9616-6969a10db0a8.png)

Other components have *0 contributions:*
![screen shot 2015-06-19 at 2 59 48 pm](https://cloud.githubusercontent.com/assets/5975444/8261020/4a1bd79e-1695-11e5-9ee9-298302350ee9.png)
despite the components having files added. 

Again, the registration project log does not show any contributions for the components that have *0 contributions* displayed, and visiting the component registration page shows an empty log.

Then, some components appear as normal with their actual contribution number listed.

**Comment by chennan47** [comment]
This is related to the none log problem and will be fixed by https://github.com/CenterForOpenScience/osf.io/pull/3224

**Comment by sloria** [comment]
Migration was run. @caileyfitz Can you confirm that this is fixed?

**Comment by caileyfitz** [comment]
Issue is resolved :whale:
