### ISSUE TITLE
[account merging] account shows up in both alternative email and unconfirmed email

### ISSUE THREAD

**Issue by chennan47** [CenterForOpenScience/osf.io#3248]
<b>Steps</b>
1. create 3 registered user A ,B and C
2. log in as user A and add B and C's email to A
3. go to user B's email and find and confirm the link in the email. 
4. log in as use A and go to the your account settings page.

<b>Excepted</b>
User B's email will show up in alternative email and user C's email is in unconfirmed email.

<b>Actual</b>
![screen shot 2015-06-22 at 12 00 54 pm](https://cloud.githubusercontent.com/assets/4974056/8286372/18c98904-18d7-11e5-9abe-e87ffcec7eb8.png)
User C's email is showing up in both alternative email and unconfirmed email

**Comment by nanchen47** [comment]
https://github.com/CenterForOpenScience/osf.io/pull/3224

**Comment by XTech2K** [comment]
I attempted to recreate this issue, but ended up getting the expected result instead of the problematic one. The only difference when I tried this was that all emails were sent to my account A, and it was with that account that I confirmed account B, not the other way around.

![screen shot 2015-06-22 at 1 21 33 pm](https://cloud.githubusercontent.com/assets/5955359/8288039/921049ec-18e1-11e5-9a27-87fb86b73906.png)

**Comment by chennan47** [comment]
When I clicked on my third account's email confirmation link, it said that that email has already been merged. I sort of remember I have merged that account before but not sure. Need to take a look at the production database to find out what's going on.

**Comment by sloria** [comment]
Migration was run. @chennan47 Can you confirm that this is now fixed?

**Comment by chennan47** [comment]
Migration was run. @chennan47 Can you confirm that this is now fixed?
![screen shot 2015-06-24 at 9 07 47 am](https://cloud.githubusercontent.com/assets/4974056/8330616/8249a920-1a50-11e5-9a42-ac039cb92142.png)

**Comment by sloria** [comment]
Ah, I commented on the wrong issue; the migration had nothing to do with this issue. I will look into this soon.

**Comment by chennan47** [comment]
This problem may be caused by old bad data in staging server and can't repo anymore.
