### ISSUE TITLE
Duplicate and Watch buttons should not be visible to logged out users

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3249]
This issue was caught by an OSF user, and then was logged in the community repo: https://github.com/CenterForOpenScience/community/issues/258

<h4>Steps</h4>
1. Visit any OSF project while logged out
2. Look at the upper right hand of the project overview page

<h4>Current behavior</h4>
1. The watch button is greyed out, indicating no action can be taken, but it is still present.
2. The duplicate button is active and users can click on it, though the options to fork/template/link are unavailable.

![screen shot 2015-06-22 at 12 02 49 pm](https://cloud.githubusercontent.com/assets/4965832/8286411/4adfd4a2-18d7-11e5-863e-fb5585853bc6.png)

<h4>Expected behavior</h4>
1. The watch button and the duplicate button should not be visible to users who are not signed in; at the very least, the duplicate button should not be clickable by users who are not signed in.

**Comment by XTech2K** [comment]
I will work on this issue.
