### ISSUE TITLE
Forks of projects cannot be displayed; shows error

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3250]
<h4>Steps</h4>
1. Visit a public project with forks (https://osf.io/px0sw/, for example)
2. Click on the "forks" tab

<h4>Current Behavior</h4>
1. The user is shown an error:

![screen shot 2015-06-22 at 12 09 30 pm](https://cloud.githubusercontent.com/assets/4965832/8286440/909fa6de-18d7-11e5-9ca2-191768cd7e75.png)

This only occurs if there have been forks. If no forks have been created, the user is just informed that there are none to view.

<h4>Expected</h4>
1. Forks should be listed on the forks tab.
2. If forks cannot be listed (i.e. if there is an error) the error users are shown should be more approachable—something like: "Forks cannot be displayed at this time, please try again later."

**Comment by chennan47** [comment]
@sloria I thought this is fixed last week.

**Comment by sloria** [comment]
This is now fixed
