### ISSUE TITLE
File Detail Page via Anonymous Links for new projects shows user detail

### ISSUE THREAD

**Issue by GaryKriebel** [CenterForOpenScience/osf.io#3253]
Per @saradbowman, two reports via the help desk state that anonymized view-only links are displaying contributors' names on file history on file detail page.

I am not linking to those reported projects as they are user's private projects.

In investigating the issue, making an anonymous view-only link for a previous project shows correct behaviour:
https://osf.io/u7r5e/?view_only=15cf92dcfca646769116bce86a0a3e6c
![screen shot 2015-06-22 at 2 46 12 pm](https://cloud.githubusercontent.com/assets/9437946/8289926/7660c7f6-18ed-11e5-98c4-712bde10b9a7.png)

However, for a newly created project.  After uploading files and then creating an anonymized view-old link, the behaviour described in the help desk issues is seen:
https://osf.io/5u7rc/?view_only=ad9606ffbc0544c0871262705ef6ba95
![screen shot 2015-06-22 at 2 47 37 pm](https://cloud.githubusercontent.com/assets/9437946/8289955/a753e546-18ed-11e5-8735-114841f5a58d.png)

**Comment by chennan47** [comment]
The problem does not matter about when the project is created. It seems the anonymous link is not hiding the name for OSF storage files.

**Comment by GaryKriebel** [comment]
my apologies, @chennan47 ... I thought I liked to a file in OSF... I see that my top link was dropbox.

**Comment by saradbowman** [comment]
User reports issue is resolved - thanks @GaryKriebel @chennan47!
