### ISSUE TITLE
Dataverse: Send Registrations DOIs to Related Publication Field for a dataset

### ISSUE THREAD

**Issue by eaquigley** [CenterForOpenScience/osf.io#3255]
During a recent OSF talk, I saw DOIs are now being minted for Registrations. From what I can tell those aren't being sent over to Dataverse through the SWORD API when someone is pushing their dataset from OSF to Dataverse. 

@posixeleni and myself discussed this as an issue in the Dataverse repo here: https://github.com/IQSS/dataverse/issues/2236 and think it would fit well into the Related Publications metadata field for a dataset in Dataverse.

This metadata map, https://github.com/IQSS/dataverse/blob/guides4.0/doc/sphinx-guides/source/api/sword.rst#dublin-core-terms-dc-terms-qualified-mapping-dataverse-db-element-crosswalk, also shows it can be mapped by using dcterms:relation if you don't want to use related publication.

**Comment by pdurbin** [comment]
As @posixeleni mentioned at https://github.com/IQSS/dataverse/issues/2236#issuecomment-108654390 the advantage of "Related Publication" is that it's structured rather than how "Related Material" is free form.
