### ISSUE TITLE
Mendeley and Zotero add-on terms modals incorrect

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3276]
# Steps
1. Log into production
2. Go to user settings > Configure add-ons
3. Click the box next to Mendeley and Zotero to enable the add-ons (if already checked, click to uncheck and then click again)
4. Read the registration section of the terms modals for each add-on

# Expected
I expect that the terms modal would indicate that Mendeley and Zotero content **will not** be registered, since we decided that the content is non-registerable (and the registration confirmation modal notes that citation add-on content will not be registered)

# Actual
The registration section of the terms modal states that the content **will** be registered for both Mendeley and Zotero. This occurs when enabling the two citation add-ons in both user settings *and* project settings: 

Add-on terms modals:
![screen shot 2015-06-23 at 11 13 25 am](https://cloud.githubusercontent.com/assets/5975444/8309572/331a92d6-1999-11e5-8462-fb2778d8549f.png)
![screen shot 2015-06-23 at 11 13 33 am](https://cloud.githubusercontent.com/assets/5975444/8309571/33195164-1999-11e5-83e3-5d2aa5238a47.png)

Registration confirmation modal:
![screen shot 2015-06-23 at 11 14 42 am](https://cloud.githubusercontent.com/assets/5975444/8309574/35f9104a-1999-11e5-83ba-84089735534d.png)

**Comment by XTech2K** [comment]
I will create a hotfix for this
