### ISSUE TITLE
[Feature] Add a "New Fork" button to the Forks page

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3278]
### Steps
1. Go to [osf.io](http://www.osf.io).
2. Go to one of your projects.
3. Go to your project's Forks page.

### Expected behavior
I would expect to be able to create a new fork from the Forks page, in the same way that I can create a new registration from the Registrations page.

### Actual behavior
The only way to make a new fork is by clicking the Duplicate button on the top right of the project overview page. This may not be as intuitive as going to the Forks page to create a new fork.

![screen shot 2015-06-23 at 11 39 12 am](https://cloud.githubusercontent.com/assets/8591162/8310290/e7cb81ba-199c-11e5-90cd-6496a0670796.png)

**Comment by XTech2K** [comment]
Oh; I didn't see that discuss label.

Well, if we decide that this change is something we want, I have a PR ready to fix it.

What I did was make the forks page look like the registrations page, which made sense to me since both pages perform similar functions.

**Comment by lbanner** [comment]
OK @XTech2K ... I think we will want @jlcohoon at minimum providing feedback on your approach to this - possibly @saradbowman as well. Thanks.

**Comment by jlcohoon** [comment]
I 100% agree with this.

**Comment by XTech2K** [comment]
By the way, this is what my version of the page looks like:

![screen shot 2015-06-24 at 10 57 42 am](https://cloud.githubusercontent.com/assets/5955359/8333202/fd455c46-1a5f-11e5-9bc6-a615b6cb7158.png)

**Comment by jlcohoon** [comment]
Looks good to me. Could we also move the "There have been no forks of this project" to be left aligned rather than randomly floating?

**Comment by XTech2K** [comment]
I moved the entire column, which means that that happened anyways

here is an image of a project with no forks:

![screen shot 2015-06-24 at 11 05 43 am](https://cloud.githubusercontent.com/assets/5955359/8333463/fce4510c-1a60-11e5-9a36-a160130964e8.png)

**Comment by brianjgeiger** [comment]
Be sure to check the Style Guide for this. http://caneruguz.github.io/osf-style/

**Comment by lbanner** [comment]
+ 1 @brianjgeiger

**Comment by XTech2K** [comment]
Just checked it, and I see no issues, especially because I am just copying the design of another page.

The one thing that might be improvable would be the amount of text when there are no forks, since the page feels slightly empty with just one short sentence. Any ideas on what could be put there?

**Comment by brianjgeiger** [comment]
Specifically, http://caneruguz.github.io/osf-style/style.html#buttons - And the style guide is more important than existing usage. There's all sorts of crazy inconsistent things we do now that we don't want to copy.

**Comment by XTech2K** [comment]
Thanks! Fixing that now. I can also change the registration button to be the correct color if we want (especially since that is one of the exact examples used in the style guide) but would it be a bad idea to include that in the same PR, even if it is a single-word change?
