### ISSUE TITLE
Error when searching for * (asterisk) on production

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3281]
## Steps 
1. Go to osf.io
2. On the navbar, click on search and type in the asterisk (*)

## Expected
The search page would display several results for each category

## Actual
I get a 500 error on my console and a message saying 'unable to resolve'. 

![500 error when searching for asterisk](https://cloud.githubusercontent.com/assets/10926926/8315001/45c40ed6-19bb-11e5-95bc-0f478ffcd409.png)

**Comment by GaryKriebel** [comment]
@nanchen47 can you give this a look?

**Comment by nanchen47** [comment]
This problem has been fixed on production by running invoke migrate search to remove wrong data from elasticsearch database.
