### ISSUE TITLE
Incorrect rendering of R code

### ISSUE THREAD

**Issue by TomHardwicke** [CenterForOpenScience/osf.io#3282]
# Steps

Go to https://osf.io/s8z37/

# Expected

Correctly rendered R code document.

# Actual

I get a series of apparently meaningless symbols like this:

![screen shot 2015-06-23 at 15 41 11](https://cloud.githubusercontent.com/assets/5615147/8315379/61914f90-19be-11e5-9232-564f82f50dec.png)

Note that other R code documents in this project are rendering correctly and the file in question appears to be legitimate R code (I can download it to my desktop and open it in RStudio).

**Comment by GaryKriebel** [comment]
Might this be the same issue as https://github.com/CenterForOpenScience/osf.io/issues/3014?

**Comment by sloria** [comment]
Thanks for reporting @TomHardwicke. Yes, this has the same cause as #3014. @chrisseto is working on the fix.

**Comment by chrisseto** [comment]
This is fixed @GaryKriebel
