### ISSUE TITLE
"Make Public" button message is inaccurate for embargoed registrations

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3286]
# Steps
1. Go to osf.io
2. Go to one of your projects that has at least one other admin user
3. Create an embargoed registration of your project
4. In the email sent to admins, **do not** yet click the "Approval" link 
5. Go to the registration's overview page
6. Click the "Make Public" button
7. Read the message in the modal

# Expected behavior
I expect that immediately upon clicking the "Make Public" button, an error message would appear saying that the privacy of the project cannot be changed prior to admin approval:
![screen shot 2015-06-23 at 4 19 33 pm](https://cloud.githubusercontent.com/assets/5975444/8316242/b78a5d38-19c3-11e5-9918-6096aac94794.png)

I also expected that the modal would warn the user that making the embargoed registration public is irreversible, and that these changes went into effect as early as June 8 (although they actually went into effect June 22). 

# Actual behavior
The error message does not appear until a user presses "OK" within the modal. This makes it appear as though the user is actually able to change privacy of the registration. The modal message also says "This registration occurred before June 8..." when it actually was made today and that it thus has the ability to remain private (it does not).

![screen shot 2015-06-23 at 4 23 36 pm](https://cloud.githubusercontent.com/assets/5975444/8316343/4e13d090-19c4-11e5-9bbc-cc91a5b34c0d.png)

pinging @sloria and @HarryRybacki

**Comment by sloria** [comment]
Thanks @caileyfitz . @HarryRybacki please incorporate this behavior into the hotfix for removing the outdated text.
