### ISSUE TITLE
[osf production] Remove "Important Note" from Registration Modal

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#3287]
This is now outdated.  Registration and retraction functionality is in production.

![screen shot 2015-06-23 at 4 31 42 pm](https://cloud.githubusercontent.com/assets/1761504/8316497/7487b858-19c5-11e5-9d5c-489f1f126a49.png)

A sentence can be added to the top paragraph "After selecting OK, you will next select a registration form."

**Comment by lbanner** [comment]
Thanks @bnosek  -- @sloria has this on his list, but good to have it here as issue.

**Comment by caileyfitz** [comment]
Related to #3286 (same inaccurate information in the modal but the modal appears in a different place)
