### ISSUE TITLE
Go/nogo on 0.41.0

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#3292]
Includes the new landing page and navbar.

Also contains a few bugfix PRs https://github.com/CenterForOpenScience/osf.io/pulls?page=1&q=is%3Apr+milestone%3A0.41.0+is%3Aclosed which have already gone through QA.

ping @JeffSpies @GaryKriebel @lbanner @caileyfitz

**Comment by lbanner** [comment]
Including all 47 of those PR's tagged w/41 milestone @sloria ?

**Comment by sloria** [comment]
@lbanner No, only those that are closed and have gone through QA.

**Comment by lbanner** [comment]
Cool. So -- I am going to assume that we defer for graphics-contractor participation the "mobile" oriented bugs on Trello board for the new landing page? -- If so -- it's looking very clean at present!

**Comment by GaryKriebel** [comment]
My only concern is the logo when seen in Safari.
![screen shot 2015-06-23 at 4 38 02 pm](https://cloud.githubusercontent.com/assets/9437946/8332612/d52679be-1a5c-11e5-8dca-6f1255c036d3.png)

Is this one of the issues that Caner is reviewing?

**Comment by sloria** [comment]
Yes, @caneruguz is looking into this now.

**Comment by JeffSpies** [comment]
It does something similar on small screens.

**Comment by sloria** [comment]
Here is the trello card: https://trello.com/c/W8q6GJOR/19-safari-mobile-responsive-logo-is-broken

**Comment by lbanner** [comment]
PR is in: #3295

**Comment by caneruguz** [comment]
Wow that was fast @lbanner ! I updated the Trello board. 

The one thing that I couldn't figur out fast is that their dot animation does not properly reset itself on resize (orientation change in phone is also resize). That's something that might need to go back to them.

**Comment by sloria** [comment]
Once the latest fixes have gone through QA, I am a go.

**Comment by lbanner** [comment]
I'm on board -- "GO" w/those fixes passing. Thanks.

**Comment by caneruguz** [comment]
Sara had comments on the text consistency https://github.com/CenterForOpenScience/osf.io/pull/3267#issuecomment-114909631

**Comment by sloria** [comment]
Those comments have now been addressed.

**Comment by GaryKriebel** [comment]
Capital "I" on "OSF Integrations make ..."?

**Comment by caileyfitz** [comment]
When all cards have made it through QA and all issues resolved, I am a GO. 

We currently have three cards in 2nd Pass, three in Bugs Found, and one in Draft/Pending

**Comment by JeffSpies** [comment]
Does the OSF have an upper password limit?

**Comment by sloria** [comment]
@JeffSpies I believe it is 256 characters.

**Comment by JeffSpies** [comment]
And the minimum is 6? Shall we update the landing page?

**Comment by sloria** [comment]
Yes, good catch. I'll change it to "Must be 6 to 256 characters" when I make the other small changes.

**Comment by sloria** [comment]
@caileyfitz Some of the mobile-related issues will likely be sent back to the contractor. Unless there a major bugs, those cards can be deferred.

**Comment by caileyfitz** [comment]
@sloria deferred all the mobile related issue cards. Looks like everything has passed through QA now. If there are no more PRs to test, I am a go :rocket:

**Comment by GaryKriebel** [comment]
I'm a go as well.

**Comment by lbanner** [comment]
:rocket: :rocket: :rocket:

**Comment by sloria** [comment]
Language changes (https://trello.com/c/YNTaTDrD/33-language-changes) made. 

Are we a go, @JeffSpies ?

**Comment by sloria** [comment]
@JeffSpies' go given verbally.

This is now released.

**Comment by GaryKriebel** [comment]
👍🏻
