### ISSUE TITLE
Project stuck in Archiving mode

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3293]
## Steps
1. Go to a project you have admin access to on production
2. Go to the settings tab for the project
3. Enable/Configure the *all* external add-ons: S3, Box, Dataverse, Dropbox, Github, Google Drive, figshare, Mendeley, and Zotero.
4. Also, enable the external link and enter a forwarding url
5. Go to the registrations tab
6. Go through the steps to make an embargoed registration using the "Replication Recipe (Brand et al, 2013): Pre-registration" template

## Expected
I would expect the registration to be successful.  Or if not, send the user an email informing of the problem

## Actual
The registration gets stuck in the archiving state and the user does not receive any emails. I registered one other project that had almost exactly all the same add-ons with the exception of Zotero and an external link and that registration went through in only a couple of minutes. For some reason, this registration got stuck:
![screen shot 2015-06-24 at 10 20 33 am](https://cloud.githubusercontent.com/assets/5975444/8332303/31564fea-1a5b-11e5-8a49-afaaa500b9d3.png)

Additionally, this project does not even appear in my project organizer as a registration that is currently being Archived. To my knowledge, there is usually an [Archiving] tag in the project organizer for registrations for which archiving is not complete:
![screen shot 2015-06-24 at 10 23 17 am](https://cloud.githubusercontent.com/assets/5975444/8332310/38ccb7b4-1a5b-11e5-990b-b2dc3a931475.png)

BUT it does show up as a template option in the Create a Project widget:
![screen shot 2015-06-24 at 10 23 59 am](https://cloud.githubusercontent.com/assets/5975444/8332320/4da156b8-1a5b-11e5-8304-9aad43f5471f.png)

So maybe the project organizer is pulling from the wrong place? That, or the Create a Project widget is prematurely pulling from the registration list?

**Comment by caileyfitz** [comment]
Tagging @sloria. Maybe we should run the script? @samchrisinger as well

**Comment by lbanner** [comment]
Have we had other successful Registrations on Production @caileyfitz ?

**Comment by caileyfitz** [comment]
@lbanner Yes, I registered one other project that had almost exactly all the same add-ons with the exception of Zotero and an external link and that registration went through in only a couple of minutes. For some reason, only this registration got stuck.

**Comment by caileyfitz** [comment]
Two other projects with a combination of these add-ons also registered successfully.

**Comment by HarryRybacki** [comment]
@GaryKriebel @lbanner I think this was resolved in PR #3742

**Comment by lbanner** [comment]
Yes -- resolved -- Closing, and thank you.
