### ISSUE TITLE
[Production] Warning about private Figshare content appears twice if Figshare is enabled for both parent & component

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3296]
### Steps
1. Go to [osf.io](http://www.osf.io).
2. Go to one of your projects.
3. Make sure Figshare, with private content in it, is enabled.
4. Create a component.
5. Enable the same Figshare folder in the component.
6. Go back to the project overview.
7. Go through the steps to create a new registration.
8. Stop at the first warning modal about Figshare.

### Expected behavior
I expected that the modal would warn me about Figshare's content not being copied.

### Actual behavior
The modal lists Figshare twice, once for the parent project and once for the component.

![screen shot 2015-06-24 at 10 55 13 am](https://cloud.githubusercontent.com/assets/8591162/8333459/f4f9a474-1a60-11e5-8619-fe934f16e2e1.png)

**Comment by hmoco** [comment]
I can work on this

**Comment by lbanner** [comment]
Done!
