### ISSUE TITLE
[feature request] Change log of "User initiated/cancelled embargo" to "embargoed registration" for clarity

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3297]
Reported by @jinluyuan on the 0.41 Trello board: 

> # Steps
1. Create an embargoed registration for one of your projects.
2. Disapprove the embargo from the email link.
3. View the project logs.

> # Expected behavior
I expected that the logs would read "Jinlu Yuan initiated an embargoed registration...".

> # Actual behavior
The logs say "Jinlu Yuan initiated embargo of Jungle". I believe saying "an embargoed registration" would be clearer. The embargo applies not the project, but to the registration of the project.

**Comment by jinluyuan** [comment]
+1 Thanks @caileyfitz
