### ISSUE TITLE
[Production]: Admin cannot comment on a project that is configured for email notifications

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3298]
## Steps

1. Log in to osf.io
2. Navigate to a project for which you have admin permissions.
3. Go to your settings page to configure your notifications
4. Choose from the drop-down menu: "Emails"
5. Comment on the project 
6. Navigate to another project for which you have admin permissions
7. Have **another** admin on the project configure notifications this time
8. Have them choose from the drop-down menu: "Emails"
9. Try to comment on the project 

## Expected behavior:

I expect to be able to comment on any project for which I have admin or read-write permissions.

## Actual behavior:

When I comment on a project for which I am an admin in the second situation (another admin configured notifications), I have a 500 error in the console and a growl box appears that reads "Could not submit comment." If that same admin configures notifications to be  "Email Digest" or "None," then I can comment. It's only when comments are configured for "Emails" that I cannot comment. In the screenshot below, I could not comment back to Cailey because she configured notifications for "Emails." She could comment because she did the configuring herself. When I am the one to configure notifications for "Emails," then I can comment.

## Screenshot:

![commentissue](https://cloud.githubusercontent.com/assets/7093086/8331821/57845a66-1a58-11e5-8bc8-d3ee7b372c06.png)

**Comment by lbanner** [comment]
Interesting bug .... @samanehsan ?

**Comment by samanehsan** [comment]
Looks to be a bug in inheriting the `notify_base.mako` template. Reassigning to @samchrisinger, since he worked on this last.

**Comment by samchrisinger** [comment]
Resolved in https://github.com/CenterForOpenScience/osf.io/pull/3329
