### ISSUE TITLE
[Production] Grammatical & spelling mistakes in private registration's "Make Public" warning modal

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3300]
### Steps
1. Go to [osf.io](http://www.osf.io)
2. Go to one of your projects that has a private/embargoed registration
3. Go to that registration's overview page
4. Click the "Make Public" button 
5. Read the modal

![screen shot 2015-06-24 at 10 57 03 am](https://cloud.githubusercontent.com/assets/8591162/8334067/f288b934-1a63-11e5-80e3-4f5a5fa403a5.png)

### There are also a few stylistic issues.
1. The message should be written to the same person. The second sentence says *"Users should assume that..."*, but then the second sentence says *"...you will not be able to..."*. Either use *"the user"* both times or *"you"* both times.
2. The first sentence states, *"... there is no way to guarantee that access to the data it contains can be completely prevented"*. This seems to suggests that there is some way to partially prevent access to data. Also, *"the data it contains"* could be shortened to *"its data"* to be more concise.
3. I suggest that the modal simply state, "**Once you make this registration public, you will not be able to make it private again.** However, you may later retract the public registration, only leaving behind a record of its existence and basic metadata related to the project and its contributors." This is the clearest way of getting the message across to the user.

(Just suggestions to make the message more straightforward. This is potentially the most significant action a user can take!)

**Comment by sloria** [comment]
Good catches. Will fix those now.

**Comment by sloria** [comment]
Here is the updated text:

![osf___test_comp](https://cloud.githubusercontent.com/assets/2379650/8334845/0f92287c-1a68-11e5-90e3-6289913bf51e.png)

@bnosek Feel free to suggest any further changes.

**Comment by bnosek** [comment]
First sentence doesn't make sense because obviously making something public
means that the data is accessible.


"Once a registration is made public, you will not be able to make the
registration private again.  After making the registration public, if you
discover material in it that should have remained private, your only option
will be to retract the registration.  This will eliminate the registration,
leaving only basic information of the project title, description, and
contributors with a notice of retraction."

**Comment by sloria** [comment]
Thanks @bnosek , I will make that change.

The first sentence also appears in the modal that appears when making a project public:

![osf___new_addons](https://cloud.githubusercontent.com/assets/2379650/8356096/2bba1ac8-1b21-11e5-8dbf-55a35acfebef.png)


The intention was to make clear that once a project is made public, search engines and crawlers may index the data, which would make the data publicly available even if the project is made private again. 

Do any changes need to be made to this modal as well?

**Comment by bnosek** [comment]
Good catch.  How about we simplify a bit and be more direct:

"Once a project is made public, you should assume that it will always be
public.  You can return it to private later, but search engines or others
may access the files before you do so.  Please review your project for
sensitive or restricted information before making it public.  Are you sure
you would like to continue?"

**Comment by sloria** [comment]
Sounds good. Will make that change as well.
