### ISSUE TITLE
No results when searching for user with same name as contributor on a project

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3302]
# Steps
1. Go to a project on which you have admin access on production
2. Go to the Sharing tab
3. Press Add to add a contributor
4. In the modal, search for *Casey Rollins*
5. Confirm that three users appear
![screen shot 2015-06-24 at 11 36 32 am](https://cloud.githubusercontent.com/assets/5975444/8334687/38fd2a00-1a67-11e5-84f0-cd20dbc8ac9a.png)
6. Select the account for Casey with the pink avatar and add to project to exit the modal
![screen shot 2015-06-24 at 11 51 33 am](https://cloud.githubusercontent.com/assets/5975444/8334722/69ad1dcc-1a67-11e5-881d-9426864852a6.png)
7. On the Sharing tab, after confirming that Casey is now a contributor, click the **x** to remove her from the project
![screen shot 2015-06-24 at 11 51 43 am](https://cloud.githubusercontent.com/assets/5975444/8334726/6f2e5e96-1a67-11e5-9a27-974a6411f429.png)
8. Confirm that Casey is now removed as a contributor
9. Press Add to add another contributor
10. Search for *Casey Rollins*
11. Again, confirm that three users appear
12. Select the account for Casey with the picture (as avatar) and add to project to exit the modal
![screen shot 2015-06-24 at 11 36 45 am](https://cloud.githubusercontent.com/assets/5975444/8334748/911dc6c2-1a67-11e5-897b-60492a98be22.png)
13. Confirm that Casey with the picture avatar is added as a contributor to the project 
![screen shot 2015-06-24 at 11 36 53 am](https://cloud.githubusercontent.com/assets/5975444/8334786/cdc1920c-1a67-11e5-8284-ad60d5dac57d.png)
14. On the Sharing tab, press Add again to add another contributor
15. Press *recent collaborators* and confirm that Casey with the pink avatar appears in this list
![screen shot 2015-06-24 at 11 37 24 am](https://cloud.githubusercontent.com/assets/5975444/8334790/d4822c00-1a67-11e5-9442-64857e3fc0ca.png)
16. Now, search for *Casey Rollins*

# Expected
I expect that the other two Casey Rollins accounts (pink avatar and green avatar) would appear in the search results, since neither of those accounts are added as contributors on the project.

# Actual
No search results appear when searching for *Casey Rollins*:
![screen shot 2015-06-24 at 11 37 33 am](https://cloud.githubusercontent.com/assets/5975444/8334855/22210e18-1a68-11e5-87fb-5f9893869f00.png)

I am guessing that this is because we omit search results for users who are already contributors on the project, and it seems like maybe we are only indexing those results by name and not by user id? This can become problematic if we have two distinct users with the same name that want to be added to the same project. As current functionality stands, this is not possible via contributor search.

**Comment by Johnetordoff** [comment]
I got this.

**Comment by lbanner** [comment]
Thanks

**Comment by sloria** [comment]
Fixed by https://github.com/CenterForOpenScience/osf.io/commit/a05f0aca6cbcf25b8301f039e022c1f770cd0eb5
