### ISSUE TITLE
Make API 401 instead of 403ing during unauthorized requests

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3310]
Steps
-------
While logged out of the OSF, try to perform an action that requires authorization.

Expected
-------------
You would receive a 401 error.

Actual
--------
You receive a 403.

The reason this is happening right now is because unit tests (and runscope tests) currently require basic authorization, but I don't want basic auth to be used by users as it is not super secure. However, when using the DRF docs, receiving a 401 prompts a Basic Auth login prompt from the DRF, which encourages users to use that.

So, the ultimate task is to return a 401 without prompting a user to log in with Basic auth. How this happens isn't really super-important to me, but options are:

1) Create a custom error handler that returns a 401 but does not invoke the basic login prompt (@sloria is not a fan of this method last I proposed it);
2) Modify what happens for logins so that it prefers to take you to the OSF CAS login page rather than using basic auth as the preferred login method;
3) Make all of the unit tests and runscope no longer need basic auth, so that we can entirely disable it from the authorization methods (probably not feasible);
4) Something else that I haven't thought of.

Once all of the 403s are fixed, be sure to fix all of the tests. Really, fix the tests first, then fix the code, because that's a much better way to do this.

**Comment by sloria** [comment]
> Create a custom error handler that returns a 401 but does not invoke the basic login prompt (@sloria is not a fan

I am not opposed to a custom error handler; I was opposed to sending the wrong error code (403). See https://github.com/CenterForOpenScience/osf.io/pull/3156#discussion_r33174879. If you can somehow use a custom error handler to prevent the dialog while browsing the API docs (while still supporting basic auth for other clients), go for it.

**Comment by brianjgeiger** [comment]
Ah, I see. I typed a 403 when I meant 401 in that thread. This is how wars get started. :)
