### ISSUE TITLE
"OSF" is an initialism and should be preceded by "the" when used as a noun

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3312]
We have inconsistent usage of "the" throughout the OSF site and related materials. Since the OSF is an initialism, meaning you pronounce each letter, it always needs to have "the" (or another article) in front of it when it is used as a noun (e.g., the FBI, an IUD, the DVD, a VCR, the SAT). This issue is most apparent when reading through the FAQs page, attached. I also read through Getting Started, and there were no problems there.

Please reference [this site](http://www.dailywritingtips.com/initialisms-and-acronyms/) for a more detailed explanation.

![screen shot 2015-06-24 at 3 35 05 pm](https://cloud.githubusercontent.com/assets/8591162/8339673/2b6cc060-1a87-11e5-968f-ec35fdb6323e.png)

**Comment by MPNussbaum** [comment]
@lbanner Should I take care of this or will it be trashed in the upcoming redesign?

**Comment by lbanner** [comment]
You can update the FAQ page -- that'd be good!
