### ISSUE TITLE
Ensure API tests are tearing down properly

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3314]
When going through the test code, it looks like Node Filtering tests have a teardown method that removes all the nodes. Most of the other test cases have nothing at all, though there is one test class that has the node removal code at the end of the last case of that test.

This task is to see if the Node.remove() code is necessary and, if so, put it in the appropriate places for existing tests (which likely should be in the teardown method), and definitely to remove it from the one time it's just hanging out at the end of a test case. If it's not necessary anywhere, then we should remove it from the node filtering tests.

**Comment by PatrickEGorman** [comment]
I'd be interested in working on this

**Comment by lbanner** [comment]
OK -- will assign. You can check in with @brianjgeiger as needed ... he'll be checking messages even while away. Thanks.

**Comment by PatrickEGorman** [comment]
@brianjgeiger Says I should talk to Jeff.

**Comment by lbanner** [comment]
OK
