### ISSUE TITLE
[Production]: Fix language in Getting Started page Links Explanation

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3315]
## Steps

1. Log in to osf.io.
2. Click on the "help" drop-down menu at the top of the screen and select "Getting started."
3. Go to the "structure" heading on the left hand side of the screen and click on the subheading "links."
4. Read the first sentence in the third paragraph.

## Current:

"A link can **created be** by visiting the project you want to add the link to."

## Change to:

"A link can **be created** by visiting the project you want to add the link to."

## Screenshot

![grammarproblem](https://cloud.githubusercontent.com/assets/7093086/8340682/11e4dbc6-1a8e-11e5-905d-9355e1d70177.png)

**Comment by XTech2K** [comment]
Making a hotfix for this now.

Also changes another grammatical error from the same section, "persons's work" to "person's work"

**Comment by lbanner** [comment]
Good!
