### ISSUE TITLE
[Staging and Production] Comment buttons cut-off at bottom of screen

### ISSUE THREAD

**Issue by WillBanner** [CenterForOpenScience/osf.io#3319]
# Steps 
1. Go to osf.io and log in.
2. Go to one of your projects.
3. Click on the comment box in the upper right-hand corner.
4. Create a comment.
5. Reply to the comment using the arrow at the bottom right of the comment you just made.
6. Repeat step number 5, 5-6 times or more if necessary to each subsequent comment.

# Expected
The "save" and "cancel" buttons would continue to display above the bottom of the window.

# Actual
Buttons are cut in half by the bottom of the window so that you must already know what the buttons are/ say in order to use them. Eventually you get to the point where you can't reply to the comment at all (image 3).

*Changing the size of the window/going into full screen doesn't matter, you are still unable to scroll down any further.
* The images display to the bottom edge of the window.

![image](https://cloud.githubusercontent.com/assets/12799635/8341590/cb6014ee-1a93-11e5-97af-5bb80c4b27e2.png)

![image](https://cloud.githubusercontent.com/assets/12799635/8341593/d3bb965e-1a93-11e5-8d09-0058eab2b5e0.png)

![image](https://cloud.githubusercontent.com/assets/12799635/8341780/3f58d6e6-1a95-11e5-9c59-fb2567b52526.png)

**Comment by lbanner** [comment]
@WillBanner -- Good catch. This bug is meant to be resolved with PR #2534 -- updated commenting functionality. Hope to get this to Production within this Epic.

**Comment by samanehsan** [comment]
This issue is fixed on production now!
