### ISSUE TITLE
Revoking API access through addon OAuth providers not handled gracefully

### ISSUE THREAD

**Issue by lyndsysimon** [CenterForOpenScience/osf.io#332]
### Notes

This issue was originally only for Github - but this could be a problem with all addons that use OAuth.

### Steps to reproduce

1. Add a Github addon to a new project, and connect it to a repo on your Github account
1. On the Github account settings page, revoke access for the OSF

### Impact

Once access has been revoked, hGrid will fail to populate on the project's dashboard for non-contributors (the AJAX call gets a 500). Contributors will be unable to load the dashboard at all, but will instead get an "Unknown Error" page.

### TODO
Handle all other addons that exhibit this behavior: 

- [x] Amazon S3
- [x] Dropbox
- [x] Figshare

**Comment by samanehsan** [comment]
@chennan47, this is now handled for every addon right?

**Comment by chennan47** [comment]
It is covered for all the addons which use the new oauth system.

**Comment by samanehsan** [comment]
Ok, in that case I will go ahead and close this issue.
