### ISSUE TITLE
[Production] Files View Page file tree not sorting

### ISSUE THREAD

**Issue by icereval** [CenterForOpenScience/osf.io#3324]
# Steps 
1. Go to staging.osf.io and log in.
2. Create a new project.
3. Upload files in this specific order: x.txt, y.txt and z.txt
4. Upload files in this specific order: c.txt, b.txt and a.txt
5. Click on b.txt to navigate to the file view page
6. The left file view tree does not properly sort the files by name.

# Expected
File names would show up in alphabetical order, e.g. a.txt, b.txt, c.txt, x.txt, y.txt, z.txt

# Actual
Files show up in the order they were uploaded.

![image](https://cloud.githubusercontent.com/assets/3111541/8356059/e67a923a-1b20-11e5-8ab0-0bec70ece218.png)

**Comment by hmoco** [comment]
@GaryKriebel  I can work on this

**Comment by lbanner** [comment]
@icereval ... suspect this to be a regression?

**Comment by icereval** [comment]
I don't believe so, it's been happening for some time on all environments.

**Comment by lbanner** [comment]
OK

**Comment by hmoco** [comment]
This is fixed in the referenced pr.
