### ISSUE TITLE
Onboarder's Create Project Broken

### ISSUE THREAD

**Issue by samchrisinger** [CenterForOpenScience/osf.io#3328]
![screen shot 2015-06-25 at 11 00 51 am](https://cloud.githubusercontent.com/assets/2207561/8357570/7f8871ce-1b29-11e5-95d4-f94f1b35fea2.png)
![screen shot 2015-06-25 at 11 00 59 am](https://cloud.githubusercontent.com/assets/2207561/8357569/7f8551b0-1b29-11e5-8ff7-00f9cdadc264.png)

# Expected
A new project gets created and I'm redirected to that project

# Actual
Clicking the create button causes the button to become disabled and nothing happens (no user-facing error message).

**Comment by lbanner** [comment]
@sloria ?

**Comment by GaryKriebel** [comment]
@nanchen47 can you look at this?  We'll want this fixed asap with the science articles coming out today.

**Comment by sloria** [comment]
Regression was introduced by this hotfix: https://github.com/CenterForOpenScience/osf.io/pull/3208. @chennan47 Any ideas?

**Comment by chennan47** [comment]
Just talked with @sloria. This should now be fixed.
