### ISSUE TITLE
Dashboard buttons fail to restore after canceling search

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3341]
## Summary
The project dashboard toolbar has four buttons (add collection, add project, search, and info)

If the user clicks "search", then "cancel", there will only be two buttons. The "add collection" and "add project" buttons are not restored.

Seen in Firefox and Chrome.

## Steps to reproduce
1. Go to the project dashboard
2. Click "Search" on the toolbar above the project organizer.
3. Click "x" to cancel the search.
4. Count the buttons

## Expected result
After canceling the search action, the toolbar would restore to its original state with the same 4 choices

## Actual result
The toolbar only shows search and info after cancel.
![screenshot 2015-06-25 17 03 10](https://cloud.githubusercontent.com/assets/9381062/8365621/4f3c6420-1b5c-11e5-8bd9-1d51727d5674.png)
![screenshot 2015-06-25 17 03 22](https://cloud.githubusercontent.com/assets/9381062/8365626/57133336-1b5c-11e5-9f3d-aadc4db25cd2.png)
![screenshot 2015-06-25 17 03 29](https://cloud.githubusercontent.com/assets/9381062/8365627/594e4d66-1b5c-11e5-9c9a-09a637ebda40.png)

Reported on the 0.36 release trello board by @abought

**Comment by haoyuchen1992** [comment]
I can work on this one. Thanks!
