### ISSUE TITLE
Link back to the homepage of each project OSF integrates with (Dropbox, Github, Dataverse, etc.)

### ISSUE THREAD

**Issue by pdurbin** [CenterForOpenScience/osf.io#3345]
I **love** the [fancy new](https://groups.google.com/forum/#!topic/openscienceframework/TJixx-R3UkU) https://osf.io homepage*!

It would be kind of awesome if all these images (Dropbox, Github, Dataverse, etc.) linked back to the homepage of each project. Here's where this is in the code:

https://github.com/CenterForOpenScience/osf.io/commit/b9de67f6b46dc661863bfe8883976caec0795e6a#commitcomment-11869545

\* p.s. The animation is neat but it would be nice if hitting the Esc key stopped it. :)

**Comment by GaryKriebel** [comment]
Thanks @pdurbin

**Comment by pdurbin** [comment]
@GaryKriebel you're welcome. @caneruguz encouraged me to create this issue: https://github.com/CenterForOpenScience/osf.io/commit/b9de67f6b46dc661863bfe8883976caec0795e6a#commitcomment-11869545

The new site is great.

**Comment by nanchen47** [comment]
@pdurbin Thanks very much for your suggestions. We will consider your opinion when we refine homepage. You are very welcome to provide further suggestions. Thanks again.
