### ISSUE TITLE
Show changes made in dropbox in logs

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#3351]
Question about/Request from user to log changes made in dropbox. 

Current behavior is that changes made from dropbox website or synced dropbox folder do not display in OSF logs. Changes made to dropbox content from the OSF interface do show in logs. All versions of files display on file detail page, regardless of where change was made. 

Dropbox has recently added webhooks. Would be great to utilize this functionality on the OSF.

**Comment by nanchen47** [comment]
Included in https://github.com/CenterForOpenScience/osf.io/issues/620. Close this one and keep tracking issue there.
