### ISSUE TITLE
OSF for Meetings table rows not tall enough

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3366]
<h4>Steps</h4>
1. Visit an OSF for Meetings conference page and look at one of the poster/talk rows.

<h4>Outcome</h4>
1. The download button is slightly too large for the row and the bottom gets cut off. This is especially obvious when someone has clicked the download button and there is shadow surrounding it
![screen shot 2015-06-26 at 4 35 42 pm](https://cloud.githubusercontent.com/assets/4965832/8386924/64a85564-1c22-11e5-9f94-659bd5670d6c.png)

<h4>Expected Outcome</h4>
1. The rows should be tall enough to fit all contents

**Comment by bdyetton** [comment]
@GaryKriebel I will work on this

**Comment by GaryKriebel** [comment]
:+1:

**Comment by caneruguz** [comment]
@bdyetton any update?

**Comment by bdyetton** [comment]
@caneruguz Yep closed by steve in #3391

**Comment by nanchen47** [comment]
Verified with @jlcohoon, this bug is gone.
