### ISSUE TITLE
Search Only Returns Values for the First Job or School in User Profile

### ISSUE THREAD

**Issue by billyhunt** [CenterForOpenScience/osf.io#3368]
Steps
-------
1. Go to user profile.
2.  Click Employment
3.  Create a First Employer
4.  Create a uniquely named second Employer, for example, "Pizza Snack Bread Shack"
5.  Search for "Pizza Snack Bread Shack" on the osf

Expected
------------

You would find the person who worked at the Pizza Snack Bread Shack

Actual
--------

You do not find the person who worked at the Pizza Snack Bread Shack

**Comment by lbanner** [comment]
@brandonPurvis -- maybe you can look at this one in regards to search?

**Comment by XTech2K** [comment]
I remember working on both search and user jobs last year, and I can tell you that the problem here is specifically with the user doc portion of website/search/elastic_search.py.

Also, I remember that this was done purposefully, though I cannot remember why, but it also applies to contributor searches.

Finally, when someone fixes this, they will also need to fix it for schools, since it doesn't make sense to only be able to search previous jobs but not previous schools.

**Comment by billyhunt** [comment]
That's good information.  @XTech2K, do you remember someone else who might know the use case that searching all jobs and schools might cause a problem?  I can't think of what it might be.

**Comment by brandonPurvis** [comment]
I can work on this. 

One reason it was done this way might have been that in search results, the employer the user ranks the highest is shown under the users name. Searching for an employer and getting results which show people who's displayed employer doesn't match the given query might be confusing.

Ensuring users who's highest ranked employer/school matches the query appear first in the results should avoid this problem.

**Comment by lbanner** [comment]
:+1:

**Comment by billyhunt** [comment]
@brandonPurvis, that sounds like a good idea.  I like you weighting the search for the first matched job or school.  Smart.  

@lbanner, Maybe I should file an issue for this other problem? (only first job shows in search results)  There is no reason to only show the first job as opposed to the matched search result.  To the user, there is no weight on which job they enter first.  They might be filling them out chronologically, oldest to newest.  Then on a search of Center for Open Science, it would still say I still worked at AOL.  :scream:
