### ISSUE TITLE
Send emails to users when they have been added as a contributor to a project

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3369]
From the community repo: https://github.com/CenterForOpenScience/community/issues/257
 
<h4>Current behavior</h4>
Presently, users who are added to a project as a contributor do not receive a notification, unless they do not already have an OSF account.

<h4>Expected behavior</h4>
Users should receive an email to notify them that they have been added to an OSF project. If a project has components, they should only receive one email. Suggested email content:

***Added to a project with no components:***
Hello "User Name A",

You have been added by "User Name B" as a contributor to project "Project Name", "Overview URL", on the Open Science Framework.

If you are erroneously being associated with "Project Name" then you may visit the project's sharing page at "Sharing URL" and remove yourself as a contributor.

Sincerely,

Open Science Framework Robot

Want more information? Visit http://osf.io/ to learn about the Open Science Framework, or http://cos.io/ for information about its supporting organization, the Center for Open Science.

Questions? Email contact@osf.io

***Added to a project with components:***
....If you are erroneously being associated with "Project Name" then you may visit the project's sharing page at "Sharing URL" and remove yourself as a contributor.

This project also has X components. To remove yourself as a contributor you must visit each component's sharing page....

**Comment by samanehsan** [comment]
I just started working on this today!

**Comment by nanchen47** [comment]
This pr has been merged and deployed on production.

**Comment by samanehsan** [comment]
@nanchen47, this PR is merged but it is still being tested and will go out in the next release.
