### ISSUE TITLE
[File view pages] Make default toggle: view [ON], revisions [OFF]

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#3371]
![screen shot 2015-06-27 at 8 22 37 am](https://cloud.githubusercontent.com/assets/1761504/8391953/ce5cea0a-1ca5-11e5-8e5c-b767280f2456.png)

That way, focus is on most recent version which is the users primary interest, and previous versions are accessible easily with toggle.

**Comment by brianjgeiger** [comment]
+1

**Comment by haoyuchen1992** [comment]
I can work on this one. Thanks :)
