### ISSUE TITLE
reformat registrations page to give info on each registration template

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3373]
From the community repo: https://github.com/CenterForOpenScience/community/issues/264

<h4>Current Behavior</h4>
Users can select a registration template from a dropdown menu after clicking "new registration." To know what is included in a template, they must select it—there is no preview or information available ahead of time.

<h4>Suggested Behavior</h4>
Users should be provided with a brief description of each registration template (and perhaps have access to the questions ahead of time). The community team suggests that instead of using a dropdown menu to select an option, the user is presented with collapsable descriptions of each:

![screen shot 2015-06-26 at 4 08 13 pm](https://cloud.githubusercontent.com/assets/4965832/8408840/6158c558-1e41-11e5-948e-c4d61af81f41.png)

If the questions were to be provided ahead of time as well, PDFs could be linked to from those descriptions. The parenthetical text below could be muted text, shown not in parentheses.

**Suggested content for each tab:**

Open Ended: You will be asked to provide a narrative summary of what is contained in your project. There is no minimum character length. This template is not a valid submission for the Pre-registration Prize.

OSF Standard (pre-data collection): You will be asked if data collection is underway and if you have looked at your data already. You will be provided an opportunity to post other comments about your project. This template is not a valid submission for the Pre-registration Prize.

Brandt et al 2013 Replication Recipe (pre-data collection): This template is intended for use when conducting a replication. You will be asked a series of questions about the study you intend to replicate. This template is not a valid submission for the Pre-registration Prize.

Brandt et al 2013 Replication Recipe (post-data collection): This template is intended for use when conducting a replication. You will be asked a series of questions about your completed replication.  This template is not a valid submission for the Pre-registration Prize.

Pre-Registration Prize (pre-data collection):  You will be asked a series of questions to ensure that your sampling, design, and analysis plans are solidified prior to beginning your study. Publications that pre-register with this template may be eligible for a $1,000 prize. <a href="https://osf.io/x5w7h/">See project page for complete information</a>.

**Comment by samchrisinger** [comment]
I'm 100% onboard here. We will very likely implement this as part of the Prereg prize development

**Comment by lbanner** [comment]
@samchrisinger -- OK I assign this to you, so we make sure it is covered? Thanks.

**Comment by samchrisinger** [comment]
:+1:, got it

**Comment by samchrisinger** [comment]
WIP, but 
![screen shot 2015-06-30 at 1 21 57 pm](https://cloud.githubusercontent.com/assets/2207561/8437128/08cf4c32-1f2b-11e5-83e9-38cbd78c7dba.png)

**Comment by evomellor** [comment]
Sorry @jlcohoon , after seeing the pre or post data collection recommendation in this format, I think the wording (that I had approved!) is a bit misleading. Pre-reg prize can use preexisting data under certain circumstances and this format also makes it look like there is a separate post data-collection pre-reg prize template. Please revise as follows: 

Open Ended Registration Form: You will be asked to provide a narrative summary of what is contained in your project. There is no minimum character length. This template is not a valid submission for the Pre-registration Prize.

OSF Standard Pre-Data Collection: You will be asked if data collection is underway and if you have looked at your data already. You will be provided an opportunity to post other comments about your project. This template is not a valid submission for the Pre-registration Prize. 

Brandt et al 2013 Replication Recipe Pre-Data Collection: This template is intended for use when conducting a replication and should be used before collecting data. You will be asked a series of questions about the study you intend to replicate. This template is not a valid submission for the Pre-registration Prize.

Brandt et al 2013 Replication Recipe Post-Data Collection: This template is intended for use when conducting a replication and should be used after collecting data. You will be asked a series of questions about your completed replication. This template is not a valid submission for the Pre-registration Prize.

Pre-Registration Prize: You will be asked a series of questions to ensure that your sampling, design, and analysis plans are specified prior to beginning your study. Publications that pre-register with this template may be eligible for a $1,000 prize. This template can be used prior to data collection and, under certain circumstances, can be used with preexisting data. See [project page][1] for complete information.


  [1]: https://osf.io/x5w7h/wiki/home/

**Comment by evomellor** [comment]
@samchrisinger This mockup looks really good and brings the information right to the user earlier and in a clear way. Thanks for including the "Fulfills" category. We use "form" "schema" and "template" somewhat interchageably in a few different places. For consistency, let's refer to each of these as "templates." So please change the wording to "Please select a registration template to continue:"

**Comment by jlcohoon** [comment]
That's fine by me. @samchrisinger, cancel my previous comments!
