### ISSUE TITLE
"forgot password" link indicates message sent to emails that were never registered

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3374]
<h4>Steps</h4>
1. Visit the OSF while logged out
2. Click on the dropdown and click on "forgot password"
3. Enter an email address that you have never registered an account with. If you have gmail, you can test this by adding "+XYZ" to your email (eg. youraddress+XYZ@gmail.com). 

<h4>Outcome</h4>
1. The OSF gives you an alert that reads "An email with instructions on how to reset the password for the account associated with EMAIL ADDRESS has been sent. If you do not receive an email and believe you should have please contact OSF Support."

<h4>Expected Behavior</h4>
1. The alert should read: "If there is an OSF account associated with EMAIL ADDRESS, an email with instructions on how to reset the OSF password has been sent to EMAIL ADDRESS. If you do not receive an email and believe you should have, please contact OSF Support, support@osf.io."

**Comment by jinluyuan** [comment]
I believe the alert should be "If there is an OSF account associated with EMAIL ADDRESS, an email with instructions on how to reset the OSF password has been sent to EMAIL ADDRESS. If you do not receive an email and believe you should have, please contact OSF Support."

This ensures that the user will not be told whether or not there is an OSF account associated with the email address (a possible security risk that we've talked about), but at the same time, it makes no promise that there will be an email sent.

**Comment by jlcohoon** [comment]
Isn't alerting people that they entered an incorrect email address fairly standard?

**Comment by jinluyuan** [comment]
@jlcohoon That's what I thought, but we've (QA) asked the developers about this to change it. Their response was that it's a security/privacy concern.

**Comment by jlcohoon** [comment]
Thanks, @jinluyuan!
When you try to register with an already registered email, you do get an alert that it has an account already. So our behavior is inconsistent.

If we don't want to reveal immediately if there is an account registered, we should send the email a message even if it doesn't have an account. That email could say something to the effect of "you tried to reset the password for an OSF account associated with this email address, but no such account exists. To register an account click here. For assistance with your OSF account, email support@osf.io."

**Comment by jinluyuan** [comment]
@jlcohoon Good point! Your idea sounds the most straightforward.

**Comment by GaryKriebel** [comment]
the security concern is someone can keep requesting a new password for email addresses they think may be yours and then can narrow it down to addresses that were actually registered....

**Comment by jlcohoon** [comment]
Update: I talked with Jeff and the decision is to follow @jinluyuan's suggestion of just updating the alert. I'll update the original issue

**Comment by JeffSpies** [comment]
@jlcohoon, did you do that? If so, this issue should be closed.

**Comment by jlcohoon** [comment]
I did update the issue, but I don't think the message has been updated yet, so this should remain open. By original issue, I meant what I logged at the top of this thread.

**Comment by JeffSpies** [comment]
We only need one issue. You should link them and close one of them.
