### ISSUE TITLE
private project/public repo alert should be dismissible

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3375]
Submitted via the suggestion box

***Steps***
1. Link a public Github repo to a private OSF project
2. Visit your project's overview page

***Outcome***
1. The alert at the top of the page telling you that your repo is public is not dismissible
![screen shot 2015-06-29 at 10 27 00 am](https://cloud.githubusercontent.com/assets/4965832/8410100/1c712d8c-1e4a-11e5-8b76-2d70ee572a38.png)

***Expected Behavior***
1. The alert at the top of the page should be dismissible

**Comment by nanchen47** [comment]
Will be considered when refine the warning system.
