### ISSUE TITLE
Sign in and Slide-in Footer Buttons are different colors

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#3379]
The sign-in button in the nav bar and the "create account" / "learn more" buttons on the slide-in footer are not the same colors:

![screen shot 2015-06-29 at 12 31 02 pm](https://cloud.githubusercontent.com/assets/7749914/8412893/e4817ac4-1e5a-11e5-90db-57e297b5b65e.png)

I would think the slide-in footer buttons should match the new sign-in button on the nav bar.

**Comment by GaryKriebel** [comment]
not the same colors as each other or not the same colors as something else?

**Comment by lbanner** [comment]
StyleGuide insight here @caneruguz ?

**Comment by jlcohoon** [comment]
As each other. The issue, I believe, is that the "info" buttons/text are a very similar color to the logo, but are slightly different. The right class was used on the button but to resolve this we might consider customizing the info color to be the same as the logo color.

**Comment by caneruguz** [comment]
I don't think sign in and create account need to be the exact same color. The buttons below are using the right color "primary" for call to action to create account, while Learn more needs to be "info. The sign in can be a "primary" but the color will be too close to the navigation bar. We need to play with it to see what's going on there.
