### ISSUE TITLE
line breaks in the file extension

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3384]
**Steps**
1. Visit this file: https://staging.osf.io/z5hp7/
2. Adjust the window size

**Outcome**
1.  From a window width of about 1320px to 1200px, the line that the file title is on breaks in the middle of ".docx" 
![screen shot 2015-06-29 at 3 43 58 pm](https://cloud.githubusercontent.com/assets/4965832/8416886/b92f05f0-1e76-11e5-8495-087cf0d98fb0.png)

**Expected Outcome**
1. While line breaks may not be well placed in a file title all the time (who knows when a new word starts/ends if there are no spaces/dashes/underscores), we can avoid breaking in the middle of a file extension—if the space available for the file title is too long and some of the file extension needs to move to the next line, the *whole* extension should move to the next line

**Comment by PatrickEGorman** [comment]
I have a spare moment to sort this out

**Comment by lbanner** [comment]
Yours!
