### ISSUE TITLE
Renaming files does not let changes persist & more strange behavior

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3386]
### Steps
1. Go to [osf.io](http://www.osf.io).
2. Go to one of your projects.
3. In either the Files widget in the project overview page or the Files page itself, select a file or folder. 
4. Click the "Rename" button in the menu that appears.
5. Click in the middle of the file's name, either in the middle of a word or in between words.
6. Type a letter or two.
7. Click to the right of the name / the end of the text (where the cursor was before you clicked in the middle).
8. Notice how your edits change.

### Expected behavior
I expected that if I try to change the name of a file, any changes I make in the "Rename" field will persist until I click the "Rename" button, even if I click at the end of the text.

### Actual behavior
I cannot click at the end of the text without losing some or all of my edits. My old edits also reappear if I change something in the middle and then click the end again. 

Tested on Safari, Chrome, and Firefox.

**File widget, one word name example**
![rename_bug2](https://cloud.githubusercontent.com/assets/8591162/8433971/d16fc0f0-1f16-11e5-8a02-02286130d1d6.gif)

**Files page, multiple word name example**
![rename_bug](https://cloud.githubusercontent.com/assets/8591162/8433600/d017851e-1f14-11e5-9203-607db5c3ac68.gif)

**Comment by hmoco** [comment]
I am working on this

**Comment by mfraezz** [comment]
This also occurs on mouseover of other files.

![rename-bug](https://cloud.githubusercontent.com/assets/5659262/8483780/1daaffec-20c1-11e5-82b5-55b9504e4157.gif)

**Comment by hmoco** [comment]
So I have a fix for the problem mentioned in the original issue, still working on the mouseover issue.
