### ISSUE TITLE
Download as zip button does not appear for closed folders

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3388]
### Steps
1. Go to [osf.io](http://www.osf.io)
2. Go to one of your projects
3. In the files widget, create a folder in one of the storage add-ons
4. Upload some files to the folder
5. Refresh the page
6. Select the folder without opening it
7. Notice that there is no "Download as zip" button
8. Open the folder
9. Notice the "Download as zip" button appears
10. Close the folder
11. Notice the "Download as zip" button persists
12. Refresh the page
13. Notice the "Download as zip" button is no longer there for the folder

### Expected behavior
I expected that the "Download as zip" button would be available for closed folders, as it is for the overall storage add-on.

### Actual behavior
The "Download as zip" button only appears when the folder is opened.

**Closed folder**
![screen shot 2015-06-30 at 11 20 56 am](https://cloud.githubusercontent.com/assets/8591162/8434571/278eaa0c-1f1a-11e5-9abc-7401fa3ebebd.png)

**Open folder**
![screen shot 2015-06-30 at 11 21 05 am](https://cloud.githubusercontent.com/assets/8591162/8434573/2793cd70-1f1a-11e5-9c67-1133336a7468.png)

**Closed folder after opening, but without refreshing page**
![screen shot 2015-06-30 at 11 21 14 am](https://cloud.githubusercontent.com/assets/8591162/8434572/2792ea54-1f1a-11e5-903b-7619d1614d6b.png)

**Comment by bdyetton** [comment]
@GaryKriebel I will look at this, its very close to the other issue i just fixed.

**Comment by bdyetton** [comment]
@GaryKriebel @lbanner @caneruguz 
Before we give the user the option to download a folder we check if that folder is empty by looking at the number of children it has. Because we use lazy loading, all non-expanded folders do not have children, and therefore we do not get the zip download option until the user expands the folder (see above). 

A user should be able to zip download a folder no matter what, so i propose removing the check for children and then either:
-Check for children once the download has been pressed, and give an error if the folder is actually empty.
-Just let the user download empty folders. 

Thoughts?

**Comment by lbanner** [comment]
I am good with letting the user download empty folders if they chose - simple approach, and your average user will recognize the fact that a folder is, in fact, empty. Unless there is another mechanism by which to verify contents in folders?

**Comment by jinluyuan** [comment]
https://github.com/CenterForOpenScience/osf.io/issues/3018 addresses empty storage add-ons. We do not have "Download as zip" as an option for empty storage add-ons, so it would be inconsistent to have it for empty folders. However, storage add-ons are by default expanded while folders are default closed. A conundrum.

**Comment by bdyetton** [comment]
Right well im working on another issue for now/ my project. @GaryKriebel can you change this to discussion while we work this one through please.

**Comment by saradbowman** [comment]
Question about this on the help desk - "sometimes I have the option to download as a .zip, sometimes not"

**Comment by GaryKriebel** [comment]
I assume they give no details of when they see it and when they do not?
