### ISSUE TITLE
ID requested for linkedin profile does not lead to public profile

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3401]
From the community repo: https://github.com/CenterForOpenScience/community/issues/269
## Current behavior
When adding a Linkedin profile, the user is shown the beginning of a URL that they are expected to fill out with their "profile ID" (https://www.linkedin.com/profile/view?id=)

![screen shot 2015-07-01 at 9 42 16 am](https://cloud.githubusercontent.com/assets/4965832/8455840/95abd6ca-1fd5-11e5-8ac2-09b39642b386.png)

My Linkedin user ID is davidtmellor, which does not successfully complete the expected URL, it results in a 404 error on Linkedin. The correct URL that I think would complete it is: ttps://www.linkedin.com/profile/view?id=77582777 but that URL only works if the user is signed into Linkedin, a visitor to my OSF profile who clicks on that link would be prompted to sign into Linkedin before seeing my Linkefin profile. The suggest change below allows a user to access my Linkedin profile without signing up for Linkedin.

![screen shot 2015-07-01 at 9 42 38 am](https://cloud.githubusercontent.com/assets/4965832/8455846/9ef85c94-1fd5-11e5-8ef0-0f8e2756500d.png)

The public profile also shows a number (the ID) instead of their user ID, which would be slightly more welcoming: 

![screen shot 2015-07-01 at 9 42 09 am](https://cloud.githubusercontent.com/assets/4965832/8455862/b31c0630-1fd5-11e5-85f1-2734ef3efa1e.png)

## Suggested behavior
Allow the user to enter in their Linkedin ID to complete this URL: https://www.linkedin.com/in/USERID example: https://www.linkedin.com/in/davidtmellor. Show this on the public profile

OR

Allow user to enter in any URL they want for their Linkedin profile.

**Comment by billyhunt** [comment]
LinkedIn used to only link via profile ID, which is a number and requires a login.  Something like this:

https://www.linkedin.com/profile/view?id=285397262

That is what the OSF currently supports.  The new LinkedIn URL is pretty strange.  Something like 

https://www.linkedin.com/pub/erin-braswell/31/a7/481

for someone who doesn't claim a LinkedIn UserID, or 

https://www.linkedin.com/in/billyhunt

for someone who does.

I would think the simplest solution is to allow OSF users to enter any valid URL that starts with linkedin.com for their profile.  It won't break existing OSF users profile links, and will allow the other two types of LinkedIn users (ones with named URLs and without) to put the new style of URL in.  If we want a more elegant solution, we will probably have to interface with the LinkedIn API.

**Comment by lbanner** [comment]
+1

**Comment by evomellor** [comment]
+1 for the simpler solution that @billyhunt suggested. Perhaps display simply "Linkedin Profile" on user's profile page until we have a more elegant solution that would extract the person's name or Linkedin ID.

**Comment by sloria** [comment]
You are now able to input either your user ID or profile ID

**Comment by evomellor** [comment]
Thanks everyone, I've updated my ID already, it looks great!

**Comment by HarryRybacki** [comment]
Excellent @evomellor!
