### ISSUE TITLE
No clear registration option after failed login

### ISSUE THREAD

**Issue by geeksnglitter** [CenterForOpenScience/osf.io#3402]
Steps
----------------------
1. Go to either production or staging.
2. Try to log in using an email you have not used for the OSF or a wrong password.
3. Be redirected to this page:

![screen shot 2015-07-01 at 8 58 25 am](https://cloud.githubusercontent.com/assets/7839433/8455512/2fea7d3e-1fd3-11e5-8146-e858ffe078d7.png)

44. Realize that you have not registered this email and would like to make a new account. 

Expected
-----------------------
That there would be a clear way to register for an account if the wrong email/password combination is entered.
![screen shot 2015-07-01 at 9 32 05 am](https://cloud.githubusercontent.com/assets/7839433/8455623/11cfb5ac-1fd4-11e5-9818-2adba51d67da.png)

Actual
------------------
The page only gives you a "wrong password" option.

_________________
This may be something to discuss.
Github does not have this option, but they have their login and sign up buttons right next to each other. Something as simple as linking back to the registration section of the home screen could theoretically help with onboarding.

GitHub: 
![screen shot 2015-07-01 at 9 20 33 am](https://cloud.githubusercontent.com/assets/7839433/8455720/b32ae78c-1fd4-11e5-9e08-e970deed7b45.png)
Facebook:
![screen shot 2015-07-01 at 9 37 21 am](https://cloud.githubusercontent.com/assets/7839433/8455753/f19aa0fc-1fd4-11e5-94e4-125b0b10b01f.png)

**Comment by jlcohoon** [comment]
related to https://github.com/CenterForOpenScience/osf.io/issues/2469
