### ISSUE TITLE
No keyboard “Tab” key functionality in the Comments widget

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3414]
### Steps
1. Go to osf.io
2. Go to any project
3. Click the blue Comment widget icon in the top right
4. Click inside the text box
5. Type a comment
6. Press the "tab" key

### Expected behavior
I expected that pressing tab would select the "Save" button.

### Actual behavior
Pressing tab makes the cursor move into the project's Tags widget.

![screen shot 2015-07-01 at 2 58 30 pm](https://cloud.githubusercontent.com/assets/8591162/8462472/29c85028-2002-11e5-8a9e-98f1dcde7309.png)

**Comment by GaryKriebel** [comment]
Comments are about to get an overhaul.  Perhaps @samanehsan can check if this is handled in the new system.

**Comment by nanchen47** [comment]
Will be considered based on user's feed back on the new comment panel when it's on production. Thanks.
