### ISSUE TITLE
Long email address breaks "Remove Email?" modal

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3418]
### Steps
1. Go to osf.io
2. Go to your Account Settings page
3. Below the Unconfirmed Emails, enter a long email address of > 100 characters long
4. Click on Add Email button
5. Click on the X mark at the end of the email address

### Expected behavior
I expected that the email address would wrap inside the modal

### Actual behavior
The email address breaks across the modal.

![screen shot 2015-07-01 at 3 22 38 pm](https://cloud.githubusercontent.com/assets/8591162/8463006/87c4dcf2-2005-11e5-95b4-887075404ddd.png)

**Comment by revanthkolli** [comment]
Is this still an issue? If so can I work on it?

**Comment by lbanner** [comment]
@revanthkolli Can you replicate it? If so, yes, all yours -- I will assign -- Make a note if it does not replicate on Production.

**Comment by revanthkolli** [comment]
@lbanner Yeah I was able to replicate it.
