### ISSUE TITLE
Unhelpful error message when trying to configure Amazon S-3 without entering credentials

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3420]
## Steps
1. Go to osf.io
2. Go to account settings and click on configure add-ons
3. Select Amazon S3 and click on 'Create access token'
4. Without putting in the credentials, click submit.
5. Now go to one of your projects for which you are admin
6. Configure Amazon S3 but do not put in the credentials and hit submit.

## Expected
An error message both times that informs the user that the credentials must be put in to configure the add-on

## Actual
Unhelpful error messages both times
Account settings: “Error: Settings not updated.”
Project settings: "Could not add S3 credentials at this time. Please refresh the page. If the problem persists, email support@osf.io."

**Comment by haoyuchen1992** [comment]
I can work on it!
