### ISSUE TITLE
Registration page's link to "this project" leads to unhelpful error page

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3421]
### Steps
1. Go to osf.io
2. Create a new project
3. Register your new project
4. Go to the registration once it has finished archiving
5. Click the "this project" link in the blue box at the top. You should be taken to the project you created. 
6. Go to the project's Settings page
7. Delete the project
8. Go to your Dashboard
9. Click on the registration of the project you just deleted
10. Click the "this project" link in the blue box at the top.

### Expected behavior
I expected that clicking the link would take me to a page that more clearly said "This project has been deleted".

### Actual behavior
Clicking "this project" takes me to a page that says "Resource deleted". This is not as clear as saying "This project has been deleted".

![screen shot 2015-07-01 at 3 52 44 pm](https://cloud.githubusercontent.com/assets/8591162/8463552/3cf63938-2009-11e5-9736-1fc2d4280e03.png)

**Comment by Johnetordoff** [comment]
I got this

**Comment by lyndsysimon** [comment]
The message on that page is purposefully vague, as exposing the type of object that was deleted might not be a good thing.

For example - a user who requests that their account be deleted would probably not want the page where there account was to say that the ID once belonged to a user at all.

A spurious, meaningless registration that was created in error due to a bug might be deleted as well, and we certainly don't want to have a page that says "Registration Deleted" - even though that might have happened in fact, we don't want to give the appearance that regisrations *can* be deleted.

I would prefer that the language remain as it is. If changes for clarity are desired, I'm all for it, but I would be opposed to providing additional information about the resource that once resided at that page.

**Comment by lbanner** [comment]
@lyndsysimon ... is "resource deleted" the generic/standard term for all objects that are removed, and whose links are no longer valid? i.e. go to no existent resource?

**Comment by Johnetordoff** [comment]
Would it be beneficial to have a specific resource message, but not use the word "deleted"? Maybe "Project is missing" or "Project has been removed" or something more ambiguous?

**Comment by sloria** [comment]
@lbanner My suggestion in @Johnetordoff 's PR was to make the message default to "This resource has been deleted" but make it configurable. In most cases, we should stick with the default, but we can override it in the case of deleted projects.

As a sidenote, I don't believe this issue has anything to do with registrations at all--whether you click a link to a deleted project from a registration or just type the URL in your browser, you should see "This project has been deleted".

**Comment by lyndsysimon** [comment]
@sloria

I agree that registrations wouldn't be impacted by this change, or the associated PR. My point in bringing that up is to illustrate why I believe the text was generic when it was written. I seem to recall explicitly deciding to not provide any information about the resource that had been removed.

@lbanner 

The word "resource" is used in [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.5.9), where the status code (410 GONE) is defined.

> The 410 (Gone) status code indicates that access to the target resource is no longer available at the origin server and that this condition is likely to be permanent.

-

> The 410 response is primarily intended to assist the task of web maintenance by notifying the recipient that the resource is intentionally unavailable and that the server owners desire that remote links to that resource be removed.

I have no strong feeling at all about what word is used there - only that whatever it is, it should be be specific to the type of "thing" that was there.

To be precise, I don't strongly feel that we *shouldn't* say whether it was a project, component, user, or whatever. My concern is only that I recall a decision being explicitly made in the past not to do so, and that if we reverse that decision we should be aware that we're doing it and consider any possible ramifications.

**Comment by sloria** [comment]
Thanks for the clarification, Lyndsy. I was not aware of an explicit decision to omit resource names from the GONE error pages. If that's still the case, then this issue can be closed. If not, we'll move forward with the PR.

Pinging @lbanner @GaryKriebel for more info on this.

**Comment by Johnetordoff** [comment]
@sloria should we close this one, or is there a work around?

**Comment by lbanner** [comment]
My sense = simpler (and more conservative re: possibly prior concerns) solution is to leave as is, noting "resource" -- So I'll close this for now.
