### ISSUE TITLE
Project settings does not accept external link with FTP protocol

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3425]
## Steps
1. Go to osf.io 
2. Go to a project with admin access
3. Go to Settings
4. Select "External link" and hit submit.
5. Under "Configure Add-ons", enter the following URL in the URL field:  ftp://testinsane.com

## Expected
The project would be successfully linked to the above url

## Actual
Does not allow to enter the ftp url
![email_field_invalid_settings](https://cloud.githubusercontent.com/assets/10926926/8464334/52b0f50a-200f-11e5-8894-70b19ba2774d.png)

**Comment by GaryKriebel** [comment]
Closed
