### ISSUE TITLE
Password reset is missing client-side data validation 

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3428]
### Steps
1. Go to osf.io
2. Go to your Account Settings
3. Without filling in any of the boxes, click "Update Password"

### Expected behavior
I expected red text to appear above the button warning me that the fields are blank.

### Actual behavior
There is an unnecessary server side call for validation as the page reloads.

**Comment by revanthkolli** [comment]
@lbanner Can I work on this?

**Comment by lbanner** [comment]
OK
