### ISSUE TITLE
Youtube frame overlaps the nav bar when scrolling down in the Getting Started Page on IE

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3429]
# Steps
1. Open up IE
2. Go to the Getting Started page
3. Click to play one of the youtube videos 
4. Pause it after a couple of seconds
5. Scroll down the page

# Expected
The page would scroll normally with no overlaps

# Actual
The video player frame overlaps the OSF nav bar. This only occurs on IE-10 and only with the videos that are played.
 
![image](https://cloud.githubusercontent.com/assets/10926926/8478735/403b5d74-20a1-11e5-9cb9-9d0b93cbe8f7.png)

**Comment by caneruguz** [comment]
@wisherp can you specify IE version?

**Comment by wisherp** [comment]
@caneruguz This is happening on IE 10

**Comment by caneruguz** [comment]
@wisherp I can't replicate this issue can you try again?

**Comment by wisherp** [comment]
@caneruguz I am still seeing this on IE 10 through UVA Hive. It seems to work fine on every other browser so it might be an issue with the Hive rather than the OSF.

**Comment by lbanner** [comment]
Let's go with that for now :smiling_imp:  -- closing. TY!
