### ISSUE TITLE
Long project names extend boundary in User settings Authorized project list for S3

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3430]
## Steps
1. Go to osf.io and log in
2. Go to a project you have admin access on
3. Edit the name of the project to be the maximum number of characters (200)
4. Go to the project settings page
5. Configure the S3 add-on for the project
6. Go to the user settings page; configure add-ons
7. Scroll down to see S3's authorized projects

## Expected
The long project name would not break out of the area for listing projects authorized for the S3 add-on
Other add-ons keep the project name contained within the boundary and have a scroll bar
![screenshot 2015-07-02 10 11 38](https://cloud.githubusercontent.com/assets/9381062/8478985/c1822f74-20a2-11e5-80e7-6595b58561d6.png)

## Actual
The project name extends past the boundary
![screenshot 2015-07-02 10 05 19](https://cloud.githubusercontent.com/assets/9381062/8478959/a059aaa2-20a2-11e5-8f28-4f0f9b68830b.png)

**Comment by Johnetordoff** [comment]
Do you think it would be better to extend the boundary or go with a character display limit and ellipsis?

**Comment by MPNussbaum** [comment]
It seems that this issue has been fixed by someone else.

**Comment by nicipfeiffer** [comment]
@lbanner @GaryKriebel @MPNussbaum This issue was fixed with the style guide changes in release 0.42 :grinning: by this PR https://github.com/CenterForOpenScience/osf.io/pull/3553

**Comment by GaryKriebel** [comment]
closing the issue
