### ISSUE TITLE
Email address length (Example: 64 characters) makes the message cross visual boundary

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3431]
# Steps
1. Go to Home page osf.io.
2. Enter the name in the Sign up form.
3. Enter an e-mail address with 64 characters.
4. Re-enter the same e-mail address in "Confirm Email" field. 
5. Click on Sign up button.

# Expected
The account will be successfully created and the success message will be displayed in the box below the sign up form.

# Actual
The confirmation message crosses the visual boundary of the UI layout

![image](https://cloud.githubusercontent.com/assets/10926926/8479790/f8c9e30a-20a7-11e5-9f4c-de2889585bf0.png)

**Comment by hmoco** [comment]
This has been fixed with the new layout, and should be closed @lbanner 
![screen shot 2015-07-14 at 11 40 04 am](https://cloud.githubusercontent.com/assets/6268982/8677458/22c12bb8-2a1d-11e5-8d34-0f5a96eae60e.png)

**Comment by lbanner** [comment]
Cool - Thanks.
