### ISSUE TITLE
S3 log in credentials give 400 error

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3432]
## Steps
1. Log in to osf.io
2. Go to the user settings page
3. Go to configure add-ons; enable S3
4. Enter the access key and secret key and Submit

## Expected
The credentials would be successfully submitted and the S3 add-on configured 

## Actual
A 400 error in the console and 'Error: Could not access IAM. Please allow these keys permission' seen in the widget.
![screenshot 2015-07-02 11 11 26](https://cloud.githubusercontent.com/assets/9381062/8480347/1c6a7128-20ab-11e5-9684-13d9b7193095.png)

**The same credentials work on staging.**

**Comment by lbanner** [comment]
Could this be an issue with S3? ..... we've had no changes made here right @sloria ?

**Comment by HarryRybacki** [comment]
Has someone logged into the respective AWS account and made any changes since Tuesday?

**Comment by nicipfeiffer** [comment]
@lbanner this issue has been resolved.  The old credentials were deleted, but @icereval has generated new ones.

**Comment by lbanner** [comment]
Cool!
