### ISSUE TITLE
“Unconfirmed Emails” accepts Invalid email addresses.

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3435]
# Steps
1. Log into osf.io and go to User Settings
2. Click on Account settings
3. Below Unconfirmed Emails, enter any random character in the format of an email address.
4. Click 'Add Email'

# Expected
Error message will be displayed saying that the email address is invalid

# Actual
It accepts any invalid email address and shows the confirmation message about the confirmation. Email is sent to the invalid email address entered.

![image](https://cloud.githubusercontent.com/assets/10926926/8483978/bc0766d4-20c2-11e5-8589-b8dfdd670ed2.png)

**Comment by revanthkolli** [comment]
@lbanner Can I work on this?

**Comment by chennan47** [comment]
@revanthkolli I already work on this one. Sry.
