### ISSUE TITLE
[Production&Staging] Print pdf doesn't work in file rendering

### ISSUE THREAD

**Issue by haoyuchen1992** [CenterForOpenScience/osf.io#3440]
### Steps:
1. open a pdf file in osf
2. click print button on the right upper corner

### Expected:
Give me a printing page
 
### Actual
Nothing happens. And notice there is warning message in console
![screen shot 2015-07-02 at 4 17 52 pm](https://cloud.githubusercontent.com/assets/5420789/8486948/a0d39a22-20d6-11e5-8aa7-94e18031f279.png)

**Comment by lbanner** [comment]
@icereval ... this a piece of MFR?

**Comment by icereval** [comment]
The makers of pdf.js have provided a shim to enable a non-mozilla browser the ability to print. This is now included in the MFR [0.2.11 hotfix](https://github.com/CenterForOpenScience/modular-file-renderer/releases/tag/0.2.11).
