### ISSUE TITLE
Folder names not italicized in log when deleted

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3454]
## Steps

1. Log in to osf.io.
2. Navigate to a project for which you have admin access.
3. Create a folder in OSF Storage.
4. Delete the folder.
5. Look at your project's log.

## Expected Behavior

I expect the folder name to be italicized in the log.

## Actual Behavior

When I create the folder, the name of the folder is italicized in the log. However, when I delete the folder, the name of the folder is not italicized in the log. Consistency would improve the user experience.

## Screenshots

![logitalics](https://cloud.githubusercontent.com/assets/7093086/8530964/2c1e7002-23f2-11e5-834b-5d10b7b15004.png)

![italics](https://cloud.githubusercontent.com/assets/7093086/8530965/2e66f03c-23f2-11e5-868e-2892a1e11d9f.png)

**Comment by geeksnglitter** [comment]
@lbanner Can I fix this?

**Comment by geeksnglitter** [comment]
Actually - this might be something to discuss. When all different types of objects are removed from logs, they are all presented in plain text. Should this be changed for all types (components, files etc.)? Or should this be left as is?

**Comment by lbanner** [comment]
Yes, @geeksnglitter -- Maybe this is a StyleGuide / consistency question? I will tag w/"Discuss"
