### ISSUE TITLE
"Search" is missing from nav bar in small windows and mobile

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3461]
### Steps
1. Go to [osf.io](http://www.osf.io) in either a small window or on mobile
2. Log in
3. Click the navigation menu button

### Expected behavior
I expected there to be a "Search" link or a magnifying glass icon when I opened the navigation menu.

### Actual behavior
There is no "Search" option.

![screen shot 2015-07-07 at 8 37 54 am](https://cloud.githubusercontent.com/assets/8591162/8546775/5c27b150-2488-11e5-9a27-de2eceb7f49d.png)

**Comment by GaryKriebel** [comment]
@haoyuchen1992 .... in between responding to QA for the style guide updates, is this something you can give a look?

**Comment by haoyuchen1992** [comment]
@GaryKriebel  Sorry for late reply. I will look at it now!

**Comment by GaryKriebel** [comment]
no worries ... QA has you busy, I'm sure

**Comment by haoyuchen1992** [comment]
@caneruguz fix it!
