### ISSUE TITLE
Selected page in paginator shows through OSF banner

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#3478]
Steps
=====
1. Make sure you are logged out of the OSF
2. Visit a public project with enough log activity so that the paginator shows up (e.g. RP:CB: https://osf.io/e81xl/) 
3. Scroll so that the "Start Managing Your Projects on the OSF" banner at the bottom is above the paginator

Expected
=========
I should not be able to see anything "behind" the banner. 

Actual
=====
On both staging and production, the selected page in the paginator shows through. 

Here's what the paginator looks like: 
![screen shot 2015-07-08 at 9 58 27 am](https://cloud.githubusercontent.com/assets/6414394/8572191/fe0d7006-2558-11e5-88e8-a132c3ff1ccb.png)

When you scroll up, it overlaps/shows through: 
![screen shot 2015-07-08 at 9 58 46 am](https://cloud.githubusercontent.com/assets/6414394/8572180/efd6d860-2558-11e5-8e5e-d0ef86055d84.png)

![screen shot 2015-07-08 at 9 59 00 am](https://cloud.githubusercontent.com/assets/6414394/8572184/f2a5498c-2558-11e5-9b8e-bf7a149374f1.png)

**Comment by caneruguz** [comment]
Is this not the same as #3696 ? Admittedly this was first so the other one was a replica. 
The fix is merged though so this should be closed. @sloria @lbanner

**Comment by lbanner** [comment]
OK
