### ISSUE TITLE
[Firefox] Sign-in username field is off the page in small windows

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3480]
### Steps
1. Go to [osf.io](http://www.osf.io) in Firefox as a logged out user.
2. Make the window smaller until the top navigation bar is reduced to just the "menu" icon.
3. Click the menu icon.
4. Notice the formatting of the sign-in field.

### Expected behavior
I expected the username sign-in field to be vertically in line with the other buttons and fields.

### Actual behavior
![firefox_sign_in_bug](https://cloud.githubusercontent.com/assets/8591162/8573064/bb2db912-255d-11e5-9a03-a2d51414ea30.png)

This was also tested in Safari, Chrome, and IE, but only Firefox has this issue.

**Comment by revanthkolli** [comment]
@GaryKriebel Can I work on this?
