### ISSUE TITLE
Left Side Navigation overlaps Footer on Getting Started Page for reduced screen size

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3481]
## Steps
1. Go to osf.io and click on the Help dropdown in the navbar
2. Click on the Getting Started Page
3. Reduce the screen size and scroll down
4. Notice the left side navigation bar

## Expected
I would expect the left side navigation bar to have responsive sizing for reduced window sizes so that it does not overlap the footer

## Actual
The left side navigation bar overlaps the text in the footer with reduced window sizes.

![screenshot 2015-07-08 10 39 50](https://cloud.githubusercontent.com/assets/9381062/8573058/b60ae464-255d-11e5-93ae-ab74a3903d69.png)

**Comment by haoyuchen1992** [comment]
@GaryKriebel I just checked get-start page on production. It looks like the issue has already been solved. We can close this one now.

**Comment by nicipfeiffer** [comment]
@GaryKriebel @haoyuchen1992 I am still seeing this:
![screenshot 2015-07-23 12 06 50](https://cloud.githubusercontent.com/assets/9381062/8855495/68df3da2-3133-11e5-912f-683b7c9ee928.png)

**Comment by lbanner** [comment]
How might this be resolved visually? Would we expect the left-side navigation to turn into a scrolling overlay? Such that it remains above the footer, but only displays 2-3 items, giving option to scroll for more?

**Comment by haoyuchen1992** [comment]
@lbanner I think the reason for this issue is that we don't set a bottom offset for the affix.  If the bottom offset is set, the nav-bar will not down to to the bottom and then it will not overlap with the footer. I will send a fixed PR for this.
