### ISSUE TITLE
Language in logs of projects created from templates is vague

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3482]
## Steps

1. Log in to osf.io.
2. Create a new project, but use another one of your projects (that has components) as a template.
3. When redirected to your new project, look at the Recent Activity log. 

## Expected Behavior

I expect that the logs will refer to the actual name of the project I used as a template and to the actual component names within the project.

## Actual Behavior

The logs read that I created a project or a component based on "another," where "another" is a link leading to either the project or components used as templates.

## Screenshots

![logsaftercreatingtemplatedproject](https://cloud.githubusercontent.com/assets/7093086/8573436/81d9944a-255f-11e5-9774-0e555804ef79.png)

![logs](https://cloud.githubusercontent.com/assets/7093086/8573592/6c6da046-2560-11e5-9f8d-d53712f8fdcf.png)

**Comment by GaryKriebel** [comment]
Closed
