### ISSUE TITLE
[production] registration cancelation policy unclear

### ISSUE THREAD

**Issue by csoderberg** [CenterForOpenScience/osf.io#3484]
When you go to register a project we currently say: 

"When you register, a notification will be sent to all other project contributors. Other administrators will have 48 hours to approve or reject creating the registration. If any other administrator rejects the registration, it will be canceled. If all other administrators approve or do nothing, the registration will be confirmed and released or enter its embargo period."

This indicates that, whether you choose to make the registration public immediately or embargo is, the 48 hour cancelation policy should apply. Current behavior is that the 48 hour cancelation only applies to registrations that were embargoed. We should either change the language to indicate this, or change it so all registrations (regardless of public immediately vs. embargo) should have the 48 hour cancelation policy.

**Comment by csoderberg** [comment]
For what it's worth, I would vote for the 48 hour cancelation policy regardless of what option (immediate vs. embargo) is chosen to give other admins on a project the chance to over-rule a registration no matter how it is being released.

**Comment by lbanner** [comment]
I think I agree @csoderberg .... Question to @HarryRybacki or @GaryKriebel : Current functionality, if I register a project w/multiple admins making it immediately public, and another Admin receives the email and "rejects" -- what happens to the, presumably, former public registration.

**Comment by HarryRybacki** [comment]
There were no changes made to registrations that are made public immediately. That is to say, there is no approval/disapproval emails issued for registrations made public immediately. I think that is on the list for this epic though.

**Comment by HarryRybacki** [comment]
I will write a hotfix to adjust the language accordingly this morning.

**Comment by csoderberg** [comment]
Thanks @HarryRybacki

**Comment by haoyuchen1992** [comment]
@lbanner This fixed PR has been merged. Maybe we could close this one.

**Comment by lbanner** [comment]
:+1:

**Comment by csoderberg** [comment]
@lbanner , this got brought up in metascience and this functionality is an urgent bug( @bnosek ). All registrations, no matter which release option you choose, should have the 48 hour cancelation policy in place.

**Comment by lbanner** [comment]
We got that -- PR in for review on that here: #3919

**Comment by HarryRybacki** [comment]
Make sure to differentiate bug and feature -- the former strikes fear in the developer's heart.

**Comment by csoderberg** [comment]
I was told to log it as a bug, just following orders.
