### ISSUE TITLE
Registration selection gives no 'Back' and 'Forward' option for users

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3485]
## Steps
1. Go to a project you have admin access on
2. Go to the registrations tab
3. Click to make a new registration
4. In the first form, select a type of registration from the dropdown
5. You should be redirected to a new form based on the previous selection.
6. Now decide you would like to change the type of registration.... notice that there is no button option to go back to the previous form to change the selection.  So, click the browser BACK button to return to the previous page
7. Click on the dropdown, but don't  change your selection. Click on the same selection again to close the dropdown.

## Expected
I would expect the user to have the option to 'go back' after each selection in the registration process.  
I would also expect that the dropdown selection should not immediately take the user to the next from in the process; another step of a button click to confirm that is the correct selection.

## Actual
Selecting an option from the dropdown for type of registration immediately takes the user to the next form/step in the process.
Once on the next step/form of the process there is no 'button' way for the user to return to the type selection to make a change or reconsider; afterall registrations are public now!  Decisions need to be made carefully.
![screenshot 2015-07-08 11 27 24](https://cloud.githubusercontent.com/assets/9381062/8574382/564121a4-2564-11e5-9b44-46c1f7b9f2ab.png)

Notice in this video clip the user has no option to go back to change selection or to go forward after deciding to keep the selection.
![registration](https://cloud.githubusercontent.com/assets/9381062/8574876/f30bf962-2566-11e5-8c69-46c9da86bdd8.gif)

**Comment by lbanner** [comment]
@nicipfeiffer This area will be refactored in the Pre-Reg PR #3476 and will be imporved, so I am gonig to close this for now. Thanks.
