### ISSUE TITLE
Firefox: .txt files don't wrap text

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3491]
## Steps
1. Using the Firefox browser, go to https://osf.io/cvh87/
2. Click on the file test(1) (2).txt 
3. On the files detail page scroll the file render view to the right

## Expected
I would expect the text to wrap as it does on all other browsers so that the file does not extend to the right and require a left/right scroll bar

## Actual
The file should render the same on all browsers

**Comment by lbanner** [comment]
confirmed --
