### ISSUE TITLE
Cannot delete last remaining job/school from user profile

### ISSUE THREAD

**Issue by lyndsysimon** [CenterForOpenScience/osf.io#3492]
# Steps to Reproduce

1. As a logged-in user, visit the user settings page (`/settings/`)
1. On the "Education" tab, type any value in the "Institution" field
1. Save your changes
1. Reload the page

# Expected behavior

A "remove" link should be visible in the top right of the section for that institution

# Actual behavior

No "remove" link is available. Setting the "name" field to an empty string and attempting to save raises an error.

As a result, once a user enters a job or educational institution, it is not possible for them to remove all entries from their profile.

**Comment by lbanner** [comment]
@Johnetordoff --- You want to take a look at this?

**Comment by lyndsysimon** [comment]
It turns out, there is a conflict in a couple of PRs that address issues on that page, and this issue should be resolved by @billyhunt in #2531.

Closing :)
