### ISSUE TITLE
[Firefox] OSF Spinner does not spin on Files pages

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3494]
## Steps
1. Using the Firefox browser, go to a project you have read+write permissions
2. Go to the Files Tab
3. Look for the OSF spinner as the page loads, refresh the page if needed
4. Click on a file to go to the files detail page
5. Look for the OSF spinner as the page loads where the file should render, refresh the page if needed

## Expected
I would expect the OSF spinner to spin

## Actual
On these pages, the spinner flashes or is constant, but does not spin

**Comment by Johnetordoff** [comment]
@lbanner can I get this one?

**Comment by lbanner** [comment]
:+1:

**Comment by Johnetordoff** [comment]
I got this issue mixed up with #3611, the correct PR is coming.

**Comment by Johnetordoff** [comment]
This issue was fixed as of [this pr](https://github.com/CenterForOpenScience/modular-file-renderer/commit/7605cefb95f41497387eda3a4d40cd18bc1e8957) and is no longer reproducible. @lbanner can we close this?

**Comment by lbanner** [comment]
Yes -- thanks @Johnetordoff
