### ISSUE TITLE
External link URL persists after disabling and then re-enabling 

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3496]
## Steps

1. Login to osf.io
2. Navigate to a project for which you have admin permissions.
3. Head to the Project Settings. 
4. Under Select Add-Ons, click the checkbox to enable the External Links and click Submit.
5. Scroll down to Configure Add-ons and enter a website link into the URL field and click Submit.
6. Now, return to Select Add-Ons to disable External Links and click Submit.
7. Re-enable External Links by checking the box again and click Submit.
8. Scroll down to configure and notice the URL field.

## Expected Behavior

I expect that upon disabling and re-enabling external links, the URL field will be empty.

## Actual Behavior

The external link URL persists.

**Comment by chrisseto** [comment]
It may be worth disabling the external link addon for the moment. It was originally created to work with the badges addon but it wasn't disabled along with it.

**Comment by lbanner** [comment]
OK -- would want @jlcohoon and Community input on that re: expectations of users.

**Comment by jlcohoon** [comment]
I do agree with Natasha's expectations. But, I would check how many people are using it. If it's not many and the issue will be fixed soon, you could probably disable it. The feature has more applications than just badges, however (e.g. I had a paper that cited the OSF as containing my supplemental materials, but then I moved them elsewhere). 

@JeffSpies probably has the best insight on this.

**Comment by JeffSpies** [comment]
It was not created for badges; it supports the flexibility and freedom of our identifiers. It should be fixed ASAP.
