### ISSUE TITLE
"Add Links" modal search error

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3497]
## Steps

1. Log in to osf.io.
2. Navigate to one of your projects.
3. Under the components widget, click the "Add Links" button.
4. In the search field, search for the letter "A" (click Search all projects).
5. Many results will appear; click to one of the later pages (page 5 for instance).
6. Now return to the search field and search for the letter "B" (again, click Search all projects).
7. Notice what page of the search results you are on (still page 5).
8. Remain on the page you are on and in the search bar enter, "Cayley" (again, click Search all projects).
9. Notice the results of the search.
10. Search for the letter "B" again and click Search all projects.
11. Click back to the first page of the search results.
12. Now, search for "Cayley" and click Search all projects.
13. Notice the new results.

## Expected Behavior

I expect that if I click to page 5 of the results for one search, upon entering a new search parameter, the search results will return to page 1. I also expect that when I search for "Cayley," the public project "Cayley Graphs" (one of Cailey's projects on Production) will appear.

## Actual Behavior

After searching for "A" in all projects and clicking to page 5, when I enter my new search, the search results remain on page 5. This problem results in the latter problem. Searching for "Cayley" will not turn up five pages worth of results, and so the project is not revealed in search at all. When I return to page 1 of the last search results and then search again for "Cayley," I see her project and the registration of the project listed.

## Screenshots

**Searching for "A" in search field**

![searchfora](https://cloud.githubusercontent.com/assets/7093086/8580261/a6113a70-2587-11e5-865c-78ab136e7664.png)

**Searching for "B" in search field**

![searchforb](https://cloud.githubusercontent.com/assets/7093086/8580294/e1e4a73a-2587-11e5-9349-07976f7fe694.png)

**Searching for "Cayley" while remaining on page 5**

![searchforcayley](https://cloud.githubusercontent.com/assets/7093086/8580315/ffe9f618-2587-11e5-87a9-0ac9dbb27a9f.png)

**Searching for "Cayley" after returning to page 1**

![searchforcayleyagain](https://cloud.githubusercontent.com/assets/7093086/8580839/e3f48218-258a-11e5-9154-1715c294086c.png)

**Comment by lbanner** [comment]
Interesting ...

**Comment by caileyfitz** [comment]
Same problem occurs (only displaying results for the specific page the user was last on) *after* the modal is exited and re-opened. The only way to fix this is to refresh the page or add a link.
