### ISSUE TITLE
External links form submit button not clickable until URL field is filled out

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3505]
## Steps

1. Log in to osf.io.
2. Navigate to one of your projects.
3. Head to the project settings page.
4. Enable "External Links" under "Select Add-ons."
5. Scroll down to "Configure Add-ons" and notice button.

## Expected Behavior

I expect that the button will not appear grayed out or disabled. In other similar places on the OSF, buttons do not appear this way, even when fields are empty.

## Actual Behavior

The button is grayed out until I fill in the URL field. 

## Screenshot

![formsubmitbutton](https://cloud.githubusercontent.com/assets/7093086/8597984/661a6b9a-2626-11e5-9799-399d39a85824.png)

**Comment by NatashaRichter** [comment]
I've talked to Saman about this problem and we thought github may be a good place for this issue.

**Comment by jinluyuan** [comment]
Appearance on production: 
![screen shot 2015-07-09 at 10 20 14 am](https://cloud.githubusercontent.com/assets/8591162/8597554/1f947f82-2624-11e5-9152-a885b6a29bc4.png)

**Comment by chennan47** [comment]
Url should have placehold required

**Comment by GaryKriebel** [comment]
closed with release 0.81.0
