### ISSUE TITLE
[bug] `User.social` validators never called upon `User.save()`

### ISSUE THREAD

**Issue by HarryRybacki** [CenterForOpenScience/osf.io#3513]
## Steps:
1. Log into an account
2. Navigate to the account settings page, osf.io/settings>/ 
3. Click the `Social` tab
4. Edit one of the social fields
5. Click `Submit`

## Expected:
The updated field will be validated by `profile.js` and the model `core.py`

## Actual:
1. The field is scrubbed in `profile.js` -- https://github.com/CenterForOpenScience/osf.io/blob/develop/website/static/js/profile.js#L15-L23
2. HTML characters are escaped in the view -- https://github.com/CenterForOpenScience/osf.io/blob/develop/website/profile/views.py#L636
3. When the `User` object is saved, the validator is short-circuited  -- https://github.com/CenterForOpenScience/osf.io/blob/develop/framework/auth/core.py#L87-L98

## Discussion:
Specifically, [this line](https://github.com/CenterForOpenScience/osf.io/blob/develop/framework/auth/core.py#L98) results in none of the fields ever truly being validated.

**Comment by Johnetordoff** [comment]
I too was very puzzled by the validation on this page, much of the code included was superfluous, but I didn't remove any because I couldn't tell how the validation was actually being done.
