### ISSUE TITLE
[Staging and Production] [Firefox] [Safari] View-only Link copy button does not copy

### ISSUE THREAD

**Issue by WillBanner** [CenterForOpenScience/osf.io#3514]
# Steps #
1. Go to osf.io and log in on safari or firefox
2. go to a project on which you are an admin and that has a View-only link.
3. Go to the sharing tab
4. Scroll down to "view-only links" and look under the header "link"
5. Click on the button to copy the link (to the left of the link box)
6. Paste into the browser search bar.

# Expected #
The link to the view-only version of the project would appear in the search 

# Actual #
Whatever I had copied prior to pressing the button appears in the browser search, so it's as if I never had pressed the copy button at all.

**Comment by chennan47** [comment]
@caileyfitz I can't repo this problem. Can you verify it? Thanks.

**Comment by mfraezz** [comment]
@chennan47 I can confirm this button works in Chrome but not FF. 
<img width="591" alt="screen shot 2015-07-13 at 10 08 10 am" src="https://cloud.githubusercontent.com/assets/5659262/8651935/cc00e800-2949-11e5-9116-f8c8007aaa54.png">

I've noticed the lack of clipboard-copy functionality on FF with other sites too, this [MDN](https://developer.mozilla.org/en-US/docs/Midas/Security_preferences) article explains why. In short, Mozilla thinks it's a *security feature* to disallow this functionality unless a user explicitly allows it for specific sites by editing ```user.js``` in their profile. Safari probably does something similar, but I haven't looked into it.

If we can't get it functioning across all browsers, we should at least not display it for browsers that won't support it. @lbanner Thoughts?

**Comment by chennan47** [comment]
@mfraezz what's ur firefox version?

**Comment by mfraezz** [comment]
[FirefoxDeveloperEdition](https://www.mozilla.org/en-US/firefox/developer/), 41.0a2 (latest)

**Comment by nanchen47** [comment]
Will be consider based on more user's feedback.
