### ISSUE TITLE
[Bug Production: All browsers but FireFox] hitting enter after adding an image or link to wiki exits editing

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3518]
## Steps
1. Visit a wiki page you have permissions to edit
2. Enter edit mode and click on the add link or add image button above the wiki editing box.
3. Enter a url—do not press 'OK'
4. Hit the 'return' key

## Outcome
1. The user is brought out of edit mode
2. Changes are not published (but returning to edit mode shows that they were auto saved)

## Expected outcome
1. Either hitting return should be equivalent to pressing OK or it should do nothing. The user should not be brought out of the edit mode.

**Comment by mfraezz** [comment]
I can't reproduce this bug. Tested locally, on staging, and on production (on production - both projects that I created and did not), also with default ('http://') and filled in url fields. Are there any other details that might affect this?

**Comment by jlcohoon** [comment]
not that I can think of? I can still produce it and so can @mckidwell 
![3518](https://cloud.githubusercontent.com/assets/4965832/8624111/8ca540d6-2703-11e5-9633-ee7573fc8d08.gif)

**Comment by mfraezz** [comment]
Hmm. It's not happening on Firefox, but it does on Chrome/Safari. I'm getting a ```TypeError: r.refresh is not a function``` in my console log for FF, which may explain why FF is immune to this bug. It appears to be coming from a minified version of pagedown-ace's [JS](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/addons/wiki/static/pagedown-ace/Markdown.Editor.js#L1539)

**Comment by mfraezz** [comment]
So, commenting out that [line](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/addons/wiki/static/pagedown-ace/Markdown.Editor.js#L1539) fixes this in Safari and Chrome, and has no effect that I've observed in FF. Reading through that code doesn't yield any obvious issues with doing so, and the original author even left a comment saying that ```this [method] is awkward and I think it sucks```. However, the wiki doesn't run in Live Edit Mode locally, so there may be unintended side effects on staging. @brianjgeiger Can you comment on that subject?

**Comment by brianjgeiger** [comment]
I have no comment on the subject. I didn't work with that particular code directly.
