### ISSUE TITLE
logs allow you to click on deleted file; alert is unhelpful

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3526]
## Steps
1. Visit a project with a file (or upload one)
2. Delete that file
3. Look at the logs and scroll to any log that is about that file *except* the log saying the file was deleted

## Outcome
1. The log that says the file was deleted does not link to the file
2. All other logs do link to the a file page
3. The file page is titled with a series of numbers
4. There is an alert that says the file does not exist
5. The revisions say the file was not found

![screen shot 2015-07-10 at 10 22 07 am](https://cloud.githubusercontent.com/assets/4965832/8620489/e0cb86c2-26ed-11e5-8d68-487a048377f7.png)

## Expected outcome
1. The file should not be linked to in the logs. If the file must be linked to, the detail page should still include the file's title and the alert should read, "This file was deleted on [Date]." The revisions should also include that message.

**Comment by chennan47** [comment]
Based on how log works, this is expected behavior. Before the log is deleted, any logs about that file include the url link to that file which is already stored in the database. When the file is deleted, it just generated a new log but doesn't modify any previous log.

**Comment by bnosek** [comment]
An improved message of "this file was deleted on [date]" is useful, and the file should continue to be linked in the logs.

**Comment by lbanner** [comment]
I like that approach - @nanchen47 How does that sound? Difficult to change?

**Comment by jlcohoon** [comment]
@JeffSpies, thoughts? 
what do we do about the file title on the file's page?

**Comment by chennan47** [comment]
@lbanner easy to do. Can be an intern task.
