### ISSUE TITLE
[bug] Pointer created by Swagger docs belongs to wrong node

### ISSUE THREAD

**Issue by jamiehand** [CenterForOpenScience/osf.io#3536]
@brianjgeiger 

### Steps:

1. Go to http://localhost:8000/v2/docs/ or https://staging2.osf.io/api/v2/docs/
2. Expand ```POST /v2/nodes/{node_id}/pointers/```
3. Enter node_id A in top ```node_id``` field and node_id B in bottom ```node_id``` field.
4. Click ```Try it out!```

Based on the description, it seems this should create a pointer from node A to node B, but it instead it creates a pointer from node B to node B. See below for more detail.

### Expected: 

![screen shot 2015-07-10 at 2 04 34 pm](https://cloud.githubusercontent.com/assets/10687411/8625421/ab8f1310-270c-11e5-9b43-ba9785546c1c.png)
Clicking ```Try it out!``` here should create a pointer from upper node ```kbufp``` to lower node ```9adsc``` (i.e. node ```kbufp``` should own a new pointer than points to ```9adsc```).

### Actual:

The pointer is being created from lower node ```9adsc``` to itself (it is owned by ```9adsc``` and points to ```9adsc```) -- so it is pointing the right direction but is owned by the wrong node.

Pointer list of ```kbufp``` ("node A", which should have a link to ```9adsc```, "node B"):
![screen shot 2015-07-10 at 2 17 43 pm](https://cloud.githubusercontent.com/assets/10687411/8626066/6e2a49e6-2710-11e5-9ac2-5620c1ee3245.png)

Pointer list of ```9adsc``` ("node B", which should have no links):
![screen shot 2015-07-10 at 2 18 02 pm](https://cloud.githubusercontent.com/assets/10687411/8625728/930c7312-270e-11e5-89af-b4407400b6bf.png)

### Possible solution:

- Seems like it needs to be a back-end fix, correcting which ```node_id``` is passed as the owner to the pointer.
- On the front-end (swagger docs) it would be helpful if the "parameters" listed had different names (e.g. ```node_id_that_owns_pointer``` and ```node_id_that_pointer_points_to```) -- maybe the problem is actually occurring *because* of the same-name parameters?

**Comment by brianjgeiger** [comment]
One of those parameters should be 'id' rather than 'node_id'. I expect that's related.

**Comment by jamiehand** [comment]
@brianjgeiger, based on the NodePointersSerializer in the docs, "id" doesn't seem to be something that could be entered as a parameter. It seems like "id" is a random id generated for the pointer upon creation of the pointer (i.e. it seems to be the "pointer_id", which can later be used with GET /v2/nodes/{node_id}/pointers/{pointer_id} to see a detail view for the pointer). Is that not the case?

![screen shot 2015-07-13 at 12 41 09 pm](https://cloud.githubusercontent.com/assets/10687411/8655035/79be3c9c-295c-11e5-99b5-5066c086646f.png)

**Comment by brianjgeiger** [comment]
Riiight. Okay. So there's the node_id in the path, which would have been pk before Patrick G changed it to make the documentation more useful. And even though it's labelled as the one in the path, it's clearly not working that way, because when you look at the request url, the one in the path is the id from the form item.

So the swagger docs should be able to recognize this situation, but they don't seem to. We should file a bug on the django_rest_swagger repo about this situation. We might be able to fix it by renaming one of those `node_id`s.

**Comment by jamiehand** [comment]
Should filing that bug be a priority, or should I hold off until we know we'll be sticking with the swagger docs?

**Comment by brianjgeiger** [comment]
If it's 15 minutes to file the bug, go ahead and do that sooner. Even if we don't need it, it'll help other people. Be sure to check to make sure someone hasn't already filed it, though.

**Comment by brianjgeiger** [comment]
Probably `target_node_id` for the node being pointed to is the proper way to fix this and should be very quick to do.

**Comment by jamiehand** [comment]
Is this something that I could do?

**Comment by brianjgeiger** [comment]
Yeah, this would be probably a 10 minute PR. Maybe a bit more if tests need changing, but not much. If you need a break from client stuff, feel free.

**Comment by brianjgeiger** [comment]
@reinaH There's a PR for this, yes? If so, please reference this issue in the PR.
