### ISSUE TITLE
Go/nogo on release 0.42.0

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#3540]
@JeffSpies @GaryKriebel @lbanner @caileyfitz @nicipfeiffer

**Comment by GaryKriebel** [comment]
Currently >20 bug cards that are not in the deferred column with 11 in the draft/pending column.

**Comment by lbanner** [comment]
RE: Dataverse PR clarification: Robert notes that the "Other" field is meant to allow the user to input any URL that is a 4.0 Dataverse implementation. However, there appear to be no current, existent, Dataverse implementations that have been updated to 4.0. @nicipfeiffer, your referenced web site lists Dataverse "collections" rather than Dataverse repositories.

Two + 1 options: Release as is, anticipating the ability to verify at some point in the future (when a DV repository at v.4.0 exists) -- or -- Remove the "Other" option -- or -- Release current, and deploy a correction later to remove the "Other" option if we choose. I am OK with that one and not holding release for a code change on this.

**Comment by sloria** [comment]
Re: Dataverse, I vote to keep "Other" option for now.

**Comment by GaryKriebel** [comment]
I am fine with other as well.

**Comment by JeffSpies** [comment]
Summary?

On Friday, July 10, 2015, Steven Loria <notifications@github.com> wrote:

> @JeffSpies <https://github.com/JeffSpies> @GaryKriebel
> <https://github.com/GaryKriebel> @lbanner <https://github.com/lbanner>
> @caileyfitz <https://github.com/caileyfitz> @nicipfeiffer
> <https://github.com/nicipfeiffer>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/issues/3540>.
>


-- 
Sent from mobile.

**Comment by JeffSpies** [comment]
What happens if people choose a dataverse that isn't 4.0?

**Comment by lbanner** [comment]
Error message that we will want to improve, "There was a problem connecting to the Dataverse."

**Comment by JeffSpies** [comment]
How about

Sorry, but there was a problem connecting to that instance of Dataverse. It
is likely that the instance hasn't been upgraded to Dataverse 4.0. If you
have any questions or believe this to be an error, please contact
support@osf.io.

**Comment by sloria** [comment]
Ok, that change is made.

Haoyu, Caner, Nan, and I are continuing to address the remaining bugs. We will re-evaluate at 4pm to check progress.

I will be a "go" when QA decides there are no more bugs that should hold release.

**Comment by lbanner** [comment]
Good on that change @sloria -- We'll help make sure the communication is happening 'tween Haoyu, Caner and QA.

**Comment by GaryKriebel** [comment]
Thank you for the update @sloria, I'm just getting caught up from my return.  I agree with this plan.

**Comment by sloria** [comment]
Update: There are 4 remaining bugs. Two are related to searching in the Add Links modal. It is likely that they both have the same cause: there are projects with no visible contributors (https://github.com/CenterForOpenScience/osf.io/issues/3560). Since this bug is on production, I recommend deferring. Nan is already working on the fix.

The other two bugs are Dataverse-related. One is an aesthetic bug, which I recommend deferring. The other seems to be a more significant bug (https://trello.com/c/zXYPxkjB/259-import-dataverse-access-token-modal-pops-up-after-creating-access-token-on-project-settings), though @caileyfitz or @nicipfeiffer  will have a better idea about its severity, e.g. if it can reliably be reproduced, etc.

@caileyfitz @nicipfeiffer Any objections to releasing this evening?

**Comment by lbanner** [comment]
I am a GO ... issues that exist are very well documented, and Dataverse in particular represents a very small percentage of any user use-cases on Production at the moment -- As long as @nicipfeiffer and @caileyfitz are good. Thanks.

**Comment by GaryKriebel** [comment]
I concur with @sloria

**Comment by caileyfitz** [comment]
Dataverse is now stuck in an infinite loop... so I am a no-go for the moment

**Comment by chennan47** [comment]
Sry, that's my fault, but have a fix for that included in
https://github.com/CenterForOpenScience/osf.io/pull/3571. Once that one is
merged, all dataverse problem should be fixed.

On Mon, Jul 13, 2015 at 5:07 PM, Cailey Fitzgerald <notifications@github.com

**Comment by nicipfeiffer** [comment]
With dataverse fixed and all style/UI bugs that are deferred documented for fixing post release, I am a GO.

**Comment by sloria** [comment]
Nan's PR is now merged and on staging.

**Comment by JeffSpies** [comment]
I'll tether my go-no go to Cailey. On her go-ahead, I'm a go.

J.

**Comment by GaryKriebel** [comment]
Does it still need testing?  If so, I'll give it a run through.

**Comment by sloria** [comment]
@GaryKriebel Yes, it still needs testing.

**Comment by lbanner** [comment]
OK ... if we run through it, and all's good, can we still get a "Go?"

**Comment by caileyfitz** [comment]
All looks well upon a quick run-through, so I am a GO! :rocket:

**Comment by lbanner** [comment]
Yep, I and @willbanner confirm as well. Thanks.

**Comment by GaryKriebel** [comment]
Sorry. Everything got in my way tonight including being stopped on rt20 for construction. Testing still needed?

**Comment by GaryKriebel** [comment]
Dataverse worked well for me.... I am a go if word is still needed.

**Comment by sloria** [comment]
Released!
