### ISSUE TITLE
[bug] Swagger PATCH doesn't allow change to blank-string category

### ISSUE THREAD

**Issue by jamiehand** [CenterForOpenScience/osf.io#3543]
@brianjgeiger 

Steps
-------
1. Go to http://localhost:8000/v2/docs/ or https://staging2.osf.io/api/v2/docs/
2. Expand ```PATCH /v2/nodes/{node_id}```
3. Enter a node_id that you can modify in the ```node_id``` field, enter "Title 1" in the ```title``` field, and set ```category``` to "project".
4. Click ```Try it out!```-- Note that the title changes to "Title 1" and the category becomes "project".
![screen shot 2015-07-10 at 3 50 00 pm](https://cloud.githubusercontent.com/assets/10687411/8627772/5fa9af96-271b-11e5-9832-923246af3bc7.png)
5. Leave the node_id the same, enter "Title 2" in the ```title``` field, and this time set the ```category``` field to be blank (either of the two blank choices will produce this behavior).
![screen shot 2015-07-10 at 3 50 51 pm](https://cloud.githubusercontent.com/assets/10687411/8627790/77c6e2ce-271b-11e5-9527-3d3d432d1310.png)
6. Click ```Try it out!``` -- Note the the title changes to "Title 2" but the category remains "project".
![screen shot 2015-07-10 at 3 51 25 pm](https://cloud.githubusercontent.com/assets/10687411/8627805/8cc8c200-271b-11e5-8756-c4b93c13e45f.png)

Expected
------------
Based on the "Choices" description, there should be some way, by selecting a blank choice for ```category```, to PATCH the node in a way that changes its category to ```''```.

Actual
--------
No matter which of the two blank choices is selected, submitting the form does not change the category to ```''```.

Possible solution
-----------------------

- There should be a choice for "category" that allows the category to be set to an empty string.
- Ideally, there should be a clear difference between the "no choice" category (e.g. it could say ```Please select```), and the "empty string" category (e.g. it could just be blank).

**Comment by samchrisinger** [comment]
@lbanner I have a suspicion that this may not be an API issue at all, rather an aspect of the Node#update_node implementation

**Comment by brianjgeiger** [comment]
No, you can make the change if you don't use a form field (i.e. with a request that uses a json body)

**Comment by lbanner** [comment]
Do we need more clarity here? Let me know -
