### ISSUE TITLE
[bug] can return deleted nodes

### ISSUE THREAD

**Issue by reinaH** [CenterForOpenScience/osf.io#3550]
@brianjgeiger 

# Steps
Can be reproduced for both url bases: "https://staging2.osf.io/api/v2/"  and "http://localhost:8000/v2/"

1.Go to url and create a new node:
```
basic_auth = ('username', 'password')
url = "https://staging2.osf.io/api/v2/nodes/"
payload = {'title': 'create a node', 'description':'A Properly Cool Project', 'category': 'data'}
res = requests.post(url, json=payload, auth=(basic_auth))
data = res.json()
pprint.pprint(data) #or print (data)
```
2.Retrieve the node id that has just been created:
```
node_id = data['data']['id']
```
3.Using the node id, delete the node:
```
url = "https://staging2.osf.io/api/v2/nodes/{}/"
res = requests.delete(url.format(node_id), auth=(basic_auth))
print res.status_code  #expected: 204
```
4.Attempt to retrieve the deleted node:
```
url = "https://staging2.osf.io/api/v2/nodes/{}/"
res = requests.get(url.format(node_id), auth=(basic_auth))
print res.status_code
pprint.pprint(res.json()) # or print (res.json())
```
# Expected
Once the node has been deleted, it should not be able to be retrieved. 

# Actual 
Deleted node information is returned and node information does not contain the "is deleted" flag, which should be set to true. May lead the user to believe the node was not deleted. 

# Possible Solution
The node should not be returned at all or should be returned with an explicit "is_deleted" flag set to "True" so that the user knows the node they retrieved is a deleted node.

**Comment by brianjgeiger** [comment]
This is essentially part of #3551, so I think we can close this one.
