### ISSUE TITLE
[bug] can access and edit deleted nodes

### ISSUE THREAD

**Issue by reinaH** [CenterForOpenScience/osf.io#3551]
@brianjgeiger 

# Steps
Can be reproduced for both url bases: "https://staging2.osf.io/api/v2/"  and "http://localhost:8000/v2/"

1.Go to url and create a new node:
```
basic_auth = ('username', 'password')
url = "https://staging2.osf.io/api/v2/nodes/"
payload = {'title': 'create a node', 'description':'A Properly Cool Project', 'category': 'data'}
res = requests.post(url, json=payload, auth=(basic_auth))
data = res.json()
pprint.pprint(data) #or print (data)
```
2.Retrieve the node id that has just been created:
```
node_id = data['data']['id']
```
3.Using the node id, delete the node:
```
url = "https://staging2.osf.io/api/v2/nodes/{}/"
res = requests.delete(url.format(node_id), auth=(basic_auth))
print res.status_code  #expected: 204
```
4.Attempt to edit the deleted node and return the node:
```
url = "https://staging2.osf.io/api/v2/nodes/{}/"
res = requests.put(url.format(node_id), json={'title': 'This deleted node has been edited',
                                                               'node_id': node_id,
                                                               'category': 'data'}, 
                                                               auth=(basic_auth))
print res.status_code
pprint.pprint(res.json()) # or print (res.json())
```

# Expected
Once the node has been deleted, it should not be able to be retrieved and it should not be editable . 

# Actual 
Deleted node can be retrieved and edited.

# Possible Solution
Do not allow for this functionality.

**Comment by brianjgeiger** [comment]
For this and #3550, I would have expected this not to be possible based on the base ODM query. So I think we will need to make permissions classes that prevent these thing from happening. It may be a deleted node gets a 404 rather than a 401/403. We may have to do the same with the other items in the base query.

**Comment by reinaH** [comment]
https://gist.github.com/reinaH/7eaeab5f05acac948566
