### ISSUE TITLE
Consider removing/hiding Swagger docs

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3552]
The swagger docs are somewhat redundant with the Django docs, and are somewhat troublesome. It might be better to keep the swagger generation capability, but to not use the auto-generated swagger docs as the primary point of contact with the API.

On the other hand, it could be that the Swagger isn't being so troublesome now but is really good for finding issues in the API. Anyways, this issue is to generate discussion and get me to keep thinking about this issue.

**Comment by abought** [comment]
The swagger docs are an asset to discovery (all routes documented on a single page).

I admit to preferring the DRF browseable API for detailed information on a route, but I wouldn't want to use it for a high-level summary of what the API could do. Not sure if another public overview doc exists.

Just my 2 pence.

**Comment by brianjgeiger** [comment]
Agreed. If it goes, it'll need replacing, but it may be replaced with something generated from the swagger json but served more statically.

**Comment by brianjgeiger** [comment]
Might look at using something like https://github.com/devo-ps/carte - it's a statically served set of pages created by Jekyll. It's fairly simple thing, and would require some extra work on our end, but we could have it point interactive examples at the Django docs on the api test server (currently staging2) rather than encouraging live testing on production, regardless of where they are checking out the docs from. 

It might also still be nice to take advantage of the swagger json that can be created as a starting point for creating alternate documents, but there are somewhat limited options for that. Shouldn't be hard to do if we wanted to, though.

**Comment by brianjgeiger** [comment]
Although Carte is really so simple that just making a sing file by hand would probably be better.

**Comment by brianjgeiger** [comment]
Other ways to handle some issues:
* Point the live version of the swagger docs to the staging server rather than to whatever it happens to be hosted on. If this is possible (which it should be), it could be overridden for development testing
* See if there's an option to disable having active pages and just have them display the docs.

**Comment by pattisdr** [comment]
Documenting a Swagger issue:

I am trying to get the API to match the JSONAPI v1 spec http://jsonapi.org/format/

The header `Content-Type: application/vnd.api+json` must be sent with the response, but a Swagger bug is preventing this. There's an old issue for this https://github.com/marcgibbons/django-rest-swagger/issues/271.

If I comment out `rest_framework.renderers.JSONRenderer` in settings, the content type is correct everywhere but Swagger, where it throws a `406 : NOT ACCEPTABLE` error.

**Comment by brianjgeiger** [comment]
@reinaH When you're done with your current PR, see if you can find a way to disable api/v2/docs url while still generating a swagger json document (currently being served at https://staging2.osf.io/api/v2/docs/api-docs/v2). It may be that we just don't advertise the /docs/ or it may be that we want to serve static content at /docs/. See if you can get a feel for the sorts of things that the django rest swagger is okay with us modifying and which it gets really uncomfortable about if you do.

**Comment by brianjgeiger** [comment]
I think we're going to keep the swagger docs, but we're going to make them more generally useful by modifying the layount and allowing us to add more context around the docs.
