### ISSUE TITLE
[Staging and Production] Can have project with no listed contributors

### ISSUE THREAD

**Issue by WillBanner** [CenterForOpenScience/osf.io#3560]
# Steps
1. Go to osf.io and log in.
2. Go to a project on which you are an admin.
3. Go to the sharing tab for that project.
4. Add your secondary osf account as a read/write contributor. 
5. Uncheck the box listing you as a bibliographic contributor (the only contributor listed should now be the read/write contributor).
6. Log on to the account of the read/write contributor.
7. Go to the project.
8. Go to the sharing tab.
9. Press the x to remove yourself as a contributor.

# Expected
Either I would be prevented from removing myself as a contributor or I would be notified that if I were to remove myself, the other contributor would automatically become a bibliographic contributor or something along those lines.

# Actual
I am removed from being a contributor and when I publicly search for the project, there are no listed contributors.

![image](https://cloud.githubusercontent.com/assets/12799635/8656303/c3e0c4fe-2964-11e5-8e7f-bc4ce6a5ba32.png)

**Comment by chennan47** [comment]
@WillBanner Actually this problem should already be fixed on staging. Can we try to reproduce it?

**Comment by WillBanner** [comment]
@chennan47 Hmm, I'm still able to reproduce it. If you search for project Los Angeles on staging, there shouldn't be any listed contributors, and if there are, then maybe it's a problem on my end?

**Comment by lbanner** [comment]
No contributors ....
<img width="609" alt="screen shot 2015-07-13 at 2 34 02 pm" src="https://cloud.githubusercontent.com/assets/2964829/8657540/43f8b582-296c-11e5-8184-307d9451c31a.png">
