### ISSUE TITLE
[production] In-progress edits in Project Description lost

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#3561]
Steps
-------
1. Click on a project's description to edit it, and begin typing
2. Highlight something on the wiki to copy+paste it into the description
3. The text you typed in the description box is lost, even though you have not clicked the "x"

Expected
------------
The text you typed would remain unless you click "x" to revert to the last saved version

Actual
--------
In-progress text is lost.

Reported by a user on the help desk.

**Comment by GaryKriebel** [comment]
Closed
