### ISSUE TITLE
[bug] can return deactivated user 

### ISSUE THREAD

**Issue by reinaH** [CenterForOpenScience/osf.io#3565]
@brianjgeiger
# Steps
1. Go to an account on staging2 that has at least a couple of components, files, and at least one contributor. Save the account user ID for your account.  
2. Deactivate the account on staging2 (ping Steve or Sara to expedite the process)
3. Go to: "https://staging2.osf.io/api/v2/users/{deactivated_user_ID}/" 

# Expected
It is unknown what is expected. If a user wanted to delete their account, they would deactivate their account because it states that the action is “irreversible”. If a user deactivates an account and tries to create a new account with the email that was associated with the deactivated account, it can not be done. The error message states "The email X is already associated with an account". As a user, this makes me think my deactivated account is synonymous to a project registration: a frozen version of my account where other users can access the public components I have contributed to/created up until that point and I would assume that I could reactivate my account. If that is how we define a deactivated user then from a developer's perspective, I would assume that you should be able to return a deactivated user using the API. On the other hand, if a deactivated user should not be accessible then a user might expect that the email associated to the old account be free. This presents an off boarding issue that should be considered.

# Actual 
The deactivated user information is retrieved- 200 status code. API Links associated with the account are also active and point to the user's respective projects (public and private), and files (which can all be downloaded). The "html" link that points to the OSF staging2 account returns a 410 (GONE) status code.

**Comment by reinaH** [comment]
@lbanner

**Comment by lbanner** [comment]
I would think we would want to just dis-allow this (?) i.e. retrieving data from deactivated accounts. But this note too begs an interesting question around what it means to 'deactivate' an account as opposed to a full deletion, 'If a user deactivates an account and tries to create a new account with the email that was associated with the deactivated account, it can not be done. The error message states "The email X is already associated with an account." ' @saradbowman @jlcohoon ?

**Comment by brianjgeiger** [comment]
Agreed, the API should definitely not return any info about a deactivated user. It should essentially be the same solution as #3551

**Comment by lbanner** [comment]
OK good -

**Comment by jlcohoon** [comment]
Whether we fully delete or deactivate, shouldn't the user be able to sign up with the same email? If it's just deactivation, they resume where they left off. If it's full deletion, they start from scratch.

**Comment by jlcohoon** [comment]
I think I might be overruled in my previous comment. I'm going to make a summary of account alerts/emails when you try to perform various actions (forgot password, try to log in with a deactivated account) and then we should be able to make a more consistent decision on the alert/behavior the user sees.

**Comment by GaryKriebel** [comment]
this is a great idea, @jlcohoon .... we discussed with ErinM the need for this kind of documentation and this would be a good first step.

**Comment by saradbowman** [comment]
Some of this is captured here
<https://docs.google.com/document/d/1bLNVsHLktmRFhW1TJ-K4kR6PQa39aQP3iFw3shgk_vk/edit#>
(though
not all).

**Comment by GaryKriebel** [comment]
woah, that's great @saradbowman

**Comment by saradbowman** [comment]
I have a concern about this. Currently, there's no standard procedure for what happens upon deactivating an account; cases are evaluated as they come in dependent on various factors (public vs private projects, project has other contributors or does not, etc.). Happy to discuss scenarios further privately. 

Is there a proposal or text written to explain what happens when a user is deactivated via the API? Is this something that needs to be run by community? 

The update to the FAQ page also makes claims about account deactivation: https://osf.io/faq/#common
To my knowledge, those also have not been discussed.

**Comment by brianjgeiger** [comment]
Users will not be deactivated via the API. The only thing this issue explicitly will be addressing is ensuring that deactivated users are not returned by the API. This issue should be resolved soon, and further discussions about how deactivated users will be handled will likely want to move somewhere else.

**Comment by saradbowman** [comment]
Ah, okay. Thanks!
