### ISSUE TITLE
[bug] Panel headings are not a consistent size

### ISSUE THREAD

**Issue by ticklemepierce** [CenterForOpenScience/osf.io#3578]
Steps:
1) Go to a project
2) Go to its wiki
3) Click the "Edit" toggle
4) Observer the difference in the panel headings of Edit and View

Expected:
They should be the same (presumably a height that is constant across the OSF).

Actual:
They are different.  Then if I create my own panel I get yet another height.

<img width="1048" alt="screen shot 2015-07-14 at 10 04 40 am" src="https://cloud.githubusercontent.com/assets/8229937/8675078/d70ee3b6-2a0f-11e5-875f-f463107bc22d.png">

**Comment by GaryKriebel** [comment]
I believe @caneruguz already started addressing this?

**Comment by caneruguz** [comment]
@Gary the issue I'm addressing right now is unrelated to this. 

The height of a panel header is determined by what the developer chooses to put in there, and the spacing of these elements are different. The panel header allows for these changes. It is of course aesthetically better to have them all be same height but for that the style  needs to be page specific css and not a global style change. 

I think one could override the header min-height or height for this specific purpose, the wiki-page.css is a good place to add that override.

**Comment by GaryKriebel** [comment]
Thanks @caneruguz.
@ticklemepierce , can you update this with screenshots as well?

**Comment by GaryKriebel** [comment]
Fixed in release 0.67
