### ISSUE TITLE
Files Detail Page: Rich Text Files (.rtf) have edit pane

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3580]
## Steps
1. Go to a project with an .rtf file uploaded or upload one to a project
2. Click on the file name to go to the files detail page and render the file
3. On the files detail page, look in the upper right for the view toggle
4. Toggle the edit button to show the edit pane for the .rtf file

## Expected
Since this file renders as a pdf, the edit pane is not consistent with other files rendering in that format.

## Actual
There is an edit pane for rich text files.

![screenshot 2015-07-14 10 09 59](https://cloud.githubusercontent.com/assets/9381062/8675194/83f1a92e-2a10-11e5-926c-6abd4d168776.png)

**Comment by nanchen47** [comment]
This looks more like a desired behavior to provide user with options to edit .rtf file directly on OSF. Thoughts? @GaryKriebel @lbanner

**Comment by lbanner** [comment]
There should be an edit pane for RTF files, I think (?) But @nicipfeiffer are you suggesting that in this case, displaying RTF, using the edit function does not work?

**Comment by nicipfeiffer** [comment]
@lbanner I am really just asking that since this is a Rich text formatted file (similar to gdocs and word docs) that the edit pane isn't helpful to users.  For .txt files and the like the edit pane is useful as there is not formatting within the edit pane, but for this .rtf file there is lots of formatting language instead of editable text.

**Comment by lbanner** [comment]
I get ya -- OK -- I'm going to relabel as 'enhancement' as @nanchen47 has noted, as, technically, this is working as required.

**Comment by nanchen47** [comment]
Will be considered on future file page edit enhancements. Thanks.
