### ISSUE TITLE
[bug][production] Semicolon on profile pages

### ISSUE THREAD

**Issue by HarryRybacki** [CenterForOpenScience/osf.io#3588]
## Steps to recreate:
- Go to any user profile page

## Expected:
There to not be a semicolon on the upper left corner of the page.

## Actual:
There is a semicolon on the upper left corner of the page.
<img width="244" alt="screen shot 2015-07-14 at 12 16 00 pm" src="https://cloud.githubusercontent.com/assets/2614670/8678433/8e60ddf0-2a22-11e5-82a3-0bbea0d8d194.png">

**Comment by samanehsan** [comment]
Fixed in #3595
