### ISSUE TITLE
include link to project in issue registering project email

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3589]
## Current Behavior
The email alerting users that there was an issue in registering a project does not include a link to the project.
![screen shot 2015-07-14 at 12 57 02 pm](https://cloud.githubusercontent.com/assets/4965832/8679331/083bdada-2a28-11e5-8e4b-be32639a75ce.png)

## Expected Behavior
The project title should link to the project page so that the user can easily try to register again.

**Comment by haoyuchen1992** [comment]
I can work on this one!
