### ISSUE TITLE
add link to component in file tree 

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3593]
This comes from the community repo: https://github.com/CenterForOpenScience/community/issues/179

## Steps
1. Visit the overview of a project with multiple components
2. Hover over a component's name in the file tree
3. Try to click on a component's name in the file tree

*or*

1. Visit the files page of a project with multiple components
2. Hover over a component's name in the file tree
3. Try to click on a component's name in the file tree

*or*

1. Visit the file detail page of a file in the top level of a project that has components
2. Hover over a component's name in the file tree
3. Try to click on a component's name in the file tree

## Outcome
In all cases, the component title does not link anywhere. No effect is shown on hover and the user cannot click on the name to visit that component.
![screen shot 2015-07-14 at 1 51 35 pm](https://cloud.githubusercontent.com/assets/4965832/8680463/79cad4ce-2a2f-11e5-875e-cf523ab5fff9.png)

## Expected outcome
In all cases, the component title should link to that component's overview page. There should be an underline on hover (like on the project organizer) to indicate that it is a link.
![screen shot 2015-07-14 at 1 43 19 pm](https://cloud.githubusercontent.com/assets/4965832/8680450/694639a4-2a2f-11e5-81c7-0d15324e352b.png)

**Comment by hmoco** [comment]
Oh, I'm working on this.

**Comment by hmoco** [comment]
This should be good to go on #3608

**Comment by sloria** [comment]
Patch has been merged. Will be released in 0.43.0
