### ISSUE TITLE
User Settings - Authorized Projects list in Mendeley & Zotero do not clear out deleted projects

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3594]
### Steps
1. Go to [osf.io](http://www.osf.io)
2. Create a new project or fork an existing project
3. Configure and enable Mendeley and Zotero, as well as a storage add-on, in your project
4. Go to your User Settings page
5. Go to the Configure Add-ons page
6. Confirm that the new project appears as an Authorized Project under Mendeley, Zotero, and the storage add-on you chose
7. Go to the new project's Settings page
8. Delete the project
9. Go back to the Configure Add-ons page

### Expected behavior
I expected that the Configure Add-ons page would not display the deleted project anywhere.

### Actual behavior
Although the storage add-ons clear the deleted project from their Authorized Projects lists, Mendeley and Zotero still display it.

In this example, both "Fork of Benediction in the morning" (only enabled Mendeley) and "Tester" have been deleted, but they are still shown under in Mendeley and Zotero. If I click the link to them, I arrive at the Resource Deleted page.

![screen shot 2015-07-14 at 1 53 36 pm](https://cloud.githubusercontent.com/assets/8591162/8680495/bd4dc8aa-2a2f-11e5-920e-4556ebcdd774.png)

**Comment by hmoco** [comment]
I am working on this @GaryKriebel

**Comment by jinluyuan** [comment]
I also just noticed that clicking the "x" button of these deleted projects does nothing, so they are stuck in the list until we put a fix in.

**Comment by hmoco** [comment]
#3631 Fixes this !
