### ISSUE TITLE
add public activity back to explore dropdown

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3599]
The link to view public activity was removed from the "explore" dropdown. Unless there is a reason for this, it should be added back. 

![screen shot 2015-07-14 at 2 57 20 pm](https://cloud.githubusercontent.com/assets/4965832/8682000/a7ae87f6-2a38-11e5-8fa4-d8b07421e714.png)

**Comment by GaryKriebel** [comment]
It was removed and made it's own visible link (Browse New Projects) when not logged in

![screen shot 2015-07-14 at 3 00 22 pm](https://cloud.githubusercontent.com/assets/9437946/8682112/24a587a0-2a39-11e5-9011-c336f8377469.png)

but you are correct in when you log it is not available:

![screen shot 2015-07-14 at 3 01 19 pm](https://cloud.githubusercontent.com/assets/9437946/8682123/3472d516-2a39-11e5-8c29-42ed9ed0a822.png)

**Comment by jinluyuan** [comment]
This was addressed in https://github.com/CenterForOpenScience/osf.io/issues/3326.
PR https://github.com/CenterForOpenScience/osf.io/pull/3332 is waiting for a consensus. 
@jlcohoon Could you help figure out the best way to link to it?

**Comment by sloria** [comment]
As an alternative to the suggestions in https://github.com/CenterForOpenScience/osf.io/pull/3332, maybe we keep the navbar behavior as is and just add Public Activity to the Explore dropdown. This seems to be what @jlcohoon is suggesting anyway in this issue.

This will mean that there will be two links to get to the Public Activity page when you are logged out. I don't think this degrades usability.

**Comment by jlcohoon** [comment]
That's what I thought would happen. I think that the reason to move it out of the dropdown was to surface the functionality for non-users ("you can enjoy the OSF without an account!"), but when you're logged in that matters less. However, I just commented on the PR that I like Andrew's idea. Basically I'm content with whatever as long as it exists.

**Comment by GaryKriebel** [comment]
I'm fine with @sloria suggestion as well
