### ISSUE TITLE
"Add Links" modal: Add spinner when search results are loading

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3611]
## Steps

1. Log in to osf.io
2. Navigate to one of your projects.
3. In the components widget, click on "Add Links."
4. Search all projects for "Psych".
5. From page 1 of the results, click to the last page of the results.
6. Notice the behavior.

## Expected Behavior

I expect that while the page loads, I will see a spinner, as when logs are loading:

![loading_logs](https://cloud.githubusercontent.com/assets/7093086/8689044/fbc1e95e-2a70-11e5-80fa-73d66e6f851a.png)

## Actual Behavior

There are 28 pages of results in this example, and clicking between pages (especially from page 1 to page 28) takes awhile. While the load occurs, nothing appears to be happening. With more pages of results, the lack of a spinner informing the user what is going on becomes more noticeable. Blue highlighting of the page number doesn't occur until the load has finished, so the user doesn't know for sure if the request is being processed. Adding a spinner will enhance the user experience.

**Comment by Johnetordoff** [comment]
@lbanner There was a slight mix up and I should be assigned to this issue, could you do that?
