### ISSUE TITLE
Improve language on Forks tab

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3612]
## Steps

On production, navigate to one of your projects that has not been forked before and click on the "Forks" tab.

## Current text

There have been no forks of this project. Forking a project means you have created a copy of it into your dashboard, and can change that copy for your own purposes. You will be the only contributor to the forked project until you add others.

## Proposed change

This project has not been forked. When you fork a project, you create a copy of the project that appears in your dashboard, and you can change that copy for your own purposes without affecting the original project. You will be the only contributor to the forked project until you add others.

**Comment by Johnetordoff** [comment]
@lbanner can I go ahead and implement this change?

**Comment by lbanner** [comment]
:+1:

**Comment by sloria** [comment]
I think we can simplify the language even further:

> This project has no forks. A fork is a copy of a project that appears that you can change without affecting the original project.

**Comment by NatashaRichter** [comment]
@sloria Thanks--I like the much more simplified language. :+1: For more info, users can always head to the Getting Started page anyway.
