### ISSUE TITLE
Zotero, Mendeley addons don't have READMEs for setup

### ISSUE THREAD

**Issue by hmoco** [CenterForOpenScience/osf.io#3616]
## Steps
1. Go to the folder osf/website/addons/mendeley (or zotero)
2. Look for a readme on how to set them up locally
3. Realize there is none
4. Cry

## Expected
Much like github, googledrive, and box, there should be a README.md file detailing how to setup those addons locally.

## Actual
There is none.

**Comment by Johnetordoff** [comment]
@hmoco did you ever successfully set these up? I'm trying now and getting errors from Zotero.

**Comment by hmoco** [comment]
@Johnetordoff I never did try to setup Zotero. I did, however, get Mendeley working.

**Comment by Johnetordoff** [comment]
@hmoco do you know who would know about setting up Zotero?

**Comment by GaryKriebel** [comment]
fixed in release 0.66
