### ISSUE TITLE
only show "OSF Storage" folder if other add-ons are present

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3617]
from the community repo: https://github.com/CenterForOpenScience/community/issues/210

## Current Behavior
Presently, every project and component on the OSF requires that OSF Storage be available. This means that in the file tree of a project, every project and component has an "OSF Storage" folder listed, whether it is empty or not.

![screen shot 2015-07-15 at 12 00 00 pm](https://cloud.githubusercontent.com/assets/4965832/8703002/0e16838a-2ae9-11e5-856c-683ba2f651ef.png)

## Suggested Behavior
OSF Storage folders should not appear when there are no other add-ons present. This would mean that only project names and component names would show in the file tree for a majority of users. Instead of clicking on an "OSF Storage" folder to upload a file, the user would simply click on the project/component title. Files would be listed directly under the project/component title.
If an add-on is present in a project/component, then the "OSF Storage" folder would be visible if the user uploaded a file to that component's OSF Storage (but not if there were no OSF Storage files).

**Comment by brianjgeiger** [comment]
This should be a UI-only change. Back end functionality should not be added to support this.

**Comment by csoderberg** [comment]
+1 form Piper Mullins at the Smithsonian

**Comment by jlcohoon** [comment]
+1 from Richard and Norm who note that because of the extra levels/labels that components come with (i.e. "OSF Storage") they are more inclined to use folders, despite the reduced functionality. They think that having fewer items in the file tree makes it more approachable, especially for new users.

**Comment by GaryKriebel** [comment]
Closed
