### ISSUE TITLE
Change private component icons to be consistent and match other OSF icons

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3619]
### Steps
1. Go to [osf.io](http://www.osf.io)
2. Go to a public project that has private components
3. Ensure that the private components are of three different types - uncategorized, project, and another category
4. Create a link in the project to a private project
5. View the public project's overview page as a non-contributor/logged-out user

Example project: [On staging](https://staging.osf.io/rcmpf/)

### Expected behavior
I expected that the icon for all of the "Private Component" rows to be the same.

### Actual behavior

Private component icons in the file tree look like this for Uncategorized and all categories other than "project":
![screen shot 2015-07-15 at 2 25 10 pm](https://cloud.githubusercontent.com/assets/8591162/8706459/d0e648fa-2afd-11e5-9da0-4e3e5e0acfb7.png)

Icon for private component in the "project" category:
![screen shot 2015-07-15 at 2 25 03 pm](https://cloud.githubusercontent.com/assets/8591162/8706496/07495ba8-2afe-11e5-83c1-623ec3e2709f.png)

Icon for private component that is a linked project: 
![screen shot 2015-07-15 at 2 30 27 pm](https://cloud.githubusercontent.com/assets/8591162/8706506/1a763a7a-2afe-11e5-904c-34dda0ca8f68.png)

It would be better if they were all the same icon, regardless of type, in order to maintain the intended private nature of the component. Furthermore, the general private component icon, the yellow folder, does not match the style of the other icons (from Font Awesome).

![screen shot 2015-07-15 at 2 39 18 pm](https://cloud.githubusercontent.com/assets/8591162/8706719/4f982ffa-2aff-11e5-8111-0384f8a3d8fc.png)

I think it would make sense for all the private component/link icons to be a [lock](http://fortawesome.github.io/Font-Awesome/icon/lock/). This best represents the privacy of the component.

**Comment by lbanner** [comment]
Is there a StyleGuide approach to this @caneruguz ?

**Comment by sloria** [comment]
This is a clear inconsistency--the icon differs in one place from all other places. Not sure that this needs a Style Guide discussion. I recommend we go ahead and fix it for now.

**Comment by lbanner** [comment]
:+1:

**Comment by GaryKriebel** [comment]
I concur

**Comment by caneruguz** [comment]
This is not a styleguide issue as Steve said, it's an oversight that should have been fixed during the transition of icons a while ago. I can be assigned to do this.

**Comment by lbanner** [comment]
Done @caneruguz

**Comment by caneruguz** [comment]
@lbanner just sent a PR for this issue: https://github.com/CenterForOpenScience/osf.io/pull/4002

**Comment by lbanner** [comment]
Got it!
