### ISSUE TITLE
Private Link in file tree should say "Private Link", not "Private Component"

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3621]
### Steps
1. Go to [osf.io](http://www.osf.io)
2. Go to one of your public projects
3. Add a link to a private project
4. View your public project as a non-contributor/logged-out user

### Expected behavior
I expected that the private link's listing in the Files widget file tree would match its listing in the Components widget (which says "Private Link").

![screen shot 2015-07-15 at 2 43 49 pm](https://cloud.githubusercontent.com/assets/8591162/8706913/5bd91076-2b00-11e5-9bfe-7aebe816df21.png)

### Actual behavior
The private link is listed as "Private Component" in the file tree. 

![screen shot 2015-07-15 at 2 30 27 pm](https://cloud.githubusercontent.com/assets/8591162/8706904/52a02382-2b00-11e5-88e2-271b1cefd9b0.png)

**Comment by haoyuchen1992** [comment]
I am OK with displaying as "private link". But my question is that why we need display all the private components or links as  a number of empty and same boxes. I think it is better  to add one sentence, such as "private components are not shown". In our current design, we spends too much space on delivering that message.

What do you think? @caneruguz @lbanner @GaryKriebel

**Comment by brianjgeiger** [comment]
#2951

**Comment by lbanner** [comment]
Ties these together then?

**Comment by brianjgeiger** [comment]
They don't have to be solved at the same time, but they should use the same solution from the end-user's perspective (i.e. 3 Private Projects, 1 Private Link or whatever)

**Comment by jinluyuan** [comment]
@lbanner I think these are different issues since Johanna & Haoyu's ideas are bigger feature changes, but I am simply requesting that the file tree on the Project Overview page say "Private Link" instead of "Private Component".

![screen shot 2015-07-17 at 3 50 14 pm](https://cloud.githubusercontent.com/assets/8591162/8755858/f71941f4-2c9b-11e5-88c6-fa5729a34e9f.png)

**Comment by lbanner** [comment]
Good point -- We'll keep this one narrow, and deal with the bigger issue via the other. Thanks!

**Comment by haoyuchen1992** [comment]
Yes, limited to this text change. I am starting to work on this now. :)

**Comment by caileyfitz** [comment]
@lbanner @haoyuchen1992 What about the case where the link is also a fork? There is still a discrepancy in wording:

![link vs fork](https://cloud.githubusercontent.com/assets/5975444/8861378/20b0785a-3158-11e5-94e1-ec46cb548d2c.png)

What should we do in this case?

**Comment by lbanner** [comment]
:anguished:

**Comment by jinluyuan** [comment]
"Private Linked Fork"

**Comment by haoyuchen1992** [comment]
I just checked the code in render_node.mako. It shows there are four cases. Now it only deal with two.

            %if summary['is_registration']:
                Private Registration
            %elif summary['is_fork']:
                Private Fork
            %elif not summary['primary']:
                Private Link
            %else:
                Private Component
            %endif

**Comment by caileyfitz** [comment]
I say we implement what the mako template does. That seems the easiest in terms of decisions because someone already wrote that and had rationale for it

**Comment by caileyfitz** [comment]
So just have the files grid implement the same logic?

**Comment by haoyuchen1992** [comment]
@caileyfitz Yes, the logic is implemented in python. So it is a little bit different from mako implementation.

**Comment by caileyfitz** [comment]
@haoyuchen1992 Does that mean that you can or cannot have the files grid match the wording in the component widget?

**Comment by haoyuchen1992** [comment]
@caileyfitz Theoretically , I can do that. Because node object should have all the information about a project. But I need spend some time on finding how the information are defined.

**Comment by caileyfitz** [comment]
@haoyuchen1992 Let me know when this is implemented so we can test the cases where the link is also a fork and a registration!

**Comment by haoyuchen1992** [comment]
@caileyfitz  After the new PR #3803  merged, it will be good to be tested！

**Comment by caileyfitz** [comment]
@haoyuchen1992 Great - thanks!

**Comment by caileyfitz** [comment]
@haoyuchen1992 I just took a look at this, and it seems like now there are different icons in the file grid. Not sure what gets a box icon vs folder icon though:

![screen shot 2015-07-28 at 3 03 59 pm](https://cloud.githubusercontent.com/assets/5975444/8940813/e8fa0774-3539-11e5-925b-1c38010d6a75.png)

Is this intended?

**Comment by jinluyuan** [comment]
@caileyfitz These different private icons are covered in issue https://github.com/CenterForOpenScience/osf.io/issues/3619. Basically, the Private Components with project icons are *actually* projects (or components in the "project" category).
