### ISSUE TITLE
Google files do not have file extensions when downloaded as part of a zip

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3622]
Reported by me on the 0.42 Trello board:

### Steps
1. Go to [osf.io](http://www.osf.io).
2. Go to one of your projects that has Google Drive enabled and configured.
3. Make sure your selected Google Drive folder contains .g documents (Google Sheets, Google Docs, and Google Slides).
4. In your project's files tree, scroll to the Google Drive add-on.
5. Click the folder that has the .g files in it.
6. Click the "Download as zip" button that appears in the file tree's top menu.
7. Check your Downloads folder for the files
8. Go back to the file tree and download each file individually.
9. Check your Downloads folder for the individual files

### Expected behavior
I expected that when I downloaded the .gsheet, .gdoc, and .gslide files as part of a zip folder, they would download with the .xlsx, .docx, and .pptx file extensions that they do when downloaded individually.

### Actual behavior
If I download them together in a zip, the files do not have any file extensions. I can manually add the file extensions, and the files will work properly.

**Comment by GaryKriebel** [comment]
Fixed w/ release 68
