### ISSUE TITLE
Change case in blue alert on component's page

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3623]
I reported this on the 0.42 trello board.

# Steps

1. Log in to osf.io. 
2. Navigate to a project for which you have admin access.
3. Create a component.
4. Notice the blue alert on the top of the new component page.

# Suggested change:

Change case of "Project Page" to lowercase "project page" to match other places on the site where the word "project" is lowercase in alerts.

# Screenshots:

First attachment shows where "projects" are referred to in lowercase. Second attachment shows the uppercase "Project Page."

![lowercase_project](https://cloud.githubusercontent.com/assets/7093086/8707042/4f76b6ac-2b01-11e5-83eb-af4939969003.png)

![uppercase_project](https://cloud.githubusercontent.com/assets/7093086/8707061/79d9252e-2b01-11e5-92d5-22c6d360a8e3.png)

**Comment by lbanner** [comment]
Good catch -- Is there StyleGuide direction on this one @NatashaRichter

**Comment by Johnetordoff** [comment]
@lbanner can I get on this?

**Comment by Johnetordoff** [comment]
The Style Guide doesn't say anything about case, but this should probably be lower case just so we can remain consistent.

**Comment by lbanner** [comment]
Agreed.
