### ISSUE TITLE
Add Links modal: Long project names extend out of modal

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3625]
Reported on the 0.42 Trello board: 

## Steps
1. Go to a project you have admin on
2. On the project overview page click on the project title to edit the name
3. Enter text up to the max capacity without spaces; click the check mark to save the changes
4.Go to another project you have admin access on
5. On the project overview page, click the 'Add Links' button in the component widget
6. Enter the first few letters from the long named project title in the text field and click 'search my projects'
7. Look at the results
8. Click the + next to the 'Deer Creek ....' project
9. Look at the modal

## Expected 
I thought this would be fixed, per this
 PR https://github.com/CenterForOpenScience/osf.io/pull/2840
and issue https://github.com/CenterForOpenScience/osf.io/issues/2778

## Actual
The project name extends outside of the modal

**Comment by Johnetordoff** [comment]
@lbanner can I get this?

**Comment by lbanner** [comment]
:+1:
