### ISSUE TITLE
Project/Registrations overview page: "Contributors" link would look better with a solid underline

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3628]
Reported on the 0.42 trello board by @jinluyuan 

## Description

On Project and Registration overview pages, the link to Contributors has a dashed line. Although the dashed line is mentioned as a link option in the [Style Guide](https://centerforopenscience.github.io/osf-style/style.html#links), on this page, it doesn't make much sense. It sticks out too much as the only link with a dashed line. The Style Guide doesn't talk about when to use each style of link. 

In the screenshot below, notice the link in the blue warning above as a point of comparison.

## Screenshot

![dashed_underline](https://cloud.githubusercontent.com/assets/7093086/8707389/63bbff3a-2b03-11e5-841f-bf04376a53b9.png)

**Comment by chennan47** [comment]
This is a designed behavior as we don't want it to draw too much user's attention. Altho there is a bug here, the text of the contributor are supposed to be black instead of blue for the same purpose.

**Comment by NatashaRichter** [comment]
Got it! Thanks @chennan47 

Would you like me to report the bug about the text color of the contributor?

**Comment by chennan47** [comment]
@NatashaRichter yes, pls and close this one. Thanks.
