### ISSUE TITLE
Watch & Duplicate buttons should not be in a button group

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3630]
It doesn't make sense that Watch and Duplicate should be a button group since they do not have any relationship with each other. [UI Guide](https://centerforopenscience.github.io/osf-style/ui.html#button-state)

![screen shot 2015-07-15 at 4 04 05 pm](https://cloud.githubusercontent.com/assets/8591162/8708792/2050a1ac-2b0c-11e5-9903-9acb8f2bc993.png)

**Comment by Johnetordoff** [comment]
@lbanner should I go ahead with this?

**Comment by jinluyuan** [comment]
If the purpose behind making these two buttons into a button group was to minimize the amount of individual buttons, then I would say that it makes more sense for the Add to Dashboard button and Watch button to be in a button group. Otherwise, three individual buttons works!

**Comment by lbanner** [comment]
@Johnetordoff -- Yes -- can you post screenshot of proposed change in buttons/UI when you have it? Thanks.

**Comment by Johnetordoff** [comment]
How's this?
![screen shot 2015-07-29 at 10 27 38 am](https://cloud.githubusercontent.com/assets/9688518/8960123/7e9a3a5e-35dc-11e5-8cd9-22ebba5e44d5.png)
