### ISSUE TITLE
Getting Started page: Update add-on info to reflect recent button changes

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3632]
## Description

With the new style guide changes implemented, we need to update the add-on info on the Getting Started page under "Storage Options" to reflect button changes.

## Screenshots and Changes

**Dropbox**

![dropbox_buttons](https://cloud.githubusercontent.com/assets/7093086/8709502/a27b1f28-2b10-11e5-8288-3e7827f650d0.png)

Change "submit" to "click Apply."
Change "authorize" to "Import Access Token".
Eventually, the "Ok" button language will need to change.

**Github**

![github_buttons](https://cloud.githubusercontent.com/assets/7093086/8709383/e5be16ce-2b0f-11e5-8e7a-f710b3abe157.png)

Change "submitting" to "clicking Apply".
Change "blue" to "green Save".
Eventually, the "Ok" button language will need to change.

**Amazon S3**

![amazons3_buttons](https://cloud.githubusercontent.com/assets/7093086/8709312/73b7cb88-2b0f-11e5-8f68-205ba5738884.png)

Change "Submit" to "Save" in both instances.
Eventually, the "Ok" button language will need to change.

**Figshare**

![figshare_buttons](https://cloud.githubusercontent.com/assets/7093086/8709306/5becc404-2b0f-11e5-94d0-d6b3e5864068.png)

Change submit to "save."
Change "authorize" to "Import Access Token."
Eventually, the "Ok" button language will need to change.

**Dataverse**

![dataverse_buttons](https://cloud.githubusercontent.com/assets/7093086/8709093/0a17f8c0-2b0e-11e5-89e3-4496fc39c39a.png)

Change "Submit" to "Save" in both instances.
Change "authenticate with Dataverse by selecting" to "import your access token and select"

**Box**

![box_buttons](https://cloud.githubusercontent.com/assets/7093086/8709223/e4d05b2e-2b0e-11e5-8657-814a328ccc20.png)

Change submit to "click Apply."
Change "authorize" to "Import Access Token."
Eventually, the "Ok" button language will need to change.

**Google Drive**

![googledrive_buttons](https://cloud.githubusercontent.com/assets/7093086/8709609/79e15036-2b11-11e5-93a6-0062bf2b1fb0.png)

Change "submit" to "apply."

**Mendeley**

![mendeley_buttons](https://cloud.githubusercontent.com/assets/7093086/8709645/cc667ed0-2b11-11e5-87aa-25dfcfa82d27.png)

Change first instance of "submit" to "apply."
Change second instance of "submit" to "save."

**Zotero**

![zotero_buttons](https://cloud.githubusercontent.com/assets/7093086/8709724/a1635dba-2b12-11e5-9143-614aeaa4486c.png)

Change "submit" to "apply."

**Comment by jlcohoon** [comment]
We might wait for this until the add-on settings change more. Which should be very soon, no?

**Comment by lbanner** [comment]
Good point @jlcohoon -- I labeled as 'Hold' for now.

**Comment by NatashaRichter** [comment]
Sounds good to me! I'll try to find out when the other changes will be implemented.
