### ISSUE TITLE
Fix typos on Getting Started page

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3633]
## Description

Fix typos in the following sections on the Getting Started page.

## Screenshots and Changes

**Contributors section**

![contributors_typos](https://cloud.githubusercontent.com/assets/7093086/8707653/1730ce82-2b05-11e5-966a-ecda487ab138.png)

Change "contributor" to "the contributor."

**Citations section**

![citations_typo](https://cloud.githubusercontent.com/assets/7093086/8709924/fc532844-2b13-11e5-858e-e710cf2d6e71.png)

Change "ill" to "will"

**View-only Links section**

![viewonly_typos](https://cloud.githubusercontent.com/assets/7093086/8707763/c5a1ef8c-2b05-11e5-91b7-af609640a3a6.png)

Change the en dashes to em dashes. Change "chose" to "choose."

**Comment by Johnetordoff** [comment]
@lbanner can I get this one?

**Comment by lbanner** [comment]
:+1:

**Comment by sloria** [comment]
I've cherry-picked this change onto master, so this is on prod now.
