### ISSUE TITLE
re-arrange project settings to put notification and comment configuration next to each other

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3634]
From the community repo: https://github.com/CenterForOpenScience/community/issues/287

## Current Behavior
Project settings places the commenting section and the notification section apart from one another (add-ons are in between). 
![screen shot 2015-07-15 at 6 06 04 pm](https://cloud.githubusercontent.com/assets/7749914/8711034/59e836d6-2b1c-11e5-8927-5123664db53c.png)

## Suggested Behavior
The order of the settings page should be re-arranged so that "configure commenting" and "configure notifications" are next to one another, as the content is related.

**Comment by Johnetordoff** [comment]
@lbanner can I get this?
