### ISSUE TITLE
Project Overview: Discrepancy between spacing of widgets

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3636]
## Steps

Navigate to one of your projects on Production. On the Project Overview (or Component Overview) page, compare spacing between widgets. 

## Expected Behavior

I expect that all widgets will be equally spaced.

## Actual Behavior

Notice that there is slightly more space between the Recent Activity widget and the Tags widget than between the other widgets on the page.

## Screenshot

![widget_spacing_proj_overview](https://cloud.githubusercontent.com/assets/7093086/8727346/3025ea82-2bad-11e5-8a5c-ad2589b2d5ac.png)

**Comment by Johnetordoff** [comment]
@GaryKriebel Can I get this one?
