### ISSUE TITLE
Links icon incorrect on wiki menu

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3637]
# Steps
1. Go to a project on which you have admin access
2. Add a link to the project (link another project for which you have admin access)
3. Go to the Wiki tab
4. On the left side of the page, look at the wiki menu > Component Wiki Pages

# Expected 
I expect that the linked project would have a link icon, just as it does on the project overview page: 
![project overview](https://cloud.githubusercontent.com/assets/5975444/8727840/e94b82a4-2baf-11e5-8987-60fe813d82f1.png)

# Actual
The linked project has a pointer icon, which does not appear anywhere else on the site:
![wiki page menu](https://cloud.githubusercontent.com/assets/5975444/8727856/007d75fe-2bb0-11e5-9a27-087447a57fbc.png)

**Comment by Johnetordoff** [comment]
I'm a little confused about replicating this. I went to the wiki tab and got this screen,

![screen shot 2015-07-20 at 1 36 52 pm](https://cloud.githubusercontent.com/assets/9688518/8782594/89c20cc6-2ee4-11e5-9371-c46efff98b31.png)

which doesn't correspond to the pic.

**Comment by caileyfitz** [comment]
Yes @Johnetordoff that is because @caseyrollins recently changed the wiki tree over to treebeard, so this should no longer be an issue.

**Comment by caneruguz** [comment]
@caileyfitz to clarify, should this issue be closed?

**Comment by caileyfitz** [comment]
Yes, I can close this
