### ISSUE TITLE
Cannot restore deleted comments

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3638]
## Steps

1. Log in to osf.io.
2. Navigate to one of your own projects.
3. Create a comment on the project.
4. Delete the comment by clicking the trash icon and then confirming by clicking the red "Delete" button.
5. Click to restore the comment.
6. Hit the green Save button.

## Expected Behavior

I expect that my deleted comment will show up again. 

## Actual Behavior

The comment does not restore, nor am I given any feedback for why it is not restoring.

In my console, I am seeing 404 errors.

## Screenshot

![404_commenting_error](https://cloud.githubusercontent.com/assets/7093086/8728227/ed1cdfde-2bb1-11e5-955c-8a641de2e7a6.png)

**Comment by brandonPurvis** [comment]
I can work on this.

**Comment by lbanner** [comment]
:+1:
