### ISSUE TITLE
Recent Activity - "No logs to show" flashes for a brief, but noticeable second, before logs load

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3641]
### Steps
1. Go to [osf.io](http://www.osf.io)
2. Go to any public project
3. Look at the Recent Activity widget
4. Refresh the page while keeping your eye on Recent Activity

### Expected behavior
I expected there to be a "Loading" message or just blank white space until the logs loaded.

### Actual behavior
This flashes for a brief second before the Loading message and then the actual logs.

![screen shot 2015-07-16 at 12 08 07 pm](https://cloud.githubusercontent.com/assets/8591162/8728513/828e944e-2bb3-11e5-8a1b-c051819b5946.png)

This issue may be related to https://github.com/CenterForOpenScience/osf.io/issues/3233.

**Comment by Johnetordoff** [comment]
@GaryKriebel Can I take this?

**Comment by lbanner** [comment]
Done!
