### ISSUE TITLE
Project Settings Dataverse message - change phrasing from "node" to "project/component"

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3644]
### Steps
1. Go to [osf.io](http://www.osf.io)
2. Go to your User Settings
3. Enable and configure Dataverse for a Dataverse account that has no actual content in it
4. Go to one of your projects or components
5. Go to the project's Settings page
6. Import the Dataverse account you just connected to in User Settings
7. Notice the blue message that appears

### Expected behavior
I expected that the blue message would say "The Dataverse user associated with this project/component does not currently have any Dataverses."

### Actual behavior
![screen shot 2015-07-16 at 12 21 55 pm](https://cloud.githubusercontent.com/assets/8591162/8728899/dd0006f4-2bb5-11e5-9c79-27c5aba36b3a.png)

**Comment by Johnetordoff** [comment]
@GaryKriebel I can you put me on this?

**Comment by jinluyuan** [comment]
@Johnetordoff I think a better sentence might be "There are no dataverses, datasets, or files associated with the connected account."
This better matches Dataverse's own message for empty accounts.

![screen shot 2015-07-16 at 3 47 25 pm](https://cloud.githubusercontent.com/assets/8591162/8733481/00ff3a2c-2bd2-11e5-9c79-d6a4430902c3.png)

**Comment by lbanner** [comment]
Good @jinluyuan

**Comment by lbanner** [comment]
Since not merged yet, will keep this open for now.

**Comment by Johnetordoff** [comment]
@lbanner can we close this?

**Comment by jinluyuan** [comment]
@Johnetordoff Closed!
