### ISSUE TITLE
[Feature Request] Dashboard: The list of legends under the information button should be vertical and alphabetized

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3645]
# Steps
1. Log into osf.io
2. On your dashboard, click on the information button (“i", next to “Search”)
3. Ensure you get a modal with a list of legends

# Expected
The legends are listed vertically and alphabetically for easy find

# Actual
The list is presented horizontally and also is not alphabetized which makes it difficult to read and find the desired legend

![legend modal could be updated](https://cloud.githubusercontent.com/assets/10926926/8729895/c489eaa8-2bbb-11e5-9dd7-fbe111450598.png)

**Comment by MPNussbaum** [comment]
@GaryKriebel, would you please assign me to this?

**Comment by caneruguz** [comment]
@MPNussbaum how is this fix coming along? I have made minor changes to the legend so there might be merge conflicts. https://github.com/caneruguz/osf.io/commit/c7f1d40bda2ec3cd314814de27a8c7521289b610

**Comment by chennan47** [comment]
this is fixed by https://github.com/CenterForOpenScience/osf.io/pull/4053
