### ISSUE TITLE
Linked projects in registrations have buttons for forbidden actions

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3646]
# Steps
1. Go to a project for which you have admin access
2. Add a link to the project
3. Confirm that the link appears in the component list on the right side of the project overview page
4. Take note of the actions which appear to the right of the link title (**x**, fork icon, plus sign)
5. Register the project
6. Go to the project registration
7. In the component list on the project registration overview page, locate the link
8. Look at which actions appear to the right of the link title

# Expected
I expect that the link will be listed among the project components but that only the plus sign would appear since the other actions are forbidden.

# Actual
The link on a project registration page has the same three action buttons as it does on a non-registered project. 
![link registration](https://cloud.githubusercontent.com/assets/5975444/8730779/0f684204-2bc1-11e5-963d-72c6950227f5.png)

The actions are forbidden, however, and a user gets error messages after clicking the buttons:

### Remove this link
![registered nodes immutable](https://cloud.githubusercontent.com/assets/5975444/8730785/18550d02-2bc1-11e5-8478-1837fdb7d572.png)

### Fork this project into project XYZ
![could not fork link](https://cloud.githubusercontent.com/assets/5975444/8730792/1d7e4500-2bc1-11e5-8b69-650faef25265.png)

# Suggested Fix
Why don't we just remove these icons for links on registered projects?

**Comment by XTech2K** [comment]
Can I nab this? It's a quick fix and I have it almost prepared already.

**Comment by nanchen47** [comment]
The fix has been deployed.
