### ISSUE TITLE
Change category button flashes for parent project

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3649]
# Steps
1. Go to a parent project for which you have admin access
2. Go to the settings page
3. Immediately as the page loads, pay attention to the Configure Project container at the top of the page

# Expected
Since this is a parent project and thus the category cannot be changed, I would expect that there would be no option to change the category, no matter how briefly it may appear.

# Actual
When the page first loads, buttons to change the category of the project appear for a split second:
![parent project change button](https://cloud.githubusercontent.com/assets/5975444/8731570/4b01e2fc-2bc6-11e5-9aa1-c8a17c758605.png)

Quickly, it goes away and the page appears as it is supposed to:
![parent project no button](https://cloud.githubusercontent.com/assets/5975444/8731581/5b7c1206-2bc6-11e5-9f65-a2c860acad43.png)

It would be ideal if the Change/Cancel buttons do not appear *at all* on the page

**Comment by Johnetordoff** [comment]
@lbanner can I get this?

**Comment by lbanner** [comment]
Yep!

**Comment by caileyfitz** [comment]
@sloria @Johnetordoff this problem has returned!!! We need to re-open this!

**Comment by lbanner** [comment]
:anguished:

**Comment by caileyfitz** [comment]
Related: the error message now flashes before category is displayed for every node, whether a parent project or a component and despite current category: 

Error message flashes: 
![screen shot 2015-07-30 at 10 40 05 am](https://cloud.githubusercontent.com/assets/5975444/8985931/a461111a-36a7-11e5-8b63-1d64d73c86d3.png)

Message goes away after load: 
![screen shot 2015-07-30 at 10 40 05 am 1](https://cloud.githubusercontent.com/assets/5975444/8985938/ab298c70-36a7-11e5-9e0f-cf60ae540136.png)
