### ISSUE TITLE
Fix language of "Resend Email Confirmation" modal

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3650]
## Steps

1. Head to your User Settings > Account Settings
2. Under "Unconfirmed Emails," add a secondary email address. 
3. Click "Add Email" and then click the blue "resend confirmation" that appears. 
4. Notice modal that appears.

## Current Language

The text of the modal that appears reads, "Are you sure that you want to resend email confirmation at nadiya@gmail.com"

The text is missing a question mark and needs to be phrased better. 

## Change to:

"Are you sure that you want to resend email confirmation **to** nadiya@gmail.com?"

## Screenshot

![resend_email_modal](https://cloud.githubusercontent.com/assets/7093086/8731870/17c22864-2bc8-11e5-9b44-8f38dfe7e78b.png)

**Comment by Johnetordoff** [comment]
@GaryKriebel I can do this
