### ISSUE TITLE
Change project & comment expansion icon from plus sign to down arrow for consistency

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3651]
The expansion icons in the Dashboard and a project's Citations widget are light blue down arrows, which are both attractive and easy to understand.

![screen shot 2015-07-16 at 2 22 05 pm](https://cloud.githubusercontent.com/assets/8591162/8731619/9ce6cdf8-2bc6-11e5-8c79-5dd74cb81bf6.png)
![screen shot 2015-07-16 at 2 27 51 pm](https://cloud.githubusercontent.com/assets/8591162/8731655/dcfbf26a-2bc6-11e5-823b-7b65c615c2db.png)

However, in other areas of the site, a bold black plus sign + is used for expansion.

### User profile
![screen shot 2015-07-16 at 2 22 58 pm](https://cloud.githubusercontent.com/assets/8591162/8731620/9ced0862-2bc6-11e5-9bd7-30757005e8b5.png)

### Components widget of project overview 
![screen shot 2015-07-16 at 2 23 09 pm](https://cloud.githubusercontent.com/assets/8591162/8731622/9ceec09e-2bc6-11e5-80bf-9ef00440ea09.png)

### Registrations page
![screen shot 2015-07-16 at 2 22 11 pm](https://cloud.githubusercontent.com/assets/8591162/8731623/9ceee164-2bc6-11e5-9a4e-0206ac20857a.png)

### Comments with replies
![screen shot 2015-07-16 at 2 22 38 pm](https://cloud.githubusercontent.com/assets/8591162/8731621/9cee2a62-2bc6-11e5-9b8a-4928207ce0f7.png)

A plus sign is ambiguous since it can represent "more" or "add". We have tooltips when hovering over the Components widget plus signs, but that is the only place where a user would see that. Users may not immediately recognize what the plus sign means, and the Add to Dashboard button's plus sign can only further confuse them. 
![screen shot 2015-07-16 at 2 37 55 pm](https://cloud.githubusercontent.com/assets/8591162/8731955/8bfe108a-2bc8-11e5-94ff-4ceb783c2905.png)

Also, the black plus sign is the same size and color as the icons to the left of a project name, and this can clutter the project container since the plus sign is so noticeable. It would be best if we could make the plus sign a light blue (or gray/black) down arrow, just like the Dashboard.

**Comment by GaryKriebel** [comment]
@caneruguz ... part of style guide?

**Comment by caneruguz** [comment]
@GaryKriebel not part of style guide but legitimate unification bug for osf. As @jinlu says, plus sign should not be used for expanding/collapsing. Let's tag this style and you can assign me.

**Comment by jinluyuan** [comment]
@caneruguz I just realized that this also applies to the Treebeard expansion icon. I think it would look better as a down arrow, but this might require more discussion.

Dashboard
![screen shot 2015-07-17 at 11 46 30 am](https://cloud.githubusercontent.com/assets/8591162/8751190/9fe8e6ae-2c79-11e5-944f-9054f74581c6.png)

Files tree
![screen shot 2015-07-17 at 11 47 12 am](https://cloud.githubusercontent.com/assets/8591162/8751191/9fe995fe-2c79-11e5-9741-a9f2d7ac9430.png)

**Comment by caneruguz** [comment]
@jinluyuan for treebeard the plus and minus icons should stay as they are. Other icons are not as visible for the type of grid that file browser provides.

**Comment by jinluyuan** [comment]
@caneruguz I understand. 
However, for the wiki menu, it does look strange having a "+" icon for New while also having plus icons next to the Components folder. The same issue applies to the Add to Dashboard button previously mentioned. It's not necessarily a problem, but it would be better to have consistent meaning behind each of our icons at some point.

![screen shot 2015-07-22 at 10 27 23 am](https://cloud.githubusercontent.com/assets/8591162/8827747/6def6952-305c-11e5-842e-e7650249aed1.png)

**Comment by caneruguz** [comment]
Okay I see that but this needs some discussion. In any case these icons on file browsers will not be the same icons as the expand icons we are talking about since they are too small. These icons would probably be carets and they would be facing right and down, not up and down. So this needs to be it's own issue.

**Comment by caneruguz** [comment]
@sloria you can close this after merge if everything is looking good.

**Comment by jinluyuan** [comment]
@caneruguz Did you decide not to change the plus icon in the Comments widget?

**Comment by caneruguz** [comment]
@jinluyuan No I just didn't see that. That's a terrible placement for the expansion icon though. What;s happening with comments, isn't it going to go through some changes? @sloria?

**Comment by jinluyuan** [comment]
@caneruguz I put in a [Trello card](https://trello.com/c/xdsRUYRF/143-comments-widget-icon-for-opening-up-replies-to-a-comment-differs-from-rest-of-site) about this in the 0.42 release. It used to look like this before Haoyu changed the plus sign and put it on the right of the box.

![](https://trello-attachments.s3.amazonaws.com/559c3b7719602e88644166b1/412x120/5887371463bf64894e870e8afbfde15e/Screen_Shot_2015-07-07_at_4.49.06_PM.png)
(I think the old style looks even worse than it does now.)

Ideally, I think a down arrow on the bottom left corner would look best.

**Comment by caneruguz** [comment]
Alternatively we need to come up with a standard expansion of non-panel items. We'll need to work on this a bit.
