### ISSUE TITLE
User Settings: Email confirmation alert not italicized correctly

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3652]
## Steps

1. Navigate to a project for which you have an unconfirmed secondary email address.
2. Navigate to your user settings.
3. Click on "Account Settings" in the side bar.
4. Under Unconfirmed Emails, click on "resend confirmation."
5. Notice italics in the green alert that pops up. 

## Expected Behavior

That only the email address will be italicized in the alert.

## Actual Behavior

The second sentence ("Please check your email and confirm") is also italicized.

## Screenshot

![green_alert](https://cloud.githubusercontent.com/assets/7093086/8732372/1e544fba-2bcb-11e5-89b0-92da0b52c81f.png)

**Comment by brandonPurvis** [comment]
I can take this one.
