### ISSUE TITLE
Create project form inputs don't have placeholder text

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#3658]
Unlike the other widgets, the "Create a project" widget does not have placeholder text for its input fields.

![osf___dashboard](https://cloud.githubusercontent.com/assets/2379650/8734180/434568b2-2bd6-11e5-9c41-400495268292.png)

Perhaps add "Required" as a placeholder for the Title field and "Optional description" for the Description field.

**Comment by Johnetordoff** [comment]
@GaryKriebel can I get this?
