### ISSUE TITLE
extra space after contributor names on public activity and registrations pages

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3669]
## Steps
1. Visit the public activity page: https://osf.io/explore/activity/
2. Look for a project with multiple contributors—look a their names.
3. Visit the registrations page of a project with multiple contributors: https://osf.io/atgp5/registrations/
4. Look at the contributor names below the registration name

## Outcome
1. Each contributor has an extra space after their name. In some cases this comes before a comma, in others, before an &

![screen shot 2015-07-17 at 11 31 49 am](https://cloud.githubusercontent.com/assets/4965832/8750782/72973450-2c77-11e5-8d03-36f3965020cb.png)

![screen shot 2015-07-17 at 11 31 12 am](https://cloud.githubusercontent.com/assets/4965832/8751087/feab4b4c-2c78-11e5-9dda-9c93a944c11b.png)

## Expected Behavior
1. Appropriate spacing should be used—contributors should not automatically have an extra space after their names.
Spacing is correct in search results and project overview pages.

**Comment by jinluyuan** [comment]
I noticed this too. It happens in all project/component containers, not just on the public activity page. Relevant [Trello card](https://trello.com/c/2QIU8n4V/65-public-activity-page-extra-space-between-contributor-and).

This is an example from an OSF user's profile page Public Projects widget:
![](https://trello-attachments.s3.amazonaws.com/55a66adf15c499b55aa312ee/491x161/905122975ef6f937a156bed668a5b171/Screen_Shot_2015-07-17_at_11.13.55_AM.png)

@haoyuchen1992 Are you working on fixing this?

**Comment by jlcohoon** [comment]
Not on *all* containers though—not on project overviews.

**Comment by jinluyuan** [comment]
@jlcohoon Ah weird!

**Comment by haoyuchen1992** [comment]
@jinluyuan I think this is the unnecessary space before an & has been deleted in an unmerged PR. And as for the comma, I am not sure this would be treated as an bug. Some discussion need here.

**Comment by jinluyuan** [comment]
@haoyuchen1992 I think this is a bug since the spacing should look like this: 

Project overview page
![screen shot 2015-07-17 at 2 00 18 pm](https://cloud.githubusercontent.com/assets/8591162/8753754/35357ff8-2c8c-11e5-8783-fd4c659adf22.png)

**Comment by jlcohoon** [comment]
Agreed, there should never be a space before a comma and should only ever have one before an ampersand

**Comment by haoyuchen1992** [comment]
I think this will be solved in this PR- https://github.com/CenterForOpenScience/osf.io/pull/3713

**Comment by jlcohoon** [comment]
Just noticed on staging that in the component widget there is *no* space before the ampersand. Maybe it got fixed too much?

![screen shot 2015-07-21 at 2 18 06 pm](https://cloud.githubusercontent.com/assets/4965832/8809097/69c3e298-2fb4-11e5-9946-6902f0b7b40b.png)
