### ISSUE TITLE
public activity should not show retracted registrations

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3671]
## Current Behavior
The public activity lists popular projects and registrations as well as new projects and registrations. Retracted registrations are included in the displayed projects. For example, this registration was listed under Popular Registrations: https://osf.io/ct8dx/ (Study of attention focus in different environments)

![screen shot 2015-07-17 at 11 45 05 am](https://cloud.githubusercontent.com/assets/4965832/8751143/576f442c-2c79-11e5-99e1-bb75245f2322.png)

## Expected Behavior
Retracted registrations should not be included in the public activity page.

**Comment by Johnetordoff** [comment]
@nanchen47 can I get this?
