### ISSUE TITLE
User Settings: Text of green alerts sometimes covers the "x"

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3673]
## Steps

1. Log in to osf.io.
2. Go to your User Settings.
3. Add some alternate email addresses (some shorter than others) and confirm them if necessary.
4. Switch your primary and alternate email addresses.
5. Notice the green alerts which pop up.

## Expected Behavior

I expect that regardless of the length of my email addresses, the text of the alerts will not run into the "x" on the right side of the alert.

## Actual Behavior

When email addresses are shorter, the alerts are smaller and text overflows onto the "x" in the alert. I am still able to click the "x" to exit the alert--I just cannot see it very well.

## Screenshot

![emailalerts](https://cloud.githubusercontent.com/assets/7093086/8752713/1d4166b2-2c84-11e5-84cb-196ae94c0ac9.png)

**Comment by Johnetordoff** [comment]
@nanchen47 Can I get this issue?

**Comment by caneruguz** [comment]
@lbanner I propose closing this issue in favor of #3700 ; which shows that there might be a bigger sitewide issue here. It might also very well be a regression bug, I'm happy to help with it.

**Comment by GaryKriebel** [comment]
Closing in favor of https://github.com/CenterForOpenScience/osf.io/issues/3700
