### ISSUE TITLE
[user claiming] Politely Declining Contributor Requests 

### ISSUE THREAD

**Issue by cbischak** [CenterForOpenScience/osf.io#368]
If a user is invited to a project there should be a way for that user to reject the invite to the project, aside from the link expiring which would inform the inviter of this.

A possible user story:
User Mary wishes to invite John Doe to a project. However, Mary invites the wrong John Doe to the project, as there exists several John Doe's in the system. John realizes he should not have been invited and wants to reject his contributor claim.

**Comment by nanchen47** [comment]
Will be considered based on the feed back from users.
