### ISSUE TITLE
[docs] README.md should mention MFR

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/osf.io#3680]
The OSF file preview page requires running an optional extra service called "Modular File Renderer" (MFR):
https://github.com/CenterForOpenScience/modular-file-renderer

This service is not mentioned in the README.md installation instructions for the OSF, but it should be.
https://github.com/CenterForOpenScience/osf.io/#optional-extras

(Complete with any additional configuration needed to make it run correctly)

**Comment by Johnetordoff** [comment]
@revanthkolli If you have a second could you write these instructions, there's some little issues I'd like to fix but don't know how to get this thing running.

**Comment by revanthkolli** [comment]
@Johnetordoff The instructions for running the MFR are all on the README.md here https://github.com/CenterForOpenScience/modular-file-renderer

**Comment by nanchen47** [comment]
The pr has been merged
