### ISSUE TITLE
SHARE main page overflow on mobile

### ISSUE THREAD

**Issue by AndrewSallans** [CenterForOpenScience/osf.io#3681]
I was looking at the SHARE page (http://osf.io/share) on a mobile browser and noticed that some of the provider labels overflow from their boxes (see image below), and they are still listed two columns wide.

![screenshot_2015-07-17-21-18-11](https://cloud.githubusercontent.com/assets/2151933/8760260/01d6ba7a-2cdf-11e5-8f15-7edbd3780b4f.png)

Suggestion:  like the way providers are displayed on the SHARE search results page, make it a one column list and ensure there is no overflow.

**Comment by haoyuchen1992** [comment]
I can work on it! Thanks!

**Comment by lbanner** [comment]
Done! Thanks -

**Comment by fabianvf** [comment]
There are a few more problems on mobile, I think...

**Comment by haoyuchen1992** [comment]
@fabianvf  Yes, I don't find any media css code for Share.

**Comment by fabianvf** [comment]
no, so far as I know we did not have any focus on mobile when we wrote it.
