### ISSUE TITLE
[staging + production] wiki menu does not resize correctly 

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3685]
## Steps
*On staging or production*
1. Visit a wiki page.
2. Collapse the left hand navigation menu
3. Resize the window to be about 860 px wide.
4. Note the icons in the menu on the left.
5. Uncollapse the menu
6. Resize the window to be about 916 px wide

*On staging*
1. Visit a non-homepage wiki for a project.
2. Collapse the left hand navigation menu
3. Resize the window to be about 730 px wide

## Outcome
*Staging and Production*
1. The icons in the left hand navigation get cut off and are not properly centered. 
![screen shot 2015-07-20 at 10 05 19 am](https://cloud.githubusercontent.com/assets/4965832/8777740/e01f992a-2ec7-11e5-8f3a-77625aad0e74.png)
![screen shot 2015-07-20 at 10 05 25 am](https://cloud.githubusercontent.com/assets/4965832/8777742/e30dd99e-2ec7-11e5-8cd0-2153feaa8c49.png)

*Staging*
1. The left hand navigation takes up the entire screen but only the icons are used, wasting space.
![screen shot 2015-07-20 at 10 05 41 am](https://cloud.githubusercontent.com/assets/4965832/8777747/ec927a42-2ec7-11e5-8db2-77312e158e3b.png)

## Expected outcome
1. When resizing windows, appropriate padding should be given so that icons do not get cut off, but excessive space is not allowed. Specifically, here, the icons should be centered with some space around them when the menu is collapsed. If the menu takes up the entire screen, then more information should be provided (i.e. there should be accompanying text).

**Comment by jinluyuan** [comment]
[Trello card](https://trello.com/c/eJNsz1fG/137-issues-when-collapsing-wiki-menu-and-then-making-window-smaller) to address staging issues

**Comment by haoyuchen1992** [comment]
@caseyrollins Hi Casey, I know you have sent a PR about his. Can you look at this again? Because wiki plus icon is not centered in staging for xs screen.

![screenshot 2015-07-21 15 01 16](https://cloud.githubusercontent.com/assets/5420789/8809962/aa76c2f6-2fb9-11e5-8159-470dfdaf4e82.png)

**Comment by caseyrollins** [comment]
@haoyuchen1992, thanks for catching that! The PR that fixes this is [here](https://github.com/CenterForOpenScience/osf.io/pull/3735).

**Comment by nanchen47** [comment]
The pr has been merged and deployed.
