### ISSUE TITLE
View-only links - Expand and collapse buttons for component listing are awkward

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3689]
### Steps
1. Go to [osf.io](http://www.osf.io)
2. Go to one of your projects that has at least two components
3. Go to the project's Sharing page
4. Add a new View-only link that includes all the components

### Expected behavior
I expected that the list of components would be expanded with a double down-arrow icon like in user settings for add-ons.

![screen shot 2015-07-20 at 11 32 27 am](https://cloud.githubusercontent.com/assets/8591162/8779766/0df05e06-2ed3-11e5-9ec7-e0601bc1befc.png)

### Actual behavior
The expand and collapse buttons are full-size and ungainly. 

![screen shot 2015-07-20 at 11 31 27 am](https://cloud.githubusercontent.com/assets/8591162/8779746/eb4e5bdc-2ed2-11e5-972d-f96ca5cff3f2.png)
![screen shot 2015-07-20 at 11 31 32 am](https://cloud.githubusercontent.com/assets/8591162/8779747/eb52e60c-2ed2-11e5-8774-979e159940b6.png)

This is especially apparent when you look at the buttons in the context of the rest of the content under View-only Links.

![screen shot 2015-07-20 at 11 36 21 am](https://cloud.githubusercontent.com/assets/8591162/8779871/9a697e4e-2ed3-11e5-8044-bacdcd7b428c.png)

If the double down-arrow is not a good solution, then simply having the text "Show 1 more..." and "Collapse" would be better than the full-size buttons.

**Comment by caneruguz** [comment]
Now that we have a plugin for expanding view it might be a good idea to try to implement it on these uses as well. I can take a look at this one @lbanner

**Comment by lbanner** [comment]
Done!
