### ISSUE TITLE
Inconsistent style of top right "x" icon in Treebeard modals

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3693]
Reported on [Trello](https://trello.com/c/C8kEBqVK/135-inconsistent-style-of-top-right-x-icon-in-modals) by me

The Dashboard's Legend modal and all the modals within Treebeard have two different "x" icons than the typical small, light gray "x" in other modals, such as the Change Avatar modal and Collaborative File Editing modal.

![dashboard legend](https://cloud.githubusercontent.com/assets/8591162/8781939/418d0d24-2ee0-11e5-9fc6-50aa3ba885da.png)
![file browser information](https://cloud.githubusercontent.com/assets/8591162/8781941/418e2fec-2ee0-11e5-849e-73db0dbb29af.png)
![screen shot 2015-07-20 at 1 09 56 pm](https://cloud.githubusercontent.com/assets/8591162/8782034/ca296ee8-2ee0-11e5-846c-98709122106e.png)

![change avatar](https://cloud.githubusercontent.com/assets/8591162/8781938/418ae594-2ee0-11e5-9d86-bd6b55b73051.png)
![collaborative file editing](https://cloud.githubusercontent.com/assets/8591162/8781940/418d2f66-2ee0-11e5-866d-0bfc7d779153.png)

**Comment by caneruguz** [comment]
This is a treebeard change. I'll be working on this now and update osf.

**Comment by caneruguz** [comment]
Fix is sent here: https://github.com/CenterForOpenScience/osf.io/pull/3733
