### ISSUE TITLE
Project overview page - Recent Activity page number shows through OSF footer banner for logged out users

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3696]
### Steps
1. Go to osf.io as a logged out user
2. Go to any project that has multiple pages of recent activity, such as [this one](https://osf.io/9f6gx/)
3. Wait for the footer banner to load
4. Scroll until the banner is over the bottom of the Recent Activity widget

### Expected behavior
I expected that the banner would cover all affected Recent Activity content.

### Actual behavior
![screen shot 2015-07-20 at 12 34 17 pm](https://cloud.githubusercontent.com/assets/8591162/8782288/5dd49d92-2ee2-11e5-9fb1-3703f76eb046.png)

**Comment by caneruguz** [comment]
Sent a quick fix here: https://github.com/CenterForOpenScience/osf.io/pull/3701

**Comment by caneruguz** [comment]
@jinluyuan it appears that this exact issue was reported already at #3478 . Please search through github issues before reporting production bugs.
