### ISSUE TITLE
Github: Project logs list uploaded files twice

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3698]
Reported on the "Large file uploads" trello board by @nicipfeiffer 
https://trello.com/c/jgSLqE7v/24-github-project-logs-list-the-uploaded-files-twice

## Steps

1. Navigate to a project for which you have read + write or admin access.
2. Go to project settings.
3. Enable and configure Github for the project.
4. Go to the files tab.
5. Click to select the row where the Github icon is displayed.
6. In the files grid header, click the "Upload" button to upload a file into the Github folder.
7. Select a file.
8. Upload the selected file into the Github folder.
9. Return to the project overview page and scroll to view project logs.

## Expected Behavior

I expect that the file upload will only be documented once in project logs.

## Actual Behavior

The file upload is documented twice (see screenshot below). This behavior does not occur when uploading files to other add-ons.

## Screenshot

![github_repeat_file](https://cloud.githubusercontent.com/assets/7093086/8782499/dac899a6-2ee3-11e5-82c8-81a227b7521e.png)

**Comment by chennan47** [comment]
Can't repo this problem on staging or production. @NatashaRichter can you verify this problem still exists? Thanks.

**Comment by chennan47** [comment]
Verified with @NatashaRichter, this problem only happens when your github repo is public.

**Comment by chrisseto** [comment]
@NatashaRichter fixed via https://github.com/CenterForOpenScience/waterbutler/commit/97d48c027b09e657ba0ece8ecc1c35ed93dff020

**Comment by erinmayhood** [comment]
@NatashaRichter can you verify this has been fixed and close if so?

**Comment by nicipfeiffer** [comment]
@erinmayhood This is currently in the 0.47 release as a hotfix.  (https://trello.com/c/b48zfyPF/41-fix-double-log-problem-with-github)
QA has done 2 passes and it looks to be fixed. @lbanner Can you close?

**Comment by lbanner** [comment]
OK ... looked to be rooted in the Staging server in any case - Thanks.
