### ISSUE TITLE
Email notification about new comment has too much white space at top

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3699]
Reported on [Trello](https://trello.com/c/jPKa1LO2/62-email-notification-about-new-comment-has-too-much-white-space-at-top-above-recent-activity) by me

### Steps
1. Go to osf.io
2. Go to one of your projects that has two contributors, both that you control
3. Go to the project's Settings page as one contributor
4. Go to "Configure Notifications"
5. Change the setting for Comments Added to "Emails"
6. Go to the project as the second contributor
7. Make a new comment
8. Check the email inbox of the first contributor

### Expected behavior
I expected that the Recent Activity email would look as it did back at the beginning of June 2015.

![](https://trello-attachments.s3.amazonaws.com/55a56eeec4fce6cee2e0f9c4/600x450/709726420035bf5d6e803ebbe6438f42/122cacac-0b99-11e5-90b8-acc9c6a87127.png)

### Actual behavior
There is a large white space above the header.

![](https://trello-attachments.s3.amazonaws.com/55a56eeec4fce6cee2e0f9c4/600x518/6b433b4e04e6ab9b30413a9f4d2db5e7/Screen_Shot_2015-07-14_at_3.59.17_PM.png)

**Comment by haoyuchen1992** [comment]
I can work on this one ! Thanks!
