### ISSUE TITLE
Check growl boxes and alerts across site for overlapping text

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3700]
## Description

I attempted to upload a file to Amazon S3 and saw the growl box in the screenshot below, because I need to update my S3 credentials.

## Expected Behavior

I expect that the text of all growl boxes and alerts will not overlap with the "x" to cancel out of the growl boxes or alerts.

## Actual Behavior

When the text of a grow box or alert is short, the text overlaps with the "x."

## Screenshots

![error_growl](https://cloud.githubusercontent.com/assets/7093086/8782719/511e6512-2ee5-11e5-9592-9301eeb87d0f.png)

![overlapping_text](https://cloud.githubusercontent.com/assets/7093086/8782886/5a65a9c2-2ee6-11e5-93f5-6dcdee541dd4.png)

**Another example (from #3673)**

![emailalerts](https://cloud.githubusercontent.com/assets/7093086/8752713/1d4166b2-2c84-11e5-84cb-196ae94c0ac9.png)

## Notes 

Related to #3673 

Perhaps close that issue in favor of this one? At the time I reported that issue, I didn't know this problem was more pervasive.

**Comment by haoyuchen1992** [comment]
I can work on this! Thanks :)
