### ISSUE TITLE
Improve error message when Amazon S3 credentials need to be updated

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3703]
## Description

I attempted to upload a file to my Amazon S3 add-on from the Project Overview page without knowing that my credentials had expired. The red error message I see upon trying to upload is unhelpful.

## Expected Behavior

I expect a more descriptive error message on the Project Overview page **OR** for a message to appear underneath the add-on heading in the files widget itself to describe why uploading is unsuccessful (as when files are too large). In this case, a message does not appear underneath the Amazon S3 add-on heading in the files widget, so the user does not know why uploading has failed.

## Actual Behavior

I was unsure why the file upload failed until I navigated to my Project Settings, where I saw the message in the second screenshot below.

## Screenshots

**On Project Overview page**

![amazon_s3_credentials](https://cloud.githubusercontent.com/assets/7093086/8783576/cd04ddc8-2eea-11e5-9c74-cd2597673b77.png)

**On Project Settings page**

![settings_amazons3](https://cloud.githubusercontent.com/assets/7093086/8783698/7bf8fb66-2eeb-11e5-84b4-980198979f16.png)

**Comment by haoyuchen1992** [comment]
I can work on this one, Thanks!

**Comment by nanchen47** [comment]
@haoyuchen1992 what's the status on this one?

**Comment by haoyuchen1992** [comment]
@nanchen47 Oh, I almost forget about this one. Because it isn't assigned to me. Can you assign it to me now? Thanks!
