### ISSUE TITLE
[Production] 502 Error when filtering tags

### ISSUE THREAD

**Issue by WillBanner** [CenterForOpenScience/osf.io#3706]
# [Firefox] [Chrome] [Safari]
# Steps
1. Go to osf.io and log in
2. Click on the search bar at the top
3. Paste one of the searches in the google doc.

Because of how long the searches are, I created a google doc so that I don't fill up this issue page. These are searches that I copied directly from the search bar on production after the error occurred. 
These problems could occur on staging, but it could be that we don't have enough tags on staging in order to test it.

Here's the link to the Google doc:
https://docs.google.com/document/d/1G6PFRI2bNKOQMRNJKtG2Ke_vLNd4VLvsrujGTnbuzgk/edit?usp=sharing

Below each search input I have a screenshot of what occurs, though I'll also put one here:
![image](https://cloud.githubusercontent.com/assets/12799635/8785098/6274d1bc-2ef3-11e5-9f2b-1ef6dcbcccad.png)

**Comment by nanchen47** [comment]
Verify with @NatashaRichter , this is no longer an issue.
