### ISSUE TITLE
[Staging and Production] 500/503 errors when filtering tags in OSF search

### ISSUE THREAD

**Issue by WillBanner** [CenterForOpenScience/osf.io#3708]
# [Safari] [Firefox] [Chrome]
# Steps
1. Go to osf.io and log in.
2. Go to the search bar.
3. With these errors there are no exact steps for reproduction. What I've found is that, even when I copy the exact search that I've used in order to get the error, and paste it into the search again, everything will work correctly. So what you'll probably have to do is filter out tags over and over, usually it happens within the first 0 to 30 that you filter though.

So that I don't fill up the issue page I've created a google doc with some of the instances of the bug:
https://docs.google.com/document/d/1g4ZIrq3Hkr1KIPeTfYex3zGJNQaBzMrUwuGtPpswJZA/edit?usp=sharing

The formatting that I'm using is
- any comments on the instance of the bug
- the NOT tags that were put into the search in order to get the bug.
- a screenshot of the bug

This was originally a trello bug and I have the card here:
https://trello.com/c/UKi5HrAr/53-500-error-when-using-not-tags

There are screenshots below the filters that I used to get to the bug on the google doc, but I'll put a screenshot here too:

![image](https://cloud.githubusercontent.com/assets/12799635/8785338/053a7590-2ef5-11e5-8bd7-0b30651c7efc.png)

**Comment by nanchen47** [comment]
Can't repo this problem anymore. If this happens again, please reopen it.
