### ISSUE TITLE
Getting Started: The page does not scroll to the headers when clicking through the side navbar

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3709]
# Steps
1. Log in to osf.io
2. Go to the 'Getting Started' page
3. On the left nav bar, click on 'Getting Started'
4. Then click on 'Creating a Project', 'Collaboration', and 'Version Control' respectively

# Expected
The page would scroll just above the respective header selected through the navbar

# Actual
The page scrolls to few lines below the header

![scrolls below the header](https://cloud.githubusercontent.com/assets/10926926/8785536/621299ae-2ef6-11e5-8372-dc8c332fd8bf.png)

**Comment by caneruguz** [comment]
I'm working on this.

**Comment by caneruguz** [comment]
@sloria let me know when this is tested and working so we can close this issue.

**Comment by sloria** [comment]
This has been tested by QA on staging.
