### ISSUE TITLE
[Firefox] [UI] Add Contributors Modal: Contributor permissions dropdown entire words not shown

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3710]
## Steps using Firefox browser:
1. Go to a project you have admin access on
2. Click to go to the sharing tab
3. Click to Add a new contributor
4. Enter a name to get a contributor list
5. Select one of the users in the list by clicking the + sign
6. In the Permission dropdown toggle to select 'administrator' and 'read+write'

## Expected
I would expect the entire word to show in the dropdown selector like it does on other browsers
![chrome - rw](https://cloud.githubusercontent.com/assets/9381062/8785932/264248d6-2ef9-11e5-862a-ce548f0072a1.png)
![chrome - admin](https://cloud.githubusercontent.com/assets/9381062/8785935/2881381e-2ef9-11e5-9ef9-8112b1651c4b.png)

## Actual
On Firefox, the words are cut off
![firefox - rw](https://cloud.githubusercontent.com/assets/9381062/8785892/ef56f15a-2ef8-11e5-92f7-346c3be8bee4.png)
![firefox - admin](https://cloud.githubusercontent.com/assets/9381062/8785894/f436f03a-2ef8-11e5-9a3b-41eb5222b102.png)

**Comment by haoyuchen1992** [comment]
I can work on this one! Thanks!

**Comment by haoyuchen1992** [comment]
The PR has been merged. So this issue could be closed now.

**Comment by lbanner** [comment]
Got it - Thanks
