### ISSUE TITLE
"add existing project" search does not search components

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3721]
## Steps
1. If you do not have one already, create a project that has a component within it
2. Go to your project organizer
3. Create a collection
4. Drag and drop the *component* from your project into the collection
5. Create another collection
6. Ensure that the project is expanded in the organizer so that you can see the component (rules out https://github.com/CenterForOpenScience/osf.io/issues/2779 as the issue)
7. Select the collection
8. Click on "Add Existing Project" from the toolbar above the organizer.
9. Search for the *component* title

## Outcome
1. You can successfully drag and drop a component into a collection
2. When you attempt to search for the component, no results are returned making it impossible to search and add the component.
![screen shot 2015-07-21 at 11 32 36 am](https://cloud.githubusercontent.com/assets/4965832/8805130/9c822940-2f9d-11e5-954b-e9647ca2535b.png)
(in the above image, "QA component" is hidden beneath the results dropdown)

## Expected Outcome
1. If components can be added to collections by dragging and dropping, they should also be able to be added by searching for them. This means that the search for existing projects must include a component search as well.

**Comment by brianjgeiger** [comment]
What's happening is that the component search is only looking for components that you otherwise don't have access to because they are located in a project that is private but you are not a contributor.

That being said, I don't disagree with the issue. Just be careful when the change is made not to break existing functionality.
