### ISSUE TITLE
Improve error message when connecting Dataverse account

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3723]
## Steps

1. Log in to osf.io and head to one of your projects.
2. Navigate to User Settings and click "Connect an Account" next to the Dataverse add-on.
3. Without selecting a Dataverse repository, click "Save."
4. Notice the error message.

## Current Message

"Sorry, but there was a problem connecting to that instance of Dataverse. It is likely that the instance hasn't been upgraded to Dataverse 4.0. If you have any questions or believe this to be an error, please contact support@osf.io."

## Suggested Change

Make the error message match other error messages when required fields are left empty.

Change to: "This field is required" or "Please select a Dataverse repository."

## Screenshots

**Current Dataverse error message for required field**

![dataverse_error_message](https://cloud.githubusercontent.com/assets/7093086/8805738/e7c38cf2-2fa0-11e5-8043-a6782e1e9b90.png)

**Uploader widget required field**

![uploader_error_message](https://cloud.githubusercontent.com/assets/7093086/8805847/706feb4a-2fa1-11e5-876b-f049731d7eb1.png)

**Onboarder project creation required field**

![this_field_is_required](https://cloud.githubusercontent.com/assets/7093086/8805729/d98a4018-2fa0-11e5-8ee4-c703954ad79d.png)

**Comment by haoyuchen1992** [comment]
I can work on this! Thanks!

**Comment by lbanner** [comment]
Done!
