### ISSUE TITLE
User Settings: Change placeholder text of dataverse repository drop-down menu

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3728]
## Steps

1. Log in to osf.io.
2. Go to your User Settings > Configure Add-ons.
3. Click "Connect an Account" next to the Dataverse add-on.
4. Notice placeholder text in the drop-down menu of the modal that appears.

## Current Text:

"Select an item..." (see second screenshot below)

## Suggested Change:

"Select a Dataverse repository"

This makes the placeholder text more descriptive (as with the placeholder text in the template drop-down in the first screenshot below).

## Screenshots

**Template drop-down placeholder text**

![select_a_project](https://cloud.githubusercontent.com/assets/7093086/8806379/73da199c-2fa4-11e5-8b62-eedffecdc813.png)

**Dataverse drop-down placeholder text**

![select_an_item](https://cloud.githubusercontent.com/assets/7093086/8806395/85fd50a8-2fa4-11e5-9024-289ae412af47.png)

**Comment by Johnetordoff** [comment]
@GaryKriebel can I get this?
