### ISSUE TITLE
[staging & production] file tree collapse icon needs pointer class

### ISSUE THREAD

**Issue by caseyrollins** [CenterForOpenScience/osf.io#3734]
#### Steps
- View a file on the OSF
- Collapse the file tree, notice that when you do so your cursor changes.
- Expand the file tree, notice that your cursor does not change.

[![Gyazo](http://i.gyazo.com/84ac2124a8d38b76555994298ebdf35e.gif)](http://gyazo.com/84ac2124a8d38b76555994298ebdf35e)

#### Expected
- When expanding the file tree, the cursor should change the same way it does when collapsing the file tree.

**Comment by Johnetordoff** [comment]
@GaryKriebel can I get this one?

**Comment by lbanner** [comment]
Done!
