### ISSUE TITLE
Disallow "Register a Project" search for projects user does not have admin privileges on

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3738]
## Steps
1. Ensure that you are a read or a read + write contributor on a project or component
2. Visit your dashboard
3. Open the "Register a Project" dropdown. 
4. Search for a component that you are a read or a read + write contributor on.

## Outcome
1. Results are returned.
2. Clicking "Continue Registration" brings you to a page that tells you the action is forbidden.

## Expected Outcome
1. No results should be returned if there are no relevant projects that the user has admin privileges on. Because only admins can register a project, it should not be implied to other read or read+write contributors that they can also register a project. When a user searches for a word or phrase that returns no results, the "Register a Project" dropdown simply shows no results. Even if a project with that title exists, the result should not be returned if the user does not have permission to register the project.

**Comment by Johnetordoff** [comment]
@lbanner can I get this?

**Comment by lbanner** [comment]
:+1:
