### ISSUE TITLE
Zotero has incorrect error message when credentials are revoked 

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3750]
# Steps
1. Go to a project on which you have admin access
2. Go to project settings and enable and configure Zotero
3. Confirm that Zotero is configured and citations are linked
4. Go to Zotero > Settings > Feeds/API
5. Revoke access the most recent access to OSF
6. Go back to project settings and refresh page

# Expected
I expect that the error message saying that the credentials are no longer valid would be consistent with other error messages displayed when access is revoked via the external service.

# Actual
The correct error message is not shown. Instead, this is the error message:
![screen shot 2015-07-22 at 12 15 20 pm](https://cloud.githubusercontent.com/assets/5975444/8830651/62b9f2aa-306b-11e5-940b-d00d3d3bd199.png)

The error message with the correct instructions is
![screen shot 2015-07-22 at 11 31 50 am](https://cloud.githubusercontent.com/assets/5975444/8830632/38007854-306b-11e5-9ffb-15cdd8ee2ae8.png)

Zotero's error message should be updated to include information about deauthorizing the add-on from the account settings page and trying again.

**Comment by caneruguz** [comment]
@sloria @nanchen47 @haoyuchen1992 

Is suggesting that they deauthorize really the correct solution to the problem of not being able to access? It seems like overkill and a hassle for connectivity problems. 

What is the suggested text to resolve this solution that can properly apply to all addons and that is a bit more helpful than the Zotero text above?

**Comment by haoyuchen1992** [comment]
Because the add-ons are implemented differently. Dropbox has its own warning logic and messages. For some other add-ons, such Zotero, they are implemented in `folderPickerNodeConfig.js`.  It is only very general warning message and doesn't do the validation check.  

The Zotero error example shown above is created by the code [here]( https://github.com/CenterForOpenScience/osf.io/blob/develop/website/static/js/folderPickerNodeConfig.js#L93):

            cantRetrieveSettings: ko.pureComputed(function() {
                return 'Could not retrieve ' + self.addonName + ' settings at ' +
                    'this time. Please refresh ' +
                    'the page. If the problem persists, email ' +
                    '<a href="mailto:support@osf.io">support@osf.io</a>.';
            }),

**Comment by nanchen47** [comment]
Will be considered when we refactor addons.
