### ISSUE TITLE
Long (or forever) load time for new wiki menu for projects with substantial wiki content

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#3763]
For projects with only a bit of wiki content, the new wiki menu loaded fine.  But for these two projects with sizable wiki content:

https://osf.io/ezcuj/wiki/home/
https://osf.io/e81xl/wiki/home/

The menu did not load (2+ minute wait). Including after clearing browser cache.

**Comment by sloria** [comment]
Should be fixed now.

**Comment by bnosek** [comment]
Yes, first try loaded just fine.
