### ISSUE TITLE
Sharing Tab: incorrect error 'Must have at least one visible contributor'

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#3765]
## Steps
1. Go to a project you are admin on
2. Go to the project sharing tab
3. Add another contributor, preferably one that is also you
4. On the sharing tab, in the contributor table give the contributor that is not you read only permissions and save the changes
5. Now uncheck the box for yourself to be bibliographic, but do not change you admin status. Save the changes
6. Reorder the contributors so that the read access bibliographic contributor is first and the admin non-bibliographic contributor is second. Save the changes
7. Now drag to reorder the contributors, moving the first into the second position

## Expected
I would expect the reorder would not initiate the error message and would only show the save changes button.

## Actual
The reorder causes an error on the page the 'Must have at least one visible contributor', which is incorrect.
![screenshot 2015-07-23 09 22 35](https://cloud.githubusercontent.com/assets/9381062/8851261/64516664-311c-11e5-9459-3498bd74b79a.png)

**Comment by Johnetordoff** [comment]
@nanchen47 Can you assign me to this?

**Comment by lbanner** [comment]
Yours!

**Comment by Johnetordoff** [comment]
@nicipfeiffer I have replicated this behavior, but it's very inconsistent. I've followed these instructions carefully and I find when this happens it's fixable by simply clicking save changes again. Is this true for you too?

**Comment by nicipfeiffer** [comment]
@Johnetordoff Yes, I can clear the error message by putting the order back to it's original state or by saving or canceling the changes.  Irregardless, the error is incorrect and should not be showing.
