### ISSUE TITLE
Project Overview: The pages on the 'Add Links' modal take a longer time to render on production 

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3771]
# Steps
1. Go to osf.io
2. Go to a project for which you have admin access
3. On the project overview page, click on 'Add Links'
4. Type 'a' on the modal and click on 'Search all projects'
5. Click the right arrow to go through the list of suggested projects

# Expected
The user would be able to go to the next page of results without delay as on staging

![add links staging](https://cloud.githubusercontent.com/assets/10926926/8854339/6a8fec56-312d-11e5-82a2-0bc2e7baba6b.gif)

# Actual
There is about a 1.5 second delay before the next page of results is displayed

![add links on production](https://cloud.githubusercontent.com/assets/10926926/8854326/5cd84f0e-312d-11e5-8322-826b4697fb45.gif)

**Comment by lbanner** [comment]
Could this have been traffic/timing? I'd like to see this reproduced before a Dev begins investigating/coding. Thanks.

**Comment by chennan47** [comment]
Every page changes means a ajax request to the backend server and front end needs to wait for the answer from the request to build the content. There is not much user and request on staging than production which makes the speed difference. This is totally expected as long as the delay is acceptable. @lbanner I think this issue can either be labeled as defer for later improvement or just close it.

**Comment by lbanner** [comment]
I'll close based on your note -- our awareness around Production performance is likely high at present, in any case. Thanks.
