### ISSUE TITLE
Create View-only Link modal - Change "Generate" to "Create"

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3773]
Reported on the 0.43 trello board by @jinluyuan 
Link: https://trello.com/c/1lLoHdBw/67-create-view-only-link-modal-change-generate-to-create
# Issue
The word "generate" is not used anywhere else on the site, and it makes more sense to stick with "Create", which we use extensively. 

![](https://trello-attachments.s3.amazonaws.com/55a68b70d7448f83e279e7c8/600x495/a99e244265ae5b26539431322028288e/Screen_Shot_2015-07-15_at_12.33.00_PM.png)

**Furthermore, the text that describes View Only Links uses the word "Create", so we should make the modal be consistent with that description.**

![](https://trello-attachments.s3.amazonaws.com/55a68b70d7448f83e279e7c8/600x66/f9bbedc25efff77f82d1c7d6bcf32da7/Screen_Shot_2015-07-15_at_12.37.26_PM.png)

**This applies to the header of the modal as well as the button.**

# Comments from the card: 
@caneruguz: @jinluyuan1 is this not also the same in production?

Also this does not strike me as a bug nor a style issue, it's essentially and opinion on proper use of text and I think the best place for this is as an issue in Github for osf because there is room for discussion and disagreement here.

The style guide says to use the verb that makes most sense, so whatever we end up calling this process will be the button name.

**Comment by chrisseto** [comment]
+1

**Comment by chennan47** [comment]
@jlcohoon can you confirm this change is what we want?

**Comment by jlcohoon** [comment]
+1, "create" is more colloquial and more consistent.
