### ISSUE TITLE
Amazon S3 account connection success message is different from others

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3776]
Reported on the 0.43 trello board by Will Banner
Link: https://trello.com/c/EdQIrIOX/92-amazon-s3-account-connection-success-message-is-different-from-others

# Steps
1. Go to osf.io
2. Go to your user settings.
3. Configure the Amazon S3 Add on.

# Expected 
I would get a green message that says "Add on successfully authorized. To link this add on to an OSF project, go to the settings page of the project, enable Amazon S3, and choose content to connect." below the Amazon S3 header.

# Actual
I get a green message below the save button that says "settings updated"

![a](https://trello-attachments.s3.amazonaws.com/55a7ee0b3d751979103ab7a6/310x354/6a01a276bc051d0c172e5c4b41cd4286/upload_7_16_2015_at_1_51_25_PM.png)

**Comment by haoyuchen1992** [comment]
I can work on this, Thanks!

**Comment by haoyuchen1992** [comment]
### Analysis
The message is from onSubmitSettings in addonHelper.js. So it is not only for Amazon s3. Therefore, we need input parameters to put the proper message for every addon.  

### Possible Solution
pass warning message to onSubmitSettings -- The technique details could be based on Stackoverflow issues -- http://stackoverflow.com/questions/3458553/javascript-passing-parameters-to-a-callback-function
