### ISSUE TITLE
Page should update after connecting to Amazon S3 account

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3778]
Reported on the 0.43 trello board by @jinluyuan 
Link: https://trello.com/c/paXFY0Qz/104-page-should-update-after-connecting-to-amazon-s3-account

# Steps
1. Go to osf.io
2. Go to your user settings
3. Click the "Connect Account" link next to Amazon S3
4. Go through the account connection process

# Expected behavior
I expected that after I successfully connected to my account, the page would refresh & update, and I would see "Amazon S3 authorized by *Jinlu Yuan*" with a green success message below and a red "Disconnect Account" link.

# Actual behavior
The only change is a green "Settings Updated" text appears. If I refresh the page, I can see the expected format.

![a](https://trello-attachments.s3.amazonaws.com/55a800e5ac5dc008e6279482/664x340/3b41c874b8ec714c67e80c54b3505baf/Screen_Shot_2015-07-16_at_3.07.29_PM.png)

**Comment by lbanner** [comment]
I believe this was expected functionality for this refactor (?) given the different approach to connection for S3. But considering how to make it function more consistently with others is worthwhile.

**Comment by nanchen47** [comment]
Will be considered when we refactor S3 addon.
