### ISSUE TITLE
Cannot edit comments by clicking on them

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#3780]
Steps
-------
1) comment on a project
2) hover your cursor over the comment

Expected
------------
I would expect that clicking on the comment text would allow me to edit it in place since the text cursor appears.

Actual
--------
The cursor changes to a text cursor and the comment background highlights, but I cannot edit the comment.

![comment](https://cloud.githubusercontent.com/assets/6414394/8856900/b113e674-313b-11e5-9541-de909fcfc39f.png)

**Comment by samanehsan** [comment]
@caneruguz, @haoyuchen1992 could this be a regression from the recent style changes?

**Comment by haoyuchen1992** [comment]
@samanehsan I think so. When I changed it, I didn't realize we had such functionality.

**Comment by caneruguz** [comment]
@haoyuchen1992 you should first check if that's in fact the case or it's a css thing. If we broke it the solution has to be very simple, if you see yourself having to play with javascript then something else is wrong.

**Comment by lbanner** [comment]
@haoyuchen1992 I am assigning to you for first investigate then resolve if able -- If it needs to go to someone else past investigation, let me know.

**Comment by haoyuchen1992** [comment]
This is because Steve disable the click-edit effect in a PR -[https://github.com/CenterForOpenScience/osf.io/commit/56f886091fd06bce1472aa24e4fe85c0c6f75db8]. But it doesn't clear it up. I just sent the aboved PR for that.
