### ISSUE TITLE
Using keyboard shortcut to open a new tab from Dashboard projects produces red highlight 

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3781]
### Steps
1. Log into osf.io
2. In your Dashboard, hover over a project
3. Use the keyboard shortcut Cmd + left mouse click to open a new tab for viewing the project
4. Compare this behavior to using the keyboard shortcut to open a new tab for a project file

### Expected behavior
With the keyboard shortcut, I expected that opening a new tab from the Dashboard would be the same as opening a new tab for a file. That is, the background stays light blue until I stop hovering over the project or file.

### Actual behavior
The background flashes red until the new tab is opened. The red highlight is alarming as it makes me think there is something wrong, or I'm unable to open the tab.

![red treebeard highlight](https://cloud.githubusercontent.com/assets/8591162/8857149/a5606ec2-313d-11e5-9951-6c0e9b30d24c.gif)

**Comment by haoyuchen1992** [comment]
I will look at it, Thanks!

**Comment by caneruguz** [comment]
@GaryKriebel can you assign me to this? Thanks!

**Comment by caneruguz** [comment]
@GaryKriebel a fix is submitted for this one.

**Comment by nanchen47** [comment]
The fix has been merged.
