### ISSUE TITLE
Google Drive account connection should not yield an alert at top of page

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3782]
Reported by @willbanner on the 0.43 Trello board:

# Steps
1. Go to staging.osf.io
2. Go to your user settings.
3. Configure the Google Drive add on.

# Expected
I would get a green message that says "Add on successfully authorized. To link this add on to an OSF project, go to the settings page of the project, enable Amazon S3, and choose content to connect." below the Add on header.

# Actual
Instead of the message below the google drive header (issue #2031 references this problem), I get a green alert at the top of the screen saying that the add on has been configured. The alert at the top *only* occurs for Google Drive and should be removed to be consistent with other add-ons.

![dd](https://trello-attachments.s3.amazonaws.com/55a7f142e2680ad295914302/1024x92/29fc2571f56fd93664356ee4552f94da/Google_Drive_Green_Alert_at_top_of_Screen.png)

**Comment by Johnetordoff** [comment]
@GaryKriebel can I get this

**Comment by lbanner** [comment]
Done!

**Comment by Johnetordoff** [comment]
@caileyfitz I'm not getting the this alert, could you check this? I rummaged through the code as well and couldn't find that message.

**Comment by caileyfitz** [comment]
@Johnetordoff Hmm... I am not seeing this either. We might wait until @willbanner can try to repo this since he filed the issue initially.

**Comment by Johnetordoff** [comment]
@willbanner Any word? Can you reproduce this?
