### ISSUE TITLE
Project Overview: Tags have inconsistent color

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3783]
Reported by @nicipfeiffer on the 0.43 Trello board:

On the project overview page tags are green:
![green](https://trello-attachments.s3.amazonaws.com/559e79c80f869aa72844e395/581x188/740d84de974b27f834335c459c21dc74/Screenshot_2015-07-09_09.39.16.png)

But on the search page they are blue:
![blue](https://trello-attachments.s3.amazonaws.com/559e79c80f869aa72844e395/600x134/ebaf000c0a38c2ef60a0b125fa6d5fec/Screenshot_2015-07-09_09.41.27.png)

The tag color should be consistent across the site. Also, this green color is not a color listed formally in the style guide. 

Comment by @caneruguz 
> This is a bit of a huge deal so I would like to move this to the list to discuss as feature.

**Comment by caneruguz** [comment]
Okay thanks! 

We don't need to overextend the idea of uniformity. If we do however and we move to use colors that are more uniform we need to pick something that works well in both of these cases. Also reminder that the unity thereby formed will need to be applied to all future tags. 

Uniformity can be accomplished across items and pages. Sometimes these will conflict. We can have all our tags be light blue but in some pages this migh look very out of place. Design is usually a compromise between these. We should keep that in mind when trying to make things look alike. 

In this case the recommendation I would have is to use the blue for the tags.

**Comment by Johnetordoff** [comment]
@lbanner can you put me on this?

**Comment by lbanner** [comment]
Done!
