### ISSUE TITLE
[Production and Staging] User Settings Side Nav Bar moves after disconnecting add-ons

### ISSUE THREAD

**Issue by WillBanner** [CenterForOpenScience/osf.io#3784]
# [Firefox] [Chrome]

Here's the original trello card, though the bug has changed since then- the nav bar does not get stuck.
https://trello.com/c/fypn8RkM/102-chrome-firefox-after-disconnecting-github-or-google-drive-accounts-side-nav-bar-does-not-scroll

# Steps
1. Go to osf.io and log in.
2. Go to your user settings.
3. Go to configure Add-ons
4. Configure the google drive, Github, box, dropbox, or figshare add-on.
4. Scroll down so that you can see the bottom of the "configure add-on accounts" box like so:
![image](https://cloud.githubusercontent.com/assets/12799635/8857916/88e9b3f2-3142-11e5-98ff-c8ba5cd56960.png)

5. Click to disconnect the add-on.

# Expected:
The page would reload and the side nav bar would appear in the upper left.

# Actual:
The side nav bar appears at the bottom of the page (though it is still usable) and, as soon as you scroll, the bar jumps to the top of the screen.

![image](https://cloud.githubusercontent.com/assets/12799635/8858039/2144db36-3143-11e5-8787-9bf1df7167e4.png)

**Comment by jinluyuan** [comment]
This happens in other situations in which the Project or User Settings page has to refresh and return to the same place on the page. Difficult to give "steps" to replicate, but we've all encountered this jumpy nav bar.

**Comment by haoyuchen1992** [comment]
@WillBanner Hi Will, can you replicate this issue again? I tried in both staging and production. It looks fine.

**Comment by WillBanner** [comment]
@haoyuchen1992 hmm, I've been able to replicate it.

**Comment by haoyuchen1992** [comment]
The replicated the steps:
1. Scroll down to the bottom of the addon
2. refresh the page (disconnect will lead to refresh the page)

Since this is a small and weird bug, Caner suggested to defer it for a while. But it can be assigned to me and I will check it when I have time.

**Comment by lbanner** [comment]
OK

**Comment by XTech2K** [comment]
The exact same thing happens with the sidebar on the project settings page as well, so if you fix this one, make sure to fix that one as well.

![screen shot 2015-07-29 at 10 50 35 am](https://cloud.githubusercontent.com/assets/5955359/8960703/55482d3e-35df-11e5-8556-d9a89cf8622a.png)

**Comment by XTech2K** [comment]
Also, this might be different enough to warrant its own issue, but if you reload the page while anywhere besides the bottom section or very top of the page, the sidebar shrinks horizontally, only looking normal when scrolled to the top of the page.

![screen shot 2015-07-29 at 10 56 13 am](https://cloud.githubusercontent.com/assets/5955359/8960884/207dc1da-35e0-11e5-8ba9-d05fffdf87e4.png)
