### ISSUE TITLE
Dataverse should display name of Dataverse account user next to the repository

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3786]
Reported by @jinluyuan on 0.43 trello board
Link: https://trello.com/c/lzluMd0Y/110-dataverse-should-display-name-of-dataverse-account-user-next-to-the-repository
Testing card: https://trello.com/c/WvbiX4Fu/78-user-settings-connect-dataverse-account

# Issue
In User Settings, Dataverse should display "Authorized on *Repository_Name* by *Dataverse_Account_User*". 

![](https://trello-attachments.s3.amazonaws.com/55a811b01286e49783f498b3/600x83/c9916dba05a26e014e03cc2de2a1f088/Screen_Shot_2015-07-16_at_4.07.43_PM.png)

Mendeley, which has a similar structure to the Dataverse settings due to multiple accounts, does display the Mendeley account holder.

![](https://trello-attachments.s3.amazonaws.com/55a811b01286e49783f498b3/600x82/2db67b936f61c855afaaa1b8514c5967/Screen_Shot_2015-07-16_at_4.19.13_PM.png)

# Comments
@sloria: Possibly defer this? It's not critical, and it might be desirable to show which Dataverse host was used. Ideally, we'd show both the user and the host, e.g. "Authorized by Jinlu Yuan on dataverse-demo...", but it's not absolutely necessary to get this in before releasing.

**Comment by lbanner** [comment]
Noted -- this is/was anticipated functionality, I believe, due to Dataverse approach -- But good to aim for consistency.
