### ISSUE TITLE
Project Dashboard Page: Widget heights do not align (top)

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3790]
Reported by @nicipfeiffer on the 0.43 trello board
Link: https://trello.com/c/wtNK5RwA/151-project-dashboard-page-widget-heights-do-not-align-top

![a](https://trello-attachments.s3.amazonaws.com/55ae6b16ea6efa40c5d53ff4/1317x169/2362344a6c44566ee7fe0bf0c086d576/dashboard_-_height.png)

# Comments:
@caneruguz: So from a technical perspective these two components are not related at all in terms of layout so there is no reason why they should be aligned. One has a header, the other is a tab list.

To align them we would need to force unnatural boundaries into them and shift things around, which does not hold when widths change so it will be a serious battle to manage this.

I think we can defer this, mainly because it's on production. Then we can look into it and I will look for a solid fix that will work in all widths.

**Comment by caneruguz** [comment]
Incidentally I have a proposal for the dashboard page: 
https://osf.io/53dnv/

It suggest making these tabs and full page versions with pins that allow users to individually set their preference for the default. 

![project_organizer full screen](https://cloud.githubusercontent.com/assets/1314003/8858637/7f46e500-3146-11e5-994f-743036c411c9.png)

**Comment by lbanner** [comment]
The Dashboard project as noted by @caneruguz could be a candidate for next Epic -- So I'm going to tag this with "Hold" for now - Thanks.

**Comment by NatashaRichter** [comment]
Related to this is: https://trello.com/c/rSWuHsOA/152-project-dashboard-page-widget-heights-do-not-align-bottom

**Comment by nanchen47** [comment]
Will be considered when refactor dashboard page. Thanks.
