### ISSUE TITLE
Success alerts should be green

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3792]
Reported by @jinluyuan on the 0.43 Trello board:

As the [Style Guide](https://centerforopenscience.github.io/osf-style/style.html#alerts) shows, "success" alerts should be green.

The attached example is from making a new fork from a project with configured add-ons. This kind of discrepancy occurs in other places on the OSF (can discuss in future release)

Alerts were yellow:
![](https://trello-attachments.s3.amazonaws.com/559e887e727e8b18fe67b8ac/1166x569/45a4549f06fd94ea56212f7647c30e60/Forks_alerts_-_not_seeing_any_difference.png)

but @haoyuchen1992 changed them to be blue: 
![](https://trello-attachments.s3.amazonaws.com/559e887e727e8b18fe67b8ac/1169x624/f187ffdf7aaebf48c0def2ecd9f91c19/Screen_Shot_2015-07-20_at_9.55.48_AM.png)

The question now is... do we want different color boxes for different alerts (yes the add-on was copied vs no it wasn't)? Do we want to have all the separate boxes at all? 

Comment from @jinluyuan:
> Are you able to change the color depending on the success of the copying or not? It's fine if they're all blue, but it would be better if the "not copied" alerts were yellow.

Comment from @haoyuchen1992:
> @sloria Hi Steve, since this alert messages come from a for loop. It looks like it is hard to add info or warning respectively based on their content. Do you have any ideas? Or can we make it in another way? For example, we just add bold or red color to the text "not copied to forked project"
> ![](https://trello-attachments.s3.amazonaws.com/559e887e727e8b18fe67b8ac/1258x560/cb3da530fadbffe71fa0f8931c5704a1/Screenshot_2015-07-20_11.07.01.png)

**Comment by caneruguz** [comment]
I don't think this is a matter of what color these alerts should be, it's more of a matter of how to display this type of data in an efficient way. 

This many alerts is not acceptable; so maybe combining into a single alert is the answer. In that process we need to decide which alerts can be combined and which should remain separate. When we do this we can accomodate different status types by using text coloring with ```text-danger``` etc.

**Comment by lbanner** [comment]
@caneruguz Should that be a proposed Style Guide discussion item?

**Comment by brianjgeiger** [comment]
Yeah, we need a better system for collecting multiple alerts. It didn't happen with growlbox because it was out of scope at the time, but we knew it was going to have to go in at some point.
