### ISSUE TITLE
User & Project Settings - Amazon S3 should have Connect Account link instead of Access & Secret Key input fields

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3793]
Reported on 0.43 trello board by @jinluyuan 
Testing card: https://trello.com/c/LITno6xe/72-user-settings-connect-amazon-s3-account#

In both User & Project settings when there is not an Amazon S3 account connected, there is no "Connect Account" link next to Amazon S3. Instead, the key input fields are by default visible. This does not match the style of our other add-on settings.

## User Settings
![User Settings](https://trello-attachments.s3.amazonaws.com/55a7e8b227da6e3156fffbc4/664x307/978d1c1390af213f88eed8cce6ef4ee7/User_Settings.png)

## Project Settings
![Project Settings](https://trello-attachments.s3.amazonaws.com/55a7e8b227da6e3156fffbc4/868x308/62181d3727c9cdbfb3d7e5d215cae172/Project_Settings.png)

**Comment by lbanner** [comment]
Reference #3778 - I think there are anticipated reasons as to why S3 is handled differently, but moving toward consistency is worth noting.

**Comment by nanchen47** [comment]
Same issue as #3778 . Close this one in favor of that.
