### ISSUE TITLE
GitHub is the only add-on that causes the page to refresh after importing account from profile or disconnecting account

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3794]
Reported by @jinluyuan on the 0.43 Trello board:

> Not sure if this qualifies as a bug, but none of the other add-ons refresh after importing or disconnecting

**Comment by caileyfitz** [comment]
Comment from @sloria: 
> Yeah, Github was the first addon to be written, so it differs in subtle ways from the other addons. Since this is the behavior on production, marking this as deferred for now.

**Comment by nanchen47** [comment]
Will be worked on when we refactor github addon. Thanks.
