### ISSUE TITLE
[Staging and Production] New Component: The 'project page' link does not navigate to the main project overview page

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3799]
# Steps
1. Go to osf.io
2. Go to a project for which you have admin access
3. On the project overview page, click add component and create a new component
4. Ensure that you are redirected to the component overview page and there is a blue alert message at the top
5. Click on 'project page' link

# Expected
The link would redirect the user to the main project overview page

# Actual
The link just refreshes the component page and the blue alert disappears
![project page link not working](https://cloud.githubusercontent.com/assets/10926926/8875908/3e4fba6e-31ea-11e5-80be-9136e48df5a1.png)

**Comment by chennan47** [comment]
This problem has been fixed on production
