### ISSUE TITLE
User Settings: Long project titles break UI for "Disconnect Account" link for Dataverse, Mendeley and Zotero

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3804]
Reported on the 0.43 trello board by @WillBanner

## Steps

1. Log in to osf.io.
2. Create a project with a really long name. 
3. Connect the project to the Dataverse, Mendeley, and Zotero add-ons on the project settings page.
4. Navigate to User Settings > Configure Add-on Accounts
5. Scroll down to look at the Dataverse, Mendeley, and Zotero add-ons.
6. Look at the "Disconnect Account" link.

## Expected Behavior

I expect the "Disconnect Account" to remain on one line.

## Actual Behavior

"Disconnect Account" is broken up across four lines.

## Screenshots

![dataverse_long_title](https://cloud.githubusercontent.com/assets/7093086/8878802/24050414-31fb-11e5-80ff-ab2df4781023.png)

![long_project_titles](https://cloud.githubusercontent.com/assets/7093086/8878804/28ff78a0-31fb-11e5-8142-ce6792854d78.png)

**Comment by Johnetordoff** [comment]
@nanchen47 can I get this one?
