### ISSUE TITLE
Change Password empty fields warning has wrong style and looks different across browsers

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3805]
Reported on the 0.43 trello board by @jinluyuan 
Trello card: https://trello.com/c/cWxRufp5/71-change-password-empty-fields-warning-has-wrong-style-and-looks-different-across-browsers

## Steps

1. Log in to osf.io and head to your User Settings.
2. Click on "Account Settings" in the side navigation bar. 
3. Scroll down to the "Change Password" widget.
4. Without filling in any of the fields, click on the "Update Password" button.
5. Notice the warning that appears.
6. Test this across all four browsers and note the differences.

## Expected Behavior

That the messages will have the correct style and be consistent across browsers.

## Actual Behavior

See screenshots below.

## Screenshots

**Safari**

![safari_-_warning](https://cloud.githubusercontent.com/assets/7093086/8879563/28fe278e-3200-11e5-8261-802e19fcf8ac.png)

**IE 11**

![ie_11_-_warning](https://cloud.githubusercontent.com/assets/7093086/8879571/3963c48a-3200-11e5-8f79-9a7d0576e40f.png)

**Firefox**

![firefox_-_warning](https://cloud.githubusercontent.com/assets/7093086/8879580/4a10dc32-3200-11e5-9864-6c9526fc5d17.png)

**Chrome**

![chrome_-_warning](https://cloud.githubusercontent.com/assets/7093086/8879587/5f107f84-3200-11e5-878a-c4cff4b7af85.png)

**Comment by NatashaRichter** [comment]
**Comment by @sloria** (from trello board) : @caneruguz What are your thoughts on styling required validation messages ?

Revanth used the native HTML 'required' attribute here.

This raises a more general question of using native form validation/controls vs. using our own implementation (KO-validation or otherwise).

On one hand, native controls leaves styling up to the browser, leading to minor UI inconsistency (hence this card). On the other hand, native form validation may be desirable because all browsers (incl. mobile browsers) can take advantage of them. Not to mention the simplicity of implementation.

Unless this feature is broken, I recommend that we defer changing this until we discuss how to do form validation moving forward. @revanthkolli

**Reply by @caneruguz**: @sloria1 Yes I agree that we need to talk about this more.

My vote would be to use our custom validation styles and do cross browser testing on that. But what that exactly entails needs some discussion.

**Comment by chennan47** [comment]
There is also the same problem on the front-end email verification on add unconfirmed email. They are using html input type check which is provided by browser and thus will have different appearance based on different browser.

**Comment by GaryKriebel** [comment]
Closed
