### ISSUE TITLE
User Settings: Incorrect error message when Amazon S3 credentials not entered

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3810]
## Steps

1. Log in to osf.io and navigate to your User Settings.
2. Click on "Configure Add-on Accounts" in the side nav bar
3. Without entering credentials to the Amazon S3 fields, click the "Save" button.
4. Notice the red warning that appears.

## Expected

I expect the error message to say that the Access Key and Secret Key fields are required.

## Actual

The user sees this red error message instead (which is about buckets and not access/secret keys):

![amazons3_message](https://cloud.githubusercontent.com/assets/7093086/8883726/0f49ad4e-321f-11e5-82de-ce7934c633f9.png)

**Comment by Johnetordoff** [comment]
@nanchen47 Can I get this one?

**Comment by caneruguz** [comment]
@haoyuchen1992 might already be working on this?

**Comment by haoyuchen1992** [comment]
@caneruguz @Johnetordoff  Yes, I started to work it a while ago. I can work on it.

**Comment by Johnetordoff** [comment]
No problem
