### ISSUE TITLE
[Staging & Producation] Project Organizer Folder Button Message Lag

### ISSUE THREAD

**Issue by geeksnglitter** [CenterForOpenScience/osf.io#3820]
## Steps
1. Go to any project.
2. Click the file folder in the upper right corner to add the project to your dashboard.
3. Click it again to remove it from your dashboard.

## Expected
When you are not hovering over the folder icon the "Add to Dashboard Folder" and "Remove from Dashboard Folder" messages would disappear.

## Actual
4.The "Add to Dashboard Folder" and "Remove from Dashboard Folder" messages do not disappear and even overlap one another.
![screen shot 2015-07-27 at 10 06 31 am](https://cloud.githubusercontent.com/assets/7839433/8908274/25908ba0-3449-11e5-976f-778ed0f760f4.png)
![screen shot 2015-07-27 at 10 06 20 am](https://cloud.githubusercontent.com/assets/7839433/8908266/227daae2-3449-11e5-96b6-221202312786.png)

**Comment by haoyuchen1992** [comment]
I can work on this, thanks!

**Comment by lbanner** [comment]
You got it!

**Comment by nanchen47** [comment]
The pr has been merged.
