### ISSUE TITLE
User Settings - Amazon S3 and figshare display OSF user's name instead of add-on accountholder

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3835]
### Steps
1. For all OSF add-ons, ensure that your name is the same (for me, "Jinlu Yuan" is the owner of each account)
2. Log into osf.io or staging.osf.io under a user that does not have the name of your add-on accounts' holder (or you can change the name of your current OSF account to something other than your add-on accounts' name)
3. Go to Account Settings
4. Configure all add-ons 
5. Notice the name following "authorized by" for each add-on

### Expected behavior
I expected that each "authorized by" name would be the same.

### Actual behavior
The specific problem this issue covers is that Amazon S3 and figshare display the name of the OSF user (Susie Soo) instead of the add-on's accountholder (Jinlu Yuan).

(As already addressed by #2031, GitHub and Zotero display the username of the add-on accountholder, not the full name of the user.)

![screen shot 2015-07-27 at 3 45 02 pm](https://cloud.githubusercontent.com/assets/8591162/8916016/aa2ff3aa-3476-11e5-9166-385a9879dbd0.png)

**Comment by lbanner** [comment]
Known issue due to technical obstacles --

**Comment by erinmayhood** [comment]
Is fixed with refactor.
