### ISSUE TITLE
File grid's information modal has incorrect information for non-contributors

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3837]
### Steps
1. Go to osf.io
2. Go to any public project that has multiple files visible, or any other project in which you only have read access 
3. In the Files widget (aka. File grid), click the "i" button
4. Review the information in the modal that appears

### Expected behavior
I expected that the modal would not say anything about "Select Multiple Files" or "Copy Files" since those are not features that non-contributors can access. 

### Actual behavior
I see that information.

![screen shot 2015-07-27 at 4 21 04 pm](https://cloud.githubusercontent.com/assets/8591162/8916799/df89154a-347b-11e5-8954-8979eb89b992.png)

### Explanation

A non-contributor is obviously unable to copy files. The "Select Multiple Files" information should not be displayed since a non-contributor does not actually have any options available once multiple files are selected:

**Non-contributor**
![screen shot 2015-07-27 at 4 24 57 pm](https://cloud.githubusercontent.com/assets/8591162/8916827/119af936-347c-11e5-874d-672a6b455e0c.png)

**Contributor**
![screen shot 2015-07-27 at 4 25 55 pm](https://cloud.githubusercontent.com/assets/8591162/8916843/32c63e2c-347c-11e5-9718-e4f4abbdaedb.png)

**Comment by haoyuchen1992** [comment]
I just checked it and tried to show the text conditionally. However, since the file tree is created by fangorn.js, there is no specific parameter which tells whether a visitor is contributor or not.  To make it simple, should we apply easy alternative way to show the difference? For example, add text "Only for project contributor" or else:
![screenshot 2015-07-28 11 45 57](https://cloud.githubusercontent.com/assets/5420789/8936510/b5eb5720-3520-11e5-8630-5a280b49eb22.png)

**Comment by jinluyuan** [comment]
@haoyuchen1992 I think that's a good idea. 

@lbanner @GaryKriebel What do you think of this rewrite? This will also cover the issue with users not knowing that folders have to be expanded in order to download as zip.

I combined the Select Rows and Select Multiple Files information since they're so related. Also, I de-capitalized the bold text. 

At the very least, we should go with adding the information for Copy Files, which is the problem addressed in the OP.

>### How to use the file browser

>**Select rows:** Click on a row (outside the add-on, file, or folder name) to show further actions in the toolbar. Use Command or Shift keys to select multiple files.

>**Open files:** Click a file name to go to view the file in the OSF. 

>**Open files in new tab:** Press Command (Ctrl in Windows) and click a file name to open it in a new tab.

>**Download as zip:** Click on the row of an add-on or folder and click the Download as Zip button in the toolbar. Folders must be expanded before the Download as Zip button can appear. *Not available for all storage add-ons.*

>**Copy Files:** Press Option (Alt in Windows) while dragging a file to a new folder or component. *Only for contributors with write access*.

**Comment by caneruguz** [comment]
@sloria can you confirm that wht @haoyuchen1992 is saying above is in fact correct, can we not use context variables or other methods to pass to fangorn this information? 

@GaryKriebel can you put discuss label on this while we figure it out?
