### ISSUE TITLE
User Settings: Align links on Account Settings page

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3839]
## Description

Head to your User Settings > Account Settings. Add an alternate email and an unconfirmed email.

Notice how the links "make primary" and "resend confirmation" are not aligned. Also the, "make primary" text is too far from the red "x".

## Screenshots

![make_links_align](https://cloud.githubusercontent.com/assets/7093086/8918172/6a880176-3484-11e5-928f-a6904c5838d5.png)

**Comment by haoyuchen1992** [comment]
I can work on it, Thanks!

**Comment by lbanner** [comment]
Done!
