### ISSUE TITLE
GitHub branch goes back to default (master) in file details page

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3841]
### Steps
1. Go to github.com
2. Go to one of your repos for OSF testing
3. Ensure that your GitHub repo has Master as its default branch (check in Settings)
4. Create a new branch 
5. Upload a file into the new branch
6. Go to osf.io
7. Go to one of your projects that has GitHub enabled and configured
8. In project settings, ensure that the relevant GitHub repo is connected
9. Go to the project's overview page
10. In the files widget, select the GitHub repo
11. In the top menu that appears, change the branch to the new branch
12. Click to view the file in the new branch
13. Confirm that you are taken to the file details page

### Expected behavior
I expected that the side menu in the file details page would list the correct GitHub repo branch (the new one, not the default/master).

### Actual behavior
The side menu automatically switches back to the default branch. In order for the user to view another file in the new branch, he must go back to the project overview page or files page, change the branch again, and then click on a file.

![screen shot 2015-07-28 at 10 02 06 am](https://cloud.githubusercontent.com/assets/8591162/8933232/bbe0b4a6-350f-11e5-9a2f-ad305c93d15c.png)

**Comment by caneruguz** [comment]
It looks like in here: 
https://github.com/CenterForOpenScience/osf.io/blob/develop/website/static/js/fileViewTreebeard.js#L13
the if logic is failing because ```window.contextVars.file.extra.branch``` goes to false because extra is null. 

It gets set here: https://github.com/CenterForOpenScience/osf.io/blob/develop/website/templates/project/view_file.mako#L164

@samanehsan do you know where that mako variable gets its value from?

**Comment by samanehsan** [comment]
@caneruguz, that value gets passed in from the view here: https://github.com/CenterForOpenScience/osf.io/blob/develop/website/addons/base/views.py#L455

**Comment by caneruguz** [comment]
@samanehsan for some reason the extra field is not being filled properly. It looks like you wrote that function, do you have some time to look into this issue?
