### ISSUE TITLE
Too little spacing for GitHub buttons on project settings

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3844]
Enable and configure GitHub for a project and then decrease screen width:
![screen shot 2015-07-28 at 10 37 20 am](https://cloud.githubusercontent.com/assets/5975444/8935528/30c26624-351b-11e5-8036-1f88e8133de9.png)

There should be more spacing between the buttons and the dropdown menu.

**Comment by haoyuchen1992** [comment]
I can work on it, Thanks!

**Comment by lbanner** [comment]
Done!
