### ISSUE TITLE
Too little spacing for links in Add Links modal

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3848]
## Description

Navigate to one of your projects and from the Overview page, click on the "Add Links" button. Notice the links in the modal. 

More space is needed between the links and the "Results" and "Adding" headers.

## Screenshot

![add_links_need_more_space](https://cloud.githubusercontent.com/assets/7093086/8936973/6c33d014-3523-11e5-8940-f0c237fb1c05.png)

**Comment by chennan47** [comment]
![screen shot 2015-07-28 at 1 47 32 pm](https://cloud.githubusercontent.com/assets/4974056/8938918/713b4018-352f-11e5-8827-504cbfb700e4.png)
All those modals have the same spacing. Doesn't seems a problem to me.

**Comment by NatashaRichter** [comment]
Ah okay, thanks @chennan47 I was looking at links in other places, but they are consistently spaced within modals, as you wrote. Still might look nicer to add a little bit of space between the link and headers in modals, but it's not a big issue. We can close if you like or leave it for discussion.

**Comment by lbanner** [comment]
@NatashaRichter and @nanchen47 If OK, I will close this for now -- for greater consideration, we might consider a StyleGuide submission/proposal (?). Thanks!
