### ISSUE TITLE
Project Overview page: Add underline to link in blue warning

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3849]
## Description 

Navigate to a private project with a public Github repo connected to it. Look at the blue warning at the top of the project's overview page and notice the link (hard to see because not underlined). Then, create a new component on the project. Look at the blue warning at the top of the component's overview page and notice the link (underlined). I also looked at an old registration of the project to look at the blue warning on that page. Notice the link is also underlined there.

We should create consistency between appearance of links in warnings (underlined versus not). It seems more of the warnings have links that are underlined rather than not underlined.

At this time, the style guide does not differentiate in regards to different use cases for links.

## Screenshots

**Project Overview page**

This warning should have **here** underlined to match underlining of links in other places on the site (as in the other screenshots below).

![link_no_underline](https://cloud.githubusercontent.com/assets/7093086/8939426/53dca87e-3532-11e5-8daa-c9bbc1334b6f.png)

**Component Overview page**

![component_overview_underlined](https://cloud.githubusercontent.com/assets/7093086/8939451/7bafc7fa-3532-11e5-8b6b-27ef3d014c04.png)

**Registration**

![registration](https://cloud.githubusercontent.com/assets/7093086/8939479/a677dc2a-3532-11e5-8f49-3ed9dc38cbf9.png)

**Comment by chennan47** [comment]
This looks more like a bug that the first one warning about github should have a under line.

**Comment by NatashaRichter** [comment]
Thanks @chennan47, I will edit the title of this issue accordingly.

**Comment by Johnetordoff** [comment]
@nanchen47 can I get this?
