### ISSUE TITLE
File Tag UI

### ISSUE THREAD

**Issue by caseyrollins** [CenterForOpenScience/osf.io#3852]
The implementation of file tagging ([WIP PR here](https://github.com/CenterForOpenScience/osf.io/pull/3113)) will require adding another UI element to the file detail page. From discussion with @JeffSpies, the two options that would integrate best with our existing functionality on the page would be to either have the tag box above or below the file navigation tree (shown in the first screenshot), or to change the Revisions panel to an "Information" panel which could hold both the tag box and the revisions table (shown in second screenshot).

1. Tag box above file navigation tree 
![screen shot 2015-07-28 at 2 34 22 pm](https://cloud.githubusercontent.com/assets/7913604/8940525/7e785d98-3538-11e5-97ff-85439f1f819b.png)

2. Tag box as a part of an "Information" panel
![screen shot 2015-07-28 at 2 52 52 pm](https://cloud.githubusercontent.com/assets/7913604/8940529/83431f3e-3538-11e5-95de-2473cf4d4399.png)

**Comment by caseyrollins** [comment]
I've also looked into how other storage services handle adding tags to files -- out of Dropbox, GitHub, Google Drive, and Box, Box is the only service that offers file tagging. The gif below shows the process of adding a file tag in Box.

[![Gyazo](http://i.gyazo.com/170d4c6b726bba47d25ad18dbd747e83.gif)](http://gyazo.com/170d4c6b726bba47d25ad18dbd747e83)

**Comment by caseyrollins** [comment]
ping @JeffSpies

**Comment by JeffSpies** [comment]
@caneruguz @bnosek @saradbowman Can you comment on this when you get a chance? Thanks!

**Comment by saradbowman** [comment]
I'd vote for putting the tags on the right side (@caseyrollins' second screenshot) because they're on the right on the project overview page. That also separates things associated with this file (revisions + tags) on the right from actions to get to another file (file tree) on the left.

**Comment by bnosek** [comment]
Definitely above revisions.  In using the file viewer page, it is most natural to bounce around the tree on the left a bit to see different files (separate issue, it would actually be useful to be a bit wider to see the full file names, many get cut-off).

Having tags above revisions makes sense because neither need to be in the viewer's face as a default.  They are viewable when the person toggles there.  

I like parts of how Box does it, but for the future when we improve our navigation and representation.

**Comment by GaryKriebel** [comment]
FWIW, I agree with @saradbowman and @bnosek .... putting it on the right constrains actions/descriptions for that file on one side and navigation to all files on the other.

**Comment by lbanner** [comment]
+1 on the above discussion ... right side appears most appropriate.

**Comment by caseyrollins** [comment]
Follow-up question, does "Information" make sense as the new title for that panel? Or would a title such as "More Information" or "More Actions" be more descriptive?

**Comment by bnosek** [comment]
How about "File Info"

**Comment by caneruguz** [comment]
I also agree with the top right on this decision. I have been suggesting to people working on any aspect of this file detail page that the right column should be a more all-encompassing action and revision list so I'm glad we are moving in that direction. 

I think "File Info" is good, my only concern is whether using Info sounds too colloquial. Another option could be "Details".

**Comment by bnosek** [comment]
details is good

**Comment by JeffSpies** [comment]
+1
