### ISSUE TITLE
"View File" tooltip for Dataverse should not exist

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3858]
### Steps
1. Go to osf.io or staging.osf.io
2. Go to one of your projects
3. Enable and configure Dataverse for your project
4. Ensure that your connected Dataverse has files in it
5. Go to the files widget in the project overview page or the Files page
6. Hover over a file in Dataverse
7. ~~Try to open the file in a new tab or window~~

### Expected behavior
I expected that files in Dataverse would not have a "View File" tooltip since none of the other storage add-ons display this behavior. 
~~I also expected to be able to open up the Dataverse file in a new tab by either right clicking the file and choosing "Open Link in New Tab" or by pressing the Command key and clicking the file. All files in other storage add-ons are able to be opened in a new tab.~~

### Actual behavior
I see the tooltip when I hover over the file.
~~I also cannot open the file in a new tab through either method. "Open Link in New Tab" and "Open Link in New Window" are not options in the right-click menu.~~

It looks like @sloria removed unnecessary Dataverse tooltips in https://github.com/CenterForOpenScience/osf.io/commit/87a1ea35acec83ffdd8b5f5e20ceeec71baf7b58, but not this one.

![screen shot 2015-07-28 at 4 26 24 pm](https://cloud.githubusercontent.com/assets/8591162/8942791/6b5af1dc-3545-11e5-8580-10281c9d2c00.png)

### Note 7/29
@Johnetordoff and I decided that the tooltip is unrelated to the issue that Dataverse files cannot be opened in a new tab.

**Comment by Johnetordoff** [comment]
@lbanner Can I get on this?

**Comment by Johnetordoff** [comment]
@jinluyuan the right click functionality isn't tied to the tooltips currently. The other addons can't open a new tab from right click either.

**Comment by sloria** [comment]
That tooltip is unnecessary. I think we should remove it there and for all addons.

**Comment by sloria** [comment]
Ah, read the "Expected" section after posting my previous comment; sorry for the redundancy. So yes, go with Jinlu's suggestion on the expected behavior.

**Comment by Johnetordoff** [comment]
It also says  "All files in other storage add-ons are able to be opened in a new tab." I don't get that behavior, so I'm confused. But I've removed the tooltip,

**Comment by jinluyuan** [comment]
@Johnetordoff Are you sure you can't get them to open in new tabs? I'm not claiming that clicking on a file opens a new tab. I am saying that I *can* open them in a new tab, either by right clicking or by Cmd + click.

**Comment by Johnetordoff** [comment]
I can't right clicking doesn't give the option, Cmd + click actually produces the following error:
![screen shot 2015-07-29 at 2 12 56 pm](https://cloud.githubusercontent.com/assets/9688518/8965838/0190a488-35fc-11e5-989f-9c5b10248a54.png)
I'll test this bit it probably something wrong I'm doing.

**Comment by jinluyuan** [comment]
@Johnetordoff I'll meet with you about this
