### ISSUE TITLE
update and redirect "about" information

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3862]
From a conversation regarding: https://github.com/CenterForOpenScience/community/issues/294

* osf.io/about should redirect to osf.io/4znzp/wiki/home/
* osf.io/howosfworks/ should redirect to osf.io/getting-started/
* until further updates to the actual content of the "about" OSF project (4znzp), "About" should be removed from the header navigation and footer of the OSF

**Comment by sloria** [comment]
@lbanner @GaryKriebel At what stage of the proposal process is this? Is this ready for implementation + QA, or are we holding for feedback?

**Comment by jlcohoon** [comment]
For context, said conversation was part of the triage meeting Monday morning.

**Comment by lbanner** [comment]
I think w/ @jlcohoon's go on this, we are good.
