### ISSUE TITLE
Modify add-on icons in user & project settings

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3867]
The current icons have fuzzy quality because they have been resized through css. 

![screen shot 2015-07-29 at 11 06 21 am](https://cloud.githubusercontent.com/assets/8591162/8961220/ecf06b0e-35e1-11e5-8b5f-fb1d8a095e4a.png)

Furthermore, some of the icons differ from what the official, company-sanctioned trademarks should be. This really only applies to Dropbox and Box, but I've listed out all the add-ons. Amazon S3's case is tricky.

- **Amazon S3** does not have an officially licensed logo that we can use. The [AWS trademark guidelines](http://aws.amazon.com/trademark-guidelines/) only describe how to use the "Powered by Amazon Web Services" logo, and logos other than "Powered by" are not mentioned. Amazon provides zip downloads of the [Simple Icons for Architecture Diagrams](http://aws.amazon.com/architecture/icons/), which includes the standard Amazon S3 red geometric icon, but these icons are only licensed for diagrams. Unsure what to do.
- **Box** [branding guidelines](https://box-content.readme.io/docs/branding-guidelines) and [logos](https://app.box.com/shared/cr5fggo7sd/1/1232053181)
- **Dataverse**'s website does not have information about logos and trademarks.
- **Dropbox** [logos](https://www.dropbox.com/branding)
- **figshare**'s website does not have information about logos and trademarks.
- **GitHub** [logos](https://github.com/logos)
- **Google Drive** [logos](https://developers.google.com/drive/web/branding)
- **Mendeley** does not have information about logos and trademarks.
- **Zotero** does not have information about logos and trademarks.

**Comment by nanchen47** [comment]
Will be considered based on user's feedback. Thanks.
