### ISSUE TITLE
Onboarder project search's timestamp should turn lighter color upon hover 

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3868]
Hovering over a project results in a blue background in the row. The name of the project becomes white, but the "modified" timestamp stays dark gray. The small, dark gray text on a blue background makes it difficult to read the timestamp without hovering off of it.

![screen shot 2015-07-29 at 1 22 53 pm](https://cloud.githubusercontent.com/assets/8591162/8964703/338f32d0-35f5-11e5-9ba3-d5c5ad9e210f.png)

**Comment by chennan47** [comment]
The purpose of the timestamp is to help user to identify two projects with the same name altho timestamp does not seem to be the best solution but it is what we have now. The information is useful before u select it rather than you already select one.

**Comment by jinluyuan** [comment]
@chennan47 I don't have a problem with the timestamp. I would just prefer it become a lighter gray or white when I hover over it, so I can read it easier. This is a small style issue.

**Comment by jinluyuan** [comment]
@chennan47 I see what you mean that the information is useful before selecting rather than after, but hovering over a project does not mean I have already selected it. A lot of people hover over items in a list or point their mouse at each row in order to keep track of where they are in the list.

**Comment by Johnetordoff** [comment]
@jinluyuan , @chennan47  This would be very simple to fix and I think if the title is highlighted the time stamp should be consistent with that. You can see in the example it's more difficult to read the highlighted time stamp.
