### ISSUE TITLE
Settings tab viewable on component registration

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3870]
## Description

A week ago, I registered one of my components (Almond), which is a child of the parent project, Walnut. When I click into the registration of the component, I see a "Settings" tab and can click into it, as well.

## Expected behavior

I would expect to only see a settings page on a parent registration to retract registration. However, since you can't retract a component's registration, I should not be able to see the settings page.

## Actual behavior

I am able to see and click into the settings page, where I see the message: "This component is a registration of this component; the content of the component has been frozen and cannot be edited" (see screenshot below).

## Screenshot

![registration_settings_tab](https://cloud.githubusercontent.com/assets/7093086/8966648/8229c85a-3600-11e5-81bc-694f8f49b157.png)

**Comment by NatashaRichter** [comment]
@HarryRybacki

**Comment by HarryRybacki** [comment]
@lbanner @GaryKriebel please assign me

**Comment by HarryRybacki** [comment]
@NatashaRichter can you attempt to reproduce this bug again? I just tried and was prompted by what I think to be a satisfactory response:
![screen shot 2015-08-10 at 11 08 45 am](https://cloud.githubusercontent.com/assets/2614670/9174818/4ee403d0-3f50-11e5-932b-ca3f7bd951f2.png)
