### ISSUE TITLE
Delay after clicking Save button and actual save needs some kind of loading indicator

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3871]
### Steps
1. Go to staging.osf.io
2. Go to one of your account settings
3. Change any field in your Profile Information
4. Click the Save button
5. Notice the delay between clicking Save and the green "Settings updated" text appearing

### Expected behavior
I expected that while there's a delay between clicking Save and actually saving, I would get some indication that my changes were being processed, such as the Save button's text changing into a lighter color "Saving" button until the "Settings updated" message appeared below.

For example, the Add button in the New wiki page modal changes to "Creating New Wiki page" before the page is successfully created.
![screen shot 2015-07-29 at 9 58 29 am](https://cloud.githubusercontent.com/assets/8591162/8966650/85617586-3600-11e5-9ecb-409bf91c39eb.png)

In project settings, the link to connect/import an account changes to a grayed out "Loading..." message before the account is successfully imported.

![screen shot 2015-07-29 at 2 46 47 pm](https://cloud.githubusercontent.com/assets/8591162/8966700/bfa6f586-3600-11e5-8429-c8cb65887f46.png)

### Actual behavior

![save](https://cloud.githubusercontent.com/assets/8591162/8966746/0fc0f6c0-3601-11e5-9d3a-6755967e81ac.gif)

Since there's a delay before the "Settings updated" message appears, the user may think the changes were successful and try to leave the page before they are actually processed.

**Comment by Johnetordoff** [comment]
@nanchen47 can I get on this?

**Comment by lbanner** [comment]
Done!

**Comment by GaryKriebel** [comment]
Closed
