### ISSUE TITLE
View-on links should open in new tab

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#3878]
Clicking a view-on link to open a file stored on Github, figshare, or Google Drive opens the file in the current window. 

It would be helpful if the file opened in a new tab, so it was easier for a user to return to the OSF when done viewing the file on 3rd party storage.

**Comment by jinluyuan** [comment]
This is related to https://github.com/CenterForOpenScience/osf.io/issues/3419.

@saradbowman In talks about the "View on" feature, @caseyrollins said that some users' browsers do not allow the new tab to be opened and instead show a "pop-up blocked" message. The team decided to go with opening these links in the same page to guarantee that they all open, and the user can still manually open links in a new tab.

**Comment by caneruguz** [comment]
@GaryKriebel does this mean this issue should be closed?

**Comment by nanchen47** [comment]
Based on the discussion above, close this one.
