### ISSUE TITLE
Some buttons are inconsistent with OSF style

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3879]
## Amazon S3 project settings
Clicking the Create button prompts the user to enter a new bucket name. The blue button should say "Confirm", not "OK". [Style guidelines](https://centerforopenscience.github.io/osf-style/style.html#buttons)

![screen shot 2015-07-30 at 9 43 25 am](https://cloud.githubusercontent.com/assets/8591162/8984422/87efe090-369f-11e5-88a4-65fc8716133b.png)

Entering an invalid bucket name prompts an error message modal. The button text "Try new one" is a little awkward. It would be better as "Try again".

![screen shot 2015-07-30 at 9 43 19 am](https://cloud.githubusercontent.com/assets/8591162/8984421/87ec1410-369f-11e5-9c33-6ed16442c657.png)

## Project deletion
Clicking the Delete project button produces this modal. The button in the bottom right should be a red "Delete" button, not a green "Confirm" button, since clicking it results in a removal action. [Style guidelines](https://centerforopenscience.github.io/osf-style/style.html#buttons)

![screen shot 2015-07-30 at 9 46 19 am](https://cloud.githubusercontent.com/assets/8591162/8984497/f66b53ba-369f-11e5-99bc-625d576e0174.png)

## Add new wiki page modal
Once the user clicks the Add button in the modal, the button text changes into "Creating New Wiki page". The word "page" should be capitalized.

![](https://cloud.githubusercontent.com/assets/8591162/8966650/85617586-3600-11e5-9ecb-409bf91c39eb.png)

If the user tries to enter a wiki page name that already exists, red error text appears. The modal's button then changes to a green OK button. The button should stay as a green Add button. 

![screen shot 2015-07-30 at 11 45 34 am](https://cloud.githubusercontent.com/assets/8591162/8987793/c4c87c64-36b0-11e5-8ccf-67ba924718af.png)

If the user clicks the Cancel button after the red error text appears and then clicks the wiki menu's New button to add another page, the Add new wiki page modal has an OK button. Refreshing the page makes this change back to an Add button.

![screen shot 2015-07-30 at 11 47 54 am](https://cloud.githubusercontent.com/assets/8591162/8987805/d5f80694-36b0-11e5-8558-bbc75bfceacd.png)

**Comment by NatashaRichter** [comment]
@jinluyuan Update on button capitalization: https://github.com/CenterForOpenScience/osf-style/issues/71

**Comment by jinluyuan** [comment]
@NatashaRichter Oh I didn't realize that Lauren's issue covered the buttons too. 

Since the button case is still being worked on, most of that part of my issue can be ignored for now. 
However, "Try new one" should really be changed to "Try again" since it just sounds weird saying "Try new one", and "Creating New Wiki page" needs to either be all sentence case or all title case.

**Comment by haoyuchen1992** [comment]
I will look at it. Thanks!

**Comment by haoyuchen1992** [comment]
'Name a new bucket' page on project setting has been changed because of @HarryRybacki 's previous PR. So it's follow the style guide now.

For the new bucket name checking, better solution should be applied. Here is the issue #3905
