### ISSUE TITLE
Project Settings > GitHub "Create Repo" button is broken

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3880]
### Steps
1. Go to osf.io
2. Go to one of your projects
3. In project settings, enable and configure GitHub
4. Click the Create Repo button next to the repo names

### Expected behavior
I expected to be able to create a new repo.

### Actual behavior
Nothing happens when I click the button.

Error console:
![screen shot 2015-07-30 at 10 21 27 am](https://cloud.githubusercontent.com/assets/8591162/8985323/c8d35538-36a4-11e5-815b-7e2091709c3c.png)

**Comment by nanchen47** [comment]
The fix has been deployed on production.
