### ISSUE TITLE
Mobile site: Navbar obscures search bar if left open

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3881]
## Description

On the mobile site, if I open the navbar, and then click the search icon, the navbar persists. I am able to search, but what I type into the search bar (behind the navbar) is hidden (see picture below). We should have the navbar close upon clicking the search icon.

## Phone Screenshot

![image](https://cloud.githubusercontent.com/assets/7093086/8985452/8721215a-36a5-11e5-9544-c7d3c259a657.png)

**Comment by haoyuchen1992** [comment]
@lbanner  I already submitted a PR yesterday, please assign to me, Thanks!
