### ISSUE TITLE
Fix language for the blue Dataverse and Google Drive add-on messages on forked projects 

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3886]
## Steps

1. On osf.io, navigate to one of your projects.
2. On your project settings page, enable and configure all of your add-ons.
3. Fork the project.
4. On the forked project, notice the blue messages that appear in reference to your add-ons.

## Expected behavior

I expect the add-on warnings to have consistent language.

## Actual behavior

The Google Drive and Dataverse add-on messages need to be fixed. Dataverse refers to the forked project as a "component," when it isn't, and Google Drive just says "fork" instead of "forked project."

![standardize_fork_warning_language](https://cloud.githubusercontent.com/assets/7093086/8988847/a4e651d6-36b6-11e5-9006-49776598eac1.png)

**Comment by jinluyuan** [comment]
@NatashaRichter Did you notice that Dataverse authorization is listed twice? The first one says "component", but the second one says "project".

**Comment by NatashaRichter** [comment]
@jinluyuan The fact that there are two makes this even weirder! I'll look into that issue separately by forking other projects and then see why Dataverse might be double-listed here.

**Comment by jinluyuan** [comment]
@NatashaRichter I think something like this issue about strange repeated/wrong alerts has come up before, either on GitHub or Trello. It's happened to me as well.

**Comment by NatashaRichter** [comment]
Related to: https://github.com/CenterForOpenScience/osf.io/issues/2644

**Comment by jinluyuan** [comment]
@NatashaRichter This turns out to be an exact repeat of https://github.com/CenterForOpenScience/osf.io/issues/2616. I think we should close this issue in favor of the old one since the old one has more discussion in it.

**Comment by NatashaRichter** [comment]
Closing in favor of: https://github.com/CenterForOpenScience/osf.io/issues/2616
