### ISSUE TITLE
Link needs underline in blue messages on forked project

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3887]
## Steps

1. Log in to osf.io and navigate to one of your projects.
2. Go to your project settings page. 
3. Check all the boxes for all add-ons and click "apply," but do not configure the add-ons.
4. Go to the project overview page.
5. Click on the duplicate button and choose to create a fork.
6. Click the "Fork" button on the modal that appears. 
7. Notice the blue messages at the top of the newly forked project's overview page.

## Expected behavior

I expect the link "Settings" to be underlined in the messages for all of the add-ons; this would be consistent with behavior for links in these kinds of messages across the site.

## Actual behavior

"Settings" is not underlined.

## Screenshot

![more links needing underline](https://cloud.githubusercontent.com/assets/7093086/8990039/d8274a6c-36bd-11e5-856d-d3a4f9c9203b.png)

**Comment by NatashaRichter** [comment]
This is similar to my other issue: https://github.com/CenterForOpenScience/osf.io/issues/3849

**Comment by jinluyuan** [comment]
This alert for Two-factor authorization needs an underline for "activate your device".

![screen shot 2015-07-30 at 3 15 10 pm](https://cloud.githubusercontent.com/assets/8591162/8992676/e0550a34-36cd-11e5-8137-430d9679e1c6.png)

**Comment by Johnetordoff** [comment]
@nanchen47 I can do this
