### ISSUE TITLE
Standardize order of view/edit panes across pages

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3888]
# Steps
1. Go to a project on which you are an admin
2. Upload an editable .txt file to OSF Storage
3. Click on the file to view it in the file details page
4. Click to toggle Edit to open the edit pane
5. Notice the order of the Edit and View panes
6. Now, go to the Wiki tab
7. Click to toggle Edit to open the edit pane
8. Notice the order of the Edit and View panes

# Expected
I expect that the panes would be in the same order, whether on the files or wiki page.

# Actual
The Edit and View panes are **not** in the same order on the files vs wiki pages.

### Files page:
**Toggle buttons:**
![files toggle buttons](https://cloud.githubusercontent.com/assets/5975444/8990481/9f15f89c-36c0-11e5-93d3-393153d48374.png)

**Order of panes:**
![files pane order](https://cloud.githubusercontent.com/assets/5975444/8990483/a2aec6f0-36c0-11e5-940a-f68e7ae874fc.png)

### Wiki page:
**Toggle buttons:**
![wiki toggle buttons](https://cloud.githubusercontent.com/assets/5975444/8990487/a63eaef2-36c0-11e5-89b5-4c7927aa4997.png)

**Order of panes:**
![wiki pane order](https://cloud.githubusercontent.com/assets/5975444/8990491/a975909a-36c0-11e5-82fd-192cdfcf63f1.png)

Personally, I think it looks better when the View pane always stays immediately to the right of the files/wiki menus (how it is on the files page).

**Comment by Johnetordoff** [comment]
@GaryKriebel can I get on this?
