### ISSUE TITLE
re-enable reordering of components

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3892]
## Steps
1. Visit a project that you are an admin on that has multiple components that you are also an admin on
2. In the widget on the right, click on a component and try to drag to re-order it among the others.

## Outcome
1. Re-ordering is not possible

## Expected Outcome
1. Re-ordering had previously been enabled (I've used it on the RPP: https://osf.io/ezcuj/), so I expected to be able to drag and drop to reorder. 

** Notes: ** I am not sure that it was only admins who could reorder. 

Tagging @caneruguz because it is possible this is a side effect of UI updates.

**Comment by caneruguz** [comment]
@GaryKriebel and @jlcohoon I just submitted a quick fix for this. 

It was not related to style changes as far as I could tell.

**Comment by jlcohoon** [comment]
great! thank you!!
