### ISSUE TITLE
[contributors] Interaction between clicking and dragging

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#390]
Dragging the contributors to change order does not have a space buffer. This means that, if someone clicks the remove button while the mouse is moving just a bit, it will appears as if the button kind of clicked but didn't really. It took a while to nail down what was happening, as I thought maybe it was some kind of issue with the button itself.

Ultimately it rarely comes up, and you tend to re-click without thinking about it. I think, when we want to seriously polish it, the drag action should not overtake the click action unless the drag happens by a certain number of pixels before the mouse release.

**Comment by JeffSpies** [comment]
I'd like to see a demo of this. Is it on staging?
