### ISSUE TITLE
'Activate your device' link not working for two-factor authentication

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#3901]
# Steps
1. Log in to osf.io
2. Go to user settings
3. Click on Account Settings on the left navbar
4. Click to enable two-factor authentication
5. Scan the barcode using a google authenticator on your phone and put in your code
4. Hit submit
5. Now go to your Dashboard to navigate away from the User Settings page
6. Notice the blue alert message at the top and click on 'Activate your device' link

# Expected
The link should redirect the user to the appropriate page. (Not too sure where it should redirect or that if the link is even necessary)

# Actual
Clicking on the link does nothing

![activate your device link does not work](https://cloud.githubusercontent.com/assets/10926926/9015250/a5080706-3795-11e5-8f35-29e8fc7d97dd.png)

**Comment by Johnetordoff** [comment]
@nanchen47  can I get this one?

**Comment by sloria** [comment]
Hm, that alert shouldn't even appear on the dashboard page (or any page other than the user settings page).

**Comment by nicipfeiffer** [comment]
@sloria has this been fixed and merged?

**Comment by erinmayhood** [comment]
Yes.
