### ISSUE TITLE
[Enhancement] Real-time name checking when user input their new name

### ISSUE THREAD

**Issue by haoyuchen1992** [CenterForOpenScience/osf.io#3905]
### Steps
1. Go to configure add-on in project setting page
2. Create new bucket in Amazon s3
3. Input a name (input 'a')

### Actual
It doesn't tell me anything wrong when I input the new bucket name. Only after I submit the new name, it says it is a invalid name but without any further explanation, such as what the valid name should be.
![screenshot 2015-08-03 09 01 39](https://cloud.githubusercontent.com/assets/5420789/9037947/477fa7f8-39be-11e5-947d-e04252780a1a.png)

### Expected
It will check my name while I input it.  Similar as the new password checking in google.
![screenshot 2015-08-03 08 53 20](https://cloud.githubusercontent.com/assets/5420789/9037943/378666f2-39be-11e5-81b1-f7c1c8224e14.png)

**Comment by jinluyuan** [comment]
Just some helpful info!

### Bucket naming rules
Bucket name should conform with DNS requirements: 
- Should not contain uppercase characters
- Should not contain underscores (_)
- Should be between 3 and 63 characters long
- Should not end with a dash
- Cannot contain two, adjacent periods
- Cannot contain dashes next to periods (e.g., "my-.bucket.com" and "my.-bucket" are invalid)

([Source](https://forums.aws.amazon.com/message.jspa?messageID=315883))

These are the rules which if broken, will pull up the "Invalid bucket name" modal shown above. It makes sense to have an inline check for those to save the user time and confusion, or the "Invalid bucket name" modal could just have this bulleted information for the benefit of the user.

However, there's another rule for bucket names that needs a server-side check.

> The bucket name you choose must be unique across all existing bucket names in Amazon S3
([Source](http://docs.aws.amazon.com/AmazonS3/latest/gsg/CreatingABucket.html))

Breaking the unique name rule brings up a different modal, the "Problem creating bucket 'name'" modal, and cannot be checked while in the process of inputting. (Example: try to create a bucket named "ireland").

**Comment by lbanner** [comment]
Shall we document the above ^^ somewhere?

**Comment by GaryKriebel** [comment]
Closed
