### ISSUE TITLE
Update Can't Render File text to include download statement

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3907]
from the community repo: https://github.com/CenterForOpenScience/community/issues/325

## Steps
1. Visit a file that cannot be rendered (e.g. a zip file)
2. Read the error message displayed on the screen

## Outcome
1. The error message reads "No renderer could be found for the file type requested."

## Suggested Outcome
1. No renderer could be found for the file type requested. Please download the file to view.

**Comment by haoyuchen1992** [comment]
I can work on it, thanks!

**Comment by lbanner** [comment]
Done!

**Comment by haoyuchen1992** [comment]
@jlcohoon @lbanner Can we make it simpler ? Such as "Currently we don't support to view this format of file online, please download it to view." Because renderer is kind of abstract.

**Comment by lbanner** [comment]
"We do not currently support viewing of this file type within the OSF. Please download the file to view." <---- @jlcohoon ?

**Comment by jlcohoon** [comment]
How about even simpler: "This file cannot be viewed, please download it to see the contents."

If that's too curt, I vote for Larry's suggestion.

**Comment by haoyuchen1992** [comment]
It may be better to explain why it can't be viewed and I also vote  for Larry's suggestion. So go for it? :) @jlcohoon @lbanner

**Comment by lbanner** [comment]
One more: "Viewing of this file type within the OSF is not currently supported. Please download the file to view."

**Comment by jlcohoon** [comment]
That's better. Go with that.

**Comment by haoyuchen1992** [comment]
OK! Go this, Right?--"Viewing of this file type within the OSF is not currently supported. Please download the file to view."   And since this is about file rendering, the change should be made in mfr. I will send a PR there.

**Comment by haoyuchen1992** [comment]
@lbanner  I just tested the message, which has been changed.

**Comment by lbanner** [comment]
:+1:
