### ISSUE TITLE
Change order of Keep Both button

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3914]
The current style of button order on the OSF is that the "Cancel" button is on the left, and the action button is on the right. 

When a user tries to move a file to a folder or component that already has a file by that same name, a modal appears that has two action buttons. It makes sense for the two buttons to be next to each other instead of having Cancel sandwiched in between.

Staging (new look)

![screen shot 2015-08-03 at 1 08 05 pm](https://cloud.githubusercontent.com/assets/8591162/9043429/5186aaa6-39e3-11e5-83c0-448f3adcca02.png)

Production (old look)

![screen shot 2015-08-03 at 1 26 37 pm](https://cloud.githubusercontent.com/assets/8591162/9043430/518ab92a-39e3-11e5-9ec7-72256be516d5.png)

**Comment by lbanner** [comment]
Suggestion is to make order: CANCEL REPLACE KEEP BOTH? ..... And does your "Staging" screenshot represent a UI change not yet on Production? Possibly a PR currently on Staging but not merged?

**Comment by jinluyuan** [comment]
@lbanner Sorry, I should have been clearer. I'm proposing that the order be "CANCEL, KEEP BOTH, REPLACE" since "Keep Both" is an option that is in between "Cancel" and "Replace" (which would delete the original file). 

The staging screenshot shows a UI change on staging that hasn't been merged to production yet. Since the order of the buttons is independent of the UI changes, I decided to put this on GH instead of a trello card.

**Comment by lbanner** [comment]
Got it -- Thanks! .... so, FYI to any dev .... best this issue follows the deployment of PR / Staging to Production. Likely on Develop for 0.45.0 release.

**Comment by caneruguz** [comment]
@lbanner @jinluyuan  This should be fixed in the 0.45 Trello board, there was a card about the color of the keep both button.

**Comment by jinluyuan** [comment]
@caneruguz Got it, thanks!
