### ISSUE TITLE
Improve language of email notification for removing alternate email address

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3922]
This sentence should be changed since it uses first person and has a comma splice.

>I just wanted to let you know, the email address pearsoncreed@gmail.com has been removed from your account.

Better version (removes the beginning clause)

>The email address pearsoncreed@gmail.com has been removed from your account.

### Screenshot

![screen shot 2015-08-03 at 4 12 58 pm](https://cloud.githubusercontent.com/assets/8591162/9047028/f63f516a-39fc-11e5-923d-cb2bd52735f6.png)

**Comment by lbanner** [comment]
But the change is not as polite, yes? :smiling_imp:

**Comment by jinluyuan** [comment]
@lbanner It seems uncharacteristic of the OSF emails to have first person narration. Robots don't need to be polite!

**Comment by sloria** [comment]
I like the suggested change. Ping @jlcohoon for a final "go" or "nogo" on this.

**Comment by jlcohoon** [comment]
I like it. There should be a second email that pairs with this (the alternate and primary get this email). Both should be updated.
