### ISSUE TITLE
Registrations page should not display Recent Activity for retracted registrations

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3928]
### Steps
1. Go to osf.io or staging.osf.io
2. Go view any public project that has a retracted registration
3. Go to the Registrations page of the project
4. Locate the retracted registration
5. Click the down arrow to expand the Recent Activity

### Expected behavior
I expected that there would not be a down arrow to allow viewing of Recent Activity. Alternatively, I expected that upon clicking the down arrow, there would be a message that indicates the Recent Activity information has been retracted/removed.

### Actual behavior
![screen shot 2015-08-04 at 11 28 55 am](https://cloud.githubusercontent.com/assets/8591162/9064820/506cef40-3a9c-11e5-92a1-2d01a6ab47c1.png)

**Comment by Johnetordoff** [comment]
@nanchen47 can I get this?

**Comment by nanchen47** [comment]
@Johnetordoff any update on this one?
