### ISSUE TITLE
Dropbox credentials message does not persist long enough

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3935]
## Description

I just tried to import my Dropbox account information on a project. I was met with the message below. However, the message did not persist long enough (at least on Chrome) for me to finish reading it, so I had to go through the steps again and then captured the message quickly.

I was familiar with what the message would say, but it still does not persist long enough.

For longer messages like this one, let's have them persist a little longer on the screen (especially for users unfamiliar with the content). This may apply to other add-ons, as well.

![dropbox_credentials_message](https://cloud.githubusercontent.com/assets/7093086/9068420/5a82352a-3ab1-11e5-948b-48ff012d999a.png)

**Comment by caneruguz** [comment]
@NatashaRichter I took a look at this, the error is not supposed to disappear at all. I'm having a hard time creating the error itself, can you try this one more time?

**Comment by NatashaRichter** [comment]
Thanks @caneruguz. I am not able to reproduce this right now. Let's close it and if I notice it again, I'll come find you and show you.
