### ISSUE TITLE
Add-on request: Evernote

### ISSUE THREAD

**Issue by livethedance** [CenterForOpenScience/osf.io#3937]
Is there any chance someone can add Evernote (https://evernote.com) as an Add-on? I use it to keep my research notebooks because it is such a flexible app.

**Comment by GaryKriebel** [comment]
@livethedance we have actually discussed this as a future feature.  I have updated our internal tracking system by adding your request for the Evernote addon.

I'm going to close the issue here as it is being tracked elsewhere.

**Comment by rdhyee** [comment]
@livethedance what type of features would you like to see in an Evernote addon?
