### ISSUE TITLE
Mendeley add-on folders 

### ISSUE THREAD

**Issue by livethedance** [CenterForOpenScience/osf.io#3938]
When I try to select a folder to use from Mendeley, only some of the folders it contains appear as options. I see this: (https://cloud.githubusercontent.com/assets/12090449/9070172/e1d53e30-3ae5-11e5-85b2-dfeda50e1cec.png)

Instead of this: (https://cloud.githubusercontent.com/assets/12090449/9070202/0cc25740-3ae6-11e5-9036-a3c45727bc42.png)

**Comment by GaryKriebel** [comment]
Based on the information provided, this looks like it will be fixed with the release of the following PR:
https://github.com/CenterForOpenScience/osf.io/pull/3900

I will follow up with you after it releases this week to see if you are still experiencing the issue.
