### ISSUE TITLE
swap order of configure commenting and notifications

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3944]
## Current Behavior
In the Project Settings, "Configure Commenting" is below "Configure Notifications."

![screen shot 2015-08-05 at 10 22 29 am](https://cloud.githubusercontent.com/assets/4965832/9088046/18cccb80-3b5c-11e5-8561-c0997108bcde.png)

## Suggested Behavior
Because notifications are a result of commenting (at least at the present moment, the notifications are dependent on comments being left), they should be listed after the commenting configuration panel.

**Comment by sloria** [comment]
The suggested order change will be in effect in https://github.com/CenterForOpenScience/osf.io/pull/3397. See https://github.com/CenterForOpenScience/osf.io/pull/3397#issuecomment-133438729
