### ISSUE TITLE
Can create multiple S3 buckets with the same name 

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3947]
## Steps

1. Log in to osf.io.
2. Head to your project settings page.
3. Select and configure the Amazon S3 add-on.
4. Create a bucket with the same name as one you already have in existence.
5. Try this with multiple bucket names.

Alternatively, ping me for access to: https://osf.io/vnmyr/
There, create the bucket "blackmore," and you'll see you are able to create it multiple times.

On staging, I am able to create multiple buckets with the same name and in the same location.

## Expected behavior

I expect that each time I try to create a bucket I already own, I will be met with the "Problem creating bucket [insert bucket name]" modal that tells me I already own a bucket with that name.

## Actual behavior

For some bucket names, like "blackmore," I am able to create multiples of it. However, the bucket only shows up once in the drop-down menu. For others, I am met with the modal that informs me that I already own a bucket with that name.

**Comment by NatashaRichter** [comment]
From trello card: https://trello.com/c/T6LR7SHs/69-can-create-multiple-buckets-with-the-same-name-in-the-same-location

**Comment by HarryRybacki** [comment]
Regarding S3, bucket names must be unique across all server locations and user attempting to use them. 

This specific problem is resulting from another odd boto specific behavior. 

- If you attempt to create a **US Standard** bucket with a name you have previously reserved it will simply return the bucket you already have created.
![screen shot 2015-08-10 at 10 37 04 am](https://cloud.githubusercontent.com/assets/2614670/9174045/cf807f78-3f4b-11e5-9a08-7951beac51fa.png)

- If you attempt to create a **NON US Standard** bucket with a name you have previously reserved it will return a `BucketAlreadyOwnedByYou` error that our error handler already knows how to handle.
![screen shot 2015-08-10 at 9 30 39 am](https://cloud.githubusercontent.com/assets/2614670/9173998/925439c8-3f4b-11e5-89d8-ffcf40a704be.png)

The result of this behavior is that we have no way of differentiating between a successfully created bucket or a failed attempt to create a **US Standard** bucket that already exists and is associated with our credentials.

Note that if you attempt to create *any* bucket with a name that is already reserved it will return `BucketAlreadyExists` error.
![screen shot 2015-08-10 at 10 34 19 am](https://cloud.githubusercontent.com/assets/2614670/9174021/9ff7c4b4-3f4b-11e5-8bbe-9611b66c6911.png)

@NatashaRichter

**Comment by HarryRybacki** [comment]
@NatashaRichter are you okay with closing this?

**Comment by HarryRybacki** [comment]
@lbanner @GaryKriebel ^^

**Comment by NatashaRichter** [comment]
@HarryRybacki @lbanner @GaryKriebel I'm cool with closing this now. Thanks for the explanation, Harry!

**Comment by lbanner** [comment]
OK!
