### ISSUE TITLE
Greyed out files grid background obscures navbar upon scroll

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#3948]
# Steps
1. Go to a project on which you have admin access
2. If the project does not already have components, add a component
3. Upload the same file into OSF Storage for the parent project and for one of the components
4. Locate the file in the component
5. Drag it into OSF Storage for the project to move the file
6. Confirm that an modal pops up saying that a file with that name already exists in the target location
7. Without exiting the modal, scroll down the page
8. Look at the project navigation bar

# Expected
I expect that the greyed out background and modal would be contained within the file grid and would *not* overlap the project navbar.

# Actual
The greyed out background and modal overlap the navigation bar upon scroll:

![screen shot 2015-08-05 at 10 49 06 am](https://cloud.githubusercontent.com/assets/5975444/9090769/2c6075f8-3b6a-11e5-8115-271b3bf6ae4c.png)

**Comment by caileyfitz** [comment]
tagging @caneruguz

**Comment by nanchen47** [comment]
@NatashaRichter can you verify if this has been fixed on production?

**Comment by caileyfitz** [comment]
@nanchen47 I checked on production, and it looks fixed!

**Comment by nanchen47** [comment]
Thanks @caileyfitz
