### ISSUE TITLE
Go/Nogo for 0.45.0

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#3949]
Includes S3 bucket location selection and server-side encryption of uploads and a number of UI fixes.

milestone: https://github.com/CenterForOpenScience/osf.io/pulls?q=is%3Apr+is%3Aclosed+milestone%3A0.45.0

trello: https://trello.com/b/saiiLiob/0-45

ping @JeffSpies @GaryKriebel @lbanner @caileyfitz @nicipfeiffer

**Comment by sloria** [comment]
Deployment note: will require a waterbutler release @chrisseto @icereval

**Comment by JeffSpies** [comment]
With both out, is this smart to release? Will they have availability in
case of unforeseen circumstances?

On Wednesday, August 5, 2015, Steven Loria <notifications@github.com> wrote:

> Deployment note: will require a waterbutler release @chrisseto
> <https://github.com/chrisseto> @icereval <https://github.com/icereval>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/issues/3949#issuecomment-128051702>
> .
>


-- 
Sent from mobile.

**Comment by GaryKriebel** [comment]
@JeffSpies took my comment ... are they aware of the release?  They are both listed as PTO for the next two days .... would they be available in the event of an issue and would we even be able to contact them?

**Comment by lbanner** [comment]
Good questions -- Their intent was to be working / online and available ... but they are at a conference and it is in Vegas. @sloria If we don't get any confirmation on their part, then we probably put this on ice (?)

**Comment by chrisseto** [comment]
Both @icereval and I will be avaible until ~7pm EST

**Comment by sloria** [comment]
OK, I will be out today ~4:45-8:30 EST. If we don't have all "go's" by then, then we can hold on releasing this and continue work on 0.46.0.

**Comment by JeffSpies** [comment]
Getting on plane soon; assume my "go" unless--given schedules--it isn't
practical to go tonight. Not a problem to wait until better alignment of
schedules--just keep Johanna updated.

**Comment by sloria** [comment]
Update:

- We are holding deployment until Chris's, Michael's, and my schedules align. I believe Chris and Michael are available remotely on Monday. ping @icereval @chrisseto for confirmation.
- QA is finishing up the last few cards on the 0.45.0 board.
- QA is almost finished with 1st pass for all markupsafe-3 cards. `feature/markupsafe-3` still exists as its own branch so that it can be released independently of 0.45.0. However...
- If QA finishes with markupsafe-3 before the time we are ready to deploy 0.45.0, we can include markupsafe-3 in the release. QA will have a more accurate feasibility estimate when they are finished with the 1st pass cards.

I am a "go" for releasing 0.45.0 as is. 

My "go" to include markupsafe-3 is dependent on QA's assessment.

ping @JeffSpies @lbanner @GaryKriebel @caileyfitz @nicipfeiffer 

Once we have all a "go" for 0.45.0 (w/o markupsafe-3), I will put the 0.46.0 release branch on staging.

**Comment by lbanner** [comment]
That sounds right to me .... I'm a GO on 0.45.0 .... let's keep moving! Thanks.

**Comment by GaryKriebel** [comment]
Yes, the calendar states they will be remote on Monday, but good to get their confirmation.

I'm good with the plan.

I'll provide a Go when the remaining few bugs are fixed and cleared through QA.

**Comment by nicipfeiffer** [comment]
I am also a GO for 0.45 release when schedules align for deployment.

**Comment by JeffSpies** [comment]
With others' dependencies met, you have my go.

**Comment by nicipfeiffer** [comment]
In addition, I am confident in saying that QA will be a GO for release of markup safe 3 with the release of 0.45 on Monday.

**Comment by lbanner** [comment]
Woot Woot! :smiling_imp:

**Comment by chennan47** [comment]
@sloria can this be closed?

**Comment by sloria** [comment]
Yes
