### ISSUE TITLE
Mendeley & Zotero - Download citation button does not work

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3951]
### Steps
1. Go to osf.io
2. Go to one of your projects
3. If you don't already have Mendeley and Zotero enabled and configured, do so
4. Go to the project overview page
5. Go to the Mendeley and Zotero widgets
6. Expand any folder collection
7. Click the Download Citation button

![screen shot 2015-08-05 at 12 04 14 pm](https://cloud.githubusercontent.com/assets/8591162/9090759/23a3e83c-3b6a-11e5-8360-c8194adef5cb.png)

### Expected behavior
I expected to download the citation.

### Actual behavior
[Safari] I get taken to a blank web page with this:

![screen shot 2015-08-05 at 12 04 50 pm](https://cloud.githubusercontent.com/assets/8591162/9090777/31179b62-3b6a-11e5-95d7-1a6b51755cef.png)

My browser's address bar contains this:
>data:text/plain;charset=utf-8,%20%20%3Cspan%20class%3D%22csl-entry%22%3EBrandon_baby.%20(n.d.).%3C%2Fspan%3E%0A%0A%20%20%3Cspan%20class%3D%22csl-entry%22%3EIMG_7863.%20(n.d.).%3C%2Fspan%3E%0A 

Different behavior in Chrome & Firefox -

When I click to download, a .txt file is downloaded onto my computer. However, the file only has the same text shown above in Safari (`<span class...`) instead of the actual citation style chosen (APA, MLA, etc.).

**Comment by jinluyuan** [comment]
Just checked this again. When I click to download, a .txt file is downloaded onto my computer. However, the file simply has the image shown above (<span class...) instead of the actual citation style chosen (APA, MLA, etc.).

**Comment by mfraezz** [comment]
Some citation styles have different text styling (**bold**, *italic*, etc.). These aren't supported in `.txt` files. I'll have to figure out exactly what's going on first, but the cleanest solution that comes to mind would be sending the already formatted text (the html I received has the right style tags for APA) to the MFR's unoconv extension, and having it export back an `.rtf` or `.pdf`, or possibly some other filetype.

@lbanner @GaryKriebel , thoughts?

**Comment by GaryKriebel** [comment]
@mfraezz seems to have a logical solution to this.

**Comment by jinluyuan** [comment]
@mfraezz I think an `.rtf` would be appropriate since people will want to copy and paste from the document. A `.pdf` would have some accessibility issues.

**Comment by mfraezz** [comment]
Okay. I'm not terribly familiar with MFR's use of `unoconv`, but I know that is a possibility of the third-party `unoconv` library. It may require minor adjustments to the MFR first, which I'll begin investigating.

**Comment by mfraezz** [comment]
The MFR currently doesn't have the required functionality exposed, any there isn't enough reason to expose it at present. It can all be done with JS if you get the `.rtf` headers correct, which I'm working on
