### ISSUE TITLE
[production + staging] Capitalization is not consistant

### ISSUE THREAD

**Issue by geeksnglitter** [CenterForOpenScience/osf.io#3955]
The OSF has inconsistent capitalization.
As shown in: https://github.com/CenterForOpenScience/osf-style/issues/71

There are now rules for capitalization in the style guide: https://github.com/CenterForOpenScience/osf-style/pull/75

This issue is to instigate movement towards fixing those inconsistencies and bringing the capitalization of the OSF to the newly changed standards.

Some places that need particular attention:
Buttons
Links
Pannel titles
Side navigation bars
Form labels

Note: All of these places the text needs to be changed to sentence case.

**Comment by geeksnglitter** [comment]
@haoyuchen1992 & @caneruguz

**Comment by caneruguz** [comment]
Sounds like a good intern task! Thanks @geeksnglitter 
Guidelines are here: http://localhost:8000/language.html#capitalization
