### ISSUE TITLE
No indication of limit on characters in comments

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#3961]
Very long comments have the potential for display issues. To deal with very long comments (rather than imposing a character limit), please add a scroll bar to the commenting boxes.
## Steps
1. Comment on a project.
2. Make it a long comment.
## Expected

You could keep writing until something told you that you're not allowed to write any more.
## Actual

The typing just stops with no other indication that there's a limit.

If there's a character limit to comments, there should be a countdown that indicates how many characters are left. Better is to do like a lot of twitter clients and not limit the characters in the input field, but to indicate how many characters you are over and disable save until you're at the right amount. This would let you put in your comment and edit it after it's done.

**Comment by chennan47** [comment]
@samanehsan will the comment panel pr cover this?

**Comment by samanehsan** [comment]
No, it will not

**Comment by Ghalko** [comment]
You could do it text-message style with a second comment being made out of the overflow from the first comment.
