### ISSUE TITLE
osf.io/login does not show the correct branding or "remember me" option

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#3973]
noted in a community issue: https://github.com/CenterForOpenScience/community/issues/333#issuecomment-128753862

## Steps
1. Log out of the OSF
2. Go to accounts.osf.io/login and look at the branding and options on the page
3. Go to osf.io/login and look at the branding and options on the page

## Outcome
1. accounts.osf.io/login has the COS logo and a "remember me" option. 
![screen shot 2015-08-07 at 11 23 53 am](https://cloud.githubusercontent.com/assets/4965832/9140801/b26ab166-3d01-11e5-808e-c7c587501c9a.png)
2. osf.io/login just says "sign in" in text above the sign in fields. No "remember me" option is available.
![signin](https://cloud.githubusercontent.com/assets/4965832/9140798/aef0d240-3d01-11e5-9a41-56eb34368f92.png)

3. The pages' formatting differ in other respects (grey background vs. no grey background to the form, different buttons, extra HR).

## Expected outcome
1. The two pages should have the same visual look, the same branding, and the same options.

**Comment by lbanner** [comment]
I believe this approach has been discussed as intentional here #3026 (?)

**Comment by jlcohoon** [comment]
This isn't about the "COS" logo or if it should be "OSF," it's the fact that two login pages for the OSF are formatted differently with different features.

**Comment by lbanner** [comment]
Noted .. wrong discussion .. how about this discussion? #2358

**Comment by jlcohoon** [comment]
Also different because that was talking about the lack of navbar/footer. 

The most important thing from *this* issue is the no "remember me" option. Really, the two pages should be identical, however.

**Comment by mfraezz** [comment]
There was likely a breaking change with recent style guide modifications, as the style on the login, password reset, and two-factor auth pages are all affected (see https://github.com/CenterForOpenScience/osf.io/pull/2365 and compare with production). @haoyuchen1992 might know what's causing this.

As for the "remember me" checkbox: I don't think that's ever been on the `osf.io/login/` page, but it shouldn't be difficult to add.

**Comment by haoyuchen1992** [comment]
@mfraezz @jlcohoon  Actually, when applying in style guide, we may not touch this page. Maybe there is style missing. If not, I can add "remember me" instead.

**Comment by caneruguz** [comment]
@jlcohoon 
I don't think the pages should be identical necessarily. COS login is a service that is independent of the OSF. It's branding should not be OSF and it should not have the OSF headers and components. I think we agree up to here. 

In terms of its look that's up for discussion, it could be made to apply the same style as the OSF, but I don't think that's very necessary. It would be simple to change though.  

About the remember me, this is a separate discussion of whether we want the remember me button in OSF, my opinion is yes, we should definitely have that check box.

The current OSF login pages do have a broken style, they are missing the panel-default style and are using instead the removed osf-panel I think. That's a bug and needs to be fixed; @haoyuchen1992 is on that.

**Comment by jlcohoon** [comment]
I'm not sure I understand. This isn't about whether or not we have COS or OSF branding. The issue is that we have two different login pages for the OSF with disparate looks and features. 

For example, if I attempt to log in to the OSF but mess up my login, I find myself at accounts.osf.io/login:
![screen shot 2015-08-10 at 4 41 57 pm](https://cloud.githubusercontent.com/assets/4965832/9183816/99e340d8-3f7f-11e5-88f9-b7c68369a5da.png)

Then, I forgot my password and I click the link which sends me to the password reset request page.

Then, I click "reset password" and the page refreshes and I'm at osf.io/login:
![screen shot 2015-08-10 at 4 42 46 pm](https://cloud.githubusercontent.com/assets/4965832/9183831/a8142a6e-3f7f-11e5-9b0c-70cdeef66ffd.png)

The two login pages are different but both are attempting to bring the user to the OSF. *Especially* after forgetting a password, the "remember me" option would be very helpful. I'd also think that since this is likely a common user story and is only over a short time period, having visual consistency between the pages is important. Is the panel bug what's making the formatting different? Is there a reason that we have two pages at all?

**Comment by lbanner** [comment]
I get it - and thanks for finding form whence a user hits 'osf.io/login' @jlcohoon -- I want to suggest we tie this into next Epic, as we consider overall site consistency and navigation. OK @erinmayhood ?

**Comment by caneruguz** [comment]
@jlcohoon is making good points, the user experience managing login is potentially causing confusion. The panel bug is not the main reason for formatting, the two login systems are designed entirely differently and the universal login does not take any design clues from OSF, it's rather mimicking other single login systems. Is there a reason we have two pages is a bigger discussion but the quick answer is yes, the universal login can be used for other services as well.

I don't see the problem so much as that two pages look different but that we use them both in a single user experience. If we have a universal login system why don't we handle all login related issues through that including password recovery? 

I agree with @lbanner that this will need a revision of consistency and would benefit from a high level look into what the login experience is.

**Comment by jlcohoon** [comment]
@icereval, do you know what the purposes for the two pages are? Are there differences in functionality?

**Comment by erinmayhood** [comment]
@caneruguz can you consider these pages as you work on: https://openscience.atlassian.net/browse/OSF-4148? As we add login pages from target sources we should make sure to have the consistency issues existing here cleaned up.

@caneruguz I'd love a very specific list of changes you would recommend here so we can make assignments.

**Comment by caneruguz** [comment]
@erinmayhood having an external login complicates things significantly for us. I think we need a functionality review before I can make suggestions about concrete tasks. Preferably to answer these questions?

- Is our authentication system (CAS) built to be invisible in terms of UI and just provide backend support? If that's the case why are we sent to its login page?
- Why is CAS not handling forgotten password recovery? If it is, why are there pages in CAS for this purpose and the user has to do it over OSF?
- Is there a difference in OSF between someone who registered an account before CAS and after? Do they get different user experiences? 
- Can someone register a new account with CAS? How does that effect our own onboarding process? 

It looks to me like we should not be using a CAS interface at all in the meantime while these are sorted out, i.e. the user should never see the CAS login. The experience should be either one or the other, not a combination of two.

For our purpose of combined login/register we can have an OSF widget for it or a CAS Widget that is embeddable to OSF pages (i.e. it's not its own page).

I'm not sure if all this is clear, but I'm happy to discuss further.

**Comment by GaryKriebel** [comment]
Closed
