### ISSUE TITLE
Incorrect cursor when hovering over typeahead results

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#3978]
### Steps

On your Dashboard, type into any of the onboarder widgets that have a typeahead input. Hover over a result with your mouse.

### Expected

Cursor is a pointer, since results are clickable

### Actual

Cursor is for text.

Should be a very quick fix.

**Comment by haoyuchen1992** [comment]
@sloria I just check the  issue. I think it has been solved.
