### ISSUE TITLE
[osf] Discrepancies in Benchmarks.py and Search

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#3979]
Related to #2853

In search, a wildcard search for projects yields 2475 projects (should only return public projects)

In benchmarks.py (https://github.com/CenterForOpenScience/osf.io/blob/750125e9cbaaf51ca55938ab1380166e133801d8/scripts/analytics/benchmarks.py), current value for public projects value is 3175.

There are inconsistencies between search and the scripts that should be addressed so we have a full picture of OSF use. 

Also inconsistent in benchmarks.py is file_download vs number_download, which give very different values (278k vs. 433k). This number is particularly important for reporting to funders. 

I started documentation on the metrics in the community repo, here: https://github.com/CenterForOpenScience/community/blob/master/UserMetrics.md
but would appreciate help in clearing up confusion on definitions for some metrics.

**Comment by chennan47** [comment]
The banchmark.py result should be trusted since it is directly getting numbers from OSF database. While the public search is getting result from elastic search database. The difference between the number suggesting that there is inconsistency in updating elastic search database.

**Comment by chrisseto** [comment]
@saradbowman I'm not sure why there is a `file_download` and a `number_download` at all but the discrepancy is because `downloads-total` and `downloads-unique

**Comment by chrisseto** [comment]
As for projects the value is skewed because its counting registrations as well as (folders created via project organizer)[https://github.com/CenterForOpenScience/osf.io/blob/750125e9cbaaf51ca55938ab1380166e133801d8/scripts/analytics/benchmarks.py#L172].

**Comment by chrisseto** [comment]
As for projects the script is counting registrations as well as unregistered projects.
![screen shot 2015-08-19 at 10 02 03](https://cloud.githubusercontent.com/assets/5532905/9358327/5fdc8008-4659-11e5-85fb-ac5fb3112003.png)
What do you think is the correct behavior @saradbowman?

**Comment by GaryKriebel** [comment]
Closed
