### ISSUE TITLE
Improve user-facing error message when editing project titles in prohibited ways

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3981]
## Steps
1. Log in to osf.io.
2. Navigate to one of your projects.
3. Edit the project title so that your title is contained in angle brackets.
4. Notice the error message.

## Expected behavior

An error message informing me that the project title cannot be updated as suggested due to presence of characters that are not allowed as entered. Or, we can simplify the message further, saying that the project title cannot be updated as suggested and to try entering another title.

## Actual behavior

The user is met with "Unexpected Error: Bad Request," which is not a helpful message for our users.

## Screenshot

![bad_request_error_message](https://cloud.githubusercontent.com/assets/7093086/9172318/dad847bc-3f40-11e5-967c-cc391b463c74.png)

**Comment by erinmayhood** [comment]
Done.
