### ISSUE TITLE
[Safari] Files grid jumps when clicking a row for the first time upon page load

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3987]
### Steps
1. Sign into osf.io in Safari
2. Go to one of your projects
3. In either the project overview page or the files page, click on any row in the files grid (project name, add-on name, file, etc.)
4. Click on another row
5. Repeat this in any other browser (Chrome, FF, IE)

### Expected behavior
I expected that the first click in Safari would behave like all the other browsers.

![normal behavior](https://cloud.githubusercontent.com/assets/8591162/9177917/492e5b4a-3f62-11e5-9631-6407b07871f9.gif)

### Actual behavior
The files grid jumps for a fraction of a second. It's very noticeable, but quick. After this first click upon the page load, clicking another row (Step 4) does not cause a flash. 
(I couldn't capture it in a gif due to the low frame rate of my usual mov-gif converter.)

**Comment by haoyuchen1992** [comment]
@nanchen47  I can look at it, thanks!

**Comment by lbanner** [comment]
You got it!

**Comment by haoyuchen1992** [comment]
After playing around for a while, I find it happens in two other situations. Firstly, go to the project with admin right.
1.   changing the selection from osf-storage icon to github icon for the project with 
2.   changing the selection from osf-storage icon to the file under that osf-storage icon

**Comment by haoyuchen1992** [comment]
@lbanner  after discussing with @caneruguz, we suggest to defer this bug. Firstly, it doesn't hurt any functionality and only happens on Safari. And also it is hard to debug.

**Comment by lbanner** [comment]
Deferred!

**Comment by nanchen47** [comment]
Will be considered when refine the file grid.
