### ISSUE TITLE
OSF Help Page is placeholder

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/osf.io#3998]
## Priority

Probably quite trivial.

Will become more relevant once we have more content (eg API and OAuth developer docs) in the near future.

## Description
The OSF has had a help page route (https://osf.io/help/) since 2013, but only as an unstyled placeholder. As we add more help content (including for developers) this should be reorganized and made consistent.

For now, it might make sense to redirect `/help` to the FAQ or getting started pages so that users who guess a URL would be able to get help.

**Comment by GaryKriebel** [comment]
Closed via https://github.com/CenterForOpenScience/osf.io/pull/5810
