### ISSUE TITLE
No header on information modal on project overview and files tab

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3999]
## Steps

1. Log in to osf.io.
2. Navigate to one of your projects.
3. From your project overview page, click the "i" button above the files widget.
4. Then, head to your files tab and click the "i" button.

## Expected behavior

I expect to see what I do when I click the information button on staging: a header reading, "How to Use the File Browser."

## Actual behavior

The modal has no header in both places on Production.

## Screenshots

**Staging: Project Dashboard**

![staging_header](https://cloud.githubusercontent.com/assets/7093086/9198559/eea63e14-400a-11e5-9e28-929afe862676.png)

**Staging: Files Tab**

![staging_files_tab](https://cloud.githubusercontent.com/assets/7093086/9198621/4cb3f35c-400b-11e5-9a09-6e7ad0bf4457.png)

**Production: Project Dashboard**

![production_no_header](https://cloud.githubusercontent.com/assets/7093086/9198604/2dcbeb70-400b-11e5-89b2-7cbd058b0f74.png)

**Production: Files Tab**

![no_header_how_to_use_file_browser](https://cloud.githubusercontent.com/assets/7093086/9198574/0f6a1f80-400b-11e5-8d30-fc92d20beb00.png)

**Comment by nanchen47** [comment]
@NatashaRichter this issue doesn't seem to have a high priority and once staging gets merged into production. This should be fixed. I suggest closing this issue.

**Comment by lbanner** [comment]
That sounds good - I will make it so!

**Comment by NatashaRichter** [comment]
@nanchen47 okay, how do we know that this wasn't a regression from the release though?

**Comment by NatashaRichter** [comment]
@caneruguz @haoyuchen1992 Could you check this out? I was worried this might be a regression after the release.

**Comment by sloria** [comment]
This should now be fixed
