### ISSUE TITLE
[Safari] No green success message after configuring commenting

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#4001]
## Steps

1. Log in to osf.io.
2. Navigate to one of your projects. 
3. Head to the project settings page.
4. Scroll down to Configure Commenting.
4. Choose an option and click Save.

## Expected behavior

In Safari, I expect to see what I do in Chrome and Firefox: a green success message informing me that I've successfully updated my settings prior to page refresh. 

## Actual behavior

In Safari, I click save and the page refreshes without showing the success message first (or if it shows, it must flash very briefly before the page refreshes?). I've reproduced this on several projects. 

We should show the green success message to users on Safari, too.

## Screenshots

**Chrome, Firefox**

![success_message_chrome](https://cloud.githubusercontent.com/assets/7093086/9201674/45788132-401c-11e5-8fa2-b5e448968c78.png)

**Safari before clicking save**

![safari_before_save](https://cloud.githubusercontent.com/assets/7093086/9202030/d849d618-401d-11e5-8215-7ce8eea7317c.png)

**Safari after clicking save (button is darker green upon click but there is no message)**

![safari_no_success_message](https://cloud.githubusercontent.com/assets/7093086/9201918/5fdd164a-401d-11e5-8d04-be0239307b12.png)

**Comment by NatashaRichter** [comment]
The same issue occurs with the Apply button when selecting add-ons (no green "settings updated" message is shown). Under Configure Add-ons, though, I do see the green success messages when importing individual add-on accounts from my Profile.

**Comment by haoyuchen1992** [comment]
I can work on it, thanks!
