### ISSUE TITLE
No way to distinguish between projects in Add Links modal

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#4005]
### Steps
1. Sign into osf.io or staging.osf.io
2. Go to one of your projects
3. In the Components widget of project's Overview page, click the "Add Links" button 
4. In the modal that appears, search for a registered project with multiple registrations

### Expected behavior
I expected that for each project or registered project, there would be a timestamp indicating when the project was created or when a registered project was registered. Alternatively, the search results could make the project names links, so the user can open up the link in a new tab to verify that the project is the one he wants to link.

### Actual behavior
There is no way to distinguish between projects of the same name and contributors since there are no timestamps, and the project names do not link to the actual project. 
This is specifically a problem for registrations since a normal project is very unlikely to have the same name and contributors as another project, but registrations can possibly have multiple iterations.

![screen shot 2015-08-11 at 1 45 10 pm](https://cloud.githubusercontent.com/assets/8591162/9205296/47065124-402f-11e5-8faf-906353a45bf0.png)

**Comment by GaryKriebel** [comment]
closed with release 0.82.0
