### ISSUE TITLE
Treebeard modals did not get updated during the 0.45 release

### ISSUE THREAD

**Issue by wisherp** [CenterForOpenScience/osf.io#4009]
The treebeard changes made on staging did not get merged well onto production during the 0.45 release. Notice the difference below:

# Expected (as it is on staging): 
![space between the buttons on staging](https://cloud.githubusercontent.com/assets/10926926/9209393/471634ee-4044-11e5-898f-c595f72b1663.png)

![image](https://cloud.githubusercontent.com/assets/10926926/9209426/742d170e-4044-11e5-87dc-b311c7e499d0.png)

# Actual (on production)
![modal buttons need spacing on prod](https://cloud.githubusercontent.com/assets/10926926/9209404/5588878e-4044-11e5-8688-a960f16b8f25.png)

![image](https://cloud.githubusercontent.com/assets/10926926/9209436/806e2120-4044-11e5-8ebb-bc2fbf99016e.png)

**Comment by chennan47** [comment]
https://github.com/CenterForOpenScience/osf.io/issues/3999related issue

**Comment by caneruguz** [comment]
@steve this looks like an update of install issue. Can you take a look?

**Comment by sloria** [comment]
Yes, needed to reinstall treebeard. Good catch @wisherp
