### ISSUE TITLE
removing self as contributor produces two different modals

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#4016]
## Steps
1. Visit a project where you are a read or read+write contributor
2. Visit the sharing page
3. Click the red 'x' in the row where you are listed
4. Click "Save Changes"
5. Read the modal that appears 
6. Confirm changes

Then

6. Visit a project where you are an admin
7. Visit the sharing page
8. Click the red 'x' in a row where you are listed
9. Click "Save Changes"
10. Read the modal that appears
11. Confirm Changes

## Outcome
1. When you are a read+write or read contributor, the modal confirms that you want to remove yourself as a contributor:
![screen shot 2015-08-12 at 10 30 06 am](https://cloud.githubusercontent.com/assets/4965832/9226688/bd7a4262-40dd-11e5-8382-4003582e3837.png)

2. When you are a read+write or read contributor, the dashboard alert reads: Removed self from project

3. When you are an admin, the modal confirms that you want to save changes:
![screen shot 2015-08-12 at 10 34 47 am](https://cloud.githubusercontent.com/assets/4965832/9226694/c7e0b1e6-40dd-11e5-81d4-f4aa074abd31.png)

4. When you are an admin, the dashboard alert reads: You have removed yourself as a contributor from this project

## Expected Outcome
Considering that, for the user, the actions performed were identical, the alerts and modals should be identical:
1. Both modals should say the same thing
2. Both modals should ask you to confirm that you want to remove yourself as a contributor. This is *especially* important if you are an admin because you are giving up more permissions.
3. Dashboard alerts should say the same thing

**Updated to add dashboard alerts**

**Comment by erinmayhood** [comment]
Fixed.
