### ISSUE TITLE
Remove unnecessary modal when registering project

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#4017]
The registration process has an excess of confirmation steps.

1. Click New Registration -> Modal confirmation
2. The registration form selection page shows the same information as the previous modal.
3. Once finished with the form, type "register"
4. Modal displays showing which addons and files will be registered.
5. As of release 0.46: Confirm modal -> Admins must confirm through email

![register](https://cloud.githubusercontent.com/assets/2379650/9226514/03895ce4-40dd-11e5-8025-d535db55ced1.gif)

Some of these confirmations steps display necessary information; others do not. Of all of these, the first modal is the most redundant, since it displays the same information (what a registration is) as the next page.

### Suggested action

Remove the modal that appears after clicking "New Registration".

**Comment by caneruguz** [comment]
Yes totally agree!

**Comment by sloria** [comment]
This is a minimal code change. With @erinmayhood 's "go", I can go ahead and remove the modal or allow this issue to be claimed.

**Comment by erinmayhood** [comment]
Fixed with registrations changes.
