### ISSUE TITLE
UI issue with the new tag colors

### ISSUE THREAD

**Issue by caneruguz** [CenterForOpenScience/osf.io#4019]
## Steps:
1. Go to a project on osf.io and click on the box to enter a tag
2. Click inside the box but away from the blue box for the new tag input, observe that the blue box is not going away. 
2. Hover over an existing tag

![screen shot 2015-08-12 at 11 17 11 am](https://cloud.githubusercontent.com/assets/1314003/9228000/5dba1a4e-40e4-11e5-929d-7931396fdeab.png)

There are two problems here
1. The blue box over the input element on focus should not be visible
2. The tag should have white text when hoever over and it changes color. This includes the X. 
Also reduce the border radius to 2px to comply with all other components in the page. This will be added to style guide.

**Comment by caneruguz** [comment]
@lbanner PR for this are coming in a bit.

**Comment by lbanner** [comment]
:+1:

**Comment by caneruguz** [comment]
@lbanner I think this is merged and also released with 0.46
