### ISSUE TITLE
Unicode Emoticons in Project Titles disable links to S3 files in Project Logs

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#4025]
Reported on the 0.45 Trello testing board

## Steps
1. Go to a project you have admin access to that has a project name not containing unicode emoticons
2. Go to the project setting page and configure S3 for the project
3. On the Project overview page upload a file to the S3 folder
4. Refresh the page and look at the project logs
5. Confirm that you can see the filename that was just uploaded and that you can click on the link in the log
6. Go to the Title of the project on the project overview page
7. Click on the title to edit the name
8. In the text input field that appears, edit the project name to one that contains an unicode emoticon. Good examples are here http://unicodeemoticons.com/index.htm
9. Click the check mark to save the changes to the project title
10. Return now to the project log
11. Find the file that you recently uploaded to the S3 folder. Try to click on the filename

## Expected
I would expect the Project title to have no effect on the project logs and links to S3 files within.

## Actual
When the project title contains unicode emoticons the links to S3 files in the project logs are no longer available.
![screenshot 2015-08-12 12 41 11](https://cloud.githubusercontent.com/assets/9381062/9230519/9ad2f25a-40f0-11e5-8333-433ab398b3fc.png)

**Comment by lbanner** [comment]
Rather a random edge case, eh? :smiling_imp: I'll tag w/Discuss

**Comment by GaryKriebel** [comment]
Closed
