### ISSUE TITLE
S3 Bucket location is unknown after creation

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#4026]
Reported on the 0.45 Trello board
## Steps
1. Go to project settings for a project with S3 enabled
2. Click to create a new bucket
3. Enter the name and select a location
4. Save the new bucket to your project
5. Go to the settings page and project log to look to see what location you chose
## Expected

As a user that may have collaborators in another region, I may want to have access to the S3 bucket location on my project settings and/or in the project log for reference
## Actual

Once created, the bucket location is no longer accessible
## Comments

Related comments from the testing card https://trello.com/c/j7SAjQWP/56-bucket-location-is-unknown-after-creation : 
@HarryRybacki commented "I think it's a good idea. Our current AddonS3NodeSettings does not currently have any awareness of a location. This would require a bit of 're-plumbing' of the whole thing to get working."
@erinmayhood commented " since location is present for the user during set-up, it should show in our UI. I would recommend having it appear along with the bucket name on the settings page (and not the user activity log to keep that clean)."

**Comment by TomBaxter** [comment]
I'd like to take a look at this, but before I get too far, I wanted to make sure no one else was already looking at it. I see it is marked JIRA and that it has been reported on Trello, neither of which I have access to.

**Comment by TomBaxter** [comment]
I've read through the code and reviewed AWS documentation. While I think this could be achieved without undue effort, I'm not sure this feature would be very useful. All bucket names are unique over all AWS locations. The location is not required for access. I spent some time trying to think of scenarios where an OSF user might need to know the location of the data. The only thing I could think of is if someone had a need to know location for some reason other then accessing the data. For instance, many countries have laws regarding the export/storage of personal data outside of the country they live in. If someone wanted to verify that they were in compliance, that the data was stored in an acceptable region, they could not do that verification through the OSF interface.
  Please let me know if you would like me to pursue this any further, or if you have any other questions.
