### ISSUE TITLE
Mobile: Password warning cut off on front page

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#4031]
Reported on 0.45 Trello board

## Steps
1. Using a mobile device or Chrome with developer tools and mobile browser enabled, go to osf.io
2. Be sure that you are logged out
3. Do not enter any text into the name, email, password, etc fields and click the Sign Up Free button

## Expected
I would see errors that those fields are required and the rest of the page would appear normally

## Actual
The warning to input appears correctly, but now the Sign Up Free button now moves down on the page and occludes the Open Science Framework text.

![screenshot 2015-08-12 15 25 24](https://cloud.githubusercontent.com/assets/9381062/9234362/726664a8-4106-11e5-991c-e8209116279a.png)

## Comments:

Testing card is here : https://trello.com/c/DRdKB1jX/39-mobile-password-warning-cut-off-on-front-page

@caneruguz commented "the fix for this was a quick patch to make the button visible. The ideal solution would have been to extend the space but the designers have done that in a very restricted way. So this gives us two options:
(1)Consider this use case to be a very rare occurance and ignore it. Both the cases where the user clicks sign up without writing ANY field and that they would at the same time be using a mobile device are low. In that case the downside is that there is some covering of text below which is not a functionality hindering issue.
(2)Patch this right now and go back to designers to ask them to create a fix for this situation.
I recommend option 1.

@sloria commented "Yes, I think Caner's suggested option 1 is fine in the short-term. I think we can defer this for now, and send this issue to the design firm"

Ping @lbanner to provide this feedback to the proper channel.

**Comment by caneruguz** [comment]
@lbanner The task for designers would be to look into the sign up form when all or some of the error messages are present and suggest changes to their design that should fit this situation. One solution is to push the background down as well or change the size.
