### ISSUE TITLE
[Production & Staging] [Style Guide] Need change button text when it is disabled 

### ISSUE THREAD

**Issue by haoyuchen1992** [CenterForOpenScience/osf.io#4032]
### Steps
1. Go to project setting
2. Connect Amazon S3 account
3. Change bucket and click Save
 
### Expected
When save button turns disable, it should change the button text from Save to Saving.

###  Actual
Related PR for Similar Issue: https://github.com/CenterForOpenScience/osf.io/pull/3993

![saving](https://cloud.githubusercontent.com/assets/5420789/9233080/1d3fccbe-40ff-11e5-8e47-fd2c8e3b2745.gif)

**Comment by jinluyuan** [comment]
There should be a guideline in the Style Guide about this. This is similar to https://github.com/CenterForOpenScience/osf.io/issues/3871. 

The disabled button's text should be "Saving", or the progressive tense of whatever verb the button had. (Create -> Creating, Add -> Adding)

**Comment by haoyuchen1992** [comment]
I will make a PR for this issue.
