### ISSUE TITLE
Improve Error message when attempting to create an S3 bucket that already exists

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#4033]
Reported as an enhancement on the 0.45 Trello board

## Steps to Reproduce:
1. Configure S3 in your user settings
2. Go to a project that you have admin access to
3. On the project settings page, select S3 and click to import from profile
4. Click to create a bucket
5. Enter a name for the bucket and a location
6. Should see that it was successfully created and saved on the settings page
7. Now click create bucket again and repeat steps 5 and 6; entering the same name and location

## Expected
A clear error message informing me that the bucket name already exists. 

## Actual
Receive a modal with message 'Your previous request to create the named bucket succeeded and you already own it.' with button choices of CANCEL or TRY AGAIN
![screenshot 2015-08-12 15 43 45](https://cloud.githubusercontent.com/assets/9381062/9234830/3d63e016-4109-11e5-9f38-e68fb8329cb2.png)
Since the heading of the card is one that we can easily pass, perhaps a better heading than the current 'Problem creating bucket '*bucket name*' would be 'The bucket '*bucket name*' already exists'?
And if possible to pass a more informative error message to users for the modal body.

## Comments
@HarryRybacki commented on the trello card (https://trello.com/c/2SGUqUCy/41-unusual-error-message-when-creating-an-bucket-that-already-exists)
" this title is something we create on our end when we receive a S3CreateError as a response from S3. The long message is attached to the response S3 sends."

**Comment by GaryKriebel** [comment]
This will depend on changes to error handling in WaterButler.

**Comment by GaryKriebel** [comment]
Closed
