### ISSUE TITLE
[Staging and Production] [Firefox] View Only link name without spaces does not wrap text

### ISSUE THREAD

**Issue by WillBanner** [CenterForOpenScience/osf.io#4035]
# Steps
1. Go to osf.io and log in.
2. Go to a project on which you are an admin.
3. Go to the sharing tab.
4. Click to create a view only link.
5. Name the link something long without any spaces like: "ThisisareallylongviewonlylinknamethatdoesnothaveanyspaceswhichcanbeaproblemasyouwillseeassoonasIfinishtypingthiswholethingout"

# Expected
When I create the link, after a certain number of characters, the text will wrap, like what is done in Chrome and Safari.

# Actual
The text does not wrap which results in the section for the view only link name becoming extremely long and the entire page becoming wider.

![image](https://cloud.githubusercontent.com/assets/12799635/9235347/428164e4-410c-11e5-8bdc-fa16e72731f7.png)

**Comment by nanchen47** [comment]
When developing view-only link field, this situation has been taken into consideration. The name field of view-only link is more like a description which admins are used to distinguish the purpose of one view-only link from another. Although we can't trust user, but it won't make sense in real like for a single English word to be that long. Thoughts? @lbanner @GaryKriebel

**Comment by lbanner** [comment]
@WillBanner  --  will it wrap, or how does it look, given @nanchen47's case above ^^, for a lot of text in the field i.e. a sentence structure but not a single long string?

**Comment by WillBanner** [comment]
@lbanner @nanchen47 An actual sentence will wrap, however the reason I'm bringing this up, as it is a very minor issue, is because, in both safari and chrome, if a stream of text without spaces is put in for the name, the text will wrap, but this is not the case in Firefox or, as I recently discovered, IE.
