### ISSUE TITLE
S3 icon cut off on Project Overview page and on Files tab

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#4039]
This was reported on the 0.45 trello board by @WillBanner

## Steps

1. Log in to osf.io.
2. Navigate to a project for which you have admin access.
3. Head to your project settings and select and configure your Amazon S3 add-on. Connect it to a bucket.
4. Now, return to the Project Overview page and look at the S3 icon there.
5. Click to navigate to the Files tab and look at the S3 icon there, too.

## Expected behavior

I expect that the entire S3 icon will be visible.

## Actual behavior

The icon is cut off in both places.

## Notes

Looks like we chose to shrink this icon in: https://github.com/CenterForOpenScience/osf.io/pull/2961
However, it looks like a mistake on our part that we didn't shrink to fit the entire icon in (reference Caner's notes in the comments below from the trello board).

## Screenshots

**Project Overview page**

![project_overview_page](https://cloud.githubusercontent.com/assets/7093086/9251462/5c3f67e2-41a1-11e5-90ab-321d6a4ee365.png)

**Files tab**

![files_tab](https://cloud.githubusercontent.com/assets/7093086/9251458/583d3eda-41a1-11e5-8d34-189bef47c81e.png)

**How it should look (as on Project settings)**

![project_settings](https://cloud.githubusercontent.com/assets/7093086/9251555/d22f8108-41a1-11e5-8d1d-d9078ef61c6a.png)

**Comment by NatashaRichter** [comment]
**Comment from trello board**

@caneruguz wrote: This is an error on production, we have standard sizes for icons but in this case this icon is not properly sized. There is a CSS solution to this with background-size:contain but that would effect every icon on that list.

We can either create a github issue since it's on production or if we have time I can come back to this when I'm finished with my current work and do a fix.

**Comment by caneruguz** [comment]
@lbanner I'll do this, it should be a quick fix
