### ISSUE TITLE
[API] /nodes/ endpoint returns 500 when a node has system tags

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#4044]
### Steps

1. Add a system tag to a node (can be any string). This can be done "manually" in the shell.
2. Visit `/v2/nodes/`

### Traceback

![attributeerror_at__v2_nodes_](https://cloud.githubusercontent.com/assets/2379650/9257947/acecd8f8-41c6-11e5-879b-a21b5c532ddb.png)

It looks like system tags being serialized incorrectly. They should be serialized as a list of strings.

**Comment by brianjgeiger** [comment]
Well, we'll have to fix that, then. I wonder if system tags are stored differently than user tags, or if we did the serialization differently for each. Whoever gets this, Test Driven would be the way to go about fixing it.

**Comment by brianjgeiger** [comment]
Currently leaning towards removing system tags from the API entirely. If I do that, I'll likely collapse the tags structure into a list. Then if we add the system tags back in, they'll be in their own level, rather than in the compound data structure that they are now.
