### ISSUE TITLE
View-Only Links name field allows unlimited input

### ISSUE THREAD

**Issue by alexschiller** [CenterForOpenScience/osf.io#4047]
<h3>Steps</h3>
1. Make an new view only link
2. Paste as much text as you want into the name field. 
![screen shot 2015-08-13 at 3 24 36 pm](https://cloud.githubusercontent.com/assets/1322421/9259649/9b10879c-41d0-11e5-886d-5ec47bd95641.png)

<h3>Expected</h3>
Limited input like on other Title fields (e.g., Project/Component titles).

**Comment by chennan47** [comment]
The question will be how many characters will be reasonable. @jlcohoon

**Comment by jinluyuan** [comment]
This is a duplicate of https://github.com/CenterForOpenScience/osf.io/issues/4034

**Comment by alexschiller** [comment]
I'll close, thanks, didn't see that one when I searched
