### ISSUE TITLE
[Staging and Production] [Chrome] Scroll Bar overlaps navigation strip

### ISSUE THREAD

**Issue by WillBanner** [CenterForOpenScience/osf.io#4052]
# Steps
1. Go to staging.osf.io and log in.
2. On the dashboard, add a bunch of collections/ projects. This is just so that you have the ability to scroll through the project browser.
3. Scroll all the way down to the bottom of the list of projects/collections on the project browser.
4. Scroll down on the page itself (not on the project browser) so that the navigation strip at the top is covering about half of the project browser (by this I mean the strip that says "dashboard, browse, help etc."- I don't know what else to call it)
5. Hover your mouse over the right side of the project browser and scroll up through the project browser.

# Expected
The scroll bar would disappear behind the navigation strip

# Actual
The Scroll bar overlaps the navigation strip. (below is an image of this happening on the files browser on the project overview page).

This also occurs:
- On the files tab for a project
- On the project overview page- files browser
- On the "change folders" for addons on user settings.
- Mendeley folder browser- project overview page

![image](https://cloud.githubusercontent.com/assets/12799635/9261390/99c31174-41db-11e5-8b74-e7b8e4a5470d.png)

**Comment by caneruguz** [comment]
@WillBanner I can't replicate this with the instructions given. Can you check again? If it is still a problem we may need more instructions for duplicating.

**Comment by WillBanner** [comment]
@caneruguz This is only replicable on chrome on macs, so that could be the issue? I can still replicate the problem. I've edited the steps so that they might make more sense? I hope that helps!

**Comment by erinmayhood** [comment]
Closing for now - can't replicate.
