### ISSUE TITLE
OSF Meetings page displaying escaped ampersands for project titles

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#4067]
### Steps
1. Go to osf.io
2. Go to the Meetings page (Browse > Meetings)
3. Go to a meeting that contains projects with ampersands in the title, such as [Inclusive Astronomy 2015 Posters & Talks](https://osf.io/view/IA2015/) or [SPSP 2014 Posters & Talks](https://osf.io/view/spsp2014/).

### Expected behavior
I expected that the ampersand in project titles on the OSF Meetings page would match the project titles found on projects' overview pages, like these:

![screen shot 2015-08-14 at 3 17 21 pm](https://cloud.githubusercontent.com/assets/8591162/9282148/50eaf3c8-4298-11e5-9e0c-d2e320c56225.png)
![screen shot 2015-08-14 at 3 22 19 pm](https://cloud.githubusercontent.com/assets/8591162/9282149/50fa9508-4298-11e5-8c92-6c786c7a36f3.png)

### Actual behavior
The OSF Meetings page displays escaped ampersands (`&amp;`) in the project titles.

![screen shot 2015-08-14 at 3 17 13 pm](https://cloud.githubusercontent.com/assets/8591162/9282180/891d1258-4298-11e5-9d5d-cc19bb986131.png)
![screen shot 2015-08-14 at 3 20 19 pm](https://cloud.githubusercontent.com/assets/8591162/9282181/892b5e12-4298-11e5-813b-4699e6a09533.png)

**Note:** The OSF Meetings page displays the ampersand properly in its own titles, such as in the SPSP 2014 page:

![screen shot 2015-08-14 at 3 24 40 pm](https://cloud.githubusercontent.com/assets/8591162/9282193/a8f3cc66-4298-11e5-9355-55e0d10ad655.png)

**Comment by haoyuchen1992** [comment]
I just went to the example projects, such as Inclusive [Astronomy 2015 Posters & Talks](https://osf.io/view/IA2015/) or [SPSP 2014 Posters & Talks](https://osf.io/view/spsp2014/).  The special characters were rendered well. Can anyone check it again? @lbanner @GaryKriebel

**Comment by lbanner** [comment]
Looks resolved! Closing ...
