### ISSUE TITLE
OSF Meetings table's scrollbar causes contents to be misaligned with column labels

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#4068]
### Steps
1. Go to osf.io/meetings
2. Go to a meeting that has more than 17 submissions (the maximum height of the table)
3. In the meeting's table of contents, notice the alignment of the contents with the column labels

### Expected behavior
I expected the contents to align vertically with the column labels. This is the behavior when viewing a project with 17 or less submissions.

[APS 2015](https://osf.io/view/aps2015/)

![screen shot 2015-08-14 at 3 42 49 pm](https://cloud.githubusercontent.com/assets/8591162/9282606/8bccf6dc-429b-11e5-8abb-f86fef820af1.png)

### Actual behavior
The appearance of the scrollbar condenses the contents to the left.

[SPSP 2015](https://osf.io/view/spsp2015/)

![screen shot 2015-08-14 at 3 41 34 pm](https://cloud.githubusercontent.com/assets/8591162/9282519/fba5255c-429a-11e5-9a0a-e389bcb0e7fa.png)

**Comment by GaryKriebel** [comment]
This page may be updated shortly.  Good to keep in mind when that work is merged.
