### ISSUE TITLE
Long external link causes project overview page to freeze

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#4072]
## Steps

1. Log in to osf.io.
2. Enable "External Link."
3. Enter a long link (I entered a link from a search query on the UVA Virgo site).
4. Head to your project overview page after configuring the link.
5. Notice the alert that appears on screen (which is locked, since you must attend to it and cannot click out of it to dismiss it).
6. Try to zoom out (Command and "-").

## Expected behavior

I expect that I will be able to see the entire alert and choose whether or not I am redirected to the external link. 

## Actual behavior

I am zoomed in a little too much, but while the page is loading, I cannot make the screen resolution smaller (it hangs for about five seconds). As a result, the buttons are hidden off-screen and I **cannot** scroll within the alert to see them (scrolling simply moves me up or down the project page without scrolling in the alert itself). The result is that I am redirected to the external link (see second screenshot) every time I enter the project if I cannot manage to reduce zoom quickly enough. 

I've tried this multiple times with shorter links, and the page often hangs or freezes long enough for the amount of time to pass (around 10 seconds for those) and the forward to the external link to occur despite me not wanting to head there. 

## Screenshots

![long_link](https://cloud.githubusercontent.com/assets/7093086/9276255/b7ed1ea2-4270-11e5-8b6b-3a846a84e754.png)

![virgo_catalog_search](https://cloud.githubusercontent.com/assets/7093086/9276248/b217272a-4270-11e5-9050-1795cc58e55f.png)

## Note 

This is a real edge case, as no one will likely have a URL this long, but we could still improve functionality for these cases. I'm not sure what is responsible for the hanging on the project overview page.

**Comment by lbanner** [comment]
Replicated a few times @NatashaRichter ? ... the freezing aspect?
