### ISSUE TITLE
API Validator not complaining if you try to update a read-only field

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#4086]
Steps
-------
1. Enable all asserts for tests/api_tests/nodes/test_views/test_writing_to_public_field
2. Run the test

Expected
------------
Tests would pass

Actual
--------
The assertion that you would get a 403 when trying to update the public field, which is currently read-only, passes with a 200.

**Comment by billyhunt** [comment]
It seems this is a "feature" of Django Rest Framework.  https://github.com/CenterForOpenScience/osf.io/issues/4086

I looked over the JSON API Spec and found no mention of a process for PATCH and PUT with read only fields.

**Comment by brianjgeiger** [comment]
Okay, then could you submit a PR to take out the commented-out assert.

**Comment by billyhunt** [comment]
Oh yeah!  :100: :turtle:

**Comment by sloria** [comment]
As @billyhunt said, the lack or errors is by design; here is the relevant thread: https://github.com/tomchristie/django-rest-framework/issues/1655#issuecomment-47097476
