### ISSUE TITLE
search bar occludes dropdown items

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#4088]
## Steps
1. Visit the OSF
2. Open the search bar and type something
3. Click on a dropdown menu from the top navigation bar

## Outcome
1. The search bar has a higher z-index than the dropdown, blocking the dropdown from view
![screen shot 2015-08-18 at 11 42 40 am](https://cloud.githubusercontent.com/assets/4965832/9334866/f9350d9e-459e-11e5-89bf-d105eb4f3def.png)

## Expected outcome
1. Dropdown items should be visible over the search bar

Tested in Chrome and Safari. Both have the problem.

**Comment by caneruguz** [comment]
@jlcohoon should it not ideally close the search bar?

**Comment by GaryKriebel** [comment]
That is what I was thinking.

**Comment by jlcohoon** [comment]
Yep, that makes more sense.

**Comment by haoyuchen1992** [comment]
So for this one, the ideal solution is to hidden the search bar when the dropdown menu downs, right?  If Yes, I can work on it. Thanks!

**Comment by haoyuchen1992** [comment]
Update: But for the search page, the search bar can't be hidden. 
![screenshot 2015-08-25 15 09 15](https://cloud.githubusercontent.com/assets/5420789/9476574/5a70fdba-4b3b-11e5-9e46-46adcace583c.png)

**Comment by caileyfitz** [comment]
Since @haoyuchen1992's PR was merged, should this be fixed? @sloria @lbanner Because I am still seeing things as obscured by the search bar... 

![screen shot 2015-08-27 at 11 03 15 am](https://cloud.githubusercontent.com/assets/5975444/9528531/eb5f90ba-4cc2-11e5-91b1-68577eba8ad5.png)

**Comment by lbanner** [comment]
Thoughts on this @haoyuchen1992 ?

**Comment by haoyuchen1992** [comment]
@lbanner I have tried to replicated the error on Firefox, Safari, and Chrome. But I couldn't replicate it. on both staging and production. Can you try it again?  Thanks!

**Comment by lbanner** [comment]
@caileyfitz ? ^^

**Comment by caileyfitz** [comment]
@lbanner @haoyuchen1992 All looks well now. Was having an issue but now I'm not, even on Firefox.

**Comment by lbanner** [comment]
OK!
