### ISSUE TITLE
OSF spinner - smaller screen size distorts spinner image

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#4089]
## Steps

1. Log in to osf.io on Chrome (or Safari) and reduce screen size to 938*815 (inner screen), or so that your outer screen takes up a little over half your screen.
2. Zoom out two or three times.
3. Navigate to one of your projects that has files and citations in the Mendeley and Zotero widgets.
4. Notice the spinners as they load.
5. Click on the "Add Links" button in the Components widget.
6. Search all projects for a letter, like "a."
7. Notice the spinner.
8. Head to your User Settings and to "Notifications."
9. Notice the spinner as content loads.

## Expected behavior

I expect all spinners to display normally.

## Actual behavior

In the Add Links modal and under Contributor Notification Preferences in User Settings, one of the black circles of the spinner is distorted in Chrome (two for Safari).

On the project overview page, the spinners in the files widget, as well as the Mendeley and Zotero widgets, are distorted. 

The spinner in the Recent Activity widget displays fine, as does the spinner in the file tree on the file detail page and the spinner on the files tab.

## Screenshots

**Chrome: Project overview page**

![spinner_distorted](https://cloud.githubusercontent.com/assets/7093086/9333945/34ee8c0c-459a-11e5-9f1c-19460b893fb6.png)

**Chrome: Close-up of spinner in files, Mendeley, and Zotero widgets**

<img width="114" alt="screenshot 2015-08-18 10 59 55" src="https://cloud.githubusercontent.com/assets/7093086/9334879/15f4fe30-459f-11e5-83f1-db9045c629fe.png">

**Chrome: Add links modal spinner and Contributor Notification Preferences spinner**

![add_links_modal_spinner](https://cloud.githubusercontent.com/assets/7093086/9333960/40e6978e-459a-11e5-9da4-e691f4ae359d.png)

**Safari Project overview page**

![safari_project_overview](https://cloud.githubusercontent.com/assets/7093086/9334737/378a5758-459e-11e5-8ea8-3ae2630baffa.png)

**Safari: Add links modal spinner and Contributor Notification Preferences spinner**

![safari_add_links_modal](https://cloud.githubusercontent.com/assets/7093086/9334667/df44b444-459d-11e5-8841-119579a744b0.png)

**Comment by haoyuchen1992** [comment]
This may be resolved by Caner's PR -- https://github.com/CenterForOpenScience/osf.io/pull/4083

**Comment by lbanner** [comment]
I'll tag 'pending review' until #4083 is merged and tested -
