### ISSUE TITLE
osf for meetings breaks lines at awkward place in default window size

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#4090]
## Steps
1. Open the OSF for Meetings page in your laptop: https://osf.io/meetings/
2. Look at the number of submissions for each conference

## Outcome
1. "Submission(s)" is cut so that the final s is on a new line:
![screen shot 2015-08-18 at 11 42 58 am](https://cloud.githubusercontent.com/assets/4965832/9334986/aa3e35b6-459f-11e5-8826-148cb98ce827.png)

2. The line breaks that way at any window size smaller than 1600px wide

## Expected Outcome
1. The line should not break mid-word, especially not at a standard window size

**Comment by jinluyuan** [comment]
This happens in Safari, Chrome, and IE. 

It is not an issue in Firefox.
![screen shot 2015-08-18 at 1 24 29 pm](https://cloud.githubusercontent.com/assets/8591162/9337288/7a0e5350-45ac-11e5-9fb3-c3fba05402c5.png)

**Comment by GaryKriebel** [comment]
This page is currently being reworked and may be fixed with the updates.
