### ISSUE TITLE
APIv2 Serializers should support validation on compound fields

### ISSUE THREAD

**Issue by abought** [CenterForOpenScience/osf.io#4101]
## Summary
Currently, some APIv2 serializers convert compound fields to simple lists and dictionaries. This makes it difficult to document what the fields in the dictionary should be, and impossible to control input validation or sanitization per-entry (eg for URLs).

This will become more problematic once we introduce the ability to *edit* these fields (eg user data).

A PR exists demonstrating some appropriate validators for, eg, social fields in v1 API: #3754 .

## Example
Below is the field `social_accounts` in `UserSerializer`. Note that there are many nested fields, each of which has different validation rules:
```
        "social_accounts": {
            "github": "",
            "scholar": "",
            "personal": "http://localhost:5000/urldeformedbysanitizer/?param=val&amp;otherparam=otherval",
            "twitter": "anAccount",
            "linkedIn": "",
            "impactStory": "",
            "orcid": "",
            "researcherId": ""
        },
```
## Serializers affected
As of this writing, serializers affected include:
- `UserSerializer`
  - employment_institutions
  - educational_institutions
  - social_accounts
- `NodeSerializer`
  - metadata (unsure if this field is used or where it comes from)

**Comment by brianjgeiger** [comment]
API v2 Serializers do support custom field-level validators, and there's no reason they couldn't handle compound fields. http://www.django-rest-framework.org/api-guide/serializers/#validation "You can specify custom field-level validation by adding `.validate_<field_name>` methods to your `Serializer` subclass."

Is that sufficient for this issue, @abought? I know that, as we add editing capability, we'll want to consider adding validation.

**Comment by abought** [comment]
Unfortunately, it's not enough that DRF *can* do this- the issue is whether we take advantage of those capabilities. Minimum requirements for resolution include:

1. API behavior is self-documenting, *in our implementation*. The user should never have to submit a "black box" dictionary (such as social fields) whose structure and keys are undocumented. **All** input fields that the API acts on should be explicitly identified. 
    - The recent addition of [explicit social fields](https://github.com/CenterForOpenScience/osf.io/blob/develop/api/users/serializers.py#L23) is good progress in that direction. But there are still other serializers with nested fields.

2. Any field that expects specialized text input should include explicit validation. (social fields, URLs, etc) This isn't possible without requirement (1) being met.

**Comment by brianjgeiger** [comment]
I don't necessarily agree. For item 1, we need to make sure the documentation is correct and useful. We don't necessarily need to ensure that it self-documents correctly. Trying to do the latter may be more work than is worthwhile, and it may cause extra tension with things like ensuring that reserved fields don't automatically become documented.

Item 2 is not necessarily the job of the API. The model could reject the field. Or the UI. Unless we are passing the validation criteria from one part of the system to the rest (which we aren't in the V2 API), then that's upwards of three places that validation will have to happen. 

Also, as of I believe *right this very moment* in develop, we do not have any compound fields in any of the serializers. If that's not entirely correct, then it will be in a PR or two. So at that point, this issue would not be valid. I can't say that won't be true forever though. But if DRF can do it, and we aren't using compound fields, then it's going to be hard to close this issue.
