### ISSUE TITLE
MFR only displays first sheet of spreadsheets

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#4102]
## Steps
1. Go to this project [file](https://osf.io/4vjxa/) (or upload your own spreadsheet with multiple sheets)
2. Notice that the MFR only displays the first sheet
3. Download the file and open it
4. Notice that all of data is on the second sheet

## Expected behavior
I expected that the MFR would display all of the file. This is important for cases when the data is on the second page, like in the example.

## Actual behavior
I have to download the file in order to see it. The MFR's display first caused me to think that the file itself was broken, but then I downloaded it and saw that all the data was on the second page.

**MFR**

![screen shot 2015-08-19 at 10 03 08 am](https://cloud.githubusercontent.com/assets/8591162/9358420/e9de7b44-4659-11e5-845f-3ac73abf81d0.png)

**Download and view file's second sheet**

![screen shot 2015-08-19 at 10 03 17 am](https://cloud.githubusercontent.com/assets/8591162/9358419/e9d99bb0-4659-11e5-92e4-f21683112434.png)

Let me know if this should be posted in the MFR repo instead!

**Comment by GaryKriebel** [comment]
@icereval, do you know if MFR was designed to handle multiple sheets of a spreadsheet?

**Comment by jinluyuan** [comment]
@GaryKriebel @icereval If handling multiple sheets is too difficult, then it would be nice to have an alert above the MFR that says "Download file to view all sheets". The current setup makes the user (or maybe just me) think there's something wrong with the file.

**Comment by mfraezz** [comment]
@GaryKriebel It was not designed with this in mind. I'll work on this enhancement

**Comment by erinmayhood** [comment]
#187 will address the issue. Closing.

**Comment by jinluyuan** [comment]
The PR fix is in the MFR repo: https://github.com/CenterForOpenScience/modular-file-renderer/pull/187
