### ISSUE TITLE
change "statistics" button to read "analytics"

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#4105]
from the community repo: https://github.com/CenterForOpenScience/community/issues/317

Users frequently ask if the "Statistics" page is where they put their results/code. This could be clarified by using a more common word for the information stored on the page—"Analytics." Because we do not want to change the URLS, we should just change what the button reads. This would mean URLS should still read osf.io/GUID/statistics, but the tab changes:

![screen shot 2015-08-19 at 10 37 46 am](https://cloud.githubusercontent.com/assets/4965832/9359346/aa8165c4-465e-11e5-989c-8e5530789641.png)

**Comment by GaryKriebel** [comment]
@JeffSpies, based on https://github.com/CenterForOpenScience/community/issues/317#issuecomment-128041857, would you rather just change the tab name or change the url as well (with /statistics redirecting)?

**Comment by jinluyuan** [comment]
I think if we rename it to Analytics, the link in the menu should be moved to be last, behind Forks but before Settings, since it is not a part of the actual project's work, and it could be confused with the "analysis" part of the research process. The statistics/analytics link is currently in the middle, which is also where analysis would be in a research project.

**Comment by chennan47** [comment]
@GaryKriebel If this is what we want, we will need to change both the tab name and make the url change. Moreover, we need to keep the original url and make it redirect to the new url.

**Comment by GaryKriebel** [comment]
@chennan47 ... yes .... exactly ... just asking Jeff if we should simply change the tab name or go all the way with the tab/url/redirect (1 change vs. 3)

**Comment by JeffSpies** [comment]
Let's hold on this; @erinmayhood should keep this in mind as she looks at
project dashboard navigation.

**Comment by erinmayhood** [comment]
@sloria Please go ahead and change the name of the tab ASAP. 

For the next iteration: 
The new URL should be /analytics.
We will need a redirect.

Further changes (placement, etc) will wait for an update of navigation.

**Comment by sloria** [comment]
The tab name has been changed.
