### ISSUE TITLE
Indicate who saved each version of a wiki 

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#4106]
from the Community repo: https://github.com/CenterForOpenScience/community/issues/318

## Steps

1. Visit a wiki page with multiple versions
2. Open the dropdown on the view or compare panels

## Outcome

1. Versions are listed
2. No indication of who saved each version is given

![screen shot 2015-08-19 at 10 44 08 am](https://cloud.githubusercontent.com/assets/4965832/9359463/40ceb446-465f-11e5-9f9b-254f90c84978.png)

## Suggested behavior

1. It would be helpful, especially with publicly editable wikis, to indicate who saved a particular version of a wiki. Ideally, this information would be given to the user without them having to visit a particular version.

This could potentially be addressed at the same time as #2362.

**Comment by GaryKriebel** [comment]
@erinmayhood - input on the UI?
