### ISSUE TITLE
[Small screen] Incorrect title header for Sharing page

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#4109]
## Steps
1. Sign into osf.io
2. Go to one of your projects
3. Visit each page and notice that there are no header titles
4. Make your window smaller
5. Visit each page and notice that there ARE header titles for every page except Wiki

## Expected behavior
In a small window, I expected that the header of the Sharing page would be "Sharing" since all the other pages have headers that match the name of the page (except the afore-mentioned Wiki page).

## Actual behavior
The Sharing page's header is "Contributors". This is not only incorrect, but misleading, since the page also has View-only links. It should be changed to "Sharing".

![screen shot 2015-08-19 at 12 31 57 pm](https://cloud.githubusercontent.com/assets/8591162/9362493/ab38e5f4-466e-11e5-9538-faed3e56540a.png)

**Comment by caneruguz** [comment]
@sloria does the route need to change as well? 

![screen shot 2015-08-20 at 9 25 43 am](https://cloud.githubusercontent.com/assets/1314003/9384278/7477191e-471d-11e5-9281-030a33121d90.png)

**Comment by sloria** [comment]
Let's not change the route for now; it's possible that the name of that page may be changed in the near future.
 
For now, it's fine to just change the header to be consistent.

**Comment by caneruguz** [comment]
Okay I'm sending a quick hotfix for three issues that are very minor.
