### ISSUE TITLE
[Small screen] Landing page's sign in fields are not responsive to window size

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#4122]
## Steps
1. Go to osf.io as a logged out user
2. Make your window small enough, so the page goes into small screen mode
3. Click the Sign In button

## Expected behavior
I expected that the sign in fields and Log In button would be responsive to the size of the window, which was the case pre-0.45 release (or around that time).

![bb2db912-255d-11e5-9a03-a2d51414ea30](https://cloud.githubusercontent.com/assets/8591162/9368007/f2a26b0c-468e-11e5-827b-8db787e2f4b7.png)

(Shown here with a bug in the username field - in Firefox - now fixed)

## Actual behavior
The sign in fields are the same size no matter how I change the window size.

![screen shot 2015-08-19 at 12 36 26 pm](https://cloud.githubusercontent.com/assets/8591162/9368006/f29ca80c-468e-11e5-893b-88705e5d5111.png)

@caneruguz

**Comment by caneruguz** [comment]
The PR for this issue was merged: https://github.com/CenterForOpenScience/osf.io/pull/4115
