### ISSUE TITLE
Icons not centered for information and x buttons

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#4137]
In the project organizer, both the information and the x button (visible after clicking to rename a collection or project) have uncentered icon text: 

![screen shot 2015-08-21 at 7 45 11 am](https://cloud.githubusercontent.com/assets/5975444/9407582/940aa12c-47d8-11e5-9e13-0d182e6f6007.png)

![info icon not centered](https://cloud.githubusercontent.com/assets/5975444/9407572/7def6102-47d8-11e5-879b-ac22af0249e2.png)

For both, there is more padding to the right of the icon text than to the left.

**Comment by haoyuchen1992** [comment]
Pending review tag could be added here.
