### ISSUE TITLE
Button should say "Add" instead of "Save" when adding contributor to a project with no children

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#4138]
# Steps
1. Go to a project for which there are no children components
2. Go to the Sharing tab
3. Click to add a contributor
4. Search for a user and press the plus sign to add them to the project
5. Read the button text at the bottom of the modal

# Expected
I expect that there would be two buttons: a gray button with the text "Cancel" and a green button with the text "Add"

# Actual
The gray Cancel button is present, but the green button has text that reads "Save" rather than "Add." When adding contributors to a node with children, the final modal has a green "Add" button, thus button text for nodes with no children should be changed to be consistent with this.

![add components has save label for projects with no children](https://cloud.githubusercontent.com/assets/5975444/9407634/34277a54-47d9-11e5-8b30-08c98f04deb3.png)

**Comment by haoyuchen1992** [comment]
Pending review tag could be added here.
