### ISSUE TITLE
Wiki rename flashes modal that wiki has moved

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#4167]
## Steps
1. Go to a project you are an admin on
2. Go to the the wiki tab
3. Create a new wiki
4. On the new wiki, click on the name of the wiki in the upper left above the wiki menu
5. Edit or rename the wiki
6. Click to save the edit
7. Look at the screen

## Expected
I would expect the rename to be saved, nothing flashing on the screen

## Actual
After saving the edits to the wiki name, there is a brief flash of a modal that says the wiki has been moved.
![wiki](https://cloud.githubusercontent.com/assets/9381062/9472297/74b5d330-4b22-11e5-80ed-adf5f1b8b164.gif)

**Comment by chennan47** [comment]
I think this is a desired behavior. If the user's internet is slow or under some lag spike, the pop up modal gives user a sense for what's going on. It also block the page to prevent user doing other action when server is handling user's rename wiki request. @erinmayhood any thought?

**Comment by GaryKriebel** [comment]
Closed via https://openscience.atlassian.net/browse/OSF-4225
