### ISSUE TITLE
[production] Email address for login is case sensitive

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#4183]
Steps
-------
1. Login to the OSF using your email/password as you normally enter it
2. Log out of the OSF.
3. Login again, but this time type your email address in all caps, or with some capitalization scheme you did not use in step 1. 

Expected
------------
User would be able to login regardless of capitalization

Actual
--------
User receives error message, The email or password you entered is incorrect.
![screen shot 2015-08-26 at 12 42 33 pm](https://cloud.githubusercontent.com/assets/7749914/9499872/0a3e4f5e-4bf0-11e5-9265-f6f19b261ac0.png)

**Comment by GaryKriebel** [comment]
@icereval ... is the fault in CAS or OSF?

**Comment by icereval** [comment]
Fixed in https://github.com/CenterForOpenScience/cas-overlay/commit/50153bf6057459ea413bf64891e3f7d8421afb9e
