### ISSUE TITLE
Profile page scrollspy "jumps" at the top of the page

### ISSUE THREAD

**Issue by chrisseto** [CenterForOpenScience/osf.io#4193]
# Steps
* Go the the profile
* Scroll to the bottom of the page
* Slowly scroll to the top
* Notice the jump
* Lie down
* Try not to cry
* Cry a lot

![glitch](https://cloud.githubusercontent.com/assets/5532905/9505752/2e6a7926-4c12-11e5-9f76-c78c7db24c1c.gif)

**Comment by GaryKriebel** [comment]
JIRA ISSUE -> https://openscience.atlassian.net/browse/OSF-4536

**Comment by GaryKriebel** [comment]
Closed
