### ISSUE TITLE
Nodes' recent activity has no loading indicator

### ISSUE THREAD

**Issue by chrisseto** [CenterForOpenScience/osf.io#4201]
# Step
* Go to someone's profile
* Click the chevron on one of their popular nodes
* Wait
* Notice that text randomly pops in after some amount of time
* Lie down
* Try not to cry
* Cry a lot

![noloader](https://cloud.githubusercontent.com/assets/5532905/9546091/c7d80c44-4d5d-11e5-809c-f221820502b4.gif)

**Comment by GaryKriebel** [comment]
JIRA ISSUE -> https://openscience.atlassian.net/browse/OSF-4536

**Comment by GaryKriebel** [comment]
Closed via https://github.com/CenterForOpenScience/osf.io/pull/5523
