### ISSUE TITLE
Unmatched parens break search

### ISSUE THREAD

**Issue by chrisseto** [CenterForOpenScience/osf.io#4202]
# Steps
* Go to search
* Search for something
* Throw an unmatched `)` somewhere in the query
* Lie down
* Try not to cry
* Cry a lot

![brokensearch](https://cloud.githubusercontent.com/assets/5532905/9546648/81cb5e7c-4d62-11e5-9ace-1eb5d9b2fa54.gif)

**Comment by GaryKriebel** [comment]
JIRA ISSUE -> https://openscience.atlassian.net/browse/OSF-4536

**Comment by TomBaxter** [comment]
There may be a way to get a better error message out of this but the issue itself is the result of using the Lucene search syntax. There are several special characters that need to be escaped if they are to be interpreted literally.

+ - && || ! ( ) { } [ ] ^ " ~ * ? : \

They can be escaped with a proceeding \ as documented at URL below

http://extensions.xwiki.org/xwiki/bin/view/Extension/Search+Application+Query+Syntax#HEscapingSpecialCharacters

**Comment by GaryKriebel** [comment]
fixed in release 0.67
