### ISSUE TITLE
Change "Sharing" to "Contributors"

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#4204]
It is not intuitive that the "Sharing" tab is where you manage contributors. 

![osf___realigned_stable_initiative_contributors](https://cloud.githubusercontent.com/assets/2379650/9547863/2073e0b4-4d6b-11e5-8233-53481776554c.png)

It is worth noting that the URL also says "contributors".

The tab text should be changed to "Contributors.

Pinging @erinmayhood for feedback.

**Comment by sloria** [comment]
I believe the rationale behind "Sharing" was to be inclusive of the "View-only links" on the page. 

The term "sharing", however, is too misleading.

I think it's OK to have "View-only links" on a page titled "Contributors". One possible alternative might be "Collaborators", but I think that's less than ideal.

**Comment by erinmayhood** [comment]
@sloria 100% yes on changing the tab from Sharing to Contributors.

I will consider View-only links when looking at refactors but I think making the change as you suggest immediately is good.
