### ISSUE TITLE
Add third option between private and public: Available by request

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#425]
When project admin sets to "available by request" the project/component title, contributors, and description are visible - but not the wiki, files, logs or add-ons.  [maybe revise on wiki - with warning to admin?]

An OSF user can click the "request access" button (alternative toggle on the public/private if this is enabled).  When they do so, a modal pops up with a dialogue box auto-filled with "Hello - I would like to access [project/component title]."  With a note saying that they can add or edit text.  

When they submit, an email is sent to all admins of that project/component regarding the access request.  

Granting access options:

1. as a contributor with read, read/write, or admin privileges

2. as a viewer - read-only access and not a contributor

3. via private link (Nan developed functionality) that may or may not expire

**Comment by jlcohoon** [comment]
We're working on a proposal to address this.

**Comment by GaryKriebel** [comment]
Closed
