### ISSUE TITLE
OSF4M Accepting Submissions doesn't sort

### ISSUE THREAD

**Issue by AndrewSallans** [CenterForOpenScience/osf.io#4298]
On this page:  https://osf.io/meetings/

The right column should sort based on the up and down arrows, but doesn't.  I've tried in Chrome and Safari, and the Submissions column will sort as suggested, but the Accepting Submissions column will not.  Please fix.

![screen shot 2015-09-15 at 2 19 44 pm](https://cloud.githubusercontent.com/assets/2151933/9885774/f275ec04-5bb4-11e5-9e80-4cb5aed80814.png)

**Comment by AndrewSallans** [comment]
Related to this issue?  https://github.com/CenterForOpenScience/osf.io/pull/4252

**Comment by GaryKriebel** [comment]
JIRA ISSUE -> https://openscience.atlassian.net/browse/OSF-4539

**Comment by TomBaxter** [comment]
As the OP AndrewSallans suggested this seems to be related to issue #4252 . A fix for which was merged two weeks ago. I tested just now and was able to sort on "Accepting Submissions." I think this issue can be closed.
