### ISSUE TITLE
Merging projects

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#435]
First pass at a process.

Checks:
(1) Contributor lists for parent project must be the same
(2) User initiating the merge must have administrator privileges on both projects

Process:
(1) User selects "Merge project with another project"

(2) Search for second project

(3) check contributor lists and admin privleges

(4) warning message: Merging two projects will create a single project, any components that are not part of the merge will be deleted

(5) On confirmation: a three column screen appears with one project on left and another on right.  The middle is "merged project".  Rows are the various elements of the project.  User selects which to include from each project.

(a) Title: select one
(b) Project description: select one
(c) Contributors: already defined as same as both parent projects - note that permissions will be set to "greatest access" - e.g., if someone is admin on one and read-only on other, they will be admin on merged project
(d) Components: select as many from each that should be included in the merged project - if name conflcts, then can auto-rename for now and person edits after merge
(e) Add-ons: select as many from each that should be included
(f) Registrations: all get included
(g) Counts of forks, links, etc all get combined
(h) Project wiki: if both selected, then have to label one as "primary" and its home page becomes the new project wiki homepage - the other gets renamed home page and name conflict resolutions
(i) Project files: select all that should be included
(j) Logs: all get merged
(k) Tags: select one 
(l) Links: select which get included (avoid redundancy and no links to the other project being merged)

(6) On completion: First a warning of what components and other project elements will be deleted upon merge.  Ask for confirmation, or return to editing.

(7) On confirmation: Final warning that this cannot be undone.  On confirmation, merge.

**Comment by nanchen47** [comment]
Will be considered when we refactor the project modal.
