### ISSUE TITLE
[feature request] Comment organization like GitHub issues tracking

### ISSUE THREAD

**Issue by tsalo** [CenterForOpenScience/osf.io#4474]
## Steps
1. If you need to discuss something related to a project on the OSF (potential changes to a planned analysis, authorship order, etc.), go to the project and make a comment.
2. Add relevant labels and mention contributors you want to be involved in the discussion.
3. When the discussion is over, it should be closeable and searchable.
## Expected

Discussions between contributors about a given project are openly available, with time and author information, labels, and the ability to close issues when discussions have been resolved. Also, there should be a way to @ mention other contributors and contributors should be able to respond to comments via email. Perhaps a separate page, with a link at the top alongside Wiki and Files?
## Actual

Comment author and time are both kept track of, which is great, but it doesn't look like comments can be searched, closed, or labeled.

**Comment by nicipfeiffer** [comment]
The ability to @mention in comments, comment on files and wikis, and to reply from an email is complete. At this time, there is no plan to incorporate comments into search.
