### ISSUE TITLE
While dropbox is fetching content, hgrid is non-responsive, but action clicks are stored and then applied inappropriately to the grid once dropbox finishes loading

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#468]
For example, I go to hgrid and click on a file that is in the OSF tree, but dropbox is fetching content from a big folder.  When it finallly loads, the click on the OSF file actually clicks on a file in the dropbox folder because it took over that location on the hgrid.

**Comment by caneruguz** [comment]
It doesn't look like this is an issue anymore. @sloria @jmcarp can comment to this as well. While lazyloading is happening the clicks are still responsive and the page load to what you clicked has started. 
Close?

**Comment by lbanner** [comment]
Currently is is deferred, but I am happy to close unless @sloria or @jmcarp say no. Thanks!

**Comment by nanchen47** [comment]
This is no longer a problem with the new loading screen.
