### ISSUE TITLE
Downloading Multiple Files 

### ISSUE THREAD

**Issue by cbischak** [CenterForOpenScience/osf.io#475]
Add the ability to download multiple files. 

As an OSF user, I want the ability to select multiple files and then download them. 

Requirements:

1. User can select multiple files at once
2. When user selects one or more files, the following actions are possible: Delete Multiple (already implemented), Download Multiple
3. When the user chooses Download Multiple, all selected files download

Currently file downloading is limited to one file at a time. It would be nice to be able to download multiple files at a time or even have a download all button.

**Comment by caneruguz** [comment]
@GaryKriebel this issue will be fixed with download as zip right?

**Comment by GaryKriebel** [comment]
I belive download as a zip will be for the entirety of OSF Storage, not a select number of the files.

**Comment by lbanner** [comment]
@GaryKriebel is correct - Download as Zip covers top level OSF folder, so let's keep this open for issue prioritization by Community and @jlcohoon

**Comment by jlcohoon** [comment]
OSF Storage and folders can now be downloaded as a zip, but you still can't select multiple files to be downloaded. Any chance this can be put on the list for next epic?

**Comment by lbanner** [comment]
I'd suggest you put it on the Epic planing Trello -- ping @erinmayhood . Thanks.
