### ISSUE TITLE
Unclear if there is a web API

### ISSUE THREAD

**Issue by suchow** [CenterForOpenScience/osf.io#4787]
I can't figure out if there is an API exposed to developers. Is it possible to programmatically create new projects and add assets to them?

**Comment by lbanner** [comment]
Hi @suchow -- The answer is yes -- We've got BAPI docs on Production here:
https://api.osf.io/v2/

Not 100% stable as yet i.e. as we continue to develop, we'll likely continue to make changes/alterations + additions. Let me know how I can help further. Thanks!

**Comment by suchow** [comment]
Thanks, I'm now able to use the web API to create a new project. Is it possible to create registrations? The source code seems to suggest that's not implemented yet.

**Comment by lbanner** [comment]
@suchow You are correct, currently we have no V2 for the creation of registrations. It is, however, on the near term development list.

**Comment by erinmayhood** [comment]
Closing for now. @suchow please let us know if you have more questions.
