### ISSUE TITLE
Private Links: Edits to modal text

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#482]
If the "label" column is removed, then remove the top part of the modal and edit

"Would you like to apply the link privilege to any children of the current component?"

to be

"Anyone with the private link can view, but not edit, the components associated with the link.  Which components would you like to associate with this link?"

![screen shot 2014-04-08 at 8 59 57 am](https://cloud.githubusercontent.com/assets/1761504/2643592/d4e1b77a-bf1d-11e3-96d2-31e4418496fc.png)

**Comment by nanchen47** [comment]
This is no longer a problem.
