### ISSUE TITLE
Adminstrators for projects are supposed to have at least read-only access to all child components in project

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#492]
Just adding issue as a reminder from prior discussion.  

![screen shot 2014-04-11 at 12 55 18 pm](https://cloud.githubusercontent.com/assets/1761504/2682391/552b5084-c19a-11e3-8c2b-96e8769bce76.png)

**Comment by samanehsan** [comment]
Closing, since admins now have view-only access to all components in a project.
