### ISSUE TITLE
OSF can create Github commits with no changes

### ISSUE THREAD

**Issue by remram44** [CenterForOpenScience/osf.io#4966]
Please do not create a commit if saving with no change. Empty commits are useless.

Example: https://github.com/ViDA-NYU/reproducibility-news/commit/8add858676e87e4b19b383103b1f1f439fd0920a

**Comment by whit537** [comment]
FTR, this has been ticketed internally (should be viewable with a Jira account):

https://openscience.atlassian.net/browse/OSF-6715

**Comment by remram44** [comment]
Apparently only an `..@cos.io` email will do...

**Comment by whit537** [comment]
D'oh! Okay, thanks for the feedback. :-/

**Comment by felliott** [comment]
Hey @remram44,

Sorry it's taken so long, but this issue has been fixed by the WaterButler v0.31.0 release this past Friday.  Thanks for the report!

Cheers,
@felliott
