### ISSUE TITLE
GitHub web hook setup fails when using local.py config

### ISSUE THREAD

**Issue by TomBaxter** [CenterForOpenScience/osf.io#4974]
While setting up GitHub on my development environment I ran into this error when selecting/saving repository during initial setup.

GitHubError: 422 Invalid request.
For 'properties/events', nil is not an array.

This is due to "events=None" in osf.io/website/addons/github/api.py  "def add_hook" Events must be an array/list. The following change fixed the issue.

    # def add_hook(self, user, repo, name, config, events=None, active=True):
    def add_hook(self, user, repo, name, config, events=['push'], active=True):

['push'] is the default for the github API. This could also be fixed by not passing "events" or "active" at all, letting them default to ['push'] and True.

Please let me know if you would like  PR for this.

Thanks, Tom

**Comment by felliott** [comment]
Hey @TomBaxter,

Looking at this, I think there are two issues.  First, we want to require the programmer who calls `add_hook` to specify which event they're creating a hook for.  We shouldn't be guessing for them.  So perhaps we should throw an error if `events is None`.  Secondly, did you note which bit of code was calling `add_hook` without providing an event list?  Wherever it is, it shouldn't be doing that.  The github addon was just refactored, so it's possible some code got changed or deleted on accident.  If you could track it down and provide a PR, that'd be awesome!  Thank you!

Cheers,
@felliott

**Comment by TomBaxter** [comment]
Will do. Traveling with my wife today and tomorrow, but will work it as
soon as I'm back.

Thanks, Tom

**Comment by felliott** [comment]
Hey @TomBaxter,

Sorry, I just saw on our internal issue tracker that this has been identified and assigned.  I'll let them know about this ticket so they can close it when it gets merged.

Cheers,
@felliott

**Comment by TomBaxter** [comment]
Nice! Thanks.

**Comment by mfraezz** [comment]
@felliott, the refactor hasn't gone in yet. There should only be one call that specifies the list of events; `add_hook` on the `GitHubNodeSettings` model. This doesn't accept `events` as a kwarg and passes in the event list (`['push']`) defined in `addons/github/settings`. I don't see anywhere else on `develop` or `master` calling the `github/api` method, which is called by the one on the model.

**Comment by mfraezz** [comment]
Confirmed with @TomBaxter, fixed when #4936 was merged into develop. This issue can be closed @sloria
