### ISSUE TITLE
Make tables that are rendered in MFR sort/searchable by default

### ISSUE THREAD

**Issue by JeffSpies** [CenterForOpenScience/osf.io#500]
When viewing a tabular like file, the MFR should render the table with the ability to sort and search.

**Comment by mfraezz** [comment]
SlickGrid, the UI component we’re using for tabular data, is sortable by default (ascending / descending based on column). Clicking the column header toggles sorting, so half of this is already done. Slickgrid hasn’t been maintained for two years, but apparently has support for “Grouping, filtering, custom aggregators, and more!”, which sounds a lot like searching. However, we’re not currently taking advantage of that. There’s another [open issue](https://github.com/CenterForOpenScience/osf.io/issues/4102) about multiple tables in a single file not being rendered (only the first in a series of sheets), I'll work on both of these.

**Comment by erinmayhood** [comment]
#187 will address the issue. Closing.

**Comment by jinluyuan** [comment]
The PR fix is in the MFR repo: https://github.com/CenterForOpenScience/modular-file-renderer/pull/187
