### ISSUE TITLE
Adding Mendeley to OSF project seems to be broken

### ISSUE THREAD

**Issue by srw6v** [CenterForOpenScience/osf.io#5150]
Tried to add Mendeley to my OSF project and got the error "Error occurred while importing Mendeley account."  Tried multiple times from multiple projects. @saradbowman

**Comment by saradbowman** [comment]
Thanks for the report @srw6v - looking at this now.

**Comment by GaryKriebel** [comment]
@saradbowman, still an issue?

**Comment by saradbowman** [comment]
@srw6v still an issue? I think it's related to https://openscience.atlassian.net/browse/OSF-5853?jql=text%20~%20%22token%20refresh%22 - manual refresh of auth token should resolve temporarily until permanent fix

**Comment by srw6v** [comment]
Looks fixed to me. Didn’t have to to an auth token refresh.
--
Stephen R. Williams, PhD
Assistant Professor
Department of Neurology
University of Virginia
Phone: (804)426-7446

From: saradbowman
Reply-To: "CenterForOpenScience/osf.io"
Date: Monday, July 18, 2016 at 10:44 AM
To: "CenterForOpenScience/osf.io"
Cc: "srw6v@virginia.edu<mailto:srw6v@virginia.edu>", Mention
Subject: Re: [CenterForOpenScience/osf.io] Adding Mendeley to OSF project seems to be broken (#5150)


@srw6v<https://github.com/srw6v> still an issue? I think it's related to https://openscience.atlassian.net/browse/OSF-5853?jql=text%20~%20%22token%20refresh%22<https://openscience.atlassian.net/browse/OSF-5853?jql=text%20%7E%20%22token%20refresh%22> - manual refresh of auth token should resolve temporarily until permanent fix
