### ISSUE TITLE
Project: Spam Filter

### ISSUE THREAD

**Issue by JeffSpies** [CenterForOpenScience/osf.io#530]
Projects/components will be run through a spam filter. If they get marked as spam, they cannot be made public until they are manually checked (for now). An extra email confirmation step may help with this if the project gets flagged as spam.

**Comment by GaryKriebel** [comment]
This is being addressed with the following PRs:
https://github.com/CenterForOpenScience/osf.io/pull/2652
https://github.com/CenterForOpenScience/osf.io/pull/2624

**Comment by nanchen47** [comment]
Will be fixed by the spam assassin. Close for now.
