### ISSUE TITLE
Draft registrations have unexpected "save" behavior

### ISSUE THREAD

**Issue by evomellor** [CenterForOpenScience/osf.io#5432]
There appears to be unexpected behavior for when draft registration content is saved and when warnings pop up. This behavior recently led to one user losing work, and I am having a hard time consistently replicating everything that may be confusing, but below is the most concrete issue I can document. I can't quite decide if this is a bug or is something that should be improved. @csoderberg brought issue to my attention. @samchrisinger may have insight on the cause or possible solution.

Expected behavior:
- Content is saved when users navigate away from page, or, if the user is about to navigate away with unsaved changes on page, a dialog box pops up with a warning (You have unsaved changes...). 
- Most recent saved content appears in fields if a user navigates back to the page.

Actual behavior:
- The dialog only appears one time. If the user "stays on page" and then later tries to navigate away, no warning is displayed.
- The old content is displayed when a user comes back to a page with browser "forward" navigation button. The proper, newer content does reappear when user refreshes page, or navigates to draft via the "Registrations" tab. But that content is lost if the user triggers a "save" event in the meantime.

http://g.recordit.co/BSIMlvbFha.gif

Possible fixes:
- Adding a "Previous Page" button on the bottom of the page (either to the left of the "Next Page" button or above the "Save as Draft" button) would discourage use of the browser back and forward buttons, which appears to be the source of the unexpected behavior.

**Comment by GaryKriebel** [comment]
@evomellor, is this still an issue?  Is it on JIRA if so?

**Comment by futa-ikeda** [comment]
Draft registration submission page has been rewritten so this should no longer be an issue
