### ISSUE TITLE
Gravatars not displaying

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#555]
![open_science_framework___contributors](https://cloud.githubusercontent.com/assets/2379650/3018748/7ea6041a-df89-11e3-9afc-c577ba81acea.png)

**Comment by ShKlinkenberg** [comment]
While we are on the gravatar subject. It looks like OSF is referring to gravatar.org instead of gravatar.com. This is when clicking the avatar icon in OSF.io

https://en.gravatar.org directs to a non private connection
