### ISSUE TITLE
OSF V2 API: Support for JSON-API 1.0 Compound Documents

### ISSUE THREAD

**Issue by emetsger** [CenterForOpenScience/osf.io#5590]
It seems that the OSF v2 API doesn't quite support the idea of [JSON-API compound documents](http://jsonapi.org/format/#document-compound-documents):

> To reduce the number of HTTP requests, servers MAY allow responses that include related resources along with the requested primary resources. Such responses are called compound documents.
> 
> In a compound document, all included resources MUST be represented as an array of resource objects in a top-level included member.
> 
> Compound documents require full linkage, meaning that every included resource MUST be identified by at least one resource identifier object in the same document. These resource identifier objects could either be primary data or represent resource linkage contained within primary or included resources.

The OSF v2 `embed` HTTP query parameter seems to support the spirit of compound documents, but not the letter.  For example, the `embeds` object seems to be an analog of the JSON-API 1.0 `included`object, but the `embeds` object occurs at the wrong level in the response document.  As a consequence, linking between included data and relationships doesn't occur as specified in JSON-API 1.0.

If the OSF v2 API were to support compound documents as specified by the JSON-API, existing clients like the [JSON-API Converter](https://github.com/jasminb/jsonapi-converter) would be able to consume the OSF v2 API.

**Comment by brianjgeiger** [comment]
We've wrapped this into an existing Jira issue for resolution after the JSON API team finalizes their extension spec.
