### ISSUE TITLE
In API v2 GET /registrations/{id}/files/ - files relationship points to nodes directory 

### ISSUE THREAD

**Issue by karenhanson** [CenterForOpenScience/osf.io#5609]
For example:
https://api.osf.io/v2/registrations/fjguy/files/
Shows the following value in relationships.files.links.related.href:
https://api.osf.io/v2/nodes/fjguy/files/osfstorage
which leads to a "Not Found" response.  Manually entering the following path displays the expected data:
https://api.osf.io/v2/registrations/fjguy/files/osfstorage

**Comment by brianjgeiger** [comment]
Well, *that* shouldn't happen. I've made an issue for it in Jira. We should get to it soon. Hopefully it should be an easy fix.
