### ISSUE TITLE
JSON-API spec-compliant pagination

### ISSUE THREAD

**Issue by emetsger** [CenterForOpenScience/osf.io#5653]
When a collection of resource objects (i.e. primary data) are returned, they may be paginated.  Pagination information is representing in a top-level `links` object.

The JSON-API 1.0 Spec says [this](http://jsonapi.org/format/#document-links) about the structure of `links` objects:

> Where specified, a links member can be used to represent links. The value of each links member **MUST** be an object (a “links object”).
> 
> Each member of a links object is a “link”. A link **MUST** be represented as either:
> 
>   * a string containing the link’s URL.
>   * an object (“link object”) which can contain the following members:
>     * href: a string containing the link’s URL.
>     * meta: a meta object containing non-standard meta-information about the link.

Currently the v2 API represents links objects in a way that is not compliant with the spec; the `meta` information is at the same level as the other link objects:

```json
    "links": {
        "first": null,
        "last": "https://test-api.osf.io/v2/nodes/?page=9",
        "prev": null,
        "next": "https://test-api.osf.io/v2/nodes/?page=2",
        "meta": {
            "total": 84,
            "per_page": 10
        }
    }
```

Unfortunately, to represent this meta information in a spec-compliant way, the links would have to become complex objects, each of them containing a `meta` object:

```json
  "links": {
    "first": {
      "href": null,
      "meta": {
        "total": 84,
        "per_page": 10
      }
    },
    "last": {
      "href": "https://test-api.osf.io/v2/nodes/?page=9",
      "meta": {
        "total": 84,
        "per_page": 10
      }
    },
    "prev": {
      "href": null,
      "meta": {
        "total": 84,
        "per_page": 10
      }
    },
    "next": {
      "href": "https://test-api.osf.io/v2/nodes/?page=2",
      "meta": {
        "total": 84,
        "per_page": 10
      }
    }
```

The above model is suspect, because the `meta` object should really be describing the resource collection (i.e. primary data) not an individual link object.  

A suggested solution is to construct paginated results where `meta` is a top-level object and a sibling of the `links` and `data` members.  This is spec-compliant, and also semantically correct.

```json
{
  "data": [
    {
      // object 1
    },
    {
      // object 2,
    },
    {
      // object n
    }
  ],
  "links": {
    "first": "http://localhost:8000/v2/nodes/",
    "last": "http://localhost:8000/v2/nodes/?page=m",
    "prev": null,
    "next": "http://localhost:8000/v2/nodes/?page=2"
  },
  "meta": {
    "total": "m",
    "per_page": "n"
  }
}
```

**Comment by brianjgeiger** [comment]
This checks out. Okay, we'll see what will be involved in getting this fixed.

**Comment by brianjgeiger** [comment]
Moved to Jira issue https://openscience.atlassian.net/browse/OSF-6330

**Comment by emetsger** [comment]
Great! Thanks!
