### ISSUE TITLE
Slight variations on date formats used in OSF /v2/ API

### ISSUE THREAD

**Issue by karenhanson** [CenterForOpenScience/osf.io#5712]
At least 4 slightly different date formats are used in the OSF API v2, making it harder to parse the dates consistently.  Some examples:

Node:
https://api.osf.io/v2/nodes/6n2re/:
"date_modified": "2016-05-20T20:40:32.206000"

Different node:
https://api.osf.io/v2/nodes/bygau/
"date_modified": "2016-05-23T14:40:15"

File:
https://api.osf.io/v2/files/573f742a594d9001f37be1ee/
"last_touched": "2016-05-20T20:39:26.704000",
"date_modified": "2016-04-15T12:05:01Z",
"date_created": "2016-04-15T12:05:01Z",

Different File:
https://api.osf.io/v2/files/5730aa679ad5a101e8877f18/
"date_modified": "2016-05-10T19:37:49.150Z",
"date_created": "2016-05-09T15:19:03.322Z",

It would be useful if the exact same date format was used for all. Thanks!

**Comment by emetsger** [comment]
It is worth noting that many of the above examples do not have timezone information, when in fact they are UTC.  Some timestamp libraries, when encountering timestamps with no timezone, will interpret them as being in local timezone.

**Comment by brianjgeiger** [comment]
This is fixed via https://github.com/CenterForOpenScience/osf.io/pull/6508 - use the API versioning to set the version to 2.2 and you will have normalized timestamps. Note that upgrading your API version will have other effects. See https://osf.io/y9jdt/wiki/Changelog/ for details.
