### ISSUE TITLE
No way to combine projects after they've been created

### ISSUE THREAD

**Issue by eplebel** [CenterForOpenScience/osf.io#587]
Example common use case. You create a project for a replication study, and then you decide to do a second replication study in a different project. Now I would like to combine both projects into a new project that has both projects as children.

E.g.
Independent Direct Replication #1 of Correll (2008, JPSP, Study 2): https://osf.io/zx4ia/
Independent Direct Replication #2 of Correll (2008, JPSP, Study 2): https://osf.io/iraqy/

It would be super useful to be able to combine these two projects into a super project called "Independent Replications of Correll (2008, JPSP, Study 2)"

**Comment by GaryKriebel** [comment]
Closed
