### ISSUE TITLE
[hgrid] 'Email file(s) to me' links

### ISSUE THREAD

**Issue by mambocab** [CenterForOpenScience/osf.io#597]
We might add a feature that allows users to input an email address and have some OSF resource emailed to that address. This could allow OSF users to easily share materials with non-users.

This could also help any users behind institutional firewalls that disallow certain downloads but who have access to email. SSRN [has this feature](http://www.ssrn.com/update/general/ssrn_faq.html#ob_copy), and their proposed use case is for users in this situation.

My thoughts on this are riffing on @RaoulGrosser's suggestion [here](https://github.com/CenterForOpenScience/openscienceframework.org/issues/578#issuecomment-46420328) that users should be able to request an archive of a GitHub addon's contents be emailed to them.

If you have an SSRN account, you can see how their implementation works [here](http://papers.ssrn.com/sol3/papers.cfm?abstract_id=2442459#) or on any other paper posted there.

**Comment by nanchen47** [comment]
Will be considered when we refactor the email system. Thanks.
