### ISSUE TITLE
Log breaks page if template not found

### ISSUE THREAD

**Issue by rliebz** [CenterForOpenScience/osf.io#599]
If there is a saved log that uses a non-existent template, the log list for that project will populate with an extraordinary number of repeated logs, causing extreme slowness and often crashing the chrome tab. 

This will almost certainly not be an issue on production, but if I were for instance to work on a feature branch, generate some branch-specific logs, then switch back to develop, I would basically be unable to access any project that I manipulated while on that branch.

**Comment by nanchen47** [comment]
Will be worked on when we refine the log system.
