### ISSUE TITLE
Add SSRN to "Social" links

### ISSUE THREAD

**Issue by anseljh** [CenterForOpenScience/osf.io#5992]
[SSRN](http://ssrn.com/) has made some missteps lately that are alienating many law professors and possibly others who publish their working papers there. Several law professors, including some influential ones, are now uploading their works into [SocArXiv](https://osf.io/view/socarxiv/), which is using OSF.

It would be great to add SSRN author page links to the list of other account links in your OSF profile. 

![2016-07-18-osf-add-ssrn](https://cloud.githubusercontent.com/assets/2075772/16935086/1d0a8ff8-4d11-11e6-8a2c-6f3288d69809.png)

**Why Do This**

SSRN is a pretty big deal: they have over 200K papers in just law, 394K in economics, etc.

Collecting this information now, when people are actively creating their OSF/SocArXiv profiles, would be helpful down the road to help authors import their content from SSRN. I have done some [experimental work toward parsing SSRN pages](https://github.com/OpenSSR/openssr-parser), so it's definitely feasible.

![2016-07-18-ssrn-stats](https://cloud.githubusercontent.com/assets/2075772/16935157/d9eb59ae-4d11-11e6-96f9-0660ac1919e7.png)

**Comment by saradbowman** [comment]
This is a great suggestion, thanks @anseljh! I'll get it in the queue.

**Comment by saradbowman** [comment]
Hey @anseljh - Sorry I forgot to let you know sooner, but this is in production now!
