### ISSUE TITLE
New Public Projects are all obvious spam

### ISSUE THREAD

**Issue by ClaytonJY** [CenterForOpenScience/osf.io#6111]
Perhaps this is known about, but I found some spam-marker issues from 2014 and nothing lately, so I thought I'd point out there's a deluge of spam accounts right now; every entry in "Newest Public Projects" as of this posting is clearly spam: https://osf.io/explore/activity/

I know spam filtering ain't easy, and if it's consistently hard to catch beforehand, it might be worth removing that section from the Public Activity page so as not to give new users a negative first impression of a valuable service.

**Comment by saradbowman** [comment]
@ClaytonJY Thanks for the heads up! We've removed these projects and are working on improved spam filtering.
