### ISSUE TITLE
Timestamps exposed by the V2 API do not have timezone information, and may be reasonably interpreted in local time.

### ISSUE THREAD

**Issue by emetsger** [CenterForOpenScience/osf.io#6116]
See example timestamps in issue #5712; timestamps absent timezone information [may be interpreted](http://www.cl.cam.ac.uk/~mgk25/iso-time.html#zone) in the local timezone.  

Please consider putting timezone information on timestamps, or at least documenting the timezone in the API docs.  Thanks!

**Comment by brianjgeiger** [comment]
This is fixed via https://github.com/CenterForOpenScience/osf.io/pull/6508 - use the API versioning to set the version to 2.2 and you will have normalized timestamps. Note that upgrading your API version will have other effects. See https://osf.io/y9jdt/wiki/Changelog/ for details.

**Comment by emetsger** [comment]
🍗🐔🎉
