### ISSUE TITLE
Automatically share project with all co-contributors

### ISSUE THREAD

**Issue by mambocab** [CenterForOpenScience/osf.io#617]
Feature request from one of the behavioral genetics folks: this user wants to be able to attach resources (I imagine a project) to their profile. All users who the owner collaborates with on any project would have read-only access to this project; it would not be shared with anyone else.

The use case is for sharing commonly-referenced materials with a research group. For instance, Brian uploads shared analysis scripts, reading lists, etc., to his "profile project". Brian takes on a new student, Maija. They create a project on which they are both contributors. Because Maija and Brian are co-contributors on the new project, Maija now has access to Brian's profile project.

**Comment by erinmayhood** [comment]
Closing as we plan for groups functionality.
