### ISSUE TITLE
[wiki] "history" shows diffs between rendered markdown and raw markdown

### ISSUE THREAD

**Issue by kmjungersen** [CenterForOpenScience/osf.io#624]
An interesting note is that when you try to view the history of a wiki, it shows the diffs in the form of the raw markdown:
![screen shot 2014-06-24 at 4 10 43 pm](https://cloud.githubusercontent.com/assets/6546342/3377082/fe45de16-fbdb-11e3-8593-786c898d346c.png)

...with the rendered markdown appearing as normal:

![screen shot 2014-06-24 at 4 10 55 pm](https://cloud.githubusercontent.com/assets/6546342/3377089/04e6cda2-fbdc-11e3-8721-3f8958694544.png)

@mambocab and I briefly discussed the issue, and think that possibly a way to easily toggle between the two in history would be nice.  While MD may be intuitive for us and for developers, it may not be intuitive for most people, and they may think that something is wrong with the page if it's showing a both of 1, 1, 1, etc. instead 1, 2, 3, etc., and pound signs next to things that should be bolded and what not.  The nested lists (ordered and unordered) are also displayed in a very confusing way (since there is no indentation), to the point that even with experience in MD, I found myself doing a lot of manual comparison between the MD and the rendered version to figure out what was what.

This may be (and is almost definitely) intended behavior as of right now, however I think some discussion on the matter may not be a bad idea!

**Comment by nanchen47** [comment]
This is an expected behavior. It will be considered when we enhance wiki system. Thanks.
