### ISSUE TITLE
Login Page error

### ISSUE THREAD

**Issue by umardraz** [CenterForOpenScience/osf.io#6248]
Hi,

I have configure this osf on CentOS, apparently it is successfully installed but when I click on login page, then there is something wrong and I am getting this.

Page not found (404)
Request Method: 	GET
Request URL: 	http://localhost:8080/login?service=http://localhost:5000/

Using the URLconf defined in api.base.urls, Django tried these URL patterns, in this order:

    ^v2/
    ^$ [name='redirect-to-root']
    ^static\/(?P<path>.*)$

The current URL, login, didn't match any of these.

Would you please help me what I did wrong and how to fix?

-- umar

**Comment by mfraezz** [comment]
Are you running CAS, either [real](https://github.com/CenterForOpenScience/docker-library/tree/master/cas#central-authentication-server-cas) or [fake](https://github.com/CenterForOpenScience/fakecas#fake-cas)? It handles authentication for us, and locally is expected to be running on port `8080`.

FakeCAS is significantly easier to set up. While I can't say for sure that the latest build works on CentOS, it's been tested on Fedora (and Ubuntu), so I suspect it will. Just in case it doesn't, I'll keep this ticket open. Let me know if this doesn't solve your problem, or if you encounter any issues getting either version of CAS up and running.

**Comment by umardraz** [comment]
HI, I think I am missing this FakeCAS, let me install this and will let you know if anything goes wrong.

**Comment by mfraezz** [comment]
Wonderful. We also have some [set-up docs](http://cosdev.readthedocs.io/en/latest/osf/setup.html#quick-installing-the-osf) available... although I notice that it doesn't mention [WaterButler](https://github.com/CenterForOpenScience/waterbutler), which you'll need if you're working with files.

**Comment by umardraz** [comment]
Ok I have install this FakeCAS, now all the urls are pointed to localhost:8080 and localhost:5000, I want to change them with my public so I can access this server from outside the localhost, would you please help me where I need to go change so all of these urls change accordingly.

**Comment by mfraezz** [comment]
FakeCAS should not be used for anything other than local development. What are you trying to do?

**Comment by umardraz** [comment]
well we are using this on our local network, I am using this on my CentOS and it has 192.168.1.20.

now invoke server or ./fackecas all are by default listening on localhost. my CentOS server is not a desktop machine. so how I can access this OSF interface on my desktop using http://,

I had installed the varnish on this CentOS server and then I had set backend as localhost:5000 varnish, with that I was able to access OS on my desktop machine, but all the href is set as localhost:5000 and for login localhost:8080/login?

I just want to know how to fix them?

**Comment by mfraezz** [comment]
You can specify the hosts (and database) with flags passed to fakeCAS:
```
❯ ../fakecas --help    
Starting FakeCAS 0.8.0
Usage of ../fakecas:
  -dbaddress string
    	The address of your mongodb. ie: localhost:27017 (default "localhost:27017")
  -dbname string
    	The name of your OSF database (default "osf20130903")
  -host string
    	The host to bind to (default "localhost:8080")
  -osfhost string
    	The osf host to bind to (default "localhost:5000")
```

**Comment by umardraz** [comment]
well I did that, but the problem is there is some kind of hard coded hrefs in the templates so they always remain localhost:5000

Please find the attached image and see the browser progress bar
![osf](https://cloud.githubusercontent.com/assets/3677378/18116316/4b6d0e68-6f60-11e6-90df-1b922ea2fd8f.png)

**Comment by mfraezz** [comment]
Did you override the `CAS_SERVER_URL` (and any other `<service>_SERVER_URL` found in `website/settings/defaults.py`) in your `local.py`?

**Comment by umardraz** [comment]
ok thanks, it worked, ok I have another thing which I want to confirm either it is just warning or that also need to fix.

node ./node_modules/webpack/bin/webpack.js --config webpack.prod.config.js

on the above command when it finished these lines are appears

WARNING in ./~/knockout/build/output/knockout-latest.debug.js
Critical dependencies:
22:24-31 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/knockout/build/output/knockout-latest.debug.js 22:24-31

WARNING in ./~/knockout/build/output/knockout-latest.js
Critical dependencies:
7:222-229 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/knockout/build/output/knockout-latest.js 7:222-229

WARNING in ./~/markdown-it/dist/markdown-it.js
Critical dependencies:
1:564-571 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/markdown-it/dist/markdown-it.js 1:564-571

WARNING in ./~/markdown-it-sanitizer/dist/markdown-it-sanitizer.js
Critical dependencies:
1:591-598 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/markdown-it-sanitizer/dist/markdown-it-sanitizer.js 1:591-598

WARNING in ./website/addons/wiki/static/ace.js
Critical dependencies:
5:52-59 require function is used in a way in which dependencies cannot be statically extracted
 @ ./website/addons/wiki/static/ace.js 5:52-59

**Comment by mfraezz** [comment]
That's expected output from `invoke assets`; it shouldn't be problematic.

**Comment by umardraz** [comment]
Ok, thanks for your help
