### ISSUE TITLE
Issues with making separate OSF site production ready

### ISSUE THREAD

**Issue by mattvw** [CenterForOpenScience/osf.io#6255]
Hello,

We're trying to set up our own OSF site in-house, using the osf.io repository, using Linux (Ubuntu 14) with Linuxbrew. So, I was able to more-or-less use the instructions that were provided for setting it up with OS X + Homebrew. My intention is to set up all the necessary components to run on the same server (no Docker!).

Everything is working with respect to the OSF site. I am able to use the site that was set up when using all the invoke commands to start up the various components (and using direct ports 5000/etc. with HTTPS). I even have Waterbutler working properly with the OSF site to make all the storage components work (on the same server).

Now I am trying to set it up so the site can be properly launched through a web server, rather then having to use all the invoke commands to start it all up (in other words, making it "production ready").

I am trying to use Apache + mod_wsgi to accomplish this, as I know it can work well with Django sites (apiserver & adminserver components). I have some experience with Apache + mod_wsgi, so I thought I'd try doing it that way. I don't have much experience with working with Flask apps (main site/server component) though.

I've tried to just start up the apiserver by itself using Apache + mod_wsgi, using the wsgi.py file that was found in api/base/. I have it all set up I believe correctly, but I am seeing this error message in the Apache logs when restarting the service:

```
[Tue Aug 30 13:26:40.365037 2016] [:error] [pid 5768:tid 140369222911744] [remote <remote IP>:10810] mod_wsgi (pid=5768): Target WSGI script '/opt/osf/api/base/wsgi.py' cannot be loaded as Python module.
[Tue Aug 30 13:26:40.365077 2016] [:error] [pid 5768:tid 140369222911744] [remote <remote IP>:10810] mod_wsgi (pid=5768): Exception occurred processing WSGI script '/opt/osf/api/base/wsgi.py'.
[Tue Aug 30 13:26:40.365110 2016] [:error] [pid 5768:tid 140369222911744] [remote <remote IP>:10810] Traceback (most recent call last):
[Tue Aug 30 13:26:40.365143 2016] [:error] [pid 5768:tid 140369222911744] [remote <remote IP>:10810]   File "/opt/osf/api/base/wsgi.py", line 9, in <module>
[Tue Aug 30 13:26:40.365185 2016] [:error] [pid 5768:tid 140369222911744] [remote <remote IP>:10810]     from website import settings
[Tue Aug 30 13:26:40.365213 2016] [:error] [pid 5768:tid 140369222911744] [remote <remote IP>:10810] ImportError: No module named website
```

It appears that there is some sharing of code between the main site/server and the apiserver. I don't have any experience setting up multiple sites that share the same code, so this is where I've hit a roadblock.

Has anyone done this using Apache + mod_wsgi as the web frontend? Or is there a better, easier way to accomplish what I'm trying to do? Is there a way to bring in the main site/server functionality correctly for the apiserver to work?

Can any assistance also be provided for how to implement the main site/server Flask app in a similar way?

Are there other components that will need to be started manually, i.e. can't be started through the web server?

Any help would be greatly appreciated!!

**Comment by brianjgeiger** [comment]
Hi, @mattvw,

I'm afraid I won't be much help here. We don't have the resources to support other folks running the OSF in production just yet. I can tell you that we use nginx to handle getting the data to the web, but beyond that, it's a land of devops that I tend to avoid as much as possible. To my knowledge, nobody has used Apache for the purpose with the OSF.
