### ISSUE TITLE
[private links] when viewing a public project through a PL, no alert is shown.

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#628]
Usually, when viewing a project through a private link, you get an alert at the top of the page to tell you that you're viewing it through special means.

However, if I have a public project with private components and I make a private link that includes the project and its components, the people that I share it with won't have any kind of alert on the top of the parent project's page to notify users.

I think that even if you're viewing a public page, you should see the alert.

**Comment by nanchen47** [comment]
This is an expected behavior. Will consider an enhancement when we update view-only link. Thanks.
