### ISSUE TITLE
[user settings] no active class on left sidebar

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#631]
In user settings, there is a left sidebar with profile and add-on configuration as options. There should be an active class added to these so that there is an indication of which one the user is currently viewing. Currently, regardless of which one you are looking at, the sidebar doesn't update.

**Comment by GageGaskins** [comment]
@lyndsysimon @lbanner @GaryKriebel I have this one ready if we're still trying to add this.

**Comment by lbanner** [comment]
OK @GageGaskins .... go ahead and submit a PR on this. TY.

**Comment by jlcohoon** [comment]
This is also the case with the project settings page now too—could that be resolved in this issue as well?
