### ISSUE TITLE
[figshare] private FS files are public on public OSF projects

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#634]
A public OSF project will make public all linked Figshare files, even if they are private according to Figshare. For example, this is confirmation that my file is private on Figshare:
![screen shot 2014-06-25 at 11 00 14 am](https://cloud.githubusercontent.com/assets/4965832/3387001/81234c9a-fc79-11e3-83a6-dc1aadfcdb1f.png)

But when not logged into the OSF and viewing a public project, I can still see that private file listed:
![screen shot 2014-06-25 at 11 00 55 am](https://cloud.githubusercontent.com/assets/4965832/3387005/89731006-fc79-11e3-90c5-24ff9df34c12.png)

**Comment by nanchen47** [comment]
Will be worked on when we refactor the warning system. Thanks.
