### ISSUE TITLE
Internal wiki links

### ISSUE THREAD

**Issue by aaronwolen** [CenterForOpenScience/osf.io#6357]
Although it looks like OSF is [already][1] [configured][2] to support the [WikiLinks](https://en.wikipedia.org/wiki/Hyperlink#Hyperlinks_in_wikis) shorthand for creating links to internal wiki pages, using the `[[]]` markup within a wiki page doesn't actually produce a link.

[1]: https://github.com/CenterForOpenScience/osf-models/blob/7bcc4269c89733073049f39f817204c9d2b2e793/osf_models/models/wiki.py#L8
[2]: https://github.com/CenterForOpenScience/osf-models/blob/7bcc4269c89733073049f39f817204c9d2b2e793/osf_models/models/wiki.py#L56:L62

Steps
-------
1. Create a wiki with only 2 pages: *Home* and *Test*.
2. Add `[[Test]]` to *Home* and save.

Expected
------------
`[[Test]]` to be rendered as a link pointing to `wiki/Test/`.

Actual
--------
The raw `[[Test]]` markup is left as is.

![screen shot 2016-09-29 at 10 09 01 am](https://cloud.githubusercontent.com/assets/1067915/18957375/c82fa54a-862c-11e6-860e-d5d8837b6461.png)

**Comment by brianjgeiger** [comment]
Our current markdown engine is [Markdown-It](https://markdown-it.github.io). All the Python code is legacy and being removed shortly.

**Comment by aaronwolen** [comment]
Okay, so no internal links with Markdown-It. Thanks for the info.

Awesome that OSF is using a parser that supports CommonMark! This is just for the wiki, correct? The renderer used for markdown files stored on OSF appears to only support strict Markdown. That inconsistency could be confusing for new users.

**Comment by brianjgeiger** [comment]
Yeah, the goal is to get wiki and files merged, and probably moving to storing wikis as files. At that point, we could potentially even allow you to choose your renderer within reason (rst, for example), but keep the renderers between the two the same. We have a couple of internal refactors to do first, and then we can start making the wiki properly good.

**Comment by aaronwolen** [comment]
That sounds great! Looking forward to it.
