### ISSUE TITLE
Changing contributor's name doesn't update in citation viewer

### ISSUE THREAD

**Issue by MGretton** [CenterForOpenScience/osf.io#6382]
To reproduce:
1. User creates profile and misspells their own name
2. User is then added as a contributor to a project and the citation (in APA, MLA and Harvard) is automatically generated based on their name
3. User then corrects the spelling of their name on their own profile page
4. User's name is now correctly spelled on the project page contributor's list, but the old misspelling is retained in the generated citation.

**Comment by saradbowman** [comment]
Hi @MGretton 
There are two places for a user to enter his/her name on the user profile page. The first is for the users display name, and the second is used for generating citations. I wonder if you're updating one but not the other, and that's causing the problem? Here's a screenshot with what I'm talking about:

![screen shot 2016-10-12 at 8 59 58 am](https://cloud.githubusercontent.com/assets/7749914/19311211/5a628eea-905b-11e6-933b-83443899850a.png)

You can click "autofill" to fill the citation-generating name based on your display name, or you can fill it out independently. Let me know if that helps!

**Comment by MGretton** [comment]
Hi @saradbowman - thanks so much for that, it's all fixed now. I couldn't view the profile myself and didn't realise that's what was happening. Much appreciated.
