### ISSUE TITLE
Losing file encoding when Moving existing files or Uploading new

### ISSUE THREAD

**Issue by abrinckm** [CenterForOpenScience/osf.io#6461]
I'm observing this when trying to upload or rename image files in OSF storage. For example, see this request to rename: 

```
POST /v1/resources/<proj_id>/providers/osfstorage/<file_name> HTTP/1.1
Host: staging-files.osf.io
Authorization: Bearer <my_access_token>
Content-Type: application/json
Cache-Control: no-cache
{
	"action": "rename",
	"rename": "irenamedthis"
}
```

Before issuing this request, I can view this file as an image (as it is). After issuing this request, the file is successfully renamed to "irenamedthis", however I am no longer able to view this file as an image. When I download this file and try to preview it in the Mac OS preview app, it gives an error:
 `It may be damaged or use a file format that Preview doesn’t recognize.`

This occurs when uploading new images to OSF storage as well when using this request:

```
PUT /v1/resources/<proj_id>/providers/osfstorage/?kind=file&amp;name=anotherpicture.jpg HTTP/1.1
Host: staging-files.osf.io
Authorization: Bearer <my_access_token>
Content-Type: image/jpeg
Content-Length: 182475
Cache-Control: no-cache
```

Please note that I do not experience these bugs when manipulating files through the web app at https://staging.osf.io. This only happens when submitting raw http requests.

**Comment by felliott** [comment]
Hey @abrinckm,

What client are you using to upload the file?  I've seen this happen in the past with clients that automatically form-encode their payloads.  `staging-files` expects raw data and will not automatically decode for you.  Form-encoded data look like this:

```
--169f57f74e814c33a26670e06ffa77a8
Content-Disposition: form-data; name="attributes"

{"name": "aaa-01.txt", "parent": {"id": null}}
--169f57f74e814c33a26670e06ffa77a8
Content-Disposition: form-data; name="file"; filename="aaa-01.txt"
Content-Type: application/octet-stream
Content-Transfer-Encoding: binary

fesnabbaurnm

--169f57f74e814c33a26670e06ffa77a8--
```

If that's not it, please let me know!

Cheers,
@felliott

**Comment by abrinckm** [comment]
My client must've been the problem! Thank you! 
I was using Postman as my client. Submitting via the Node.js request module worked fine.
