### ISSUE TITLE
OSF on Ubuntu - start up problem

### ISSUE THREAD

**Issue by TomMiksa** [CenterForOpenScience/osf.io#6592]
Hi guys,

I've been installing OSF on Ubuntu 16.10. I have followed your installation manual and have problems running the OSF server. I would very much appreciate your help, because I have run out of ideas.

STEPS:

I've followed http://cosdev.readthedocs.io/en/latest/osf/setup.html including installing one piece at a time.
The major differences is that instead of TokuMx I have installed Percona Server for MongoDB, because TokuMx is not supported anymore.
https://www.percona.com/doc/percona-server-for-mongodb/3.2/install/apt.html
After installing manually the indivial compoments I've run "invoke setup" and didn't get any errors.

EXPECTED:

To start OSF I run following commands in separate consoles being in the osf folder using osf virtualenv:

mongodb (percona) runs as a daemon
invoke mailserver
invoke rabbitmq
**celery worker** OR **invoke celery_worker**
elasticsearch also runs as a daemon 
invoke assets -dw
invoke server

WHAT HAPPENS:

When I run "invoke celery_worker" I get the following error:
`OperationFailure: bad index key pattern { referent.$: 1 }: Index key contains an illegal field name: field name starts with '$'.`
[celery_error.txt](https://github.com/CenterForOpenScience/osf.io/files/614673/celery_error.txt)

But everything looks fine when I run it like this: "celery worker". 
However, then when starting the server I get this error:
`pymongo.errors.OperationFailure: command SON([('create', u'maintenance')]) failed: collection already exists`
[server_error.txt](https://github.com/CenterForOpenScience/osf.io/files/614672/server_error.txt)

POTENTIAL CAUSES:

I connected to the database, and yes, the collections are already there. I suppose they were created by the setup. Is the server trying to create them again? Could this be a problem caused by the celery or this has something to do with using Percona instead of TokuMx?

**Comment by TomMiksa** [comment]
I managed to get it running. I had to make the following changes:
- downgrade to Ubuntu 14.04
- install the original TokuMx https://github.com/Tokutek/mongo/wiki/Installing-on-Debian-and-Ubuntu

**Comment by TomBaxter** [comment]
Glad to hear you got it working. For posterity's sake I would like to note that the tarball at https://www.percona.com/downloads/percona-tokumx/tokumx-enterprise-2.0.2/binary/tarball/tokumx-e-2.0.2-linux-x86_64-main.tar.gz is working for me on Ubuntu 16.04
