### ISSUE TITLE
Add new branding to OSF for Meetings

### ISSUE THREAD

**Issue by rustyspeidel** [CenterForOpenScience/osf.io#6679]
We have a new logo for OSF Meetings and I'd like to get it added to the product home page. Two logo versions attached. 
![osfmeetings_white](https://cloud.githubusercontent.com/assets/135407/21325821/1afd9bc0-c5f6-11e6-9e63-5b27ed375408.png)
![osfmeetings black](https://cloud.githubusercontent.com/assets/135407/21325820/1afccaec-c5f6-11e6-8c6e-2c9a8613e25f.png)

**Comment by saradbowman** [comment]
@rustyspeidel do you want this to go on osf.io or cos.io?

**Comment by rustyspeidel** [comment]
sorry, osf. the actual service.

**Comment by saradbowman** [comment]
Ok, can you put this in JIRA as an improvement ticket?
