### ISSUE TITLE
[Interface request] Link to OSF from OSF Help

### ISSUE THREAD

**Issue by LibrarPotter** [CenterForOpenScience/osf.io#6682]
Once in the http://help.osf.io/ section of the site, there does not appear to be a link back to the main,  https://osf.io/, page. Perhaps the footer from https://osf.io/ could be added to the help section.

**Comment by BRosenblatt** [comment]
http://help.osf.io/ now links back to the OSF homepage.

**Comment by sloria** [comment]
Thanks for the suggestion @LibrarPotter and thanks @BRosenblatt for adding the link. Closing.
