### ISSUE TITLE
'extra' field in 'registered_meta' 'summary' object is serialized as an object and as an array.

### ISSUE THREAD

**Issue by emetsger** [CenterForOpenScience/osf.io#6696]
Summary
-----------

The `registered_meta` field carries an object named `summary`. The `summary` object carries a field named `extra`.  I have two registrations; each registration serializes the `extra` field differently.

Both registrations would have been made by the UI (not the API).  Note that `5nua2` was registered some time after `tgzhk` (August vs March), so maybe some change in the underlying code base is responsible for this?

Steps
-------
1.   Look at `registered_meta` for [`tgzhk`](https://api.osf.io/v2/registrations/tgzhk/?version=2.2) (note: using version 2.2 of the API)- `extra` is serialized as an empty object:
```json
"registered_meta": {
                "summary": {
                    "value": "Test registration.",
                    "comments": [],
                    "extra": {}
                }
            }
```

2.  Look at `registered_meta` for [`5nua2`](https://api.osf.io/v2/registrations/5nua2/?version=2.2) (note: using version 2.2 of the API)- `extra` is serialized as an empty array:
```json
"registered_meta": {
                "summary": {
                    "value": "test",
                    "comments": [],
                    "extra": []
                }
            }
```

Expected
------------
I would expect the type of the `extra` field to be consistent.  That is, for all `registered_meta` instances, all `extra` fields would either be an array or an object, but not both. 

This is all the more curious because the values for `extra` in this case are empty!  

Actual
--------
In actuality, it appears that the `extra`, at least when part of `registered_meta`, can be arbitrarily an object or an array, which proves problematic when deserializing the JSON to Java objects.

**Comment by emetsger** [comment]
Got bit by this today, so here's another example in the wild:
[registration 5nua2](https://api.osf.io/v2/registrations/5nua2/url) serializes `extra` as an empty object, whereas [registration b6psa](http://localhost:8000/v2/registrations/b6psa/) serializes `extra` as an empty array.

**Comment by msuhovec** [comment]
As a downstream user of the the DataConservancy PSF packaging tool, I am at present unable to Archive OSF Registrations into or CurateND repository, as I encounter this JSON serialization error whenever we try to download a registration via the packaging tool. This has left our development effort to support OSF Projects and Archives curated Data types in Limbo until this problem is resolved.

**Comment by felliott** [comment]
Hey @emetsger, @msuhovec,

We've got a ticket for this issue.  It'll probably in the second post-Django release.

Cheers,
@felliott

**Comment by brianjgeiger** [comment]
Good news! This was just bad data and not actively bad code. The data has been fixed, and shouldn't be a problem in the future. Let us know if you have additional trouble with this.

**Comment by brianjgeiger** [comment]
Also, the field should always be a list. If there's anything in the list, currently that's going to be file metadata.
