### ISSUE TITLE
502 when issuing version requests against GitHub storage provider

### ISSUE THREAD

**Issue by emetsger** [CenterForOpenScience/osf.io#6705]
Steps
-------
1. Issue a GET against a github storage provider: `curl -s https://api.osf.io/v2/nodes/xug4a/files/github/`
    - a `200` with JSON should be returned.
2. Issue the same GET request, but with a specific API version: `curl -s https://api.osf.io/v2/nodes/xug4a/files/github/?version=2.2` or `curl -sH "Accept: application/vnd.api+json;version=2.2" https://api.osf.io/v2/nodes/xug4a/files/github/`
    - a `502 Bad Gateway` is returned for either of those requests

Expected
------------
I expect a successful response (`200`) containing the 2.2 API serialization of a GitHub storage provider file listing to be returned.

Actual
--------
Received a `502` when a `200` was expected.

**Comment by felliott** [comment]
Will be fixed after django-osf is released.

[#OSF-7316]

**Comment by brianjgeiger** [comment]
Fixed in https://github.com/CenterForOpenScience/osf.io/releases/tag/0.106.0
