### ISSUE TITLE
Failed registration behaviors

### ISSUE THREAD

**Issue by chrisseto** [CenterForOpenScience/osf.io#671]
A problem that has not yet been fully addressed is that of failed registrations. 
Currently they just hang in limbo, this is not the ideal behavior.

So the question becomes what to do with failed registrations, we could:
* Delete it with no trace
* Leave it but marked as failed
* Alert user and delete it.
* etc

**Comment by HarryRybacki** [comment]
@GaryKriebel I think this fell into the abyss. We should reassess the behavior, if it's fine, close this out, else update it.

**Comment by nanchen47** [comment]
This is no longer a problem with the new registrations system.
