### ISSUE TITLE
update the Copyright year on Sign In page.

### ISSUE THREAD

**Issue by raj-maurya** [CenterForOpenScience/osf.io#6711]
Please update Copyright © 2011-2016 to Copyright © 2011-2017 on [Sign In](https://accounts.osf.io/login?service=https://osf.io/)

Thank you!

**Comment by sloria** [comment]
Thanks for reporting, @raj-maurya . @cslzchen Can you please update this in CAS?

**Comment by cslzchen** [comment]
@sloria Sure.

**Comment by cslzchen** [comment]
Here is CAS PR: https://github.com/CenterForOpenScience/cas-overlay/pull/35, we will merge it when tests pass.

**Comment by raj-maurya** [comment]
Thanks @cslzchen  and @sloria
