### ISSUE TITLE
Remove watermark from registrations

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#673]
The large "read-only" watermark is distracting. I propose removing it.

![osf___project_explicit](https://cloud.githubusercontent.com/assets/2379650/3512008/c32cb578-06b4-11e4-9066-92978da66a3c.png)

I think the un-dismissable blue alert at the top of the page fulfills the purpose of indicating that a node is a registration. We might also add an icon next to the project title to make it even more clear.

Pinging @jlcohoon @caneruguz @bnosek  for thoughts on this.

**Comment by HarryRybacki** [comment]
@GaryKriebel another one that got pushed into the backlog abyss -- update/close?

**Comment by sloria** [comment]
Would still like to see further movement on this, so would prefer not to close.

**Comment by GaryKriebel** [comment]
Let's see what @JeffSpies has in terms of legal updates.

**Comment by JeffSpies** [comment]
Why are we removing the watermark?

**Comment by brianjgeiger** [comment]
Because @sloria felt 10 months ago that it was distracting and that the blue floating bar does enough. The last item from you said we should wait until changing interface and lawyer talking could impact, so to defer until that was done.

**Comment by JeffSpies** [comment]
Caught up, sorry. Yeah, unless there's user feedback about it not differentiating, then this should be closed for the time being.

**Comment by GaryKriebel** [comment]
Closing this issue.  Will open a new issue if user feedback warrants it.

**Comment by sloria** [comment]
For better or worse, we receive very little user feedback on UI concerns like this (thus far, our UI decisions have been informed by our own usage of the site).

Given that others agreed that there might be better alternatives to the status quo, I'm not sure why this was closed. It can definitely be put on hold, but I think this is low-hanging fruit for improving the presentation of registrations.

**Comment by jlcohoon** [comment]
I agree with Steve. We do have one comment from UI review the other day
about the background being unattractive. We could see if the interns say
anything as well?

**Comment by JeffSpies** [comment]
I think the grey background is unattractive and doesn't do what we need it
to. If there is serious concern on usability and aesthetic, then we can
consider making it a priority when our designers get to the base OSF L&F.
Until then, unless there is a better solution proposed that addresses both
usability and aesthetic, then we can keep this closed.

If anyone want spend time thinking about UI, let's focus on the things that
users actually see--right now, registrations is not one of them. Lower
hanging fruit is hanging elsewhere--let's prioritize. To me, this is low on
the priority list as compared to those things.

J.
