### ISSUE TITLE
Error retrieving paginated search results: 502 Bad Gateway

### ISSUE THREAD

**Issue by emetsger** [CenterForOpenScience/osf.io#6751]
Steps
-------
1. Execute a search for "Johns Hopkins" using the v2 Search API (I get 66 results across 6 pages of results):
* `curl -s 'https://api.osf.io/v2/search/?q=%22johns%20hopkins%22'`
2. To obtain the full result set, each page will have to be retrieved
* `curl -s 'https://api.osf.io/v2/search/?q=%22johns%20hopkins%22?page=2'`
* `curl -s 'https://api.osf.io/v2/search/?q=%22johns%20hopkins%22?page=3'`
* ... and so on

Expected
------------
I expect to be able to retrieve each page of results (e.g. receive a `200`), totaling 66 "hits".

Actual
--------
I've had problems either retrieving page 3 or page 4 of the results.  In this example, page 4 is problematic:

```
curl -Is 'https://api.osf.io/v2/search/?q=%22johns%20hopkins%22&page=4'
HTTP/1.1 502 Bad Gateway
Date: Fri, 20 Jan 2017 15:56:12 GMT
Content-Type: text/html
Content-Length: 166
Strict-Transport-Security: max-age=16000000; preload;
```

The bug seems to be a function of the total number of results and where the problematic record exists within the results.

**Comment by brianjgeiger** [comment]
Added to Jira. Thanks!

**Comment by brianjgeiger** [comment]
Fixed in https://github.com/CenterForOpenScience/osf.io/releases/tag/0.106.0
