### ISSUE TITLE
storage add-ons link to enable-add-ons is empty

### ISSUE THREAD

**Issue by mlinksva** [CenterForOpenScience/osf.io#6757]
Steps
-------
1. Visit http://help.osf.io/m/addons/l/524149-storage-add-ons
2. See "see the Enable Add-ons article"
3. Click link, still on http://help.osf.io/m/addons/l/524149-storage-add-ons (because the link is empty)

Expected
------------
3. Click link, obtain http://help.osf.io/m/addons/l/524148-enabling-add-ons

**Comment by saradbowman** [comment]
Thanks @mlinksva! Link is fixed.
