### ISSUE TITLE
Add-on behavior not defined for merging users

### ISSUE THREAD

**Issue by rliebz** [CenterForOpenScience/osf.io#677]
@JeffSpies @sloria
When user accounts are merged, on each project, one account is added and the other is removed. This activates the `after_remove_contributor` callback, which removes add-on credentials from all projects that the removed account had authorized. 

I'm not sure what the expected behavior should be—the safest bet would be to inform the user before merging that all projects authorized by the "deleted" account will need to be manually reauthorized. We could instead/additionally define some add-on `after_merge_contributor` callback to handle this case more specifically, although this is a bit of an edge case to have to define a callback for all current and future add-ons. Thoughts?

**Comment by lbanner** [comment]
I am going to remove 'deferred' on this one -- just in case this "standardization will occur in an upcoming refactor of add-ons" can happen in next Epic.

**Comment by lyndsysimon** [comment]
Self-assigning; this is part of my task list for this epic.

**Comment by lbanner** [comment]
@lyndsysimon -- This taken care of in level 2 merge #2548 - Correct?

**Comment by GaryKriebel** [comment]
Fixed in https://github.com/CenterForOpenScience/osf.io/pull/2548

**Comment by nanchen47** [comment]
The pr already goes into production.
