### ISSUE TITLE
Make a flag to allow registrations without confirmation

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#703]
It does not appear that we have the ability to optionally auto-confirm accounts in the OSF. This would be a great flag. Partially because it's convenient for development situations, but mostly for staging. We've gotten our confirmation message marked as spam when it came from the unnamed staging server at least once, and it'd be a shame to start training spam filters the taste of those messages if we can avoid it. Might not be a big deal, but.

**Comment by lbanner** [comment]
This looks to be covered - Closing.
