### ISSUE TITLE
Don't load all nested nodes on files page

### ISSUE THREAD

**Issue by jmcarp** [CenterForOpenScience/osf.io#709]
The files page currently recurses over all nodes and pointers in the tree, which means we're loading potentially large numbers of files on deeply nested projects (see https://osf.io/ezcuj/ for an example). To cut back on the number of unnecessary requests, how about only loading the tree to a fixed depth (maybe just the root node and its immediate descendants) to start with?

**Comment by caneruguz** [comment]
Currently the files page will only load the root of addons. @GaryKriebel can we consider this issue fixed?
