### ISSUE TITLE
[Project-Organizer] feature request - easy to add certain facets

### ISSUE THREAD

**Issue by AndrewSallans** [CenterForOpenScience/osf.io#711]
Use case:  I want to create a Project-Organizer folder for all projects from a certain researcher or from a certain lab or on a certain topic.  Perhaps allow for results from an elasticsearch to generate a new folder, or to allow check boxes to add to a folder.

**Comment by nanchen47** [comment]
Will be consider when we enhance the project organizer. Thanks.
