### ISSUE TITLE
Name change not reflected in project dashboard

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#713]
Steps
--------------
1) Go to your profile page
2) Click on your name 
3) Change your name (click the checkmark)

![screen shot 2014-09-22 at 10 33 30 am](https://cloud.githubusercontent.com/assets/6414394/4357901/1894fb64-4266-11e4-8191-670f66e2f116.png)

Expected
---------------------------------
I would expect that my name would then be changed wherever it appears on the OSF. 

Actual
------------------------------
The project citation in my dashboard still says Ehsan (even though the tooltip is correct): 
![screen shot 2014-09-22 at 10 41 29 am](https://cloud.githubusercontent.com/assets/6414394/4357965/91a92034-4266-11e4-9ee7-5b774e36e35a.png)

However, the project page itself displays the correct name:
![screen shot 2014-09-22 at 10 40 17 am](https://cloud.githubusercontent.com/assets/6414394/4357950/85b80b78-4266-11e4-9ac2-2c4240e3893c.png)

Possible Cause 
---------------------
Changing your name on the OSF does not automatically update your citation in the settings page: 

![screen shot 2014-09-22 at 10 35 18 am](https://cloud.githubusercontent.com/assets/6414394/4357997/d167c3ce-4266-11e4-9348-681b90e0024d.png)

Possible Solutions
------------------------
- Alert user that they may need to update their bibliographic citation 
- Redirect users to their profile settings page to edit their name 
- Automatically update user citation information

I like the idea of redirecting users to their profile page, since they can see the citation fields and change them if necessary.

**Comment by brianjgeiger** [comment]
This will be fixed by #1465.

**Comment by samanehsan** [comment]
Closing this since users can no longer edit their names from the profile page. It is still possible to edit your name in your user settings page without changing your citation info, but now it is less likely to occur on accident.
