### ISSUE TITLE
Migrate data from MongoDB to PostgreSQL

### ISSUE THREAD

**Issue by sonnenschein123** [CenterForOpenScience/osf.io#7212]
Hello, 
is there a way to to migrate the local data from the MongoDB to the PostgreSQL database ?
Best 
sonnenschein123

**Comment by saradbowman** [comment]
Hi @sonnenschein123,

Here’s a branch with the last version of the migrations in it:
https://github.com/cwisecarver/osf.io/tree/feature/optimize-fk-migrations/

These are the steps to complete the migration:
$ python -m scripts.merge_duplicate_users
$ python -m scripts.set_null_usernames_to_guid
$ python -m scripts.migration.ensure_bookmark_uniqueness_legacy

Then start a celery worker in a new shell: (replace 2 in the next line with the concurrency that’d you would like to run celery with)
$ celery worker -A api.base -c 2 -Q celery -n celery0@%h --purge --maxtasksperchild 100 -Ofair

Erase your Postgres db and create a new one and the table structure
$ python manage.py reset_db --noinput && python manage.py migrate

Migrate data fields for all models
$ python manage.py migratedata && python manage.py migratedata —nodelogs

Migrate guids and blacklist guid
$ python manage.py migratedata —dependents

Migrate foreign key relations
$ python manage.py migraterelations —fk

Migrate many to many relations
$ python manage.py migraterelations --m2m


Hope this helps.

**Comment by sonnenschein123** [comment]
Hey @saradbowman, 
this is very helpful. 
Thanks a lot!
