### ISSUE TITLE
Long file names unreadable in analytics popular page list

### ISSUE THREAD

**Issue by wikey** [CenterForOpenScience/osf.io#7254]
File names longer than about 15 characters double over on themselves in the popular page widget. The resulting text is largely illegible. See https://osf.io/ixgcd/analytics/ for a good project example. Screenshot attached from Chrome (58.0.3029.110 (64-bit)) on OSX but I get similar results on the major linux browsers as well.

![screen shot 2017-05-22 at 7 27 07 pm](https://cloud.githubusercontent.com/assets/1824588/26332484/e096e0e2-3f24-11e7-8ad1-5ad844fc5582.png)

**Comment by saradbowman** [comment]
Thanks for the report @wikey! I moved this over to the bugs and improvements board and added you as a watcher there. Can you close this ticket?
