### ISSUE TITLE
"File not found at Google Drive." message when file exists on drive

### ISSUE THREAD

**Issue by TomHardwicke** [CenterForOpenScience/osf.io#7270]
## Description of problem
I have a google doc linked up with an OSF component but OSF seems to be having problems 'finding' it. The doc is there when I check on my Google Drive. Also when I choose the "view on google drive" option on the OSF then it does take me to the document. So OSF appears to be having trouble rendering the doc.

## Steps
1. Go to https://osf.io/jmk75/files/googledrive/Preregistration.gdoc/

## Expected

Rendered Google doc.

## Actual

"File not found at Google Drive."

**Comment by saradbowman** [comment]
Hey @TomHardwicke, thanks for the bug report and sorry for the error! When I go to that link, I see the Google doc rendered. Can you check again? Wondering if this got fixed between your report and me seeing it. Thanks!
