### ISSUE TITLE
Changing username from profile silently leaves individual name fields unaltered

### ISSUE THREAD

**Issue by rliebz** [CenterForOpenScience/osf.io#728]
I suspect this is also related to #713

Say I register as "Aobert Aiebowitz". I go to my profile, and realize I've made a horrible spelling mistake. I go to my profile, change my name to "Bobert Biebowitz", and assume I've finished.

There is no indication that on the account settings page, there are 4 name fields that exist unaltered from my original input. Because of this, any time I am referenced by last name alone on the OSF, I will still be listed as "Aiebowitz." 

I would expect to be notified that this discrepancy might exist, and even better, given the option to correct those fields without leaving the page.

**Comment by samanehsan** [comment]
Closing this issue since you can no longer edit your profile information from your profile page.
