### ISSUE TITLE
[improvement] Move user profile link off of user name in add contributor view

### ISSUE THREAD

**Issue by wikey** [CenterForOpenScience/osf.io#7297]
When adding contributors to a project it can be very tempting to click directly on their name when you find it in the search list rather that first finding the name from the list then finding the "Add" button. If the link were moved to a separate "view profile" button so that the name were no longer directly clickable it might make the process smoother for new users.

**Comment by saradbowman** [comment]
Thanks @wikey, moved this into our internal tracking! Can you close this one please?
