### ISSUE TITLE
FakeCas: Internal Server Error

### ISSUE THREAD

**Issue by antonwats** [CenterForOpenScience/osf.io#7347]
Hi! I'm trying to run a local instance of OSF, and I've succeeded in getting the website running @ localhost. I'm now trying to setup my local authentication with FakeCAS and it is correctly redirecting me to localhost:8080 and prompting me for an email. I first tried putting in a random email and I was given an Internal Server Error. So I navigated to the 'Sign Up' page and created an account; this was also successful. When I returned to the login page, however, FakeCAS returns an Internal Server Error for any email I typed in. 

I'm thinking it could be an error involving PostgreSQL, but I'm not sure. I'm totally new at this, so any help is appreciated!

Thanks!

**Comment by antonwats** [comment]
After doing some digging, it seems that fakeCAS is searching for the supplied email using a command ANY(emails) but it should be ANY(username) as usernames are stored in the osf_osfuser table by a 'username' column. I'm going to try and find what file this command is located in, make the change, and see if anything changes.

**Comment by sloria** [comment]
@antonwats Are you using the latest fakecas binary? If you're using docker-compose (recommended), you can do `docker-compose pull fakecas` then `docker-compose up fakecas`.

**Comment by antonwats** [comment]
This worked! Thank you!
