### ISSUE TITLE
[File organization] More sorting features

### ISSUE THREAD

**Issue by kmjungersen** [CenterForOpenScience/osf.io#742]
Right now, you can sort files/folders alphabetically and that's it.  It alphabetizes top level folders first and then moves down the hierarchy, which is intended behavior, and is very useful.  Unfortunately, this is the only way to sort files right now.  At the very least, there should be `Date Added` and/or `Date Created` fields.  I'm not sure what other fields would be useful, but I'm sure there are others.  Discuss?

On a separate, yet related note, a page refresh after sorting files alphabetically loses those changes.  In a situation where a user has a long, long list of files/folders, it would be nice for those changes to stick around.

**Comment by jinluyuan** [comment]
It would also help if folders were sorted first within a storage add-on, and then individual files. The current system makes locating and using folders a little more difficult.

![screen shot 2015-06-29 at 11 29 43 am](https://cloud.githubusercontent.com/assets/8591162/8411495/317d64ae-1e52-11e5-9d67-db6e390f234f.png)
