### ISSUE TITLE
[File Organization] [feature] Expand/collapse all folders

### ISSUE THREAD

**Issue by kmjungersen** [CenterForOpenScience/osf.io#743]
This could certainly be discussed, but I could certainly see some value in this.

Potential use-case: a scientist has thousands of pictures of cells in many different folders labeled by experiment.  They want to go to a particular experiment performed about 6 weeks ago, so they collapse all folders to see all experiment folders, sort by date added (feature requested in #742), and then they are able to quickly navigate to the approximate point in time they're looking for to begin searching for the exact experiment.

**Comment by nanchen47** [comment]
Will be worked on with the treebeard enhancement.
