### ISSUE TITLE
safely render user-supplied html files in file browser using iframe sandbox

### ISSUE THREAD

**Issue by rubenarslan** [CenterForOpenScience/osf.io#7482]
Would it be possible to render HTML files in the file browser view without having to download them?

When I originally shared my rmarkdown output on the OSF, you still used to render HTML when clicking the download button. Now users have to download the files and view them locally. This extra step made me switch to Github pages.

But as far as I can tell, you could safely include files from your API via <iframe src="" sandbox="">
https://osf.io/5st8i/

Any reason not to do this? Currently, this encourages people to upload PDFs which are very lossy and not easily machine-readable.

**Comment by Johnetordoff** [comment]
This is a nice suggestion, but it would be more visible to developers in the  [MFR Repo](https://github.com/CenterForOpenScience/modular-file-renderer). The MFR is the service we've created to render files.
