### ISSUE TITLE
502 error in the API while adding a contributor to a project

### ISSUE THREAD

**Issue by wetneb** [CenterForOpenScience/osf.io#7575]
We use the OSF API to deposit papers in OSF Preprints. We get a 502 error while adding contributors.
The following log comes from our test suite. The tests started failing (with no related code change) a while ago.

```
### Creating a project
--- Request to https://test-api.osf.io/v2/nodes/
Status code: 201 (expected 201)

### Creating a new deposit

--- Request to https://test-api.osf.io/v2/nodes/udj37/files/
Status code: 200 (expected 200)

### Uploading the PDF

--- Request to https://test-files.osf.io/v1/resources/udj37/providers/osfstorage/?kind=file&name=article.pdf
Status code: 201 (expected 201)

--- Request to https://test-api.osf.io/v2/nodes/udj37/contributors/
Status code: 201 (expected 201)

--- Request to https://test-api.osf.io/v2/nodes/udj37/contributors/

Status code: 502 (expected 201)
Server response:

<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by brianjgeiger** [comment]
Interesting. We've seen something like that in some of our runscope tests but haven't narrowed it down. Is that a GET request that 502s?

**Comment by wetneb** [comment]
Hi @brianjgeiger. It's a POST request, and the code is here:
https://github.com/dissemin/dissemin/blob/master/deposit/osf/protocol.py#L214

**Comment by wetneb** [comment]
This seems to have been resolved, our tests are passing now. https://travis-ci.org/dissemin/dissemin
We will keep monitoring this and I'll reopen if the bug shows up again.
