### ISSUE TITLE
enhancement [hgrid] - bulk stop upload

### ISSUE THREAD

**Issue by asmacdo** [CenterForOpenScience/osf.io#758]
Related to https://github.com/CenterForOpenScience/openscienceframework.org/issues/754

If a user uploads a directory that contains many files, they should be able to stop all uploads. Currently, the user cannot stop uploads once they are in the queue and must delete them after the upload is complete.

This is particularly a problem if the user inadvertently adds a large file.

**Comment by nanchen47** [comment]
This has been fixed and no longer is a problem
