### ISSUE TITLE
Trouble connecting to live editor

### ISSUE THREAD

**Issue by jpkeith4** [CenterForOpenScience/osf.io#7596]
I am attempting to run a local instance of OSF and have been running into some trouble connecting the live editing mode.

The install is running on a Redhat7 server using docker as recommended, with Apache2 to proxypass subdomains to the various containers.
For live editing of documents it seems to require /sharejs/* to utilize regular HTTP so the client may download the needed javascript files "share.js" and "text.js"
But at the same time the websocket itself used for live editing seems to require /sharejs to utilize the websocket protocol

So we currently have it set up as follows:
ProxyPass /sharejs/ https://localhost:7007/
ProxyPass /sharejs ws://localhost:7007

This seems to both allow the downloading of files such as /sharejs/share.js, and also allows the websocket to successfully connect on /sharejs. However, we are still not able to actually make any changes to the document. Although the editor appears and we can see the documents text
 inside, trying to type in it or delete text doesn't do anything. The indicator in the top right just displays "Attempting to connect" indefinitely.
The only clue about what might be going on I can find is that the sharejs docker container outputs:
[Connection Closed] reason: 1001
I see no other errors in any of the other containers to go off of.
I'm not even completely sure if this is an error, is it supposed to happen? If so can you say where else I might look for the problem?
Is the apache setup described above correct, or is it possible that sending all /sharejs/* traffic through HTTP is somehow interfering with the websocket? Are there any other related configuration options you think might need to be set properly? Could this possibly be related to SSL, as we are currently running off of a self-signed certificate?

**Comment by alexschiller** [comment]
Hi @jpkeith4, while I'm unable to comment on the config, there is a known issue on the current develop branch that is causing sharejs to fail. 

I believe it was due to a node version update, but we are still looking into it. It is possible that downgrading the version or switching to the master branch might fix the error. If that doesn't work, I can contact someone who knows more about the devops setup.

**Comment by alexschiller** [comment]
Also, there is a Work in Progress PR that might allow you to stop the sharejs docker container and at least allow wiki editing to work without the collaborative aspect, though no guarantees. https://github.com/CenterForOpenScience/osf.io/pull/7599

**Comment by jpkeith4** [comment]
Thank you for the replies. I made a few changes and finally got a temporary workaround going.

One issue I solved might be relevant to the current sharejs build failing as you mentioned. I was seeing a module loading error for bson. I'm not sure how to go about fixing this before installation, but after the sharejs docker container has already been installed if I open a shell in it and go to file /code/node_modules/mongodb/node_modules/bson/ext/index.js
and modify the two lines which say `bson = require('../build/Release/bson');` to `bson = require('../browser_build/bson');` then it stopped giving the error.

Another issue I noticed was that the server was sending "localhost:7007" as the address for the client to connect to sharejs. I fixed that by changing lines 7 and 9 in file
https://github.com/CenterForOpenScience/osf.io/blob/3df745feae0236d174bc38f7d39d66175d9f1b68/addons/wiki/settings/defaults.py
to reflect the servers domain and just set SHAREJS_URL = SHAREJS_HOST`
to remove the port number from being sent to the client. I don't know if this is the right way to do it but it fixed that particular issue.

Then to finally get it working I noticed the callback function whenReady declared here:
https://github.com/CenterForOpenScience/osf.io/blob/develop/website/static/js/pages/ShareJSDocFile.js#L150
Was never being called, so I just added a direct call to whenReady() right below it and now the live editor is working.

**Comment by alexschiller** [comment]
Glad you got it working (at least temporarily). I'll pass this info on, thanks!

**Comment by binoculars** [comment]
I have a fix forthcoming in #7507. ShareJS doesn't play well with Node 8 yet.

**Comment by jpkeith4** [comment]
This now seems to be working for me in OSF version 0.120.0 (I was trying with 0.119.0 but was running into other issues preventing me from testing it).
So I think this issue can be closed.

**Comment by jpkeith4** [comment]
This seems to have been resolved in newer versions of OSF, so I'll close this issue.
