### ISSUE TITLE
treeData has no property "children"

### ISSUE THREAD

**Issue by jpkeith4** [CenterForOpenScience/osf.io#7742]
In OSF versions 0.119.0 and 0.120.28 I've been seeing an issue with storage services not being connected on the project page, including OSF storage. In the Javascript console it complains about "this.treeData.children" not existing in vendor.js
which is composed of the code from website/static/js/fangorn.js inside the function _loadTopLevelChildren(). It is called with this=tb.

If I add an if-statement to check whether the property "children" exists to allow the code to continue instead of crashing, I can verify that later on tb.treeData gets filled and has a "children" property. However at the stage where _loadTopLevelChildren() is called treeData is always empty and has no "children" property. I can't seem to find where treeData is supposed to be populated which might help to know what's causing the issue.

**Comment by sloria** [comment]
@jpkeith4 I believe this is fixed in our latest release. Feel free to re-open if the problem still exists.
