### ISSUE TITLE
Markdown renderer

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#795]
With the wiki refactor, and with the eventual addition of the Trello add-on, we will want to deal with Markdown in a consistent manner. Currently, the Wiki renders markdown both on the server and on the client. #624 #566 

Ideally, we should have one library. If we keep with Markdown for the wiki, my personal preference is to keep the Markdown on the server and render it only on the front-end. There might be some potential quirks with that, such as rendering changing when the plugin is updated (most of concern for Registrations), and potential client performance issues with large documents, but it makes sense as far as what things should do what.

The two aspects of this issue are:
1) Should we move Markdown to the front-end only;
2) Do we have preferences on an ideal Markdown library?

**Comment by nanchen47** [comment]
Talked with @brianjgeiger , This problem is solved.
