### ISSUE TITLE
Running initial migrations fails at step "osf.0024_migrate_subject_parents_to_parent.py"

### ISSUE THREAD

**Issue by abrinckm** [CenterForOpenScience/osf.io#8104]
The chief issue is that it appears the table 'osf_subject_parents' does not exist and cannot be found in any of the previous migration files. This causes migration 0024 to fail.

To give you some context into what we are doing I'd like to first point out that we are attempting to upgrade our local instance of OSF on our machine to the latest OSF release. This was a major upgrade from MongoDB to PostgreSQL. The data migration to copy everything from Mongo into Postgres seems to have been successful (using this [guide](https://github.com/CenterForOpenScience/osf.io/issues/7212#issuecomment-302228952))

After the data migration, we've pulled the latest release of osf.io from the develop branch and are attempting to run the django migrations.

Steps
-------
1. (after migration steps above)
1. git pull latest from the develop branch
1. manage.py migrate contenttypes
1. manage.py migrate auth
1. manage.py migrate osf

Expected
------------
I expect that the 'osf_subject_parents' table had been added in a previous migration.

Actual
--------
The 'osf_subject_parents' table and migration is "missing".

Probably what happened
--------
This table was added manually into postgres as I don't see a model for it either.

**Comment by mfraezz** [comment]
The `osf_subject_parents` table existed when `parents` was a `ManyToManyField` between `Subject` objects. It was created in `osf/migrations/0001_initial.py` with [this line](https://github.com/CenterForOpenScience/osf.io/blob/develop/osf/migrations/0001_initial.py#L879).

From an empty database:
1) Run the initial osf migration (and non-osf migrations it requires)
```
(osf) ~/D/osf.io ❯ python manage.py migrate osf 0001
[... info logs ...]
Operations to perform:
  Target specific migration: 0001_initial, from osf
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying osf.0001_initial...
  [... info logs ...]
   OK
```
2) Check what tables Postgres knows about:
```
osf=# SELECT tablename FROM pg_catalog.pg_tables WHERE tablename LIKE '%subject%';
      tablename
---------------------
 osf_subject
 osf_subject_parents
(2 rows)
```

It's possibly that specifying each app individually caused the migrations to run in an unexpected order. @abrinckm, to check what migrations have been ran and in what order, could you execute the following SQL?

```SQL
SELECT id, app, name
FROM django_migrations
ORDER BY id;
```

Alternatively, if you don't have any data you care about keeping, you can try using a fresh database and just let Django handle the migrations:
```
python manage.py migrate
```

**Comment by abrinckm** [comment]
Okay. I've felt it best to return to the state immediately after migrating to Postgres and ran 
`python manage.py migrate` as you suggested and the migrations ran successfully (it would seem). So I am closing this issue.
