### ISSUE TITLE
Dropbox outdated OAuth2 calls

### ISSUE THREAD

**Issue by jpkeith4** [CenterForOpenScience/osf.io#8159]
On a local installation of OSF I've been getting errors trying to connect dropbox. The issue seems to be that Dropbox has deprecated v1 and published this migration guide: https://www.dropbox.com/developers/reference/migration-guide

As you can see the first box shows the change in API addresses. However, my server is making v1 calls with the error:

    MaxRetryError: HTTPSConnectionPool(host='api.dropbox.com', port=443): Max retries exceeded with url: /1/oauth2/token (Caused by ProtocolError('Connection aborted.', error(99, 'Cannot assign requested address')))

Which contains a v1 call as displayed in the link.

Is this something I have to change on my end? I can't seem to find where these calls can be modified. I believe Dropbox removed those calls in September, and the versions of OSF I have been testing with are from December and January, so I'm wondering if it's just something I'm doing wrong as it seems to be working fine on osf.io.

**Comment by jpkeith4** [comment]
I have a workaround for this which seems to work for me:
First I just added `pip install dropbox --upgrade` to the command for the web container in docker-compose.yml
and then the following patch for addons/dropbox/models.py
https://gist.github.com/jpkeith4/141181d9a325d266e3a0161cbb2887a1

**Comment by felliott** [comment]
This will be fixed in an upcoming release.  PR #8200 implements this.

**Comment by sloria** [comment]
The fix has been released.
