### ISSUE TITLE
Cannot change email address associated with OSF account

### ISSUE THREAD

**Issue by eplebel** [CenterForOpenScience/osf.io#828]
And because of this, I cannot add an avatar (profile photo) to my account, because I no longer have access to the email address (i.e., elebel@uwo.ca) I used to sign up for the OSF.

**Comment by samanehsan** [comment]
Closing since users can now add multiple emails associated with their account on the OSF, and change which one of those emails is the "primary" email. Thanks again for reporting this issue @eplebel!
