### ISSUE TITLE
Owncloud Addon does not show files

### ISSUE THREAD

**Issue by mdehollander** [CenterForOpenScience/osf.io#8318]
I connected OSF with the Owncloud Addon to a folder on my own Owncloud instance. I can select a folder from the list. But in the Files Overview it does not show the actual files, but the refresh icon keeps spinning. Is there a know issue with connecting to a owncloud instance? I also don't see the OSF Addon mentioned on the status.cio.io page.

**Comment by saradbowman** [comment]
Hi @mdehollander, Thanks for getting in touch. Can you send us an email to support@osf.io so we can gather some more information from you and do some troubleshooting?

**Comment by mdehollander** [comment]
Here a screencast of the owncloud connection I am trying to make:

![osf-owncloud](https://user-images.githubusercontent.com/262872/46536174-f891c400-c8ad-11e8-8603-469c9b4735d8.gif)

**Comment by mdehollander** [comment]
I think it is a Owncloud (version) problem. I tried it now with a Nextcloud instance and it works ok.
![peek 2018-10-06 10-06](https://user-images.githubusercontent.com/262872/46569067-19125a80-c950-11e8-9266-e7b42c265def.gif)

**Comment by mdehollander** [comment]
The OSF team has narrowed the problem down to an issue at my owncloud provider stackstorage.com. OSF is expecting a 207 status code from a PROPFIND request, but a 200 status code is received.
Unfortunately, stackstorage.com is not able to look further into this problem. So therefore this issue is closed.

**Comment by mdehollander** [comment]
And thanks a lot OSF for spending time debugging this issue!
