### ISSUE TITLE
[merged-users] Should logs link to merged users?

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#834]
After a user has been merged, log events that refer to that user link to the merged user's profile. Should we instead link directly to the "master" user's (the user account who merged the old account) profile? This would involve modifying the logs in the database to point to the new user.

An alternative might be to redirect from the merged user's profile page to the master user's profile page after n seconds. This would avoid having to change the logs.

@JeffSpies @bnosek What are your thoughts on this?

Thanks @eplebel for bringing this to our attention.

**Comment by sloria** [comment]
@bnosek @JeffSpies Given that we will be exposing user merging to users within the next day or two, just want to make sure that the desired behavior is implemented.

Currently behavior on develop/staging: Logs still link to the merged user's profile. Since activity points are just log counts, activity points do not get transferred.

Please let I or @lyndsysimon know if changes to this behavior need to be made ASAP.

**Comment by JeffSpies** [comment]
And that profile links the user's actual profile?

**Comment by sloria** [comment]
@JeffSpies Correct. There is an alert at the top that the user's profile has been merged and links to the user's actual profile.

**Comment by bnosek** [comment]
This seems fine, particularly because we could always iterate to a
"stronger" merge by suppressing the merged user and combining the log
activity points if it made sense to do that someday.

**Comment by JeffSpies** [comment]
That's right. This is the iterative solution. Let's go with it.

**Comment by sloria** [comment]
Thanks for the feedback. Closing this for now.
