### ISSUE TITLE
Feature request: collaborative editing of documents on the OSF

### ISSUE THREAD

**Issue by samanehsan** [CenterForOpenScience/osf.io#839]
I think being able to collaboratively edit documents on the OSF would be a useful feature. I was talking to a member of the NRAO about this yesterday. He really likes Authorea (https://www.authorea.com/), a version-controlled collaborative writing tool for technical documents, and suggested that the OSF do something similar. Unfortunately, they do not have an API, but we could bring in this functionality using the Google Realtime API for collaborative editing. Maybe start by incorporating this into the Wiki editor?

**Comment by richardotis** [comment]
Authorea allows syncing article data to GitHub repos now: https://www.authorea.com/users/3/articles/17235/_show_article

It's possible to edit the file on OSF and propagate the changes back to GitHub, and ultimately back to Authorea, though it's not as nice as editing the rendered paper on the regular Authorea site.

**Comment by samanehsan** [comment]
This issue can be closed, since the OSF now supports collaborative editing of files and wiki pages!
