### ISSUE TITLE
Docker Container : osfio_registries_1 exited with code 127

### ISSUE THREAD

**Issue by HiroyukiNaito** [CenterForOpenScience/osf.io#8456]
osfio_registries_1 couldn't run with below error message.
How do I handle to fix this message?
```
$ docker-compose up registries
osfio_postgres_1 is up-to-date
osfio_rabbitmq_1 is up-to-date
osfio_elasticsearch_1 is up-to-date
osfio_api_1 is up-to-date
osfio_web_1 is up-to-date
Starting osfio_registries_1 ... done
Attaching to osfio_registries_1
registries_1        | yarn install v1.5.1
registries_1        | [1/4] Resolving packages...
registries_1        | success Already up-to-date.
registries_1        | Done in 2.12s.
registries_1        | /bin/bash: ./node_modules/.bin/bower: No such file or directory
osfio_registries_1 exited with code 127
```

**Comment by laurenbarker** [comment]
Thanks for the report @HiroyukiNaito!
 
We recently updated the registries app to only use npm but it looks like we missed a docker file. We'll update the file but it the meantime you can just remove the [bower install line from docker-compose.yml](https://github.com/CenterForOpenScience/osf.io/blob/develop/docker-compose.yml#L304) to prevent the error.
