### ISSUE TITLE
can't find any collection named 'tasks'!

### ISSUE THREAD

**Issue by ho9science** [CenterForOpenScience/osf.io#8467]
my env
>windows 10
>docker 18.03.0-ce

I was just follow [manual](https://github.com/CenterForOpenScience/osf.io/blob/develop/README-docker-compose.md)

but
In Running arbitrary commands, when I exec `docker-compose run --rm web python manage.py migrate`
I got this error
>"can't find any collection named 'tasks'!"

what can I do?

![image](https://user-images.githubusercontent.com/13064046/41650797-da3ae3b2-74b9-11e8-80b9-960f5d5e8e6d.png)

**Comment by HiroyukiNaito** [comment]
Have you executed before ```$ docker-compose up requirements mfr_requirements wb_requirements```?
```cp docker-compose.linux.yml docker-compose.override.yml```

**Comment by ho9science** [comment]
thanks.
I just miss
`$ cp docker-compose.linux.yml docker-compose.override.yml`
