### ISSUE TITLE
NameError: name 'n' is not defined

### ISSUE THREAD

**Issue by ho9science** [CenterForOpenScience/osf.io#8475]
my env
> windows10
> docker 18.03

An error occurred during execution according to the manual. **Application Runtime**
This error occurs when execute :
>$ docker-compose up -d assets

The logs are(docker-compose logs -f --tail 1000 assets):
>assets_1            | Traceback (most recent call last):
assets_1            |   File "/usr/local/bin/invoke", line 11, in <module>
assets_1            |     sys.exit(program.run())
assets_1            |   File "/usr/local/lib/python2.7/site-packages/invoke/program.py", line 286, in run
assets_1            |     self._parse(argv)
assets_1            |   File "/usr/local/lib/python2.7/site-packages/invoke/program.py", line 352, in _parse
assets_1            |     self.load_collection()
assets_1            |   File "/usr/local/lib/python2.7/site-packages/invoke/program.py", line 500, in load_collection
assets_1            |     coll = loader.load(coll_name) if coll_name else loader.load()
assets_1            |   File "/usr/local/lib/python2.7/site-packages/invoke/loader.py", line 53, in load
assets_1            |     module = imp.load_module(name, fd, path, desc)
assets_1            |   File "/code/tasks/__init__.py", line 1, in <module>
assets_1            |     n#!/usr/bin/env python
assets_1            | NameError: name 'n' is not defined

is it error in assets? or my env bug?

**Comment by slamdunking** [comment]
How is the ho science going besides that
