### ISSUE TITLE
Separated domain doesn't function proerly (Result in Unauthorized)

### ISSUE THREAD

**Issue by HiroyukiNaito** [CenterForOpenScience/osf.io#8493]
I separated api domain, ex) api.osf.xxx.jp, osf.xxx.jp.
How should I set for fake CAS?
It seems like the authentication state doesn't share so far.

```
http://api.osf.xxx.jp/v2/users/me/nodes/?related_counts=children&embed=contributors&version=2.2&fields%5Busers%5D=family_name%2Cfull_name%2Cgiven_name%2Cmiddle_names&fields%5Bcontributors%5D=bibliographic%2Cunregistered_contributor%2Cusers&fields%5Bnodes%5D=category%2Cchildren%2Ccontributors%2Ccurrent_user_permissions%2Cdate_modified%2Cdescription%2Cparent%2Cpublic%2Ctags%2Ctitle&_=1530096771720 401 (Unauthorized)

```

**Comment by HiroyukiNaito** [comment]
I am surveying continuously how to build OSF in a CORE (Cross Origin Recourse Sharing)  environments.
How can I find the settings documents?

**Comment by HiroyukiNaito** [comment]
I built CORS environment, but still receive 401 (Unautohrized) message from API server with following message.
```
HTTP 401 Unauthorized
Allow: GET, HEAD, OPTIONS
Content-Type: application/vnd.api+json
Vary: Accept
WWW-Authenticate: Documentation realm="api"

{
    "errors": [
        {
            "detail": "Authentication credentials were not provided."
        }
    ],
    "meta": {
        "version": "2.8"
    }
}
```
Would it be possible to tell me If you know how to build reverse proxy environment with Apatch or Nignx properly to circumvent this message?

**Comment by HiroyukiNaito** [comment]
I replaced fakecas with cas-overlay. However, still facing same results.
Is it a reverse proxy server problem? 
If possible, I 'd like to know reverse proxy setting for cas and cors environment.

**Comment by icereval** [comment]
@HiroyukiNaito,

We are not applying any special configurations to NGINX for CORS support.  If you would like to review our configurations you can find them here: ([web](https://github.com/CenterForOpenScience/helm-charts/blob/master/osf/templates/configmap.yaml#L508)) ([api](https://github.com/CenterForOpenScience/helm-charts/blob/master/osf/templates/configmap.yaml#L180))

Here are a few items that come to mind that you'll want to check:

1. The OSF cookie configuration is setup for sub-domain support (has a `.` at the beginning).

e.g. from [defaults.py](https://github.com/CenterForOpenScience/osf.io/blob/develop/website/settings/defaults.py#L121-L123) (the `.`. is very important)
```py
COOKIE_NAME = 'osf'
OSF_COOKIE_DOMAIN = '.osf.io'
```

2. Are you making the request w/ `credentials: true`?
* `XMLHttpRequest ` uses the [`withCredentials` property](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials)
* `fetch` requires the [init parameter `credentials: include`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Parameters)

**Comment by HiroyukiNaito** [comment]
@icereva , 

I could fix this problem through [1.] solution you suggested to `./website/settings/local-dist.py` at this time.

<pre>
COOKIE_NAME = 'osf'
OSF_COOKIE_DOMAIN = '.osf.io'
</pre>

Thank you very much!

**Comment by icereval** [comment]
Awesome!
