### ISSUE TITLE
[Increasing engagement] feature request - extending badges for open practices to OSF usage

### ISSUE THREAD

**Issue by AndrewSallans** [CenterForOpenScience/osf.io#852]
Logging for the future...

Like in many systems, users would be awarded badges for hitting certain milestones, thereby increasing user engagement.  This would extend off of the badges for open practices effort:  https://osf.io/tvyxz/

Examples:
-1, 10, 25, 50, 100 projects created
-1, 10, 25, 50, 100 registrations
-1, 3, 5, all add-ons configured
-when baked badges are implemented, then 1, 3, 5, 10, etc. meta-badges for open data, open materials, preregistration

**Comment by GaryKriebel** [comment]
Closed
