### ISSUE TITLE
[filebrowser] Don't expand folders on load

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#856]
The filebrowser will automatically open all first-level folders and addons upon loading the page. A number of people (incl @csoderberg and @jmcarp) have brought up independently that this can be an annoyance when trying to find files at the top level. 

This is an easy change to make. Should we move forward with this?

**Comment by caneruguz** [comment]
@lbanner @GaryKriebel ; it may be time to revisit this issue. Treebeard is in place and the current behavior does open top level folders.

**Comment by lbanner** [comment]
OK -- I prioritized 'high' so we might remember to engage this conversation again. TY

**Comment by haoyuchen1992** [comment]
So currently when user opens project, the file will be expanded at the first level (See picture below). So does it mean the problem has been solved?

![screen shot 2015-06-25 at 4 28 45 pm](https://cloud.githubusercontent.com/assets/5420789/8364909/9135b66a-1b57-11e5-8416-ba949deccc47.png)

Similar as this issue, I think we should also expand the projects on the dashboard page. Every time I want to open a project, I have to expand the project file tree and then click the one I want to visit(See picture below). That happens to every user.  
![screen shot 2015-06-25 at 4 34 17 pm](https://cloud.githubusercontent.com/assets/5420789/8364974/11157cbc-1b58-11e5-95f3-5af982305274.png)

It may be better to expand the first level of project folder when loading the page (See picture below).
![screen shot 2015-06-25 at 4 28 08 pm](https://cloud.githubusercontent.com/assets/5420789/8364996/40e204e2-1b58-11e5-9d32-a88de87f7886.png)

Any comments? Once the decision is made, I could work on it! Thanks!

**Comment by GaryKriebel** [comment]
@sloria was this to do with just "folders" or the addons themselves?

Currently, folders within the addon don't expand but the top-level addons do.
![screen shot 2015-06-25 at 4 43 51 pm](https://cloud.githubusercontent.com/assets/9437946/8365174/6dd40c42-1b59-11e5-8aa5-41edd6d0b5f7.png)

**Comment by haoyuchen1992** [comment]
I think I made mistake in last comment. Considering some collections and projects could be displayed in top level of dashboard. If `all my projects` expand at the beginning, use would be hard to find the items originally below `all my projects`.

So it may be better to make a small expanded list that contains the most or recently visited projects.

**Comment by lbanner** [comment]
Interesting approach -- thoughts @caneruguz ? I'd like @jlcohoon 's further thoughts too.

**Comment by brianjgeiger** [comment]
The proper solution for this problem is #3054

**Comment by jinluyuan** [comment]
Could the "Collapse all folders" idea from https://github.com/CenterForOpenScience/osf.io/issues/743 be an answer for the question of whether expanded or collapsed folders is better? Users who want to search through their top level folders can do so by clicking "Collapse all folders", but users who need to interact with files multiple times will still have the benefit of default expanded top-level folders.

**Comment by caneruguz** [comment]
@lbanner I think the original issue was a short term solution and Steve asked whether it's better to load with folders open or closed and Brian said it's better to have them open in the short term although that's also not ideal. I think BrianG's suggestion of #3054 is the right way to go. 

My recommendation is that this issue should be closed and discussion should happen at #3054. @sloria ?

**Comment by lbanner** [comment]
Agreed .. closing in favor of forward movement on #3054
