### ISSUE TITLE
[dev] [migration] Find and handle components with no parent project

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#874]
There are a few components on production that do not have a reference to a parent project. This results in a 500 error when trying to access those components.

We need to find these corrupted components and ensure that their parent projects have proper references to them. 

@jmcarp has done much of the work for finding affected components in this script: https://github.com/CenterForOpenScience/osf/blob/master/scripts/consistency/find_bad_children.py

The next step is to actually find the parents of these nodes. This might be done by inspecting the logs associated with these components.

```python
# the params may have a 'project' key, which will be the GUID of the parent project
orphaned_component.logs[0].params['project']
```

Once a parent is found, the component should be added to the `nodes` field of the parent.

```python
parent.nodes.append(orphaned_component)
parent.save()
```

@samanehsan @caseyrollins , and/or @ericanbaranski : Could you please work on updating the `find_bad_children.py` script to migrate the affected components? The updated script should follow the guidelines in the dev docs: http://cosdev.readthedocs.org/en/latest/osf/migrations.html

**Comment by GaryKriebel** [comment]
@sloria is this still an issue?

**Comment by nanchen47** [comment]
Will be considered based on user's feedback.
