### ISSUE TITLE
[staging: 2-factor] What should happen when person enters data and two-factor is not enabled?

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#879]
Right now, the most sensible thing occurs -- the 2-factor code is ignored and the person is logged in as long as they enter the correct password.

The only user experience oddity that comes to mind is the user who does not have two-factor enabled but types in something to see what happens.  The fact that nothing happens might be experienced as "their two-factor solution doesn't work, I entered garbage and still got in."

I don't know if this justifies adding an alert that two-factor is not enabled, but it was the only issue I generated during testing.

**Comment by HarryRybacki** [comment]
This will no longer be an issue after PR #1728 is merged and the two factor field is removed from the login page.

**Comment by samanehsan** [comment]
@lbanner @GaryKriebel, might we remove the "ready" label on this? The PR @HarryRybacki mentioned is merged onto staging and resolves this issue.

**Comment by lbanner** [comment]
Yep @samanehsan -- updated, thank you.

**Comment by HarryRybacki** [comment]
PR #2007 is the updated version that will resolve the issue.

**Comment by samanehsan** [comment]
This has been resolved by the new login form, which does not have a field to enter two-factor auth by default.
