### ISSUE TITLE
Not possible to add all authors to a preprint

### ISSUE THREAD

**Issue by moorepants** [CenterForOpenScience/osf.io#8879]
It seems the website requires all authors to have accounts to be listed as a preprint author. We should be able to add authors to preprints without having them make an account on the service. The current setup even tries to force you to invite them to OSF. This is a less-than-ethical tactic and really turned me off.

**Comment by devinberg** [comment]
This is a good point. I'd also like to know if the emails collected are harvested for solicitations without giving those co-authors a chance to opt-out first.
