### ISSUE TITLE
502 error from file retrieve endpoint when passed a user ID

### ISSUE THREAD

**Issue by aaronwolen** [CenterForOpenScience/osf.io#8888]
This is _definitely_ an edge case but wanted to point it out. Passing an existing user's GUID to the file retrieval endpoint throws a 502 error without a JSON response. 

Example:

```sh
curl -X GET --silent https://api.osf.io/v2/files/c28dr/
```

```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by sloria** [comment]
Thanks for reporting! I've filed this in our internal tracker. We'll look into the fix.
