### ISSUE TITLE
Change Text to Prompt Users to Fill Out Profile Upon Claiming Account

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#889]
When a user claims an account, they are taken to the Account Settings page and prompted with, "Welcome to the OSF! Edit your display name below." Changing this text to also prompt them to fill out their profile information will directly support our 3-month goal of raising the number profile updates to 500.

**Comment by saradbowman** [comment]
I want to ping on this again, as it's becoming increasingly important to know what our user base looks like. We get frequent questions from outside groups about this.

It would be very helpful to have profile information to be able to search, but few users have filled out profile information. It's unclear if this is because users do no want to fill out profile information or because they're not aware this is an option. Wondering on status of this?

**Comment by erinmayhood** [comment]
@saradbowman I believe we have addressed this with the new onboarding process.
