### ISSUE TITLE
Automatically link email addresses in wiki pages

### ISSUE THREAD

**Issue by lyndsysimon** [CenterForOpenScience/osf.io#89]
This enhancement proposal comes out of #82.

When a user enters and email address or a url in a wiki page, they could be automatically turned into links on the rendered page. This would require no interaction on the part of the user, although perhaps we should consider providing a means through which the user may explicitly mark up a string so a link would not be created.

**Comment by lbanner** [comment]
@brianjgeiger -- Think this remains a desired functionality? TY

**Comment by brianjgeiger** [comment]
Not at this point. If people want links to autolink, the Commonmark standard says to put them in angle brackets. This includes email addresses.

![screen shot 2015-04-15 at 10 47 22 am](https://cloud.githubusercontent.com/assets/6599111/7161413/ed0ef6be-e35c-11e4-9e13-d968a3bab3c2.png)

**Comment by lbanner** [comment]
Great!
