### ISSUE TITLE
[production] Comment option should appear on all of the project pages, not just Project Summary

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#897]
e.g., here:

![screen shot 2014-09-06 at 8 09 47 am](https://cloud.githubusercontent.com/assets/1761504/4175097/dcf48dc6-35be-11e4-950b-2048d31b4840.png)

![screen shot 2014-09-06 at 8 10 02 am](https://cloud.githubusercontent.com/assets/1761504/4175100/e01dafdc-35be-11e4-8cae-a6ff56b09c3b.png)

**Comment by samanehsan** [comment]
Comment panes will be added to all files and wiki pages in PR #2534, and there will be an interface for viewing all of the comments across the project.
