### ISSUE TITLE
Unwanted information added when uploading a text file from the WaterButler API

### ISSUE THREAD

**Issue by HiroyukiNaito** [CenterForOpenScience/osf.io#8979]
When I upload a text file from the WaterButler API, additional information is added to a text file automatically with following procedure. 
How I can avoid this phenomena? or is it a bug?

## Upload file
- File name: test.txt
```vi
test test test test test
test test test test test
test test test test test
test test test test test
test test test test test
```
## Upload command
```shell
curl -X PUT  \
-H  "Content-Type: text/plain" \
-F "file=@./test.txt" \
"https://files.osf.io/v1/resources/[Project id]/providers/osfstorage/?name=test.txt&kind=file" \
-H  "Authorization: Bearer [Token]" 
```
## Upload results
```vi
--------------------------770601d2d8e88898
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

test test test test test
test test test test test
test test test test test
test test test test test
test test test test test


--------------------------770601d2d8e88898--
```
## Screen shot
![image](https://user-images.githubusercontent.com/32320988/54574070-3fc1da80-4a32-11e9-9fba-39fbb5752f78.png)

**Comment by felliott** [comment]
Hey @HiroyukiNaito,

WaterButler expects the body of the request to have the raw data for upload, i.e. *not* form-encoded.  Try this:

**Comment by felliott** [comment]
Sorry, hit return too fast.  Response amended above.

**Comment by HiroyukiNaito** [comment]
Hi @felliott,

It woked out completely.
Thank you!

Regards,
@HiroyukiNaito
