### ISSUE TITLE
Removal debian jessie from mirrors

### ISSUE THREAD

**Issue by fujimotodaisuke** [CenterForOpenScience/osf.io#8986]
An error occurred when building osf.io with docker build command.

    Step 3/62 : RUN set -ex     && mkdir -p /var/www     && chown www-data:www-data /var/www     && apt-get update     && apt-get install -y gnupg2     && for key in       B42F6819007F00F88E364FD4036A9C25BF357DD4       9554F04D7259F04124DE6B476D5A82AC7E37093B       94AE36675C464D64BAFA68DD7434390BDBE9B9C5       FD3A5288F042B6850C66B31F09FE44734EB7990E       71DCFD284A79C3B38668286BC97EC7A07EDE3FC1       DD8F2338BAE7501E3DD5AC78C273792F7D83545D       B9AE9905FFD7803F25714661B63B535A4C206CA9       C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8       56730D5401028683275BD23C23EFEFE93C4CFFFE       6A010C5166006599AA17F08146C2130DFD2497F5     ; do       gpg --keyserver hkp://ipv4.pool.sks-keyservers.net:80 --recv-keys "$key" ||       gpg --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys "$key" ||       gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys "$key" ||       gpg --keyserver hkp://keyserver.pgp.com:80 --recv-keys "$key"     ; done     && apt-get install -y         git         libev4         libev-dev         libevent-dev         libxml2-dev         libxslt1-dev         zlib1g-dev         curl         build-essential         libssl-dev         libffi-dev         python-dev         libpq-dev         par2     && ARCH=     && dpkgArch="$(dpkg --print-architecture)"     && case "${dpkgArch##*-}" in       amd64) ARCH='x64';;       ppc64el) ARCH='ppc64le';;       *) echo "unsupported architecture"; exit 1 ;;     esac     && curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"     && curl -o /usr/local/bin/gosu.asc -SL "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"     && gpg --verify /usr/local/bin/gosu.asc     && rm /usr/local/bin/gosu.asc     && chmod +x /usr/local/bin/gosu     && curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$ARCH.tar.xz"     && curl -SLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc"     && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc     && grep " node-v$NODE_VERSION-linux-$ARCH.tar.xz\$" SHASUMS256.txt | sha256sum -c -     && tar -xJf "node-v$NODE_VERSION-linux-$ARCH.tar.xz" -C /usr/local --strip-components=1     && rm "node-v$NODE_VERSION-linux-$ARCH.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt     && ln -s /usr/local/bin/node /usr/local/bin/nodejs     && curl -fSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz"     && curl -fSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz.asc"     && gpg --batch --verify yarn-v$YARN_VERSION.tar.gz.asc yarn-v$YARN_VERSION.tar.gz     && mkdir -p /opt/yarn     && tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/yarn --strip-components=1     && ln -s /opt/yarn/bin/yarn /usr/local/bin/yarn     && ln -s /opt/yarn/bin/yarn /usr/local/bin/yarnpkg     && yarn global add bower     && yarn cache clean     && rm -rf         yarn-v$YARN_VERSION.tar.gz.asc         yarn-v$YARN_VERSION.tar.gz         $HOME/.gnupg         $HOME/.cache     && apt-get remove -y         curl     && apt-get clean     && apt-get autoremove -y     && rm -rf /var/lib/apt/lists/*     && mkdir -p /code
     ---> Running in 7e7ceca49f99
    + mkdir -p /var/www
    + chown www-data:www-data /var/www
    + apt-get update
    Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
    Ign http://deb.debian.org jessie InRelease
    Ign http://deb.debian.org jessie-updates InRelease
    Get:2 http://deb.debian.org jessie Release.gpg [2420 B]
    Ign http://deb.debian.org jessie-updates Release.gpg
    Get:3 http://deb.debian.org jessie Release [148 kB]
    Get:4 http://security.debian.org jessie/updates/main amd64 Packages [822 kB]
    Ign http://deb.debian.org jessie-updates Release
    Get:5 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
    Err http://deb.debian.org jessie-updates/main amd64 Packages
      
    Err http://deb.debian.org jessie-updates/main amd64 Packages
      
    Err http://deb.debian.org jessie-updates/main amd64 Packages
      
    Err http://deb.debian.org jessie-updates/main amd64 Packages
      
    Err http://deb.debian.org jessie-updates/main amd64 Packages
      404  Not Found
    Fetched 10.1 MB in 6s (1593 kB/s)
    W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found
    
    E: Some index files failed to download. They have been ignored, or old ones used instead.

Debian jessie-updates seems to have been removed from the mirrors.
https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

**Comment by rija** [comment]
Hi,
everyone who use Jessie as base image for their container is affected.
Examples of how it has been fixed on other projects:
* https://github.com/circleci/circleci-images/pull/368
* https://github.com/gigascience/gigadb-website/issues/296#issuecomment-476579106

Hope it helps.

**Comment by mfraezz** [comment]
This has been fixed via 234b60547c4d1a813939367c097afdbb267389c7, 9f6af57db559ffae4d46307b18db485191760683, and 7c90b1dd035847d80cb62ff99e00902751337b7b. Thanks for reporting it 🍡
