### ISSUE TITLE
Download link blocked by ublock origin

### ISSUE THREAD

**Issue by rgieseke** [CenterForOpenScience/osf.io#9007]
I was looking for a download link on e.g. https://osf.io/preprints/socarxiv/ghb4p/ and finally noted that it was blocked by https://github.com/gorhill/uBlock/

Disabling the blocker is of course possible but maybe there is a way to code the osf site to avoid this?

Ublock origin is blocking Google Analytics and Keen.io.

**Comment by mfraezz** [comment]
Default uBlock settings on Chrome, MacOS, didn't cause this behavior for me; it only blocked GA and Keen. 

Can you include any logs, screenshots, or system information, @rgieseke?

**Comment by rgieseke** [comment]
Gotcha! It was an overzealous `.share-row` in the extra Fanboy Annoyance list it seems …

I had forgotten i had added those additional filters so thought this might affect more visitors of OSF/ArXiv (who likely use an adblocker).

Sorry for the noise!
