### ISSUE TITLE
[Production] Black Navigation Bar Obscures Text for Anchors in Wiki

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#902]
Reference #593 

Clicking on a link to an anchor takes the user to the anchor, but the black (OSF) navigation bar covers the first few lines of text below the anchor. See example: https://osf.io/r9pqe/wiki/home/ (The links for questions 1A, 1B, and 2A refer to anchors below, placed before question/answers 1A, 1B, and 2A, respectively).

Can an offset be applied so that the anchor appears below the black navigation bar?

**Comment by HarryRybacki** [comment]
@GaryKriebel can we close this out?
