### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#906]
Instead of going to the help tab and clicking either Contact or Email Support and having an email application pop up with a pre-populated email field, I think it would be helpful to be redirected to a page with contact information on it. That's what I expected would happen when I clicked on Contact or Email Support. Another option that Lyndsy suggested is having a pre-populated email modal where users can enter a subject and a message and the email is sent to an osf address upon pressing submit. 

It just feels strange to me that there is no email listed on the site at all. I personally never use email applications, so it is annoying to have them pop up because I just end up having to copy the email address and paste it into my gmail email account online. 

We might also be able to consolidate Contact and Email Support into one page. It is not immediately clear to me what the difference is, besides the emails being sent to different addresses. If we have a page, we could say something like "If you are having trouble with XYZ, contact us at email support here" or "To find out more information about us, send us a contact email here." Not those words obviously, but some description so that it's more obvious which email address to send different emails to.

**Comment by nanchen47** [comment]
Will be considered in the interface refactor. Thanks.
