### ISSUE TITLE
Add unregistered user is sometimes non-responsive

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#913]
It appears to occur immediately following adding a contributor that is in the system.  I have not yet confirmed the addition, but try to add another person that is unregistered, when I click add - nothing happens.

![screen shot 2014-09-14 at 2 28 14 pm](https://cloud.githubusercontent.com/assets/1761504/4265046/16c1670c-3c3d-11e4-9007-7407a48e8c99.png)

**Comment by samanehsan** [comment]
This issue is the same as #2317, which has been resolved.
