### ISSUE TITLE
Lists of projects load very slowly when lots of projects exist

### ISSUE THREAD

**Issue by zoidy** [CenterForOpenScience/osf.io#9158]
For users with many projects, the projects list loads very slowly. E.g., for a list of about 30 projects, the My Projects page takes more than a minute to fully load.  

For an institutional portal with about the same number of projects, the project list takes about 30 seconds to load (sometimes the list fails to load at all, the message "fetching more projects" appears perpetually).

**Comment by Johnetordoff** [comment]
This has been changed to only load a partial list of projects. Please contact us if you experience more issues.
