### ISSUE TITLE
Improve interface for renaming wiki pages

### ISSUE THREAD

**Issue by lyndsysimon** [CenterForOpenScience/osf.io#922]
Renaming wiki pages (added in #416) is not in an obvious place, and is likely to be overlooked by users.

![screen shot 2014-09-16 at 11 07 17 am](https://cloud.githubusercontent.com/assets/131414/4289447/b2e266b4-3db3-11e4-8c96-3e3979a20dfa.png)

The interface for renaming a wiki page should be changed to an obvious input box when the use is on the *Edit Wiki Page*.

**Comment by samanehsan** [comment]
The wiki interface has changed significantly, so this is no longer an issue. With the current interface, the wiki title is in a prominent location and can be edited by clicking on it: 
![screen shot 2015-04-14 at 11 16 27 am](https://cloud.githubusercontent.com/assets/6414394/7145061/8e4aefac-e2b7-11e4-954f-b68d6020c51c.png)
