### ISSUE TITLE
A node with subcomponents cannot be directly deleted via API

### ISSUE THREAD

**Issue by aaronwolen** [CenterForOpenScience/osf.io#9252]
According to the change log, as of version 2.12

> DELETE requests to a node detail will also delete all the node's subcomponents

but that doesn't appear to the case. When attempting to delete a project with a single subcomponent

```sh
curl -X DELETE "https://api.osf.io/v2/nodes/8xc9y/" -H "Authorization: Bearer $PAT"
```

the following error is thrown

```son
{
  "errors": [
    {
      "detail": "Any child components must be deleted prior to deleting this project."
    }
  ],
  "meta": {
    "version": "2.0"
  }
}
```

Am I missing something or misinterpret the docs?

**Comment by brianjgeiger** [comment]
It's because you're using version 2.0 of the API rather than version 2.12 or later. https://developer.osf.io/#tag/Versioning should get you the rest of the way there.

**Comment by aaronwolen** [comment]
Thanks, Brian.

I can confirm it works as expected when the version is pinned using a query parameter but I hit the same problem when using header-based versioning

```bash
curl -X DELETE "https://api.osf.io/v2/nodes/hrbkg/" \
     -H "Authorization: Bearer $PAT" \
     -H "Accept-Header: application/vnd.api+json;version=2.12"
```

**Comment by brianjgeiger** [comment]
What do you get in the `meta.version` section of the API response? Still '2.0'?

**Comment by brianjgeiger** [comment]
Ah, I think the header is supposed to be `Accept` and not `Accept-Header`. We will need to change our documentation.

**Comment by aaronwolen** [comment]
Changing `Accept-Header` to `Accept` did the trick! Thanks!
