### ISSUE TITLE
Feature: Non-modal JS Error reporting

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#928]
There are times when might I need to show an arbitrary number of errors at once, and our current error reporting won't work well for that. We should have a non-modal solution for easily showing errors. Currently we are showing a bootbox. If we used an equivalent plugin to do alerts instead of dialog boxes, the interface would be much nicer. Alternately, a fancier growl-style notification would do, but bootstrap alerts would be serviceable.

**Comment by samanehsan** [comment]
Closing this since we now use growl-style notifications on the osf.
