### ISSUE TITLE
Use the poster attribute for videos hosted on OSF

### ISSUE THREAD

**Issue by allsey87** [CenterForOpenScience/osf.io#9373]
To save a lot of OSF bandwidth and to speed up the loading of content, I would strongly suggest the use of the `poster=path/to/poster.png` and `preload="none"` attributes of HTML video nodes. This would impact the video preview panel when browsing project files and also videos embedded in the wiki using the `@[osf](GUID)` method.

It would also be nice if eventually the poster images could be selected by the users when uploading video files, but I would say this is lower priority for now.

**Comment by Johnetordoff** [comment]
@allsey87 Thanks, this is a nice optimization suggestion, but this issue belongs in our markdown-it-video repo at https://github.com/CenterForOpenScience/markdown-it-video.

**Comment by allsey87** [comment]
Ok, I recreated the issue over there and will close this one
