### ISSUE TITLE
gitlab addon lists only 20 repositories max

### ISSUE THREAD

**Issue by simoncarrignon** [CenterForOpenScience/osf.io#9444]
When connecting a Gitlab account, only the 20 last repositories are listed, which is a bit annoying when you have more than that, as It means that I need to create a new gitlab account to access my oldest repository.

I guess this is that way as it is the default behavior of [python-gitlab API wrapper](https://github.com/python-gitlab/python-gitlab) function: `projects.list()`, as described in [the documentation of python-gitlab](https://github.com/python-gitlab/python-gitlab/blob/dad505c5e6aac3081ed796227e8f21d28b217ea0/docs/gl_objects/projects.rst). Strangely if the [gitlab API documentation](https://docs.gitlab.com/ee/api/projects.html) doesn't mention that limit for project listing, it does mention it when describing call for [repository listing](https://docs.gitlab.com/ee/api/repositories.html) and the `pyhthon-gitlab` doc mentions it here:
![image](https://user-images.githubusercontent.com/4749455/88568472-540be380-d039-11ea-906c-52edee08d4ca.png)
 

Is there a reason to keep that? There is no such limit when linking a github account.  I _guess_ (but haven't tried) this would be easily solved by simply replacing:  `projects.list()` by `projects.list(all=True)`. in the function `repos()` defined in [here in api.py](https://github.com/CenterForOpenScience/osf.io/blob/57c7e6c545fdae1798ef019eca7106d5a7124dcd/addons/gitlab/api.py#L58). 
Would love to try this myself but not sure it's worth it trying to install a full osf.io instance just to test that...

**Comment by mfraezz** [comment]
Thanks for the report, @simoncarrignon. The hotfix should be live now. 🌶️

**Comment by Matherion** [comment]
It _is_! For me at least! AWESOME! 🤩 Thank you very much, both of you!!! 🙏 👍

**Comment by simoncarrignon** [comment]
awesome, works for me too
