### ISSUE TITLE
[ui] When user creates a new component, set focus in title automatically

### ISSUE THREAD

**Issue by csheldonhess** [CenterForOpenScience/osf.io#954]
This is a pretty minor thing, basically just a nicety.

When a user goes to create a new component inside a project, a dialog box (modal?) comes up.
![image](https://cloud.githubusercontent.com/assets/3027971/4325765/818002b4-3f68-11e4-97d1-8f564c319226.png)

Focus should be set into the Component Title so that they can just start typing without having to click again.

**Comment by haoyuchen1992** [comment]
This is a small but good UI improvement. I can work on it! Thanks :)
