### ISSUE TITLE
[staging] Feature request: reorganizing folders in Project Organizer

### ISSUE THREAD

**Issue by csheldonhess** [CenterForOpenScience/osf.io#963]
It would be really nice to be able to change the order of folders in the Project Organizer, directly, via drag-and-drop.

Right now, when a user makes a new folder it ends up on top of their folder list. It *is* possible to reorganize them via a workaround (drag the folder you want to be on the top of the list into another folder; now, drag it back into Dashboard, and, bam, it's on top). But it's not immediately obvious that this is how it's done, so I predict there will be users who think they can't reorganize their folders.

**Comment by erinmayhood** [comment]
Addressed in redesign of project organizer.
