### ISSUE TITLE
github addon: Deprecating OAuth Application API in May.2021

### ISSUE THREAD

**Issue by ebijun** [CenterForOpenScience/osf.io#9676]
github changes API in May.2021,
github addon support for newer APIs?

https://developer.github.com/changes/2020-02-14-deprecating-oauth-app-endpoint/

addons/github/requirements.txt uses github3.py 1.0.0a4.
more newer github3.py 2.0.0,but not support newer API.

**Comment by nevrome** [comment]
I think it's broken now - I can not get it to work any more.

**Comment by Johnetordoff** [comment]
@nevrome It should work now.

**Comment by ebijun** [comment]
https://github.com/CenterForOpenScience/osf.io/commit/a39923392aa7da716b23efd12bf7bcbbf19bb573
Thanx!
