### ISSUE TITLE
Public, visitable registration is listed as embargoed with no end date

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#9721]
Steps
-------
1. Visited public project 
2. Clicked on registrations of that project (https://osf.io/jt652/registrations)
3. Clicked on title of embargoed registration
4. Clicked on embargo information dropdown under registration title.

Expected
------------
Expected embargoed registration wouldn't be click-onable/visitable. When it was anyway, I expected to be brought to a page with minimal info that indicated that parts of the registration weren't available because it was embargoed. When clicking on the embargo information dropdown (step 4 above), I expected to see the date the project was embargoed until; given the information just summarized, I considered it possible the embargo had ended.

Actual
--------
Embargoed registration could be visited and information like attached files was available. The dropdown did not give the date that the registration was embargoed until (see screenshot below). 

<img width="299" alt="Screen Shot 2021-06-28 at 10 06 00 AM" src="https://user-images.githubusercontent.com/4965832/123660340-315dee00-d7f9-11eb-8a56-121c837400cb.png">

**Comment by brianjgeiger** [comment]
Hi, @jlcohoon,

The 'embargoed' state was shown in error; it should have shown that it was public. This issue has been resolved to the best of our knowledge, and the existing registrations that were affected have been fixed. If you see this again, please let us know.
