### ISSUE TITLE
[project-organizer] Highlight bar sometimes eclipses icons below it

### ISSUE THREAD

**Issue by rliebz** [CenterForOpenScience/osf.io#973]
The highlight bar sometimes eclipses the new icons below it, but not always. It appears to occur only for the first subproject or subcomponent listed, and is reliably occurring for the same items, even after page refresh.
![screen shot 2014-09-22 at 2 29 13 pm](https://cloud.githubusercontent.com/assets/5321575/4361721/91d3e8ee-4286-11e4-828a-07e4f24fd799.png)
This occurs on OSX Mavericks in Chrome, but not Safari. In Safari, the row elements are spread out far enough that if this issue existed, it would not have the opportunity to manifest itself.

**Comment by caneruguz** [comment]
@lbanner this issue should be closed, it is not relevant with the new Treebeard implementation.

**Comment by lbanner** [comment]
Thanks!
