### ISSUE TITLE
[project-organizer] Pseudo-button in Info column display issues

### ISSUE THREAD

**Issue by rliebz** [CenterForOpenScience/osf.io#975]
There are some minor display issues I’m noticing with using buttons that are styled to not look like buttons in the info column. Chiefly, an off-center white square background shows up when the row is highlighted, and when the button is clicked, this square itself is highlighted in a way that only really makes sense for a full button. 
![screen shot 2014-09-22 at 2 46 50 pm](https://cloud.githubusercontent.com/assets/5321575/4362050/ea9b9640-4289-11e4-9052-2ef68bb3256f.png)

**Comment by caneruguz** [comment]
@lbanner This issue is also not relevant anymore, does not happen with Treebeard.

**Comment by lbanner** [comment]
Thanks!
