### ISSUE TITLE
Explore projects by tags

### ISSUE THREAD

**Issue by rubenarslan** [CenterForOpenScience/osf.io#98]
At the moment tags are pretty much unused - it would make sense to let users browse through public projects by tags.

**Comment by fabianvf** [comment]
Has this been covered by one of the search updates that went through in the last few months?

**Comment by brianjgeiger** [comment]
With the recent search updates, any search will show the top tags related to that search, and you can browse those projects by clicking on the tags. If you wanted to start with everything on the site, you could search for *. Is this kind of what you were thinking, @rubenarslan?

![screen shot 2015-01-30 at 4 07 37 pm](https://cloud.githubusercontent.com/assets/6599111/5983365/8cd71ef4-a89a-11e4-8e2a-e2127f178e70.png)

**Comment by rubenarslan** [comment]
I honestly don't remember if this is what I wanted, I asked that question more than a year ago :-)
If you're interested in my opinion now: I doubt many people will have the idea to enter `*` to idly browse. And I think many people want to "check out how others are using the OSF" real quick. At the moment the only direct links to real projects from the front page are the reproducibility projects which are a bit intimidating if you're looking for something to emulate. 
Clicking "Explore" at the bottom or choosing the first item at the top leads you to a pretty but pretty useless bubble plot of collaborators without names and links (which slows my Firefox to a crawl). Maybe the public activity page would be a nicer default and maybe you could add "Popular tags" to that.

Also, apparently you base popularity on views in the last week. I think the intention is that it should show "trending" projects (and maybe it shouldn't turn into a self-fulfilling prophecy). However, for "public registrations" there are only two included with one view each. So it seems the cutoff isn't really relevant at current activity levels.

So much criticism, apologies! I really like the new search interface though.

**Comment by lbanner** [comment]
That is great feedback @rubenarslan -- Thank you!

**Comment by Ghalko** [comment]
Just an idea: http://internet-map.net/
Looks like it is preprocessed. Could be based on tags, allowing people to click on the circles and get a list of projects in the circle.

**Comment by lbanner** [comment]
Sure looks pretty @Ghalko -- want to take a wee bit-o-time to understand how to make that happen?

**Comment by Ghalko** [comment]
Getting into D3
Notice the first link has lots of bubbles but doesn't slow down the browser.
http://www.nytimes.com/interactive/2012/02/13/us/politics/2013-budget-proposal-graphic.html?_r=0
http://www.infocaptor.com/bubble-my-page?url=osf.io&size=800

And we need to find a way to do something similar with contributions: http://mbtaviz.github.io/

http://bl.ocks.org/kerryrodden/477c1bfb081b783f80ad
I really like this last one. Wouldn't mind some pointers on how to get tooltips.

**Comment by jlcohoon** [comment]
Exploring collaboration networks by forks would also be helpful, and would likely increase the use of that feature. Right now, there is no way (to my knowledge) to find which projects are forks of others, and there is definitely no visualization of that collaboration network. <a href="https://osf.io/wfc6u/">One project on the OSF</a>, in particular, uses forking often, and would likely benefit a lot from surfacing these connections more.

**Comment by fabianvf** [comment]
That would be very interesting. I have some plans to improve the elastic search models, but I am pretty busy with SHARE atm so if anyone else wanted to tackle it, I'd be happy to provide some guidance. I don't think it would be very hard. Once the information is in elasticsearch, building these types of visualizations/interfaces becomes much more doable.

**Comment by caneruguz** [comment]
@lbanner @GaryKriebel can we revisit this issue to see if any action can be taken?  It seems to be going into an undirected discussion but we need to move on. It seems to me these are not issues we are discussing anymore but revisions and features.

**Comment by GaryKriebel** [comment]
@erinmayhood should be brought into this discussion as well.

**Comment by lbanner** [comment]
This one is definitely an 'enhancement' -- not 'UI,' I think -

**Comment by erinmayhood** [comment]
@lbanner Currently I can perform a search, see suggested tags to improve my search, and successfully add those tags to my search. I agree with @caneruguz that we should move on from this particular discussion because the next steps would be adding significant functionality in addition to UI changes. 

I'd like to do a UX assessment of Browse, Search, and Explore, while reviewing the Interactive Project Outline Proposal which is also to trying to address discovery (although on a project/component level). Can we add Discovery as a suggested item on the Epic Preparation list for consideration? If it becomes a priority I'll work with Community on requirements and circle back around with elastic search folks on potential next steps.

**Comment by lbanner** [comment]
:+1: Closing this in favor of larger discussion. Thanks.
