### ISSUE TITLE
Word doc file rendering

### ISSUE THREAD

**Issue by TimErrington** [CenterForOpenScience/osf.io#980]
The file rendering for this file (https://osf.io/z3ma2/) does not display the header or text box that is found in the file when you download it, only the main text content.

**Comment by sloria** [comment]
@TimErrington That file seems to have been deleted. Can this issue be closed?

**Comment by TimErrington** [comment]
Here's a similar file with the same issue. https://osf.io/2perh/

**Comment by sloria** [comment]
Thanks @TimErrington . I've reported an issue on the pydocx tracker.

**Comment by samanehsan** [comment]
Closing this issue here since it's been reported on the pydocx tracker.
