### ISSUE TITLE
Confusing if you try to log in while logged in

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#982]
What I did
---
1. Log out of OSF
2. Open two tabs at the login page
3. Log in on one tab
4. Log into a different account on the second tab

What I would expect
---
There would be an error that says, "You are already logged in as \<username\>. Please log out first."

What happened
----
It took me to the dashboard for the already logged in user

Alternate solution
----
It logs out the initial user and logs in the second user.

This happens on staging and production. It's not a security issue as near as I can tell, because you don't have any access you wouldn't have had by just clicking on the home link, but it can certainly be confusing.

**Comment by HarryRybacki** [comment]
@huangginny @JeffSpies any updates on this? I didn't see any PRs mentioning this issue.

**Comment by lbanner** [comment]
@HarryRybacki @huangginny had submitted #1015 and referenced this, but I am uncertain whether all questions were resolved. I can help you followup.

**Comment by huangginny** [comment]
@HarryRybacki I think my pr is still in the old osf repository, not in the osf.io one :8ball:  I'll check it out

**Comment by HarryRybacki** [comment]
Thanks!

On Mon, Feb 23, 2015 at 9:16 AM, Ginny <notifications@github.com> wrote:

> @HarryRybacki <https://github.com/HarryRybacki> I think my pr is still in
> the old osf repository, not in the osf.io one [image: :8ball:] I'll check
> it out
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/issues/982#issuecomment-75547302>
> .
>



-- 
*Harry Rybacki* - Developer, Center for Open Science
Research: http://scinet.osf.io
Blog: http://rybacki.io
[image: http://github.com/harryrybacki]
<http://github.com/HarryRybacki> [image:
https://twitter.com/HarryRybacki] <https://twitter.com/HarryRybacki> [image:
http://www.linkedin.com/in/HarryRybacki/]
<http://www.linkedin.com/in/HarryRybacki/> [image:
https://plus.google.com/+HarryRybacki]
<https://plus.google.com/+HarryRybacki>

**Comment by huangginny** [comment]
@HarryRybacki CenterForOpenScience/osf#1015

**Comment by Ghalko** [comment]
Recreated Ginny's changes. Logs in second person after logging out 1st. Should I submit a PR? Any more comments?

**Comment by lbanner** [comment]
Updated #1015 @Ghalko ? Yes, looks like consensus and other practice says go with   'Logs in second person after logging out 1st.'

**Comment by sloria** [comment]
@brianjgeiger Does this issue still exist with the latest integration of SSO/CAS?

**Comment by brianjgeiger** [comment]
Yes, it works with the alternate solution given above. Much better.
