### ISSUE TITLE
Dropbox storage add-on requires constant manual reauthorization

### ISSUE THREAD

**Issue by richardarsenault** [CenterForOpenScience/osf.io#9932]
Hi,

I am having a problem with the authorization of a Dropbox add-on. I think I have identified the problem, but I am not nearly competent enough to provide a PR to help solve the problem. 

Dropbox has recently (~March 2022) migrated form a long-lived access token to a refresh token for authorization. Therefore, new Dropbox authorizations are short-lived and must be manually re-authorized multiple times a day, when the tokens expire. It seems refresh tokens need to be added to the code to ensure permanent access to the data. Authorizations that were created with long-lived tokens are still working, so only new authorizations are concerned. In my case, I have 4 projects I need to keep updated by manually re-authorizing access through the settings --> Add-ons.

More information is available here:
https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Unable-to-get-long-lived-access-tokens/td-p/585450

and also here:
https://www.dropboxforum.com/t5/Discuss-Dropbox-Developer-API/Need-Permanant-Access-token-for-drop-box/td-p/583956

I am unable to help solve this problem but I figured I'd at least let the community know about a potentially important issue.

Thanks,

**Comment by mfraezz** [comment]
Hi @richardarsenault,

Thanks for bringing this to our attention. 

I've written and tested a fix for this issue, it should be deployed within a couple hours. Once it's out, you'll need to reauthorize the Dropbox add-on via your user settings once more, after which OSF will use refresh tokens to keep the credentials alive. 

I'll follow-up again here after it's deployed and confirmed to be fixed on production.

**Comment by mfraezz** [comment]
The fix for this issue is now live, and reauthorizing on https://osf.io/settings/addons/ once more should resolve this for you. I've verified it on my account, but feel free to reopen this issue if you find any unexpected behavior with it. :octocat:

**Comment by richardarsenault** [comment]
Thanks a lot @mfraezz, the fix has been working perfectly!
