### ISSUE TITLE
[production] deleting a file and re-uploading with the same name does not update file rendering

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#995]
I recently deleted a file, userdata.txt, from a project (xcsi9). When I then uploaded a file with different contents but the same name, the rendered file on the OSF did not update. Hard refresh did not change this. Instead of seeing the new contents (which read "teehee") I saw the old contents of the file. 

I tried this several times and the original version was always displayed as the rendered file, no matter how many times I refreshed. 

When I updated the new file to a second version, however, the rendering was updated to version two. This suggests that version one of a file with the same name as a deleted file will not update the rendering, but that subsequent versions will.

**Comment by nanchen47** [comment]
@caileyfitz has verified that this is no longer an issue on production.
