### ISSUE TITLE
Wiki edit page tab order is wrong

### ISSUE THREAD

**Issue by lyndsysimon** [CenterForOpenScience/osf.io#997]
When editting a wiki page, pressing tab takes you out of the textarea and moves focus to the *Cancel* button. Most of the time, the user will be wanting to move to the *Save* button, so it should be the first highlighted.

# Steps to reproduce

1. Edit a wiki page, and make some changes
1. Press tab

# What happens now

The *Cancel* button recieves focus.

# What should happen

The *Save* button should recieve focus.

# Suggested fix

Set the `tabindex` property of the textarea, *Save*, and *Cancel* buttons to tab in the correct order.

[Reference link](http://www.html5tothepoint.com/tabindex.htm)

**Comment by lbanner** [comment]
@brianjgeiger And this one -- Does your new Wiki work overcome any issue here?

**Comment by brianjgeiger** [comment]
Not my changes, but the last round. The current editor captures tabs rather than using it to navigate to other components, so this is not a thing anymore. Capturing the tab may negatively impact accessibility, however, and we should probably look into that.

**Comment by lbanner** [comment]
Thank you -
