### ISSUE TITLE
Add filters to "Watched Projects" feed

### ISSUE THREAD

**Issue by lyndsysimon** [CenterForOpenScience/osf.io#998]
Imported from CenterforOpenScience/osf#85

Additional comments are present but were not imported.

-----

By @sloria:

> Currently, every logged event for every watched project is shown in the feed. This leads to active projects dominating the feed.

> This raises questions:

> * Should we set up a filtering system for the feed?
* If so, which event types should be shown?
* Should the filtering be configurable? If so, how will the user configure it?
* How granular should configuration be? (e.g. "I want to hide all wiki changes from the feed" vs. "I want to hide all wiki changes for project Foo but still want to see wiki changes for project Bar")

**Comment by erinmayhood** [comment]
Addressed in dashboard redesign.
